### ISSUE TITLE
[Bug] v1.2.6.15 Binance trading_apiKey incorrect data

### ISSUE THREAD

**Issue by draggy** [taniman/profit-trailer#1001]
I just tried the new version (v1.2.6.15 Bug fixes (REUPLOADED)) and it is saying:
`ERROR Application - Please fix: trading_apiKey -- We got incorrect data, retrying`

application.properties has not changed, and I double checked the trading_apiKey key. I reverted back to v1.2.6.14 and it has no issues with the same config files.

I'm using Binance as my exchange, java 8, Debian 8. The trading key is restricted to my server's ip and trading rights.

**Comment by YoJeff** [comment]
The ongoing Binance struggles are real, known, and already have existing issues.

**Comment by ksteigerwald** [comment]
Could you post those tickets. I am having the same issue as @draggy

**Comment by draggy** [comment]
v1.2.6.16 also has this issue fyi

**Comment by vinz0380** [comment]
same issue here.

**Comment by draggy** [comment]
@YoJeff can we please get some update or linked tickets. This bug happens with v1.2.6.15, v1.2.6.16, and v1.2.6.17. I have even tried a different trading_apiKey and got the same result. Why do some people have no issues with Binance and these versions and some of us have this error?

**Comment by taniman** [comment]
@draggy there is nothing to update. If your bot does not start you need to check the reason on your end. If you have a slow connection than yes. the bot will not start up if it receives a timeout. There can be multiple other reasons. 

Send me your log files and I will look if it's something other than a connection timeout on your end

**Comment by draggy** [comment]
@taniman I did find the error in the logs:
`2018-02-16 12:39:37 INFO Application - PT Version: 1.2.6.17
2018-02-16 12:39:37 INFO Application - Java Version: 1.8.0_131
2018-02-16 12:39:39 DEBUG a - value {"validLicense":"true","exchange":"BINANCE"}
2018-02-16 12:39:39 DEBUG Application - {"validLicense":"true","exchange":"BINANCE"}
2018-02-16 12:39:39 DEBUG Application - Key: - Exchange BINANCE
2018-02-16 12:40:04 DEBUG ProfitTrailerService - Error in reading response sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2018-02-16 12:40:04 DEBUG ProfitTrailerService - nl.komtek.pt.utils.c: We got incorrect data, retrying`

This started happening in v1.2.6.15 as v1.2.6.14 starts up fine. This is on a vps so no slowness should happen. OS is Debian Jessie x64.

**Comment by YoJeff** [comment]
That looks like the problem is your cert.    Perhaps a self-signed cert.

**Comment by draggy** [comment]
I have a valid letsencrypt cert on my running config, but I removed it from the config for testing. I am using a completely clean unzip of the latest PT, I have only changed the application.properties to include my api keys and it gives me the above error.

**Comment by YoJeff** [comment]
Somethings is screwed up with your cert chain or cert store then.

**Comment by taniman** [comment]
draggy this happens because we use a stricter SSL certificate check. And seems like your ca-certificates-java is out of date for some reason. 

Try to update this on your system or try reinstalling your java which should normally update the certificate store too

**Comment by draggy** [comment]
ty @taniman I reinstalled java and now everything works, including my letsencrypt cert. Here's the steps that I did on my debian 8 vps:
`# apt-get remove openjdk-8-jdk --purge
# apt-get autoremove --purge
# reboot now
# apt-get update
# apt-get dist-upgrade
# apt-get install -t jessie-backports openjdk-8-jdk`

**Comment by taniman** [comment]
Yes!
