### ISSUE TITLE
[Feature] Trading folder configuration variable

### ISSUE THREAD

**Issue by aries-delossantos** [taniman/profit-trailer#1002]
I think it is better if we can switch trading config directory instantly by a variable set somewhere maybe `configuration.properties`?

**Comment by tooraj-enayati** [comment]
Yes, this would be great. We could switch between different configurations on the fly.

**Comment by innerpartycolt** [comment]
I'm not sure about switching, but importing configs (last one overrides the previous) would be awesome. This would save a lot of time.

**Comment by YoJeff** [comment]
trading configs are online/encrypted now.

If any/all of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
