### ISSUE TITLE
[ Feature ] - manual sell button in the pairs log...seeing as binance triggers dont work.

### ISSUE THREAD

**Issue by WesNz** [taniman/profit-trailer#1003]
as the title says...put a manual sell button in the pairs log next to each trade/currency

**Comment by ruudwelten** [comment]
@WesNz Please search through the existing issues before posting a new one: https://github.com/taniman/profit-trailer/issues?utf8=%E2%9C%93&q=sell+button

**Comment by YoJeff** [comment]
Dup

**Comment by WesNz** [comment]
Cool..searched..mayjor request ...multiple times ....nothing done...got it thanks.
