### ISSUE TITLE
[Feature Request] Variable Traling_Buy rates per Buy_Trigger

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer#1004]
Anything in the pipeline or is there any way to set a unique trail for each DCA level?
Such as: 
buy_trigger_1_trailing_buy = 0.3
buy_trigger_2_trailing_buy = 0.5
buy_trigger_3_trailing_buy = 1
etc?

I think this would make the trailing feature more powerful and effective for various market types?

**Comment by ruudwelten** [comment]
In the pipeline for v1.2.7: #222

**Comment by YoJeff** [comment]
Duplicate #222
