### ISSUE TITLE
[Bug] ETH trading Monitoring view on mobile shows price for BTC 

### ISSUE THREAD

**Issue by sroberson** [taniman/profit-trailer#1005]
If you're on mobile and you're looking at a bot that's trading ETH, the base-coin price is showing the price for BTC, not ETH.

![screenshot_20180206-092854](https://user-images.githubusercontent.com/107141/35866800-16e9581e-0b26-11e8-870d-b6b25eea4e07.png)

**Comment by YoJeff** [comment]
Dup #424
