### ISSUE TITLE
BTC Percentage indicator 

### ISSUE THREAD

**Issue by cupid-stunt** [taniman/profit-trailer#1007]
BTC percentage indicator (in the Monitoring screen) shows -4.53% while all the major exchanges are showing a positive figure. Dollar value is similar to the exchange!

**Comment by YoJeff** [comment]
gui just shows what coinmarketcap.com shows, not your exchange.

**Comment by cupid-stunt** [comment]
Just refreshed the bot and Coinmarketcap shows -4.67% and the bot is showing -3.38 for BTC. Binance was showing +1.6.

**Comment by YoJeff** [comment]
Looks like coinmarketcap isn't used anymore.    Check the value of USDT/BTC pair on your particular exchange.     It looks good on mine.   Keep in mind these are polled numbers, not realtime -- so they lag a little.
