### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gainmedia** [taniman/profit-trailer#1009]
Hi, is it possible to expand the strategy almost like with gunbot ? I am thinking that more indicators could make for  better target market. It would be really nice if there was the possibility to choose between multiple strategies, such as Stochastics, RS and Feva indicators, basically in conjunction with the api in the exchanges. 

thanks for your time.

**Comment by YoJeff** [comment]
There are several existing issues for more indicators -- please participate in those.

#82, #370, etc, etc.
