### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chrismlogan** [taniman/profit-trailer#1010]
It'd be nice to automatically sort the PBL by placing the true trailing coins atop any of the others regardless of the sort options...

**Comment by YoJeff** [comment]
An option to sort by trailing would be interesting, if short lived.

Assuming everybody wants it sorted this way is presumptuous.

**Comment by chrismlogan** [comment]
Didn’t mean to assume everyone’s preference... with my (little) experience with it im most interested in the very few that it is actively looking to buy and am scrolling through the false to find it... just a thought.. thanks!

**Comment by YoJeff** [comment]
It's not a bad idea for those who pine over their buy logs.    Personally I sort by current value which accomplishes virtually the same thing.
