### ISSUE TITLE
BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read - v1.2.6.15

### ISSUE THREAD

**Issue by tarekmty** [taniman/profit-trailer#1011]
Bot is like watch only mode watch coins and trailing buy but not buying anything

2018-02-07 07:00:15 ERROR BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read

ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message Error in reading response Read timed out, message [{"e":"24hrTicker","E":1517958926572,"s":"ETHBTC","p":"0.00049100","P":"0.487","w":"0.09887356","x":"0.10086000","c":"0.10136500","Q":"0.01000000","b":"0.10127100","B":"0.53700000","a":"0.10136500","A":"1.06200000","o":"0.10087400","h":"0.10228300","l":"0.09443100","v":"222702.71300000","q":"22019.41073956","O":1517872526568,"C":1517958926568,"F":30743357,"L":31402002,"n":65864

**Comment by YoJeff** [comment]
Duplicate ^ 5

**Comment by pepps1976** [comment]
I am also having this issue did you resolve it?
