### ISSUE TITLE
Monitor showing Config: "On" although settings are set to false.

### ISSUE THREAD

**Issue by Legedric** [taniman/profit-trailer#1013]
Hey guys,

so I have set my hotConfig to fales as you can see here:
![image](https://user-images.githubusercontent.com/8308141/35906185-e3aaab96-0be9-11e8-9d6c-36e19abf74ab.png)

But the monitor doesn't recognize it somehow:
![image](https://user-images.githubusercontent.com/8308141/35906162-d58648fe-0be9-11e8-8bf2-2333f67b02fe.png)

However, when I comment the config line like this (or when I remove the line):
![image](https://user-images.githubusercontent.com/8308141/35906242-1a4dd434-0bea-11e8-805b-e11e14f1d049.png)

The monitor does recognize it correctly:
![image](https://user-images.githubusercontent.com/8308141/35906227-0e072b8a-0bea-11e8-98e8-feff54a5eba1.png)

So I guess the monitor is just looking for a line starting with "server.enableConfig" and disregards the actual value once it was found.

/edit: The menu entry for the HotConfig is NOT visible anyway so it is only the display within the top bar that seems to have that issue.

**Comment by YoJeff** [comment]
This looks like a one off, or a duplicate configuration -- closing for now.   Re-open with full application.properties (remove keys) if still an issue.
