### ISSUE TITLE
DCA_enabled = false - Causing pairs that are already in DCA 1+ to get moved to Pairs log and not showing DCA level in Sales Log.

### ISSUE THREAD

**Issue by Legedric** [taniman/profit-trailer#1014]
So here is my issue.

Yesterday I had several bags in my DCA log and my automated setting tool (similar to Feeder) set some coins to "DCA_enabled = false".

When it does that, they get moved from DCA log to Pairs log, no matter if they already got DCA'd or not.
In addition, when it sells one of these coins the column "Bough price" is just listing the plain price, without its DCA level like this:
![image](https://user-images.githubusercontent.com/8308141/35906622-81abad94-0beb-11e8-93a8-9aedb8370fc3.png)

This seems to be a bit inconsistent as when I set DCA_enabled to lets say -100 (which pretty much equals false) it will NOT move coins that got already DCA'd back into Pairs Log and lists the DCA level correct in my Sales Log.

I know that setting it to false disabled DCA. But it should follow the same rule so that any coin that already is in DCA 1 or more, will stay in DCA log and just won't go further down.

**Comment by YoJeff** [comment]
Should it?  Or is this a mechanism to 'reset' the DCA counter.   I'm not certain myself.

> This seems to be a bit inconsistent as when I set DCA_enabled to lets say -100 (which pretty much equals false) 

Functionally equivalent is not equal.   I don't see this as an inconsistancy since the coins are still 'eligible' for DCA.

**Comment by Macflurry26** [comment]
From what I've gathered from using it, I may be wrong, when you go back to DCA_enabled = false everything goes back to the pairs log so they can be treated by the normal pairs buy/sell rules.  You should see that your average bought price still reflects the DCA'd average but there is no reference to the DCA levels as you have told the bot to treat everything like a standard pair.

If you still want the DCA info to show for specific pairs but don't want anything to buy more then use DCA_enabled = false but also enable DCA for the specific pairs with something like FUNBTC_DCA_enabled = true in your pairs file.  Then set your max_buy-times to 1.  As you've already DCA'd the pairs this will stop them buying more but still show all the relevant info.

Then set your DCA sell strategy to match your standard pairs ones so they are treated the same for sales if that is what you are after.

**Comment by Macflurry26** [comment]
> when I set DCA_enabled to lets say -100 (which pretty much equals false) it will NOT move coins that got already DCA'd back into Pairs Log.
> 
I think when you enable DCA to -100, pairs that have never DCA'd will only be moved over once they hit the -100 level but as you have pairs that have already DCA'd then they are moved back to the DCA log as they have historic DCA actions against that pair.

If you're looking to turn off DCA but keep the info then you need to try what I said above to disable DCA everywhere but enable if for the pairs you want to retain the info for and drop the max buys so it doesn't buy any further.

**Comment by Legedric** [comment]
@Macflurry26 The thing is, the DCA_enabled = false is getting set by a feeder-like tool. So it is an automated to protect myself from buying deeper into risky coins for example during an obvious Pump.

So disabling DCA in general and enabling it for only single pairs will not solve this particular problem.

I mean, it is ok for me to just set it to -100 instead of "false" to get the result I prefer here but it still doesn't seem logic to me. My logic is: If a coin got into DCA atleast by one level, it should never return to Pairs Log, no matter what.
Of course there may be different opinions about this :)

**Comment by YoJeff** [comment]
Never say never.   People may want to unDCA a coin.

**Comment by taniman** [comment]
@Legedric If a coin in in DCA log it will get DCA'd  unless it reached it's limit.
So if a coin has not reached it's limit and I don't want it to DCA anymore what do I do??

Answer: I Disable DCA for this particular coin. and let it go to pairs log.

The logic is consistent. pairs in DCA log get dca'd, pairs not in DCA log will not get DCA'd
I am not seeing any confusion here.

If we do as you suggest and leave them there, but they not get DCA, THAT will create confusion.

```My coin is in DCA log but it's not buying anything```

So all in all, currently this is not something that will change.

**Comment by Legedric** [comment]
Ok I got that and I agree it will cause more confusion if you change it.
