### ISSUE TITLE
"SOM: true" (Triggered by price rise)

### ISSUE THREAD

**Issue by MindWallet** [taniman/profit-trailer#1016]
Hello all,

I just bought PT yesterday and am reading up on it and watching videos. I got my monitor to function, but between "password: on" and "FOMO: false" I have "SOM: true" in red. I assume that SOM has to be turned to "false", but how do I do this? I have googled and everything but am at a loss. If it helps, these are som of my settings:

//Configuration:

sell_fillOrKill = false
sell_immediateOrCancel = true

#buy options
buy_fillOrKill = false
buy_immediateOrCancel = true

hideDust = true

testMode=false

BTC_dust = 0.00201

//Pairs

MARKET = BTC

ALL_trading_enabled = false
ALL_enabled_pairs = LTCBTC, ETHBTC, XMRBTC, TRXBTC, XRPBTC, ADABTC, NEOBTC

**Comment by YoJeff** [comment]
Please use support this is for bugs only.

**Comment by MindWallet** [comment]
Oh, goodness, did not think about that. Sorry
