### ISSUE TITLE
feature request: display values in satoshi / mbtc

### ISSUE THREAD

**Issue by gadh** [taniman/profit-trailer#1017]
all values in monitor that are currently displayed in BTC (btc market) - support in configuration to display them in satoshi/mbtc

**Comment by taniman** [comment]
why?

**Comment by gadh** [comment]
its hard to read all those zeros like 0.00023 profit

**Comment by taniman** [comment]
will this requires a lot of thinkering. maybe someone can create a script for this. i will put it on low priority

**Comment by cryptomail2018** [comment]
there is a addon you can place and it actualy shows dollar value which makes more sense , so this way Gents like Taniman can focus on other stuff and with this little app which works great you get a fantastic indication on a dollar value profit and or trade .

**Comment by gadh** [comment]
tnx but dollar  values tend to change by the market so if the trade is in btc so i think it would be reasonable to display in mbtc/satoshi

**Comment by JediWed** [comment]
bits please
1 btc = 1,000,000.00 bits

**Comment by taniman** [comment]
adding to the enhancements github
