### ISSUE TITLE
feature request: display monitor values in precentage of whole assets

### ISSUE THREAD

**Issue by gadh** [taniman/profit-trailer#1018]
instead of just in BTC/ETH - display the profit/current value/week profit/day profit - in USD but also configurable - in percentage of your total coins assets (0.14 btc / profit 0.002 btc = 1.5% profit and so on)

**Comment by YoJeff** [comment]
Percentage is good, especially since this whole game is percentages.

**Comment by blockheadbits** [comment]
Percentage Addon Here - https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons

**Comment by djcrypto75** [comment]
on roadmap
