### ISSUE TITLE
Enhancement to Buy/Sell engine: Add additional indicators

### ISSUE THREAD

**Issue by iAmVaeVictus** [taniman/profit-trailer#102]
It would be very powerful to add a secondary or tertiary indicator to assist in the buy sell decisions. Example, in addition to hitting a HighBB 0% value, a secondary indicator of volume (Like Intraday Intensity%), AD%, MFI would give you a positive, negative or neutral indication. Based on the result of that, we could either sell (negative indication) or hold (neutral), or even buy more (positive, or certainly hold our position because the price will likely continue to increase).  

These 3 indicators work very well with BB. 

**AD% Calculation**
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:accumulation_distribution_line
1. Money Flow Multiplier = [(Close  -  Low) - (High - Close)] /(High - Low) 
2. Money Flow Volume = Money Flow Multiplier x Volume for the Period
3. ADL = Previous ADL + Current Period's Money Flow Volume

**II% Calculation**
http://www.investopedia.com/terms/i/intradayintensityindex.asp
II% = (2 x close - high - low) / ((high - low) * volume)

**MFI Calculation**
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:money_flow_index_mfi
Typical Price = (High + Low + Close)/3
Raw Money Flow = Typical Price x Volume
Money Flow Ratio = (14-period Positive Money Flow)/(14-period Negative Money Flow)
Money Flow Index = 100 - 100/(1 + Money Flow Ratio)

You would have flags to turn these indicators on or off

BB_II_indicator = true
BB_MFI_indicator = true
BB_AD_indicator = true

Then you would have settings around each indicator

Examples: 
- II% - if positive buy volume is true then + signal. If negative buy volume is true, then - signal. If neutral then == signal. We would set the levels for Positive, neutral, and negative to suit our parameters, with some defaults defined. 

- AD% - (from the link above) As with all indicators, it is important to use the Accumulation Distribution Line in conjunction with other aspects of technical analysis, such as momentum oscillators and chart patterns. It is not a standalone indicator. The Accumulation Distribution Line is a cumulative measure of each period's volume flow, or money flow. A high positive multiplier combined with high volume shows strong buying pressure that pushes the indicator higher. Conversely, a low negative number combined with high volume reflects strong selling pressure that pushes the indicator lower. Money Flow Volume accumulates to form a line that either confirms or contradicts the underlying price trend. In this regard, the indicator is used to either reinforce the underlying trend or cast doubts on its sustainability. An uptrend in prices with a downtrend in the Accumulation Distribution Line suggests underlying selling pressure (distribution) that could foreshadow a bearish reversal on the price chart. A downtrend in prices with an uptrend in the Accumulation Distribution Line indicate underlying buying pressure (accumulation) that could foreshadow a bullish reversal in prices.

- MFI - (from the link above) Overbought and oversold levels can be used to identify unsustainable price extremes. Typically, MFI above 80 is considered overbought and MFI below 20 is considered oversold. Strong trends can present a problem for these classic overbought and oversold levels. MFI can become overbought (>80) and prices can simply continue higher when the uptrend is strong. Conversely, MFI can become oversold (<20) and prices can simply continue lower when the downtrend is strong. Quong and Soudack recommended expanding these extremes to further qualify signals. A move above 90 is truly overbought and a move below 10 is truly oversold. Moves above 90 and below 10 are rare occurrences that suggest a price move is unsustainable. Admittedly, many stocks will trade for a long time without reaching the 90/10 extremes. However, chartists can use the StockCharts.com scan engine to find those that do. Links to such scans are provided at the end of this article.

**Comment by taniman** [comment]
A similar issue already exists. And I will start with that one as it is less complicated. i will ofcourse look into adding more indicators soon
