### ISSUE TITLE
PT problem! buy a coin when it pumping too much (24h) and dumping too much (24h)

### ISSUE THREAD

**Issue by quochuyonnet** [taniman/profit-trailer#1020]
Guy! Please make a setting for PT that do not buy a coin when it pumping too much (24h).
And dumping too much (24h)
These days many coin are used for speculation, they pumping it 30 ~ 50%, even 100 ~ 200%, then dump it and runaway, the result is PT bought a full bag of that coin and we're never can sell it for profit...!!!
my PT holding a pump dump coin now @_@, heavy bag with 6 times DCA buying and that coin still going down with very low price !!!

**Comment by YoJeff** [comment]
#1008 dup.  again.
