### ISSUE TITLE
Total Pending Value is extremely high

### ISSUE THREAD

**Issue by techbit2** [taniman/profit-trailer#1021]
I have just set up my profit trailer and noticed that my total pending value is around 9.8 BTC which is incorrect, my actual total balance in Binance is 0.89 BTC

Am using the bot in binance only, please check my screen shots
<img width="1067" alt="screen shot 2018-02-07 at 8 43 07 pm" src="https://user-images.githubusercontent.com/35068162/35928906-bfe55630-0c47-11e8-9154-c1a8795a0f88.png">
<img width="707" alt="screen shot 2018-02-07 at 8 43 41 pm" src="https://user-images.githubusercontent.com/35068162/35928920-c79106b8-0c47-11e8-860e-ff23aad95839.png">

**Comment by YoJeff** [comment]
What's the pending page detail / total look like?

**Comment by techbit2** [comment]
<img width="1143" alt="screen shot 2018-02-07 at 9 47 19 pm" src="https://user-images.githubusercontent.com/35068162/35932199-86089360-0c50-11e8-870d-72f3c2651767.png">

**Comment by YoJeff** [comment]
Ok, this is by design.  Pending shows the total "pending" value.   Meaning if they sell.   At the prices you have them listed.   And your prices are x20.
