### ISSUE TITLE
[Feature Request] buy_trigger for EMASPREAD and EMAGAIN strategy in DCA

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1023]
Could you add buy_triggers to EMASPREAD and EMAGAIN, so we could use those strategies in the DCA?

**Comment by YoJeff** [comment]
Currently supported DCA buy strategies from wiki:

The strategy to use to buy more coins. The available options are:

LOWBB
HIGHBB
ANDERSON
EMASPREAD
EMAGAIN
SMASPREAD
SMAGAIN
LOSS

**Comment by alexdolli** [comment]
I know that, but EMAGAIN for example doesn't go by the buy_triggers. It immediately starts tracking, regardless of the percentage triggers you've set...
