### ISSUE TITLE
More coin-specific settings

### ISSUE THREAD

**Issue by orangebutblue** [taniman/profit-trailer#1024]
In accordance with this feature-request (https://github.com/taniman/profit-trailer/issues/222) that refers to coin-specific-values in the DCA-file, I wanted to ask for even more coin-specific settings in future versions. Namely, being able to set trailing_profit for each coin, instead of having a general value for all coins,
Some coins are generally more unstable than others, and therefore require bigger trailing-values.

(this setting applies both to DCA and PAIRS)

**Comment by YoJeff** [comment]
Add your suggestion to that existing issue please.
