### ISSUE TITLE
[Feature Request] Robinhood support

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1026]
I know, this is probably far fetched, but could you add support for Robinhood? They have an API feature.
I'd buy that license in a heartbeat!

**Comment by orangebutblue** [comment]
they haven't even officially launched their crypto-exchange

**Comment by alexdolli** [comment]
I meant for the stock market... think about it ;)

**Comment by swoopsus** [comment]
I like it! Id like more markets in general
