### ISSUE TITLE
Please check your VPS / PT connection

### ISSUE THREAD

**Issue by crptoguru** [taniman/profit-trailer#1027]
I'm unable to connect can someone please help?
![screen shot 2018-02-07 at 5 43 46 pm](https://user-images.githubusercontent.com/36247341/35945574-aed82034-0c2e-11e8-859d-a5213b7ee79a.png)

**Comment by cristianserban** [comment]
what version of the bot are you running?
what os ? 
vps ?

**Comment by YoJeff** [comment]
This is for bugs, please use support.

**Comment by crptoguru** [comment]
not sure how to pull up the version number but i got it from the wiki so
it's the latest version. Im using Windows VPS server 2012 from Virmach

**Comment by crptoguru** [comment]
just launched the cmd file & it says version 1.5.4

**Comment by crptoguru** [comment]
java version is 8U161
