### ISSUE TITLE
Buy issue on binance

### ISSUE THREAD

**Issue by leoneparise** [taniman/profit-trailer#1028]
I'm getting this message pretty often:

```
Binance api is having issues serious issues again. We might block some buys.
Error occured in buy, message null, result
Something is really wrong
```

Is someone experiencing the same issue? I'm using the latest version of ProfitTrailer.

**Comment by ssll88** [comment]
Yep i have the same problem...

**Comment by Mantexas** [comment]
same here

**Comment by Mr760** [comment]
I just got my PT started and no buys... nothing just the same Error message. So now what. I have $50 in my Binance account just to play with before I put larger amounts.

**Comment by erknie** [comment]
I had a sell issue on Binance about 20min ago with the same error.
PT placed a sell for some DGD,  the sale went through then the error came up.
Now it says there is not enough DGD to sell, but the  Pairs Log is still showing the same DGD balance before it was sold. It looks like PT has a corruption in it's database for DGD now, and I don't know how to fix it to make the phantom coins go away.

**Comment by Icantknowhow** [comment]
Same issue here also on Binance all outta whack... error messages and info not transferring, says something serious wrong

**Comment by Icantknowhow** [comment]
Binance system maintainence note @Binance on Twitter
Shut down PT and wait for update from Binance on when they are completed.

**Comment by erknie** [comment]
https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension

**Comment by erknie** [comment]
From their twitter feed

> We experienced a server issue on our replica database cluster, causing some data to be out of sync. Need to fully resync from master. Due the size of the data, it will take several hours. No data is lost. We appreciate your understanding and support.

**Comment by cristianserban** [comment]
https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension
