### ISSUE TITLE
Binance Error - "[x number] prices seem to be stagnant . . . did the bot hang?"

### ISSUE THREAD

**Issue by blockheadbits** [taniman/profit-trailer#1030]
Receiving constant error saying "[x number] prices seem to be stagnant . . . did the bot hang?"

I'm using Binance.  Have tried 1.2.6.15, then rolled back to both 1.2.6.13 and 1.2.6.10.  Getting the same error on all versions.  

Any idea what is going on?  Bot is basically unusable on Binance at this point and I'm feeling a little scammed here.

**Comment by hristoitchov** [comment]
Seems to be a Binance issue, judging from comments on other posts, plus their maintenance tweet an hour ago. I wonder though if and how we'll know when all is back to normal, and whether we should just let the bot run or not during this period.

**Comment by erknie** [comment]
If you login to your account on Binance, you will see your Estimated Value of your balances doesn't update either. Their exchange is effectively down for maintenance even though some bits still operate.

**Comment by cristianserban** [comment]
https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension
