### ISSUE TITLE
BTC USD Price showing as 0.00 (0.00%), Binance

### ISSUE THREAD

**Issue by orionmodern** [taniman/profit-trailer#1031]
Hi anyone else having this issue? BTC USD Price showing as 0.00 (0.00%), Binance
Using pt-feeder-v1.3.5.329 - Build 3

**Comment by erknie** [comment]
Binance is down for maintenance, and there are 3 or 4 threads about this already

**Comment by orionmodern** [comment]
Sorry about that, newbie here. and thank you

**Comment by erknie** [comment]
https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension

**Comment by erknie** [comment]
2PM UTC is like 11.5hours from now, I hope that ETA was a typo!

**Comment by orionmodern** [comment]
yeah i saw that too! should we set out PT into sell only in the meantime or shut it down completely?

**Comment by erknie** [comment]
Latest update from Binance:

> _Still waiting on data copy, it will take a while, another 10 hrs at the current estimate. Due to the unexpected length of time, we will allow 30 mins for people to withdraw orders before trading resumes when system is back._

This outage will cost them over a $billion in lost turnover, they normally do $80-100mill per hour, and it's boring me to tears.

**Comment by orionmodern** [comment]
erknie, any good settings you'd recommend for Profit Trailer?
Also, do you use feeder?

**Comment by cristianserban** [comment]
https://twitter.com/cz_binance
