### ISSUE TITLE
Show the BTC value of each DCA row as a sortable column

### ISSUE THREAD

**Issue by blacksausage** [taniman/profit-trailer#1032]
This is a feature request. It would be very helpful to be able to sort the DCA page by the current value of the bag in BTC. I have different max_buy_values for each coin so it makes it hard to know how deep the bag really is.

**Comment by orionmodern** [comment]
I would like to see this feature as well

**Comment by djcrypto75** [comment]
There is sorting on Current Value.
I dont understand what you want?

**Comment by blacksausage** [comment]
Actually the problem is with your UI layout. It's not responsive. My default browser width does not show the total value column, and there isn't a horizontal scrollbar. So my feature request is to make the monitoring layout responsive or provide a scrollbar so that when columns do not fit within the width they don't just disappear.

**Comment by djcrypto75** [comment]
What resolution are you on? There will be a scrollbar for smaller resolutions in a "soon" version.

**Comment by blacksausage** [comment]
I use a MacBook Pro Retina 2016 with the default settings. I only see the
last column when I use my monitor at home, which is 1920x1080. The laptop
screen resolution is higher than my monitor at home, but I do not see the
last column on my the laptop screen.

**Comment by djcrypto75** [comment]
Macbooks have weird resolutions, i have one myself :)
