### ISSUE TITLE
All values were showing 0, updated to latest, got  IP Ban, now License is coming up invalid

### ISSUE THREAD

**Issue by theMadMonster** [taniman/profit-trailer#1033]
PT was running fine for a long time. I last updated about a month ago. Last trade was around 3PM PST. Got home around 9PM and noticed all 0s. Figured it was a good time to update, so grabbed latest. Dropped my old trading files, application, and config files into the new version and ran. Soon after console was spammed with:
"ERROR ProfitTrailerService - Error occured in ticker, message We got incorrect data, retrying, result:"
Google search suggested an IP ban. So I closed down and waited 20 minutes. Instead of trying the latest version I tried to launch the old version that was working. This told me my license was invalid. I then tried to launch the latest version again, and again console shows invalid license. 

and ideas? 

thanks

**Comment by cristianserban** [comment]
https://twitter.com/cz_binance
