### ISSUE TITLE
Pending Pairs not updating

### ISSUE THREAD

**Issue by mikeseal** [taniman/profit-trailer#1034]
When a PAIR goes into pending.  It looks like the list never gets updated.  Still showing PAIRS that have already been sold.

**Comment by cristianserban** [comment]
if it is on binance check this https://twitter.com/cz_binance

**Comment by mikeseal** [comment]
It is on trex

Mike Seal
07463 725117

________________________________

**Comment by cristianserban** [comment]
they had also some issues ...
