### ISSUE TITLE
Binance PT Error ocurred in tick

### ISSUE THREAD

**Issue by calpage89** [taniman/profit-trailer#1035]
Please help i am a noob. PT has been working fine until i woke up this morning to find ticker error.

**Comment by calpage89** [comment]
![screenshot_20180208-084228](https://user-images.githubusercontent.com/36260187/35963365-67a87c9e-0cac-11e8-83a7-2775224fbbf1.jpg)

**Comment by Alec423** [comment]
It's happening to me too

**Comment by Orang11** [comment]
Guys, its because Binance is down for maintanace right now.  The bot can't connect to the servers as they are down

https://twitter.com/cz_binance

**Comment by calpage89** [comment]
Thanks
