### ISSUE TITLE
[Feature Request] Sell button

### ISSUE THREAD

**Issue by tes724** [taniman/profit-trailer#1037]
Hey

Great trading bot. Keep it up. 

A request to add a "sell" button for each pair to the right of each trading line on the GUI. In case you want to sell right now for any reason or take more profit if posible before a retracement when watching the GUI live.

Regards

**Comment by Dunce001** [comment]
I was just going to request the same exact same thing :)

**Comment by taniman** [comment]
this has been asked like a dozen of times already. this will come in due time.
