### ISSUE TITLE
Bad behavior at Api error

### ISSUE THREAD

**Issue by AzraelTheOne** [taniman/profit-trailer#1040]
If a DCA order is triggered by the PT on Binance or another stock exchange but is not reported back due to API errors on the stock exchange, the error "order not exist" will occur and new orders will be written every second. On 07.02 because of the APi problems with Binance from 00:45 to 00:50 he bought 18 times the same coin until min_buy_balance was reached. If the Api does not report the correct one, the PT should stop his action and either report or wait but do not continue to buy until the Wallet glows!

**Comment by taniman** [comment]
this error was already fixed in version 1.2.6.15. 

so I guess u are still running an old version
