### ISSUE TITLE
Idea: add notifications telegram errors of api

### ISSUE THREAD

**Issue by angelsomar** [taniman/profit-trailer#1041]
Greetings, with the recent events of Binance, it seems important to us to notify the notifications of the bot relevant events, which require an immediate action or at least a more constant attention ex:

Warn about api communication errors (to learn promptly of cases similar to Binance recently)

Notify temporary Baneos (I do not know if in others, but in Binance you are usually banned for 5 minutes the api, but you can receive a ban of up to 3 days which deserves immediate attention and leave manual orders, to try to get out in profit

Notify any event that you consider of attention

Successes

sorry for my English

**Comment by Q-BiC66** [comment]
Not only for API errors but any error. Like forgotten bought_prices. Those coins would just sit there and never get sold if you don't look closely or check your log every day... 
I'm much more interested in errors than in buy/sell notifications...
