### ISSUE TITLE
Error in ticker issue with Binance

### ISSUE THREAD

**Issue by vredirect** [taniman/profit-trailer#1042]
Hi there,

Like many other users, I also had the "Error in ticker issue" issue on Binance's system upgrade extension. I saw you guys already closed a similar issue here:

https://github.com/taniman/profit-trailer/issues/1036?_pjax=%23js-repo-pjax-container

However, in my case my bot inexplicably sold most of my balance (around 75%), despite both my pairs and dca files where configured to leave a minimum of 50% balance.

Of course this was an exceptional event, and probably caused to intermittent API communications on Binance's side, but maybe there's something that can be done to prevent this from happening in the future...

It happened during the night so I wasn't checking, that's why the bot kept for so long insisting on the error...

I am attaching my log file here in case it helps finding out what happened...

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1708428/ProfitTrailer.log)

**Comment by YoJeff** [comment]
The Binance API is down, and before it went down -- it was unpredictable.   This is an unfortunate side effect of getting bad information from binance.    The exchange is still down, and we are well aware of it.

**Comment by vredirect** [comment]
Got it. Thanks for the update. Is it ok to run the bot now so it picks up automatically once Binance is up and running again? Hopefully in a few hours?

**Comment by YoJeff** [comment]
More than a few hours, but sure.

**Comment by vredirect** [comment]
Cool, asked cause it will be during nighttime in my timezone. Thanks!
