### ISSUE TITLE
Estimated usd value = 0

### ISSUE THREAD

**Issue by T79x** [taniman/profit-trailer#1043]
Hey,

I'm having problems with all the est. usd values being zero inside the monitoring panel.

It's been like it nearly 2 days and happened when binance was doing their server work.

For some reason now the pbl log never shows anything even though I never changed anything prior to this problem.

Ibe downgraded, reset, updated, turned off turned on, reset settings, but still can't fix this problem.. 

Any ideas? Thanks!

**Comment by erknie** [comment]
Binance are still doing their server work for at least another 4 hours.

**Comment by T79x** [comment]
Cool thanks erknie
