### ISSUE TITLE
New Binance API for checking system status

### ISSUE THREAD

**Issue by orionmodern** [taniman/profit-trailer#1045]
https://twitter.com/cz_binance/status/961804570211975168

"For API users, we added a new API for checking system status.  Check bottom of this page: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md"

Anyone know if we need to do anything to PT or PTF?

**Comment by erknie** [comment]
The feature will need to be added to PT before it can be used.

I checked it at  https://www.binance.com/wapi/v3/systemStatus.html

and it's currently returning:

> msg | "System maintenance."
> 
> status | 1

**Comment by taniman** [comment]
This new api endpoint  does not affect the bot.

**Comment by erknie** [comment]
It does effect the bot. When the Binance API was down the bot spewed out tons of errors every few seconds into the logs. 

> _2018-02-02 06:41:49 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message Error in reading response connect timed out_

By honoring the new API flag you can prevent this, and log something more sensible that the average user can understand, thus eliminating a wall of support questions.

**Comment by orionmodern** [comment]
Issue is no longer there after binance’s maintenance  was complete
