### ISSUE TITLE
[Bug] Binance - Clicking Coin pairs opens dead links since outage.

### ISSUE THREAD

**Issue by Macflurry26** [taniman/profit-trailer#1047]
Now Binance are back online they appear to have changed their web addresses.

Clicking on the coin pairs opens dead links.  Not sure if this will be temporary or permanent but at present swapping out www.binance to us.binance takes you through to the correct exchange pages to follow the charts.

Are the links created dynamically from the site or are they hard coded into PT?

Example - broken:
https://www.binance.com/trade.html?symbol=EOSBTC

Example - working:
https://us.binance.com/tradeDetail.html?symbol=EOS_BTC

**Comment by YoJeff** [comment]
The outage is temporary.   Binance.com is still the official site.
