### ISSUE TITLE
PT will not connect to Binance

### ISSUE THREAD

**Issue by BigAl013** [taniman/profit-trailer#1049]
www.binance.com does not work anymore, it is now either us.binance.com or kr.binance.com.  Does this affect the bot?

**Comment by JulesBern** [comment]
No. The Bot connects via their API @ api.binance.com

**Comment by PoconoCrypto** [comment]
Workaround is to add the line below to your host file in c:\windows\system32\drivers\etc\hosts 
54.192.27.29   www.binance.com

**Comment by YoJeff** [comment]
This is transient, and further -- a binance issue.
