### ISSUE TITLE
Disabling DCA causes pending sell orders to be created

### ISSUE THREAD

**Issue by swoopsus** [taniman/profit-trailer#1051]
I am using PT Feeder. In certain conditions PT Feeder will disable DCA for a pair. However PT immediately creates sell orders for all pairs that are already in DCA and become disabled. This is problematic because these are now stuck as pending orders. 5 minutes later if market conditions change, PTF will re-enable DCA, but that does not work because they are stuck pending. This makes a key feature of PTF (disabling DCA in adverse market conditions) unusable. 

The feature request is to allow this to be configurable behaviour in PT, or to allow a configured delay to be set before a pending sell order is created.

**Comment by YoJeff** [comment]
Pending is in-fact configurable.   You do not have to use it.    This is for bugs.
