### ISSUE TITLE
Having unique Buy/Sell Strategies assigned to each coin

### ISSUE THREAD

**Issue by CryptoxxG** [taniman/profit-trailer#1052]
There are a variety of coins that the bot trades every day. However each of these coins have their own unique patterns. What might be a good buy strategy for one coin may be a below average strategy for another coin. Not sure if this has been posted before, but having the option to apply unique buy/sell values to specific coins would maximize profitability.

Having the option for users who wish to have more fine tuned settings to apply to each coin.

Example:
ETHBTC_BUY_STRAT= EMAGAIN
ETHBTC_BUY_VALUE= -2
ETHBTC_SELL_STRAT= GAIN
ETHBTC_SELL_VALUE= 1.5

**Comment by taniman** [comment]
not sure you are aware but this is already possible in pairs.properties.
