### ISSUE TITLE
Centos and csf

### ISSUE THREAD

**Issue by tomukaskai** [taniman/profit-trailer#1055]
Hi,
i have problem on Centos 7 vps ans csf installed... If I disable csf, everything works, if csf enabled  erorsrs:
Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
Error occured in CB, message Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive, result: Error in reading response connect timed out
In my opinion something wrog with ports...
So question... which ports are you using for profit-trailer?

**Comment by taniman** [comment]
this place is for issues not for setup

PT ses 443 and whatever port you set as server.port in application.properties default is 8081

so 443 and 8081 (default)

**Comment by tomukaskai** [comment]
centos cpanel  csf 443 opened by default...

**Comment by tomukaskai** [comment]
why "taniman closed this 16 minutes ago" ? it's not solved...

**Comment by taniman** [comment]
because like i said this is not for support. contact our support channel for support. This is for bugs

**Comment by tomukaskai** [comment]
are U fucking kidding me, creating soft on java and even doesn't know which
ports U are ussing? csf it's simple firewall closing ports...

**Comment by tomukaskai** [comment]
and for my client I should explaine that firewall it's stupid? maybe Your
support doesn't know what to do.....
