### ISSUE TITLE
PT 1.2.6.15 Needs restarting for Binance

### ISSUE THREAD

**Issue by BeldarConehead** [taniman/profit-trailer#1056]
PT 1.2.6.15 Needs restarting for Binance. It did this prior to the Binance syncing issue yesterday and continues today. For Binance, 1.2.6.9 is the only stable version I've found, it never needs restarting. With 1.2.6.15 it will run for a few hours and then just stop with no errors in the log files. Mine is running on a Mac with OS 10.13.3. FWIW, I run 1.2.6.15 with Bittrex with no restarting issues, from the same Mac.

**Comment by leoneparise** [comment]
What java version are you using? I'm using on a Ubuntu server and Open JDK 1.8 without any issues.

**Comment by blockheadbits** [comment]
Version 8 Update 162 (build 1.8.0_162-b12) on Win10Pro

**Comment by taniman** [comment]
No need to create an issue for something that is widely known in th discord channel. I even asked everybody to send log files so we could resolve the problem
