### ISSUE TITLE
Constant please set bought price

### ISSUE THREAD

**Issue by lilsou** [taniman/profit-trailer#1057]
Every heartbeat keeps giving a please set XXXETH_bought_price. It does this for several pairs for ETH. Resetting the average price and manually setting the bought price doesn't seem to fix it.
EDIT: saving the line directly to PAIRS seems to have fixed it for now.

**Comment by YoJeff** [comment]
Bugs only please, use support for... support.

**Comment by lilsou** [comment]
It was/ is for support because the bot still doesn't seem to save bought prices. I've had to manually set the bought price for ZRXETH twice now. Unless im missing something here?
