### ISSUE TITLE
Allow multiple triggers of trailing_profit help improve tracking large uploads

### ISSUE THREAD

**Issue by angelsomar** [taniman/profit-trailer#1058]
allow multiple triggers of trailing_profit

example:

ALL_sell_strategy = GAIN
ALL_sell_value = 0.75
ALL_trailing_profit = 0.25

If the price rises by 4%, double the ALL_trailing_profit = 0.50 (you would already be guaranteed + - 3.5% and keep searching)

If the price rises by 8%, double the ALL_trailing_profit = 1.0 (you would already be guaranteed + - 7.5% and keep looking)

  If the price rises by 16%, double the ALL_trailing_profit = 2.0 (you would already be guaranteeing + - 14.0% and keep looking)

It would help those of us who have moderate strategies not to lose opoutunidades of big bullish candles.

Sorry for my English

**Comment by juato4** [comment]
YES PLEASE!!!!!
