### ISSUE TITLE
Empty applications page? 

### ISSUE THREAD

**Issue by shuggiebear1** [taniman/profit-trailer#1060]
I am sure i am doing something wrong. I am a brand new mac user, and a brand new profit trailer user. I have the read the wiki and watched the video set up about a thousand times and now i am at PULL MY HAIR OUT status. So...i have downloaded the bot, i click it open and see the folder, then see the next window that says applications, configurations etc... i go to open the applications folder and it is empty. At first it said I didn't have an application to open file and i should select one...i selected notes...but applications file has nothing on it. I have the correct java 8 going..i downloaded it straight for the wiki..it says 8 in the description . Do i need some kind of secondary party like a winzip to open this file?  I bought a mac because i thought it would make this process so much easier.

**Comment by taniman** [comment]
please join discord and ask for support in the support channels. This page is for bugs
