### ISSUE TITLE
PT not purchasing below lower BB properly, but much further up.

### ISSUE THREAD

**Issue by T79x** [taniman/profit-trailer#1061]
Hey, I'm trying to set PT to purchase below the lower BB, but it's actually purchasing a fair bit above it. 

I am using version 1.2.6.14
These are my settings:

ALL_max_buy_spread = 1

ALL_buy_strategy = LOWBB
ALL_buy_value = -3.3
ALL_trailing_buy = 0.2

ALL_sell_strategy = GAIN
ALL_sell_value = 1.2
ALL_trailing_profit = 0.3

BB_period = 900
BB_sma = 40

I've taken some screenshots with the BB shaded in blue and the actual price that PT purcahsed, so should the purchases be below lower BB not in the middle? Maybe I'm missing some setting?

<img src="https://i.imgur.com/3oggQFa.png"/>

<img src="https://i.imgur.com/LLqLNTb.png"/>

Thanks in advance!

**Comment by taniman** [comment]
unless we know exactly at which point the bot started trailing we cannot tell with certainty that its a buying problem. So disable trailing and check,

If trailing started at first break out of the candle and if kept trialing it will seem like it is buying above the lowbb price but it is infact buying still below the original lowbb line

my suggestion. disable trailing. upgrade to version 16 and try again
