### ISSUE TITLE
Bot cannot buy for DCA on Bittrex

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#1062]
I think most probably the API calls in the bot that query the balance when trying to buy for DCA became outdated.
I started having errors saying "APIKEY_INVALID" and reporting 0 balance when my balance was much higher, and it's not related to settings. I started having these errors about 2 weeks ago, and my pair is still sitting in DCA, because it could never buy at lower price.
I noticed this on Bittrex's Developer's Guide page:
DEPRECATING
Request:
https://bittrex.com/api/v1.1/account/getbalances?apikey=apikey
Maybe PT is still using that way to query the balance.
Can you please double-check?

I already tried everything that support suggested. I changed both of my keys, I installed PT from scratch with no JSON file, I downgraded to versions 12 and 11, and none of those worked.
It must be some change on Bittrex, and you guys need to update the bot.

Thanks.

**Comment by taniman** [comment]
Unless everybody is having this problem it's on you end. Ask someone on support to contact me

**Comment by nstefi** [comment]
@SgtBatten helped me out by remoting in to my PC, and we saw a successful DCA buy without any API Key errors.
I had an API Key error just when I started the bot (after upgrading to version 16):
`Feb 11, 2018 11:27:36 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-02-11 11:30:16 ERROR ProfitTrailerService - Tradehistory - nl.komtek.pt.utils.b: APIKEY_INVALID
2018-02-11 11:31:53 INFO NormalStrategyRunner - API Problems?
2018-02-11 11:37:36 INFO ProfitTrailerService - DCA Heartbeat`
I was told that I can ignore that.
I also saw some API errors later, but not during DCA, here is a screenshot:
![image](https://user-images.githubusercontent.com/6478474/36081018-4276edda-0f67-11e8-9fca-d89b8024b20f.png)

I hope I can ignore those and it will not have problems in future DCA buys.
@SgtBatten identified that I had a mistake in DCA config, the max_cost was too low to cover another buy.

Thanks.

**Comment by geocrypto** [comment]
Nice job. Hopefully I can also get some of that fix.
I have the same issue and have reverted back to a completely stock installation.
DCA properties has max cost = 0.01
What should it be if that was what fixed the Trade History issue above?

**Comment by SgtBatten** [comment]
Geo it should be whatever your desired DCA levels will cost you in total.

So if all max cost in pairs is 0.0025, Max cost in DCA should be:
0.005 for one dca
0.01 for 2 dcas
0.02 for 3 dcas
0.04 for 4 dcas
0.08 for 5 dcas 
Etc etc

You can set it to zero. But if for whatever reason the bot forgets how many times it has already DCAd that can get unexpectedly expensive if it goes though another set of DCA's. I always set a max cost for safety.

**Comment by geocrypto** [comment]
Thanks!
I will have a go with your suggestions to better understand how it works.
Cheers
