### ISSUE TITLE
Trend indicator

### ISSUE THREAD

**Issue by djbadders** [taniman/profit-trailer#1065]
It would be great if on the DCS and Pairs screen if there was a column to show the percentage difference in price since the last poll. The rows could then also have a little arrow to indicate improving price, stalled or falling. This would be useful and a nice feature.

**Comment by YoJeff** [comment]
I'm not sure price change over 60 seconds is a trend.   The chart add-on that exists now, or the one in progress would provide the visual cue you are looking for.  #259
