### ISSUE TITLE
Issue: lowBB buying on 1 minute candles instead of 15 minute candles

### ISSUE THREAD

**Issue by machyy1** [taniman/profit-trailer#1071]
I have been watching PT work on lowBB, and myself and a few others have seen it buy based on 1 minute candles, even though it is configured for 15 minute candles.

An example of this, here are my settings:

BB_period = 900
BB_sma = 20

ALL_buy_strategy = LOWBB
ALL_buy_value = 5
ALL_trailing_buy = 0.25

At 11:27AM on February 11, 2018, -5 timezone (EST), on Binance, for PPT (so PPTBTC), it started trailing.  It bought at 11:33AM.  

Here is the 15 minute (900 period) chart.  What PT did makes sense if period was set to 60.  However, it doesn't make sense with it set to 900. 

![15min](https://user-images.githubusercontent.com/35576479/36076239-8819bb64-0f27-11e8-87c7-5fdb18baffa7.jpeg)

Here is the 1 minute chart:
![1min](https://user-images.githubusercontent.com/35576479/36076240-8831fada-0f27-11e8-8873-1acc8d550eca.jpeg)

**Comment by rsno** [comment]
Having wierd issues aswell.

BB_period = 900
BB_sma = 20

ALL_buy_strategy = LOWBB
ALL_buy_value = -5
ALL_trailing_buy = 0.2

VENBTC (binance) bought at 12:54:29 @ 0.00048466

15 MIN candle
![skjermbilde](https://user-images.githubusercontent.com/36379106/36076555-de94fc3e-0f5d-11e8-937e-fe67b500cbde.PNG)


1 MIN candle
![skjermbilde2](https://user-images.githubusercontent.com/36379106/36076557-e6b8a99c-0f5d-11e8-8a3c-19d018749f28.PNG)


I have a few more examples if you need more.

**Comment by taniman** [comment]
@machyy1 1 question. What does currentBB show in PT and what does the exchange low bb line show. are those to in sync or not?

So PT current BB vlaue
1 min candle lowBB line
15 min candle lowBB line

just compare to see what PT is using

**Comment by machyy1** [comment]
The current BB value matches up to the 15 minute candle lowBB line

**Comment by Basil-B** [comment]
Hello guys! I can confirm that this is happening on my end as well. I am on Binance and I had PT configured to buy on LOWBB 5 minute candles(period: 300, sma 15) at around -9%  and its actually buying on the 1 minute candles. It bought some ADX at 20:30 UTC when it made no sense to buy on the 5 minute chart, but on the 1 minute chart it did as you can see in the pictures.
![1_minute](https://user-images.githubusercontent.com/36423646/36120980-8939c5da-104d-11e8-8d7d-721c6d13ef5c.PNG)
![5_minute](https://user-images.githubusercontent.com/36423646/36120981-89589e24-104d-11e8-86e2-3d8c10452572.PNG)

**Comment by YoJeff** [comment]
Look at that tail, do you think it never reached your trigger?????????

**Comment by Basil-B** [comment]
Well i also thought of that at first, but to me, from that chart this didn't look like it to be honest. Please correct me if i'm wrong but i don't see the tail on the exact candle it bought on, to be more precise it says it bought at 20:30:04 UTC. Maybe its just unfortunate that the candle i highlighted also sits on the background grid and it seems to have that long tail but it doesn't really have one. :) If you will look for yourself on that chart you will see what i mean... so sorry if the capture is not the best to show my point. Maybe there isn't any issue at all but its a bit strange how it behaves and it could still be worth looking into this i think. I'm also running the latest version just for info. Thanks for the help!

**Comment by YoJeff** [comment]
Also keep in mind you are looking at nicely packaged 'historical' candles.   What was the current ask at that time?

**Comment by JulesBern** [comment]
This just happened to me as well.

**Comment by JulesBern** [comment]
![bb](https://user-images.githubusercontent.com/3683848/36171766-dcae1f8e-10d1-11e8-9af3-97b03ffb0cef.jpg)

**Comment by JulesBern** [comment]
Any update on this? The Bot made another bad purchase based on 1 minute chart instead of 15.

**Comment by taniman** [comment]
@JulesBern The bot is not using 1 minute candles. I have checked multiple options. and the correct chart data is being used.

There might be smething else going on. But using incorrect candle data is not one of those.

Wait for v1.2.6.17 and see if the fix I have creating for LOWBB trailing problem might be whats causing your confusion
