### ISSUE TITLE
FEATURE REQUEST: Moving Average Volume Indicator

### ISSUE THREAD

**Issue by blacksausage** [taniman/profit-trailer#1073]
Please add a moving average indicator for minimum buy volume.

This feature will help PT avoid Pump/Dump schemes which appear to be happening more frequently on Poloniex especially, but I am sure on other exchanges.

The pattern is that a coin will remain at a low volume, and get filtered out by the ALL_min_buy_volume  setting. Then the coin gets pumped or dumped and the volume will move above the min buy volume threshold. The bot will pick up the temporary increased volume and buy the coin. Then it leaves the user with a bag when the bottom falls out again a short time later.

Having some sort of moving average indicator on the volume would help prevent this issue. So for example, a coin would have to maintain its volume level across a time period in order to to be considered by the bot. Coins with temporary volume spikes would get filtered out.

**Comment by YoJeff** [comment]
Dup #708
