### ISSUE TITLE
not allowed to buy xxx buy will exceed minimum balance

### ISSUE THREAD

**Issue by Tomcattdds** [taniman/profit-trailer#1074]
In my possible buy logs, I have potential buys that go below the price trigger but my bot never buys.
Im running PT + Feeder straight out of the box, Anyone have any suggestions?

<img width="667" alt="screen shot 2018-02-11 at 10 42 01 pm" src="https://user-images.githubusercontent.com/36394167/36084005-a13e8ba4-0fb0-11e8-999c-9fd6b4bd2511.png">

**Comment by YoJeff** [comment]
I suggest you use support, this is for bugs.
