### ISSUE TITLE
stop limit/exact price entry point

### ISSUE THREAD

**Issue by kian25** [taniman/profit-trailer#1075]
This one is geared for the manual traders but when trading stocks I liked to put an entry point past a resistance and the bot could purchase only if it hits that point allowing me to enter during an uptrend. 

On another more important note, I put in entry points above supports to get some coins during dips. It works great with profit trailer because with the gain sell and trailing sell it's very easy to make some quick trades. 

A feature that I would love implemented in profit trailer would be to put an exact amount for a certain coin, I know it's possible to do that through the binance interface but every time an order is set the coins get stuck in pending whereas with profit trailer a trader can make an entry point for every coin and if there's no more capital to trade with,  the bot simply wouldn't trade anymore. So instead of splitting your capital between 5 coins you can pretty much cover every dip in your own customized way

I understand this might be something that might not be something that everyone would want because it's not very automated but implementing it would take minimal effort, for all I know it's already capable and it would make a big difference to my trading strategy

**Comment by YoJeff** [comment]
#894 is open for specific prices.  But this isn't an 'augment my manual trading' bot.
