### ISSUE TITLE
Sales not showing on Binance

### ISSUE THREAD

**Issue by vredirect** [taniman/profit-trailer#1078]
Hi,
Just had a few sales that are not showing on the log. They simply disappeared on the sales log. There were a few other before. Here is the proof of the operations I got from the trades on my Binance account.

**2018-02-12 15:14:46 | AST/ETH | Sell | 0.0006698 | 2048 | 0.01897991 BNB | 1.37175040 ETH 2018-02-12 15:14:18 | INS/ETH | Sell | 0.002700 | 384.00 | 0.01434049 BNB | 1.03680000 ETH**

I checked the terminal and it gave this error:

**2018-02-12 06:14:20 ERROR DCAStrategyRunner - An error occured nl.komtek.pt.utils.b: ERROR: -2010, Account has insufficient balance for requested action.**

I am using version 1.2.6.15... Is this maybe related to the API changes Binance has put in place?

If so, will version 1.2.6.16 fix it?

Thanks!
Vick

**Comment by YoJeff** [comment]
1)  This is for bugs only, run through support first.   2)  Development has ceased on prior versions.

**Comment by vredirect** [comment]
Ok understood. So you are saying that we ALWAYS need to be on the latest version and every single update you release WILL ALWAYS be the most stable and reliable? I ask because normally new versions are NOT like that. Anyways, just upgraded now.

FYI I think the previous version was doing some funky purchases. Just went berserk and spent 7ETH on a supposedly DCA that was supposed to be a 0.7ETH... I will let you know if this 10x issue continues on the 1.2.6.16

**Comment by YoJeff** [comment]
I'm saying READ the ANNOUNCEMENTS.   .16 is THE ONLY supported VERSION right NOW.  :)
