### ISSUE TITLE
[Feature Request] Renko Candles for applying SMA's, ADX , CMO crossovers onto.

### ISSUE THREAD

**Issue by tinybigtim** [taniman/profit-trailer#1081]
Plot of development build on Renko Candles

<img width="1134" alt="schermafbeelding 2018-02-12 om 21 47 54" src="https://user-images.githubusercontent.com/36423365/36119918-c88480a6-1041-11e8-88be-c91f2b30d07b.png">

**Comment by taniman** [comment]
Cannot be done in current setup
