### ISSUE TITLE
[BUG] Sales log got emptied

### ISSUE THREAD

**Issue by smoochy** [taniman/profit-trailer#1085]
Heya,

I think I made a big mistake.

I set trading.logHistory = 9999999999999999 in application.properties as I was a bit to over-motivated for using PTTracker.

I had a Sales log of 206. The ProfitTrailerData.json had a size of 170KB.

Some time after this a sale happened. I noticed that the Sales Log went from 207 to just 1. The size of ProfitTrailerData.json went back to 56KB. From having a look at it I only found the most recent sale in it.

I stopped PT and copied back a ProfitTrailerData.json backup file. After starting PT, I had 206 Sales again, the most recent missing. Here I made another mistake and did not make another backup and thought the issue would be solved.

Some time later another sale happened. And the Sales Log went down to 1 again, this very recent sale.

Unfortunately I did see this too late. There was no other backup of ProfitTrailerData.json which contained my sales.

I now have two questions:

Is it possible that trading.logHistory = 9999999999999999 messed up ProfitTrailerData.json?

Is there any tool, which can recover sales from ProfitTrailer.log and made it available to ProfitTrailerData.json?

Thank you.

**Comment by taniman** [comment]
Why would you use such a big value?
trading.logHistory = 9999999999999999

that value will cause an overload and will effectively make the value 0.

we have in newer versions a backup folder. so maybe your data was inside there if you did not run your bot for too long after this happened.

Other than that. there is no way.

**Comment by smoochy** [comment]
Would you mind letting me and others know which would be the largest number not to cause an overload?

**Comment by taniman** [comment]
I fail to see why you would want a value larger than 365 days. which is one year.

next to that sales log should be used as a reference.

buy max value for integers is 2,147,483,647

**Comment by smoochy** [comment]
I planed to start using [PTTracker](http://pttracker.net/) and wanted to use it for longer than just 1 year. Out of stupidity I set the value too high. I was not thinking of the possibility that PT will not be able to handle such a large number.

Well, I learned my lesson now. Making Backups of all PT files more often.

Maybe there is a chance to implement a value check to protect idiots like myself from doing stupid things? Or at least keep more backups of the ProfitTrailerData.json?

**Comment by ruudwelten** [comment]
@smoochy It would be hard to check if the number is too high since Java can only handle 2,147,483,647 maximum. Therefore it overloads and can't check if the value is too high. Maybe it could check if an overload has occured.
But still, you set this value to 27.4 Trillion years! I'd think no one would set this value to anything near the maximum: 5.9 Million years...

**Comment by YoJeff** [comment]
Not to mention shipping all that crap back and forth, every 10 seconds over, and over, and over if you are using the gui.
