### ISSUE TITLE
[Feature Request] Sales log to show purchased date in addition to sold date.

### ISSUE THREAD

**Issue by ransomcarroll** [taniman/profit-trailer#1087]
When reviewing the sales log it is imperative to understand the lifespan of the sales cycle from purchase to sold. 

Currently only the '**Sold date**' is shown and a parenthetical (-1D) showing how many days ago the sale took place.

This feature would simply add a second date perhaps (**Bought date**) above the **Sold date** and ideally a calculation could be made to show something like this:

B: 13.02.2018 01:59
S: 13.02.2018 08:19 (6h 20m)

**Comment by swoopsus** [comment]
+1

**Comment by quasio** [comment]
+1, 
This would be useful as well to confirm the strat is as expected on tradingview.

**Comment by ransomcarroll** [comment]
A similar addition would be to add a **'order date**' field to the '**pending log**' table. It is critical to know how long a PAIR has been pending and right now there is no way to tell, could be 1d or 20d.

**Comment by alexpica** [comment]
+1

**Comment by luisjotapepe** [comment]
+1

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
