### ISSUE TITLE
[Feature Request] - LAUNCH PRICE Evaluation and Trigger for Panic Sell or SOM (both on ALL and specific coins)

### ISSUE THREAD

**Issue by YancyToo** [taniman/profit-trailer#1088]
Firstly thank you for all your hard work. Your bot is amazing and I'm extremely impressed with everything you have done so far and particularly how hard you work to improve the bot. 

Would there be a clever way (i.e. not relying on a specific launch price value from the exchange) of adding the following capability to the bot: SOM or Panic Sell when a coin goes below its launch price by a specified percentage?

Please advise.

Many thanks,

YancyToo

**Comment by YoJeff** [comment]
This is for bugs, please use support for questions.
