### ISSUE TITLE
Sales log, profit last week, profit yesterday and profit today all read 0

### ISSUE THREAD

**Issue by Zakavelie** [taniman/profit-trailer#1089]
After Binance came back up, I have nothing but issues. For the last two days PT has reflected zero for Sales log, profit last week, profit yesterday and profit today. There have been sales, but nothing is populating? This only started a few days ago.
![screen shot 2018-02-13 at 2 32 52 pm](https://user-images.githubusercontent.com/35851687/36169665-e0c0ad5a-10ca-11e8-971e-0b1f993d226e.png)

**Comment by YoJeff** [comment]
Please use support, this is for bugs.
