### ISSUE TITLE
computer caused error message

### ISSUE THREAD

**Issue by 123HIPHOP** [taniman/profit-trailer#1090]
Dear Guys:
         My computer turned off unexpectentely and I received a message as well that reads: "Both save files were damaged, If you have a backup somewhere please use that or just delete ProfitTrailerData.json".
How do I get this thing going again? Any help would be greatly appreciated.
V.1.5.4. Release.
Exchange: Both on Binance
Newest Java Version, Windows 10 64 Bit
Log Attached

**Comment by YoJeff** [comment]
This is for bugs only.   Use support for support.
