### ISSUE TITLE
[BUG] MinBuyVolume trigger after a pair has been bought 

### ISSUE THREAD

**Issue by nvitas** [taniman/profit-trailer#1091]
Using ETH as the base currency I have:

"MinBuyVolume": "500" 

2 pairs were bought when the coin was above that limit. Now the two pairs have fallen below the 500 limit and are currently in the DCA log.

Problem is that it is now in SOM when it should be DCA'ing because of the following reason:

# Sell Only Mode Reasons:
# Pair volume 363.88796124 is less than the min buy volume of 500

I am using PT Feeder which creates the files so this may be a PT Feeder issue as well but PT Feeder does not know under which condition I bought the pairs.

What to do?

**Comment by YoJeff** [comment]
Use support for support, and further use PTF support.
