### ISSUE TITLE
Make the Monitoring Page Responsive (or include a horizontal scrollbar)

### ISSUE THREAD

**Issue by blacksausage** [taniman/profit-trailer#1093]
When the monitoring page gets below a certain width columns disappear from view. I do not see a scrollbar or any other way to get the missing columns back besides resizing the window. 

Browser:Version 63.0.3239.132 (Official Build) (64-bit)

OS: MacOSX: 10.13.3

**Comment by djcrypto75** [comment]
Hey,

+ Button in the front gives you the missing information if you have a small screen. 
I will change this in the future to have a scrollbar instead. 
Tips, you can also zoom out.

**Comment by sirloinwesk** [comment]
Would there be any way to stop the scaling of fonts as well based on browser window size? Or a way to collapse the sidebar?
On a 4k monitor I have about 4 browsers open, and the size of the texts become impossible to see.
