### ISSUE TITLE
Binance: fix link for trading pairs to "XXX_YYY" instead of "XXXYYY"

### ISSUE THREAD

**Issue by mattiasgeniar** [taniman/profit-trailer#1098]
The webgui now links to: https://www.binance.com/trade.html?symbol=DNTBTC

Should link to: https://www.binance.com/trade.html?symbol=DNT_BTC

Note the underscore in the trading pair, this causes a page reload/refresh in binance, adding some (small but noticeable) overhead to page loads

**Comment by douglaspeer** [comment]
In addition, it would be nice if it loaded tradeDetail.html (the advanced tab), or at least provided the option to do so.

**Comment by alexpica** [comment]
+1
