### ISSUE TITLE
Combined buying and selling strategies

### ISSUE THREAD

**Issue by Othon3** [taniman/profit-trailer#1100]
As a new user, I´ve reading and learning a lot.
One actual very important missing key on the strategies are the possibility of combining two or more
buying stretegies, so we can make the bot more flexible.

i.e.:  agreggate LOWBB + SMACROSS (MACD or RSI).

This could be a game changer on how the bot works and choose the best entry points on the market for the user.

Any chance of this being implemented soon?

**Comment by YoJeff** [comment]
Duuuuuplicate #370 #82
