### ISSUE TITLE
PT Bought Cost much less then ALL_max_cost_percentage

### ISSUE THREAD

**Issue by oblodgett** [taniman/profit-trailer#1101]
Here is my config for a pair:

FUELETH_trading_enabled = true
FUELETH_max_cost_percentage = 1
FUELETH_min_buy_balance_percentage = 50
FUELETH_trailing_profit = 0.1075
FUELETH_trailing_buy = 0.1075
FUELETH_buy_value = -1.41
FUELETH_DCA_enabled = -3
FUELETH_sell_value = 1.11
FUELETH_max_buy_spread = 0.65
FUELETH_min_profit = 1.29
FUELETH_min_buy_volume = 500
FUELETH_min_buy_price = 0.00005

My stats line:
BAL: 10.724  TCV: 13.095  TPV: 13.145  Profit : ( 0.20 LW)  ( 0.04 YD)  ( 0.04 TD)  Trend : ( -0.05 % 24H)  ETH: 919.76  (9.58 %)

But the last purchase of FUEL was the following:

14.02.2018 17:35 (0D) | FUELETH | GAIN | 0.00013356 | 0.00013545 | 1.22 | 1.50 | 0.00023801($0.24) | 147.00000000 | 0.01963332 | 0.01987133
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

So the purchase cost was only: 0.01963332
I would have thought that it should be closer to 0.13? about half my purchases are close to 0.13 and the others are much less. Am I missing something here?

**Comment by taniman** [comment]
Yes, seems you are not using ALL_buy_available_volume_trigger. to guarantee the bot will try to buy only when there is enough volume to buy. 

I think what happens is your buy is getting partially filled. But might be some other thing. 

all in all not a bug, check with support if you cannot find out the reason on your own.

**Comment by oblodgett** [comment]
Thank you... sorry to cause the issue. There are a lot of variables and still in the learning process, thanks again.

**Comment by oblodgett** [comment]
Thank you again... this was the cause of my issue. Feeder does not have a setting for ALL_buy_available_volume_trigger but it does now have a common directory for PAIRS.properties so put it in there and now all my trades are right around the percentage.

**Comment by chattaway** [comment]
That was a good one that I’ve had in the past,  but saw that I had got what
there was to get. Thanks

**Comment by mishaaltk** [comment]
Hah! I was wondering about this for a while, and came to the conclusion that there was not enuf buy volume at that buy price, so it was getting partially filled.
So what shud i put under **ALL_buy_available_volume_trigger** ?
Isn't the coin already vetted out from **ALL_min_buy_volume** ?
What did u guys put under the trigger to get it to work?
