### ISSUE TITLE
APIKEY Invalid Issue

### ISSUE THREAD

**Issue by BlockchainRevolution** [taniman/profit-trailer#1108]
Hi Taniman, I have tried to fix this issue for a couple days and still scratching my head. Hopefully you have an idea! I'm currently running Profit Trailer on a Mac with Java 8 installed. 

I get this error message(s) in my Terminal Log --- 

1) ERROR ProfitTrailerService - openOrders - nl.komtek.pt.utils.b: APIKEY_INVALID

2) ERROR ProfitTrailerService - completeBalances - nl.komtek.pt.utils.b: APIKEY_INVALID

3) INFO DCAStrategyRunner - API Problems?

I have verified my default and secondary keys that are in the application.properties. I verified them in the PT Assistant in Discord. I have ensured that there are no spaces or tabs behind the api key and that they have been pasted properly. I have un-installed PT and started from scratch a couple times and have reset my computer a few times as well. 

Any ideas?
Thnxs
<img width="924" alt="screen shot 2018-02-15 at 8 48 20 am" src="https://user-images.githubusercontent.com/30580167/36269229-80ba477c-122d-11e8-8f13-1be18e7770a1.png">

**Comment by YoJeff** [comment]
This is for bugs, please use support.
