### ISSUE TITLE
[Feature Request] Add buy option based on Market Cap

### ISSUE THREAD

**Issue by oiler2112** [taniman/profit-trailer#1111]
Was thinking it would be nice to have an option to only buy coins that meet a market cap number or higher.
We have min_buy_price and min_buy_volume, but min_buy_marketcap would be great as well. This would allow us to all but eliminate shit coins, newly released coins and many P&D coins. With that new option, we could actually specify I only want to trade the top 10 coins, top 20 coins, top 100 coins, etc..

**Comment by taniman** [comment]
Currently I will not integrate communication with a third party into the bot. 
Nonne of the exchanges support the retrieval of market cap. So this future will not be created
