### ISSUE TITLE
[Feature Request] Add options for Browser Tab Text

### ISSUE THREAD

**Issue by oiler2112** [taniman/profit-trailer#1112]
Currently, the browser tab text will show what is specified in server.sitename.

It would be great to have more options for that, specifically, to show the current price of your base currency (BTC, ETH), or to show your BAL, or TCV or TPV, or a combination. Current price of base currency and BAL is what I would like to see.

Thanks!

**Comment by taniman** [comment]
I do not see a reason to put this on the roadmap for now. So it will be closed.
