### ISSUE TITLE
[Feature Request] Specify which Binance URL to link to (Basic or Advanced)

### ISSUE THREAD

**Issue by rshinall** [taniman/profit-trailer#1114]
Add ability to specify which URL to link to from the PT GUI, i.e. Basic or Advanced exchange view when clicking on coin pairs in the GUI.

Example of Basic:
https://www.binance.com/trade.html?symbol=NEBL_BTC

Example of Advanced:
https://www.binance.com/tradeDetail.html?symbol=NEBL_BTC

**Comment by djcrypto75** [comment]
duplicate.
