### ISSUE TITLE
[Feature Request] Time delay to rebuy recently sold coin

### ISSUE THREAD

**Issue by aktrader87** [taniman/profit-trailer#1115]
Would it be possible to add in a time delay to rebuy a recently sold coin?

I've seen PT sell and then rebuy the same coin instantly, I think it would be a nice feature to have being able to delay it by say 30 mins or an hour.

**Comment by calebcall** [comment]
Even just 5 minutes would be nice...anything really.  Most of my bags are from coins in this situation (sells, immediately buys, then the coin drops and doesn't come back).

**Comment by yungcoconut** [comment]
This is a much needed feature. I got a few bags from the bot buying the same coin too quickly after selling it.
