### ISSUE TITLE
Profit Trailer Install issue

### ISSUE THREAD

**Issue by chevyboy2** [taniman/profit-trailer#1119]
When I try to install profit trailer on mac I get this message in Terminal
WARNING: An illegal reflective access operation has occurred

**Comment by SgtBatten** [comment]
Guarenteed there is alot more tot he error tuna what you just posted. My guess is lower down it says 9.0.4 at one point. Meaning you have java 9 still installed.

**Comment by chevyboy2** [comment]
Hello


Correct you are, I will delete Java 9 and install Java 8 and try again


Thank You





________________________________
