### ISSUE TITLE
[NEW FEATURE]: Allow to buy using EMACROSS only if EMA fast is in uptrend only

### ISSUE THREAD

**Issue by gpumlov** [taniman/profit-trailer#1121]
Using EMACROSS to buy pairs. 
I would like to buy only if the fast EMA line is  **uptrend**.

So there should be a settings to control buying in EMA fast uptrend and buying in downtrend too.

This would really help to buy only in uptrend.

Using below attributes, does not prevent bot to buy if fast EMA is in downtrend too.
ALL_buy_value = 0.2
ALL_buy_value_limit = 0.5

**Comment by taniman** [comment]
well actually if you define the EMA_cross_candles a low as possible it will fitler out most down tends.

can you come up with an indicator that does what you are asking?

**Comment by gpumlov** [comment]
HI,

I did have cross candle setup to only one, but bot still bought pair after fast EMA was downtrending. I am not aware of any official indicator, this would be simply rule for bot; if fast EMA in downtrend do not buy pairs....would this be possible to add as a configurable feature...

Many thanks
