### ISSUE TITLE
[Feature request] : Sell DCA bags at breakeven and keep profits in coins of your choice.

### ISSUE THREAD

**Issue by emotionzor** [taniman/profit-trailer#1123]
Hi I want to suggest something that seems extremely easy to implement and would be tremendously useful.

I have been long trying to think of a way of keeping profits in the coin the bot trades. For example, you trade ADA-BTC and make 2% DCA bag profit, but the bot only sells the BTC invested back in order to breakeven, getting the profits in ADA coins (+2%).

I would love to keep my earnings this way mostly and not only BTC, is there any way to do this? Mods of ProfitTrailer told me its a tool meant to grow your BTC or ETH but this doesn't make sense to me.

What if you love for example XMR? What if every time I trade XMR I want to recover the DCA bag investment and keep the "free coins" as profit instead of BTC? This would be super nice as you can choose which pairs you want to generate profit in that coin and not into btc. All of us have some cryptos we love and would love to accumulate more of those coins and not only btc.

Im actually pretty surprised its not implemented - seems useful and simple. The bot just needs to sell the same cost he bought to breakeven in BTC and keep the coins.

I know many people interested in this too. Let me know what you think, thanks for this great bot btw :)

**Comment by taniman** [comment]
I would say you would need to use a different software for this purpose.

We have 1 feature that looks like this coming in 1.2.8, but I am not sure it will fit your needs.

see #496
