### ISSUE TITLE
EMACROSS cross_candles bug or documentation clarification?

### ISSUE THREAD

**Issue by Sereglaith** [taniman/profit-trailer#1124]
I am trying to determine how many candlesticks the buy period will remain active.  My current understanding (and rough charting experience) is that the EMA_cross_candles value will delay the purchase until one candle after the one specified.  So if it is set to 2, then it will start looking to buy 2 candles after the EMAs cross.  Finally, the buy_value and buy_value_limit values will require a buy be done only if the current EMA spread is between these values.

How many candles after the EMA_cross_candles value will the strategy continue to check the buy_value and buy_value_limits?  It does not appear to last until the EMAs cross down again, but it does appear to be at least up to 3 candles (on 5 minute candles).

The following is some documentation confusion.
From docs 1):
> Buying with SMACROSS is similar to SMAGAIN, but the two SMA lines must have crossed within the last SMA_cross_candles (set in Indicators.configuration) value, minus one candle (e.g. if SMA_cross_candles is 5, then the cross must have occurred within the last 4 candles).

This would seem to indicate that a purchase could be made somewhere within the last 4 candles after the EMAs cross.

> In addition, the current value of the coin must be below the lower SMA line by ALL_buy_value % (again, similar to SMAGAIN explained above and in Buy & Sell Strategies.

I thought the buy_value and buy_value_limit were a percentage buy range.

From docs 2):
> 1. With EMA_cross_candles = 3 we move to the 4th dot, as this one is ignored for EMACROSS value. At this moment EMACROSS is in our range and PT is going to place an order.

I have seen purchases occur up to several candles after this point.

Here is all of the documentation I was able to find on the EMACROSS.  Docs 1) and 2) seem to contradict as stated above:
1) https://wiki.profittrailer.io/doku.php/basic_pt_buy_and_sell_logic
2) https://wiki.profittrailer.io/doku.php/pump_and_dump_protection_strategies
3) https://wiki.profittrailer.io/doku.php/buy_and_sell_strategies

Hopefully I described the problem clearly. Any help and clarifications will be gratefully accepted!

**Comment by Sereglaith** [comment]
After further thought, a potential feature suggestion would be an EMA_max_cross_candles value.  This value would work like EMA_cross_candles but in reverse.  A zero value would indicate buys can occur on only the first "valid" candle after EMA_cross_candles.  A one would indicate a buy can occur on the next two candles after EMA_cross_candles, and so on.

Hopefully, this would be easy to implement and add a lot of utility and clarity for this imho underrated buy option.

**Comment by WayneDanielSinclair** [comment]
I have also seen purchases occur many candles after the specified ema cross candles value.
If this isn't a bug, then we definitely need some clarification on this.

**Comment by gpumlov** [comment]
I like the EMA cross strategy, but with above proposed extensions below, this strategy can not be controlled in details.

1. To control the buy candles strictly
2. To prohibit buys in case EMA/SMA fast is already in downtrend

I hope either we will get exact explanation how EMA cross works in details, or/and we will get implemented some extensions to the strategy to control buys more precisely.

Many thanks to profittrailer team to provide detail description and update wiki with description how this strategy really works.

**Comment by taniman** [comment]
I agree the documentation around emacross is not clear. I think I explained in another issue how emacross is supposed to work.

It will buy if the cross happened anywhere inside the amount of cross_candles specified.

So the cross happened at 14:00 on a 5 minutes candle
EMA_cross_candles = 3
It's currently 14:10

So we look at the following candles (3 past candles excluding current candle)
14:05, 14:00, 13:55

Did the cross happened on one of those candles? Yes? We buy!

**Comment by taniman** [comment]
To anyone that added feature request on a bug/issue post I invite you to create a feature request that will be handled seperately. But will most likely be rejected as they are out of scope of current development

**Comment by WayneDanielSinclair** [comment]
I'm not requesting a feature. Do I need to provide proof that it bought after my two candle setting?
