### ISSUE TITLE
There is not enough volume to buy APPCBTC

### ISSUE THREAD

**Issue by crack00r** [taniman/profit-trailer#1127]
Since the update i get:
There is not enough volume to buy APPCBTC

But there is enoth Volumen on this coins
minvolume is 500 in config

![image](https://user-images.githubusercontent.com/6163329/36324842-0c267c6c-1356-11e8-8b9b-6e58a9627d3d.png)

![image](https://user-images.githubusercontent.com/6163329/36324790-e3785664-1355-11e8-9bee-0f368226567e.png)

**Comment by douglaspeer** [comment]
It is market orders volume.  For example, there is a market order for 100 APPC at say 0.01 BTC, if you want to buy 80APPC @ 0.01 BTC, you will be ok, but if you want to buy 120 APPC it should fail.  You need to modify buy_available_volume_trigger to 50 (a percentage) to make this trade "succeed" at 120.

**Comment by mishaaltk** [comment]
Where should u put this statement if you also have PT-Feeder?
Since it doesn't exist in ANY file by default. What does it default at if you don't have it set?
**all_buy_available_volume_trigger = ?**
