### ISSUE TITLE
[Feature Request] EMAGAIN: Profit target a percentage instead of fixed value

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1129]
Could you add a profit percentage based on the EMA drop, instead of a fixed value?
Let's say for instance profit target 50% (of EMAGAIN drop percentage) plus profit trailing at 0.25%.
So when the drop was -1.00%, shoot for 0.5% plus trailing. If the drop is -2.00%, shoot for 1% profit plus trailing, etc...
That would make the EMAGAIN strategy a lot more interesting, powerful and profitable.

**Comment by danielj86** [comment]
+1

**Comment by taniman** [comment]
sorry, currently not taking new strategies ideas
