### ISSUE TITLE
Feature Request: Wait x after selling a pair, before buying the same pair again

### ISSUE THREAD

**Issue by Al0815** [taniman/profit-trailer#113]
I thought about an parameter to pause the buy of one pair for a period x of time after selling this pair.
Example:

Bot sold ETH on the pair BTC_ETH, now buys only ETH for BTC after time x has passed. 

```
# Sets the time to wait before buying a coin again after selling it.
ALL_repurchase_time = x
```

Question is not, if this is possible, but is this affordable or does it cost to much manpower or system power. 

# Elroy Edit:
Also incorporate this
### disable panic after x minutes
`ALL_panic_sell_timeout = 10`

**Comment by taniman** [comment]
too much manpower. I am only 1 man developing. But this could be implemented the same as double buy protection.
you know this feature? It blocks the bot from buying again after it just bought.

**Comment by Al0815** [comment]
Yes I know, but this is a completely different approach.
This prevents, for a period of time,  from buying the same coin again directly after selling it, if its still in the "buy trigger" range.
Reason for that is that maybe the coin was already on his highest point and got sold cause of a fallback in the trailing trigger, but goes up a tiny bit after that. 
Bot sold the coins and instantly buy another stack of the same coin but Coin goes down now and you won a redbag. :)

**Comment by smoochy** [comment]
Thanks for coming up with this idea AI0185 before me. Just had the same thought.

And thanks for taniman for working on that.

I would like to point out, that this is really a huge benefit to prevent bags with certain settings.

Keep up the good work.

**Comment by douglaspeer** [comment]
I am having a similar issue but with buy: EMACROSS, sell: GAIN.  Specifically, a coin is purchased but goes down before the GAIN is achieved.  Later the coin goes on a run, and sells for a GAIN but is still in the EMACROSS region, and repurchases.

I have experienced a variation on this as well.  An initial buy occurs, I make my gain, it sells, then immediately buys again, sells again, and a THIRD buy occurs and I am now stuck with a bag.

My first thought was as the poster suggested and have a repurchase timeout.  But then I got greedy and wondered if it was possible to check if the same coin is in the PBL and ready to buy again.  If so, delay the sale until it is not within a buy trigger.  If this is too complicated a "cooldown" period would be nice.

**Comment by taniman** [comment]
We just released a new version with ths feature. Call in an early test release

**Comment by douglaspeer** [comment]
Great, thanks! I will give it a try.

**Comment by smoochy** [comment]
Thank you very much for adding it
