### ISSUE TITLE
Rebuy timeout is stopping DCA doubledowns

### ISSUE THREAD

**Issue by drummerboy5408** [taniman/profit-trailer#1132]
It seems that Rebuy is considering DCA coins as "just bought" I have All_rebuy_value = 1 in pairs log, and its not set in DCA, just in pairs. Its also not enabling buys even if I wait the 1 minute after it bought originally.

![4 elroy](https://user-images.githubusercontent.com/33564610/36333542-0aceb582-133d-11e8-8c2e-cec72175395f.PNG)

**Comment by SgtBatten** [comment]
Set rebuy_timeout = 0 in DCA file

**Comment by alexdolli** [comment]
Just tried your recommendation, doesn't work SgtBatten :(

**Comment by SgtBatten** [comment]
Try all rebuy timeout = 0 in pairs and rebuy timeout = 0 in DCA. Restart and test for a bit

**Comment by alexdolli** [comment]
I went back to .16 for now... until this is sorted out. Can't afford to test with the amounts I'm running.

**Comment by calebcall** [comment]
I'm not having this issue.  I have ALL_rebuy_timeout = 5 in my pairs (and it is waiting 5 mins to rebuy), nothing about rebuy in my dca file and my dca is executing fine.

**Comment by drummerboy5408** [comment]
Just tried rebuy time to 0 and it still doesn't fix this

**Comment by acefed** [comment]
I had to restart the bots as well, after changing the rebuy parameters, to see an improvement

**Comment by cybermizrach** [comment]
Please keep this config so that I can wait for x minutes before performing a DCA to ensure that the coin price has stopped falling before doing any DCA. This will avoid using up the balance.
