### ISSUE TITLE
Coins not dca'ing in .17 (not related to rebuy timeout)

### ISSUE THREAD

**Issue by DeWim** [taniman/profit-trailer#1133]
It seems alot of people are having problems with coins not dca'ing in ver .17. Here are my findings, maybe they might help.

Settings:
buy_trigger_1 = -1.5
buy_trigger_2 = -3.5
buy_trigger_3 = -7.5
buy_trigger_4 = -9.5
buy_trigger_5 = -12.5
buy_trigger_6 = -17.5
trailing_buy = 0.1

Scenario:
1.   Coin goes down to -1.51 => BT% = -1.51 => trigger = -1.51
2.   Coin goes down to -1.81 => BT% = -1.81 => trigger = -1.81
3.   Coin goes up to -1.73 => BT% = -1.73 => trigger = -1.81 (this is the case in ver .16)
3.1. Coin goes up to -1.73 => BT% = -1.73 => trigger = -1.73 (this is the case in ver .17)

So in ver .17 the trigger follows the BT% up and down instead of just down.

**Comment by cx040156** [comment]
same here. If you set trailing you never buy

**Comment by neur0x** [comment]
Actually, I started doing the same SgtBatten, yesterday I restarted PT, same issue no DCA buys, I closed all GUI's, restarted again, started buying DCA's.

**Comment by Tulleb** [comment]
Same here: I just downgraded and everything is back to normal.

**Comment by jensaturn** [comment]
I've got the same problem.
How do I close the GUI without stopping PT?

**Comment by Tulleb** [comment]
I think those last 12 hours were the best moment for this issue to happen 😍

**Comment by emx0r** [comment]
Same problem. Went back to .16 all works fine

**Comment by JulesBern** [comment]
Same issue. Does not happen in .16

**Comment by KJDcrypto** [comment]
I'm having a similar issue with .16
When pairs are in DCA the buy trigger just keeps moving up and down and never buying.
I have trailing buy set to 0.1% but the bot buy trigger is always trailing by 0.30$+
The buy strat box always reads false under Anderson so It doesn't seems to be looking to buy at all.

**Comment by ManuGithu** [comment]
+1

**Comment by neur0x** [comment]
I've had this issue with .16 however not with all pairs. It wasn't volume related, there wasn't any message on the logs, just regular heartbeats.

**Comment by SgtBatten** [comment]
Screenshot required @KJDCrypto where you think it should be trailing

**Comment by ManuGithu** [comment]
Not buying, just trailing...

![capture d ecran 2018-02-18 a 09 02 22](https://user-images.githubusercontent.com/34100280/36349572-7c108966-148a-11e8-9fd4-830003aa1851.jpg)

**Comment by SgtBatten** [comment]
17 has a bug with DCA. Fix will be out soon. Downgrade for now
