### ISSUE TITLE
[Strategy Feature] "MA APPROACH" Different than Spread/Cross

### ISSUE THREAD

**Issue by drummerboy5408** [taniman/profit-trailer#1134]
*Please delete if this is a duplicate*

Currently, MA-spread strat looks for the lowest price, and trails up from that a certain amount. I have seen this get fooled by false rises not enough to buy and make a gain. MA-Cross strat can only buy right now after it has crossed. 

What I propose is a buy thats activated BEFORE the ema crosses - once the fast MA crosses an underlying "buy value" which is a negative number below the slow MA. This means the coin fast MA can wait and ignore all those mini dips so we can specify a probable value when a coin finally breaks through climb resistance.

The arithmetic for this is very simple. Only about 13 lines of code in pinescript. Let me know if there is any possibility of this to either be added to the current EMACROSS, or to have a seperate strat. Thanks for all that the devs do to keep PT updated for us!

**Comment by taniman** [comment]
We are currently working on some other strategies, in a later update we might open the bot up to allow self made strategies
