### ISSUE TITLE
Feature Suggestion - Order Placed Indication

### ISSUE THREAD

**Issue by sanmaccrypto** [taniman/profit-trailer#1136]
Hello, I have a low priority suggestion to change the colour of the profit % square in the pairs and DCA sections (eg. to perhaps flashing green) when PT is trying to sell a pair.  This would help a user understand what PT is doing by showing that PT has reached the sell trigger, has placed an order and and is trying to sell.  It may help users understand if their settings should be adjusted to reduce expired orders.
Thanks!

**Comment by Jamavo83** [comment]
I like it...

**Comment by YoJeff** [comment]
Feature requests go here:  https://github.com/taniman/profit-trailer-enhancements/issues
