### ISSUE TITLE
[Enhancement] Treat each order individually - replace DCA concept

### ISSUE THREAD

**Issue by milanl71** [taniman/profit-trailer#1139]
Instead of DCA, I would prefer to have an option which will treat each buy of the same pair as a separate trade.
For example, let say that a coin was bought at price of 100 and that buy_trigger is set to -10. Then, the price drops to 90 and the bot buys again. So, I would like that bot is able to sell what it bought the second time separately, for example at 92 and not to wait for 95 to 96 to sell everything. Once the price goes above 100, it will eventually sold the first packet as well.
There would be multiple benefits:
- bot would be trading more often.
- it would be easy to calculate trading limits, buy_trigger and other parameters based on the available budget.
- no risk that DCA eats the complete budget exponentially.
- Less frequent bot settings change. Not to risk to get screwed with DCA, I manually turn it on for specific pair when needed. With the new approach, that wouldn't be needed.

**Comment by miladzamani** [comment]
you have to set the : ALL_pending_order_wait_time
then the first order go to fixed rate and but will able to buy the coin again if is in your trigger

**Comment by milanl71** [comment]
Well, well, well... Sounds interesting, thanks.
I am actually a Gunbot user and not that familiar with Profil Trailer....
So, like this, if the price continue to slide down, the bot would buy every time the price drops by 10%? And it will not double the amount of coins per trade?

**Comment by miladzamani** [comment]
if you disable DCA , it wont double your prev pair bought , and will buy a new pair depending on your buy strategy :)

**Comment by milanl71** [comment]
Well, man, this is veryyyyyyyyyy good!
Practically, all buys of one pair will be treated individually, like completely different coins?

**Comment by miladzamani** [comment]
exactly :)

**Comment by milanl71** [comment]
YEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSS!!!!!!!!!!!
Thanks a lot!!!! You cannot imagine how much did you help me!!!

**Comment by miladzamani** [comment]
wow like to hear that ;)

**Comment by milanl71** [comment]
:)
Next weekend I will purchase the licence and try it out. Maybe I will bug you again! Thanks in advance!

**Comment by miladzamani** [comment]
wish you money :)

**Comment by milanl71** [comment]
Hi again.
I am already using the bot with the pending orders option. The bot already created a few pending sell orders but always with 10% profit. I am using HighBB for selling and I cannot find where these 10% come from.
Wiki is saying following:
_Then the bot will place a sell order at the **desired** profit % and will place your pair in the “Pending” log._
Where "desired profit" is defined?
