### ISSUE TITLE
Feature Request: Sell if there is no movement for period x and coin is within gain range.

### ISSUE THREAD

**Issue by Al0815** [taniman/profit-trailer#114]
If a coin raises over the sell value and get a nice trailing profit ontop but then rising stops and there is no more movement mostly the price goes downwards after the pause.

Would be nice to have an option to sell a coin which is already in gain range, but there is no more (upward) movement for time x.

```
# Put coin on sell order, where there is no more movement for x minutes and coin already in gain range.
ALL_move_freeze_sell = 1.5 
```

Does it make sense, or is the time between API calls to long anyway?

**Comment by taniman** [comment]
I think the difficult part of this is to keep track of the last movement. How would I know that the price did not move?

**Comment by Al0815** [comment]
Yeah I thought about a logik that compares the last known price with the current one. 
Maybe a few times, but don't write every price but rather count the number of api calls since last change or even the time since when price did not change.
Maybe just only hold it in a memory table and don't write it to disc to kee the json small and save some i/o.

**Comment by networkjackbb** [comment]
This is related to my Feature Request of a Max Hang Time (#1226)

You keep in memory for each pair that is currently sell value triggered, two values:
1. Last Bid Price
2. Timestamp of Last Bid Price change.

When current bid price is different from Last Bid Price, you reset those values.

If current bid price is not different from Last Bid Price, and (current time - #2) is greater than "hang time", then sell.

That's what, maybe 40-50 bytes of data max per pair?
