### ISSUE TITLE
DCA - ETH - Binance

### ISSUE THREAD

**Issue by shawndamon** [taniman/profit-trailer#1140]
[TradingFolder.zip](https://github.com/taniman/profit-trailer/files/1733853/TradingFolder.zip)

Am running a robot ETH market on Binanace

I have double checked my pairs and DCA file but i cant seem to spot an issue with the config.

It simply does not seem to trigger DCA as per screenshot
![capture](https://user-images.githubusercontent.com/31374940/36343305-75f1cb7a-1445-11e8-88f5-1daf44b891e0.PNG)

Please help

Current version:
2018-02-15 21:08:33 INFO Application - PT Version: 1.2.6.16

**Comment by K-Kit** [comment]
what's your trailing value set too? also maybe upgrade to 1.2.6.17

**Comment by shawndamon** [comment]
I have upgraded to 1.2.6.17 and am having the same issue.... my trailing as per the attached file is 

# Buy Settings #
max_cost = .08
max_buy_times = 4
min_buy_balance = .05
max_buy_spread = 2
trailing_buy = 0.19

**Comment by shawndamon** [comment]
test

**Comment by SgtBatten** [comment]
Max cost is too low. 

Max cost is the total to be spent on any one pair. Your pairs are all worth nearly 0.08 already and DCAing once would exceed 0.08 so therefore none of them will ever DCA.
