### ISSUE TITLE
Why doesn't PT Buy on the way up and the way down?

### ISSUE THREAD

**Issue by surfr10132** [taniman/profit-trailer#1142]
How can I make this happen? 

Here's a good app that did it. https://steemit.com/cryptocurrency/@stoner19/traderdaddy-com-tutorial-v2

**Comment by taniman** [comment]
I would suggest not posting competitor links here. We are adding new features and will keep improving.

**Comment by surfr10132** [comment]
They’re not a competitor because they don’t exist anymore. Regardless I made a ton of money buying both the way up and down.
