### ISSUE TITLE
NormalStrategyRunner - You are not allowed to buy XXX. Buy will exceed minimum buy balance

### ISSUE THREAD

**Issue by bogdanstroescu** [taniman/profit-trailer#1143]
For the past few days since I changed my settings, I've been getting the below error and the bot doesn't buy any pairs anymore:
![image](https://user-images.githubusercontent.com/35555709/36344854-c5fc0378-13dd-11e8-84f3-15db37772e1a.png)

I'm a noob, but to my understanding my PAIRS.properties folder is giving this error. Please, if someone would kindly have a look at my settings below and let me know what the issue is. I've changed the ALL_min_buy_price many times and I have no clue what is wrong in the code.

![image](https://user-images.githubusercontent.com/35555709/36344864-ffbff2a4-13dd-11e8-8c04-451a3db90aa1.png)

![image](https://user-images.githubusercontent.com/35555709/36344875-1a771d7a-13de-11e8-850d-1ff7067ad450.png)

**Comment by SgtBatten** [comment]
Its not telling you.to change min buy price it's telling you to change  min buy balance.

Your Min buy balance percentage is saving 10% of your balance from being spent. It's not an error. It's doing what you told it to do. Please come to discord for further help. This is not a support platform. It is designed for bug reporting.

**Comment by bogdanstroescu** [comment]
Thank you for the reply, I just joined discord and posted this issue i'm having on there.
