### ISSUE TITLE
Feature Suggestion - Unloading a portion of the DCA balances or crappy buys.

### ISSUE THREAD

**Issue by Jamavo83** [taniman/profit-trailer#1146]
When you have accumulated a huge bag, sometimes it would be nice to be able to unload part of that bag.  Example, you have 0.5 BTC tied up in BRD, and it has DCA'd 5 times, now your bot is locked up due to capital being used.  Set a trigger for a smaller profit or small loss based on percentage to unload a portion of that bag.  Say if this pair DCA'd 4 or more times, and the price has come back up to a break even or a -0.5% loss, sell 30% of my holdings to unlock my capital to make other purchases (of course with a trailing option).   I have seen several times in the last 2 week where I have a pair that comes up to maybe +0.2% but then drops back down to -14%.  I know you can manually do this in the exchange by setting a limit order But if you can set it up to do it automatically, I think that may really help with some of these bags that soak up huge portion of your portfolio.

**Comment by Jamavo83** [comment]
Additional though, this could potentially give you another opportunity to DCA.  Say you unload 50% of your our 0.5 BTC Bag at a 0.05% profit, and the price begins to drop again and hits your next DCA trigger, you get another DCA and your back in to your original 0.5 BTC bag, but now have a lower Average cost.

**Comment by neur0x** [comment]
+1

**Comment by taniman** [comment]
Although this idea has crossed my mind multiple times. There are bigger implications that cannot be handled correctly in the current state of the bot. So this idea will be skipped for now
