### ISSUE TITLE
Make PT run as a service! Include console in web gui too!

### ISSUE THREAD

**Issue by elementalwindx** [taniman/profit-trailer#1147]
I'm so sick of having to re-run the program every time my server restarts for updates. Please make this run as a service as it should have been in the first place, and output all console to a rotated log file and also into a page on the webgui. Group the feeder addon console output into the same place as well.

I've successfully ran pt as a service using: https://github.com/kohsuke/winsw/releases

Make it "part of the package" perhaps?

**Comment by taniman** [comment]
that's why we deliver the pm2 file.

**Comment by elementalwindx** [comment]
Is there a howto on using the pm2 file?
