### ISSUE TITLE
[BUG] Auto-fixed sales don't register in sales log

### ISSUE THREAD

**Issue by bruce133** [taniman/profit-trailer#1148]
The bot sometimes sets a pair to FIXED and moves it into the Pending Log, which I guess is fine.
The problem however is that when the pair finally sells off, it isn't registered in the Sales Log (see BCD below):

![image](https://user-images.githubusercontent.com/2420663/36354320-affdb058-14d2-11e8-883d-8d82dac9b7b4.png)

![image](https://user-images.githubusercontent.com/2420663/36354311-910dbae4-14d2-11e8-94fd-86afbe830146.png)

I'm using v.1.2.6.17.

**Comment by miladzamani** [comment]
Correct

**Comment by YoJeff** [comment]
This is the correct function.

**Comment by bruce133** [comment]
How is this working as intended? Why shouldn't a sale be registered in the log if the bot initiated it?
