### ISSUE TITLE
[Bug] Manually DCAing causes the bot to have inconsistent Profit% for a period of time

### ISSUE THREAD

**Issue by tomasgodoi** [taniman/profit-trailer#1149]
When I manually buy an amount of an already bought coin, PT detects that buy, but for some minutes the Profit% looks like just the last buy was made. After a few minutes it finally averages it with the previous buys.
![image](https://user-images.githubusercontent.com/13601534/36354646-5591b572-14b6-11e8-9583-9dbfcf7d7c1c.png)
Look at the -0.58 Profit%
Now look the the correct percent after some minutes...
![image](https://user-images.githubusercontent.com/13601534/36354660-7f3a055a-14b6-11e8-8f22-17a55c762984.png)

I'm not sure what the bot would do if the last buy goes up fast, but I'm afraid it would sell it giving me a loss.

**Comment by taniman** [comment]
What version of the bot is this?

**Comment by tomasgodoi** [comment]
1.2.6.16
And that started to happen just after Binance was back from mainantence on February 9. It didn't happen before that.

**Comment by taniman** [comment]
I have a possible fix for this. even though manual buys on binance are not recommended.
So once version 1.2.6.19 has been released check if the problem persists

**Comment by cmreynol** [comment]
I am still seeing this same issue and I am using version 1.2.6.20.
