### ISSUE TITLE
[Suggestion] Option to view "Possible Buy Log" at all times, even at max pairs

### ISSUE THREAD

**Issue by octobrium** [taniman/profit-trailer#1151]
I think the Possible Buy Log is a very useful feature to see, as it shows what the bot would be buying if it were not at max pairs already, allowing for improvements and tweaking the settings. Having the option to put the possible buy log in a sort of "watch mode" (instead of disappearing) while at max pairs would be helpful

**Comment by smoochy** [comment]
Yes please.

**Comment by mnanut** [comment]
Yes, would love this...It is useful to study and see if settings are behaving while you are maxed out.

**Comment by ShadowOnTheLand** [comment]
I would go one step further with this:

It would be nice if we could have a button which would execute a buy order manually in the GUI. As long as you have the funds available, and you don't violate your min_buy_balance settings, it executes a buy.
 There have been times where a coin drops and I have full bags, but profit is there to be made so I will manually buy which can cause issues with the bot.

**Comment by HojouFotytu** [comment]
Agree with all of this, especially the comment above.   I do a lot of manual buying for the bot, and it takes too long to show up on the bot, and it also causes issues with DCA, as I mentioned in another post.

**Comment by ShadowOnTheLand** [comment]
I’ll also add to this, that you could do the “buy now” button as a trail trigger. Price is 1.00, you feel this is an acceptable buy price. So you hit the buy button. The bot now starts trailing the coin.

Pairs file syntax;

All_buynow = true/false
All_buynow_trail = 0.1
All_buynow_variance = 1 (percentage)
All_buy_now_timeout = 60 (time in seconds)

The time out is the specified length of time you want the bot to trail after hitting the buy now button. If after the allotted time period it hasn’t dropped below your  initial trigger point, it will check against your variance and issue a buy order for the current price if it’s still within your price range. If it’s not, then the bot does nothing.

**Comment by ShadowOnTheLand** [comment]
You could add in:

all_buynow_price

And

All_buynow_price_percentage

If you wanted to customize separate pricing buy points from your normal buy price/price percentage.

This would also follow buy balance, and dca reserve rules(should my idea for dca reserve gets implemented).

**Comment by ShadowOnTheLand** [comment]
if You want me to post a full work up of my idea in its own post I have the idea fully fleshed out.

**Comment by smoochy** [comment]
The idea of Shadow sounds interesting. If you think about adding it, please also allow this for DCA.

**Comment by ramonduraes** [comment]
I would like to see on this same screen the estimated value in USD that the BOT will spend.

**Comment by YoJeff** [comment]
This has turned into a hodge podge of requests.  Please don't hijack requests.

You can sort of achieve this now by hacking the configs a little.
-  Set you default buy value to something crazy that will not ever buy
-  Ensure your max_pairs is always +1 to actual pairs
-  Selectively set buy_values for individual coins, get rid of them when you are at your real max_pairs

It's work, but will show possible buys for all coins not currently owned.

**Comment by tru-fkn-blu** [comment]
Can be done easier than mentioned above. Have max pairs set to like 50 and use all_min_buy_percentage. 

Set the value to 99 and then you can monitor the buy log without purchasing. Just drop the value back down to like 30 when you want to start buying again. I do this instead of running sell only mode. Same result but you can see when coins are being trailed

**Comment by SgtBatten** [comment]
Multiple trailing coins will be purchased as soon as you lower the % unless you are very precise 

Recommend you use min buy balance and adjust it low enough to allow one buy for example.

**Comment by taniman** [comment]
original request has been made available in 1.2.6.23
