### ISSUE TITLE
[Feature Request] Add a sell now button to each pair

### ISSUE THREAD

**Issue by dennisgyor** [taniman/profit-trailer#1152]
Im not sure what the cause is but sometimes, the Total cost in my DCS and pairs log is somehow set to 0.00000000. Possible workarounds:

1. Add it in the JSON file.
2. set panic sell = true  for the pair. 

Ideally I would like to see a check box allowing me to select the pair I want to take action on and by clicking a button to immediately sell the selected pairs.

Im working on a javascript solution myself and may submit a pull request at a later date if this is not implemented soon.

**Comment by SgtBatten** [comment]
The solution to the 0.0000 is the hotconfig.
