### ISSUE TITLE
There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot

### ISSUE THREAD

**Issue by smoochy** [taniman/profit-trailer#1154]
Hi,

this morning, I woke up to Telegram spammed me with this message:

> 2018-02-18 04:05:40 INFO ProfitTrailerService - Cache Heartbeat
> 2018-02-18 04:05:45 INFO ProfitTrailerService - DCA Heartbeat
> 2018-02-18 04:06:01 INFO ProfitTrailerService - Normal Heartbeat
> 2018-02-18 04:10:43 INFO ProfitTrailerService - There is something wrong with your Bot, let me try to restore it...
> 2018-02-18 04:10:46 INFO DCAStrategyRunner - API Problems?
> 2018-02-18 04:15:50 INFO ProfitTrailerService - DCA Heartbeat
> 2018-02-18 04:15:53 INFO ProfitTrailerService - There is something wrong with your Bot, let me try to restore it...
> 2018-02-18 04:15:58 INFO ProfitTrailerService - Cache Heartbeat
> 2018-02-18 04:16:04 INFO ProfitTrailerService - Normal Heartbeat
> 2018-02-18 04:21:01 INFO ProfitTrailerService - There is something wrong with your Bot, let me try to restore it...

This went on for hours, until I restarted PT. This was happening with Version .16 (I downgraded from .17 because of the DCA bug). I am not sure, if this affected trading in any way, as I was stuck with 4 DCA anyways.

This night, I updated to .18 (REUPLOADED -1) in the meantime, this occured:

> 2018-02-18 20:23:57 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
> 2018-02-18 20:23:57 INFO ProfitTrailerService - LOADING REQUIRED DATA....
> 2018-02-18 20:24:00 INFO DCAStrategyRunner - API Problems?
> 2018-02-18 20:25:54 INFO Util - Detected configuration changes
> 2018-02-18 20:25:59 INFO Util - Detected configuration changes
> 2018-02-18 20:26:04 INFO Util - Detected configuration changes
> 2018-02-18 20:26:05 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
> 2018-02-18 20:26:05 INFO ProfitTrailerService - LOADING REQUIRED DATA....
> 2018-02-18 20:28:15 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
> 2018-02-18 20:28:15 INFO ProfitTrailerService - LOADING REQUIRED DATA....
> 2018-02-18 20:30:22 INFO ProfitTrailerService - Normal Heartbeat
> 2018-02-18 20:30:26 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
> 2018-02-18 20:30:26 INFO ProfitTrailerService - LOADING REQUIRED DATA....

I am not sure what is causing this. There was nothing special happening before this.

Any information you need?

**Comment by synapse1** [comment]
I have the same issue, the messages started 1hour ago. I installed version x.17 yesterday although I see we now have 18 so I'll try that after work

**Comment by dangeross** [comment]
Having the same issue with 18. Restarted the bot and I get:

> 1|profit-t | 2018-02-19 06:10 +00:00: 2018-02-19 06:10:37 ERROR Application - INVALID LICENSE

**Comment by synapse1** [comment]
I believe the invalid licence was an issue with the server earlier on. I'll be retrying mine in a few hours

**Comment by okulair** [comment]
Same problem here.
2018-02-19 09:12:39 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
2018-02-19 09:12:39 INFO ProfitTrailerService - LOADING REQUIRED DATA....
2018-02-19 09:12:43 INFO DCAStrategyRunner - API Problems?

It happened with .16, .17 and now with .18.  The issue seems to happen about two time per day, at random interval.

**Comment by marinatraisler** [comment]
same for me, with version 18

**Comment by cupid-stunt** [comment]
I have the same problem. Happens every day. I noticed that the BTC price on the monitor shows zero and the DCA log was also not accurate. Seems like a server feed problem from Binance. I'm using ver.18 on a Raspberry pi. I'm considering making a cron job to auto restart profittrailer. But does anyone know if we can restart just the process? i.e. the data feed from Binance?

**Comment by statik121** [comment]
Same here. Running solid for weeks and now this.

**Comment by synapse1** [comment]
OK I just had the issue again after upgrading to 18.
So for me 17 had the same issue. The last stable version I ran was 15 so i'm in the process of downgrading to that version.

I dont know if it's co-incidence or not, But i started getting the errors around the same time a newly purchased pair (NEBL) got moved into DCA. Perhaps this is related to the DCA issues reported in the last few versions?

This is what i saw on version 18

0|profit-t | 2018-02-20 14:40 +10:30: 2018-02-20 14:40:23 INFO NormalStrategyRunner - Normal Pair - LOWBB bought -- currency pair NEBLBTC - BV -0.7, BVL 0.0, MTP 4, TTP 4
0|profit-t | 2018-02-20 14:41 +10:30: 2018-02-20 14:41:50 INFO ProfitTrailerService - DCA Heartbeat
0|profit-t | 2018-02-20 14:42 +10:30: 2018-02-20 14:42:06 INFO ProfitTrailerService - Normal Heartbeat
0|profit-t | 2018-02-20 14:49 +10:30: 2018-02-20 14:49:12 INFO ProfitTrailerService - Cache Heartbeat
0|profit-t | 2018-02-20 14:51 +10:30: 2018-02-20 14:51:50 INFO ProfitTrailerService - DCA Heartbeat
0|profit-t | 2018-02-20 14:52 +10:30: 2018-02-20 14:52:10 INFO ProfitTrailerService - Normal Heartbeat
0|profit-t | 2018-02-20 14:59 +10:30: 2018-02-20 14:59:13 INFO ProfitTrailerService - Cache Heartbeat
0|profit-t | 2018-02-20 15:01 +10:30: 2018-02-20 15:01:54 INFO ProfitTrailerService - DCA Heartbeat
0|profit-t | 2018-02-20 15:02 +10:30: 2018-02-20 15:02:10 INFO ProfitTrailerService - Normal Heartbeat
0|profit-t | 2018-02-20 15:05 +10:30: 2018-02-20 15:05:17 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
0|profit-t | 2018-02-20 15:05 +10:30: 2018-02-20 15:05:17 INFO ProfitTrailerService - LOADING REQUIRED DATA....
0|profit-t | 2018-02-20 15:05 +10:30: 2018-02-20 15:05:22 INFO NormalStrategyRunner - API Problems?
0|profit-t | 2018-02-20 15:07 +10:30: 2018-02-20 15:07:30 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
0|profit-t | 2018-02-20 15:07 +10:30: 2018-02-20 15:07:30 INFO ProfitTrailerService - LOADING REQUIRED DATA....
0|profit-t | 2018-02-20 15:09 +10:30: 2018-02-20 15:09:41 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
0|profit-t | 2018-02-20 15:09 +10:30: 2018-02-20 15:09:41 INFO ProfitTrailerService - LOADING REQUIRED DATA....
0|profit-t | 2018-02-20 15:09 +10:30: 2018-02-20 15:09:51 INFO ProfitTrailerService - Cache Heartbeat
0|profit-t | 2018-02-20 15:11 +10:30: 2018-02-20 15:11:54 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
0|profit-t | 2018-02-20 15:11 +10:30: 2018-02-20 15:11:54 INFO ProfitTrailerService - LOADING REQUIRED DATA....
0|profit-t | 2018-02-20 15:11 +10:30: 2018-02-20 15:11:59 INFO ProfitTrailerService - DCA Heartbeat
0|profit-t | 2018-02-20 15:12 +10:30: 2018-02-20 15:12:13 INFO ProfitTrailerService - Normal Heartbeat
0|profit-t | 2018-02-20 15:14 +10:30: 2018-02-20 15:14:05 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot

**Comment by DaNiSeL** [comment]
I have the same issue ! With version 16 it said “there is something wrong with your bot, let me try to restore it” and with version 18 “there is something wrong with your bot, if this happens more then three times restart your bot. In the log it says there might be a api problem. When this starts happening it is not able to read 24h % and volume anymore. So it will stop buying and doing dca etc... !

**Comment by znafca** [comment]
Hi guys, I also faced that issue, binance, pt v17 and v18. Today I logged in to the GUI, the top row was running this rotating circle and not really showing stuff, paris and DCA were like freeze (no update), I wen to the command line and hit ctrl+c, it did not stop the bot but throw below entires on the screen and made bot runnig fine again (GUI with no rotating circle, pairs and DCA refreshed).

2018-02-20 08:58:09 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -- currency pair NEBLBTC - BV -0.95, BVL 0.0, MTP 8, TTP 8
2018-02-20 08:58:17 INFO DCAStrategyRunner - There is not enough volume to make a successfull DCA VIBEBTC
2018-02-20 08:58:47 INFO ProfitTrailerService - SOM is active for VIBEBTC. -- Manually set in PAIRS.properties
2018-02-20 09:12:27 INFO Util - Detected configuration changes
2018-02-20 09:01:00 INFO ProfitTrailerService - Cache Heartbeat
2018-02-20 09:00:55 INFO ProfitTrailerService - Cache Heartbeat
2018-02-20 09:48:17 INFO ProfitTrailerService - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot
2018-02-20 09:00:53 INFO ProfitTrailerService - Cache Heartbeat
2018-02-20 09:00:53 INFO ProfitTrailerService - Cache Heartbeat
2018-02-20 09:00:52 INFO ProfitTrailerService - Cache Heartbeat
2018-02-20 09:48:17 INFO ProfitTrailerService - LOADING REQUIRED DATA....

Look at the time stamps, this is what I saw in the command line after pressing ctrl+c, like the entries are not in synch.

**Comment by taniman** [comment]
This problem is the weeks old binance freeze that happens on some bots. Version .19 will try to resolve it again. 
@cupid-stunt  please contact support if you can't contact me on discord tell them I send you. If this happens everyday to you. I want you to try this fix we are testing

**Comment by swoopsus** [comment]
This has happened to me on two separate bots on binance twice in the last 24 hours, on both bots at different times. I had previous binance issue where updates to pricing stopped without error, but this seemed to be fixed in 1.2.6.16. This seems to be a new issue. The error keeps repeating and the time between the error varies from 5 minutes to 20 mins typically. When you kill and restart the bot it normally runs a few hours before this comes back again.

**Comment by eiertee** [comment]
Hi guys, it's happening to me too now... running on .18, what should i do?

**Comment by synapse1** [comment]
Downgraded to .15 on my rPi fixed it for me

**Comment by julian4646** [comment]
Also happens to me on rPI - is that something we all have in common ?

**Comment by calebcall** [comment]
This is also happening to me, I'm not on an rPi.  It's happening every 2-4 hours from a restart for me.  If there's any info, data I can provide I'm happy to.

**Comment by simonwahlgren** [comment]
Hey! I'm having the same problem since 4 days back. After restarting the bot the problem disappear for a short while but it always return.

@taniman If you need more guinea pigs I would like to test the new 1.2.6.19 release.

**Comment by magisterh** [comment]
Same problem with v19 on binance...

**Comment by simonwahlgren** [comment]
So far it's working for me
