### ISSUE TITLE
Add console output to webgui

### ISSUE THREAD

**Issue by elementalwindx** [taniman/profit-trailer#1156]
I was told to put suggestions here. Add all pt and ptf console output to the webgui so we can see it all from there as well. For us linux users using pm2 with no console screens to directly look at.

**Comment by aries-delossantos** [comment]
Why don't use you the `pm2 log`?

**Comment by elementalwindx** [comment]
I want to be able to use the web gui for everything and never have to remote into the server. You guys are already 90% there. Just need to add a "restart" button instead of just a "stop" button, and what I've requested here :)

**Comment by elementalwindx** [comment]
oh and add the ability to edit the pft files when pft is being used :)

**Comment by aries-delossantos** [comment]
> oh and add the ability to edit the pft files when pft is being used :)

`server.enableConfig = true` ?

**Comment by djcrypto75** [comment]
PTF is 3rd party. Also all this have been requested many times.
