### ISSUE TITLE
[BUG] EMASPREAD - Bot re-buying even though spread is +ve 

### ISSUE THREAD

**Issue by quasio** [taniman/profit-trailer#1158]
Occurs on both .16 and .17 the bot sometimes re-buys even though the conditions for EMASPREAD aren't met. 

i set a rebuy timeout of 5minutes , but it constantly tries even still tried when EMASPREAD is +ve

Pairs:
ALL_buy_strategy = EMASPREAD
ALL_buy_value = -0.60
ALL_trailing_buy = 0.2
ALL_rebuy_timeout = 5

Indicators:
EMA_period = 300
EMA_1 = 24
EMA_2 = 10

![image](https://user-images.githubusercontent.com/7871238/36362070-4a2356f8-156c-11e8-8d28-a2b2aaf670a5.png)

log:
Line 4041: 2018-02-19 04:54:26 INFO ProfitTrailerService - Sell order for BCPTETH sold amount 59.000000 for price 0.000857 -- {"symbol":"BCPTETH","orderId":6126814,"clientOrderId":"XktS9Modl5Wji0emnLmFqa","transactTime":1518987266820,"price":"0.00085674","origQty":"59.00000000","executedQty":"0.00000000","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
	Line 4041: 2018-02-19 04:54:26 INFO ProfitTrailerService - Sell order for BCPTETH sold amount 59.000000 for price 0.000857 -- {"symbol":"BCPTETH","orderId":6126814,"clientOrderId":"XktS9Modl5Wji0emnLmFqa","transactTime":1518987266820,"price":"0.00085674","origQty":"59.00000000","executedQty":"0.00000000","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
	Line 4042: 2018-02-19 04:54:31 INFO ProfitTrailerService - Get order information -- {"symbol":"BCPTETH","orderId":6126814,"clientOrderId":"XktS9Modl5Wji0emnLmFqa","price":0.00085674,"origQty":59.00000000,"executedQty":0E-8,"status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1518987266820}
	Line 4043: 2018-02-19 04:54:39 INFO ProfitTrailerService - Sell order for BCPTETH sold amount 59.000000 for price 0.000853 -- {"symbol":"BCPTETH","orderId":6126865,"clientOrderId":"gEIlW6NYfkSG3PTrB16wKB","transactTime":1518987279643,"price":"0.00085254","origQty":"59.00000000","executedQty":"59.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
	Line 4043: 2018-02-19 04:54:39 INFO ProfitTrailerService - Sell order for BCPTETH sold amount 59.000000 for price 0.000853 -- {"symbol":"BCPTETH","orderId":6126865,"clientOrderId":"gEIlW6NYfkSG3PTrB16wKB","transactTime":1518987279643,"price":"0.00085254","origQty":"59.00000000","executedQty":"59.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
	Line 4044: 2018-02-19 04:54:44 INFO ProfitTrailerService - Get order information -- {"symbol":"BCPTETH","orderId":6126865,"clientOrderId":"gEIlW6NYfkSG3PTrB16wKB","price":0.00085254,"origQty":59.00000000,"executedQty":59.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1518987279643}
	Line 4045: 2018-02-19 04:54:48 INFO ProfitTrailerService - Cannot buy BCPTETH. rebuy timeout active!
	Line 4046: 2018-02-19 04:55:31 INFO NormalStrategyRunner - There is not enough volume to buy BCPTETH
	Line 4047: 2018-02-19 04:55:58 INFO ProfitTrailerService - Cannot buy BCPTETH. rebuy timeout active!
	Line 4048: 2018-02-19 04:57:07 INFO ProfitTrailerService - Cannot buy BCPTETH. rebuy timeout active!
	Line 4049: 2018-02-19 04:58:11 INFO ProfitTrailerService - Cannot buy BCPTETH. rebuy timeout active!
	Line 4050: 2018-02-19 04:58:38 INFO NormalStrategyRunner - There is not enough volume to buy BCPTETH
	Line 4051: 2018-02-19 04:59:16 INFO ProfitTrailerService - Cannot buy BCPTETH. rebuy timeout active!
	Line 4052: 2018-02-19 04:59:49 INFO ProfitTrailerService - Buy order for BCPTETH -- {"symbol":"BCPTETH","orderId":6127835,"clientOrderId":"UTieViNgZtCCpeZyKfxGmY","transactTime":1518987589804,"price":"0.00085868","origQty":"58.00000000","executedQty":"58.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
	Line 4052: 2018-02-19 04:59:49 INFO ProfitTrailerService - Buy order for BCPTETH -- {"symbol":"BCPTETH","orderId":6127835,"clientOrderId":"UTieViNgZtCCpeZyKfxGmY","transactTime":1518987589804,"price":"0.00085868","origQty":"58.00000000","executedQty":"58.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
	Line 4053: 2018-02-19 04:59:54 INFO ProfitTrailerService - Get order information -- {"symbol":"BCPTETH","orderId":6127835,"clientOrderId":"UTieViNgZtCCpeZyKfxGmY","price":0.00085868,"origQty":58.00000000,"executedQty":58.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1518987589804}
	Line 4054: 2018-02-19 04:59:55 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -- currency pair BCPTETH - BV -0.6, BVL 0.0, MTP 5, TTP 3
	Line 40

**Comment by taniman** [comment]
.16 does not have rebuy timeout logic
and .17 has been taken out of circulation.
please use .18 and create a new issue if the problem exists there
