### ISSUE TITLE
How do I get rid of dust in binance?

### ISSUE THREAD

**Issue by SERHYG** [taniman/profit-trailer#1159]
hello
I have this amount of dust in my account:

Current Value                0.00594613
Difference  (-10.18 %)  -0.00067391
Bought Cost                   0.00662004

the problem is not the quantity, the problem is that it does not diminish with the new purchases that the bot makes!!!
in configuration.properties i have set BTC_dust = 0.001 so that the bot makes new purchases and eliminates the remains of coins that I have.
the ALL_max_cost = 0.00155555 Set it up like this, because the bot now rounds up the purchase of coins to units and does not use the dust I have!
I have tried to give particular configurations to each coin according to the remnant I have (VENBTC_max_cost = 0.00156773) for the bot to buy the decimals that I need to complete the salable unit, but I have not had any luck!
Buying in manual directly in binance does not work either!

How can I solve this problem!?

thank you!

**Comment by YoJeff** [comment]
"How can I" type questions are for support.  This is for bugs.
