### ISSUE TITLE
Installed latest ver. 1.2.6.18 - ERROR Application - INVALID LICENSE

### ISSUE THREAD

**Issue by TeleTubby9** [taniman/profit-trailer#1162]
Installed latest ver. 1.2.6.18 - I get this error in the command window when PT is loading the program, the fourth line from the top  

ERROR Application - INVALID LICENSE

**Comment by Jerek1022** [comment]
me too

**Comment by tabletman** [comment]
me too... entering any key after this point closes the window and shuts down the boot.
[Screen Shot 2018-02-19 at 03.21.07.pdf](https://github.com/taniman/profit-trailer/files/1735931/Screen.Shot.2018-02-19.at.03.21.07.pdf)

**Comment by SgtBatten** [comment]
The licence server is down guys. Please close this issue and monitor the announcements channel on discord

**Comment by kernmeister** [comment]
Any news on the server? i still have the problem that i can't log-in!
