### ISSUE TITLE
[Feature Request] Error-Log in the Frontend

### ISSUE THREAD

**Issue by ingeniumdesign** [taniman/profit-trailer#1164]
Hello Team,
can u add the Error-Log in the Frontend?
We see a Error faster, and we dont need to Connect on the Bot via SSH.
Thanks

**Comment by julian4646** [comment]
Viewing the whole ProfitTrailer.log would be great in the GUI or even the last Xx lines

**Comment by znafca** [comment]
+1 to the idea

**Comment by taniman** [comment]
/monitorig/log is a work in progress. But we are already working on this for the future.
