### ISSUE TITLE
Dust with a specific pair on Binance

### ISSUE THREAD

**Issue by cryptolegendx** [taniman/profit-trailer#1165]
Hello, I am having an issue with binance and a specific pair GTOBTC.  I have BNB with BNB purchasing enabled to limit the dust.  However my bot purchased GTOBTC.  Has not done any trading with it and no DCA was applied.  It purchased exactly 21 coins so there should be no dust however its sitting in my dust log losing value as the coin is in a down trend.

![dustlog](https://user-images.githubusercontent.com/36631398/36381273-17959fac-1553-11e8-9749-23c2833a6c8b.png)

**Comment by YoJeff** [comment]
If you buy near dust levels, then the value drops below dust -- what do you think happens?  This.
