### ISSUE TITLE
ERROR BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read

### ISSUE THREAD

**Issue by oblodgett** [taniman/profit-trailer#1166]
2018-02-19 16:32:55 ERROR BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read
2018-02-19 16:33:33 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $, message 

I have attached the JSON to save the space here.

[error.log](https://github.com/taniman/profit-trailer/files/1737556/error.log)

The error.log is the json string that failed deserialization.

**Comment by oblodgett** [comment]
2018-02-19 16:12:00 INFO Application - PT Version: 1.2.6.18
2018-02-19 16:12:00 INFO Application - Java Version: 1.8.0_161

**Comment by pepps1976** [comment]
Same issue with the same versions

**Comment by taniman** [comment]
People keep opening this 'issue' but it's not an issue. Sometimes your internet conenction causes a timeout while reading data. That's part of having an open channel  to the exchange.

If the error happens continuosly you need to check your network and internet connection.

**Comment by rob822018** [comment]
Ok YoJeff I get it its the connection but could you be more specific?when this happen I can access to the binance website and from the desktop app so I dont see how it can be an issue related to my network and internet connection

**Comment by YoJeff** [comment]
That level of specificity would have to come from Binance, since ultimately it's their server timing out.

**Comment by rob822018** [comment]
Thanks YoJeff, do you see this to be solved in the next releases or it has to be like this?

**Comment by YoJeff** [comment]
I'm not sure when Binance is releasing their next version and/or upgrading their datacenter.

**Comment by rob822018** [comment]
Got it
Thanks

**Comment by jokaorgua** [comment]
PT: 1.2.6.23
OS: linux ubuntu

have the same issue onWebSocketError: Timeout on Read

please don't tell that this is internet connection issue. the bot is installed in ovh.com datacenter and I've checked the socket with binance with parallel my own script. the connection is good without any problems.

**Comment by SgtBatten** [comment]
It a takes a small interuption to get this message. Unless it's constant it's nothing to be concerned about.

Also getting it during or immediately after straying the bot is also normal.

**Comment by jokaorgua** [comment]
This thing is constant - 1 message in about 1-2 minutes. This is not connection issue of my vps cause I've tested on vps provided by T1M3C guy from russian support. the same issue was there.

**Comment by paulinewoon** [comment]
I have the same issue onWebSocketError: Timeout on Read

So is this a Binance issue? what should I do...contact Binance...does it help?

**Comment by SgtBatten** [comment]
It's simply timing out. Your connection is not obtaining all the data required fast enough. New version will have a longer timeout

**Comment by paulinewoon** [comment]
Does it mean I need to upgrade my vps server for a faster connection?

**Comment by paulinewoon** [comment]
so I just have to leave it on overnight for it to connect?
