### ISSUE TITLE
ERROR BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read

### ISSUE THREAD

**Issue by pepps1976** [taniman/profit-trailer#1169]
Getting the Error

ERROR BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read

I have about 60 Buy Logs I have some true trailing

but never any sales or pairs log?

can anyone help

**Comment by YoJeff** [comment]
Seriously.  One issue below.  No Duplicates.

**Comment by pepps1976** [comment]
I'm new here what have I done wrong I just need a bit of help

Sorry
