### ISSUE TITLE
@taniman

### ISSUE THREAD

**Issue by woodyalien** [taniman/profit-trailer#1170]
please https://github.com/taniman/profit-trailer/issues/980

**Comment by woodyalien** [comment]
@YoJeff @taniman frustrating how this is being handled
it would be more honorable at least to say "we are not going to work on that, please live with this"

**Comment by woodyalien** [comment]
@YoJeff @taniman @jadiesel frustrating how this is being handled
it would be more honorable at least to say "we are not going to work on that, please live with this"

**Comment by YoJeff** [comment]
It would be even more honorable to comment on an existing issue rather than creating a new one.   Even closed ones still ping participants.

**Comment by woodyalien** [comment]
@YoJeff I did, please open that link and comment there!
