### ISSUE TITLE
INVALID LICENSE on with ProfitPi on Raspberry Pi

### ISSUE THREAD

**Issue by ahmedabdrapo** [taniman/profit-trailer#1173]
Hello
For couple of days now I tried everything but ProfitTrailer keeps giving me the Error "INVALID LICENSE" on my Raspberry Pi 3.

The robot is working fine with the same license key on Windows 10 .. But I want to use it on my RPi

What is the problem? and how to fix it and why you never answer your support Tickets????
![2018-02-19_9-57-44]()

**Comment by aries-delossantos** [comment]
You shoudn't post your api keys unless you have ip whitelisting.

**Comment by cupid-stunt** [comment]
Yes, your going to get used and abused showing your keys. Take it away and change your keys straight away before someone gives you a very bad day!

**Comment by ingeniumdesign** [comment]
OMG boi, give the world all keys....

**Comment by cristianserban** [comment]
@ahmedabdrapo be carefull with your data :) enter discord channel in support and the guys will help you

**Comment by ahmedabdrapo** [comment]
Thank You guys, didn't notice that I published my api
Discord never reply anyway
