### ISSUE TITLE
I found 2 small things. I think.

### ISSUE THREAD

**Issue by ShadowOnTheLand** [taniman/profit-trailer#1174]
Let me start off by saying the work you do is fantastic and I am very pleased with your bot. I have a couple of things that I'd like to share that I've found out.

1st: I haven't looked at the code myself, but I get the feeling that the change to LOWBB that you worked into this last version is slightly off. It hasn't bought anything all day today.

Now that being said I have been watching it and it SHOULD have bought ETHUSDT today. I watched the Ask price go lower then both the Current BB and the BB Trigger. The Current value was no where near where it should have been. 

I reset the triggers by changing to and saving Buy EMAGAIN, then when I switched back to LOWBB it worked perfectly. If it trails and doesn't buy then something appears to go wrong with the triggers and the current value.

2nd: I know that you're working on Manual buys and how the bot deals with them. However I will point out that in version *.17 and sooner, when I did a manual buy on the exchange it would drop the coin into the Pairs Log. Since the update to *.18 its dropping the coin into DCA Log.

![image](https://user-images.githubusercontent.com/36648256/36399879-e6ca8e66-159b-11e8-86ba-5f62f8f46877.png)

I manually bought BTC and it put it into the DCA Log with a DCA flag of 2 buys, this is not accurate. I do not believe there is a way to change that setting once it's flagged DCA.

**Comment by taniman** [comment]
1st. The case on LOWBB is still open. there are people saying it's not buying at the right time. and you say it's not buying. :)
I have started investigations on the lowBB to see IF and where there is a problem.

2nd. Nothing changed regarding manual buys. If the coin drops into DCA that's because DCA is enabled for these coins or not? Or do you have ALL_DCA_enabled = false? 
Further more I do not recommend manual buys especially not on binance currently.

**Comment by ShadowOnTheLand** [comment]
So my understanding is that when LOWBB price gets to within your buy trigger, so for me, it's at 5%

MY understanding of the "Current Value" variable is that it is percentage above or below the LOWBB line.

If it's supposed to work along the same lines as EMAGAIN, it will show what the current value is in relation to the LOWBB line. When it gets to within the appropriate range it should start trailing. Per my current understanding...

At this point you're probably wondering where I'm going with this eh? Well, per my understanding, which is PROBABLY wrong, this seems very odd numbers to me:

![image](https://user-images.githubusercontent.com/36648256/36458552-62e8ffdc-167d-11e8-8897-b7d2ebd46284.png)

Now if this was EMAGAIN and my Trigger was -0.75, this would be like Uh? Why didn't you buy bot?

If this behavior is perfectly normal, then that's okay too. It just shows my lack of complete understanding of exactly how the bot works. That's okay too! Because it means I can learn more!

**Comment by taniman** [comment]
The current value for LOWBB is a bit new and under development. The actual logic looks at the 
current BB and BB trigger to trail. So look at those values.

About the LOWBB buys. This has been fixed in 1.2.6.19
