### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ShadowOnTheLand** [taniman/profit-trailer#1175]
This is more of a Wiki issue, I don't know where to post it otherwise. Also there is a feature request as well. I'm going to use the exact numbers in the Wiki.

First up; Per the Wiki:

ALL_max_cost_percentage = 2
Valid Values: Decimal value greater or equal to 0. 
Indicate % of total current value (TCV) of account we will use to buy 
This property only works if ALL_max_cost = 0. This is useful when your balance changes frequently and you want to keep a minimum balance. 

This is pretty straight forward. Buy x% of my bankroll per coin that I purchase.

Secondly; Per the Wiki

ALL_min_buy_balance_percentage = 60
Valid Values: Decimal value greater or equal to 0.
Only buy coins if the buy cost will not let your balance go below specified amount in %.
Example. To always leave 60% of my account untouched. set value to 60%
This property only works if ALL_min_buy_balance = 0

This is also pretty straightforward. Reserve 60% of my bankroll as untouchable (Save for DCA for example)

When you combine the two together however... One would think, with the way it's worded, that you would buy 2% of the 40% that you have available to buy (Leaving 60% in reserve). The way it's worded one could be lead to believe that you could buy any number of pairs at whatever Percentage you want, and it will buy that up to 100% of the 40% you have allocated to buying coins.

Example:

I have 100 btc bankroll, I want to reserve 60% (60 BTC) meaning I have 40 btc left over to invest, and 2% of that is: 0.4 btc per coin purchase. I could then use all of that to buy up pairs(2% is kinda low for this example), and use the 60% (60 btc) for DCA levels.

Reading the wiki that was how I understood it to work, which is AWESOME!

That's not how it works. You'd buy 2% of your entire bankroll and you could do that 20 times and at the 21st attempt the bot will stop you. This is less important at high levels of investment, but when you're short on the bankroll and you want to compound you can only do 1 or the other.

Compound or have the ability to DCA correctly. This leads me into my suggestion.

I know NUMEROUS people who want to compound their profits, but can't DCA properly because they need to invest a significant portion of their bankroll to be able to have appreciable profits early on. Not to mention that Binance has very high minimum purchase requirements (I know that's changing a little).

So being able to tell the bot something along the lines of this:

ALL_dca_reserve = 0
ALL_dca_reserve_percentage: 60
ALL_max_cost = 0
All_max_cost_percentage = 12.5

This would be REALLY, REALLY helpful. It would allow for lower bankrolls to compound effectively AND dca effectively at the same time!

**Comment by taniman** [comment]
I wish all created issues/requests where as thorough as this one. 
Straight on point, with proper knowledge of how the bot works.

With that said. I'll see what I can do for you on the enhancement release we are working on. else it will be the next one. 

But how would DCA_reserve work in combination with min_buy_balance?

**Comment by ShadowOnTheLand** [comment]
min_buy_balance would over-ride the DCA_Reserve should the DCA_reserve try to eat into the min_buy_balance.

DCA reserve should only limit your max_cost_percentage values.

**Comment by ShadowOnTheLand** [comment]
I would also like to add, that should you try to buy more then 100% is the allotted balance from the dca reserve, the bot just does nothing. Just like how it works right now with min_buy_balance.

**Comment by DragonBtc93** [comment]
Give us emacross sell with minimum profit

**Comment by taniman** [comment]
I am going to change max_cost_percentage to work the way you describe instead of creating a new option that looks similar. as to avoid confusion
