### ISSUE TITLE
Feature Request (Primary Secondary Base)

### ISSUE THREAD

**Issue by majhealth** [taniman/profit-trailer#1177]
So I was chatting with others in the community about this last night and decided it would be a good idea to submit this as a feature request.

If the bot is able to mathematically crunch the numbers for values based off a set base, wouldn't it be possible to essentially double the Math allowing a single bot to make decisions to buy and sell pairs based off multiple bases? 
For example I could setup a base as ETH and USDT. If 
ie.. ETH is increasing heavily and the pair the Bot purchased is loosing value of the original purchase because of the increased ETH price vs the original traded pair. It could then be able to determine if USDT is a better currency to exchange to rather than taking a loss on ETH trading. This essentially allows for two outs to reduce risk of trades. This ultimately would also allow the bot to then purchase back into ETH on a dip talking a potential profit or buy back into a new pair with USDT to again potentially gain on ETH.

Thinking of this as a Primary Secondary base setup. I for one am not using the bot to try and just increase total holdings of coins, but more to gain a daily steady flow of interest that allows for increased income which should ultimately result in more holdings over time.

**Comment by cristianserban** [comment]
it would be nice ... **but not posible**.. same pairs cannot be used at the same time in same account but different markets.
solution for this to use one bot intance per market and make sure that pairs used in one market dont messup the pairs in the other one.
