### ISSUE TITLE
Feature Request... A decreasing "trailing.profit" 

### ISSUE THREAD

**Issue by Jamavo83** [taniman/profit-trailer#1180]
Just to start I want to say thank you for this program.  Not only have I made BTC, but I have a ton of fun tweaking and playing around with it trying to find the perfect settings.  Thank You.

I was just watching my bot.  I have my settings at 1.2% profit with a 0.3 trailing profit.  I watched my 8 DCA'd Bitcoin Cash pair ($9000) came all the way up to 88% profit.  Then it fell, and fell.  Now, I thought about running in there and changing the settings, taking my $80+ profit and freeing up my capital.  But I didn't want emotion take over and would let the bot sell when it reached the 1.5% total needed to make a sale (1.2% trigger and a 0.3% trail).  

After this happened, I thought it might be nice to have a setting for large DCA'd pairs to be able to have a INCREASING profit trail. (I had it backwards before and had to edit)

Example.

DCA more than 4 times, I want you to start with a profit of 0.2 and a trail of 0.15 (0.35% total profit needed to even think of selling), if you hit 0.4 take my trail up to 0.25 trail (0.45%, but now instead of a minimum profit of 0.2%, it's 0.25%), 0.6 to a 0.3 (0.9% needed, 0.3 min profit, but much more looser setting for price to flicker a little.), 0.8 to a 0.35 (now only 1.15% needed, but 0.45% profit) and 0.6 to a 0.4 trail (you get the idea).  Or do a percentage, for ever 0.1% profit made, take my trailup 5%. 

For my Bitcoin Cash sale above, I would have been able to sell at 0.4%ish profit.  But if the price had continued to rise, my trail would have increase a little until hitting a max and I can still hit those higher 2%+ profits.

I bring it up cause bags can sometimes take a long time to get rid of.  I have a $2800 one that I have been holding for 21 days.  If I was able to have sold that pair at a 0.2% to free up my capital, I would have already made the profit that I would have loss, selling at 0.2% vs. 1.2%,  by trading other pairs over the past 21 days with that freed up capital.

I hope that explains my idea well enough, Let me know what you think.
Thanks,
Jason

**Comment by taniman** [comment]
Please take a look at milestone 1.2.7 and 1.2.8 and 1.2.9 I think one of them already has something similar to this. Check and let me know

**Comment by RichardLuo0506** [comment]
And increasing trailing_buy when we're deeper in DCA would be nice.
