### ISSUE TITLE
[Feature Request] - Add a sell button into the webinterface

### ISSUE THREAD

**Issue by Bertilax** [taniman/profit-trailer#1181]
Would be cool if you could add a maual sell button into the webinterface in pairs and dca.
If a coin could not reach the Profit in the settings, or would not come to Profit in longer time, it would be cool to manual sell it from the Interface.
So the calculation 
Example : 
If the Settings are 1,5% Profit and the coin reaches 0,8% and this for longer time you would be able to sell
it with Profit and give another coin the chance to be traded...

**Comment by cristianserban** [comment]
duplicate
