### ISSUE TITLE
Doubled up on discord accounts, need to remove license from one

### ISSUE THREAD

**Issue by yosip1115** [taniman/profit-trailer#1183]
Hey guys,

I accidentally created two discord accounts since there was no prompt to log into an existing discord from the invite link in the post purchase email. 

I have my email claimed on one of them, and my activation license claimed on the other one. I need my activation license removed from the one I just created today (Mike O) so I can add it onto my original discord which has my email address claimed. 

My email is yosip1115@hotmail.com for reference, thank you

**Comment by YoJeff** [comment]
These types of licensing issues are handled via support tickets.
https://support.profittrailer.com/
