### ISSUE TITLE
Trigger resetting after retraction

### ISSUE THREAD

**Issue by VeloceTrader** [taniman/profit-trailer#1184]
Been watching a coin it picked up, have the sell triggers set higher than normal at 5%.  Coin rises above limit and sets new sell value but rides my 2% trailing profit down.  After some time it reverts to the 5% limit and no trigger remains as the coin continues down.  Watched that on one coin happen twice, had it happen a third time while sleeping.  Reconfigured the sell value for just that coin to monitor it closer and it worked as it should when I had a trailing profit set.  Still, with no programs feeding the PT, there shouldn't be any change in the trigger.

**Comment by taniman** [comment]
I will need to to define this a bit more clear. AS I do not understand the blob of text

**Comment by VeloceTrader** [comment]
Min profit set @ 5
Trailing offset set @ 2

Coin takes a ride to say 6.5 and sets new high, drops back to 4.4 and lower, the trigger resets to 5.  Shouldn't it try to sell at 4.5 in that setup?

**Comment by taniman** [comment]
No, the bot will  never sell below your sell_value
