### ISSUE TITLE
Binance - ETH market - It seems like SOM is being ignored 

### ISSUE THREAD

**Issue by aleintherocks** [taniman/profit-trailer#1186]
Hi! I think I found a problem, seems like PT is ignoring SOM settings for Pairs  

I'm trading in **BINANCE** with **ETH** market, using **PT 1.2.6.18** and **PT 1.2.6.16**

I have set in my pairs file _[ALL_sell_only_mode = true]_ and _[BCPTETH_sell_only_mode = true]_, and while in the PT website the _SOM is marked as TRUE and set in color RED_ and _SOMO is marked as FALSE and set in color GREEN_; in my Possible Buy Log all the pairs are set to be bought in a near future time: EMAGAIN - (false) / EMAGAIN - (true trailing...) instead of showing pairs as inactive _[SOM ENABLED]_. The strange thing about this is that _[ALL_trading_enabled = true/false]_ and _[ALL_enabled_pairs = ADAETH,ADXETH]_ are working perfectly. **NOTE: This is not happening in BINANCE using BTC Market, I haven't checked BNB Market though** 

IMAGE of PAIRS.properties - SOM is active 
![binance-eth-pair](https://user-images.githubusercontent.com/10429318/36443889-a5fd3100-163f-11e8-8f7f-7e5d7ac63606.jpg)
**Binance ETH Market**

IMAGE of PT Desktop 1.2.6.16 - **SOM is active but ignored** in Possible Buy Log screen
![binance-eth-pbl_1 2 6 16](https://user-images.githubusercontent.com/10429318/36444921-3f5a842c-1642-11e8-9e3b-9d78f7457802.jpg)
**Binance ETH Market**

IMAGE of PT Desktop 1.2.6.18 - **SOM is active but ignored** in Possible Buy Log screen
![binance-eth-pbl](https://user-images.githubusercontent.com/10429318/36443905-b78ac61c-163f-11e8-95c6-bca7885863d7.jpg)
**Binance ETH Market**

IMAGE of PAIRS.properties - SOM is active 
![binance-btc-pair](https://user-images.githubusercontent.com/10429318/36446076-cad49d50-1645-11e8-9d56-681d9674ff36.jpg)
**Binance BTC Market**

IMAGE of PT Desktop 1.2.6.16 **SOM is active and ENFORCED** in Possible Buy Log screen
![binance-btc-pbl](https://user-images.githubusercontent.com/10429318/36445879-312b7fca-1645-11e8-8e28-f1a27c6d8e70.jpg)
**Binance BTC Market**

Please, let me know if you need more info

Thanks!!

**Comment by YoJeff** [comment]
So your complaint is the bot still shows possible buys when in SOM?

**Comment by taniman** [comment]
Please check your settings again. ETH SOM ENABLED MESSAGE is working correctly here

![image](https://user-images.githubusercontent.com/6751341/36447002-58a3162e-1683-11e8-8e8b-4e77ffce74f7.png)
