### ISSUE TITLE
VPS - Error in websocket message ERROR: -1003

### ISSUE THREAD

**Issue by Gitulu** [taniman/profit-trailer#1187]
Hello guys,

Since I switched from my Rig Windows 10 with 2 Binance PT and Feeder to an VPS (without feeder at the moment) I get much faster the "ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API., message" as before.

I contacted the official telegram group which some fantastic guys tried to help me but we need also your dev help for this issue please.

**Setup tried**:

![setup](https://user-images.githubusercontent.com/35115314/36445667-357bab60-167f-11e8-85a1-29fc152b5e1c.jpg)

With instructions from: [https://wiki.profittrailer.io/doku.php/vps_setup_guide](url)
Furthermore attached you will find all my logs.

[Websocket.zip](https://github.com/taniman/profit-trailer/files/1741649/Websocket.zip)

It seems PT does not use the Websocket as intended, could you also please explain how PT will exactly use the Websocket?

It would maybe great to add a parameter where the users can set in the settings the calls manually to prevent this. Or if the the PT have reached the max buy pairs just pull only the data for this until one pair get sold not all.

Please let me know if you need anything else.
In the meantime I can not use the bot.

Thanks 
Gitulu

**Comment by YoJeff** [comment]
Is your VPS in japan?

**Comment by Gitulu** [comment]
Hi Yojeff,

Thanks for your very fast response.
Its in Germany

![image](https://user-images.githubusercontent.com/35115314/36446517-cf895b42-1681-11e8-8170-784aa81980d6.png)

**Comment by YoJeff** [comment]
You have no shared api keys between the two instances?

**Comment by Gitulu** [comment]
I use for every Bot 2 different API keys so in total 4 keys.

**Comment by YoJeff** [comment]
I dunno then.   Something is funny with your setup.   Telegram support has been dead for a while, checkout the vps-support channel in discord.

**Comment by Gitulu** [comment]
Thanks I will try via discord.
Will the bot not use the Websocket for Binance like in the ticket: "#618"?

**Comment by taniman** [comment]
@Gitulu the bot is currently using Websockets for the last 4 weeks for sure. I have heard of people running 3 bots, So depending on your server location 2 bots should be doable.

But all in all currently for Binance it's a struggle so just 1 binance bot per server is better.

**Comment by Gitulu** [comment]
Is it possible to run 2 Binance bots on the same VPS with different IPs (incl monitoring via browser)?
This would be very helpful to find a workaround for this, maybe with a guide for Contabo.

Thanks a lot guys

**Comment by taniman** [comment]
I  think you are getting into the setup realm which is not what this platform is intended for. 

Personally I would not know hot to use 2 different ips on same VPS

**Comment by Gidubi** [comment]
Hello guys,

Thank you for your support.

It seems I have found the issue.
I have tried the version 12 and I does not got banned any more.
This happens with v12 & v18 with 2 bots on binance. Other users have partially the same issue.

Furthermore I have talked to an external developer.
To use different outgoing IPs, this should normally implemented in the software.

Attached you will find the logs from the version 12.
[ProfitTrailer_bot1_v12.log](https://github.com/taniman/profit-trailer/files/1750778/ProfitTrailer_bot1_v12.log)

It would be great if you can find a way to fix this or to give the users more control about this with more settings.

Thank you

**Comment by Gitulu** [comment]
Hello guys,

Thank you for your support.

It seems I have found the issue.
I have tried the version 12 and I does not got banned any more.
This happens with v12 & v18 with 2 bots on binance. Other users have partially the same issue.

Furthermore I have talked to an external developer.
To use different outgoing IPs, this should normally implemented in the software.

Attached you will find the logs from the version 12.
[ProfitTrailer_bot1_v12.log](https://github.com/taniman/profit-trailer/files/1750778/ProfitTrailer_bot1_v12.log)

It would be great if you can find a way to fix this or to give the users more control about this with more settings.

Thank you
