### ISSUE TITLE
Don't show spread or buy volume messages if we can't buy anyway

### ISSUE THREAD

**Issue by merricrubiyat** [taniman/profit-trailer#1188]
In SOM the log shouldn't bother telling me about spread being too big or unavailable buy volume. Probably other messages like that too

**Comment by YoJeff** [comment]
This is by design.   How do you tweak your settings without any feedback?

**Comment by merricrubiyat** [comment]
@YoJeff I think you misread, if the bot is in sell only mode, spamming me about volume etc. doesn't make sense.

**Comment by merricrubiyat** [comment]
And the answer to your question is "test mode", not SOM, if that's what you were getting at.

Can we not be so hasty about closing bugs without discussion? This is really inappropriate
