### ISSUE TITLE
[Anti-Bag-Growing]: Possible strategy scenario

### ISSUE THREAD

**Issue by scoutband** [taniman/profit-trailer#119]
It would be interesting to apply a sequence of actions to get out of a potential bag this way.

if the coin drop, for example, 5% put it in DCA and if it continues to drop by another 5% (so in total 10%) then activates the stop loss.

In this way I define a loss acceptance threshold and free the coin for any other trades, without however taking the opportunity to retrieve it as soon as possible through DCA instead of applying a dry stop loss without any recovery possibility.

It is easy to manage the uptrend as well as in the crypto coin it is difficult to handle the down trend and thus the bag phenomenon.
It is not a solution but only a mitigation action

**Comment by scoutband** [comment]
NOTE: 
Percentages are at discrection to the user

**Comment by jadiesel** [comment]
I have a slightly simpler take on this.
If the price drops x%
Check if trend flat or up = DCA
Check if Trend down = Stoploss

**Comment by scoutband** [comment]
Even this approach is very interesting, in any case implies that the coin is automatically placed in DCA as well as in the method I have described.

I hope that the opportunity to put into DCA automatically will be considered.
Regardless of the methodology chosen is a feature that in my opinion enriches the potential of PB

**Comment by taniman** [comment]
i will split this into 2.
1. create options put mark a coin as DCA enabled on price drop..
2. sometime near in the future, introduce a trend indicator

This trend indicator could then be combined with
buy_strategy
sell_strategy
stop_loss

like buy only on uptrend.
stop_loss only on donwtrend

But there are a lot of trend indicators. So gonna need to choose 1 or 2 good ones
