### ISSUE TITLE
USDT - Buys going from pairs to dust log 

### ISSUE THREAD

**Issue by planetofzog** [taniman/profit-trailer#1194]
This is not an issue with the latest version as it was happening with the previous version I just tried but my issue is this -
On Bittrex, I've just switched to USDT to test it and everything starts out in the pairs log, but instead of going to DCA almost eveything ends up in the dust log. Infact my DCA is set to -3 so many of these should be in the pairs still.
I'm buying the minimum or just above that Bittrex allow - $3.55, is the issue it is too low?

I'm running 6 pairs max, its dropping these to dust and then trying to buy more because it considers these dust so have enabled SOM for now.

These have gone straight to dust - they are above the minimum order for Bittrex, Is there an amount that the bot recognises as dust here or have I done something else wrong?
![capture](https://user-images.githubusercontent.com/36609113/36463283-de977b8e-16c0-11e8-986d-1f4f52868941.GIF)

Actually it may be they dump straight to dust because the current value falls below my all max cost of 3.55 as i've just seen one jump from dust to pairs once it went back over the 3.55.

**Comment by planetofzog** [comment]
Just an add on to say that a few hours later a lot of them are back in the pairs file having climbed higher. Weird, is there a minimum price set in PT where they'll go to dust and not DCA if their 'CURRENT VALUE' falls below a certain price?

**Comment by YoJeff** [comment]
This is how dust works.  It the value falls below dust, it becomes dust.   If you buy near dust, and it drops below dust, it IS dust.
