### ISSUE TITLE
Miscalculations from the algo?

### ISSUE THREAD

**Issue by Salocin90** [taniman/profit-trailer#1195]
Hi, I'm currently using this strat settings: 

- ALL_buy_strategy = EMAGAIN
- ALL_buy_value= -3.5
- ALL_trailing_buy = 0.5

- EMA_period = 300
- EMA_1= 24
- EMA_2= 12

This strat calculates the distance in % from the LOWEST EMA to the trigger value (-3.5%) and when the price hits that threshold buys.
The thing is, I've watched on several pairs that this is not what the UI shows on current value.
The possibilities are:

- The algo is miscalculating the current value
- There's delay between Trading View and the Bot
- I'm not getting the math right

Can someone clarify what's going on here?
![1](https://user-images.githubusercontent.com/36689046/36466594-b25e27a4-16b9-11e8-94f6-c8e36f87f18d.png)
![2](https://user-images.githubusercontent.com/36689046/36466595-b291c3de-16b9-11e8-88ac-1298ac7d8b16.png)
![3](https://user-images.githubusercontent.com/36689046/36466596-b2bf7e82-16b9-11e8-9a9a-4e1a80124c01.png)

**Comment by JAR3D** [comment]
Hi from what I see in your pics, the price don't even touch your trigger value of -3.5%. It will only trails once it touch the trigger.

**Comment by Salocin90** [comment]
Why are you explaining something that i already did? I'm saying that the difference in % doesn't match at all and they should!

**Comment by taniman** [comment]
I am pretty sure this is related to the other issues i am looking at already with binance incorrect buys. 

I am working on a release. So wait for that and try again
