### ISSUE TITLE
Missing pending orders on Bittrex

### ISSUE THREAD

**Issue by bluefuzz** [taniman/profit-trailer#1196]
I had 3 bags go into the pending log yesterday. Only one of them is showing up in the PT interface. Also the value of the 2 missing pairs is missing from the calculated TCV and TPV. All three coins show as open orders when logged into Bittrex. What to do?

The coin I can see is CVC. ETH and NBT are 'missing'.

Here's a paste of the relevant bit of the log, but there's nothing I can see. All coins went to pending on the 20th. https://pastebin.com/DHaFtrAE

**Comment by taniman** [comment]
I would prefer to see these 2 pending orders on bittrex and a screenshot of them missing in pending log.

**Comment by bluefuzz** [comment]
Her's a couple of screenshots.
![screen shot 2018-02-21 at 12 49 49](https://user-images.githubusercontent.com/5837578/36478703-0a67b2a2-1706-11e8-99f1-894e93e45a42.png)
![screen shot 2018-02-21 at 12 50 24](https://user-images.githubusercontent.com/5837578/36478704-0a7fccd4-1706-11e8-96cc-72756709eb20.png)

**Comment by felipeff** [comment]
Same happens for me. Only on bittrex. the pending orders are ok on my binance account

**Comment by SgtBatten** [comment]
@bluefuzz please share your pairs file also

**Comment by bluefuzz** [comment]
I use feeder so my pairs change with the market, but it's been 'boring' forever ... ;-)

Here is my current pairs: https://pastebin.com/afAk8mH2

**Comment by taniman** [comment]
@bluefuzz  I pressume you have already restarted your bot?

**Comment by bluefuzz** [comment]
I just restarted my Bittrex bot (again) and the missing pending coins are now showing again in PT -
 and the TCV/TPV is correct. Nothing else has changed AFAIK.

**Comment by felipeff** [comment]
same here. restarted and I can see the pending orders now

**Comment by taniman** [comment]
@bluefuzz if you restarted and nothing changed that means it was a problem on bittrex api not returning the data. All that we get is from the exchange and displayed.
