### ISSUE TITLE
BINANCE: Correct Target of Pairs Link

### ISSUE THREAD

**Issue by zapedge** [taniman/profit-trailer#1197]
It would be nice if the link on the trading Pair would connect to

https://www.binance.com/tradeDetail.html?symbol=SUB_ETH

instead of

https://www.binance.com/trade.html?symbol=SUB_ETH

because the non-detailed view is rather useless IMHO

**Comment by taniman** [comment]
it would be nice if you could search for existing issues instead of just creating a duplicate

**Comment by zapedge** [comment]
i actually did a search before
