### ISSUE TITLE
PT will sell a bag on a stoplosstrigger that just DCAed before recalculating the %profit of the bag after DCA. 

### ISSUE THREAD

**Issue by Cryptoqueb** [taniman/profit-trailer#1198]
Pretty much all in the title. I have 2 max dca level and a stoplosstrigger. If a bag is dca lvl 1 and trail on a lvl 2 it will eventually dca (reaching max lvl) then will sell 1/2 of the bag (what I had before the final dca). Happend twice in the last 24h it is quite frustrating. 

1st time : 

Gain sell (profit was made...) :2018-02-20 21:08:44 | RDN/BTC | Sell | 0.00031955 | 10 | 0.00052764 BNB | 0.00319550 BTC

((Stoplosstrigger sell )) : 2018-02-20 20:08:35 | RDN/BTC | Sell | 0.00030515 | 7 | 0.00035794 BNB | 0.00213605 BTC
((Stoplosstrigger sell )) : 2018-02-20 20:08:35 | RDN/BTC | Sell | 0.00030514 | 3 | 0.00014541 BNB | 0.00091542 BTC
(6 seconds in between the DCA buy and the Stoplosstrigger sell!)

((DCA buy )) 2018-02-20 20:08:29 | RDN/BTC | Buy | 0.00030773 | 10 | 0.00051317 BNB | 0.00307730 BTC
2018-02-20 17:37:39 | RDN/BTC | Buy | 0.00031624 | 5 | 0.00026500 BNB | 0.00158120 BTC
2018-02-20 16:42:13 | RDN/BTC | Buy | 0.00032394 | 5 | 0.00026831 BNB | 0.00161970 BTC

2nd time : 

((Stoplosstrigger sell )) 2018-02-21 12:51:32 | ENJ/BTC | Sell | 0.00001746 | 172 | 0.00051084 BNB | 0.00300312 BTC
(8 seconds in between the DCA buy and the Stoplosstrigger sell!)
((DCA buy )) 2018-02-21 12:51:26 | ENJ/BTC | Buy | 0.00001750 | 172 | 0.00051143 BNB | 0.00301000 BTC
2018-02-21 09:37:25 | ENJ/BTC | Buy | 0.00001809 | 86 | 0.00025880 BNB | 0.00155574 BTC
2018-02-21 08:21:07 | ENJ/BTC | Buy | 0.00001864 | 86 | 0.00026630 BNB | 0.00160304 BTC

A timer between a DCA buy and stoplosstrigger sell would be nice.

**Comment by taniman** [comment]
DCA and stoploss triggers is set on the wiki known issues to be avoided.  

There won't be a timer built in. 

What version of the bot is this?

**Comment by Cryptoqueb** [comment]
PT version is 1.5.4. I ended up pushing the  the Stoptriggerloss 3% further than the last DCA. would have to traile quite a bit for it to "bug" again. Do you plan any fix for this issue one day? I'd like my DCAs and StopLossTrigger to be more tight then they are now. thx for responding.

**Comment by Cryptoqueb** [comment]
https://wiki.profittrailer.io/doku.php/known_issues was there indeed. Should have read the whole wiki. This is on me.

**Comment by taniman** [comment]
I think it's still under investigation.  send me your settings file. that was causing this. So I can have a better look.

**Comment by taniman** [comment]
Yes. This issue is a duplicate that needs investigation. Add your log files to #284
