### ISSUE TITLE
ETH price drop not working on Binance

### ISSUE THREAD

**Issue by vredirect** [taniman/profit-trailer#1199]
Hi,
ETH dropped over 10% today and my triggers didn't trigger. This should be solved as soon as possible, as it is a huge safety problem.
Here is a screenshot showing the drop at -10.12% and no SOM active.
My settings were at 8 (drop) and 6 (recover).
Thanks,
Vick

![screen shot 2018-02-21 at 20 09 19](https://user-images.githubusercontent.com/36277719/36500113-9c7f930c-1743-11e8-80ad-57baaf7a02e0.png)

**Comment by miladzamani** [comment]
same issue

**Comment by SgtBatten** [comment]
@miladzamani @vredirect That setting is made up.

The only setting is ALL_btc_price_drop_trigger etc. you cannot just change it to ETH. it only works base don btc currently even if your bot is not trading btc.

**Comment by TeleTubby9** [comment]
I was thinking about substituting ETH for BTC in the trigger. Now it appears that won't work.  

Since the alt coin market tends to drop (bags) when bitcoin goes up (not sure about the inverse) it may not be such a bad thing just to leave it with BTC in the line.
