### ISSUE TITLE
Anyone know which PT file the "sales log" information is stored in??

### ISSUE THREAD

**Issue by TeleTubby9** [taniman/profit-trailer#1201]
Anyone know which PT file the "sales log" information is stored in??

I did an upgrade to the latest version which requires stopping the bot. After the update and restarting the bot, everything in the sales log was gone. I would like to attempt to recover it to use it for analytical purposes. 

As a newbie I removed and replaced all the files except the 5 that were edited - app,, config, pairs  etc. Now I vaguely understand maybe only one file needs to be replaced for an upgrade. Which one?

**Comment by YoJeff** [comment]
Upgrade instructions are on the wiki, questions are for discord.
