### ISSUE TITLE
BUG: DCA Triggers Not Resetting

### ISSUE THREAD

**Issue by HojouFotytu** [taniman/profit-trailer#1203]
I've noticed since the last update that when I make I manual purchase and PT finally notices and adds it to my holdings, it automatically has the DCA level from the last time I held the pair.

I'm not sure if I manually sold that pair the prior time, or if PT sold them.

Anyway, three pairs I just bought manually immediately have a DCA of level 3, 1, and 5.

**Comment by taniman** [comment]
This is has been the case for a long time. If you buy manually the DCA won't reset. We will implement a feature to reset DCA counter in the new features release
