### ISSUE TITLE
Feature Request:  Panic Sell & Panic Buy

### ISSUE THREAD

**Issue by HojouFotytu** [taniman/profit-trailer#1205]
Rather than being forced to edit the config files, it would be much easier if there was a small panic sell button next to each pair in the Pairs/DCA log.

I frequently find that there is a coin I want to get out of, and can see it WILL NOT get to the profit margin i've set in pairs or DCA config.  So I either have to quickly edit the config files to panic sell that coin, or quickly add a new XXXXX_sell_value for that pair, or I have to sell the coin manually on the exchange.  The later completely excludes it from my PT sales record.  

All of these options are slow, cumbersome and inefficient, often leading to missed opportunities to get out of a bag without a loss, during the few moments this is possible.

A simple "Sell Now" button in the Pairs and DCA is needed.

And as someone mentioned in another issue thread, it would also be nice to have a "Buy Now" button in the Possible Buy Log.

The bot is nice, but it isn't perfect, and requires some over-ride controls which don't require always making temporary edits to the config files, then immediately reversing those edits.

**Comment by taniman** [comment]
There are implications and things we need to think about before implementing these buttons. It's already on our to do list and has been asked multiple times.
