### ISSUE TITLE
Feature request: Do not overwrite firstBought value when token is DCAed

### ISSUE THREAD

**Issue by emx0r** [taniman/profit-trailer#1206]
Hi,

would it be possible to keep the firstBought value in ProfitTrailerData.json still the same to be original timestamp of the first buy? I reckon it get changed whenever PT does DCA buy.
This way there's no clear information for how long I hold a pair and I'm not able to do any statistic over it.

It would good to either not change that value or if this is not possible because of some reason, to have a new value in json to always indicate the timestamp of the original buy.

**Comment by MartinacPlus** [comment]
I fully agree with emx0r. I calculate detailed statistics in Excel and market exposure time (MET) is an important metric for me. I would like to calculate MET/profit ratio for each traded pair, but now it is not possible.

The charting, simulation, what if analyses, MFE & MAE and related back-testing of stop-loss and profit-target levels, is insufficient in PT, so at least it should provide the data in text format somewhere (json, plain txt, xml, ...).

Thank you for consideration.

**Comment by taniman** [comment]
Added to 2.1.0
