### ISSUE TITLE
SMA/EMASPREAD improvements

### ISSUE THREAD

**Issue by bgutmann** [taniman/profit-trailer#121]
I just put some thoughts about EMASPREAD into mind. See the following example (red=fast EMA blue=slow EMA). If I set up EMASPREAD to a low positive value it will **buy** if fast EMA will be higher than slow EMA (see green rectangle). That is quite nice and seems correct. PB will now wait for the rise and hopefully **sell** on the green pointer. everything fine until there. But then comes the "problem" because slow EMA is still higher than slow EMA PB will **(directly) buy** after that (red rectangle). Problem is that the chart is falling on that time and that will probably create a bag.

![emaspread](https://user-images.githubusercontent.com/23472989/31408996-a88db946-ae0a-11e7-8673-e83997e95f14.jpg)

How to fix?

Probably you can add some delay after a sell to trigger another buy or just allow one buy while fast EMA is still higher than slow EMA. But I don't think that that will be satisfying. So I suggest the following:
Just add some optional checks to the EMASPREAD buy strategy. I think now there will be something like

- check if fast EMA > x% slow EMA

There should be the first approvement to prevent the buy directly after a sell (if there is a big rise and drop of the coin) add some possibility to define a range:

- check if fast EMA > x% slow EMA **AND** fast EMA < y% slow EMA

Then a second approvement to prevent a buy when this condition will be true the second time (if fast EMA will again cross or getting nearer to the slow EMA line because of a drop).

- check if fast EMA > x% slow EMA **AND** fast EMA < y% slow EMA **AND** fast EMA line trend is up

With this additional checks it will be possible to use EMASPREAD without having the problems to directly buy after a sell by GAIN and it should prevent a buy on a dropping chart.

**Comment by bgutmann** [comment]
EMASPREAD is really well working but that check for SMA/EMA trend and not buy if trend goes down will be a huge advantage to the actual behaviour.
Getting some good buys and sells on rising chart but then got immediately a bag on nearly top or slightly after top of chart.

**Comment by taniman** [comment]
Some more reading materials http://www.theforexchronicles.com/the-ema-5-and-ema-20-crossover-trading-strategy/

**Comment by Condor60** [comment]
@taniman I see you added this to the 1.2.5/1.2.6 milestone.  Are you working on an EMA or SMA crossover buy strategy?  This would be an amazing enhancement to PT.  Would love to see this addition!
Thanks for everything!  I'm a big fan of PT.
