### ISSUE TITLE
Possible Buy Log losing Current Value

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer#1210]
I keep experiencing an issue that seems has only started occurring after the latest PT release (1.2.6.18) in which often 80% (fluctuates + -) of the pairs listed in the Possible By Log suddenly lose their "Current Value".  The symptom is that out of say 70 pairs, 55 of them will suddenly show "0.00" for the Current Value and then will stay that way.

As soon as I restart PT, all of the 70 pairs suddenly have correct Current Values again...and it also suddenly makes a handful of buys.  It seems that while these pairs are in this limbo "0.00" Current Value state, it does not detect that it should buy them- even though the trigger has already been met to do so, in reality.

Over and over (like 5 times now in the last 24 hours) the fix is to restart PT.  But, I don't always catch this happening in a timely fashion...so, I'm sure I'm missing a lot of good buy opportunities.

**Comment by taniman** [comment]
This problem has been fixed in the new version we are currently testing. I am pretty sure what you are describing is binance freezing
