### ISSUE TITLE
problem in profit calculation

### ISSUE THREAD

**Issue by vinibr81** [taniman/profit-trailer#1213]
![screenshot_1](https://user-images.githubusercontent.com/36087380/36561240-eb04796c-17f1-11e8-8eac-a1d7f4d7cd94.png)
![screenshot_5](https://user-images.githubusercontent.com/36087380/36561245-f0eb1a02-17f1-11e8-822b-c947eeaeaec8.png)

I am using version 1.2.6.18 and it occurs in my opinion a profit miscalculation.

I am sending attached two pictures to understand the situation I will explain them.

Case 1: INSBTC is -2.29 and my profit is at 0.27%
Case 2: INSBTC is -2.46 (lost value) and my profit is at 0.60% (I gained profit)
Case 3: I see the same situation in DCA, I can take an example if necessary

First, I want to understand, is that correct?

Second, I do not understand this calculation, if necessary I share the necessary settings if someone can help me.

Thank you

**Comment by taniman** [comment]
It seems you do not understand the meaning of 24h%, That how much a coin has moved compared to previous day. 
Profit calculation is not based on this value, it's basedon yuor bought price and the current price of a coin
