### ISSUE TITLE
EMAcross missing buy opportunities 

### ISSUE THREAD

**Issue by Steven-Licari** [taniman/profit-trailer#1215]
Can you please assist I'm using EMAcross and I did get it work and it was freaking awesome using these settings but when I got home and charted out some of the days big gainers I realized that my bot had missed several trades, can you please help?

Pairs
#Pairs settings #
ALL_enabled_pairs = ALL
#ALL_max_cost = 0
ALL_max_cost_percentage = 3.9
ALL_min_buy_balance = 0
#ALL_min_buy_balance_percentage = 50
ALL_min_buy_volume = 1000
ALL_min_buy_price = 0.00005
ALL_max_trading_pairs = 2
ALL_max_buy_spread = 3

#EMACROSS TEST
All_buy_strategy = EMACROSS
ALL_buy_value = 0.3
ALL_trailing_buy = 0.15

ALL_sell_strategy = GAIN
ALL_sell_value = 2
ALL_trailing_profit = 0.5

Indicators

EMA_period = 60
EMA_1 = 34
EMA_2 = 13
EMA_cross_candles = 2

**Comment by mattbuster** [comment]
im also having a similar issue where PT is buying after the specified candle window

**Comment by taniman** [comment]
fixed in 1.2.6.19
