### ISSUE TITLE
setting up bought price on profit trailer.

### ISSUE THREAD

**Issue by dawalyr1** [taniman/profit-trailer#1216]
I purchased all my alt coins using ETH on Binance exchange. Therefore, to set up my bought price on profit trailer, should i put the bought price in term of ETH value per coin or fiat (USD) value per coin? 
this brings me to my next question, even though i bought all my altcoins using ETH, do i have to put ETH for MARKET in PAIRS.properties files for my future purchases (example ADAETH)? OR Can i change it to BTC (examle ADABTC). I hope my questions is not too confusing. Please help.

**Comment by taniman** [comment]
You need to use the ETH market, else the bot will not recognize the buys
