### ISSUE TITLE
Feature Request:  Pair Link Options

### ISSUE THREAD

**Issue by HojouFotytu** [taniman/profit-trailer#1217]
Is it possible to add an application setting which allows the user to specify where the pair link leads?   For example "Exchange" (whatever your default exchange may be)  "Tradingview"  "Coinigy".

I'm sure many people are like me, and rely mostly on trading view for charting, or coinigy where they can chart and make trades.   Most of the exchanges (binance, etc) have pretty useless web interfaces...

**Comment by JulesBern** [comment]
There is a javascript addon that does that. Search in the crypro gnome's github repo.

**Comment by taniman** [comment]
The idea is to support the exchanges. If we were to support all these seperate entities it would be a nightmare.
We will need to know how the set the coinpairs. BTC-BCC BTCBCC BTC/BCC BCC/BTC etc etc. 

So no currently we won't support this

**Comment by HojouFotytu** [comment]
> We will need to know how the set the coinpairs. BTC-BCC BTCBCC BTC/BCC BCC/BTC etc etc.

Right.  This didn't even cross my mind.
