### ISSUE TITLE
Save files damaged

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#1221]
Sometimes I get this error. After removing the ProfitTrailerData.json file and replacing it with the backup file everything runs fine again. Wonder what is meant with "Both save files", cause the backup file was fine.

2018-02-23 10:00:24 ERROR Util - Both save files were damaged
2018-02-23 10:00:24 ERROR Util - If you have a backup somewhere please use that or just delete ProfitTrailerData.json

**Comment by taniman** [comment]
ProfitTrailerData.json
ProfitTRailerData.json.backup

Thse 2 files. It is not talking about the file in the backup folder

**Comment by timh77** [comment]
That's the file (ProfitTrailerData.json.backup in the main directory) which I renamed to ProfitTrailerData.json. I didn't even look at the backup folder. I have had it a few times in the past couple of days, all with v18.
