### ISSUE TITLE
Feature Request: Max_Balance

### ISSUE THREAD

**Issue by benzo8** [taniman/profit-trailer#1222]
One should be able to create an artificial balance ceiling, above which the bot does not touch any coins. All calculations of percentage should be based on this ceiling once it's reached.

Reasoning: At the moment, if you want to compound and take regular profits you either have to set an min limit, reducing the effectiveness of the bot overall, or take some balance when it's available, similarly reducing the effectiveness. Also, if you do not do this, profits are likely swallowed by future purchases/DCA's to the point where one bad coin could wipe out all your profits.

Suggestion: Once the bot has reach max_balance, everything above that becomes pure profit, untouched by the bot and able to skimmed off when you want without reducing the amount the bot can trade until it replenishes your drawdown.

**Comment by taniman** [comment]
Iam not seeing the difference with min_buy_balance

**Comment by benzo8** [comment]
When you drawdown the money protected by min_buy_balance, your tradeable balance decreases, so until you recoup that drawdown, your bot is trading less effectively.

e.g.:

1 BTC, min_buy_balance = 0.2 BTC, you trade from 0.8 BTC available. You drawdown 0.2 BTC, suddenly you're trading from 0.6 BTC, so min_buy_percentage, etc. is lowered.

1 BTC, max_balance = 0.8 BTC, you trade from 0.8 BTC. You drawdown 0.2 BTC, and you're still trading from 0.8 BTC. min_buy_balance, etc is unaffected.

**Comment by taniman** [comment]
max_cost_percentage is based on your total current value actually. 
So yes. if the value goes down the max_cost_percentage will go down to compensate for the loss. If it goes up the max_cost goes up with it.

So you can use max_cost to get a static value and always use the max possible like you want (kinda)
or go with max_cost_percentage to make the max_cost a bt more flexible

Are you asking for a way to make max_cost more flexible. 
or
are you asking for a way to let the bot ignore a balance above a set about. (max_balance)

Cause it sounds like you want to do 2 things in 1 go. Or I am confused.

**Comment by benzo8** [comment]
The latter. I would like to be able to say to the bot "Ignore everything above x, but continue to work as you otherwise do." 

At the moment, I have the following options:

1) set min_buy_balance_percentage to 0 (either in PAIRS or DCA, depending on the behaviour I desire) and risk not being able to drawdown profits when I would like to (as they get rolled into later transactions), or
2) set min_buy_balance_percentage to (say) 20%. When I drawdown that 20%, my TCV goes down by 20%, my max_cost_percentage becomes smaller and it takes me longer than it should to get to a point where I can drawdown 20% again.

I would like to be able to: 

3) Set max_balance to (say) 2 BTC and min_buy_percentage (PAIRS and DCA) to whatever works for my strategy and then when my TCV is over 2 BTC, the bot acts as if it _is_ 2 BTC. Once it's 2.4 BTC (for example) I can drawdown 0.4 BTC without affecting my TCV and everything that that in turn affects.

I'm sorry if I'm not explaining this well!

**Comment by YoJeff** [comment]
I think this is splitting hairs a bit.

**Comment by benzo8** [comment]
I'm sorry you think that - it's likely because I am not explaining it well.

There is a fundamental difference between drawing down from the bottom (ie: reducing your capital by taking profit) and drawing down from the top (ie: skimming). 

If I draw down from the bottom, and (in this example) am sitting at with my full min_buy_balance committed. Say my m_b_p is set at 60% with a balance on 1 BTC - I've got 0.4 BTC in the market and I just need to sell one bag to be back over my 60% and be able buy again. But If I choose now to drawdown 0.2 BTC from the bottom, my m_b_p level is now 0.468 BTC (60% of 0.8). I have the same market exposure but I'm 0.068 BTC adrift before I can even think about getting enough headroom to buy again.

With the ability to set a max_balance, if I choose drawdown then my m_b_p doesn't change and I still only need to sell one bag to get back to buying. 

I understand if you think it's splitting hairs, but to my mind lacking this functionality affects the ability to plan ahead and leaves the bot much more susceptible to the movement of the market.

**Comment by YoJeff** [comment]
I get it.  Front door, side door.   Here is another approach -- segregate your profits by moving them out of the bot's view.   Or manage your percentages more frequently.   There is nothing preventing you from managing your profits any way you like -- it just takes a little effort.

**Comment by benzo8** [comment]
Yup, you're totally right. I can change my settings each time my balances change. Doesn't seem particularly "bot-like" but it's definitely another way of ameliorating the issue I (tried to) describe. Thanks for your help.
