### ISSUE TITLE
BOT selling at wrong time (support couldn't help me)

### ISSUE THREAD

**Issue by Psynaptical** [taniman/profit-trailer#1223]
Bot selling at 2% when its set to sell all on GAIN at 6%. I posted this yesterday but it was closed and labelled ask support. I  have talked through this with support on the discord and they were unable to assist me

**Comment by Psynaptical** [comment]
Gold

**Comment by taniman** [comment]
still does not make it a bug. so I am closing it again. 
and please do not reopen the same issue. 

Give support the needed details and proof and ask to pass it on to me

**Comment by taniman** [comment]
or better yes, create a support ticket that will be sent to the correct department
