### ISSUE TITLE
DCA is trying to buy in console for SOM coins

### ISSUE THREAD

**Issue by Gaga604** [taniman/profit-trailer#1225]
Hi, in my PT  console I can see the following:
![image](https://user-images.githubusercontent.com/36766179/36597563-922f1968-18ba-11e8-9e6c-0a5b56c17935.png)

My DCA settings: ignore_sell_only_mode = false

Question (issue?): Why PT is writing "There is not enough volume to make a successfull DCA" while pair is in SOM mode? (  and SOM is not ignored - see setting )  

It makes no sense to write this!

**Comment by YoJeff** [comment]
This is not a support forum.

**Comment by Gaga604** [comment]
ok! Then it's feature request - Please do not show "There is not enough volume to make a successfull DCA" when coin piar is in SOM mode.
