### ISSUE TITLE
Feature Request - Profit Max Hang Time

### ISSUE THREAD

**Issue by networkjackbb** [taniman/profit-trailer#1226]
I would like a new variable that sets a maximum amount of time that the bot will wait for a Trailing Profit fall before going ahead and selling at the already triggered profit %.

Example:
SellProfit: 1.25%
TrailingProfit 0.1%
MaxProfitHangTime: 300

Pair goes to 1.35% profit, then drops to 1.3% and sits there for 6 minutes, then drops to 1.1%

I want PT to sell at 1.3% profit after it has been sitting there at 1.3% at the 5 minute mark.

**Comment by taniman** [comment]
will be included in PT 2.0
