### ISSUE TITLE
UI Correction - Base Currency Price Display on Monitoring page

### ISSUE THREAD

**Issue by networkjackbb** [taniman/profit-trailer#1227]
Monitoring Page: First Column from left, Second Row down.

This cell should display the current price (in USD) of the BaseCurrency, not statically BTC.

**Comment by YoJeff** [comment]
Duplicate

**Comment by djcrypto75** [comment]
Its created by default like this, you get your market usd price in the ticker.
Will keep it like this as BTCUSD is the main coinpair :)

**Comment by networkjackbb** [comment]
If I'm running an instance for ETH, I don't really care about BTC. If I cared about BTC, I can easily run another instance for BTC and in that instance, it should display BTC in that spot.

**Comment by YoJeff** [comment]
You should care about BTC.  It drives everything.  What you shouldn't care about is fiat.

**Comment by networkjackbb** [comment]
I'm completely aware of the influence of BTC on all crypto markets. Thank you.

For the purposes of THIS software and it's interface, I'm more concerned about the base currency I choose to run THIS instance under. And as such, information related to the CHOSEN base currency should be more prominently displayed than something I'm LESS concerned about. That's called good software/UI design.

**Comment by YoJeff** [comment]
The API's for ALL the exchanges are DOCUMENTED.   Make a better MOUSETRAP.

**Comment by networkjackbb** [comment]
Or I could provide feedback to the developer of the software I chosen to give my money to.

Are you suggesting that I should NOT provide feedback? Cause that is REAL easy to do.
