### ISSUE TITLE
[Feature Request] DCA Sell Value Offset (optional)

### ISSUE THREAD

**Issue by jayryemure** [taniman/profit-trailer#1229]
I would like the option to offset my sell value for all pairs according to the number of DCA buy times a bag is in.  Most, if not all, users would probably opt to use a negative offset so that the deeper a bag is in DCA, the lower the percentage profit requirement to sell it.

In DCA.properties:

```
sell_strategy = GAIN
sell_value = 1.5
sell_value_offset = -0.1 // New property

// DCA buy 1 time, sell_value = 1.5
// DCA buy 2 times, sell_value = 1.4
// DCA buy 3 times, sell_value = 1.3
// and so on
```

This will provide the following benefits:

1. Make it easier to get rid of larger DCA bags and free up capital without sacrificing the profit of smaller ones
2. Make the absolute profit (sats, dollars) more consistent across all DCA levels, allows creation of a more coherent and optimized strategy

Note:
PT Feeder has a very similar property (below) but I feel it's suited to Profit Trailer as well since it's usefulness is not inclusive to market conditions.
https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---DCA-Offset-List#dcasellvalueoffset

(I don't think it will break their API either, since this would be optional and it just wouldn't write to this new property)

**Comment by networkjackbb** [comment]
Yes, please.

**Comment by YoJeff** [comment]
Per coin DCA is coming, which will allow you to customize your targets per coin.    This is a game of percentages from top to bottom -- not sure how/why 'absolute profit' comes into play.

**Comment by networkjackbb** [comment]
I don't see anything in this request that talks about 'absolute profit.'
I see a request that allows us to dynamically alter a percentage value by some set of offsets based on some set of events/conditions. Isn't that PT's core value proposition?

**Comment by alvinphang** [comment]
please add in 
PER CON sell value in DCA settings :)
currently only available in PAIRS :( I hope they include it for DCA settings too :)

**Comment by taniman** [comment]
indicating a different buy_value or sell_value based on current DCA level is planned for PT 2.0
