### ISSUE TITLE
UI Enhancement - Today's Profit Percentage

### ISSUE THREAD

**Issue by networkjackbb** [taniman/profit-trailer#1230]
Not exactly sure where it could go, but on the Monitoring page I would like to see Today's Profit displayed as a percentage. I would like see that based against both TCV and TPV.

I'm sure many of us have compounding goals we set for each day and I would like to be able to tell at a glance how well PT is meeting that goal as the day goes on.

**Comment by YoJeff** [comment]
There are 3 or 4 variants of this already requested.
