### ISSUE TITLE
[Feature Request] Manual input for certain coin

### ISSUE THREAD

**Issue by bigworom** [taniman/profit-trailer#1235]
If we can disable a trade of entire pair. We should also be able to configure more conditions. 
If a watched coin hits a certain % sell it.

trigger DCA on a watched coin if it hits a certain %

Set an amount for a certain pair to not go below or sell

can't come up with all the conditions but you get my drift.

**Comment by YoJeff** [comment]
All of those things you can do right now.

**Comment by bigworom** [comment]
how do you do those things? clearly i'm missing something here. help please
