### ISSUE TITLE
[Feature Request] Edit Sales Log

### ISSUE THREAD

**Issue by bigworom** [taniman/profit-trailer#1236]
There have been a few transactions that did not take place. Not sure how to edit sales log.

**Comment by GriffinB123** [comment]
I just tried to remove old sales (I switched exchanges) by stopping the bot, editing the ProfitTrailer text file in the Logs folder, saving and restarting.

That didn't work.

**Comment by taniman** [comment]
The saleslog is not intended to be changed. And it's a reference of your sales. Your actual sales can always be found don the exchange

**Comment by username77** [comment]
PT bought LTCETH at price 0.3115 but has not reported time and price at DCA log. 
I maded an mistake inserting manually the price from Hot Config 10x less than real value LTCETH_bought_price = **0.0311**. PT sold directly LTC amount at price 0.31188 and reportet an profit of 901.02%.
Any idea who to change this record or to remove it because is totally wrong?

**Comment by YoJeff** [comment]
Read the message from the developer right above yours.

**Comment by username77** [comment]
can i delete manually this record?
![image](https://user-images.githubusercontent.com/4995318/38322869-f7755878-383b-11e8-85f9-67fa88382c81.png)

**Comment by YoJeff** [comment]
>The saleslog is not intended to be changed.

**Comment by username77** [comment]
thanks anyway. i was able to edit ProfitTrailerData.json with an json editor, and now it works.
1. stop bot
2. delete ProfitTrailerData.json.backup
3. edit ProfitTrailerData.json with an json editor
4. start bot

**Comment by kkoenen** [comment]
>     3. edit ProfitTrailerData.json with an json editor

Which editor did you use? thanks.

**Comment by username77** [comment]
jsonbuddy

**Comment by GriffinB123** [comment]
I believe I was an unintended recipient.

Sent from a mobile device.

On Jan 15, 2019, at 3:00 AM, username77 <notifications@github.com> wrote:

jsonbuddy
