### ISSUE TITLE
TCV not calculated correctly

### ISSUE THREAD

**Issue by jsnx** [taniman/profit-trailer#1238]
TCV according to the wiki is: 
Current Value of Pairs Log + Current Value of the DCA Log

But that isnt the case. Neither in the demo you provide on the website nor on my installation. That also leads to a mismatched balance between the exchange and PT

My guess is, that you involve the dust log in some way.

**Comment by mather21** [comment]
Same issue here only shows a small amount of what is avaible for the bot to trade with all the other vlaues are correct i just intalled the latest version v19 .

**Comment by SgtBatten** [comment]
Tcv includes dust. TPV does not. I will amend the wiki

**Comment by taniman** [comment]
Actually TCV and TPV both should include dust. Not in some way. but in ALL way. DUST is also balance to the bot

**Comment by jsnx** [comment]
@taniman
It would be okay if it would contain the dust. But the dust is valued wrong. The bot takes the actual dust PLUS the amount of eth/btc to add that you reach the trading minimum of your exchange.

Double check it in your own demo! Current pairs + current dca + current dust != tcv .

Kind of rude to close this issue before validating my first post.

**Comment by mather21** [comment]
I did reply! I didnt intentially close anything kind of rude incinuating
that especially after the isdues ive had Thanks
