### ISSUE TITLE
EMASPREAD (bot buying when it shouldn't)

### ISSUE THREAD

**Issue by airtime23** [taniman/profit-trailer#1239]
Having an issue with EMASPREAD.  My settings are 300, 12, 3 with a buy value of 1.3.  The bot bought a pair today that it shouldn't have using those settings.  I used trading view to backtest and the buy position was nowhere near the area where it should have bought.  I contacted Helmi, whose trading view script for emaspread I used.  He looked at the graph, at my indicator file, my pairs file, and my log and couldn't figure out why the bot bought. If you're familiar with Helmi's script, it gives green vertical bands where the bot should buy.  As I said, the point at which the bot bought using my settings was nowhere near where it should have bought.  My username on discord is airtime23 (I'm on profit trailer discord site).  Thank you.  Please help me figure this out.

**Comment by taniman** [comment]
Closing it as discussed on telegram
