### ISSUE TITLE
SMA/EMACROSS  wiki

### ISSUE THREAD

**Issue by berylleigh** [taniman/profit-trailer#1242]
Please add to your emacross / smacross wiki on the buying and selling page that the EMA_cross_candles =  setting needs to be put in the indicators.properties file.  

At the moment this is what is on the buying and selling wiki page:
Possible buy values example:
EMA_cross_candles = 2
ALL_buy_value = 3
ALL_trailing_buy = 0

This suggests that the candles setting goes in the pairs file with the other settings.
Otherwise - thanks.

**Comment by taniman** [comment]
done
