### ISSUE TITLE
[REQ] Dropdown information about Pairs in Possible Buy Log

### ISSUE THREAD

**Issue by NigglesSquiggles** [taniman/profit-trailer#1243]
It would be great to be able to click a "drop-down" icon in each record of the Possible Buy Log to see the pairs information, instead of navigating to Config>Pairs and scrolling down to find the pair I want to know details about.
I like to check Trailing Buy value and volume etc, and it would be awesome if I could just see that from the Possible Buy Log and even the other logs would be good to.

Just a suggestion?

**Comment by YoJeff** [comment]
Issue purge....   Gui is upcoming.
