### ISSUE TITLE
TCV calculation wrong

### ISSUE THREAD

**Issue by jsnx** [taniman/profit-trailer#1244]
It should be pairs log + dca log + dust log. 

You can check it for example in your own demo.

Right now at 10:53 GMT it is:
0.05809109 (Pairs Log)
0.04821370 (DCA Log) 
0.00925458 (Dust Log)  

The sum of that is: 0,11555937 BTC
But the TCV shows: 0.862 BTC

Where is the failure? This doesnt seem to make sense.

**Comment by SgtBatten** [comment]
You have not added the balance at all which is 0.75btcish

**Comment by jsnx** [comment]
The TCV does not contain the balance, does it? The wiki says so. Am I wrong?

**Comment by jsnx** [comment]
I see that the Wiki has been updated. Thanks for your help.

**Comment by SgtBatten** [comment]
Tcv is overall
