### ISSUE TITLE
Add indicators and let the user decide either he wanna use them or not don t decide in them place

### ISSUE THREAD

**Issue by wahbalami** [taniman/profit-trailer#1245]
i ve got a lot of bags, -40 -30 that crazy, i assum my responsability but i m disapointed,  why you take the decision to not add indicators, why? sorry but if the community want them in next releases you have to add them please, if not that means you are not listening to you costumer. have  a good one

**Comment by taniman** [comment]
I would suggest you use a different product as adding indicators and logic to handle them is not as simple as you think
