### ISSUE TITLE
There are not enough coins in the orderbook to do a FULL DCA

### ISSUE THREAD

**Issue by BeldarConehead** [taniman/profit-trailer#1246]
Immediately after upgrading from .16 to .19 I started getting this message in the terminal "There are not enough coins in the orderbook to do a FULL DCA for AMBBTC at needed price". This pair seems to have plenty of volume and coins in the order book.
![screen shot 2018-02-24 at 7 30 38 am](https://user-images.githubusercontent.com/11177698/36630464-cad498fe-1934-11e8-8274-24f381a37910.png)

Am I missing something or misunderstanding?

**Comment by taniman** [comment]
buy_available_volume_trigger has been made mandatory and set at 100% by default. This ensured the bot buy the complete amount.

change or disable this if you do not want to ise it

**Comment by BeldarConehead** [comment]
How do I disable this? I don't see anything in the Wiki about disabling. I also still don't understand why if by default it's set to 100% and there are clearly more than 100% of available coins in the order book that it wouldn't just buy them and not throw the message. It makes sense if there weren't enough coins in the order book. 

To disable would it be something like buy_available_volume_trigger = false or buy_available_volume_trigger = 0 ?
