### ISSUE TITLE
[Feature Request]: Long trail after buy signal

### ISSUE THREAD

**Issue by Sereglaith** [taniman/profit-trailer#1247]
Currently, all of the buying strategies that employ trailing have the following"feature" or "problem".  If during the course of the trail, the buy signal is lost, the coin will not be bought.  For example, with LOWBB, if I set my buy_value to 0, and my trailing_buy value to 1, I will almost never get any buys, because in general, by the time the coin trails up the 1% it will no longer be below the LOWBB.

I am proposing an ALL_trailing_override = bool.  In effect, this value would detect a buy signal was encountered, trail up and buy even if the original buy signal was lost.

Considering how the code is implemented now, I realize this might be complicated to implement, but I think it would be a very simple and powerful feature for getting better confirmations that a true bull run is occurring, especially when using downtrend buy strategies.

**Comment by taniman** [comment]
you are incorrect in your supposition. 
The original value for the trail is already stored. Like you see in the logs for LOWBB. 
And the BUY will happen even is the buy_value is different. As long as the price is still below the original buy trigger

**Comment by Sereglaith** [comment]
Then I am confused, because it appears to me that you just described my supposition.

I would have expected this to buy.
![image](https://user-images.githubusercontent.com/14242947/36631436-ae249e00-1945-11e8-863c-17231cf9b832.png)

Here is the tail from my log:
2018-02-24 08:58:32 INFO NormalStrategyRunner - LOWBB trailing started - setting original trigger 0.00110355 for ZRXETH
2018-02-24 09:08:16 INFO ProfitTrailerService - DCA Heartbeat
2018-02-24 09:08:18 INFO ProfitTrailerService - Cache Heartbeat
2018-02-24 09:08:26 INFO ProfitTrailerService - Normal Heartbeat
2018-02-24 09:10:07 INFO NormalStrategyRunner - LOWBB trailing started - setting original trigger 0.00079308 for LRCETH
2018-02-24 09:18:17 INFO ProfitTrailerService - DCA Heartbeat
2018-02-24 09:18:19 INFO ProfitTrailerService - Cache Heartbeat
2018-02-24 09:18:30 INFO ProfitTrailerService - Normal Heartbeat
2018-02-24 09:28:17 INFO ProfitTrailerService - DCA Heartbeat
2018-02-24 09:28:21 INFO ProfitTrailerService - Cache Heartbeat
2018-02-24 09:28:34 INFO ProfitTrailerService - Normal Heartbeat

And my settings:
ALL_buy_strategy = LOWBB
ALL_buy_value = 40
ALL_trailing_buy = 0.7

I should expect a buy at around 0.000798 (1.007 * 0.00079308), correct?

The only explanation I can see is that the spread increased too much.  I will remove it from the equation and try again.  Any additional insight is appreciated.  Also, I am using the latest at 1.2.6.19.

**Comment by Sereglaith** [comment]
I do not think it was the buy spread.

So in the example above, the .000793 value is the point where it crosses the buy_value and creates a buy trigger.  However, the price goes above this buy trigger by the trailing amount.  My original expectations were that the bot would buy at .000798, however, this is not case.  What is happening (I guess I described it poorly, because it seemed to me that you agreed with me in your explanation), is that the price would need to go further down and buy somewhere below the "trigger" value, even after the trailing is complete.

What I am suggesting is that the bot be allowed to trail and buy above the "trigger" value. For example. the trigger is set, and the bot will buy when trailing completes.

This feature is how I originally understood trailing to work after reading the wiki.

**Comment by Sereglaith** [comment]
Let me see if I can do a better job of explaining what I would like to see.

buy_value is 0 and trailing_buy is 1

The price hits the lowbb and sets a trigger price of 0.5.  If the price immediately turns around and goes up 1%, I would like to see a buy at 0.505.  With the current logic, the price would need to go down below 0.495 for a buy to occur.

Finally, my observations, are showing me that the buy_value still plays a role, because the coin is taken out of the PBL when it no longer meets the buy_value criteria.

If my understanding is false, then I am struggling understand how this currently works, and no one has been able to help me.  I have asked several times on discord in support and strategy and I get crickets.

**Comment by Sereglaith** [comment]
> Another important setting is the ALL_trailing_buy setting. This setting allows the bot to “trail” a price downward if it is not yet done dropping, to try and buy the coin at the lowest possible price it can. This action is why you sometimes don’t see the bot buy immediately when a price is below the LOWBB setting by your ALL_buy_value percentage. Sometimes, it buys at a really low price for you, yaaa! But sometimes, if the price turns back up, it might not buy at all if the price jumps above the ALL_buy_value setting. It can be confusing, but it is working in your favor.

Either the documentation is wrong or I am not understanding your explanation.  This explicitly states the behavior I am seeing.  The last sentence is the important part I would like to be able to control.

I would like a value that allows a buy to occur even if the price jumps above the ALL_buy_value after trailing.
