### ISSUE TITLE
Implement Coin-specific min_profit

### ISSUE THREAD

**Issue by meshcode** [taniman/profit-trailer#1248]
When placing the following code into the correct pairs.txt file
ALL_min_profit = 2 
It works and updates the Trigger% in the monitor GUI.

But when I change that to a coin-specific value for Binance in the BTC market:
ZECBTC_min_profit = 3

...it does not update the Trigger% in the monitor GUI (for any coin I try). I am able to alter all other coin properties I need in this way, so it appears to be something with XXXYYY_min_profit.

**Comment by taniman** [comment]
ALL_min_profit = 2 does not update in the gui. I think you are confused with another variable

**Comment by meshcode** [comment]
The ALL_min_profit is displayed under the Trigger% column in the GUI PAIRS LOG. I set it to 3 and all pairs correctly state 3. But when I write XXXYYY_min_profit = 2 for a specific coin it does not update.

**Comment by HojouFotytu** [comment]
Could this be related to the problem I was having with XXXYYY_sell_value being ignored a few times?

**Comment by taniman** [comment]
@meshcode i checked for you. ALL_min_profit is not coin pair specific

**Comment by taniman** [comment]
@HojouFotytu this is not related. As like I said. the XXXYYY_sell_value is working correctly

**Comment by meshcode** [comment]
OK, thanks for checking, Looking forward to the minor coin-specific property fix. Note to others: for the moment the documentation states ALL_min_profit is coin specific but it is not.
