### ISSUE TITLE
Offer Bounties for Debugging

### ISSUE THREAD

**Issue by meshcode** [taniman/profit-trailer#1249]
Some people spend hours looking for undocumented solutions and they may have more incentive to share these in exchange for something. Consider offering a bounty program:

0.01 BTC for reporting major security flaw
0.001 BTC for reporting a major bug
0.0001 BTC for reporting a minor bug
0.0001 BTC for an awesome feature suggestion which was included.

And/or make your own cryptocurrency on Bitshares and offer that.
And/or offer discount certificates for new PT keys which a bounty hunter can give to someone.
etc...

**Comment by YoJeff** [comment]
If taking better care of your own money isn't incentive enough -- I dunno what to say.
