### ISSUE TITLE
Feature request: buy strategy EMAGAIN, above the set procentage

### ISSUE THREAD

**Issue by Ichy84** [taniman/profit-trailer#1250]
Hello

I want to use the EMAGAIN buy strategy to buy coins which are ABOVE the set procentage. Now its only designed to buy below, correct?

Taniman, great work, keep it up.

BR

**Comment by taniman** [comment]
We will be reprogramming the EMAGAIN to do just this in the new features release

**Comment by Ichy84** [comment]
Jolly good. :)
