### ISSUE TITLE
Implement check for buy strategies for when the actual trigger happened

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer#1251]
The Wiki states, for "Strategy = HIGHBB", "Buy **as soon as the current price goes above the HIGHBB** line you specified."

This is not actually true.  PT will buy "if" the current price "is" above the HIGHBB...not "as soon as" the currently price goes above the HIGHBB.  I've found it will buy even if the price went above the HIGHBB 2 hours ago and is now -150% sky high (150% above HIGHBB line), getting ready to make a massive dip (which I then seem sure to catch a massive loss right when I get in).  I'm exaggerating the % to make the point.

The better way would be for PT to actually only buy "as soon as" the current price "goes" above the HIGHBB, like the Wiki currently inaccurately states.  This way, one can catch such trends only at the beginning (just as the price crosses from 1% below the HIGHBB to 1% above the HIGHBB).  In other words, we need to be able to set a limit (such as the "BuyValueLimit") to ensure it does not buy above the HIGHBB any higher than we desire it to.  We just want to catch it when it crosses or very soon thereafter.

We don't want to catch the end of a trend or, worse yet, buy-in while the trend is in free fall already (traveling down)...just because the price happens to still be above the HIGHBB line.

**Comment by airtime23** [comment]
I agree that the buy strategies are all flawed.  This is the same for emagain and emaspread.  I've backtested and the bot buys far too high.

**Comment by taniman** [comment]
you are correct. the bot will buy for all strategies even if the price crossed 10 days ago. 
That how all the strategies work. except for the emacross strategies that define a period.

there is a request to add a buy_value_limit to the buy strategies. maybe some other way of checking when the actual triggerr happened would be beneficial. though I am not certain about that.

**Comment by taniman** [comment]
issue was renamed and will be looked at in the upcoming features release or the next

**Comment by ITJusus** [comment]
One thing I would add, is the only way I can think of to make this work effectively would be to have basically a BB Cross strategy.  I say this because even if you were to add the ability to use "BuyValueLimit" to the HIGHBB  strategy, if I set the BuyValueLimit to say HIGHBB -1...while that may help me not to get into a trade higher than 1% above the HIGHBB line, it still won't prevent me from being entered into a trade once the price plummets back down through this 1% window again.  In other words, the current buy trigger for BB has no sense of direction.  Buying while the price is dropping from a HIGHBB rise is again probably the worst time to buy.

As the Wiki states, it needs to only buy "as soon as the current price goes above the HIGHBB".  The only way I see to accomplish this is for the HIGHBB line to be treated similar to the EMA Cross line, in that it will track the price (like a buying trail in the opposite of normal direction) as it starts to approach the HIGHBB line (assuming the trigger is set above the HIGHBB line) and then as soon as the HIGHBB target is hit or exceeded for the first time in an upward direction...the buy is triggered.

**Comment by slimgit** [comment]
ITJusus I see you are using HIGHBB as a buy strategy, how is it working for you?  I have been testing this for a week now, and it works pretty well in catching breakouts, however like you said it might still end up buying a falling coins and end up buying too high.  

I just want to add it might be a good idea to add buy "if candle closes price above the set BB line". Not sure if this is feasible or not.

**Comment by ITJusus** [comment]
@slimgit
@taniman

The HIGHBB strategy works great, only when you happen to catch the price as it is just crossing **UP** the HIGHBB line (or close to it)...in my experience so far.  Unfortunately, with the limited way the HIGHBB strategy currently works in PT...it is far too dangerous to use and will almost always eventually lead one to be left with heavy bags that far outweigh the profits made on the way up.  

The problem is say you set your buy_value to -0.10 (HIGHBB)...if you just so happen to catch the price the first time it crosses up that .10% above the HIGHBB line (assuming your ALL_max_buy_spread is high enough to match for entry), then you will mostly likely make a good initial profit.  But the PT's HIGHBB Strategy doesn't stop there...it will keep re-buying this coin up to the very top and, if you still haven't bought in yet, it will try to buy in all the way **DOWN** to the HIGHBB buy_value limit you specified.  Or, if you weren't even fortunate enough to catch a buy at that initial cross **UP** the HIGHBB line (because your ALL_max_buy_spread was too low at that time or PT just started tracking the coin after it was already above that point)...then you are likely not to get any profit at all and plenty of negative bags instead.   So, you MIGHT happen to get one decent trade (if by the more rare chance you catch the price before it is already away above the HIGHBB line), or maybe a series of good small trades (if your sell_value is low and your trailing is set to 0), but it will keep buying when the coin is way overbought and on down as it plummets.

I would not recommend at all using the **current** HIGHBB strategy that PT has to offer, as it seems to almost inevitable lead to bags or losses in the end (most of the time, in my experience).  I'm sitting on a bag right now (bought just an hour ago) in which PT bought the coin 5.5% above the HIGHBB line...just before it peaked and made its so far -5% fall.  Fortunately, when testing strategies like this, I set my cost extremely low and my DCA's almost off...so I'm not losing much along the way.  Just making the point and I've been testing this for a while, with the same results.

If you ARE going to risk using the HIGHBB strategy, in its current form in PT, then the safest way to use it (as far as I can tell) would be to set your ALL_rebuy_timeout to a number of hours...in order to force PT hopefully to ignore the rest of the move above HIGHBB, after the first good buy/sell, into overbought and mass sell-off territory.  Again, though, this will only protect you if you so happen to catch a coin just as it is making that first initial cross UP the HIGHBB or assuming the coin won't stay above the HIGHBB for the number of hours you specify not to re-buy.  Many times, unless your ALL_max_buy_spread is set very high, enough not to risk missing that initial move (which has its own average losses to do it that way in general) or if you happened to have just started your bot, you're going to wind up catching a coin already in overbought territory or worse.  

My advice would be to hold off utilizing PT's HIGHBB strategy until they further develop it to be able to trigger a buy only when the price is moving **UP** through our target buy_value and not much higher (except maybe allowing for some quick slippage above our buy_value via BuyValueLimit).  Otherwise, you better have an amazing good performing DCA strategy in place to deal with the more likely losses involved.  If you can pull off profitability, with the current way this strategy works in PT...your DCA wushu is stronger than mine by far.

**Comment by ITJusus** [comment]
Actually, one correction to my last comment...using an ALL_rebuy_timeout won't help much either, as you never know if that timeout will expire while the price has since gone right back to an overbought position again.  I really wish I could use this HIGHBB strategy, but currently it just has too many flaws.  I'm looking forward to what's coming in v1.2.7.  Until then, this strategy gets the back-burner.

**Comment by cvthub** [comment]
should be available in 2.0
