### ISSUE TITLE
[Feature Request] Balance specific min_profit

### ISSUE THREAD

**Issue by oiler2112** [taniman/profit-trailer#1252]
We have ALL_min_profit, which is also supposed to be coin specific as well.

Would like to have something like balance_percent_profit, meaning, if a coin meets this setting we can adjust the min_profit for that coin that meets the condition.

Example:
I have 1 BTC total balance.
All_min_profit is set to 1
balance_percent_profit is set to 25
balance_min_profit is set to 0.4
I have purchased the TRX coin and it has DCA'd to where it is now using 26% of my total balance but it has only reached 0.45 in profit. Since it has not met All_min_profit it would not sell. But, it has met the balance_percent_profit setting and the balance_min_profit setting, so it will now sell, since the balance_min_profit is set to 0.4

**Comment by taniman** [comment]
please let's me first clarify that min_profit only works with LOWBB strategy. So my question is are you using the LOWBB strategy in this example?

**Comment by oiler2112** [comment]
Sorry about that taniman, I meant to say sell_value, NOT min_profit. So, this would change the example to:

Example:
I have 1 BTC total balance.
All_sell_value is set to 1
balance_percent_sell_value is set to 25
balance_sell_value is set to 0.4
I have purchased the TRX coin and it has DCA'd to where it is now using 26% of my total balance but it has only reached 0.45 in profit. Since it has not met All_sell_value it would not sell. But, it has met the balance_percent_sell_value setting and the balance_sell_value setting, so it will now sell, since the balance_sell_value is set to 0.4

**Comment by YoJeff** [comment]
Per coin DCA is coming, which is actually more flexible.
