### ISSUE TITLE
[Bug in .19? ] EMAGAIN buys way too high

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1253]
I switched to .19 last night, excited about the Binance fix.
But today I had a rude awakening. I use EMAGAIN on a 15 minute chart (900 seconds in the indicator file).
I have a -1.6 buy value with a 0.3 trail, but it bought on the top (!) of the 15 minute candle. Which would represent a buy value of 2.33 (!!!) in the attached sample (???). It did that on 3 different coin buys.
I've went back to .16 for now. There's definitely something majorly screwed up here.
![image5](https://user-images.githubusercontent.com/36098310/36635182-9b46a632-197e-11e8-9a2b-eeebdad54a8f.png)

**Comment by alexdolli** [comment]
Another example:
![image6](https://user-images.githubusercontent.com/36098310/36635257-db4e3078-197f-11e8-87a1-6ac0beec7129.png)

**Comment by taniman** [comment]
pelase provide your log file

**Comment by alexdolli** [comment]
As I mentioned, I went back to .16. So no, I don't have the log file for these trades anymore.
Second, I already explained my settings. EMAGAIN with a buy_value of -1.6 and a 0.3 trailing_buy on a 15 minute chart (aka 900 period in the indicator file). You can see my EMA settings on the screenshots I've taken. I use the exact same ones in my indicator file. EMA_1 = 34 and EMA_2 = 12.
The top of the candle has nothing to do with my settings, that is the actual problem I am trying to  point out. It should not have bought on the top of that candle (with a 0.3 trailing_buy).
Let me know, if you need it explained even more plain and simple.

**Comment by taniman** [comment]
if you cannot provide your log I will not handle this case. In the log there is a simple line that will display the exact but time and price and other settings.

even if you downgraded the log shuld be intact. So if you can find the log you are free to reopen this issue
