### ISSUE TITLE
Feature Request:  Ascending or Descending Trends

### ISSUE THREAD

**Issue by Regimax** [taniman/profit-trailer#1254]
I've found that my trades are more profitable if I trade ascending cryptocurrencies.  Anyway to add a feature to determine ascending/descending trends (over a period of candles or price average increases/decreases).  Thanks.

**Comment by airtime23** [comment]
I second this request.  

An option for the bot to examine and track which coins on that particular day have the highest % gains on that particular exchange would be very useful and profitable.

**Comment by Regimax** [comment]
Airtime23's suggestion works for a different strategy than I had in mind. I'd like to trade coins that are on a longer ascending trend line.  Both ideas would be a good addition.

**Comment by airtime23** [comment]
I agree, Regimax.  Both ideas would be good additions.

**Comment by jason-gu** [comment]
I would like to see this feature as well, this will be very helpful.

**Comment by YoJeff** [comment]
Resubmit with a fleshed out strategy, including your requested calculations and will re-review.
