### ISSUE TITLE
Export from Sales Log confusing/wrong

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#1255]
This is a screen capture of my sales log:
![image](https://user-images.githubusercontent.com/6478474/36637250-302de978-19a6-11e8-90c6-4c2e09b7bb61.png)
When I click on "Copy" and I paste in Excel, this is how it shows:
![image](https://user-images.githubusercontent.com/6478474/36637252-50a12846-19a6-11e8-9526-70df7775b470.png)
In the screenshot after the Trigger% column, it shows a "Profit BTC" column which has the BTC value followed by the $ value in brackets.
In Excel that shows up in 2 columns instead (Profit column with BTC value, and BTC column), but the BTC column shows in brackets and Excel treats that as negative value.
I was scared at first looking at it, that all those trades ended up in loss, possibly because of fees, but I guess those should be positive values in USD.
Can you separate those columns in the web interface, and solve the issue of copy/paste to Excel?

Thanks.

**Comment by YoJeff** [comment]
Duplicate #1086
