### ISSUE TITLE
Error in reading response api.binance.com

### ISSUE THREAD

**Issue by Primalysk** [taniman/profit-trailer#1261]
Hiya,

I've started getting the following error this evening, after the bot has been working just fine in version 19.

**_ERROR ProfitTrailerService - ticker - Error in reading response api.binance.com_**

The error is spammed about 3 times a second and the bot won't function at all - I've reverted back to version 16 & 18 and still recieving the same error..

Any ideas on what is happening & a possible solution?

**Comment by taniman** [comment]
this means your network connection has a problem communicating with binance. or maybe the binance api is having problems. 

So check your network connection
