### ISSUE TITLE
Pairs with >3 letters on Binance

### ISSUE THREAD

**Issue by Tjosy** [taniman/profit-trailer#1267]
I'm not having any luck setting trading to false for NANO and STEEM on Binance. Wondering if this is because the symbols used in the pairs have more than three letters. e.g. STEEMBTC.

**Comment by mile6919** [comment]
I use this in my PAIRS-file:

NANOBTC_trading_enabled = false

and it works fine. I'm using Binance.

**Comment by Tjosy** [comment]
Weird. I'll try again.
