### ISSUE TITLE
INFO DCAStrategyRunner - not enough coins in the orderbook

### ISSUE THREAD

**Issue by ab376** [taniman/profit-trailer#1268]
Does anyone know what the cause of this INFO message?

INFO DCAStrategyRunner - There are not enough **coins** in the orderbook to do a FULL DCA for LUNBTC at needed price

So, this is not the other volume issue.

I'm running PT version 1.2.6.19

Thanks in advance!

**Comment by mile6919** [comment]
If you have set up your settings like this:
ALL_buy_available_volume_trigger = 150 (in PAIRS -file)
and/or
buy_available_volume_trigger = 150 (in DCA -file)

That can cause the problem you described. That demands that there should be at least 150% of your order available in order book before your bot makes trial for buy. Lower that number to 125 or even to 100. That should fix your problem.

**Comment by ab376** [comment]
Hi Mile6919, thanks for your quick response. I do not use those settings (buy_available_volume_trigger). other suggestions?

Thanks!

**Comment by mile6919** [comment]
Well then it can just be that in that time when your bot tried to make DCA buy of LUN for you, there was not enough LUN available just at that time. I can not think of any other possibility just now. Sorry!

**Comment by ab376** [comment]
Thanks for your time m8!

**Comment by mile6919** [comment]
No problem!

**Comment by taniman** [comment]
@ab376 the default value for buy_available_volume is 100%
