### ISSUE TITLE
[Feature Request]Reserve specify pair(s) to trade from max pairs

### ISSUE THREAD

**Issue by Cryptominht** [taniman/profit-trailer#1269]
I wanted to see if this feature could be added I want to be able to reserve a specify pair(s) slot from my max pairs.  For example: My max pairs is 8 but I wanna reserve 1 pair slot for NEOBTC all the time. Reason for this is I see PT trading with a particular pair for the past 2 days multiple times but stops trading that pair once all my max pairs are locked up.  If the pair is a wave I wanna ride it til it hits the wall!!!  

Also a priority list feature of the pairs of some sort would be great also I know this feature maybe more complex but worth a shot to ask.  For example: After a pair slot is freed up from a sell and it's doing a trailing buy of like 5 pairs (I know that whatever meets the first buy conditions it'll buy first) but if I had prioritize it buy a particular pair first over the other 4 by giving pairs a priority number like (10) for NEOBTC and giving all other pairs a default number of (5) or something. Even tho one of those 4 pair meets the buy condition it'll wait like 1 or 2 cycle(or even choosing how many cycles) before buying it and would try to reserve the buy to get NEOBTC first once when it can hit the conditions within that time frame.  Another great thing this could do is you can set less wanted pairs on the lower side of the priority list like FAIRBTC (1) even tho you don't really want to trade with it, instead of blocking it out all together it can be bought after others.

Of course for the most part these feature would be much appreciated I am seeing  on weekends my DCA  and pairs logs get locked up and would be great if there was a some customization of what pairs I can focus more on without completely stopping trades or removing pairs. Thanks.

**Comment by taniman** [comment]
1. I do not process multiple requests in 1 issues.

2. NEOBTC_max_trading_pairs = 9 will override the default if you have it on 8 to allow the bot to buy this coin if your max is set at 8

**Comment by Cryptominht** [comment]
oh great that works also thanks
