### ISSUE TITLE
Implement manual sell position buttom 

### ISSUE THREAD

**Issue by mikdesign02** [taniman/profit-trailer#1271]
Proposition : You should implement a sell position next to the pairs in the pair log and DCA log to allow manual sale action. See exemple in the attached picture
![prop](https://user-images.githubusercontent.com/34874555/36648967-4fd6d050-1a91-11e8-9dcc-8d85967da0a1.JPG)

**Comment by Vichi74** [comment]
Second this. Also a Manual DCA button.

**Comment by efurban** [comment]
That'll be great!

**Comment by YoJeff** [comment]
#1205 #1181 #1080 #1069 
etc, etc, etc.
