### ISSUE TITLE
Feature request : Have a simulation Mode 

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#1272]
Most bots have a simulation mode but are bad at making profit. PT make a little profit and have good foundation with a great dev but don''t have a simulation mode
It will save hours or days of time tweaking the conf for individuals
It will open a big door by offering to the futur dev team the tool to start thinking how they will increase the number of profitable trade based on the opportunities offered by the prices mouvment.
It will help debuging by testing directly for a big part of bugs.

So the idea is the let the bot run (at full speed or/and at real time to debug) historics from exchange if possible or trading view. The result could for starting simplyappear on the sale log and will be tagged as simulations trades.

It's not the most need feature now but I think this can bring a lot.

**Comment by AkliOnet** [comment]
I just found https://www.tradingview.com/script/HcxbnmGO-Profit-Trailer-Tester-v0-2/

**Comment by YoJeff** [comment]
Tradingview works...
