### ISSUE TITLE
Pair Did Not Take Profit

### ISSUE THREAD

**Issue by artissh1** [taniman/profit-trailer#1273]
I am quite angry.  I had my settings for Profit as GAIN with a All_sale_value of .75 and trailing_profit of .10
My pair rose to a profit of 1.86%, but never took the profit.  The pair has since dropped back to a profit of -2.0

The manner in which this software takes profit needs to be CLEARLY explained.

**Comment by artissh1** [comment]
What is the answer to my question? How dare you close this issue and not address my concern about your software.  I expect a response to my question.  Your closing my issue IS NOT A RESPONSE!

**Comment by YoJeff** [comment]
You seem to think you can plunk a price off a chart wherever you like.   Ask support IS the response.

**Comment by artissh1** [comment]
One of the most annoying aspects of Profit Trailer is the customer service provided along with the lack of professionalism.  First of all, if Ask support is the response, it should have been so stated, CLEARLY.  Second of all, there is no information regarding how to contact support.  Do you mind letting me know how support can be contacted.
