### ISSUE TITLE
[Bug] Bot ignores ALL_min_buy_volume and min_buy_volume in DCA

### ISSUE THREAD

**Issue by jason-gu** [taniman/profit-trailer#1274]
Version: 1.2.6.19
Market: BTC
Exchange: Binance
Pairs ( ALL_min_buy_volume = 500 )
DCA ( min_buy_volume = 500 )

The bot bought LRC and it bought the coin again in DCA, but looking that the 24 hr volume on Bianance is only 130.83 BTC and CoinMarketCap shows 265.47 BTC 24 hr volume.

https://coinmarketcap.com/currencies/loopring/

I think the same happened with another coin SALT which the bot bought when it shouldn't have.

**Comment by Stein276** [comment]
I've had the same.

Version: 1.2.6.19
Market: BTC
Exchange: Binance
Pairs ( ALL_min_buy_volume = 700 )

Bought a coin with a volume of 28 and a few more in the 400's

**Comment by taniman** [comment]
Please without logs we cannot handle this

**Comment by YoJeff** [comment]
Bot does not care about CMC, it reads volume data from the market it's trading on.   volume spiked, and it became eligible.

**Comment by jason-gu** [comment]
I don't think it's appropriate to close a ticket without giving me enough time to upload the log file for review. I understand the bot doesn't use CMC, that's y I sent both Binance and CMC's 24 hr volume.

Do you have an email where I can send the log file?

**Comment by YoJeff** [comment]
You sent a snapshot of the volume at -one- point in time.   I brought up the chart, saw the recent volume spike that takes it way way way over 400, explained it -- then closed it.

**Comment by sjintas** [comment]
I'm having this issue to. It happened at least once before. Here is my log of the most recent incident:
```
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:46 INFO ProfitTrailerService - Buy order for ASTETH -- {"symbol":"ASTETH","orderId":6547976,"clientOrderId":"Ypo4RPnUpxqPIjVwGC70yU","transactTime":1519728225935,"price":"0.00051940","origQty":"48.00000000","executedQty":"48.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:51 INFO ProfitTrailerService - Get order information -- {"symbol":"ASTETH","orderId":6547976,"clientOrderId":"Ypo4RPnUpxqPIjVwGC70yU","price":0.00051940,"origQty":48.00000000,"executedQty":48.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1519728225935}
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:51 INFO NormalStrategyRunner - Normal Pair - EMAGAIN bought -- currency pair ASTETH - BV -1.0, BVL -5.0, MTP 2, TTP 2
```

Setting is set to `ALL_min_buy_volume = 1000.0`

**Comment by cas8180** [comment]
I am still having this issue now sure if it was fixed when your base is ETH:

![image](https://user-images.githubusercontent.com/1483688/36815400-6dcacb66-1c8f-11e8-8758-7e9fa6ac5d19.png)

![image](https://user-images.githubusercontent.com/1483688/36815430-842baaba-1c8f-11e8-9ff9-2b4e6152ab3f.png)

**Comment by sjintas** [comment]
If you are running the latest version, please post the actual logs in stead of screenshots. They are more helpful. The volume shown in the DCA window is (afaik) the current volume, not the one at buy time.
