### ISSUE TITLE
[QUESTION] combined_cancel_pending_trigger

### ISSUE THREAD

**Issue by woodyalien** [taniman/profit-trailer#1276]
ALL_combined_cancel_pending_trigger = 0
is 10% represented by "10" or "0.1"? 
(not clear in the wiki)

Thanks!

**Comment by Mikeeetrue** [comment]
+1

**Comment by taniman** [comment]
nothing really to be clear about. when have we used 0.1 to represent a 10% increase?
if you want 10% you put 10.
if you want 0.1% you put 0.1
