### ISSUE TITLE
[Feature Request] Minimum Coin Age

### ISSUE THREAD

**Issue by SPLeon** [taniman/profit-trailer#1279]
Hi,

Just have a feature request. I'm already blacklisting my own coins in stead of just white-listing coins to trade with. 

Blacklisting coins is my preferable way of trading, the only thing what is bothering me is the fact that new coins are being added, PT buys the coins, price drops and I have a big bag.

When I look at Bittrex I see that the Added date is displayed at every coin market. Also in the API documentation I see a field for the created date of the coin.

Is it possible to add some kind of parameter to the Pairs config file, for example

All_min_coin_age = 30 (30 days).

**Comment by YoJeff** [comment]
Dup #261
