### ISSUE TITLE
Optionnal maximum loss % for All_stop_loss_trigger

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#1280]
I trade a coin only that I hold and I rebuy every time with lowbb 100 with buy limit_value of 0 (can you confirm this work with lowbb ? I used to do that ) but when the coin goes down below lowbb 0 it always go -10% I would like to have the posibilty to react and sell  at -1% with the stop loss trigger so I rebuy at -10% but I don't want to sell if the price had already gone -5% because the amount is big and I know it will go up very quicly.
What I need is a All_stop_loss_trigger_limit = -5

Just to illustrate more my use case (Hold and Trade but only with precaution as the price can go up very quickly after selling) : 

ALL_buy_strategy = LOWBB
ALL_buy_value = 100
ALL_buy_value_limit = 0
ALL_trailing_buy = 2

ALL_sell_strategy = HIGHBB
ALL_sell_value = 25
ALL_min_profit = 5
ALL_trailing_profit = 2

**Comment by YoJeff** [comment]
Interesting, so you want to set a limit where you lose so much you want to just say 'screw it, I'm holding'?

Toss this over onto the feature github for voting....
https://github.com/taniman/profit-trailer-enhancements
