### ISSUE TITLE
EMAGAIN bought too high

### ISSUE THREAD

**Issue by Eegee** [taniman/profit-trailer#1282]
This evening (at 19:42:24 UTC+1), my bot bought NEOBTC, with EMAGAIN ALL_buy_value = -0.47, ALL_buy_value_limit = -3, ALL_trailing_buy = 0.15 and indicator settings 1800, 20, 5 at a moment that wasn't even close to being lower than the lowest EMA line of the two (with the EMA of 30 minutes), at least that's what I think.

Could you please take a look at attached log file and and perhaps explain why it happened?
I am using version 1.2.6.19 on Binance.  If you require more information I am happy to provide it to you.

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1759973/ProfitTrailer.log)

[INDICATORS.properties.txt](https://github.com/taniman/profit-trailer/files/1759977/INDICATORS.properties.txt)

**Comment by YoJeff** [comment]
Well, I fully expected to pop up the chart and see some super long trail that could explain it.  But I got nothing on this one.

**Comment by Eegee** [comment]
I just saw .20 being announced with "Incorrect chatrdata causing incorect buys on binance" mentioned. Perhaps something's fixed already?

**Comment by mile6919** [comment]
Profit Trailer Wiki says that "ALL_buy_value_limit" is used with EMA/SMA SPREAD and CROSS strategies, not with EMAGAIN.

**Comment by Eegee** [comment]
OK, well, but this is not about ALL_buy_value_limit. It was bought well above zero, definitely not below -0.47. But if it may have to do something with it, I'm happy to comment out ALL_buy_value_limit.

**Comment by YoJeff** [comment]
Closing all older 'why did the bot buy' issues for older versions.  If this happens again in .20 re-report please.
