### ISSUE TITLE
Please set ETHBTC_bought_price 

### ISSUE THREAD

**Issue by shuanana** [taniman/profit-trailer#1283]
Once i enabled trading, pt quickly DCA'd my BNB and ETH. I dont understand why its attempting to DCA them but anyway. 
Is there a way to reset the DCA log or clear its cache? 
I dont know how to operate hotconfig to manually enter bought price, so any help is appreciated. 

<img width="833" alt="screen shot 2018-02-26 at 11 12 42 xoxo" src="https://user-images.githubusercontent.com/36867365/36701274-ab022100-1b4a-11e8-845e-ae8ead8063b3.png">

**Comment by YoJeff** [comment]
This is for bugs, the support folks in discord can get you straightened out.
