### ISSUE TITLE
There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot

### ISSUE THREAD

**Issue by meligo** [taniman/profit-trailer#1285]
hey 

Almost every night I get this message in my telegram chat , last night it happened 7 times in the past few days. Is there any way to have a log file or debug info so that it can help you guys? 

Exchange is Binance

kind regards
Andy

**Comment by cristianserban** [comment]
hi
please give me your discord id

**Comment by meligo** [comment]
hey , my discord ID = Meligo#9889

**Comment by taniman** [comment]
Are you using version .19 or .20?

**Comment by cristianserban** [comment]
he just updated to 20 .. will close this and you may reopen it in case it hapends again 
thanks
