### ISSUE TITLE
Feature request Dynamic Trailing 

### ISSUE THREAD

**Issue by slimgit** [taniman/profit-trailer#1286]
Instead of just having one trailing constant why not have a dynamic trailing, for example my profit is set to 1% and trailing to 0.25%, now if the coin keeps going up to 10% without dropping 0.25% I want to change my trailing to 1%, giving more chance for potential profit. 

Maybe trailing profit can a percentage of the set sell profit?

**Comment by taniman** [comment]
please search before creating new requests. I think this is set in milestone 2.0 or 2.1
