### ISSUE TITLE
Feature Request: DCA trailing buy/profit per pair (or use values from pairs.properties)

### ISSUE THREAD

**Issue by sjintas** [taniman/profit-trailer#1287]
Currently it is possible to set a trailing buy/profit per pair but not when using DCA. As I understand it now, as soon as a pair hits DCA it will use the default trailing values specified in there. And when there has been a dca buy those values will always be used (unless dca enabled is turned off).

I think it would be nice to either be able to keep using the pair specific trailing values or (maybe even better) be able to specify pair specific DCA-trailing values.

**Comment by taniman** [comment]
please search existing issues before creating new ones. check milestone 2.0

**Comment by sjintas** [comment]
I actually did look for it first, but did not find it. Perhaps it has a misleading title, or I looked for something different. Anyway, good to know it is on the roadmap!
