### ISSUE TITLE
Potential bug: Average price calculation is wrong

### ISSUE THREAD

**Issue by sjintas** [taniman/profit-trailer#1290]
**Disclaimer**: I have already discussed this with someone from support who thinks that this is just a settings issue. However I think that might not be the case and I rather be proven wrong that finding out that this is indeed a bug where people are potentially losing money...

**The setup when this occurred:**
version 1.2.6.19 running under pm2 on a linux box.
I am running my own feeder-like app (personal project, it works in a similar way, just with way more settings/conditions to tweak). Which overrides the settings files every few minutes.
I'm using `Files.write(path, lines);` (java) to write all the new settings at once. This way PT should never read partial settings.
However, if you agree with me these settings have nothing to do with the actual problem. (It might have something to do with [a related problem](https://github.com/taniman/profit-trailer/issues/1274#issuecomment-368844526), but I highly doubt it)

I've been running successfully (with my app running too) for the last 3 days have multiple sales and dca's that did work correctly.

**The actual issue**
AverageCalculator calculates an average price of `5.9e-4` for 2 values `5.19e-4` and `5.19e-4`
and later calculates it to be `5.5e-4` for values `5.19e-4`, `5.19e-4` and `5.20e-4`
_Even though the average calculations are weighted, that does not matter in this case, since the average could never be more than the maximum value._

I expect the first to be 5.19e-4 + perhaps the 0.2% for the fee. but not + 13%

**Logs:**
```
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:46 INFO ProfitTrailerService - Buy order for ASTETH -- {"symbol":"ASTETH","orderId":6547976,"clientOrderId":"Ypo4RPnUpxqPIjVwGC70yU","transactTime":1519728225935,"price":"0.00051940","origQty":"48.00000000","executedQty":"48.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:51 INFO ProfitTrailerService - Get order information -- {"symbol":"ASTETH","orderId":6547976,"clientOrderId":"Ypo4RPnUpxqPIjVwGC70yU","price":0.00051940,"origQty":48.00000000,"executedQty":48.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1519728225935}
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:51 INFO NormalStrategyRunner - Normal Pair - EMAGAIN bought -- currency pair ASTETH - BV -1.0, BVL -5.0, MTP 2, TTP 2
0|profit-t | 2018-02-27 11:43 +01:00: 2018-02-27 11:43:51 INFO NormalStrategyRunner - BUYLOG: {"BBLow":0.0,"BBTrigger":0.0,"positive":"true trailing...","BBHigh":0.0,"currentValue":-1.3224646823264519,"market":"ASTETH","profit":0.0,"currentPrice":5.194E-4,"buyStrategy":"EMAGAIN","volume":639.958049,"triggerValue":-3.1459111337085344,"percChange":-0.06549}
0|profit-t | 2018-02-27 11:45 +01:00: 2018-02-27 11:45:03 INFO ProfitTrailerService - Buy order for ASTETH -- {"symbol":"ASTETH","orderId":6548012,"clientOrderId":"kNhWY0NWoxQ8QP3EZ8Ktes","transactTime":1519728303811,"price":"0.00051940","origQty":"59.00000000","executedQty":"59.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|profit-t | 2018-02-27 11:45 +01:00: 2018-02-27 11:45:09 INFO ProfitTrailerService - Get order information -- {"symbol":"ASTETH","orderId":6548012,"clientOrderId":"kNhWY0NWoxQ8QP3EZ8Ktes","price":0.00051940,"origQty":59.00000000,"executedQty":59.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1519728303811}
0|profit-t | 2018-02-27 11:45 +01:00: 2018-02-27 11:45:09 INFO DCAStrategyRunner - ASTETH, mc 0.0, ctc 0.030644600000000004, dbc 0.06550660000000001, bb 0.22811759
0|profit-t | 2018-02-27 11:45 +01:00: 2018-02-27 11:45:09 INFO DCAStrategyRunner - DCA - Anderson bought -- currency pair ASTETH - CP -12.097210939615477 - BT -
0|profit-t | 2018-02-27 11:45 +01:00: 2018-02-27 11:45:09 INFO DCAStrategyRunner - BUYLOG: {"BBLow":0.0,"BBTrigger":-12.215678310316825,"positive":"true trailing...","highbb":0.0,"boughtTimes":1,"buyProfit":-12.097210939615477,"lastOrderNumber":"6548012","unfilledAmount":0.0,"market":"ASTETH","profit":-12.821852152721357,"averageCalculator":{"totalCost":0.034862000000000004,"totalAmount":59.0,"totalAmountWithSold":0.0,"avgPrice":5.908813559322034E-4,"avgCost":0.034862000000000004,"firstBoughtDate":{"date":{"year":2018,"month":2,"day":27},"time":{"hour":10,"minute":43,"second":45,"nano":935000000}},"totalWeightedPrice":0.034862000000000004,"orderNumber":0.0,"fee":0.2},"currentPrice":5.164E-4,"sellStrategy":"GAIN","buyStrategy":"ANDERSON","volume":640.0844054,"triggerValue":0.0,"percChange":-0.06855}
0|profit-t | 2018-02-27 11:46 +01:00: 2018-02-27 11:46:04 INFO DCAStrategyRunner - There are not enough coins in the orderbook to do a FULL DCA for ASTETH at needed price
0|profit-t | 2018-02-27 11:46 +01:00: 2018-02-27 11:46:17 INFO ProfitTrailerService - Buy order for ASTETH -- {"symbol":"ASTETH","orderId":6548060,"clientOrderId":"kVQbJ6VudOVko0Qya9D4xZ","transactTime":1519728377384,"price":"0.00052000","origQty":"118.00000000","executedQty":"118.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|profit-t | 2018-02-27 11:46 +01:00: 2018-02-27 11:46:23 INFO ProfitTrailerService - Get order information -- {"symbol":"ASTETH","orderId":6548060,"clientOrderId":"kVQbJ6VudOVko0Qya9D4xZ","price":0.00052000,"origQty":118.00000000,"executedQty":118.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1519728377384}
0|profit-t | 2018-02-27 11:46 +01:00: 2018-02-27 11:46:23 INFO DCAStrategyRunner - ASTETH, mc 0.0, ctc 0.06136, dbc 0.1268666, bb 0.19747299
0|profit-t | 2018-02-27 11:46 +01:00: 2018-02-27 11:46:23 INFO DCAStrategyRunner - DCA - Anderson bought -- currency pair ASTETH - CP -6.329934791223835 - BT -
0|profit-t | 2018-02-27 11:46 +01:00: 2018-02-27 11:46:23 INFO DCAStrategyRunner - BUYLOG: {"BBLow":0.0,"BBTrigger":-6.474042583852713,"positive":"true trailing...","highbb":0.0,"boughtTimes":2,"buyProfit":-6.329934791223835,"lastOrderNumber":"6548060","unfilledAmount":0.0,"market":"ASTETH","profit":-7.1423929098966,"averageCalculator":{"totalCost":0.06550660000000001,"totalAmount":118.0,"totalAmountWithSold":0.0,"avgPrice":5.551406779661017E-4,"avgCost":0.06550660000000001,"firstBoughtDate":{"date":{"year":2018,"month":2,"day":27},"time":{"hour":10,"minute":45,"second":3,"nano":811000000}},"totalWeightedPrice":0.06550660000000001,"orderNumber":0.0,"fee":0.2},"currentPrice":5.165E-4,"sellStrategy":"GAIN","buyStrategy":"ANDERSON","volume":635.9062677,"triggerValue":0.0,"percChange":-0.06819}
```

First at 11:43:51: 
`Buy order for ASTETH ... "price": "0.00051940" ... "executedQty": "48.00000000"`
Second at 11:45:03: 
`Buy order for ASTETH ... "price": "0.00051940" ... "executedQty": "59.00000000"`

Average calculator:
```
"averageCalculator": {
	"totalCost": 0.034862000000000004,
	"totalAmount": 59.0,
	"totalAmountWithSold": 0.0,
	"avgPrice": 5.908813559322034E-4,
	"avgCost": 0.034862000000000004,
	"firstBoughtDate": {
		"date": {
			"year": 2018,
			"month": 2,
			"day": 27
		},
		"time": {
			"hour": 10,
			"minute": 43,
			"second": 45,
			"nano": 935000000
		}
	},
	"totalWeightedPrice": 0.034862000000000004,
	"orderNumber": 0.0,
	"fee": 0.2
}
```

**Comment by YoJeff** [comment]
I dig the details, but you are running an older/retired version.

**Comment by sjintas** [comment]
You are right, I did upgrade after finding this. However, the release notes do not say anything about this being fixed so for I know it is still in the latest version. Could you please confirm if this was a known issue and or could no longer be an issue in the current version?

**Comment by YoJeff** [comment]
Here is the deal.  These github issues are a chore to wrangle.   One of my tasks is to clear out issues related to retired versions to hopefully help the limited developer resources focus on current issues.  This is no exception.

The one thing that stands out here, is there is a mismatch of DCA amounts.   I am unaware of any bugs that cause DCA to overpurchase without API issues inbetween.   It's a constant struggle to have the bot gracefully handle garbage responses from the fragile exchange APIs.

If we look at the purchases here....

- First Buy.   0.249btc.   Looks fine.
- First DCA.   .0306btc.    1.22x?? WTF  extra coins from somewhere?
- 2nd DCA.   .06xx btc.   2x, looks fine.

So yeah, something screwy happened here, but I'm not convinced it's the averaging algo.

Retest on .20 and resubmit if still an issue.

**Comment by sjintas** [comment]
You are correct it buys extra coins, but couldn't that be because it is trying to average the $ price? So if it expects the 48 to be bought at a higher price than it is worth now (which was not the case, but lets assume an API error here). Then it buys more coins to double the bought price, which means it has to buy more than 48 at a lower current value. So I think it might be more like an effect than a cause.

I do understand the developer availability problem. Are you looking for more help? Perhaps I can assist.

**Comment by YoJeff** [comment]
It doubles based on value, not any targets.    But whatever the method, the 1st dca was at exactly the same price, so it should be pretty much the same qty assuming a full fill.

**Comment by sjintas** [comment]
for reference, As discussed on discord:

If the bot somehow gets wrong data from exchange and thinks the first buy was somewhere a lot higher it could create such a situation.

The average for the first 2 buys was 5.9e-4 right? so it asumes the first buy must have been:

(firstPrice * 48 + secondPrice * 59) / (48+59)
with secondPrice = 5.19e-4 -> firstPrice = 6.7e-4

so if we do this the other way around. it would buy 59 coins at 5.19 to average out the price half way (~around the 12% it logs)

Anyway. Running with .20 now and will report if It happens again.
