### ISSUE TITLE
LowBB buying at the wrong time

### ISSUE THREAD

**Issue by Cryptoqueb** [taniman/profit-trailer#1294]
ALL_buy_strategy = LOWBB
ALL_buy_value = -2
ALL_trailing_buy = 0.35

BB_period = 900
BB_sma = 24

P T Ver: 1.2.6.19

![lowbb](https://user-images.githubusercontent.com/35400485/36744484-f9cfd0aa-1bba-11e8-9dd1-e2e66b5c6dc2.jpg)

**Comment by YoJeff** [comment]
.19 is retired.    .20 fixes some chartdata issues.   Upgrade and re-report if recurring on .20.
