### ISSUE TITLE
*** Feature Request *** Dust Killer

### ISSUE THREAD

**Issue by enigmat** [taniman/profit-trailer#1295]
Have the bot go to the exchange and buy a small amount to kill the Dust Log

**Comment by mile6919** [comment]
Yes, this is much needed feature. I hope we get this.

**Comment by YoJeff** [comment]
Don't fall over quarters picking up pennies.   If there was a solution to dust -- it would be all over the place.  The ultimate resolution lies with the exchange that creates it in the first place.
