### ISSUE TITLE
Feature Request: REVERSAL TRADING

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer#1298]
![photo_2018-02-27_16-22-39](https://user-images.githubusercontent.com/35824627/36749801-9c6a3854-1bda-11e8-893a-9b0b2a278dd3.jpg)

**Comment by YoJeff** [comment]
This almost describes the bots current function.  Almost.

**Comment by juato4** [comment]
No, Reversal trading is the new gunbot 9 functionality for DCA.

**Comment by Ruzefix** [comment]
Can you explain me the difference between "sell XXX for BTC" and "buy BTC with XXX"?

**Comment by juato4** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/76
