### ISSUE TITLE
SELL Strategy EMACROSS not working

### ISSUE THREAD

**Issue by jaminess** [taniman/profit-trailer#1300]
Hey There 
EMACROSS ist not working.  The Bot doesnt sell any pair.

I want to sell use EMACROSS as a selling stragety.

I would like to sell when the EMA lines cross no matter what. Even if the pair is in **profit** or when the pair is in **loss**

<img width="1335" alt="2018-02-27_2012" src="https://user-images.githubusercontent.com/36898888/36751664-12066526-1c01-11e8-844b-902cd3fe1997.png">

The 
I am using EMA Gain as a buying Strategy:

Buy Strategy:

All_buy_strategy = EMAGAIN
ALL_buy_value = 0.3
ALL_trailing_buy = .5

Sell Strategy:

All_sell_strategy = EMACROSS

Please fix it so the bot can sell on EMACORSS !  :)

Or Can somebody tell me the right configurations so the bot will sell?

**Comment by YoJeff** [comment]
emacross is not a valid sell strategy.  It's already been requested.
https://wiki.profittrailer.io/doku.php/buy_and_sell_strategies
