### ISSUE TITLE
DUST Issues... Please read in it's entirety... Potential DCA's and losses can result...

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer#1301]
Please read the following in it's entirety...

With all respect (sincerely) - Please consider the following...

Dust exists on the exchange because the exchange rounds trades which creates the dust in the first place. This factually creates inherent problems with PT doing the accounting, while the exchange does it efficiently and as expected. On the exchange, (in a manual trade) YOU the owner of the account, are buying "x" amount of that coin at a specific price (whether you place a market order or a limit order) For this example, let's say you elect to buy BTC with 100% of your available BTC (which includes previous dust) at $10,000 even. This order will be placed for EXACTLY $10,000 (as long as the order book can fill it in one shot)

At this point, the insignificant DUST has been added regardless if it is at profit or loss, either way, it is factored into the order at a bought price of $10,000, right along with the rest of the order. Not only is this understandable as the DUST is such an insignificant part of the order, but it makes the trade very straight-forward. This method is used (and preferred) because the DUST is the most insignificant part of the equation. PT on the other hand does the opposite, it treats the DUST bought price as the base for the whole order, which creates a host issues ranging from trades sold at a loss and misreported as a profit, to possible DCA's, etc...

As mentioned, "the only'"official' record that matters is the exchange" - I agree completely, however, PT should be able to reflect the same record in the sales log as that on the exchange, all the while presenting it's users and accurate profit percentage gain (or loss) on such trades, AND preventing possible DCA's as a result from the current DUST incorporation model.

And while a fix may not be easy "per se" (I'm not a programmer) all I 'm saying is that having a control for the end user would be a simple task for the end user to enable or disable.
However, that said, let's consider another approach, how about PT treat DUST the same way the exchange does and set/reset the bought price for DUST to the order buy price set by PT (the way the exchange does), and let the DUST be the part of the trade to adopt the insignificant gain or loss adjustment instead of the whole order. This is how it's treated on the exchange. It would keep the record on PT in line with that of the exchange as well.

Contrary to YoJeff's opinion, I don't assume too much... I am willing to bet the overwhelming majority of people that fully understand what is happening would opt for the dust to be treated secondary in a trade. This will always be the preferred method when compared to inaccurately averaged trades where the DUST represents the bought price of the FULL trade.

As stated in an earlier post, DUST can result in DCA's, lower profits, some sales that include DUST are misrepresented as a gain in the sale log when they actually trade at a loss. Not to mention this all contributes to an overall inaccurate sales log and inconsistent trade history in the sales log as compared to the exchange.

Again, this is an issue... This should not be dismissed.
A main objective of PT should be gains, not losses, and accuracy of the trade, period! - A sale should not take place at a loss because an order that has a penny's worth of dust with a lower bought price satisfies the condition for a sell trigger. This very situation has happened to me several times resulting in a loss on the whole trade. This happens because the dust bought price was low enough, by comparison to the actual bought price of the whole trade. Each time, the order was bought, included DUST which had a low enough bought price that it satisfied an immediate sell order, then sold quickly at a loss. Then the whole order was re-bought at close to the sell price because the argument for the original buy was still valid. But the icing on the cake is that the sales log showed the trade sold at a handsome profit because the low dust price was the bought price for the whole order.

Again, this is an issue and should not be dismissed.

This section is supposed to be for "issues" with PT. This is an issue that I am trying to "help" resolve. I believe Taniman understands this to be the case, so I am simply trying to include examples of where and when this happens to help provide feedback for a solution.
I find it quite dismissive of you to simply make a couple of close-minded statements, then close this thread. This is an issue that I and others have recognized and it would seem that the Devs would want to take a close look at this to make PT the best it can be.
This is not a rant, this is not a support question, this is an issue and should remain open till there is a viable solution, in my opinion.

I'm only trying to help, I appreciate all the hard work that goes into this project, and as a faithful user and advocate, I simply want to help the community and the developer make PT the best it can be.
@YoJeff ... Your position and reply to this issue seems rather provoking... You seem to have taken offense and perhaps it is you that has not given the gravity of this issue enough consideration before closing both your mind and the issue... I respectfully encourage you to reconsider both.
Once again, this post is to HELP resolve an issue. The information and images are to offer support in developing a resolution.

Sincerely...

(This was a reply to my original post that was closed prematurely by YoJeff. I encourage either YoJeff of Taniman to reopen that post as it contains valuable information which can help PT and the community. Users should be aware of this potential issue till a fix is available - The origninal post includes images that may be helpful for readers to better understand the issue - Please re-open the issue which contains this post, then feel free to close this one... Thanks for your consideration)

**Comment by YoJeff** [comment]
I commented on the other thread, don't create duplicates.
