### ISSUE TITLE
NEW ! EMACROSS Profit Strategy

### ISSUE THREAD

**Issue by jaminess** [taniman/profit-trailer#1304]
Hey There 

**UNFORTUNATELY Profittrailer does NOT support EMACROSS  as selling strategy**

Would appreciate it if you could implement EMACROSS for both Buys and Sells. 
I use this for day trading manually on Bittrex using Coinigy.
I bought PT in the hopes of automating the manual day trading method I use and developed over 2 years of hard work.
I use the EMACROSS 13/34 on 5 minute candles as a trigger for implementing either a buy or sell strategy. 
I also use Volume increase or waning, MACD crosses 12/26 with 9 length and RSI to strengthen the cases that the EMACROSS is a true cross and not a false positive.
Then use the EMASPREAD to determine when to buy or sell. 
I also use DCA to both buy into and sell out of a trade position.
That way you can Buy Low and Sell High every time.
You never get bags this way and you can make money regardless of if the market and the pair is trending up or down.

It would be AWSOME, if this settings here would work:

ALL_sell_strategy = EMACROSS
ALL_sell_value = -0.5
ALL_trailing_profit = .2
 
On heavy downswings the strategy would sell at a **loss** but the **loss** would be very small.
But it would trail the Profit.

And on any upswing the **profits** would be **very** **big**.

Look at this example:

<img width="1373" alt="12018-02-28_0158" src="https://user-images.githubusercontent.com/36898888/36764330-6f8c3bf0-1c2c-11e8-9ab1-e26bb6c384b7.png">

<img width="1272" alt="2018-02-28_0202 3" src="https://user-images.githubusercontent.com/36898888/36764584-7b5d9d10-1c2d-11e8-9ad9-f78e38acc5d9.png">

# **# Give this post a Like or Comment if you like this Idea to be Implemented ! ;D**

**Comment by YoJeff** [comment]
Duplicate #884, #719.    Check over on the features contest to see if it already exists there.
https://github.com/taniman/profit-trailer-enhancements
