### ISSUE TITLE
[Bug] DCA Log: Displays sell_value in the Sell Trigger column

### ISSUE THREAD

**Issue by dttsm** [taniman/profit-trailer#1306]
As the subject states, the DCA log wrongly displays the sell value instead of the sell trigger in the "ST%" (Sell trigger) column.
I don't know if this is only a display issue or also an underlying logic issue. I just noticed and have not been able to confirm a logic issue yet.
Please check.
Thanks

This is on 1.2.6.19 
I haven't upgraded yet to the newer version .20

**Comment by YoJeff** [comment]
.19 is retired.   If the issue persists in .20, resubmit.

**Comment by dttsm** [comment]
Upgraded to .20
Issue still persists. Reopen please.

**Comment by SgtBatten** [comment]
What sell strategy?

**Comment by dttsm** [comment]
GAIN

**Comment by dttsm** [comment]
Sorry,for DCA: ANDERSON

**Comment by dttsm** [comment]
Sorry, have had a lot less sleep than necessary, lately. 
You are right, of course, it's GAIN. I falsely corrected myself there :D. Anderson is a buy strategy...

The rest: understood. Thanks. and sorry again, about the unnecessary issue.
