### ISSUE TITLE
Sales log is lost

### ISSUE THREAD

**Issue by guillemhs** [taniman/profit-trailer#1307]
When PT sales log is updated, only one item is shown in the log. 
Additionally, all the historical sales logs are lost.

If PT sells more than pair, there is only value shown in the log.

It does not maintain the historic log of sales

Can you check if it is a config problem from my side or is it a PT issue?

**Comment by YoJeff** [comment]
You can set the number of days.    Please use support.

**Comment by guillemhs** [comment]
Ok,

My number of days is 9999999 for PT Tracker.

PT does not collect the sales log, just maintain one item there.

I will use support
