### ISSUE TITLE
Expired sell order added to sales log

### ISSUE THREAD

**Issue by woody43567** [taniman/profit-trailer#1308]
Using the Binance exchange I had a sell order that expired so the sale did not complete.
However, it was added to the sales log as sold but still remained in DCA log also.
I checked Binance and could see that the sell had not completed.

![image](https://user-images.githubusercontent.com/36909568/36769733-4f65e5ec-1c9a-11e8-8643-523d8c9aa6d2.png)

![image](https://user-images.githubusercontent.com/36909568/36769741-5e53e054-1c9a-11e8-863a-5529b72f5e0a.png)

![image](https://user-images.githubusercontent.com/36909568/36769748-64b235fe-1c9a-11e8-9d68-750a8b5dd9f5.png)

**Comment by taniman** [comment]
Nothing wrong here. This was a partial sell.  And partial sells are recorded in the sales log. In your image I cannot see the amount sold but it would most likely say. 1
