### ISSUE TITLE
Sell strategy displaying as WATCHMODE for all pairs

### ISSUE THREAD

**Issue by realpagan** [taniman/profit-trailer#1309]
My sell strategy is displaying as WATCHMODE for all pairs and I lost opportunities for the bot to sell some trades at a profit. I tried enabling panic sell for those coins only and did not work. Also backed up my files and started a new bot from scratch and still the WATCHMODE is still in effect for those coins. Please help. Everything was working perfectly until this. Attaching screenshot.

![watchmode in all pairs issue](https://user-images.githubusercontent.com/36897497/36771417-3ff13390-1c1e-11e8-9b6d-64ad928d46e7.png)

**Comment by YoJeff** [comment]
Those coins are disabled.  Please use support.
