### ISSUE TITLE
Feature Request: SOM Enabled for Pair with Trade history Less than X (time)

### ISSUE THREAD

**Issue by DaveHollows** [taniman/profit-trailer#1310]
Would be nice to have a SOM feature for X amount of time on a new coin so the bot can avoid buying into a dump when an exchange lists a new coin. 

Example:

SOM_Enabled_MaxTradeHistory = 1440

In the above, sell only mode is enabled for Pairs that have a trading history less than 1440 Minutes (1 Day)

**Comment by YoJeff** [comment]
Dup #261
