### ISSUE TITLE
[Feature Request] Dont Buy "24 Hour % Change" +xx%

### ISSUE THREAD

**Issue by ingeniumdesign** [taniman/profit-trailer#1313]
Hi, can u edit a new Marker?

We need a Marker for set a Buy Rule.
Dont buy this Coin he run in 24h over +20%
"ALL_max_buy_xxxxx = 20.0"

Its the same with "ALL_min_buy_volume = 1500"
Dont buy Coin he need a Volume over 1500

Thanks

**Comment by NathanHowell135** [comment]
I want this too!

**Comment by jaminess** [comment]
Yes Me too!

**Comment by latty40** [comment]
That's what I would like to see as well, get better results when 24h is 15% or higher, can buy and sell within 5mins, at the moment manually doing it is a pain in the arse, hopefully it will be in the next update with a bit of luck

**Comment by YoJeff** [comment]
Throw that over here for voting.  Check to see if it already exists...
https://github.com/taniman/profit-trailer-enhancements
