### ISSUE TITLE
Specific Coin Drop Triggers

### ISSUE THREAD

**Issue by jaminess** [taniman/profit-trailer#1314]
Hello i would like to know if it is  possible to activate and deactivate specific coins if The Price drops or falls

For example as this setting is already working for all coins:
ALL_btc_price_drop_trigger = 4
(Goes into sell only mode BTC drops by 24% within the last 24 hours)

# What i want to know:
Is it possible to deactivate/activate certain coins if i use this Command?

neo_price_drop_trigger = 4
(deactivates neo if it  drops by 4%)

XRP_price_drop_trigger = 4
(deactivates XRP if it  drops by 4% within the last 24 hours)

Greetings

**Comment by securitygeneration** [comment]
This would indeed be useful, and be able to do it on any coin ALL_price_drop (but also price_rise) triggers.

If a coin goes up by 10%, I find that PT will often get caught on the selloff and you end up with a massive bag.

**Comment by jaminess** [comment]
Exactly.
This way you would only "Ride" the potential upswings ;D

**Comment by YoJeff** [comment]
Throw that over here for voting.  Check to see if it already exists...
https://github.com/taniman/profit-trailer-enhancements
