### ISSUE TITLE
LowBB buying at the wrong time

### ISSUE THREAD

**Issue by Cryptoqueb** [taniman/profit-trailer#1315]
ALL_buy_strategy = LOWBB
ALL_buy_value = -2.5
ALL_trailing_buy = 0.35

BB_period = 900

BB_sma = 24

P T Ver: 1.2.6.20

the KNCBTC buy (last one) was a good one. 1/3 today.

CNDBTC (Binance)
![lowbb_er_1](https://user-images.githubusercontent.com/35400485/36800121-afdc2eb8-1c7c-11e8-8b3e-50e6d328efdd.jpg)

LINKBTC (Binance)
![lowbb_er_2](https://user-images.githubusercontent.com/35400485/36800126-b3e89988-1c7c-11e8-9948-2291329d58b1.jpg)

**Comment by taniman** [comment]
If I do not get the PT log files I  cannot start looking into this

**Comment by taniman** [comment]
Also it would be fine if you could tell me what coin bought at the wrong time instead of me having to figure out these images

**Comment by Cryptoqueb** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1772396/ProfitTrailer.log)

**Comment by Cryptoqueb** [comment]
Edited the original post to add the pairs!

**Comment by taniman** [comment]
Okay, let's start woth first thing You write that your buy_value = -2.5
```
ALL_buy_value = -2.5
```

According to the log file your buy value is set at -2.0
So that's a first inconsistentcy.

If we adjust for -2.0 instead of -2.5 doe you still see an incorrect buy?

**Comment by taniman** [comment]
I see your script on trading view is using -2.0 so all good there.

**Comment by taniman** [comment]
Do you use PTF or PT Magic? anything that changes the indicators.properties?
I am trying to pinpoint this mystery.

an i am currently seeign multiple 
2018-02-28 08:14:19 INFO Util - Detected configuration changes
2018-02-28 08:16:55 INFO Util - Detected configuration changes
in your file.

**Comment by Cryptoqueb** [comment]
Sorry man I was sleeping! So yeah my All_buy_Value is now at -2 in the Feeder appsetting file (Base value).
My offsets have a range of [-2 : -5] I'd say. Notting that would make it go above the LOWBB line for sure. I have no offsets for my indicator, All my indicators from all market condition files share the exact same values : 

BB_period = 900
BB_sma = 24

SMA_period = 300
SMA_1 = 34
SMA_2 = 13

EMA_cross_candles = 3
EMA_period = 900
EMA_1 = 24
EMA_2 = 12

**Comment by taniman** [comment]
```
Does "TriggerValue -2.5" means the Buy value trigger for that pair was -2.5 at that moment?
```
yes.

**Comment by taniman** [comment]
What's your Discord username?

**Comment by Cryptoqueb** [comment]
apesh!t_is_my_mood

**Comment by taniman** [comment]
Can't talk to you we are not on the same server.

**Comment by Cryptoqueb** [comment]
I'm on the Feeder's discord. Do you have an invite for the PT discord?

**Comment by SgtBatten** [comment]
Click where do I go for support on the ekft menu halfway down.
https://wiki.profittrailer.io/doku.php
