### ISSUE TITLE
[Feature Request] Show more values in dollars: DCA / Telegram

### ISSUE THREAD

**Issue by ramonduraes** [taniman/profit-trailer#1316]
I would suggest improving the exhibit. Many times I'm not sure how much the bot spent on each purchase order. My suggestion is to always show the estimated dollar.

Possible Buy
=> Change "Buy Value" to o display  "~ BTC/USD"

DCA
=> Change "Current Value
Total Cost" to display "~ BTC/USD"

Sales
=> Change "Bought Cost" to "~ BTC/USD"
=> Change "Sold Value" to "~ BTC/USD"
=> Reorder collum "Sold Value", "Bought Cost", "Profit" (BTC/USD)

Display Full Names and values BTC/USD
BC
D
SV

Telegram
- Buy
BINANCE
Just bought: BTC-NEO
Cost: 0.01000000
Rate: 0.01280000
Ammount: 998
~ $12,00

- Sold
BINANCE
Just sold: NEOBTC
Sell strat: GAIN
Cost: 0.07169612
Rate: 0.01301200
Profit: 1.31%
BTC: 0.00092004
USD: ~$10,00

Thanks

**Comment by YoJeff** [comment]
#546, #448, and lots more duplicates.

**Comment by ramonduraes** [comment]
I refer mainly to the above items on the screen:  Possible Buy; DCA; Sales

**Comment by ramonduraes** [comment]
@YoJeff Did the request go to the backlog?
