### ISSUE TITLE
New Feature: EMA calculation mode

### ISSUE THREAD

**Issue by futurestrader1987** [taniman/profit-trailer#1317]
Hello,

I would like to request a feature to be able to select by which mode the EMA calculates. Right now my guess is that its set to the close. I would like to be able to set it to calculate based on the low of the candle price, this makes entries after a pump and dump harder and entries from what I've seen in the charts are usually better.
something like this.
EMA_source = low

**Comment by YoJeff** [comment]
Throw that over here for voting....
https://github.com/taniman/profit-trailer-enhancements
