### ISSUE TITLE
API problems? 

### ISSUE THREAD

**Issue by Fortoona** [taniman/profit-trailer#1318]
[nothing was changed in settings from a long time...]

How to fix this?

![123](https://user-images.githubusercontent.com/36703270/36813935-64fa1e00-1cd6-11e8-9de0-93330d3d9c6f.PNG)

**Comment by taniman** [comment]
What exchange is this? Is the problem still occuring?

**Comment by YoJeff** [comment]
If it's polo, they had an outage yesterday...

**Comment by taniman** [comment]
yes. this is polo. Will close for now
