### ISSUE TITLE
DCA Log is lost when DCA is turned off.

### ISSUE THREAD

**Issue by leoneparise** [taniman/profit-trailer#1319]
I had some DCA bags and when I turn off DCA, the information gets lost forever, even if I turn on DCA again! The coins doesn't appear on pairs log anymore. On previous versions, all coins were going to the Pairs log when DCA is disabled.

The version I'm using is 1.2.6.20.

**Comment by taniman** [comment]
I have jsut check for you. and I can disable my DCA coins just fine. So how are you disabling these? and do you have a mis configuration in your pairs.properties which is causing the coins not to be shown in pairs.properties?
