### ISSUE TITLE
LOW BB not populating current value

### ISSUE THREAD

**Issue by Jonesy1214** [taniman/profit-trailer#1320]
I have been running LOW BB for a few days now and have notices it never populates the current value in possible buy log properly.  The value for current value is always whatever my buy value for LOW BB is ex. -10.  Current values for buy are -10 and trailing at .1, i have had plenty of trades but cannot tell what the bot is close to buying unless i look at the current BB value and the trigger BB value and compare them.  

I have also spoken with other in discord and they seem to be having the same issues.  Is this a known isssue?  Or is there something that can be done to fix this?  Thanks!

**Comment by taniman** [comment]
That's not a big issue. the current value in lowBB was never displaying a value. As it is not important.
I have started displaying this current value in latest version as a trial. But will be removing it soon enough as it's confusing people more than it's helping

current BB and BB trigger are the values you should be looking at.
