### ISSUE TITLE
Wrong bought price lead to a false stop loss trigger

### ISSUE THREAD

**Issue by leoneparise** [taniman/profit-trailer#1321]
Wrong bought price lead to false stop loss trigger:

<img width="1145" alt="screen shot 2018-02-28 at 21 08 24" src="https://user-images.githubusercontent.com/1442927/36820277-c55d70e0-1ccb-11e8-9b6d-61b6b47fadef.png">

<img width="1240" alt="screen shot 2018-02-28 at 21 08 57" src="https://user-images.githubusercontent.com/1442927/36820282-cc61c4b8-1ccb-11e8-99e0-b22b048c9f54.png">

<img width="1133" alt="screen shot 2018-02-28 at 21 16 47" src="https://user-images.githubusercontent.com/1442927/36820469-c336d01c-1ccc-11e8-8c3d-1d64377c647b.png">

<img width="1231" alt="screen shot 2018-02-28 at 21 16 55" src="https://user-images.githubusercontent.com/1442927/36820474-c6ed371e-1ccc-11e8-9a13-b2e14a4ef8b6.png">

As you can see, it was not a drop of 15%. Where did the bot get that bought price? I'm using Binance.

**Comment by Marco356** [comment]
Check this [https://github.com/taniman/profit-trailer/issues/1293](url)

I think this is DUST problem. Hopefully they gonna fix it soon.

**Comment by taniman** [comment]
Are you using DCA in combination with STOPLOSS? Because this is something that is known to happen and we still have not figure it out. So we advice people on our wiki not to use this combination.

**Comment by leoneparise** [comment]
@taniman I'm not using DCA, only STOPLOSS.

**Comment by taniman** [comment]
Please provide your log file so I can follow the chain of events

**Comment by leoneparise** [comment]
@taniman Here are the logs: [logs.zip](https://github.com/taniman/profit-trailer/files/1775533/logs.zip)

**Comment by taniman** [comment]
I am fairly certain that this problem was fixed in the latest release. 1.2.6.23
