### ISSUE TITLE
Please fix: trading_apiKey -- ERROR: -1013

### ISSUE THREAD

**Issue by wfjsw** [taniman/profit-trailer#1322]
Getting this error at start up of 1.2.6.20:

`2018-03-01 09:11:52 ERROR Application - Please fix: trading_apiKey -- ERROR: -1013`

**Comment by Jonesy1214** [comment]
First bot?  Has it worked previously?  Which exchange?

**Comment by wfjsw** [comment]
Binance, It works at 1.2.6.19, already running for a few days

**Comment by YoJeff** [comment]
This is for bugs, please use support.

**Comment by wfjsw** [comment]
@YoJeff This **IS** bug.
