### ISSUE TITLE
PT There was an error while refreshing the data...

### ISSUE THREAD

**Issue by Godspeed101** [taniman/profit-trailer#1324]
Seeing this message since i did buy PT a month ago. Searched the net and did ask in discord and Telegram but no answers. Found a couple of the same questions but nowere i cant find the answer. Only thing they say its fixed. I dont ask fast help but its getting irritating now:)

The only thing i could find is something about CMC api error or banned from the site..
Hope you can give me a hint were to find the solution, so i can fix this problem.

Tnx for your time
william

**Comment by taniman** [comment]
This error depends on how often you get it. and most of the time you will see something in your log file if it is bot related.

So how often do you get this? When you password is expired you will also get this error. So pressing refresh 1 time and resetting your password helps. 

and last question. Are you on the latest version?

**Comment by Godspeed101** [comment]
Hello,
Sorry i was away for work. I did get that message from the 1st minute i did
use PT. Gonna change my password because i didnt change that part for
weeks. Iam Crypto Crow fan and watch everything. Gonna try original
settings from PT without Crow his adjustments, hope that will work. Sorry
again for my late respond and tnx for your fast respond to me😎

Willem

Op 2 mrt. 2018 11:08 schreef "taniman" <notifications@github.com>:
