### ISSUE TITLE
ALL_rebuy_timeout seems doesn't work correctly

### ISSUE THREAD

**Issue by jentzheng** [taniman/profit-trailer#1325]
Mar 1, 2018 at 6:13:42 PM //Sold time
Just sold: POAETH
Sell strat: GAIN
Cost: 0.04775232 (1)
Rate: 0.00072352
Profit: 1.87%
Profit ETH: 0.00087338

Mar 1, 2018 at 6:31:00 PM //Bought Time
Just bought: POAETH
Cost: 0.02372667
Rate: 0.00071899

```
//Pairs
ALL_rebuy_timeout = 30

// Indicator
EMA_period = 60
```

**Comment by taniman** [comment]
Do you have the actual bot log file for me?

**Comment by jentzheng** [comment]
I am using v 1.2.6.19, and it seems your team resolved it in the latest version. Let me check again.
