### ISSUE TITLE
Feature request - Incorporate Godmode3.1 with LSMABG selling/buying points

### ISSUE THREAD

**Issue by D3adm3at** [taniman/profit-trailer#1327]
Tradingview has a really neat indicator for buying selling that some daytraders swear by.

Godmode3.1 (9, 6, 3 ) with indicator LSMABG (32,0)

If we could include this indicator and buy/sell on the yellow 

plotpoints.  we would all be winners.

<img width="995" alt="screen shot 2018-03-01 at 9 58 22 am" src="https://user-images.githubusercontent.com/36961285/36851488-2c95e34e-1d1e-11e8-8faf-56e4f2080cca.png">

**Comment by YoJeff** [comment]
Ship this over to the features github for voting.
https://github.com/taniman/profit-trailer-enhancements
