### ISSUE TITLE
DCA always (true trailing) and not doubling down

### ISSUE THREAD

**Issue by Zokuaku** [taniman/profit-trailer#1328]
I am finding that my Profit Trailer bot is significantly exceeding my DCA Anderson DoubleDown percentages and staying in a True Trailing state and not buying. I do not believe it is a configuration issue with my setup but I have attached my config settings and logs for your perusal. I am presently leveraging a VPS (Dual Core 2.67 GHz, 4 GB Memory on a RAID 1 SSD setup) with Server 2016 and Java 1.8 Update 161 and am configured for Binance at 5 minutes (Please let me know if you need any additional info) <Edit: I am running PT 1.2.6.20>:

![image](https://user-images.githubusercontent.com/3577196/36853479-de62f05a-1d2b-11e8-9fe8-ac294db81483.png)
[configuration.properties.txt](https://github.com/taniman/profit-trailer/files/1771743/configuration.properties.txt)
[PAIRS.properties.txt](https://github.com/taniman/profit-trailer/files/1771744/PAIRS.properties.txt)
[DCA.properties.txt](https://github.com/taniman/profit-trailer/files/1771745/DCA.properties.txt)
[INDICATORS.properties.txt](https://github.com/taniman/profit-trailer/files/1771746/INDICATORS.properties.txt)
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1771737/ProfitTrailer.log)

**Comment by YoJeff** [comment]
My guess would be you've hit max cost for DCA.  You are 2 deep with a cost already nearing 0.1 so a 3rd DCA would pass your cap.   But....  This forum is for bugs, please use discord for support.
