### ISSUE TITLE
Profit Trailer not trade

### ISSUE THREAD

**Issue by KrofekSLO** [taniman/profit-trailer#1331]
Hi,

I am new here... But I already have problem. I configure my profit Profit Trailer. But even after 6h  I don't have any trade. Can somebody helps me?

**Comment by Psyclon1981** [comment]
good day, i have the same problem. the bot trailing the coins but not buying at the percentage.
i am thinking that maybe have something to do with the latest version of pt.

**Comment by taniman** [comment]
Please check with support as this is for reporting acrual bugs. The bots are currently buying just fine
