### ISSUE TITLE
Telegram not giving DCA buy notifications

### ISSUE THREAD

**Issue by Tosko4** [taniman/profit-trailer#1334]
Hi there,

I am not sure if this is normal behaviour, but it got to my attention last night and happened again this morning. 

When Profit Trailer buys in DCA, no buy alert is given. 

When I test my bot with the /settings/telegramTestMessage, that works. And I also received a notification that BTC prise has risen. 

Now, I have never given attention to buys in DCA log, it showed me buy logs from new coins obviously. But now that I have been in DCA a while and not purchasing much new coins, I noticed my BTC funds go down without me having an alert, thats when it first got my attention, last night. 

I have the latest version. 1.2.6.20
Using it on Ubuntu 16.04

Thanks in advance

**Comment by taniman** [comment]
Bot has never given these back. A future plugin will show these
