### ISSUE TITLE
Multiple Pairs Files Based on Longer-term Market Movement (bull, bear, neutral)

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer#1335]
It would be great to have a switch/drop-down on the monitor that allows you to switch between several pairs files (or auto, based on indicators file settings, as seen below). 

This would be useful if you see the market conditions changing between a Bull, Bear and Neutral.

You could utilise files such as pairs_1.txt, pairs_2.txt etc...
Each file would then have all the same settings as the existing file + a pairs_title attribute for the drop-down menu (defaulting to filename where no name is set).

This would allow an unlimited number of personalised buy and sell strategy sets that are easy to switch between depending on how the market is moving without having to replace the contents of the pairs file each time one wants to change overall strategy.

Automation could then also be possible.
New attributes in the Indicators file can automatically trigger the file selection process based on real-time data, looking at a set base pair and its change in EMA spread or cross over a time period set.

pairs_switch_automation = false(,true)
pairs_switch_base = BTC_USDT

#BTC Bull 
pairs_1_strategy = EMACROSS
pairs_1_period = 1D
pairs_1_EMA_1 = x
pairs_1_EMA_2 = y

#BTC Bear 
pairs_2_strategy = EMACROSS
pairs_2_period = 1D
pairs_2_EMA_1 = x
pairs_2_EMA_2 = y

#BTC Neutral 
pairs_3_strategy = EMASPREAD
pairs_3_period = 1D
pairs_3_EMA_1 = x
pairs_3_EMA_2 = y
pairs_3_trigger <= z1  >= z2 (e.g. 2, -2)

Pairs_1 overrides pairs_2. 
Pairs_2 overrides pairs_3 and so on, or visa versa.

**Comment by taniman** [comment]
I would recommend you check if this feature does not exist and vote there. 
https://github.com/taniman/profit-trailer-enhancements/issues 
This is one of those features that brings a complexity to the bot that won't help regular user. But if enough people want it. I am open.
