### ISSUE TITLE
Recurrent "Please set BNBETH_bought_price"

### ISSUE THREAD

**Issue by MindWallet** [taniman/profit-trailer#1337]
Hello,

I was asked to fill in my BNBETH_bought_price, which I did. Then I was asked to do so again and again. It seemed to register the price, but then it asks for it again. Anyone with this issue?

I am using the latest version on a Windows VPS. Thanks!

**Comment by SgtBatten** [comment]
Setting the bnb price is pointless. It will forget it after every trade because the amount of bnb you own is changing and can't be easily calculated by the bot.

If you don't want to get the message you need to use all hidden pairs to hide bnb from the bot.

**Comment by MindWallet** [comment]
Thank you very much! The problem is solved.
