### ISSUE TITLE
FEATURE REQUEST: BuyOnlyMode BOM

### ISSUE THREAD

**Issue by CousinEddie** [taniman/profit-trailer#1338]
BuyOnlyMode in which the bot, given normal buy conditions, buys a pair, but will not sell them. It would immediately drop into a DCA-type configuration in which it would doubledown at various percentages. It would have to be coin specific.

It would be easy to just add the pair to hidden pairs and disable them from trading after you’ve reached the amount you desire.  

Though coin accumulation could be done outside of PT, it would be a nice feature to take advantage of the ever working bot to make the best purchase. Freeing you up from having to attempt to catch downtrends manually.

**Comment by acefed** [comment]
You can set your sell trigger (too) high to achieve that. For all coins, or specific ones:

DGDETH_sell_value = 150

This creates the time needed to transfer coins off the exchange.
