### ISSUE TITLE
Stop Loss and Rebuy Timeout Not Working

### ISSUE THREAD

**Issue by antigravity83** [taniman/profit-trailer#1342]
Version 1.2.6.20

**Stop Loss set in both Pairs and DCA Config files**

ALL_stop_loss_trigger = -5
ALL_stop_loss_timeout = 60
ALL_rebuy_timeout = 15

**Yet Stop Loss not activated on the following:**

![image](https://user-images.githubusercontent.com/27241813/36931240-a556a4ea-1efd-11e8-8323-93a436b9a596.png)

**And PT continues to rebuy assets that have just been sold**

![image](https://user-images.githubusercontent.com/27241813/36931247-bc491962-1efd-11e8-8cb5-f0b33d10a515.png)

![image](https://user-images.githubusercontent.com/27241813/36931250-cad2eeb8-1efd-11e8-8b22-cf54a00429db.png)

**Log attached**

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1777161/ProfitTrailer.log)

**Comment by antigravity83** [comment]
It seems as if Stop Loss and Rebuy limitation works when coins don't DCA.

But as soon as they DCA- these commands do nothing.

I have them in both the DCA and Pairs configs.

**Comment by taniman** [comment]
paste your DCA.properties

**Comment by antigravity83** [comment]
max_cost = 0
max_buy_times = 4
max_buy_spread = 2
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -0.5
buy_trigger_2 = -1.5
buy_trigger_4 = -2.5
buy_available_volume_trigger = 150
trailing_profit = 0.1
trailing_buy = 0.25
ignore_sell_only_mode = false
min_buy_balance = 0
min_buy_balance_percentage = 5
min_buy_volume = 0
sell_strategy = GAIN
sell_value = 1.1
ALL_stop_loss_trigger = -5
ALL_stop_loss_timeout = 60
ALL_rebuy_timeout = 15

**Comment by taniman** [comment]
so no option is DCA.properties starts with ALL_

this is why your triggers are not working. Check the wiki again or just use them like this,

stop_loss_trigger = -5
stop_loss_timeout = 60
rebuy_timeout = 15

**Comment by antigravity83** [comment]
Thank you, missed that. Much appreciated.
