### ISSUE TITLE
LOWBB current value on PBL not refreshing itself?

### ISSUE THREAD

**Issue by Orangard** [taniman/profit-trailer#1346]
I do have PTMagic.
I noticed that when it switched to lowbb the current value seemed to be way off, as it was listing all the way from -30 to -143.
my buy settings are

ALL_buy_strategy = LOWBB
ALL_buy_value = -10
ALL_trailing_buy = 0.39

Indicators are:
BB_period = 60
BB_sma = 40

and here is a TV of what should have been happening:
https://imgur.com/wSxyuOj

and SS of the current value:
https://imgur.com/TFXFbOb
(was about half way through the drop)

https://imgur.com/EdMVwfK
(was in around the last candle on the TV)

I restarted the bot, and haven't seen the settings match again (ptm has it at emaspread now)

**Comment by taniman** [comment]
lowbb current value will be removed in next release as it's causing too much confusion. 
You only need to look at current bb and bbtrigger
