### ISSUE TITLE
Feature Request - Auto exclude coins based on 24 hour change

### ISSUE THREAD

**Issue by tru-fkn-blu** [taniman/profit-trailer#1347]
Everyday I update my pairs log to exclude coins that have pumped or dumped hard in the past 24 hours. Would like PT to exclude coins that have moved 10% +/- (versus BTC, ETH or USDT) automatically. I understand PT Magic has this facility, could this be implemented in PT?

**Comment by taniman** [comment]
check the milestones before adding new issues. We have a similar request already being built into a milestone
