### ISSUE TITLE
Log profit of sells in ouput?

### ISSUE THREAD

**Issue by Fransenson** [taniman/profit-trailer#1351]
Hey there!

I am trying to build something for Notifications and probably statistics and I was wondering why there is info about the profit in buy-log lines, but not in sell-log lines.

What would be the best place to look for the profit of the last sell?

**Comment by SgtBatten** [comment]
the exchange is the absolute record

**Comment by Fransenson** [comment]
@SgtBatten Can you elaborate on that? Aren't there local logs containing the needed information?

**Comment by SgtBatten** [comment]
they are not going to be 100% reliable

**Comment by Fransenson** [comment]
That would be fine, but I‘d like to include them (even as estimate) into my telegram notifications

**Comment by SgtBatten** [comment]
sales data is contained in the json file

**Comment by Fransenson** [comment]
Is this the profit of the last sale or the overall profit with this coin?

`"market":"NEBLBTC","profit":1.0080376365521062,`

**Comment by SgtBatten** [comment]
Ive never looked in my json, does it match the profit in your sales log for that sale?

**Comment by Fransenson** [comment]
Good call. In the webinterface it is rounded up to 1.01%. Should be fine! Thank you!
