### ISSUE TITLE
FEATURE REQUEST - RANGEBB buy strategy 

### ISSUE THREAD

**Issue by jimmyjimmyv** [taniman/profit-trailer#1352]
Would it be possible to have a strategy where the bot would buy in a range of BB? Like if I only wanted to buy in a HIGHBB range of 25 - 50%. We could make a Whitelist of only coins that are rising in price but not going lower than 50% and only trading in the upper half of the bands. Currently, we have to choose a value and the bot will buy at that price OR ANY that are higher. I wouldn't want to buy at the top and I don't want to buy at any price lower than 50% for fear that the price will continue falling.

**Comment by taniman** [comment]
the new features release version of PT will allow setting a buy_value_limit for BB strategies too. So in escense I think you could use that to set a range.
