### ISSUE TITLE
LOWBB not showing correct current value on BINANCE

### ISSUE THREAD

**Issue by victorlmt1** [taniman/profit-trailer#1353]
Hello, i use the LOWBB strategy and looks like it`s not showing the right value for the current value.

Here is Profit Trailer Screen:

![current value on pt](https://user-images.githubusercontent.com/18018354/36945487-9339eeb2-1f8d-11e8-9a6f-563d3d99b39f.png)

Here is how it looks like on trading view:

![how it looks like on tradingview](https://user-images.githubusercontent.com/18018354/36945502-c9bdca94-1f8d-11e8-96f8-6509e1cbf440.png)

It`s obviously not in the -80 current lowbb value, am I right?

Here is my log file:

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1778468/ProfitTrailer.log)

Is there anything that I could do? Is it a Bug? thank you.

**Comment by taniman** [comment]
This is a display problem.  I will remove the current value from lowbb again. This is causing too much confusion.
