### ISSUE TITLE
Bought price disappearing after partially filled expired order and filled order - Binance

### ISSUE THREAD

**Issue by abyss007** [taniman/profit-trailer#1354]
This is not a biggie, but it would be nice to have a fix.  The example I got is for BCCUSDT pair. 

![capture](https://user-images.githubusercontent.com/37042912/36946949-c4da22d2-1f8a-11e8-8e09-37849f14777c.PNG)

![capture2](https://user-images.githubusercontent.com/37042912/36946952-ced2fc32-1f8a-11e8-94a4-4c49ceb84999.PNG)

The BCC total is slightly more because I had some dust.
Thank you if you can look into it.  Regards.

Quick fix / work around is the manual HotConfig, and it works well.

**Comment by taniman** [comment]
Have you tried using the ALL_buy_available_volume_trigger to avoid the partial buys?

This is a tricky one. we will be working on the calculator some more soon. So it might get resolved

**Comment by abyss007** [comment]
Very cool.  Thanks for this tip.  Will make use of it for sure.
