### ISSUE TITLE
DCA Pairs showing in Pairs log

### ISSUE THREAD

**Issue by Brillynt** [taniman/profit-trailer#1356]
Intermittently all the pairs from the DCA log show in the Pairs log and will stay there until it suddenly decides to move them back.  

[ProfitTrailerData-1520188673.DCA_Issue.json.backup.zip](https://github.com/taniman/profit-trailer/files/1779098/ProfitTrailerData-1520188673.DCA_Issue.json.backup.zip)

[image](https://user-images.githubusercontent.com/399748/36952237-087fa16a-1fdb-11e8-8692-3308f148f86c.png)

**Comment by leoneparise** [comment]
I had the same issue https://github.com/taniman/profit-trailer/issues/1319

**Comment by Brillynt** [comment]
Appears to be a PT Feeder 1.4 issue, rolled back to PT Feeder 1.3.5 and everything is good again.
