### ISSUE TITLE
Delay in Refresh of Data from Binance

### ISSUE THREAD

**Issue by artissh1** [taniman/profit-trailer#1357]
There appears to be a delay in the update of data from Binance to profit trailer.  The delays result in money lost on trades.  Is there a way to force a manual update of profit trailer from Binance?

**Comment by taniman** [comment]
What data are we talking update? 
Cause ticker data is retrieved using a websocket connection from binance.
ChartData is also retrieved using websocket connection.

**Comment by YoJeff** [comment]
The gui is always up to 10s delayed because -- that's how it works ;)
