### ISSUE TITLE
[FEATURE REQUEST] Setting up a specific buy value for a coin

### ISSUE THREAD

**Issue by andos21** [taniman/profit-trailer#1358]
If you trade manually you maybe will set an order for a lower price.

For example BTC is at 11550 and you want to buy at 11420. So you place an order for the price 11420.

When pt would support such a buy price, for example BTCUSDT_specific_buy_value = 11420, you can make use of the trailing feature and so if the price drops more you would buy at 11320 instead of 11420.

So with pt you can buy in at a lower price because of the help of the trailing feature what can generate you more profit.

This can also programmed for a specific sell_value.

**Comment by jason-gu** [comment]
+1 this is a very useful feature I would like to see in PT.

**Comment by YoJeff** [comment]
#894 duplciate
