### ISSUE TITLE
[FEATURE NEEDED] . Average Profit Percentage of Sales Log transactions Independent of ETH/BTC price

### ISSUE THREAD

**Issue by Tycoon443** [taniman/profit-trailer#1359]
Please add a feature that averages all your sales log transactions profit percentages and gives you a average so that way you can easily measure the performance of your PT settings.

Currently our average daily profit percentage gets muddied up with the price fluctuations of ETH and BTC

**Comment by taniman** [comment]
I am not understanding this request. And secondly I feel like this request is not benefiting trading.

**Comment by Tycoon443** [comment]
Right now we have no way to tell what our average profit is daily...the only figure we have goes up and down with ETH or BTC prices....

When tweaking our settings everyone wants to know how their settings are performing....if we had an average profit percentage of the trades in our sales log it would be very helpful to know.

**Comment by Tycoon443** [comment]
Right now the only profit we can see is a dollar amount, not a average percentage of our trades in our sales logs.  But if you look all over youtube and other places people are clamoring and asking about settings that produce a certain percentage return daily....be it 2% or 5% or whatever.  it's an important measuring factor....

**Comment by YoJeff** [comment]
I agree with @taniman .   Between the sales logs, exports, and exchange -- you have everything.   Lets focus on trading.
