### ISSUE TITLE
[Security] Encrypt Server Password

### ISSUE THREAD

**Issue by smoochy** [taniman/profit-trailer#1361]
Heya,

so far, the server password to protect the access to the PT webgui is stored in plaintext in application.properties.

It would be better, if it would be handled like with ProfitTrailer Magic, which generates a separate settings.secure.json which contains the server password, but in encrypted form.

**Comment by YoJeff** [comment]
You are more likely to get your password exposed by not using SSL than you are by somebody hacking into your VPS.    The API keys are in plaintext -- aren't those the real prize?

**Comment by ramonduraes** [comment]
An important suggestion that should not be ignored.

**Comment by smoochy** [comment]
As a lot of people are not using different passwords for different services (opposed to what they should do), the bigger issue would be access to this password.

**Comment by Legedric** [comment]
@YoJeff Some (me for example) are using SSL to access their PT monitor so the plain text file storing password, API keys AND their secrets is still a vulnerability.

We did that for PT Magic in a way that the user has to setup his own password on the first start of the monitor and we save it encrypted in a separate file.

However, this will of course be somewhat different/difficult for Profit Trailer as the PT monitor needs to have PT running (and probably the API keys validated) to have access to the monitor at all. So encrypting the API keys/secrets may not be that easy for the Profit Trailer devs to achieve as just encrypting a simple password @smoochy .

**Comment by smoochy** [comment]
Thank you for adding this feature. Much appreciated.
