### ISSUE TITLE
FEATURE REQUEST: Don't buy pairs when x% raise last 24hours

### ISSUE THREAD

**Issue by jerbnl** [taniman/profit-trailer#1362]
It would be nice  if  you can set this value so that PT will not buy pairs when they have risen x% in the last 24 hours . Or is this already possible?

**Comment by YoJeff** [comment]
#196 duplicate

**Comment by jerbnl** [comment]
I do not mean % rise of BTC but rise of any other coin that PT is allowed to buy but not when it has risen above a specific %

**Comment by YoJeff** [comment]
I saw this one also before, but it might be over on the new features github.    Check to see it doesn't already exist and throw it over here for voting:
https://github.com/taniman/profit-trailer-enhancements
