### ISSUE TITLE
Website isn't showing correct balance and sales

### ISSUE THREAD

**Issue by Duskfall** [taniman/profit-trailer#1363]
.20 and .21 versions don't show balances correctly. They also don't show the different logs.
.19 works fine.
http://localhost:8081/monitoring/data AJAX call returns false result for balance.

**Comment by YoJeff** [comment]
Details.....

**Comment by Duskfall** [comment]
![image](https://user-images.githubusercontent.com/2528125/37001739-2c4e889a-20d0-11e8-94b5-00f002715385.png)

My balance is 0.0842 BTC

![image](https://user-images.githubusercontent.com/2528125/37001785-4f123818-20d0-11e8-9508-c29609936025.png)

![image](https://user-images.githubusercontent.com/2528125/37001799-59f5ea18-20d0-11e8-8eba-82584607cf32.png)

**Comment by YoJeff** [comment]
Make sure your time is right...   Figure out what's spamming your settings every 30 seconds.   Check in support on discord.

**Comment by Duskfall** [comment]
PT-Feeder...
