### ISSUE TITLE
Profit trailer doesn't run

### ISSUE THREAD

**Issue by khayalahmadzada** [taniman/profit-trailer#1366]
Dear all,

I have purchased, activated and configured my profit trailer. However, when I start it with the cmd file, it goes to some extent, then says "press any key to continue". When I press a key, the black window just closes and then nothing happens. I tried to open it through cmd manually, it still doesn't work. Please help

**Comment by YoJeff** [comment]
Support on discord will get you fixed up.   This is for bugs.
