### ISSUE TITLE
[Feature Request] FIX API Integration

### ISSUE THREAD

**Issue by Knopfler23** [taniman/profit-trailer#1367]
The new XTRD platform will create a single point of access for all crypto exchanges, unified with a single FIX API (the standard in stock markets). I propose that PT integrate a FIX API feature so that we can use PT to run through XTRD on ALL exchanges. This will significantly increase liquidity.

**Comment by taniman** [comment]
This platform is not live yet. Once it is live and has proven itself we can look further into it
