### ISSUE TITLE
Wrong date showing in heartbeats notifications popup

### ISSUE THREAD

**Issue by jodee8** [taniman/profit-trailer#1369]
Hi team, I've just noticed that on all 3 of my bots running the newly upgraded v21. The heartbeats notification popup is showing the wrong date and time. The date is a whole day ahead. Yet in the sales/dca/pairs logs, the terminal window and in the server log its all displaying correctly. I've tried multiple restarts on all bots with no change to the problem.

**Comment by taniman** [comment]
Please check the date and time on your server running profittrailer and your settings for server.timeZoneOffset.

There is nothing wrong with the heartbeats itself. they are showing the correct date and time on my machine.

**Comment by jodee8** [comment]
Hi Taniman, The server.timeZoneOffset is set correctly in the applications.properties file on all 3 bots as +08:00. And the Server Time is set correctly on 1 local Raspberry pie and the other 2 on a Google Cloud Compute Instance. On further investigation I've discovered that the date today is correct but the time is what is actually out by exactly +8hrs. So it appears what is occurring is that the notification time is applying the server.timeZoneOffset = +08:00 to the already adjusted local time rather than the unadjusted server time.

**Comment by SgtBatten** [comment]
do you actually live in GMT +8 timezone?

**Comment by jodee8** [comment]
yes

**Comment by SgtBatten** [comment]
is UTC time and local time reflected correctly in your bots?

**Comment by jodee8** [comment]
yes both are displaying correctly on the GUI on all 3 bots

**Comment by SgtBatten** [comment]
can you please take a screenshot of all three times UTC, LOCAL, and notification time being wrong.

**Comment by jodee8** [comment]
![untitled](https://user-images.githubusercontent.com/35490324/37069663-52b11a46-21ef-11e8-9164-3ec397d9f551.png)
![untitled 2](https://user-images.githubusercontent.com/35490324/37069664-52ff5dc8-21ef-11e8-92e8-5512c288c428.png)

**Comment by SgtBatten** [comment]
I don't get it. 

I'm in GMT+11 and mine says the same time as locks time displayed top right.

Perhaps a browser caching issue. Have you tried clearing it all?

**Comment by jodee8** [comment]
i've tried clearing the browser cache (Safari Version 11.0.3), cleared cookies and the problem still persists.

**Comment by jodee8** [comment]
Ok so that seems to have isolated things to the Safari browser. Its working as expected on Chrome. Strange thing is I have completely cleared Safari's cache using the "Empty Caches" from the Develop menu. 

Hmmmm, the plot thickens! I just tried my iPhone with mobile Safari on iOS and it presents the same problem as it does with Safari on MacOS. Chrome on iOS also presents the same problem, yet Chrome works fine on MacOS... The mystery continues!
