### ISSUE TITLE
Sell Strat PANICSELL add to profit

### ISSUE THREAD

**Issue by Gitulu** [taniman/profit-trailer#1372]
Hello guys,

PT bought a coin: "BCDBTC" for "0.00633638" but wrongly in the pairs log recorded the bought cost with: "0.00000000". In this case the profit percentage freezed  to "0.00%".

After some minutes after bought I have sold the coin via "PANICSELL" manually.
Otherwise this coin will be a blocker.

![panicsell](https://user-images.githubusercontent.com/35115314/37051068-d1823aaa-2175-11e8-8de9-74b27812464b.png)

As you can see in the sales log. PT added the buy value as profit but this is not possible.

Thank you great software

**Comment by taniman** [comment]
The coin was missing bought_cost. So the idea was that you should put bought_cost in order to fix the problem. Now you did a panic sell and still PT did not know the price so it marked it as 0.00 %

So next time set the bought_price for coins missing the bought_price. 0.000000
