### ISSUE TITLE
Binance price not accurate in PT

### ISSUE THREAD

**Issue by kaotic818** [taniman/profit-trailer#1373]
I noticed  the price in binance is different from PT it takes 15-30 seconds to update and by that time binance price has changed. Not sure if this is throttling the API calls. 
![binanceissue](https://user-images.githubusercontent.com/25557712/37061604-d4690c26-2148-11e8-9ab2-bc4612a3fd11.JPG)

**Comment by YoJeff** [comment]
The gui polls the bot every 10 seconds.   So the price will lag by up to 10 seconds.   This isn't a realtime bot.
