### ISSUE TITLE
New pair purchased but then asked for bought price

### ISSUE THREAD

**Issue by dorianbanks** [taniman/profit-trailer#1374]
PT bought INSBTC and didn't record the bought price, now continually asking it to be set.
P T Ver:  1.2.6.21

<img width="965" alt="screen shot 2018-03-06 at 3 07 30 pm" src="https://user-images.githubusercontent.com/37125619/37064126-8f4d82ea-2150-11e8-840d-b9f80f05f331.png">

**Comment by YoJeff** [comment]
Set it.

**Comment by dorianbanks** [comment]
Ya, I did.  Not really the point though.

PT won't sell the coin without knowing cost base....so it could sit there overnight without anyone knowing.
