### ISSUE TITLE
[BUG ]Pairspecific SOM overrides or ignore_sell_only_mode = false are sometimes ignored

### ISSUE THREAD

**Issue by ACETyr** [taniman/profit-trailer#1375]
Seen on V1.2.6.20 as well as on V1.2.6.21
It seems pair specific SOM overrides are **sometimes** ignored for a short period of time after ALL_btc_price_drop_recover_trigger kicks in and turns global SOM off resulting in DCA of a pair.
In DCA.properties ignore_sell_only_mode = false is set.
I cannot determine if it is the pair specific SOM or the ignore_sell_only_mode = false that is not working.
I am using feeder on that bot but we can rule out a config issue -> proof is in the log as the config is not changed during the period of time.

My interpretation of the log excerpt (attached):

**2018-03-06 15:23:01** -> we are in global SOM because of Price Drop Trigger
**somewhere around 15:31** price drop deactivates (not logged!) but thats the timestamp i got telegram confirmation from Bot -> 
![image](https://user-images.githubusercontent.com/35745290/37079375-a58148c0-21e2-11e8-87c7-93e57a98f7e8.png)
**2018-03-06 15:31:35** PT DCA kicks in instantly and buy order gets filled
**2018-03-06 15:46:42 PT** wants to buy again after rebuy timeout is over and correctly does not because of pair specific SOM.

During the time of the attached log snippet no config changes were logged we can rule out  intervention from either manual file edit AND/OR feeder.

[SOM_Issue.txt](https://github.com/taniman/profit-trailer/files/1788209/SOM_Issue.txt)

I have 2 more occurences -> same pattern but in those cases there were config changes logged so feeder influence cannot be falsified there.

**Comment by taniman** [comment]
please provide your trading folder files

**Comment by ACETyr** [comment]
[trading.zip](https://github.com/taniman/profit-trailer/files/1793728/trading.zip)

**Comment by taniman** [comment]
Nice catch
