### ISSUE TITLE
v1.2.6.21 DCA have bug ?

### ISSUE THREAD

**Issue by g001613001** [taniman/profit-trailer#1377]
Is v1.2.6.21   DCA  have bug?
I set ALL_max_cost = 135, and my TPV is 17827
DCA buy_trigger can be use to 6
But I found use to DCA3 , my balance is left 24.
Is this is bug?
![image](https://user-images.githubusercontent.com/18544298/37094536-2ac57978-224e-11e8-8132-26b061f4c2d1.png)
![image](https://user-images.githubusercontent.com/18544298/37094539-2d9d3730-224e-11e8-982a-ea91abf91f54.png)
![image](https://user-images.githubusercontent.com/18544298/37094543-2f8924be-224e-11e8-97f5-a6e36be7afdb.png)

**Comment by taniman** [comment]
please attach your log file + dca.properties + pairs.properties

**Comment by SgtBatten** [comment]
ALL_max_cost is different from max_cost in dca.properties. they do different things.
I'm not sure if thats what you are questioning or if it is that you thought ALL_max_cost would stop it going below 135 when the setting that does this is min_buy_balance

If its neither of those, i am not sure what you are asking

**Comment by keithofaptos** [comment]
wrong response.you mean to be contacting someone else on that issue i
believe.
