### ISSUE TITLE
GUI Frontend Feature Request: Fixed Font Size in Browser / Collapsible Sidebar

### ISSUE THREAD

**Issue by sirloinwesk** [taniman/profit-trailer#1381]
Hi, would there be any way to stop the scaling of fonts as well based on browser window size?
Or a way to collapse the sidebar? 

On a 4k monitor I have about 4 browsers open, and the size of the texts become impossible to see. Not a major thing, but would be nice to see down the line. Thanks for all the work you guys do!

**Comment by djcrypto75** [comment]
I will think of a solution in the future. Until then you can zoom in/out
You can already minimize the sidebar.

**Comment by sirloinwesk** [comment]
Sorry I just realised adblock was hiding the button! Thanks for the support mate!
