### ISSUE TITLE
EMACROSS Volume Trigger Feature Request

### ISSUE THREAD

**Issue by sirloinwesk** [taniman/profit-trailer#1382]
Would it be possible to have the bot trigger the buy order based on volume amount at a particular candle after the cross? For instance if the cross happened x candles ago and volume has risen a certain number execute the buy. 

Thanks for the help as always!

**Comment by YoJeff** [comment]
Throw this comment on one of the open EMACROSS issues please.

**Comment by sirloinwesk** [comment]
Ok thanks
