### ISSUE TITLE
ALL_pending_order_wait_time not useful

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#1386]
I talked to support about my issue and they said it was because I had this setting:
ALL_pending_order_wait_time = 2880

My issue was that the bot released a sell order that was just sitting there not executed, and it showed in my "Pending Log" page.
I see no point for having this parameter, because creating a sell order with a price higher than the current price in order book, will just sit there and not get executed. When the price will rise again the bot would execute it automatically without this feature. I guess the point of this parameter would be to sell it at 0% profit instead of my set profit in the sell strategy, but it would be better to just control that profit level per this coin instead of releasing a sell order that would sit there.
Also the issues I got from this is, that I cancelled that sell order, then the bot was showing a wrong amount for that coin, because it considered sold my pending order. So I cleared my database and started from scratch, but then all my previous buys were counted as an original buy without any DCA levels yet, so it ended up doubling down and buying my total amount again. That resulted in this mess - a lot of buys for the same pair and using up my balance:
![image](https://user-images.githubusercontent.com/6478474/37159805-b7783eaa-22bc-11e8-9ba0-f56e291caaac.png)
The orange line is my average price. I hope it can still sell at that level, but I just saw another sell order in pending log.
I am also not sure if it created the sell order at the right time, because I had:
ALL_pending_order_wait_time = 2880, which means 48 hours, but my last buy was at:
2018-03-05 20:38:35
and the pending sell order was placed at:
2018/03/08 02:31:35

48 hours past would have been at 2018-03-07 20:38:35, so it looks like it waited about 6 more hours.
Is it because it did some trailing?
Here are some screenshots from my Binance orders pages:
![image](https://user-images.githubusercontent.com/6478474/37160434-31dcf874-22be-11e8-9600-abde238e9701.png)
pending order:
![image](https://user-images.githubusercontent.com/6478474/37160366-0aa2d9cc-22be-11e8-975f-e7f3caae2ae8.png)

Thanks.

**Comment by YoJeff** [comment]
'Not useful' is a bit presumptious.

The pending functions as designed.  It's purpose is to slap a price on it according to your strat and throw it up on the shelf for sale, while allowing the bot to continue to trade that pair. 

Is there a feature request in here?

**Comment by nstefi** [comment]
I'm just saying that there is no point to throw it up on the shelf for sale with the exchange, because it would just sit there for a while. It would be better if the bot monitors it and sells it when the price rises back.
Maybe it would be better to just control the profit level instead and sell for 0% profit instead of waiting for the standard sell strategy profit. That would be a feature request replacing this current procedure.

**Comment by YoJeff** [comment]
So for the people that are using pending as it stands now we should say 'tough, nstefi thinks this feature is pointless?'

**Comment by YoJeff** [comment]
Submit a feature request on the features github to kill pending.   Closing...
