### ISSUE TITLE
Poloniex Price issue

### ISSUE THREAD

**Issue by mygreeneggsandham** [taniman/profit-trailer#1387]
It bought and immediately was down over 13% which was impossible. it then DCAd 4 times. It was technically in the positive but PT said it was way down. The price was rising but it was dcaing as if it was sinking.  
![image](https://user-images.githubusercontent.com/22647980/37178712-4e918740-22f1-11e8-88c9-be4d2b190b43.png)
this is what really happened:
![image](https://user-images.githubusercontent.com/22647980/37178747-6e020140-22f1-11e8-9530-cd28c9b10f33.png)

and then it bought XMR and within a minute or so sold it for a "profit" but in reality at a loss
![image](https://user-images.githubusercontent.com/22647980/37178779-8bd586d8-22f1-11e8-8e9a-402bce05ead6.png)
here is what really happened:
![image](https://user-images.githubusercontent.com/22647980/37178827-a3a7fe3a-22f1-11e8-9e7b-c30ba3b6bf81.png)

from what I can see, Poloniex bot is significantly broken

**Comment by YoJeff** [comment]
The avg cost on the first one is within 0.29%
The second one has different quantities.

**Comment by taniman** [comment]
please provide your log file in order for us to trace the possible problem

**Comment by mygreeneggsandham** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1798027/ProfitTrailer.log)

**Comment by taniman** [comment]
Sorry I cannot see what went wrong here. 
Please check your pairs.properties if you have set any prices manually in the file

If this happens again re create the issue.
