### ISSUE TITLE
No 'bought price' being entered.

### ISSUE THREAD

**Issue by thejdg** [taniman/profit-trailer#1388]
I have just set up profit trailer on Binance with what I believe to be the correct settings. It seems to be running fine but I have 8 pairs in my log that have no bought price even though a transaction has taken place. 

The log keeps asking me to add the bought price.

1. I don't know how to do this
2. How can I prevent this from happening again?

**Comment by kaotic818** [comment]
I get this issue all the time. I happens for me when you move coins into the exchange it doesn't know the bought price.





________________________________

**Comment by thejdg** [comment]
These are all trades opened by PT

**Comment by taniman** [comment]
Update to latest version just released

**Comment by hotpt** [comment]
The bought price of one coin (rest is ok) is missing, even after updating to newest version .25.
Isn't PT connecting to trade history on binance?
