### ISSUE TITLE
Bought prices keep disappearing!

### ISSUE THREAD

**Issue by DaveBaddeley** [taniman/profit-trailer#1390]
I am running a new instance of PT Ver:  1.2.6.21 against a Binance account with existing holdings.
When the bot fired up I set bought prices using the hot config, but under circumstances the bought prices for some of the coins have suddenly been lost.

1) The pair BNBBTC keeps losing it's price randomly after a short period of time. I have set it 4 times now using the hot config and it has reverted 4 times:
![image](https://user-images.githubusercontent.com/11334852/37204208-fa1b65fe-2387-11e8-8708-9235f2519a49.png)

2) After a partial sale of BRDBTC the bought price was lost leaving the remaining portion unsold until I manually set the bought price again using the hot config.

Snippet from my log showing the initial sale of BRDBTC and then the bot asking for the bought price straight afterwards:

1|profit-t | 2018-03-09 10:31 +00:00: 2018-03-09 10:31:31 INFO ProfitTrailerService - Cache Heartbeat
1|profit-t | 2018-03-09 10:31 +00:00: 2018-03-09 10:31:36 INFO ProfitTrailerService - DCA Heartbeat
1|profit-t | 2018-03-09 10:31 +00:00: 2018-03-09 10:31:43 INFO ProfitTrailerService - Normal Heartbeat
1|profit-t | 2018-03-09 10:32 +00:00: 2018-03-09 10:32:31 INFO AverageCalculator - Please set BNBBTC_bought_price
1|profit-t | 2018-03-09 10:35 +00:00: 2018-03-09 10:35:22 INFO NormalStrategyRunner - You are not allowed to buy OSTBTC. Buy will exceed min buy balance 0.01631115. BAL: 0.01540000 - MC: 7.0E-4
1|profit-t | 2018-03-09 10:35 +00:00: 2018-03-09 10:35:52 INFO NormalStrategyRunner - You are not allowed to buy VIBEBTC. Buy will exceed min buy balance 0.01631115. BAL: 0.01540000 - MC: 7.0E-4
1|profit-t | 2018-03-09 10:37 +00:00: 2018-03-09 10:37:13 INFO NormalStrategyRunner - You are not allowed to buy NCASHBTC. Buy will exceed min buy balance 0.01631115. BAL: 0.01540000 - MC: 7.0E-4
1|profit-t | 2018-03-09 10:38 +00:00: 2018-03-09 10:38:52 INFO ProfitTrailerService - Sell order for BRDBTC sold amount 104.000000 for price 0.000071 -- {"symbol":"BRDBTC","orderId":4992191,"clientOrderId":"dN1BNLUgloDH5r5awtUgw2","transactTime":1520591932272,"price":"0.00007146","origQty":"104.00000000","executedQty":"21.00000000","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
1|profit-t | 2018-03-09 10:38 +00:00: 2018-03-09 10:38:58 INFO ProfitTrailerService - Get order information -- {"symbol":"BRDBTC","orderId":4992191,"clientOrderId":"dN1BNLUgloDH5r5awtUgw2","price":0.00007146,"origQty":104.00000000,"executedQty":21.00000000,"status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1520591932272}
1|profit-t | 2018-03-09 10:39 +00:00: 2018-03-09 10:39:04 INFO AverageCalculator - Please set BRDBTC_bought_price
1|profit-t | 2018-03-09 10:39 +00:00: 2018-03-09 10:39:33 INFO ProfitTrailerService - Cannot buy NCASHBTC. Please increase max_cost to approximately 0.001!
1|profit-t | 2018-03-09 10:40 +00:00: 2018-03-09 10:40:02 INFO ProfitTrailerService - Cannot buy OSTBTC. Please increase max_cost to approximately 0.001!
1|profit-t | 2018-03-09 10:41 +00:00: 2018-03-09 10:41:13 INFO Util - Detected configuration changes
1|profit-t | 2018-03-09 10:41 +00:00: 2018-03-09 10:41:32 INFO ProfitTrailerService - Cache Heartbeat
1|profit-t | 2018-03-09 10:41 +00:00: 2018-03-09 10:41:35 INFO AverageCalculator - BRDBTC using bought price 6.886E-5
1|profit-t | 2018-03-09 10:41 +00:00: 2018-03-09 10:41:40 INFO ProfitTrailerService - DCA Heartbeat
1|profit-t | 2018-03-09 10:41 +00:00: 2018-03-09 10:41:46 INFO ProfitTrailerService - Normal Heartbeat
1|profit-t | 2018-03-09 10:42 +00:00: 2018-03-09 10:42:14 INFO NormalStrategyRunner - You are not allowed to buy NCASHBTC. Buy will exceed min buy balance 0.01632091. BAL: 0.01691158 - MC: 7.0E-4
1|profit-t | 2018-03-09 10:42 +00:00: 2018-03-09 10:42:36 INFO AverageCalculator - Please set BNBBTC_bought_price
1|profit-t | 2018-03-09 10:43 +00:00: 2018-03-09 10:43:24 INFO ProfitTrailerService - Sell order for BRDBTC sold amount 83.000000 for price 0.000070 -- {"symbol":"BRDBTC","orderId":4993975,"clientOrderId":"WzU75LF6eqivkNmfNYsBMN","transactTime":1520592204414,"price":"0.00006963","origQty":"83.00000000","executedQty":"83.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
1|profit-t | 2018-03-09 10:43 +00:00: 2018-03-09 10:43:29 INFO ProfitTrailerService - Get order information -- {"symbol":"BRDBTC","orderId":4993975,"clientOrderId":"WzU75LF6eqivkNmfNYsBMN","price":0.00006963,"origQty":83.00000000,"executedQty":83.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1520592204414}
1|profit-t | 2018-03-09 10:44 +00:00: 2018-03-09 10:44:21 INFO ProfitTrailerService - Cannot buy CMTBTC. Please increase max_cost to approximately 0.001!
1|pr

This seems quite a bad bug, as I have definitely missed sales due to this. Restarting the bot has had no affect on the behaviour.

Thanks

**Comment by SgtBatten** [comment]
BNB will always forget the bought price because the amount you own changes every trade you make. If we allowed the bot to just make an assumption that it is only trade fees and the average price should be unchanged we will end up with miscalculations when manual trading occurs. So put up with the message or hide bnb from your bot is all you can do.

As for number 2 this is unfortunate but can happen with partial trades. Due to the way the bot does a countback only as far as it takes to get enough coins as it now sees in the balance this is also risky. If it's not clear cut it is safer to ask you.

**Comment by taniman** [comment]
update to newest version too. just released

**Comment by DaveBaddeley** [comment]
Thanks for the feedback; will update tonight.
