### ISSUE TITLE
Rebuy timeout problem in possible buy log

### ISSUE THREAD

**Issue by Masterman1980** [taniman/profit-trailer#1391]
Installed the latest version: v1.2.6.22

I have only a rebuy parameter in my DCA.properties. Sold a pair 5 minutes ago. Then in my possible buy logs behind the pair : REBUY TIMEOUT (false). I did't set any rebuy parameters in my PAIRS.properties.  Only in DCA.poperties.

**Comment by YoJeff** [comment]
What is the problem/bug?   false means no, disabled, not enabled

**Comment by Masterman1980** [comment]
The problem/bug is. Sold a pair. PT doens't buy the coin again because of a REBUY timeout active. I didn't set a rebuy timeout parameter in pairs.properties. Only in DCA.

**Comment by Mikeeetrue** [comment]
@Masterman1980 why is it closed? The problem wasn't fixed.
If I set rebuy timeout in DCA it also influences possible buy which is wrong. 
Needs to be fixed.
