### ISSUE TITLE
Feature Request: BUY/SELL signals based off CCI Indicator

### ISSUE THREAD

**Issue by ColdMedina** [taniman/profit-trailer#1393]
The CCI Indicator is calculated from several other indicators. It is simply a calculated number based off historical price vs. present price, and has proven very effective for me to trade with. 

I would LOVE for it to be a BUY and SELL signal in Profit Trailer. If this is not the appropriate place to post, apologies.

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:commodity_channel_index_cci

**Comment by YoJeff** [comment]
Search to see if this request already exists and throw it over on the features github for voting....
https://github.com/taniman/profit-trailer-enhancements
