### ISSUE TITLE
EMACROSS buying towards the bottom on a Positive value

### ISSUE THREAD

**Issue by doctoryogi** [taniman/profit-trailer#1395]
Hi Team,

I setup my bot today to use EMACROSS

ALL_buy_strategy = EMACROSS
ALL_buy_value = .25

For DCA i did 2 candles. But look where it it bought. 
![image](https://user-images.githubusercontent.com/35791967/37229722-036bd942-23b3-11e8-828c-0e1af04c64c2.png)
Can you tell me why it did that. 

I thought it was always suppose to buy towards the up if the number for Buy value was a positive number and only buy towards the down if the number was a negative number. What exactly am i doing wrong here and how do i rectify it

**Comment by Nazispele** [comment]
WTF , YOU ASKING DEV TO SHARE PROBLEM WITH THE ONLY INFORMATION GIVEN IS YOUR CROPPED SCREENSHOT ?! MOFO....

**Comment by doctoryogi** [comment]
Hey Stupid Nazi, Chill..

**Comment by taniman** [comment]
I am seeing a lot of color on that graph. please provide your log file. and indicators.properties settings

**Comment by doctoryogi** [comment]
HI taniman, i think i figured it out. I had the buy value set to very low on a 15 minute candle. What i did notice was that in Profit Trailer, the cross value was showing positive even before the cross had taken place as showing in trading view using Binance. Now, it might be a delay or a bug, i am not sure.

**Comment by doctoryogi** [comment]
I figured it out. it was my fault. You can close the ticket.
