### ISSUE TITLE
EMACROSS buying at the wrong time

### ISSUE THREAD

**Issue by Cryptoqueb** [taniman/profit-trailer#1396]
I know it's a known issue, but I thought it could help to post the issue none the less. 

Pair : 

"BuyStrategy": "EMACROSS", // ALL_buy_strategy
"BuyValue": "-0.35", // ALL_buy_value

Indicator : 

EMA_cross_candles = 3
EMA_period = 300
EMA_1 = 24
EMA_2 = 3

MTLBTC (BINANCE - bought at 13:35:02)

(Yellow : fast / blue : slow)
![emacross_issue_1](https://user-images.githubusercontent.com/35400485/37230294-f391ba76-23b4-11e8-8b18-1b9a23626827.jpg)

Look like it bought roughtly 10 minutes after the cross (first issue, I think), yet the buy value from the last 3 candles were positive (second issue, for sure)

**Comment by taniman** [comment]
I am not seeing the error in this buy.

Cross candles is set at 3
So it bought correct as the crossed happened within the last 3 candles. excluding current candle.

whats the spread of the lines on the big red bar? is it lower than -0.35??

All in all not seeing an issue

**Comment by Cryptoqueb** [comment]
I've read misleading information about the Strat online so I misunderstood how it fonction as a whole. I thought it would look at the 3 candles BEFORE the cross. Should have went deeper before trying the strat. Althought I did only 2 buys that sold quite quickly before I changed back to EMASPREAD, this could have been bad. 

Sorry for losing your time my man. Thx for all your work.
