### ISSUE TITLE
Please set the BQX-BTC price

### ISSUE THREAD

**Issue by john020884** [taniman/profit-trailer#1397]
Hello I purchased some BQX (ethos) with ethereum on binance before i downloaded the App. 

I am currently getting an error message saying: 

"Please set the BQX_BTC bought price"

How do i set the BQX price?

Thanks

**Comment by YoJeff** [comment]
https://wiki.profittrailer.com/doku.php?id=hotconfig
Hop in discord if you need anything further.  This is for bugs.
