### ISSUE TITLE
[Feature Request] Displaced EMACROSS

### ISSUE THREAD

**Issue by DomoKB** [taniman/profit-trailer#1398]
Provide a setting in indicators to allow offsetting of EMA backwards or forwards in time by x number of candles.  A displaced EMA can provide earlier signals by effectively removing/reducing the 'lag'.

https://www.investopedia.com/terms/d/displacedmovingaverage.asp

21/8 EMA with no displacement
![withoutdisplacement](https://user-images.githubusercontent.com/13867804/37238788-e3ab22fa-2481-11e8-8581-c74cbbb7583c.png)

21/8 EMA with -8 candle displacement
![withdisplacement](https://user-images.githubusercontent.com/13867804/37238792-f8f844d0-2481-11e8-8177-f8a8d487ae94.png)

**Comment by taniman** [comment]
Add this request
https://github.com/taniman/profit-trailer-enhancements
