### ISSUE TITLE
Feature Request - DCA to Pending w/Sell Order

### ISSUE THREAD

**Issue by usslindstrom** [taniman/profit-trailer#1399]
In order to handle some of the deep bags that can show up, I'd like to request a new feature be implemented.  Currently, the only way to handle bags once they have finished the DCA tree is to do one of the following:

- Panic Sell
- Meet a Stop-Loss criteria
- Or ride the wave back until the thing gets back to positive

What I'd like to suggest implementing...  Is once the DCA tree has gone all the way to the bottom, place a sell order on the coin, set at a defined percentage (like the DCA percentage) and move it to pending.

This way it would stop tracking it in the active pairs, and the bot could go and grab another set.  Just a thought.

Right now, I have stop losses setup in my bot below the DCA, but it would absolutely hurt should one of those actually be invoked, and gains for the day would be lost by a single sell.

**Comment by SleazyE** [comment]
Profit Trailer is having an "enhancement games". Put your enhancement request in an issue at https://github.com/taniman/profit-trailer-enhancements

**Comment by YoJeff** [comment]
You just described the pending feature as it exists.

**Comment by usslindstrom** [comment]
Please point me in the right direction where this is documented.  Because it is NOT working as you are suggesting it's supposed to.

I have my max DCA set to x4, - two coins of which have reached that max DCA time.  They are still being tracked within my DCA log.  They have not moved to pending, nor any sell order created for them.  Both have a "max buy times" indicator in the "buy strat" column.

The pending feature is not documented anywhere I can find it on the wiki, so if it does in fact work as you are saying then please let me (and others who may read this ticket) know where to find information on it.

**Comment by milanl71** [comment]
Is there a way to move a pair from pending order  to DCA?
