### ISSUE TITLE
Profit trailer can’t set bough prices 

### ISSUE THREAD

**Issue by trubo23** [taniman/profit-trailer#1401]
My profit trailer refuses to add the bought price after it purchases a coin. I literally have to go in there manually hit confit it Everytime it trades.

**Comment by SgtBatten** [comment]
Are you on latest version? 1.2.6.22

**Comment by trubo23** [comment]
i bought it and downloaded it yesterday how do i check the version

**Comment by trubo23** [comment]
i think im running 1.2.6.21

**Comment by trubo23** [comment]
ok can i drag my profit trailer folders such as pairs and such into the new folder. or will that bring the bug along with it

**Comment by SgtBatten** [comment]
Then you can upgrade to .22 and close this issue

**Comment by trubo23** [comment]
ok can i drag my profit trailer folders such as pairs and such into the new folder. or will that bring the bug along with it

**Comment by SgtBatten** [comment]
Upgrade instructions are on the wiki.

**Comment by trubo23** [comment]
appreciate the speedy reply
