### ISSUE TITLE
PT not buying according to EMAGAIN specs

### ISSUE THREAD

**Issue by meligo** [taniman/profit-trailer#1402]
hey 

using latest version of PT. 

I've set in the indicators file:
EMA_period = 300
EMA_1 = 24
EMA_2 = 3

In the Pairs file I have:
ALL_buy_strategy = EMAGAIN
ALL_buy_value = -0.5
ALL_trailing_buy = 0.15

But when I look at tradingview , "botindicators of EMAGAIN for profit trailer" than the bot should buy a couple of times but doesn't even do the trailing.. is there something wrong with the bot or tradingview strat?

**Comment by taniman** [comment]
This place is not for questions. If you have them contact support.
This clearly sounds like a setup/strategy issue.
