### ISSUE TITLE
ALL_combined_cancel_pending_trigger could be negative? How it works after the cancellation?

### ISSUE THREAD

**Issue by Mikeeetrue** [taniman/profit-trailer#1403]
I have two questions:
1. Could ALL_combined_cancel_pending_trigger be negative? E.g. after combined profit is reached -3% I want to move my pairs back to PT pairs log, so I can sell it with trailing
2. When this command is triggered, then what happened? A pair returns to pair logs with which boought price? Combined I hope.

**Comment by taniman** [comment]
Questions should be asked in our support channel.

1. A negative value can be use.
2. when it comes back it will indeed use try to use the combined price to continue. I mean it was already looking at the combined profit to exit from pending right?

**Comment by Mikeeetrue** [comment]
Thanks.
