### ISSUE TITLE
Please set POAETH_bought_price =

### ISSUE THREAD

**Issue by john020884** [taniman/profit-trailer#1405]
Hello. Everytime the bot makes a purchase on Binance it's says on command prompt "Please set POAETH_bought_price =".  I know how to manually set the bought price through hotconfigs but is there anyway to make ProfitTrailer to automatically register the bought price?  

I think this is a really important issue because I purchased the software to make trades automatically and if it won't set the "BOUGHT PRICE" automatically then the bot is not doing the job it's suppose to do which is buy and sell coins automatically. 

Is there anyway to fix this issue?

**Comment by taniman** [comment]
what version of the bot is this?

**Comment by john020884** [comment]
1.2.6.21

**Comment by taniman** [comment]
this is a known issue in that version. you should update to 1.2.6.22. which fixes that.
But I will release 1.2.6.23  soon. So wait on that one.

Did you not get a notification about 1.2.6.22?

**Comment by john020884** [comment]
ok thanks i'll download it now. Won't take long to upload to the VPS

**Comment by taniman** [comment]
the release is now online 1.2.6.23

**Comment by john020884** [comment]
excellent. Thanks Taniman. The updated version saved the issue
