### ISSUE TITLE
Feature request - add DCA option to control amount of coins to buy

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1406]
Now DCA buys 2x coin on balance. Would be great to add a configurable amount. For example would be great to buy as much as first order was. If options is not set standard 2x strategy will be used. If option is set in absolute numbers each DCA trigger will buy this amount of coins, if option is set in percents DCA will buy % from balance

**Comment by taniman** [comment]
current DCA will buy same amount of coins you own. 
also we are already working on the option to buy a set %. 
We will not create an option to buy set amount.

**Comment by jokaorgua** [comment]
Do you have eta for the “set % option” ?

**Comment by taniman** [comment]
PT 2.0 private beta testing starting in a few days. public release after confirmation of stability
