### ISSUE TITLE
Feature request: Allow copy and/or export of the monitor data & single export of all logs in one file

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer#1408]
It would be very useful to have the ability to export the monitor data. Being able to capture and export the BAL, TCV, TPV Trends, profits, pairs log, DCA log, Pending log, and sales log values displayed in the monitor would allow those of us a great tool for tracking our daily/weekly/monthly sales and profits... It would be very useful. It does not necessarily have to be "log" information per-se, even a capture of thos values in an excel file would prove very useful.

Alternatively/additionally... Would it be possible to export all the log data in one file, instead of having separate Possible Buy Log, Pairs Log, DCA Log,Pending Log, Sales Log, and Dust Log, excel files? This would allow us to build a single spreadsheet to format the single file data and build a nice reporting spreadsheet. Perhaps this data file could have the then current monitor values as well?

It would just be much easier to manage if these logs were all output in a single file.

**Comment by taniman** [comment]
/monitoring/data can help you achieve this I presume.

We will make some api endpoints that can use a token and you can make calls to get some data. Thats for 2.0
