### ISSUE TITLE
Feature request: User defined trading fees

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer#1410]
Instead of PT using .2% as the default value for trading fees, it would be nice if the user could input their "actual" trading fee rate based on their exchange, or none at all to determine their "true" profits and percentage gains. There are a couple of compound problems using the default per-defined rate of .2%

First, the monitoring data, never matches what is on the exchange (unless someone actually has a .2% trading fee) - For example, on Binance the fee it .1%, and if you use BNB to pay the fees it is only .05%... This causes false profit reporting on the monitor.

Second, there becomes a reporting discrepancy in the excel file export, as the sold price never matches the exchange because the default fee is deducted from the sell price (I have built a spreadsheet that factors back in the .2% to get a true base, then deducts my "actual" trading fees.

**Comment by taniman** [comment]
binance is .1 on the buy and .1 on the sell
thats .2

thats what we use for binance. I dont see a need to make this flexible. You can factor in the fee if youd like. 

Next thing you know people will start sayi g the bot fee calculation is wrong.

So flexibility is good. But some things we dont touch
