### ISSUE TITLE
Monitor Sales Log difference displays incorrect Sold Value and Difference Values...

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer#1411]
There seems to be an issue where the monitor "Sales Log" difference is inaccurate. Instead of a PT calculated .4% total variance, the actual variance is 20% - Somewhere the .2% (.002 actual) value is being calculated as a straight .2 (resulting in 20%) - If I take the Sales Log differential value and multiply that by 1.2, I get the correct profit value (sans fees)

It would be nice if PT would show us our "actual" profit based on our actual exchange fees (I have posted a feature request regarding this) - However, even in its current form, the math seems wrong.

**Comment by taniman** [comment]
A picture speaks 1000 words. Also the proof is in the pudding

**Comment by TheBigShort111** [comment]
Actually I need to offer an apology with a clarification here...

I see now that if you add in the .2% to the Sold Values in the sales log, then the math is correct. The reason this caught my attention in the first place is that the excel dump Sold Values never matched the sell orders on the exchange... So for my spreadsheet, the only way I can get the numbers to match is to add back in the trading fee, the deduct my actual trading fee (which is .05%) - Ironically, in figuring out where the discrepancy was, I first looked at the monitor screen and noticed that the value for "difference" was different than what I was seeing in my spreadsheet... But now I see that if I take the Sold Value total and multiply it by the .2% trading fee that PT uses, then subtract the bought cost, that the math is correct.

So, please accept my apology for questioning it. Although in my case I was seeing a discrepancy, the discrepancy was due to the differential between my actual trading fees, and the default PT fee.

**Comment by taniman** [comment]
No worries. All is forgiven

You can also close your own tickets if they are created by mistake. save me from doing it :D
