### ISSUE TITLE
Feature Request: Show "Total Profit" on monitor page

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer#1412]
While I understand that PT was never meant for long term reporting, many users (myself included) have set PT to keep more than one week of log history. That said, it would be nice if the "Profit Last Week" (LW) statistic on the monitor page could be changed to show the "Total Profit" for the entire period as set by the "trading.logHistory = " in the application.properties file.

**Comment by taniman** [comment]
Like u said. Not intended for long term reporting. So this wot be changed.

We might have some other plans cooking
