### ISSUE TITLE
Web Interface - Change from 'Estimated USD Value' to 'Estimated GBP Value'

### ISSUE THREAD

**Issue by NielUK** [taniman/profit-trailer#1413]
Hi Team,

It will be nice if the default Web Interface setting of displaying everything in USD can be changed to display in GBP (Great British Pounds / British Pounds Sterling) or for that matter any set number of currencies. (I live in the UK and would really like to see it in GBP) 

This account for all of the Web Interface dashboard tiles and all the related  pages from 'Posable buy log' to 'Dust Log'

Thanks.

Niel.

**Comment by taniman** [comment]
already in the works for PT 2.0

**Comment by NielUK** [comment]
Thanks, Taniman, looking forward to Version 2. When can we expect the new PT 2.0?
