### ISSUE TITLE
.23 Bug PT wants to buy even if already more than max trading pairs is reached

### ISSUE THREAD

**Issue by mayday79** [taniman/profit-trailer#1414]
Hi all,

i just updated from .20 to .23 and than started the Website. 

It shows me that there are currently 9 Pairs in the possible buy log. I have set the 

ALL_max_trading_pairs = 7 

and already have 8 pairs in DCA. So I don't understand why there are coins in the possible buy log.

So I stopped .23 immediately until this is checked. Will go back to .20 as long as this bug exists.

![pt23-1](https://user-images.githubusercontent.com/8648400/37247924-6285a8ce-24c4-11e8-85ba-6fcea0cbc81b.PNG)
![pt23-2](https://user-images.githubusercontent.com/8648400/37247925-629e965e-24c4-11e8-8aab-d0bc189d4d7f.PNG)

**Comment by ingeniumdesign** [comment]
the same here

**Comment by Draztik99** [comment]
having the same problem

**Comment by Peet911** [comment]
That is the change of the GUI........ it also shows in buy strat that your MAX PAIRS is reached. so no error... it wont buy

**Comment by taniman** [comment]
As @Peet911  already said. That is the new feature. We always shows the coins. Just check the buy_strategy field. 
It says, MAX PAIRS

meaning max pairs has been reached so it won't buy.
