### ISSUE TITLE
[Milestone 2 FEATURE] Inverse DCA - Laddered trailing sell retracement allowances

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer#1417]
Woud be great to be able to increase the amount by which we allow a pair's price to drop by, based on how high it has already gone, thus increasing the rope, the higher it rises.

Example:
trailing_sell_trigger = true

trailing_sell_value_1 = 2
trailing_profit_1 = -1

trailing_sell_value_2 = 4
trailing_profit_2 = -2.5

trailing_sell_value_3 = 6
trailing_profit_3 = -3

trailing_sell_value_4 = 10
trailing_profit_4 = -4

Applicable to PAIRS and DCA selling.

**Comment by TheBigShort111** [comment]
@omarmoss 
If you use feeder, you can do something similar by setting different DCA conditions based on the current market trend. So the DCA sell value can change dynamically.

For example, you can let feeder increase the DCA sell value as the condition goes from bear, to sideways (boring), to bull, etc... Or you can decrease the sell value under bearish conditions.

The feature works great.

**Comment by omarmoss** [comment]
@TheBigShort111 That's great, but I would like manual control on a per-pair basis.
Different cryptos are more or less volatile, so I would appreciate being able to let a turn of events ride without risking a large trail, that might otherwise return to negative value all because I'm being 'greedy' by default.

Better to make the trailing sell elastic, as per one's own pair or DCA setting.

Although BTC swings affect the overall market, each coin's trading patterns are unique and therefore globally adjusting the sell trail (as it seems you are suggesting Feeder does), does not provide the same level of control I am describing. I'm sure it helps, but it's not the same thing.

**Comment by TheBigShort111** [comment]
You can set DCA conditions per coin/per market trend/condition with feeder

**Comment by omarmoss** [comment]
Nice!
Let's make that a default feature of Profit Trailer! : D

**Comment by taniman** [comment]
I think this feature has been asked on the profittrailer-enhancement project. Better vote on it there.
Cause as it stands now, this is not something that will make it on a milestone otherwise
