### ISSUE TITLE
Manual actions on exchange take a long time to appear in PT

### ISSUE THREAD

**Issue by orangebutblue** [taniman/profit-trailer#1419]
(I only use Binance, so this might not be a problem on the other exchanges)

Basically, if you place a manual buy-order, it takes several minutes (~10 minutes) to show up in the pending-log. Similarly, if you buy a coin manually, it also takes several minutes to properly be listed in the pairs-log.

I realize that PT doesn't check for new coins or new pending orders very often (because normally there is usually no need to do so).
But this is a problem for me, because I'm trying to automate the buy-process myself, and let PT only handle the selling. To be able to do that properly, PT has to poll for new coins more frequently, or ideally have a mechanism to force polling (maybe a "refresh" button on the web-app, and a way to trigger it programmatically via command line (curl) ) .

**Comment by Wolfwood1** [comment]
I was also wondering about that, could we tune the frequency of the heartbeats?

**Comment by taniman** [comment]
No we cannot and will not. The bot does this in order to not spam the exchange. Manual actions should be avoided

**Comment by taniman** [comment]
We will introduce manual buy buttons soon enough. But for now this is what we offer. as we could have also disabled it completely too

**Comment by orangebutblue** [comment]
If this is already planned for a future version, I'm happy.
Thanks for considering it.

**Comment by YoJeff** [comment]
Some food for thought.

- It's also rude to crap on other peoples threads.
- This is not a bigger corporation.
- I've seen way, way worse in some bots.
- Who says this is only 1 man.
- I actually prefer straight to the point -vs- namby pamby corporate bullshit-speak.

Always two sides to a coin ;)
