### ISSUE TITLE
PT doesn't buy

### ISSUE THREAD

**Issue by khayalahmadzada** [taniman/profit-trailer#1422]
ARKET = ETH

ALL_trading_enabled = true
ALL_enabled_pairs = OMGETH, IOTAETH, BLZETH, POAETH, NANOETH, ARKETH, GTOETH, ELFETH, BRDETH, WABIETH, ICXETH, VENETH, TRXETH, ZILETH, RCNETH, KNCETH, LINKETH, QSPETH, POWRETH, WAVESETH, NEOETH

ALL_max_cost = 0

ALL_max_cost_percentage = 2

ALL_min_buy_volume = 0

ALL_min_buy_balance = 0.0

ALL_max_trading_pairs = 50

ALL_min_buy_price = 0

ALL_panic_sell_enabled = false
ALL_sell_only_mode = false

ALL_buy_strategy = EMAGAIN
ALL_buy_value = -0.39
ALL_trailing_buy = 0.153

ALL_sell_strategy = GAIN
ALL_sell_value = 0.39
ALL_trailing_profit = 0.297

ALL_DCA_enabled = false

**Comment by orangebutblue** [comment]
what does the possible-buy log say? if it's empty, then your settings exclude all the coins from being considered 

if it's not empty... 
what does it the console log say?

**Comment by taniman** [comment]
I would advice you to contact support. This is clearly a setup problem and not a bug.

**Comment by khayalahmadzada** [comment]
Once I set the trailing buy to zero when it was in the trailing zone and the bot bought immediately (NANOETH). But even then it made only 1 (small) trade order, even though it sold 13 ETH worth of my NANO earlier via more than 15 sell orders, when it was in the GAIN zone.
