### ISSUE TITLE
Bought but not moved to Pairs log

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1424]
PT has bought neo - I see it on binance balance. But the pair is still in possible buy log. it was not moved anywhere from possible buy log

0|ProfitTr | 2018-03-11 21:05 +01:00: 2018-03-11 21:05:12 INFO ProfitTrailerService - Buy order for NEOUSDT -- {"symbol":"NEOUSDT","orderId":18837720,"clientOrderId":"QTuiJK6q34ZrkJS2Ai7Ngy","transactTime":1520798712808,"price":"90.16000000","origQty":"0.11100000","executedQty":"0.11100000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|ProfitTr | 2018-03-11 21:05 +01:00: 2018-03-11 21:05:18 INFO ProfitTrailerService - Get order information -- {"symbol":"NEOUSDT","orderId":18837720,"clientOrderId":"QTuiJK6q34ZrkJS2Ai7Ngy","price":90.16000000,"origQty":0.11100000,"executedQty":0.11100000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1520798712808}
0|ProfitTr | 2018-03-11 21:05 +01:00: 2018-03-11 21:05:18 INFO NormalStrategyRunner - Normal Pair - EMAGAIN bought -- currency pair NEOUSDT - BV -0.2, BVL 0.0, MTP 1, TTP 1
0|ProfitTr | 2018-03-11 21:05 +01:00: 2018-03-11 21:05:18 INFO NormalStrategyRunner - BUYLOG: {"BBLow":0.0,"BBTrigger":0.0,"positive":"true trailing...","BBHigh":0.0,"currentValue":-0.7283832409408109,"market":"NEOUSDT","profit":0.0,"currentPrice":90.16,"buyStrategy":"EMAGAIN","volume":3.0721143034436E7,"triggerValue":-1.1224949769155557,"percChange":0.02396}
0|ProfitTr | 2018-03-11 21:05 +01:00: 2018-03-11 21:05:25 INFO DCAStrategyRunner - API Problems?
0|ProfitTr | 2018-03-11 21:05 +01:00: 2018-03-11 21:05:25 INFO NormalStrategyRunner - API Problems?

0|ProfitTr | 2018-03-11 21:08 +01:00: 2018-03-11 21:08:41 INFO ProfitTrailerService - Cache Heartbeat
0|ProfitTr | 2018-03-11 21:08 +01:00: 2018-03-11 21:08:55 INFO ProfitTrailerService - DCA Heartbeat
0|ProfitTr | 2018-03-11 21:08:55 INFO ProfitTrailerService - Normal Heartbeat

PT 1.2.6.23. Linux Ubuntu 16.04

**Comment by jokaorgua** [comment]
after pm2 restart ProfitTrailerBot the coin was moved to pairs log.

**Comment by jokaorgua** [comment]
restarted bot and it lost bought pair from pairs log

**Comment by jokaorgua** [comment]
stopped the bot for a night. started it in the morning and deal is again in pairs log. this is unacceptable when the deal is jumping from log to log

**Comment by taniman** [comment]
please contact support as it seems you have a configuration error. There is no user experiencing this.

What I suspect is that you are using multiple apikeys pointing to different binance accounts. 
Or you have something else interfering.

In any case it is not a bug. So ask support
