### ISSUE TITLE
Need more logs in console for API problems

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1425]
0|ProfitTr | 2018-03-11 21:24 +01:00: 2018-03-11 21:24:17 INFO NormalStrategyRunner - API Problems?

Which problems ? Api is ok. Please add some debug info which errors api has from market

Market: binance
PT: 1.2.6.23
OS: Linux Ubuntu

**Comment by taniman** [comment]
There is nothing to add. that's a complimentary message. You most likely changed something wich caused a discrepancy between the amount of pairs we last saw and the amount of pair the exchange is telling us you own. 

So there is no actual error happening that we can display. This is a protection mechanism

**Comment by jokaorgua** [comment]
I’ve changed nothing. I wanted you to add to logs real error message from the market
