### ISSUE TITLE
[Feature Request] Getting ANDERSON's multiple buy trigger for other buy strat for DCA (like EMASPREAD)

### ISSUE THREAD

**Issue by Cryptoqueb** [taniman/profit-trailer#1426]
I'm using EMASPREAD has a DCA buy strat so i'm not blindly buying when my pair drops but rather buying at a low. My problem though is that the fix trigger buy is limiting my range to which I can get out of a bad bag. 

I'd like to have the same option to set multiple buy triggers for other DCA buy strat like the ANDERSON's strat has. So for EMASPREAD it would consider buying only it the trigger is met for the specific DCA levels it's at. That would be so great. 

thx

**Comment by YoJeff** [comment]
Check for duplicates and submit to features github.
https://github.com/taniman/profit-trailer-enhancements/issues
