### ISSUE TITLE
Why did STPOPLOSS work at -25% instead of -4% specified in the settings

### ISSUE THREAD

**Issue by Mixand1984** [taniman/profit-trailer#1427]
Hi guys, I really need your help.I  bought and installed bot. Everything worked for 3 days, the bot received a profit. Then something happened and STOP LOSS stopped working. The strategy was simple: to buy by EMA if the price falls below -1.5% - turn on DCA (Andersson (without doubling, simple purchase)). The last purchase is carried out at a price of -3.5%. In case of continuing the fall, I set STOP LOSS to -4%. The problem is that STOP LOSS worked at -4% .- 12% and -25%. I suffered heavy losses. The LOG file shows that one minute before the sale there was an error of the exchange by API KEY (nl.komtek.pt.utils.b: APIKEY_INVALID).

Why did STPOPLOSS work at -25% instead of -4% specified in the settings
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1801601/ProfitTrailer.log)
![pairs_1](https://user-images.githubusercontent.com/37286301/37268664-d579e6d6-25e8-11e8-9f4c-c9ea85620a5d.png)
![pairs_2](https://user-images.githubusercontent.com/37286301/37268665-d59c7124-25e8-11e8-8e81-952d20e1b60a.png)
![dca](https://user-images.githubusercontent.com/37286301/37268666-d5bcf214-25e8-11e8-982f-cf8beef64bc1.png)
![2018-03-11 23 58 46](https://user-images.githubusercontent.com/37286301/37268667-d5ddcdf4-25e8-11e8-996e-da7f3ec2071e.png)
![2018-03-11 23 58 39](https://user-images.githubusercontent.com/37286301/37268668-d5ff73f0-25e8-11e8-8997-4123481aee73.png)
![2018-03-11 23 58 26](https://user-images.githubusercontent.com/37286301/37268669-d620ccbc-25e8-11e8-8139-2951228984c2.png)

?

How to fix this BUG?

If you can not fix this error, it turns out that the bot trades at a loss!
I really need help

**Comment by YoJeff** [comment]
Most of those are in the 4% range, the market still moves.   Make sure you are on the latest version.

**Comment by taniman** [comment]
Please read the wiki and tell me where you went wrong with your stoploss setup

![image](https://user-images.githubusercontent.com/6751341/37294718-c48b1ccc-2616-11e8-896a-f47b703cff8f.png)

**Comment by Mixand1984** [comment]
So what do I need to do? Tell me please. To make it work right away

**Comment by taniman** [comment]
I would have expected you to at least try to understand how the settings work, after saying that the bot is selling at loss..

You need to set a correct max_buy_times and a correct max_cost
In your case max_buy_time should be set at 2 as you are only using 2 anderson triggers

and your max_cost is current 0.8 BTC
max_cost is per coin. So please set it to something lower. or are you buying so big amounts?

**Comment by Mixand1984** [comment]
max_cost = 0.003
max_buy_times = 1
#--------------------------------------------------------------#
#BUY SETTINGS #
# DCA MEAN DOLLAR COST AVERAGING THIS STRATAGY BUYS MORE COINS #IF THE INTIAL BUY PRICE DUMPS A CERtAN PERCANTAGE TO BRING UP #THE AVERAGE LOSS OF THE COIN MEAKIN IT EASIER FOR IT TO REVOCER #AND MAKE A PROFIT
buy_strategy = ANDERSON
buy_trigger_1 = -2
#THIS TELLS THE BOT TO WAIT TIll IT FALLS ANOTHER .10 in Value #Before it buys protecting you from further drops in value #before buying.
trailing_buy = 0.1
pending_order_wait_time = 0
ignore_sell_only_mode = true
#--------------------------------------------------------------#
sell_strategy = GAIN
sell_value = 1
trailing_profit = 0.1
#--------------------------------------------------------------#
#SAFTEY SETTINGS#
# max spread % between lowest ask and highest bid  to allow a new buy order
# if spread is too big, most likely there was a coin dump/pump and you are buying too high
max_buy_spread = 1
ALL_stop_loss_trigger = -3

**Comment by Mixand1984** [comment]
![2018-03-14 9 42 51](https://user-images.githubusercontent.com/37286301/37384464-e913fab8-2770-11e8-89d5-7910bc38176b.jpg)

**Comment by Mixand1984** [comment]
max_cost = 0.003
max_buy_times = 1
#--------------------------------------------------------------#
#BUY SETTINGS #
buy_strategy = ANDERSON
buy_trigger_1 = -2
#THIS TELLS THE BOT TO WAIT TIll IT FALLS ANOTHER .10 in Value #Before it buys protecting you from further drops in value #before buying.
trailing_buy = 0.1
pending_order_wait_time = 0
ignore_sell_only_mode = true
#--------------------------------------------------------------#
sell_strategy = GAIN
sell_value = 1
trailing_profit = 0.1
#--------------------------------------------------------------#
#SAFTEY SETTINGS#
max_buy_spread = 1

ALL_stop_loss_trigger = -3

**Comment by Mixand1984** [comment]
Taniman thank you very much for your help and for your time. I did as you wrote, but STOPLOSS does not work correctly. Friends please tell me how you can contact the bot developers and tell them about this error. I'm upset.

**Comment by taniman** [comment]
No, you did not do as I told you. I told you how to fix the problem in the screenshots yuo showed me. 

But you went and changed the DCA.properties file to somethign that does not work. 

ALL_stop_loss_trigger = -3

You can but ALL_ items in DCA. 

stop_loss_trigger = -3

That's how it works

In the first screenshtos you had it correctly so I do not know why you changed it....
