### ISSUE TITLE
Rebuy Time Out Issue

### ISSUE THREAD

**Issue by BitcoinKing1979** [taniman/profit-trailer#1429]
I have the function set on my Pair properties : ALL_Rebuy_Timeout = 10
As described on the Wiki , the bot should not buy the same pair after 10 min
The problem are : 
 - The Pair stay On Rebuy time out status even after 10 min once sold
- Once the bot buy a pair , it goes immediatly on Rebuy Time Out status, normaly should not since is not yet sold

![1](https://user-images.githubusercontent.com/37298004/37285281-e2319cd2-25fe-11e8-980a-6d36e71d9cff.png)
![2](https://user-images.githubusercontent.com/37298004/37285282-e2548d8c-25fe-11e8-8769-0a0717c05fb9.png)

Thx to take a look

BR

**Comment by Tosko4** [comment]
I have the same issue. I have to restart PT in order to get rid of the REBUY TIMEOUT message. But it’s quite annoying to keep restarting all the time.

**Comment by taniman** [comment]
send me your trading folder to test

**Comment by B0mBeur** [comment]
I got the same problem. I had to restart the bot to get it going again.

**Comment by Tosko4** [comment]
@taniman to where can I send the email to? Don’t feel comfortable uploading it here

**Comment by BitcoinKing1979** [comment]
Which email we can send ?

**Comment by taniman** [comment]
Your trading folder has only yuor trading settings nothing sensitive.
but if you don't feel it. give it to support on discord. Or create a support ticket on
https://support.profittrailer.com

**Comment by Tosko4** [comment]
@taniman nevermind, the support ticket module does not allow to attach .properties files or .zip files...
So here you go..

[Archive.zip](https://github.com/taniman/profit-trailer/files/1805770/Archive.zip)

**Comment by Tosko4** [comment]
Update: it still happens.. even after updating to latest .24

![screenshot 2018-03-13 at 08 11 53](https://user-images.githubusercontent.com/1294707/37327354-4497c8c8-2696-11e8-8ec6-ede3b272e0de.png)
![screenshot 2018-03-13 at 08 11 22](https://user-images.githubusercontent.com/1294707/37327364-4bbf9518-2696-11e8-9458-90ae1b9da478.png)


As you can see in the second screenshot sold at 07.59, still now at 8:13 rebuy timeout still there.

While my rebuy is set to 5 minutes

![screenshot 2018-03-13 at 08 13 35](https://user-images.githubusercontent.com/1294707/37327411-741b8774-2696-11e8-8a98-d93037552870.png)

**Comment by SgtBatten** [comment]
When it happens have you looked at the monitor in another browser or from another computer? Just curious if it displays correctly on a different browser that has not cached the rebuy timeout

**Comment by Tosko4** [comment]
@SgtBatten yes, I used my laptop, my mobile phone and different browsers even. Cleared history and cookies even

**Comment by SgtBatten** [comment]
Okay thanks.

**Comment by taniman** [comment]
@Tosko4 I put an announcement saying why .24 was released. So no. I have not fixed this yet. Else I would have closed it. 

No that I have your data I can start investigation soon

**Comment by oiler2112** [comment]
Just for the record, having same issue here. Once the RebuyTimeout is enabled for a coin, it sticks and a restart of PTF seems to be the only way to reset the issue.

**Comment by Tosko4** [comment]
@taniman thank you for clarifying and hope you can fix this soon! Makes me feel safer when I can enable this line again
