### ISSUE TITLE
Wrong Values for "total value", "bought price" and  "profit" in the pairs log

### ISSUE THREAD

**Issue by visualm** [taniman/profit-trailer#1431]
Hi, PT displays the WRONG VALUES for "total value", "bought price" and  "profit" in the pairs log. Because its has the wrong value for profit, the whole sells strategy is messed up. 
This happens after the first ETHBTC buy as well as after the first XRPBTC buy. No previous ETH or XRP owned on BINANCE, so the bot shouldn't get it wrong. The issue persists after restarting the bot and Windows and after changing the trading API key. (Discrepancy is about 7%, between the ETH on BINANCE vs what PT shows). I had to shut the bot down to prevent any trade decision based on false data. 
Any Ideas?

**Comment by taniman** [comment]
Screenshot?
Your current version
and your log file

Whould be a great start

**Comment by visualm** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1804495/ProfitTrailer.log)

![pt all](https://user-images.githubusercontent.com/37308749/37309469-f0375d5a-2638-11e8-9c3d-0691f98a4f3b.jpg)

Even after taking into account the 0.1% trading fee, there is a 7% discrepancy in the amount of ETH that isdisplayed by the PT vs BINANCE. Hence the wrong profit calculated by PT. 
The bot states 0.01400 ETH, BINANCE states 0.01485 ETH (incl fees).

My system: 
- Home PC, Windows 10 (up to date with all updates)
- Firewall disabled (otherwise, PT wouldn't run)
- PT verison 1.2.6.23 (the buy trade was excuted with version 1.2.6.22)

**Comment by visualm** [comment]
Thats the log file, from the previous PT version, when the trade was done:

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1804620/ProfitTrailer.log)

**Comment by visualm** [comment]
Ok thanks, I have reset the price. Will test again once I find time to monitor the bot...
