### ISSUE TITLE
Stop Loss Offsets

### ISSUE THREAD

**Issue by mnanut** [taniman/profit-trailer#1432]
Can we have a stop loss offset if it is not yet implemented?  I am using stop loss, and would like to have this offset based on market conditions, and coin change for profit feeder addon.  Profit Trailer needs to have this option in order for the devs of profit trailer feeder to implement it.

Thanks in advance!

**Comment by taniman** [comment]
I am not sure you are aware that we are 2 seperate products and have no affiliation.

We are not in the business of building things to make 3rd party products life easier.

**Comment by mnanut** [comment]
Yes I am aware.  And I'm sure this would be useful for PT.  Each pair has different volatilities, so offsetting stop losses would be very beneficial.  Less volatile pairs could have higher stop losses to minimize loss.  More volatile pairs could have lower stop losses to give the pair some wiggle room before selling at a loss.  Can this be implemented?

**Comment by mnanut** [comment]
Taniman, please consider this or leave this feature request open at least for other to discuss.

I'm tired of getting deep bags, so I only use stop loss now, and being able to set up different stop losses for each coin would really be helpful.
