### ISSUE TITLE
PT creating fixed sell prices

### ISSUE THREAD

**Issue by mikeyshann** [taniman/profit-trailer#1433]
My bot just started creating Fixed sell orders on binance and they are now in the pending log. I thought that it would just trail the trend. I’ve never seen it do this before. I am also running profit feeder with it. I haven’t changed any settings in a long time but it’s suddenly been doing this for 2 days. Any reason why?

**Comment by taniman** [comment]
yes. this is a default setting that profit feeder turns on.

all pending order wait time.

please ask support these type of questions as this place is for bugs
