### ISSUE TITLE
Sometimes it bugs out with API

### ISSUE THREAD

**Issue by Tosko4** [taniman/profit-trailer#1434]
Hi there,

Since the last update (.24) My bot started to act weird. Replaced the .jar file with the one in the zip and my bot sent me a telegram message that is this happens 3 times in a row I should restart my bot. Well, it happened 4 times.

So I did restart and it seems to work 'for now', but maybe you guys want to have a look at this?

![screenshot 2018-03-13 at 07 56 15](https://user-images.githubusercontent.com/1294707/37326866-4dacf2d2-2694-11e8-8585-97ea023468c7.png)

**Comment by Tosko4** [comment]
It happened again. Can you guys please have a look?

**Comment by taniman** [comment]
can you send a screenshot of the telegram messages?

**Comment by Tosko4** [comment]
![dce67495-a172-4d29-b6cb-098c11629119](https://user-images.githubusercontent.com/1294707/37437053-67a9a2c2-27eb-11e8-8707-29133496ffdc.jpeg)
![779cbb4b-07cd-436f-a6b4-18775a7e32be](https://user-images.githubusercontent.com/1294707/37437054-67c53cee-27eb-11e8-9787-38a5fae1a3fc.jpeg)

This seem to have happened after I updated to .24 never seen these messages before. Now I am restarting daily

**Comment by taniman** [comment]
especially with all that corrupt data in your log.

**Comment by Tosko4** [comment]
It happened this morning (GMT+1). Havent had it the past 13 hours. But you also mentioned corrupt data in my logs. Do you want me to do something else to test more succesful?

**Comment by Tosko4** [comment]
And I believe you when you say you haven’t. I am just stating what I observe, could be helpfull in some way. Just trying to help taniman

**Comment by taniman** [comment]
If you can send me your log file. I can see if the errors in the log match when you get the notifications. Also can you send a screenshot of this mornings errors . tnx

**Comment by aceangel3k** [comment]
I have this issue as well. I've attached my log. I downgraded to .20 just now.
[ProfitTrailer.log.zip](https://github.com/taniman/profit-trailer/files/1817542/ProfitTrailer.log.zip)

**Comment by aceangel3k** [comment]
It happens for me on .20 as well. I had to restart the bot.
![screen shot 2018-03-15 at 8 51 38 pm](https://user-images.githubusercontent.com/1007695/37502924-c8ba57f8-2892-11e8-8085-75625dc08328.png)

**Comment by taniman** [comment]
@aceangel3k  I am just seeing a lot of error in your log file. This will 100% cause the issue. 

If we get so many errors while receiving ticker data from the exchange than we won't get updated data. 
So no wonder you get the message
