### ISSUE TITLE
Dashboard link...

### ISSUE THREAD

**Issue by Steve1564** [taniman/profit-trailer#1435]
The Active single settings link (i) links to Market Trends - not Market Analyzer...

No Biggie,

Steve

**Comment by taniman** [comment]
What are you talking about? Please clarify

**Comment by Steve1564** [comment]
The Info Link on the dashboard - the little i next to the number of "Active Single Settings" should when clicked open the market analyser page - it dont, it opens the now defunct "Market Trends" page....

Like i said - no biggie, just thought you should know

Steve

**Comment by Steve1564** [comment]
![image](https://user-images.githubusercontent.com/35610015/37351303-a8be2fd6-26d2-11e8-92ce-1a817d420aff.png)

**Comment by YoJeff** [comment]
This aint PTMagic.

**Comment by Steve1564** [comment]
Ahhh... My bad!!! - Ok having a senior moment
Dude I am so sorry - and i feel so stupid.....

In that case your software is working fine - Just another ID-10-t error!


Thanks 

Steve

(steve the old grey donkey wanderded up to the bend in the river, he stopped & looked at his reflection, pathetic he said, thats what it is pathetic)
" from steve the pooh - Chapter 6"
