### ISSUE TITLE
Feature request: sell button on DCA/Pairs

### ISSUE THREAD

**Issue by JaySNL** [taniman/profit-trailer#1437]
A simple sell button to push a sell through PT w/ the API to your exchange, so it still counts the profit and/or loss. I.e: [ SELL DCA ] or [ SELL PAIR ] with a pop-up box w/ text confirmation "type out SELL PAIR" and press enter to confirm.

This way sells, maybe for a higher or lower percentage - or even a loss - will still be tracked in PT.

**Comment by YoJeff** [comment]
Already one of the top requested items on the feature github.
