### ISSUE TITLE
[Feature Request] Display Market Condition

### ISSUE THREAD

**Issue by oiler2112** [taniman/profit-trailer#1439]
Would it be possible to add the current market conditions folder name, i.e. bear, bull, whatever we are naming them, on the screen? I am on Binance, so possibly where it shows the market, something like:

Market: Binance ETH (Bull)

This way we can see at a quick glance what market condition the bot is in.

**Comment by Tosko4** [comment]
PT (if i am correct) does not have different market conditions. Its your PAIRS DCA and INDICATORS file. The market settings are those from PT Feeder / Magic. They cannot interact really, or PT would have to build compatibility with an add-on, which i do not think it will happen.

**Comment by YoJeff** [comment]
This aint feeder.  PT has no concept of bull/bear/whatever.
