### ISSUE TITLE
[NEW FEATURE REQUEST] End Trailing % (Sell Instant %)

### ISSUE THREAD

**Issue by jake501** [taniman/profit-trailer#1440]
Like the title implies, I'm proposing a simple setting that will allow coins to stop trailing and instantly buy/sell whatever is in the order book at a certain percentage to utilize pumps, maybe even dumps. 

Trailing Profit = 1%
InstantSell = 15%

![image](https://user-images.githubusercontent.com/34288768/37365314-83b59282-26d3-11e8-8c1a-e933019a6723.png)

I'm sure everyone has seen coins pump up and PT tries to trail, but by the time they come back down the trailing % (say this case 1%) in reality, the pump is over and it comes back to the normal range (usually 15%+) so you end up selling at maybe 1-2% profit rather than 15%+. 

This setting would then allow PT to see the profit above 15% and sell (much like panic selling) and since PT only looks at what is available in the BUY order books, not the price for the profit %, it would be easy enough to sell into the pump.

Hope that makes as much sense in writing as it does in my head!

-Jake

**Comment by Tosko4** [comment]
Yeah!!

**Comment by mightysoul** [comment]
+1 would be really good feature

**Comment by YoJeff** [comment]
Search for duplicates first, then submit to features github.
https://github.com/taniman/profit-trailer-enhancements
