### ISSUE TITLE
Selling based on a different buying price!

### ISSUE THREAD

**Issue by Nasser74** [taniman/profit-trailer#1443]
Hi,

I am new to PT, it has been working fine but today I bought a coin manually (which i had dust for) and wanted PT to sell it; however, PT sold it based on the price the dust was bought in (which was lower than the price I manually bought in the coin), so PT sold the coin immediately taking the dust price as its base price and resulted in a loose where PT thinking its a profit.

**Comment by YoJeff** [comment]
You need to provide details.   Screenshots, logs, exchange info, etc.

**Comment by taniman** [comment]
Well we don't advise buying coins manually. But like yojeff says. where are the screenshots

**Comment by Nasser74** [comment]
@YoJeff , @taniman  , I did some investigation and the bot did not sell based on dust price but it definitely sold based on other price than the bought price. 

I am running my bot on binance, I bought EOS token manually for 0.008503 ETH (screenshot below from binance history)

![image](https://user-images.githubusercontent.com/11880900/37436888-7dca17e2-27a7-11e8-9d22-263ccb5f498b.png)

Few minutes later, the bot sold EOS with a loss as you can see in binance screenshot, but in the bot window it is showing that it sold them for a profit, taking a different price as the base price. Please advise if I am doing something wrong.

![image](https://user-images.githubusercontent.com/11880900/37436976-e0dd101e-27a7-11e8-8c46-e6684814aa21.png)

Thanks for your support!

**Comment by taniman** [comment]
I recommend you update to the latest version as we do not supprot the old version anymore. If the problem happens again you can create a new issue.

I also do once again want to remind you that we do not recommend doing manual buys
