### ISSUE TITLE
Feature Request, save multiple trading profiles

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer#1444]
New Feature Request

Allow the user to "save as" from the config screens to save all settings to a _strategy_

In addition allow the user to "load" a previously save _strategy_

This would allow users to easily save and load a different trading profile for BULL, BEAR, SUPERBEAR markets etc.

**Comment by YoJeff** [comment]
Search for duplicates first, then submit to features github.
https://github.com/taniman/profit-trailer-enhancements
