### ISSUE TITLE
SOM is triggered only after I enter monitoring page

### ISSUE THREAD

**Issue by emx0r** [taniman/profit-trailer#1446]
Since last few versions back I've noticed a problem when the SOM triggered by BTC price move stays either enabled or disabled ignoring all thresholds. As soon as I enter monitoring page I get notification to Telegram and SOM is immediately activated or deactivated.

I'm currently on 1.2.6.24

**Comment by SgtBatten** [comment]
This is expected behaviour. It wont send SOM enabled or disabled notifications unless 1. you open the GUI or 2. the bot tries to make a buy and the triggers are checked at that time. It works how it should, the notifications just aren't sent immediately unless the bot is trying to buy

**Comment by emx0r** [comment]
ok, thanks for explanation. It was just confusing as before it was working differently
