### ISSUE TITLE
POSITIVE EMA SPREAD NOT WORKING.

### ISSUE THREAD

**Issue by aknet86** [taniman/profit-trailer#1448]
positive emaspread values are recognized as negative. if i swap EMA1 and EMA 2 values bot works correct with postive values..

![1](https://user-images.githubusercontent.com/37427671/37500442-e7e31cd4-289f-11e8-90b6-276fb1a6abae.JPG)
![2](https://user-images.githubusercontent.com/37427671/37500475-16f75648-28a0-11e8-8709-5c61f4d52e22.JPG)

**Comment by taniman** [comment]
There is nothing wrong with the emaspread functionality.  You should define the values like
ema 1 = 24
ema 2 = 3

Positive values are when fast line is above slow line
negative values are when fast line is below slow line.

That's how the bot works

I advise you to contact support if you need further clarifications
