### ISSUE TITLE
[request] Alternative HotConfig command to correct SalesLog

### ISSUE THREAD

**Issue by keithofaptos** [taniman/profit-trailer#1449]
Alternative HotConfig command to correct SalesLog.
I put in wrong value of missing pair. sales log value is 
WAY off now. Would be nice to make correct. :/

**Comment by taniman** [comment]
You could have changed it before it sold. Sales log are not changeable after the coin has been sold. It required too much thinkering and recalculations

**Comment by vitalizzy** [comment]
Only the parameters like: 
OMGBTC_reset_stored_average = true
OMGBTC_bought_price = 0.1234

...are available on HOTCONFIG? or any kind of PT parameter?

Thank you in advance
