### ISSUE TITLE
original buy value issue

### ISSUE THREAD

**Issue by ilivenicely** [taniman/profit-trailer#1451]
I'm trying to trade between markets, exe: bot1 buys BTC, bot2 trades btc market alt coin to ethereum market alt coin. I have to set an buy value manually. It would be great if there were some way for 2 bots to be more aware of each other in this regard (or maybe I'm missing feature). Thanks

**Comment by YoJeff** [comment]
2 bots one account is not a supported configuration, as documented in the wiki.
https://wiki.profittrailer.com/doku.php?id=faq#how_to_set_up_a_second_bot_instance
