### ISSUE TITLE
all_max_cost_percentage issue

### ISSUE THREAD

**Issue by ilivenicely** [taniman/profit-trailer#1452]
My all_max_cost_percentage seems to not allow a buy at 100% if I trade my BTCUSDT into ETH market. I was only able to receive buys at 98%.

**Comment by taniman** [comment]
Please be a little more specific. I will need some examples as to what you mean.

**Comment by taniman** [comment]
Maybe show screenshot to elaborate

**Comment by YoJeff** [comment]
This is likely just rounding, since the TCV is fluid.    Just use 98 or 99.

**Comment by ilivenicely** [comment]
I think it's because my BTC value is changing while it's in the market for another bot (BTCUSDT to ETH market bot). Another feature to clear funds after a certain percentage would be useful for this case. No screenshot because it simply didn't attempt to buy until I brought it down to 97% (it's blank).

**Comment by taniman** [comment]
You are aware how max_cost_percentage works right? The calculation is on the wiki.

max_cost_percentage = balance + totalCost of coins you own.

So 100% will indeed never work.  cause the 100% of your balance also contains the value of the coins you own.
