### ISSUE TITLE
Binanace updates times

### ISSUE THREAD

**Issue by Rswtrader1** [taniman/profit-trailer#1453]
Good evening taniman,

I am utilizing Binance for trading and find that as I work between the PT and binance, there are timing dependencies with the bought and sold pairs not showing up on PT immediately, but they do on binanace immediately. What could be my issue?

Thank you for all of your good work on here!

**Comment by taniman** [comment]
I do not understand your question? Are you talking about anual buys and sells?

If so. The bot is a bot. Anything you buy manually on the exchange will take about 10 minutes to synchronize. You should avoid doing manual changes on the exchange while using the bot

**Comment by Rswtrader1** [comment]
Would you suggest using a separate binance account to do manual trading?

**Comment by taniman** [comment]
Yes, I would definitely suggest that. Or just be aware of how the bot reacts to manual changes. Which is, it does not do it realtime
