### ISSUE TITLE
[Feature Request] Add 24Hr% change to Possible Buy Log conditions

### ISSUE THREAD

**Issue by acasalsjahnsen** [taniman/profit-trailer#1455]
Hi,

I didn't find this on the requests so I posted it. Can you add a new condition to the Possible Buy Log settings based on the 24Hr% change of the different pairs. I find this useful to prevent buy coins which have been already pump & dump. The bot bought one pair which had a +25% day change which was on its way down and after 3 DCAs I prefered to take the loss because its price before the pump was way lower.

The setting could be something like: ALL_max_24hr%_change 

Also the minimum version could be useful as well, ALL_min_24hr%_change

Regards

**Comment by YoJeff** [comment]
There are a couple variants of this over on the features github.   Vote for the items you want to see implemented.   
https://github.com/taniman/profit-trailer-enhancements
