### ISSUE TITLE
[Feature Request] Paper Trading in Test Mode

### ISSUE THREAD

**Issue by CryptoZenMaster** [taniman/profit-trailer#1458]
Several other bots have not only a paper trading mode but full blown backtesting.

Would be great if PT could at least log when sell thresholds are hit.  Of course it cannot guarantee sells would have happened but at least it could be use to roughly tell if the chosen strategy was effective.  This would have saved me and other a lot of pain and lost funds.

**Comment by taniman** [comment]
I am going to be blunt and say as long as you are doing a comparison with other bots. 
Other bots with backtesting or 3 times as expensive or have a monthly subscription.

So sure. as soon as we start doing a monthly subscription we will add backtesting features and more
