### ISSUE TITLE
Stop Loss In DCA not working properly.

### ISSUE THREAD

**Issue by msaleh3000** [taniman/profit-trailer#1461]
The stop loss in the DCA properties is supposed to be triggered after all the DCA levels are fulfilled, but it triggered a sale before all the levels are done. I have 5 DCA levels. 
![error in dca stoploss](https://user-images.githubusercontent.com/8343562/37566508-8ce1c11c-2a90-11e8-886c-14737b1ff71b.jpg)

**Comment by taniman** [comment]
No, there are more rules for triggering a stoploss. It's in the wiki

![image](https://user-images.githubusercontent.com/6751341/37566600-be8a394e-2abb-11e8-9033-577bc49b2878.png)

**Comment by msaleh3000** [comment]
Max buy times not reached.
Max cost not reached (not set)
There was enough balance to keep going in DCA for all coins.

**Comment by taniman** [comment]
I would suggest you provide evidence of this. at least provide your log file. else this issue will be closed

**Comment by msaleh3000** [comment]
Here is my DCA settings:

max_cost = 0
max_buy_times = 5
min_buy_balance_percentage = 4

buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -1.55
buy_trigger_2 = -2.5
buy_trigger_3 = -3.5
buy_trigger_4 = -7.5
buy_trigger_5 = -10.5
trailing_buy = 0.1

sell_strategy = GAIN
sell_value = 0.6
trailing_profit = 0.05

#stop_loss_trigger = -15

buy_available_volume_trigger = 125
ignore_sell_only_mode = false
max_buy_spread = 0
min_buy_balance = 0

#pending_order_wait_time = ‪4320‬

and attached is my log file
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1822721/ProfitTrailer.log)

**Comment by taniman** [comment]
Your log file is filled with error from poloniex side. So I am sorry to say, but the stoploss triggered as a result of incorrect data received from the exchange. 

We have protection agains this, but seems not enough

**Comment by taniman** [comment]
looking at my logs too. seems like poloniex has been having issues for a few hours now.

**Comment by msaleh3000** [comment]
Thanks. Good to know it's not something I did. 
Wish the errors would appear in the notification when they happen instead of reporting normal heartbeat. 
Thank you again.

**Comment by taniman** [comment]
the errors are appearing in the log. We should indeed start displaying some of those in the notifications. Soon

**Comment by Cryptoqueb** [comment]
Are there instances where Binance had the same kind of issues? Got a Stoploss on a bag with 0 DCA (3 max), not max cost nor a balance issue yesterday.
