### ISSUE TITLE
DCA EMASPREAD not working proper?

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer#1462]
According to the PT Wiki, we can utilize EMASPREAD for the buy_strategy and then it states the following:

*buy_value indicates the % above (or below if negative) the buy_strategy to execute the buy.*
*buy_trigger indicates how much loss the coin should have before activating DCA on it. *

So, if I set my DCA config as follows...

buy_strategy = EMASPREAD
buy_value = -2.0
buy_trigger_1 = -5.0
DCA trailing_buy = 0.5

My expectation is that PT will wait for the next EMASPREAD gap to be -2.0% (or lower) and then it will start trailing it down until it is at least 0.5% below my buy value (-2.5%) and then if it makes it back to -2.0% **AND** I am in negative profit by **-5.0% or worse, ONLY THEN** will it enter into a DCA buy.

Instead, as far as I can tell in my testing, it just completely ignores what you set as the "buy_trigger_1".  All it seems to care about is that you encounter the next EMASPREAD gap at -2.0% (or lower) and then it will start trailing it down until it is at least 0.5% below my buy value (-2.5%) and then if it makes it back to -2.0%...then it buys.  Problem with this, is it could be initiating a DCA buy when you are barley at a loss- which, to me, is a waste of a DCA balance cost.  Makes it so that there is less bang for your buck and not any real advantage to using DCA at that point.  

I only want to enter a DCA at a significant loss level, but would also like to take advantage of the EMASPREAD for DCA entry filter as well.  Is my testing true to life or am I missing something?  If this is the way the strategy works (ignoring "buy_trigger" when EMASPREAD is used as "buy_strategy", rather than the default ANDERSON DOUBLEDOWN approach), I'd like to request that it not ignore the "buy_trigger" when using other such strategies for DCA.

**Comment by SgtBatten** [comment]
you used buy_trigger_1 instead of buy_trigger. so it is seeing a 0 not -5

**Comment by YoJeff** [comment]
_trigger_x is only for anderson.  So this is not a bug.    While it's nice to have fleshed out details -- these types of questions can be ferreted out via support first please.

**Comment by ITJusus** [comment]
Sorry about that guys, yes, that makes sense now.

**Comment by ITJusus** [comment]
Not to add insult to injury, but it would actually make more sense to have the ability to use "buy_trigger_1" and "buy_trigger_2" and so forth, when the DCA Strategy is EMASPREAD, as this would allow us to set a different DCA threshold for each successive DCA level.  I don't see any reason why one would want that for ANDERSON DOUBLEDOWN, but not for the other DCA strategies.
