### ISSUE TITLE
Bug - Pending Feature Not Working

### ISSUE THREAD

**Issue by usslindstrom** [taniman/profit-trailer#1463]
I submitted a feature request to improve the bot, and move items from DCA to Pending by placing a sell order on them once they reached max DCA times.  This can be referenced by the following two tickets:

https://github.com/taniman/profit-trailer/issues/1399

And under the enhancement request area:

https://github.com/taniman/profit-trailer-enhancements/issues/222

//=======================
In order to handle some of the deep bags that can show up, I'd like to request a new feature be implemented. Currently, the only way to handle bags once they have finished the DCA tree is to do one of the following:

Panic Sell
 Meet a Stop-Loss criteria
 Or ride the wave back until the thing gets back to positive
 What I'd like to suggest implementing... Is once the DCA tree has gone all the way to the bottom, place a sell order on the coin, set at a defined percentage (like the DCA percentage) and move it to pending.

This way it would stop tracking it in the active pairs, and the bot could go and grab another set. Just a thought.

Right now, I have stop losses setup in my bot below the DCA, but it would absolutely hurt should one of those actually be invoked, and gains for the day would be lost by a single sell.
//=======================

Tickets were closed stating that I'm just describing the Pending feature as it already exists.  This is false.
![maxbuytimes](https://user-images.githubusercontent.com/36229685/37571609-d7d0dfb2-2af6-11e8-82a3-685779fdffb7.png)
![dcacount0](https://user-images.githubusercontent.com/36229685/37571610-d8036da6-2af6-11e8-9b4b-19bd3c7ddfc7.png)

As you can see, everything is still being tracked within the DCA log, a sell order has not been placed, and they are not being moved over to pending.  If it is supposed to, as suggested in the previous tickets, it is NOT working as intended.

Please point to where the pending feature is described as well, as it is not located within the Wiki.

**Comment by YoJeff** [comment]
Do you have a pending_order_wait_time?   Have you asked in support how to set this up?

**Comment by SgtBatten** [comment]
for clarification pending order wait time is time based, not dca complete based, but it does place items into fixed sell orders for the dca sell value.

**Comment by YoJeff** [comment]
dca pending is time based -after- dca completion?

**Comment by usslindstrom** [comment]
Thank you all for jumping in on this again.

I did see in the Wiki for the time based entry you are describing:

//=============================
ALL_pending_order_wait_time = 360

Valid Values: Integer values greater or equal to 0 

If x amount of time in minutes has passed since we bought a coin, create a pending order for that pair. 
This enables the bot to buy this pair again. Therefore, if you want the bot to continue to purchase this pair while you have a purchase that is currently held at a loss, then set this parameter to some value that is a day or two away from the original purchase date (2880 minutes = 48 hours). Then the bot will place a sell order at the desired profit % and will place your pair in the “Pending” log. 

At that time, the bot will begin to buy more of the pair at the current “Pairs log buy strategy”, and will report the Profit % and the Comb Profit % in the Pending Log. 
//=============================

- This is based off original purchase time frame, not based off completing DCA, as I understand it.  Meaning, they do not compliment each other.  It would be more beneficial, I believe, to have this also act immediately upon finishing the final DCA, as there is no guarantee on a timeframe of when that would occur.

**Comment by usslindstrom** [comment]
*Also way more beneficial in my mind, to be able to set the value to "0", or similar, so that immediately following the final DCA it places the sell order and moves it to pending - not time based.

**Comment by SgtBatten** [comment]
not after completing dca at all i dont think @YoJeff . not according to the documentation anyway.

also @usslindstrom you need to use pending_order_wait_time in dca not All_pending_order_wait_time in pairs. but yes, its purely time based

**Comment by YoJeff** [comment]
that's the pairs version -- there is a DCA version as well.   Read thatta one, and with that -- we shall close.   Support can take it from there.    Feature requests go over in the features github.

**Comment by YoJeff** [comment]
I'm pretty sure that the pending function in DCA is after DCA is exhausted.   Getting confirmation.....

**Comment by usslindstrom** [comment]
*Update.  After configuring the value as suggested.  It did in fact place sell orders, based off the time value, and I now have "open orders" on the exchange.

That being said, PT shows "0" still for pending.  It did remove the effected pairs from the DCA log however.

**Comment by SgtBatten** [comment]
give it 10 minutes to appear

**Comment by usslindstrom** [comment]
No sir.  - Did not appear.  Still reporting as "0"

**Comment by SgtBatten** [comment]
Weird.... Restart the bot.

**Comment by usslindstrom** [comment]
Thanks.  they've popped their ugly little heads in now.  Sorry to be such a bother.

**Comment by YoJeff** [comment]
Ok I'll close this out.   Have a request in to clarify wiki.
