### ISSUE TITLE
 [REQUEST]  A FAST WAY TO HOT CHANGE PT SETTINGS

### ISSUE THREAD

**Issue by keithofaptos** [taniman/profit-trailer#1464]
ON PT DASHBOARD IN “Config”, UNDER (OR ABOVE) “HotConfig” LINE,
COULD YOU MAKE A NOTEPAD ? SO WE CAN HAVE A PLACE ON THE DASH TO BE 
ABLE TO COPY/PASTE (HOT SWITCH) DIFFERENT STRATEGIES SETTINGS PRE-READIED. FOR A LIGHTNING FAST CHANGE UP,
ESPECIALLY FOR SHORTING CHANGES.
 10 CELLS,20 LINES DEEP. ALL ON THE ONE PAGE, LISTED ABOVE EACH OTHER, IN LINE, AS TO SEE WELL.  WITH A BUTTON TO AUTO SWITCH LINE CODE INTO PAIRS/DCA/ OR INDICATORS SETTINGS,AUTOMATICALLY IMPLEMENTING (SAVING).
 THEN WE CAN CHECK TO SEE SETTINGS HAVE BEEN IMPLEMENTED BY VIEWING PROP FILES (IE: PAIRS/DCA/IND).

**Comment by YoJeff** [comment]
Throw this over on the features github if it doesn't exist, without all the caps.
https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by keithofaptos** [comment]
Ok
