### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer#1466]
Add number of buy times to the DAC log.  This could be useful information when tuning DCA settings.

**Comment by wasif28** [comment]
add a function that sells all the dust for a desired coin after a certain period of time example selling all dust for BNB coin.

**Comment by taniman** [comment]
what do you mean? We currently already show the amount of buy times in the dca log

**Comment by BitRacer** [comment]
yes, it shows in the DCA log. When I finally sell though, I only see an _average_ .  I cant tell if it was zero rebuys, and never went into DCA, or if it had a rebuy(or three).

Knowing this would allow me to better tune my sell settings in the PAIRS and DCA settings.

**Comment by YoJeff** [comment]
Toss this over on the features github if it does not already exist for voting.   Best voted features get priority.  Include as much details an/or screenshots as necessary.

https://github.com/taniman/profit-trailer-enhancements/issues
