### ISSUE TITLE
Feature Request for Dust

### ISSUE THREAD

**Issue by wasif28** [taniman/profit-trailer#1467]
Add a function that sells all the dust for a desired coin after a certain period of time. Example selling all dust for BNB coin after x number of days.

**Comment by YoJeff** [comment]
If dust could simply be sold, nobody would have dust.

**Comment by wasif28** [comment]
in case of binance i usually sell my dust for BNB like after a week or so. this is helpfull in the case of binance only i guess because BNB also helps lower the trade fee

**Comment by jfcampos** [comment]
I think you need to buy the remaining amount until you have 1.XX and then you can sell for BNB. Not all pairs can be sold for BNB though. But it's doable.
