### ISSUE TITLE
Exporting data that is visible in GUI

### ISSUE THREAD

**Issue by DrrMrr** [taniman/profit-trailer#1468]
Hi,

Is it possible to add another varible with time how often data can be exported? Then one file would be generated or overwritten in that timeframe.

I would like to have access to values like "Total Current Value" and export them to file. That way I would write a script that will change my "ALL_max_cost" variable, depending, from the last stand.

Can I find that data anywhere else?

Thank you and best regards
Damien

**Comment by YoJeff** [comment]
You can access that information in an automated way either via URL ( /monitoring/data ) or by reading the ProfitTrailerData.json file.   Both are in JSON format.   Then you can do whatever you wish.

**Comment by DrrMrr** [comment]
Hi,

Thank you for your quick answer, but I can't find that value in JSON file or in URL ( /monitoring/data ) content.

Under which key should I find that?

[ProfitTrailerData.json.txt](https://github.com/taniman/profit-trailer/files/1830184/ProfitTrailerData.json.txt)

![image](https://user-images.githubusercontent.com/174676/37667731-f859a436-2c62-11e8-83ff-b8b235a5e7a1.png)

Thank you and Best regards
Damien

**Comment by djcrypto75** [comment]
Its a summary of many strings.  You have many currentvalue you need to add together etc. Its all in the monitoring/data array
