### ISSUE TITLE
FEATURE REQUEST - enable SOM after a predefined number of consecutive Stops

### ISSUE THREAD

**Issue by JaySatthee** [taniman/profit-trailer#1469]
It would be helpful, if we could automatically activate SOM after a number of Stop-Losses, because it usually means, that the whole market is going down.

Another idea in this context is to deactivate Stop-Loss automatically if there have been a couple of Stop-Losses in a row. It happens quite often, that the market dips in a matter of hours, but then rapidly recovers. So if Stop-Loss is activated all the time, you would sometimes lose money for no reason.

**Comment by JaySatthee** [comment]
#1059

**Comment by YoJeff** [comment]
All the new features are over in the features github.    Search first, then submit it there for voting.
https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by JaySatthee** [comment]
ok
