### ISSUE TITLE
Invalid License error

### ISSUE THREAD

**Issue by hillseylondon** [taniman/profit-trailer#1472]
Trying to get my bot running but keep getting an error message 'Invalid License'.
This is getting very frustrating.
Thanks for any assistance.

**Comment by YoJeff** [comment]
Jump into discord support please -- this is for bugs.   They will get you sorted out.
https://wiki.profittrailer.com/doku.php?id=start

**Comment by keithofaptos** [comment]
Did you click both sets of api keys on , on your exchange?

**Comment by hillseylondon** [comment]
Yes both have been entered and accepted on PTAssistant
 

    On Monday, 19 March 2018, 21:31, KILLth <notifications@github.com> wrote:
 

 Did you click both sets of api keys on , on your exchange?—
