### ISSUE TITLE
Consistent URL for download of latest .zip file version.

### ISSUE THREAD

**Issue by darrenworley** [taniman/profit-trailer#1473]
Hi,
Disclaimer: This is NOT a bug or an issue, just a request. I asked on Discord #support, and it was suggested I lodge an issue here...

Q: Can we have a single consistent URL for downloading the latest release .zip file?

IE, currently it is something like this : 
"$wget https://github.com/taniman/profit-trailer/releases/download/[*version]/ProfitTrailer.zip" 

It would be nice, and more effecient the [version] info was omitted, as when scripting an upgrade & backup/archival process and not knowing the new version number of latest release makes it more complex to script for.
Can we have something like : 
"https://github.com/taniman/profit-trailer/releases/download/ProfitTrailer.zip" 

Thanks :)

**Comment by taniman** [comment]
sorry, this cannot be done as it's github that decided the url. Maybe in the future we will build a portal to download versions

**Comment by darrenworley** [comment]
Excellent, thank you for the API link hint,... 
I'll sus out either passing the "assets_url:" and then grabbing the follow on "browser_dowload_url:", or just grep the "tag_name:" and insert for [*version]. Either is is quite doable.  Thanks !!!!  :+1:  :)

( FWIW, I can then cron a 'update check', and then if a valid flag set, email, or alert/msg so I then know to do a manual 'click to archive&update' in the command&control portal I am building...

PS, I was almost hopeful for the consistent url:
http://profittrailer.com/download/ProfitTrailer.zip 

Anyway, all good now, thanks for the pointer.
Darren
