### ISSUE TITLE
Coin stuck on REBUY_TIMEOUT

### ISSUE THREAD

**Issue by woody43567** [taniman/profit-trailer#1474]
After updating to the  PT Ver: 1.2.6.25 I am getting coins that are not buying with the reason REBUY_TIMEOUT. Currently I have this set to 15. The current time of the screenshot was 17:25pm.
I am in Aus so server.timeZoneOffset = +10:00
Looking at coin ONT it last sold approx 6 hours ago.

![image](https://user-images.githubusercontent.com/36909568/37639026-ea1a520c-2c63-11e8-8e64-5ef176d9274c.png)

![image](https://user-images.githubusercontent.com/36909568/37638986-bdd67ea0-2c63-11e8-9656-2a5137daf6a8.png)

After restarting profit trailer it starts trailing straight away and REBUY_TIMEOUT is cleared.
![image](https://user-images.githubusercontent.com/36909568/37639003-d2d1a744-2c63-11e8-9c94-f0828291b813.png)

**Comment by magyosha** [comment]
same
P T Ver: 1.2.6.25
still has rebuy out bug ... 
0.03.2018 09:15 (0D)    VENBTC    -3.13    REBUY TIMEOUT - (false)
now 11:23am ,,, timeout set to 15 minutes ..
should of cleared a long time ago ..
as you know restart clears it .. but bug is still there without resart

**Comment by T1aMat** [comment]
Same
PT Ver:  1.2.6.25

**Comment by ramonduraes** [comment]
+1

**Comment by nazgul33** [comment]
+1

**Comment by taniman** [comment]
would be nice if at least 1 person would provide their settings for pairs and DCA. in order to help the investigation

**Comment by magyosha** [comment]
happy share ... have ALL_rebuy_timeout = 15 in pairs .. but not in dca

Pairs ,, 
MARKET = BTC
ALL_trading_enabled = true
ALL_enabled_pairs = ALL
ALL_max_cost = 0
ALL_max_cost_percentage = 3
ALL_min_buy_balance_percentage = 0
ALL_min_buy_volume = 650
ALL_min_buy_price = 0
ALL_max_trading_pairs = 3
ALL_DCA_enabled = true
ALL_DCA_enabled_trigger = 0
ALL_buy_strategy = EMAGAIN
ALL_buy_value = -.75
ALL_max_buy_spread = 1
ALL_sell_strategy = GAIN
ALL_sell_value = 1.1
ALL_trailing_profit = 0.01
All_stop_loss_trigger = 0
ALL_stop_loss_timeout = 0
ALL_rebuy_timeout = 15
ALL_panic_sell_enabled = false
ALL_sell_only_mode = false
ALL_sell_only_mode_override = false
ALL_btc_price_drop_trigger = 6
ALL_btc_price_drop_recover_trigger = 5
ALL_btc_price_rise_trigger = 8
ALL_btc_price_rise_recover_trigger = 6
ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0
BNBBTC_trading_enabled = false

DCA

max_cost = 0
max_buy_times = 4
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -1.25
buy_trigger_2 = -2.5
buy_trigger_3 = -4
buy_trigger_4 = -6
buy_trigger_5 = -6.5
buy_trigger_6 = -8.5
buy_trigger_7 = -12
trailing_buy = 0.1
sell_strategy = GAIN
sell_value = 1.1
sell_trigger = 0.8
trailing_profit = 0.1
stop_loss_trigger = 0
min_buy_volume = 450
buy_available_volume_trigger = 0
ignore_sell_only_mode = false
max_buy_spread = 1
min_buy_balance = 0
pending_order_wait_time = 0
buy_available_volume_trigger = 100

**Comment by knowngate** [comment]
I too have issue like that,
I deleted that time out code.
Now working fine. And dca r done acc my settings.

**Comment by taniman** [comment]
unable to reproduce. report issue again if it happens with V2
