### ISSUE TITLE
Request: do not sell more coin than purchased 

### ISSUE THREAD

**Issue by DaveCaro** [taniman/profit-trailer#1476]
An option to not sell more coins than purchased by the bot. 

I realize this would hinder the bots ability to sweep dust, but it would help those of us who mine to or exchange wallets.  I've had a few instances of mined LTC (for example) being sold along with a bag. 

If there's a solution to this already, I'd love to hear it

**Comment by taniman** [comment]
The bot will never work in this fashion. The bot will always sell everything it can sell. I suggest you create a second account for mining.
