### ISSUE TITLE
EMACROSS- buying on the drop

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer#1477]
I've mentioned this issue in another request related to a different EMACROSS issue...but the mighty Thrasher (Discord- #Support) recommended that I open this request, specifically for this aspect of how PT is currently handling the EMACROSS Strategy...

We would like a way to prevent PT from buying a coin on the way down, and rather it ONLY buy on the way up the cross threshold, once the Fast EMA has crossed up the Slow EMA in the specified candle(s).  With the current logic of PT, one is too often doomed to eventually buy on the way down...pretty much wiping out any profits made on the way up (post "up" cross).  

In my experience this can occur if you happen to start your PT bot after the Fast EMA is already above the Slow EMA cross percent "spread" (buy_value to buy_value_limit) specified.  PT will wait to buy until the Fast EMA falls all the way back down into the percent "spread" (buy_value to buy_value_limit) specified again...basically, as the price is falling.  And a new bag is born.

Another way this can happen is even if you did have the PT bot running when the initial EMA Cross occurred and you did get a good buy in at that point, you'll likely be selling with GAIN or HIGHBB when the price has risen above your percent "spread" (buy_value to buy_value_limit) specified.  So then what goes up will, in most cases, come back down and once the Fast EMA gets back into that percent "spread" (buy_value to buy_value_limit) range specified again (assuming the candle count is still valid)...PT will buy on the way down and that bag % loss will too often be a larger % for days (when working with hourly timeframes, for instance) than any gain you made in the prior trade on the way up.  You may eventually see that bag come back to profit or it may continue down down down- tying up your resources, which if time = money...counts as a daily loss to me.

I checked around in the Discord and it was confirmed in #Support this is a current limitation of the PT bot’ handling of the EMACROSS strategy.  We would only like it to buy when it is crossing UP and not when it happens to be crossing back DOWN. I don't know how hard that would be to pull off, programmatically, but that would be the ideal.

**Comment by ITJusus** [comment]
As it stands for now, it appears it is a limitation in the PT bot's handling of the EMACROSS strategy and there is nothing we can do about it (except a feature request).  From my experience then, the EMACROSS stategy in PT is not profitiable on the average.  The negative % bags created on the tail end of each cross out-weigh the profits made on the front end of the cross, when you factor in the time (= money) one typically has to hold those bags rather than making profits with other trades in that same time-frame.  Just my opinion and experience.  Hopefully PT will improve this situation or a workaround will be found, else EMACROSS is not worth the cost for me.

**Comment by maker1151** [comment]
Its been pretty good with USDT pairs and the BUY_VALUE feature helps out a lot with false positives.

**Comment by taniman** [comment]
Sorry, this will not be worked on as a bug. and as you say you already mentioned this in another post that is still open.

**Comment by ITJusus** [comment]
@taniman 
The post I mentioned this in was "EMACROSS from candle 0? #1376"...which was closed by you 4 days ago, because you felt like you addressed my issue of "EMACROSS from candle 0" by proving to me that the Wiki was not correct and it is actually candle 1 that is the current candle.  I was in agreement that you addressed the topic of that post (candle 0), but that is not the topic of this post.  This post is about the issue of EMACROSS buying on the drop (regardless of which number of candles are chosen).

I did side mention this in the other post, but this was never addressed.  Would you guys consider working on improving this aspect of EMACROSS or should I just give up requesting it?  I did try looking for alternative workarounds on Discord before coming back here to officially post a request.
