### ISSUE TITLE
Binance BNB Sales Log incorrect calculation profit in USD

### ISSUE THREAD

**Issue by SynchiropusSplendidus** [taniman/profit-trailer#1481]
The Sales Log for the Binance BNB bot calculates the profit in USD wrong!  

**Example:** 
![profit trailer binance bnb](https://user-images.githubusercontent.com/37474014/37709706-5b1cfef8-2d0b-11e8-8469-17dffbc45c90.PNG)

Profit in BNB: 0.04671192 ($2.78)
Calculated Profit in USD: 2.78

Correct Profit in USD (1 BNB = ~10 USD) would be: USD 0.4671192

**Comment by taniman** [comment]
yes. will be fixed in 2.0
