### ISSUE TITLE
[REQ] DCA Trailing buy per level

### ISSUE THREAD

**Issue by fjdelaba** [taniman/profit-trailer#1482]
Hi, i would think it would be interesting if we can have a trailing buy per lvl, as most people do, we have a low % loss on the first lvls so a trailing of say, .2 it´s what we use, but from lvl 5 or 6 most people go to -5 or -8% for the triggers, so i would like a .6 or something like that as a trailing buy.

Another way of putting it, is that trailing buy on DCA should be a % of the trigger, not an absolute value, for every trigger.

**Comment by YoJeff** [comment]
Toss this over on the features github if it does not already exist for voting.   Best voted features get priority.
https://github.com/taniman/profit-trailer-enhancements/issues
