### ISSUE TITLE
Telegram notifications not working in pt recent version

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer#1483]
Hi.
Telegram notifications r not working.
Not a single trade notification is received yet.
Pls look at this issue.
I m running pt on Ubuntu vps.

**Comment by knowngate** [comment]
I test telegram notifications from link given in wiki.
It's show msg 
"BINANCE BTC - Your telegram is setup correctly"
But no any update of my trade is there.

**Comment by taniman** [comment]
please contact support. as there is no issue with the telegram.  This logic has not been touched

I have received multple telegrm messages since releasing the latest version
