### ISSUE TITLE
EMAGAIN with positive value seems to get wrong trigger

### ISSUE THREAD

**Issue by SG2010** [taniman/profit-trailer#1485]
Recently I am using a new strategy which is a positive EMAGAIN and seems that it trigger a buy at the time I didn't expect it to.

Example:
XRPBTC_trading_enabled = true
XRPBTC_DCA_enabled = -2
XRPBTC_buy_strategy = EMAGAIN
XRPBTC_buy_value = 1
XRPBTC_trailing_buy = 0.106

XRPBTC_sell_value = 1.25
XRPBTC_trailing_profit = 0.0848
XRPBTC_max_cost = 0.0021
XRPBTC_min_buy_balance_percentage = 3
XRPBTC_min_buy_volume = 1500
XRPBTC_min_buy_price = 0.000005
XRPBTC_rebuy_timeout = 30
XRPBTC_max_buy_spread = 0.75
XRPBTC_min_profit = 1.5

And I saw in Binance, I got a buy at 03-21 10:51:31 @ price = 0.00007688.
At Log I saw:
2018-03-21 07:51:37 INFO NormalStrategyRunner - BUYLOG: {"BBLow":0.0,"BBTrigger":0.0,"positive":"true trailing...","BBHigh":0.0,"currentValue":0.15817788888570217,"market":"XRPBTC","profit":0.0,"currentPrice":7.688E-5,"buyStrategy":"EMAGAIN","volume":4308.71362935,"triggerValue":-0.13868258438256564,"percChange":-0.03635}

But if you go to tradingview.com and set the EMAGAIN graph, it shouldn't be buying at 7am or 10am on 2018-03-21.  (See attached image)
![capture](https://user-images.githubusercontent.com/7924078/37794180-1cf7eab6-2de7-11e8-8d65-d607ab570367.PNG)

**Comment by YoJeff** [comment]
So what was the EMAGAIN value at the tip of those wicks around 7am?

**Comment by YoJeff** [comment]
Also, trails are always down right now..   So if you want to buy breakouts, check into spread strats with zero trail.

**Comment by SG2010** [comment]
I made a mistake in my server, my server time wasn't the in the same time zone I captured the chart.

See Binance:
![binancetransactions](https://user-images.githubusercontent.com/7924078/37799471-292f7920-2df6-11e8-9686-8a83eb87ae44.PNG)

The transaction is actually happened at 10:51am.  I just changed the time in my server to make them identical, anyhow, here's the new screen capture:
![capture1051](https://user-images.githubusercontent.com/7924078/37799501-483a31b6-2df6-11e8-8008-8215242de235.png)

Noticed the top of the screen has O and C, where Open is at 0.00007696 and Close is at 0.00007689 (close price is similar to my buy price and open price is the tip of of the value).

I also high light the lowest tip of the EMA and the top tip of the bars at around 10:51am.  The % change was no where near 1%.  And if you look at my previous screen capture the green area is the part where 1% should trigger (which is around 15:00 on 03-21)

I understand trailing is always down, but my point is, I set buy at EMAGAIN = 1% why would I even enter buy when coin price is not 1% > lowest EMA band?

**Comment by taniman** [comment]
Please provide your complete log file as I am missing some information I need.
Also i assume you are on the latest version of the bot?

**Comment by SG2010** [comment]
[ProfitTrailer_20180320.log](https://github.com/taniman/profit-trailer/files/1843459/ProfitTrailer_20180320.log)
Attached is the log starting from 2018-03-20.  The time when this happened was at 2018-03-21 07:51am (PDT UTC-7)

The chart that I submit is actually at EDT (UTC -4).

And version of bot is v1.2.6.25.

**Comment by taniman** [comment]
Hey. The buy was correct. This is something that we are working on.
The way emagain currently works is like this...

you have set your buy_value to 1%

so the bot will on a value of 1% or lower. So a value of 0.5% is also good. a value of -0.2% is also good.

So you draw a line 1% above the lowest ema.
if current price is anywhere below that line, then the bot buys.

This is how the current behaviour works and will be changed in PT 2.0

**Comment by SG2010** [comment]
Thanks for the explanation.  I will test other strategy instead.
________________________________

**Comment by SG2010** [comment]
Thanks for the explanation, I will try other strategy.
________________________________
