### ISSUE TITLE
Log all Basecoins BuyPrice when buying a Coin

### ISSUE THREAD

**Issue by zapedge** [taniman/profit-trailer#1489]
When i buy a coin against lets say ETH and then later decide to switch my Basecoin to BTC, USDT, or BNB I have to enter the XXXYYY_bought_price = in the HotConfig. 

To get the bought_price for the new Basecoin I lookup the Price for the new Basecoin on TradingView at the time of the buy against ETH. 
It would be nice if this could happen automatically via Exchange-API-Query at the time of the initial buy (and DCA buys of Course). 

This should of course be optional by adding a new parameter like 
"log_alternate_buy_price":  "BTC, USDT",

**Comment by taniman** [comment]
I see why you would want this. But I do not believe I will implement this any time soon. it's not critical to the bot function as it's the user choosing to change from one currentcy to the other. So the user should als fix the price
