### ISSUE TITLE
BNBBTC_bought_price hotconfig not working

### ISSUE THREAD

**Issue by nazgul33** [taniman/profit-trailer#1490]
pt has been printing out
```
2018-03-24 10:13:54 INFO AverageCalculator - Please set BNBBTC_bought_price
2018-03-24 10:13:54 INFO AverageCalculator - BNBBTC - Possible avg 1 = 0.00101000
2018-03-24 10:13:54 INFO AverageCalculator - BNBBTC - Possible avg 2 = 0.00100755
2018-03-24 10:13:54 INFO AverageCalculator - BNBBTC - Possible avg 3 = 0.00100840
2018-03-24 10:13:54 INFO AverageCalculator - BNBBTC - Possible avg 4 = 0.00099855
2018-03-24 10:13:54 INFO AverageCalculator - BNBBTC - Possible avg 5 = 0.00102894
2018-03-24 10:13:54 INFO AverageCalculator - BNBBTC - Possible avg 6 = 0.00102903
```
for a while, (at least for a month, since version 1.2.6.22 or lower)
and I entered hot config like below a hundred times, and it's not working at all

![image](https://user-images.githubusercontent.com/6119284/37858763-2065184c-2f4d-11e8-8c41-664d9e7f933f.png)

![image](https://user-images.githubusercontent.com/6119284/37858769-3307d3c2-2f4d-11e8-9da5-ad4de4505cc1.png)

but pairs log doesn't update itself with entered value.
![image](https://user-images.githubusercontent.com/6119284/37858779-58eec460-2f4d-11e8-90e9-f28bf86da51a.png)

i bought BNBBTC manually a few times, and I'm keeping it for comission so it's not a big problem for me,
but still, I don't like pt printing "Please set BNBBTC_bought_price" every now and then,
so please, fix this.

thanks.

**Comment by SgtBatten** [comment]
It will never remember bnb because the amount you own changes every trade and the bot can't see this so it can't make a safe recalculation automatically.

This is not a bug.

**Comment by SgtBatten** [comment]
To answer you likely follow up question.

Hide bnb from the bot or ignore the message

**Comment by nazgul33** [comment]
even though the qty change on every trade, doesn’t it have to remember the
price until next trade?

2018년 3월 24일 (토) 10:49, SgtBatten <notifications@github.com>님이 작성:

**Comment by SgtBatten** [comment]
the bot isnt trading BNB, so the price of BNB is not important. You lose some BNB every trade because it takes fees from BNB

**Comment by nazgul33** [comment]
I can hide bnb, am aware that bdb price not important, and that i loose some every trade as **I already stated**. I know that this NOT IMPORTANT. but still PT can display correct price, and I can decide to sell or buy some without looking at binance, if PT gives me correct price.

1) I set price at some time.
2) BNB qty reduces without BNB trade record after my manual price input,
  PT can ignore BNB qty change. So the last manually entered price stands still.

How does this sound?

**Comment by SgtBatten** [comment]
Pt cannot tell the difference between you manually buying and selling a small amount of bnb and the bnb being used for fees.

It is not currently possible.

Therefore the bot does the safe thing and does not attempt to calculate a bought price. As this might be incorrect.

Having a bought price has no impact on you ability to see how much bnb you have remaining.

So yes I agree it would be nice. But it's not possible.

**Comment by taniman** [comment]
Have you already tried doing a reset stored average?
Or have you tried using a different value other than 0.00100755 ?

Please try these options ad also check in the log file. cause in the log file the bot will let you know if it used the bought_price you have given it in hotconfig or not.

**Comment by ramonduraes** [comment]
#HOTCONFIG
#BNBBTC_reset_stored_average = true
#BNBBTC_bought_price = 0.00100755

**Comment by ramonduraes** [comment]
@taniman One screen is missing to manage the coins without price. The option to click and update will be very useful. tks

**Comment by nazgul33** [comment]
thx ramon
2018년 3월 26일 (월) 09:51, Ramon Durães <notifications@github.com>님이 작성:
