### ISSUE TITLE
Sell Trigger - Max Value?

### ISSUE THREAD

**Issue by Steve1564** [taniman/profit-trailer#1491]
Whats the max sell trigger value i can use?

Had a bunch of TRX & set the sell trigger to 250%..... The bot sold at 12.51 

(i dont usually use such high values but it was a short hold)

Cheers 

Steve

**Comment by Steve1564** [comment]
Just to claify the coin was in "Pairs" Not DCA...

Steve

**Comment by SgtBatten** [comment]
What sell strategy? Sell trigger only works for highBB 

Sell value is what you needed for gain

**Comment by Steve1564** [comment]
Sorry Sgt... Yep its Gain.... I meant sell Value - 
Setting was 
TRXBTC_sell_value = 250      (in pairs file)

I only called it sale trigger as its labeled "Trigger" in the GUI


Steve

**Comment by Steve1564** [comment]
Full setting:-
TRXBTC_sell_only_mode = true
TRXBTC_DCA_enabled = false
TRXBTC_sell_value = 250
TRXBTC_trailing_profit = 2

**Comment by SgtBatten** [comment]
If you do the same thing on another coin you own right now do you see the value change in the GUI. Test it temporarily.

Please send a screenshot of the test not working and your pairs settings.

Also confirm your exchange is binance?

**Comment by Steve1564** [comment]
Yep Its Binance..... 
Value changed in the GUI - but previously the pair sold at 12%
![image](https://user-images.githubusercontent.com/35610015/37863682-0b5cd162-2f5a-11e8-82d9-96e6f84a10ad.png)

**Comment by Steve1564** [comment]
![image](https://user-images.githubusercontent.com/35610015/37863707-c46a5e4a-2f5a-11e8-8dc9-f58fc04c5348.png)

**Comment by SgtBatten** [comment]
Trading is disabled? So sell value won't do anything and it shouldn't have sold at all?

**Comment by Steve1564** [comment]
Ahh Yes at the moment.... but it was'nt yesterday, i dont want to enable trade as it might sell the coin again....

**Comment by Steve1564** [comment]
...... Just a thought, is it possible that PT magic would have over written the setting as an "anti p&d" protection?

**Comment by Steve1564** [comment]
.... Could this be the 2nd time i've made myself look like a complete wanker?

**Comment by SgtBatten** [comment]
Yes that's probably the cause. Seeing as it currently looks to be working as you intended. And I can't see why it would have failed you. Magic would explain it

**Comment by Steve1564** [comment]
Another 1d10t error !!!
