### ISSUE TITLE
[Feature Request] ALL_max_cost range

### ISSUE THREAD

**Issue by ramonduraes** [taniman/profit-trailer#1492]
set a value of ALL_max_cost = 0.5 which is the maximum value desired per order however I do not have this total value and the bot does not buy anything else even though 0.4 is available. You may need to set a buy-per-coin range.

ALL_min_cost = 0.002
ALL_max_cost = 0.5

Thanks

**Comment by SgtBatten** [comment]
All max cost does not mean max cost. It is renamed in version 2.

But for now you need to read what all max cost means in the wiki

**Comment by ramonduraes** [comment]
Thanks for the info. I think it would be important to have a range between the minimum and maximum for the value of the order.

**Comment by SgtBatten** [comment]
The bots aim for the fixed amount for every coin.

If you want to set a different all max cost for each coin you can

**Comment by ramonduraes** [comment]
I wish any currency to buy up to the value of 0.5 BTC for example. However, in this way, if you have a free balance of 0.4, it stops and does not buy.

**Comment by taniman** [comment]
I do not see the appeal. either you have enough money to buy or you don't Why should the bot be doing more calculations even before making a buy

**Comment by ramonduraes** [comment]
In this proposal you will have the flexibility to always buy avoiding the bot being stopped. If I just set ALL max _cost and I have a slightly lower available value it does not buy and we lose opportunities. Using the "range" all scenarios work. In practice you check the "Range" vs. BAL and will have the maximum value per purchase order.

Scenario:

Range: (ALL_min_cost = 0.002 and ALL_max _cost = 0.5)

1) BAL = 0.9 BTC => Bot purchase in the amount of 0.5
2) BAL = 0.4 BTC => Bot purchase in the amount of 0.4

Summary: In this proposal using a period (Min / Max) whenever you have the BAL it will make an order and seize the opportunity.

**Comment by ramonduraes** [comment]
Hi @taniman Is the proposal clearer in my last post?

**Comment by YoJeff** [comment]
This issue is closed/rejected.

**Comment by alvarovalle** [comment]
this:

**Suggestion
DEFAULT_order_min_cost = 0.002
DEFAULT_order_max_cost = 0.5**

makes lots of sense, more flexibility means more accuracy.

it is about optimize results in my point of view, obviously would lead us to more profit

**Comment by Mikeeetrue** [comment]
Don't be too complicated. 
Just make it like this:
DEFAULT_initial_cost_balance_percentage = 10
Which means "use 10% of free balance to buy the coin"

**Comment by rogeriorrodrigues** [comment]
@ramonduraes @SgtBatten  Will you launch this feature? This will help me a lot in the my project. I need to have something that can work with Min and Max. That would be perfect!

**Comment by YoJeff** [comment]
I'd say the developer rejecting and closing the issue is all the answer you need.    If you want, put it over here, and if it bubbles to the top -- it can be reconsidered.
https://github.com/taniman/profit-trailer-enhancements/issues
