### ISSUE TITLE
Please Add Volume Column in DCA Log

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer#1494]
hi
This is a suggestion, its been good if we see a Volume Column in DCA Log.
Which SHow Volume Gain % from bot made trade in it.
Trading is a Learning Process Which is a Xp gain with Time spent in it. so it will helpful.
Thanks

**Comment by taniman** [comment]
Sorry, but we are trying to remove column from DCA log. It currently has too many column already.
