### ISSUE TITLE
Incorrect Buy Price led to Selling for a loss.

### ISSUE THREAD

**Issue by mtcoope** [taniman/profit-trailer#1496]
This morning, my bot purchased STORMETH at 3:12 AM UTC-05:00 time for .00011339, The bot recorded that as .00005717 and then sold for .00011170 and .00011157. The bot recorded at 94.95% and 95.18% profit but was really a small loss. Screen shots below. Let me know if you need any other info. Thanks!

![image](https://user-images.githubusercontent.com/12025920/37868055-2e9f3904-2f77-11e8-9dc7-bbe56131f5dd.png)

![image](https://user-images.githubusercontent.com/12025920/37868063-4d9603ec-2f77-11e8-8700-02933ee8ee51.png)

**Comment by SgtBatten** [comment]
What version?

Please upload the log.

You appear to not have enough BNB to pay for fees and are getting dust which does not help.

**Comment by mtcoope** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1844845/ProfitTrailer.log)

Version 1.2.6.19

**Comment by taniman** [comment]
You can open a new issue if this problem happens on the latest version. 
Like @SgtBatten  said. We have are now on version 25 and have release multiple fixed also for incorrect buy  prices.
