### ISSUE TITLE
bot stops buying after this error. how can i fix this. PLS help

### ISSUE THREAD

**Issue by mydonose16** [taniman/profit-trailer#1503]
2018-03-26 06:35:11 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message Error in reading response Read timed out, message

**Comment by mydonose16** [comment]
PT ver 1.2.6.25

**Comment by mydonose16** [comment]
binanceBTC windows 7

**Comment by YoJeff** [comment]
This showing from time to time is normal. Please use support for questions.
https://wiki.profittrailer.com/doku.php
