### ISSUE TITLE
Average price

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer#1506]
Bot keeps loosing the average price on coins. I have to keep going in and set the price. This is happening more than 5 times a day. If I have to babysit the bot all day I mine as well shut it off and do the trading myself.

**Comment by SgtBatten** [comment]
Which version and which coins.

Don't bother with BNB as it will always get lost.

**Comment by DragonBtc93** [comment]
PT Ver:  1.2.6.25
binance
Running on Ubuntu 16.04
 It happens off and on with all coins.

**Comment by SgtBatten** [comment]
do you have dust for the coins it is happening to?

**Comment by DragonBtc93** [comment]
yes

**Comment by SgtBatten** [comment]
okay, dust is a pain but it should be able to work it out mostly on its own unless you are also doing manual trades.

please upload screenshots and your log file for some of these buys where it forgets the price

**Comment by DragonBtc93** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1849551/ProfitTrailer.log)
Here is a log at the end you will see ICXETH
Don't have a screen shot don't have any of them with messed up price. Already fixed them.

**Comment by taniman** [comment]
Are you receving referral commissions on this exchange account. That the main reason for losing prices constantly

**Comment by DragonBtc93** [comment]
Never thought of that. Yeah I have a friend as a referral

**Comment by taniman** [comment]
Currently it's not possible for us to remove the commission dust from the calculations as binance does not return this in their api. 

Maybe in the future we will figure out a better way to deal with referrla commissions and losing of price. 
For now my recommendation to everyone is always. Avoid receiving commissions on the account where you are trading with the bot
