### ISSUE TITLE
Recently bought coins not showing up in the Web GUI logs

### ISSUE THREAD

**Issue by riserpete** [taniman/profit-trailer#1507]
Recently bought coins not showing up in the Pairs log, DCA log or any of the logs. Attached my logs file and the trading folder.
Bot just bought AST_ETH, STORM_ETH, ENJ_ETH and NEBL_ETH

[trading.zip](https://github.com/taniman/profit-trailer/files/1848949/trading.zip)
[ProfitTrailer.log.zip](https://github.com/taniman/profit-trailer/files/1848950/ProfitTrailer.log.zip)

**Comment by GuillerVks** [comment]
Review DCA.properties

> 2018-03-26 20:01:21 ERROR DCAStrategyRunner - An error occured
> java.lang.NullPointerException: Name is null

You have a misspelled word, comment all and discard by removing comment and check it in profit wiki, maybe is a PT Feeder problem.

**Comment by riserpete** [comment]
thank you @GuillerVks ! it was indeed a feeder problem. issue solved.
