### ISSUE TITLE
PT miscalculates dollar costs in BNB Sales

### ISSUE THREAD

**Issue by IAmNigh** [taniman/profit-trailer#1508]
You'll see that in the clipped screenshot that the dollar calcs for BNB are off.
![screen shot 2018-03-26 at 3 13 01 pm](https://user-images.githubusercontent.com/37220652/37927568-7bda29ee-3108-11e8-8f63-89fbda0f2b7f.png)

**Comment by taniman** [comment]
This issue was already reported. It will be fixed in PT 2.0

**Comment by IAmNigh** [comment]
THANKS! 

    On Tuesday, March 27, 2018, 2:25:55 PM EDT, taniman <notifications@github.com> wrote:  
 
 
This issue was already reported. It will be fixed in PT 2.0
