### ISSUE TITLE
Non-Persistent / Selective Panic 

### ISSUE THREAD

**Issue by RchGrav** [taniman/profit-trailer#1509]
***Apologies if this has been suggested...***
It occurred to me that it would be really nice to have a "Selective Panic" in the GUI that overrides the configured panic settings until the next restart.  Often there is things sometimes worth holding that can exit without a loss if given the opportunity.  :x: :x: :ok: :x: 
  Using panic is sad, but if you have ever forgotten that you left Panic Sell enabled and dumped a good position you'll know how this can add insult to injury...  I'm not proud of this but I'll admit I've done it..  Leave panic sell disabled in the config and just start a non-persistent panic until you start the bot again, or do the opposite knowing that restarting PT will cease all trades and dump you back into your base coin.
  Anyway. that's the pitch .. "Selective Panic".. a Keep/Discard for each position, and a Non-Persistent Panic Toggle that overrides the current state until you restart ProfitTrailer.

**Comment by keithofaptos** [comment]
+1

**Comment by YoJeff** [comment]
Slated for 2.1
https://github.com/taniman/profit-trailer-enhancements/issues/7
