### ISSUE TITLE
[Req] Create Button to retrieve coin Balance data (Getting manual buys in on request)

### ISSUE THREAD

**Issue by lesiromanu** [taniman/profit-trailer#1512]
The title says it all.
On binance, sometime it takes longer than 5 minutes. You get lost opportunities like that.

Thank you

**Comment by taniman** [comment]
Sorrry. But it's a bot. You are not suposed to do things manually on your exchange. If you won't wait 10 minutes you can always restart the bot.

We need to store data locally as the exchange does not like us retrieving data continuosly
