### ISSUE TITLE
PT is not placing sales orders - POLO ver. 1.2.6.25

### ISSUE THREAD

**Issue by rafaBit** [taniman/profit-trailer#1513]
I have tried even set PANIC_SELL_ENABLED = TRUE and doesnt work. The problem started after I did the update to new version. Any ideia?

**Comment by taniman** [comment]
This version has been online for a few weeks. I can assure you it has no problem with selling. 
Please contact support and maybe provide them with your log file to see what might be your problem.

This place is for reporting actual bugs
