### ISSUE TITLE
Basic Stop Loss

### ISSUE THREAD

**Issue by gdgoggin** [taniman/profit-trailer#1514]
Trying to set stop loss of -2%, but code below not working.
Any suggestions?

PAIRS
MARKET = BTC
ALL_trading_enabled = true
ALL_enabled_pairs= ALL
ALL_max_cost = 0
ALL_max_cost_percentage = 1.8
ALL_min_buy_volume = 200
ALL_min_buy_balance = 0.0
ALL_max_trading_pairs = 25
ALL_min_buy_price = 0.00025
ALL_panic_sell_enabled = false
ALL_sell_only_mode = false
ALL_buy_strategy = EMAGAIN
ALL_buy_value = -.30
ALL_trailing_buy = .253
ALL_sell_strategy = GAIN
ALL_sell_value = .95
ALL_DCA_enabled = true
BNBBTC_trading_enabled=false
All_stop_loss_trigger = -2
ALL_max_buy_spread = 3

DCA
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -1.75
buy_trigger_2 = -3.45
buy_trigger_3 = -8.75
trailing_buy = 0.377
pending_order_wait_time = 0
ignore_sell_only_mode = true
sell_strategy = GAIN
sell_value = .95
max_buy_spread = 2
stop_loss_trigger = -2

**Comment by YoJeff** [comment]
Define 'not working'  Does it DCA?  Does it fully DCA?   The way you have it, the top one is ignored, and the bottom one won't kick in until it DCA's 3 times.
