### ISSUE TITLE
[Feature Request] minimal reserve for a particular coin

### ISSUE THREAD

**Issue by duckybsd** [taniman/profit-trailer#1515]
I want to trade BNB in Binance, but I do not want PT to sell all my BNB, obviously, I need BNB to pay me trading fees.

Can we have some sort of config in PAIRS which can have a minimal reserve for a particular coin?

**Comment by YoJeff** [comment]
Toss this over into the features github for voting if it is not already there.
https://github.com/taniman/profit-trailer-enhancements/issues
