### ISSUE TITLE
PT bought 3 times in a couple of seconds

### ISSUE THREAD

**Issue by MareG76** [taniman/profit-trailer#1516]
PT bought 3 times in a couple of seconds, is it some bug or it is me ?

![srn](https://user-images.githubusercontent.com/34779580/38138094-200e32a8-3429-11e8-81b5-a730ac96aedc.JPG)

**Comment by taniman** [comment]
We will need your log file to investigate further

**Comment by MareG76** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1866454/ProfitTrailer.log)

Funny thing is that after 3 buys of 307 unit I should have  923 coins but I have 1230 so there must have been one more buy order but there is no evidence of that on Bittrex only these 3. Maybe it is exchange bug, I don't know...

**Comment by MareG76** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1866463/ProfitTrailer.log)
This is an older log file

**Comment by MareG76** [comment]
Hi it's me again. Bittrex order history is a bit weird because sometime there is an order history and some time there is non. But I managed to take a screenshot so now I can see that day before the triple buy happened there was a double buy at almost same time and same price.
![bitt](https://user-images.githubusercontent.com/34779580/38177154-36221c10-35fc-11e8-96b0-bd637b86f2b0.JPG)

**Comment by taniman** [comment]
There are no ETH-SRN buys in either of your log files for 2018-03-30. So I am wondering if you have provided the correct log file or that some other process bought these coin

**Comment by taniman** [comment]
actually one seems to be a Binance logfile and one is a bittrex log file....

**Comment by MareG76** [comment]
Maybe I sent you the log from other bot, sorry
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1871430/ProfitTrailer.log)

**Comment by taniman** [comment]
there is much fixed in v2.0 so I will close and when you get there we will see if the error happens again
