### ISSUE TITLE
Trailing Sell: Does not make sense

### ISSUE THREAD

**Issue by storxusmc** [taniman/profit-trailer#1518]
I am fairly new to the PT bot, i have only had it 8 days, but the bot has already managed to pull in a decent profit, but i have had a lot of confusion in how trailing sell acts.

Going off the info on the Wiki, my understandings is that the bot will combine the value and trailing together as the ultimate trigger to engage a sell, but it will only still sell if the price is above the value price.

I have had some odd situations in which i felt like the bot could have sold for more, but didnt do so....

Example 1:
ALL_sell_value: 0.8
ALL_trailing_profit: 0.2

Coin pair over a 20 minute period rose to 4.80% over average bought price, actual DCA screen displayed 4.80%, bot displayed 5.00% as trigger. Price dropped to 4.20%... trigger changed to 4.60%. Price dropped to 3.90%, trigger changed to 4.10%, price dropped to 2.08%, trigger updated to 2.28%, price dropped to 0.77%, trigger updated to 1.0%, price dropped to 0.40%.... still no sale
I was waiting for the bot to sell and figured maybe it maybe already sold and had not updated the screen, so i tabbed over to find that it had placed a sell order for 0.8% and that it expired, but it never attempted any sell orders above that 0.8% profit mark... so i tabbed over to market and managed to manually sell it for 0.28% over average bought as the RSI on the chart was diving way into the weak...

Why did this not sell higher, if i would have caught it sooner than i would have manually sold it up around the 4% mark...

Example 2:
ALL_sell_value: 0.6
ALL_sell_value:0.4

Coin pair went up to 0.6%, watched it as this was a pair i had for 2 days waiting to sell, it went up to 0.9%.... then hit 1.0% and the bot sold, but seconds later the price went up to 1.2%, then 1.5% and climbed 8.4% before topping off... what in this pair caused it to sell so fast compared to example 1, which the bot kept watching for a better price and ended up missing the sell alltogether.

**Comment by YoJeff** [comment]
This is for bug reporting.   Check your logs, visit the forum.   "Why didn't this coin sell" is a common question/not a bug.
