### ISSUE TITLE
Selling coins even though not authorized

### ISSUE THREAD

**Issue by kennykidd** [taniman/profit-trailer#1519]
Hello guys...I want to start by saying that I love Profit trailer...however, just rfalseecently I had an issue...

I'm on Binance and I do not wish to trade ADA, I want to hold them all. I have used the commands: ADAETH_trading_enabled = false
ADABTC_trading_enabled = false
ALL_hidden_pairs = ADAETH
ALL_hidden_pairs = ADAETH

After I saved everything in notepad++ and checked the config in profit trailer, all commands were saved and looked good...I checked back in the morning to see my results, and ALL my ADA were sold, and the hidden pairs command was gone, and the ADAETH_trading_enabled = false was changed to true...

Can you please tell me how to fix this so I don't have to worry about my ADA being sold...Thank you

**Comment by SgtBatten** [comment]
There is absolutely no way the bot changed false to true on its own.

Only yourself or a third party add-on could do this.

Also your use of hidden pairs is incorrect. But that's not what caused the sale.

This is not a bug. Come to discord if you have further questions.
