### ISSUE TITLE
DCA Log does not have column for Amount of BTC invested!!

### ISSUE THREAD

**Issue by Printersmith** [taniman/profit-trailer#1520]
This is obvious in the Sale log, but not the DCA log, WHY?  I NEED TO KNOW THE AMOUNT OF BTC I HAVE IN EVERY COIN.  AT ALL TIMES.  IN EVERY SECTION OF THE PROGRAM.....

Can't believe everyone isn't upset about this.  The only value that means anything is amount of BTC, or ETH, not the # of alts tied up :-)

Unless I can see BTC AMOUNT in everything, every transaction, every screen, I can't even know if my settings are working correctly......nor can I keep adjusting them bases on what I am seeing in my DCA screen......

**Comment by SgtBatten** [comment]
Far right column = total cost and current value. Chill

**Comment by Printersmith** [comment]
No, it dosn't.  Far right column equals amount of ALTcoin, it has not correlation to the amount of BTC.
![dca-log](https://user-images.githubusercontent.com/37848694/38169022-6c63d3ae-351b-11e8-9f4a-6d2c22d60d05.png)

**Comment by Printersmith** [comment]
The pairs, pending, AND sales logs all have the amount of BTC used on the last column.  DCA needs this desparately, it is super critical that I know exactly how much BTC is used, what the DCA steps are costing me, just like in the other logs, it's truly a no brainer, you can just agree with me :-)

**Comment by mastetz** [comment]
I can understand where he is coming from but i wouldn't call it super critical, could always go to the exchange and add it up from the order history.

**Comment by Printersmith** [comment]
You go right ahead.  I for one will expect the software to have consistency throughout and solve these simple problems so I don't have to take extra steps :-)  I trust they will get around to adding this soon!

**Comment by SgtBatten** [comment]
Yes it does.

Your screen is too small. Your far right column is hidden click the blue +sign to see it on the left box. Or minimise the left menu.
