### ISSUE TITLE
Java 'Error, java is not an internal or external command.

### ISSUE THREAD

**Issue by SebTrader** [taniman/profit-trailer#1522]
Ive downloaded and paid for ProfitTrailer, but whenever i click on 'Run-ProfitTrailer' it just comes up saying 'java is not an internal or external command.' I've tried downloading different types of Java but it still isnt working. Any ideas?

**Comment by taniman** [comment]
Please contact support and they could help you further. This place is for reporting bugs.

What you are having is a setup problem of your environment

**Comment by SebTrader** [comment]
Do you think it would maybe be worth me getting another laptop and trying it on that?
