### ISSUE TITLE
Incorrect profit amounts shown in Sales Log after switching master currency.

### ISSUE THREAD

**Issue by HenryHatten** [taniman/profit-trailer#1524]
After switching the master currency from ETH to BTC, all previous ETH transactions in the Sales Log have incorrect profits displayed.

E.g. after making a profit of 0.005 ETH on a DASHETH buy, then switching the master currency to BTC, the Sales Log now shows under "Profit BTC" the same value of 0.005 (which should either show ETH or be converted) and an incorrect USD value of $35 instead of the actual profit of $1.83.

**Comment by YoJeff** [comment]
Ideally, switching base currencies should be a thought out process, which includes accumulating your new base currency, disposing/exluding/repricing existing eligible pairs, and deleting your ProfitTrailer.json file to start anew.    It's not really practical to re-price history.

**Comment by HenryHatten** [comment]
That's all true. However to fix this bug PT just needs to note the currency that the sale was made in (e.g. ETH ) and that this is different that the current master currency (e.g BTC), and show either ETH in the sales log, or convert the number shown to the current value in BTC. Showing an old ETH number value under a column that says "Profit BTC" is a bug.

**Comment by taniman** [comment]
I really don't feel like adding a process to monitor the change of basecurrency. 
It's like you said the saleslog is cleared once the bot is rebooted.

But if I come accross this code in PT2.0 I will see what can be done.

**Comment by HenryHatten** [comment]
You don't need a process at all. Just in the code where you are displaying the profit, check the currency of the trade matches the master currency and adjust what you display accordingly.

**Comment by taniman** [comment]
https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)

With focus on the **S**

But will be fixed in 2.0 tnx
