### ISSUE TITLE
[Suggestion] Easy startup

### ISSUE THREAD

**Issue by ramonduraes** [taniman/profit-trailer#1525]
I suggest that the bot start normally and request the license and apis settings through the portal. This change facilitates the rapid deployment of VPS-based models.

Thanks

**Comment by taniman** [comment]
through what portal?

**Comment by YoJeff** [comment]
Exactly.

**Comment by ramonduraes** [comment]
@taniman Allow start the application without having to configure the initial files. The WebSite loads and asks for the parameters.

**Comment by ramonduraes** [comment]
@taniman ok?
