### ISSUE TITLE
[Suggestion] I suggest adding the bot name to all web application screens

### ISSUE THREAD

**Issue by ramonduraes** [taniman/profit-trailer#1526]
I suggest adding the bot name to all web application screens

Bot: MYbotxyz Market:  BINANCE BTC  ....

Tks

**Comment by taniman** [comment]
if you mean sitename, I am pretty sure it is already added to the browser tab. So what else could you mean?

**Comment by ramonduraes** [comment]
Display the sitename on the screen. It is a simple and very good change for those who have several bots.

![image](https://user-images.githubusercontent.com/2014324/38309489-90090216-37f0-11e8-8534-e5ba997aef57.png)

**Comment by YoJeff** [comment]
Toss it over here and see if it gets enough votes.
https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by ramonduraes** [comment]
Sorry!
