### ISSUE TITLE
Feature Request (Product security)

### ISSUE THREAD

**Issue by saintlyct1** [taniman/profit-trailer#1527]
Would it be possible to mask all API keys and passwords that are currently in clear txt in the PT config files pls.  This small change would make a HUGE impact on security for your product.

Its not difficult or time consuming to go out and scan for default setting on the most popular hosting facilities to locate potential PT targets. Anything to obfuscate the API keys (default and secret) and passwords would be great.  This enhancement would reduce the overall security impact to users when they get hacked because they chose to leave default settings in place.

Thx!

**Comment by taniman** [comment]
This request is more difficult than you would expect. In most cases the exchange needs us to encode the data before doing a request.
To encode the data we need the actual apikey and apisecret.

So if we where to mask those we would not be able to do any requests to the exchange. 

But maybe some kind of encryption/decryption might help

**Comment by YoJeff** [comment]
The bot needs decrypted keys to sign requests.  Every other API consuming product I have seen stored keys in plain text.    Real security would be difficult since it needs to be two way.   Obfuscation isn't real security.

Let's not waste time on this.   It's on you to secure your computer, and don't allow withdrawals.

**Comment by saintlyct1** [comment]
Encryption would work :) Maybe compile the installation files and use a script that would store the API/ API secret keys in an encrypted form somewhere inside of the PT config files.  Where only the "program" can access it when needed and encrypt it for use when interacting with the exchange This approach would require the user to enter the API and API secret 1 time, then it would be stored in an encrypted form within the app.

Just an idea, Im not sure of the level of effort for something like that but I know it would be received well by the community.

Thx for the follow up!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
