### ISSUE TITLE
[Suggestion] Possible Buy percent (0-100%)

### ISSUE THREAD

**Issue by ramonduraes** [taniman/profit-trailer#1528]
I suggest adding an indicator from (0 to 100)% to indicate the possibility of buying a currency. In a certain scenario we are following to see if the purchase will actually happen and this indicator will give us a vision.

Thanks

**Comment by SgtBatten** [comment]
I know this isn't a specific indicator but you can already determine exactly when the bot should be trying to buy or not.

Compare the buy value and current value columns in the possible buy log.

Current value needs to be beyond (for most strats this means under) your ALL_buy_value and have trailed away from whatever value the buy value column now states was the lowest price reached.

So in general....
If current value is All_trailing_buy above buy value and current value is also lower than All_buy_value it's looking to buy.

**Comment by YoJeff** [comment]
Multiple conditions (v2.0) make this impossible.    Closing.

**Comment by ramonduraes** [comment]
It is a suggestion based on who uses it. No matter the amount of analysis for the purchase the process takes decision. For "who uses" many times we are in doubt the reason of being "stopped".
