### ISSUE TITLE
Cannot get Bittrex to work.....

### ISSUE THREAD

**Issue by Printersmith** [taniman/profit-trailer#1529]
I am running 2 bots successfully for several weeks now behind PT Feeder.  So I ran out of BTC in this bear market so I decided I would put manual orders on all my BTC pairs and switch to ETH.

I just made copies of all my folders and started as it were a new install.  Made all the adjustments for the ETH market and everything worked perfectly on Binance.

Bittrex not so much.  I cannot get it to do a Heartbeat, the app just opens and locks after the Browser window pops open.  I never get any Heartbeats whatsoever and its only made 1 buy all day.  Also I've been switching between LOWBB and EMAGAIN trying to trigger it to do something, but now it has "possible buys" in several strategies, and they never update.  Wiping the Log, the Data, and getting New API keys have done nothing to correct this.

I am out of ideas, please help :-)

**Comment by SgtBatten** [comment]
if you aren't getting heartbeats then your bot isn't running. This is a support issue not a bug (most likely) so please come to discord. this github is not for this kind of issue.
