### ISSUE TITLE
Sell strategy HIGHBB not work correctly!!!

### ISSUE THREAD

**Issue by diominandrew** [taniman/profit-trailer#1530]
**My INDICATORS.properties**

BB_period = 3600
BB_sma = 24

**My PAIRS.properties**

MARKET = BTC

ALL_trading_enabled = true
ALL_enabled_pairs = ALL

ALL_hidden_pairs = BNBBTC
BNBBTC_trading_enabled=false

ALL_panic_sell_enabled = false
ALL_sell_only_mode = false

ALL_max_trading_pairs = 5

ALL_DCA_enabled = false

ALL_max_cost = 0.0022

ALL_min_buy_balance = 0

ALL_buy_available_volume_trigger = 105

ALL_rebuy_timeout = 0

ALL_buy_strategy = LOWBB
ALL_buy_value = -10000
ALL_trailing_buy = 0

ALL_sell_strategy = HIGHBB
ALL_sell_value = 50

BCCBTC_buy_value = -16.00

ALL_trailing_profit = 0
ALL_min_profit = 0

ALL_min_buy_volume = 0

ALL_min_buy_price = 0

All_stop_loss_trigger = 0
ALL_stop_loss_timeout = 60

ALL_max_buy_spread = 0

ALL_btc_price_drop_trigger = 0
ALL_btc_price_drop_recover_trigger = 0

ALL_btc_price_rise_trigger = 0
ALL_btc_price_rise_recover_trigger = 0

ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0

ALL_consecutive_buy_trigger = 0
ALL_consecutive_sell_trigger = 0

![src](https://user-images.githubusercontent.com/9446264/38193702-f68bc0e4-367b-11e8-90cd-b633e0de91b6.PNG)

**Comment by diominandrew** [comment]
My version PT is v1.2.6.24

**Comment by YoJeff** [comment]
Questions belong in support...
