### ISSUE TITLE
I've tried using support and its no help at all!!!!! 

### ISSUE THREAD

**Issue by SebTrader** [taniman/profit-trailer#1532]
Ive downloaded and paid for ProfitTrailer, but whenever i click on 'Run-ProfitTrailer' it just comes up saying 'java is not an internal or external command.' I've tried downloading different types of Java but it still isnt working. 

All I'd like to know is, would it be worth me getting another laptop and doing it on that?

**Comment by YoJeff** [comment]
You would still have the same problem, you need to install java.   This is for BUGS.    Support will get you fixed up.
