### ISSUE TITLE
[Feature request] Show actual profit/loss made not just trade profits.

### ISSUE THREAD

**Issue by HenryHatten** [taniman/profit-trailer#1534]
Ideally PT should show the user how effective his or her strategy is by showing the difference in the value of their assets after a period if a) PT was running and making trades during this period as opposed to B) PT was not running at all.

This would take into account all buys made and not just the ones that were turned into sales.

Its simple enough to implement: calculate the current assets of the user, rollback though all the orders of the period in question made by PT by adding/subtracting coins and currency for each buy and sell order made, re-calculating the current value of these adjusted assets, then reporting the difference.

PT could then show both the current trade profits and the additional actual profit or loss figure.

I've calculated this a few times myself and the actual profits are sometimes greater that the daily profits shown, so it can be advantageous to PT.

The current profits shown in PT are not precise indicators really of how effective a user's strategy is.

**Comment by taniman** [comment]
PT is a trading bot and we will keep our focus in that direction. Statistics is not our main focus.
We will start looking of ways to expand in that direction in the future
