### ISSUE TITLE
[Feature Request]DCA sell value for each trigger

### ISSUE THREAD

**Issue by BroTastix** [taniman/profit-trailer#1535]
For example:

"DcaSellValueTrigger1": "0.68"
"DcaSellValueTrigger2": "0.58"
"DcaSellValueTrigger3": "0.48"
"DcaSellValueTrigger4": "0.38"

Profit is the percentage on sell multiplied by the value you had.
Each time a trigger is achieved, the value grows.
To achieve the same profit with a higher amount of value one has to lower the percentage profit on sell.
I'm happy with a sell of lets say 0.20$ on pairs. Bigger bags can be sold cheaper. The thing here is that it's not about the amount of profit, instead it's about the potential one loses when 50% of his/her balance is stuck in one bag.

**Comment by taniman** [comment]
You are giving an example of what seems to be PTF code.
In any case this feature has already been build in PT 2.0
