### ISSUE TITLE
bug DCA Rebuy time not working. Losing money

### ISSUE THREAD

**Issue by robotlovefarm** [taniman/profit-trailer#1536]
This is not the first time I spot this bug

![screen shot 2018-04-03 at 10 05 01 am](https://user-images.githubusercontent.com/2906581/38237186-bd4350f8-3726-11e8-8c5a-426bb472bb37.png)
![screen shot 2018-04-03 at 10 04 43 am](https://user-images.githubusercontent.com/2906581/38237190-c0ce7568-3726-11e8-9284-95d12f3980f0.png)
![screen shot 2018-04-03 at 10 04 48 am](https://user-images.githubusercontent.com/2906581/38237193-c225595e-3726-11e8-8206-1b347e902d67.png)

If the funtionality doesn't fully work do not make it public otherwise you'll only make us lose money

**Comment by taniman** [comment]
As far as I know ther is nothing wrong with the functionality as multiple users are using it.  

So provide your log file and your complete trading folder and I would have a look.

**Comment by robotlovefarm** [comment]
It's inconsistent. Sometimes works and some don't so it's not easy to catch it. How can I send you a private message with the files? I don't want to make my strategy public. Thanks

**Comment by YoJeff** [comment]
PM on discord.

**Comment by taniman** [comment]
Did you have a chance to send the data?

**Comment by robotlovefarm** [comment]
@taniman not yet will do asap. Thanks

**Comment by taniman** [comment]
@B0mBeur The bot does not do random. :)
So I guess you are interpreting the rebuy timeout incorrectly?

If you set it in PAIRS. And the bot buys. The rebuy timeout will activate. Even if the pair jumps to DCA right after the buy

**Comment by B0mBeur** [comment]
if that's normal is there a way to disable the timeout if the pair drop in the DCA ?

Sometime the pair drop 4 or 5 % before going up again. It could really be usefull in that case.
