### ISSUE TITLE
Multiple Volume trigger

### ISSUE THREAD

**Issue by helo03** [taniman/profit-trailer#1537]
Hi, copied from a ticket:
Is there a way to make PT look at multiple days of volume as opposed to just the past 24 hours.
At present my PT settings only look at the volume for the last 24 hours . Is there a way to make PT look at volume for last 24 hours (0 to -24) plus the previous 24 hours (-24 to -48) plus the previous 24 hours (-48 to -72). To be clearer I would like PT to look at three days volume history in 24 hour increments not as one long history. 
Example: Lets say I have PT volume set to 850 so that PT looks for pairs that trade over 850 for the past 24 hours before it will consider purchasing the pair. I want to set a volume variable to 850 and I want PT to look at the last 24H 0H to-24H for volume of 850, next I want PT to look for a volume of 850 for a second period call it -24H to -48H, and finally I want PT to look for volume of 850 for a third period call it -48H to -72H. 

I would like PT to look at the time periods as separate entities/variables not as one long 0H to -72H entitle/variable. 
Is this possible to do in the current PT settings? If not is this possible to incorporate into the bot?

As a side note I run PT Feeder in conjunction with your PT bot

Thank you for your time and patients
Ivan Helton

BTW I want to thank you for sharing your bot with the world. I feel fortunate to have stumbled across PT. 
I found your product through CryptoGnome and Crypto Crow.

**Comment by taniman** [comment]
Sorry I think what you are requesting is a strategy on itself. So this will not be build in the bot currently
