### ISSUE TITLE
Feature Request 4 line ema FIBONACCI buy and sell

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer#1538]
Don't know if it is possible to do this but would love it if the bot could use the 4 line fibonacci to buy and sell. Here is a web site that shows what I'm looking for  http://investorji.in/fibonacci-ema-trading-system-short-medium-term-trading.html

**Comment by YoJeff** [comment]
Quad ema's with multiple crossover strategies is not on the current roadmap.   Toss is over on the features github and if it gets enough votes -- we'll implement it. 
https://github.com/taniman/profit-trailer-enhancements/issues
