### ISSUE TITLE
[Feature Request] Use coinmarketcap.com for limit Market Cap and Volume (24h)

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer#1540]
Hi !

A filter already allows the limitation on the volume "ALL_min_buy_volume" in the unit you are trading.

Problem, it is the volume in ETH / BTC, it is thus rather difficult to estimate the global volume that there is on a currency (example CTRETH, CTRBTC etc).

For example, I would like to be able to trade only corners (BTC and ETH) that have at least + $100 million in volumes per day

18 000 ETH x 400 eth/usdt = 7.3M $
With filter at ALL_min_buy_volume = 2000, PT by this money
![image](https://user-images.githubusercontent.com/15019378/38267695-8928978c-377c-11e8-9b51-5a6c6fab4d57.png)

Here are some examples of variables that would be interesting:

ALL_min_buy_volume = 2000
DEFAULT_min_24h_volume = 50 000 000
DEFAULT_min_cap_volume = 100 000 000

![image](https://user-images.githubusercontent.com/15019378/38268676-029b873a-377f-11e8-890a-44fe2734b74d.png)

Thank you for a job well done!

**Comment by YoJeff** [comment]
What about the people who care less about dollars?
Why make the volume check three dimensional?     

You want to trade xxxETH, but you want to limit it based on ETHxxx.

**Comment by YoJeff** [comment]
Whitelist.  Do the work ;)
