### ISSUE TITLE
[Feature Request] Sell Button

### ISSUE THREAD

**Issue by BroTastix** [taniman/profit-trailer#1542]
Hi,

Sometimes we see the coin rise let's say 3%.
Would love to have a button next to every pair/DCA when you press it, the bot will place an order for that coin @ the price on push. -> moves to Pending (for example).
Next info is PTFeeder info but since it's incl in v2.0 i'll post it here:
When a sell trigger is reached, trailing starts. It put's up a new trigger and so on. Once the coin drops a certain % and it's still above the first sell trigger, the bot sells the coin.

The problem here is that a coin crash a few % in one move, espacially after a nice bullisch trend.
Having a sell button next to each pair will give us the opportunity to sell the coin/bag on the price given by Profittrailer (coming from the exchange). 

Trigger +2% -> DCA bag of 1-2ETH(in one coin) -> current profit +0.25% -> press sell button.
Bag is sold.
Coin rises +25% -> bot waiting for trailing -> press sell button -> +25% profit (while the bot could sell it for lower)

**Comment by mightysoul** [comment]
Sounds really good :)

**Comment by YoJeff** [comment]
Vote for it here.  https://github.com/taniman/profit-trailer-enhancements/issues/241

Please SEARCH first.. Duplicate #1510,  #1437, #1271, #1152, #1080, #1079, #1037, #985, #946, #899, #805, #754, #749, #746, #677, #673, #525, #468, #360, #353
