### ISSUE TITLE
Wrong DCA log with manual buys

### ISSUE THREAD

**Issue by ManuGithu** [taniman/profit-trailer#1544]
OS: Linux
Version: 1.2.6.23 & 1.2.6.25

When I make a manual buy, the pair appear in the pairs log (normal behavior) or in the DCA log with various level of DCAs. 
When I check the exchange I can confirm the pair is bought only once but as it is imported by PT, it can go directly to the DCA log with a DCA level of 1 or 2. 
Note that I have: max_but_times = 1

I always buy BTC pairs with an amount of 0.03 BTC. 

In the DCA log (attached jpg) we can see that  
- BLZBTC is DCAed once, which is wrong since the total cost is 0.0297... 
- CHATBTC is DCAed once, which is correct since the total cost 0.0584... This pair went first in the PAIR log and then DCAed, that is normal.
- VIBEBTC, same issue as BLZBTC
- ARNBTC: this is normal since cost is 0.057...
- VENBTC is DCAed twice ! but total cost is still 0.028...

I have attached the order history of my exchange for VENBTC. We can clearly see it was bought only once for an amount of 77 units and 0.029 BTC
![dca](https://user-images.githubusercontent.com/34100280/38295602-cf726174-37ee-11e8-9af8-e179a8a19213.jpg)
![ven](https://user-images.githubusercontent.com/34100280/38295606-d393c068-37ee-11e8-8966-9ce99f155ae1.jpg)

**Comment by taniman** [comment]
If you buy things outside of the bot. The bot cannot go into the logic to clear dca data so it can start from zero. This is another reason we do not recommend doing manual buys/sells for the bot

So nothing we can do anout it. V2.0 will come with a hotconfig to make it possible to reset the DCA countet
