### ISSUE TITLE
[Request] Limit Buy/Sell/Stop-loss Orders for Single Pairs 

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#1546]
I would love to be able to create buy or sell orders manually from Profit Trailer. I know it is possible through my exchange but I do not prefer that. This feature could be beneficial to people who are doing technical analysis.

It would also be quite good if I can panic sell my pair at certain price trigger.

**Comment by YoJeff** [comment]
The bot's purpose is to trade.
