### ISSUE TITLE
Feature Request: Estimated Value Change and Profit % Graph

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer#1548]
Could you guys add these two to PT v2.0  from the Community Tools:
https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons

Estimated Value Change : Thats how I see how deep I am in the bag.
![ev](https://user-images.githubusercontent.com/24818442/38319418-9231aa52-37e6-11e8-8ee8-6f1f29510de2.png)

and 
Profit % Graph (Graphing-Tracker): So I can see that on my Ipad/Iphone because I cant run the custom java script on Ipad browser.
![pf](https://user-images.githubusercontent.com/24818442/38319429-9973d18c-37e6-11e8-9baf-cdd228b57a86.png)

**Comment by taniman** [comment]
any feature requests go to profit-trailer-enhancements
