### ISSUE TITLE
[Feature Request]Store a record of all buy trades.

### ISSUE THREAD

**Issue by HenryHatten** [taniman/profit-trailer#1549]
Currently PT does not store a history of buy trades that it performs, just the sales. This information can be useful to see, if not in PT itself, then by other third party apps. I would imagine it would not take much effort to implement this.

**Comment by YoJeff** [comment]
I'm not sure how this helps the bot fulfill it's primary objective --- trading.

**Comment by HenryHatten** [comment]
Its provides a way that PT or a third party can compare easily how by having PT running has changed the current net value of your assets, by being able to roll-back through the orders made for a time frame and calculate what the value of your assets would be now if PT had not done any trading at all.

I know it won't be used by PT, but if it can be added easily, it would be useful to me, possibly others.

Related to this issue at PT Magic:
https://github.com/Legedric/ptmagic/issues/388

If it can be done, great, otherwise no worries.

**Comment by YoJeff** [comment]
I get what it can be used for, but considering developer resources are not infinite, and this does zero to help the bot trade better, and this information is available on the exchange (where it should be), and PT magic integration is coming....

**Comment by HenryHatten** [comment]
Also I think seeing these buy trades in PT would be interesting for the user to see the DCAs in action, and to verify that the BOT is doing what they expect it to do.

**Comment by YoJeff** [comment]
All actions are in the logs.   I'm inclined to shelf these 'replace the exchange' type features that do not enhance trading.    Throw it over on the features github for voting and lets see if it sinks or swims.
https://github.com/taniman/profit-trailer-enhancements/issues
