### ISSUE TITLE
Weekly/Daily profit in BTC + USD

### ISSUE THREAD

**Issue by zcpnate** [taniman/profit-trailer#155]
Add subtext for current USD earning. Current profit * current BTC/USD price 

Low priority, enhancement

**Comment by taniman** [comment]
I am not sure I understand what you mean here

**Comment by gmjosund** [comment]
I am guessing add BTC value in USD. Like you have on Poloniex.

**Comment by zcpnate** [comment]
![image](https://user-images.githubusercontent.com/29843998/31888431-014890e2-b7ca-11e7-80b8-c66e640b6505.png)
