### ISSUE TITLE
[Feature Request] HTTP Compression Function

### ISSUE THREAD

**Issue by Suzhou65** [taniman/profit-trailer#1551]
If I remember correctly, ProfitTrailer's java program didn't use http compression (Gzip )

ProfitTrailer's data transfer is frequently, 1 request will transferred 7.75KB. The more logs ( trade process ) you have, more data transfer it did.

If you running ProfitTrailer on you own computer than is fine, but if you running ProfitTrailer in cloud server,  like google cloud platform, it's billing will increase by your data transfer

Yeah, running ProfitTrailer on Docker, build proxy and using nginx to provide compression function is great, but not everyone know how to build a Docker and put ProfitTrailer in ( I fine some Docker-ProfitTrailer scripts on GitHub, but even in clean system, it still failure)

Can ProfitTrailer make a Built-in http compression function? Thanks

**Comment by taniman** [comment]
if you find 7KB to be too much data I suggest you use a different vps provider. 
Also  we already use HTTP Compression 
It was enabled around V1.2.6.21 or so
