### ISSUE TITLE
[FEATURE REQUEST] Better telegram follow up

### ISSUE THREAD

**Issue by BroTastix** [taniman/profit-trailer#1552]
- Trend Changes:
Perfect as is.

- New Bought Coins:
If a new pair is bought (+amount), When a DCA is triggered and wich DCA is triggered.

- New Sells:
For every sell a message, Pairs, DCA and pending pairs.
Incl the amount, the amount of profit in %, , amount of DCA.

- Crash of PT software:
If the bot crashes, telegram message.

- Sum up
24h sum up with amount of profit in $ and %, amount of sells
weekly sum up with amount of profit in $ and %, amount of sells
Perfect scenario would be sending /weekly or /daily to telegram bot and we get the notification. Don't know if this is possible, an automated sum up after 24h should be possible to code from the bot.

Everything you'll need to be up to date from your smartphone, we could have a life. 
Just saying

**Comment by taniman** [comment]
We just announced out PT Notitifcation today. Coming with PT 2.0 PRO
I will archive this issuse. And any notifications related issues can be added to that project in the future
