### ISSUE TITLE
[Feature Request] - Sell coin after a predefined amount of time

### ISSUE THREAD

**Issue by JaySatthee** [taniman/profit-trailer#1553]
I discovered that my trades work only for a specific amount of time. 

So, lets say I got 10 hours to sell a coin. Thats the time frame in which my strategy works. 
If the coin can´t be sold in time, it should better be sold immediately, because the price is very unlikely to go up to my sell target in the near future.

It would be cool if we could set e.g.: NEOBTC_max_trade_duration = 600 (minutes)

**Comment by YoJeff** [comment]
Duplicate #366
