### ISSUE TITLE
BTC-GRS Buy/Sell Glitch

### ISSUE THREAD

**Issue by awhitford** [taniman/profit-trailer#1554]
I noticed an odd situation.  PT bought 57.7167263 BTC-GRS @ 0.00008663 around 4/4/2018 2:42:05 AM on Bittrex.  Then, it sold 12.62956788 BTC-GRS @ 0.00008634 around 4/4/2018 3:02:26 AM.  I see the remaining 45.08715842 in my DCA -- yet it doesn't know the Bought Price.

So I just used the Hot Config to specify the Bought Price, but I don't see it selling it (clearly in profit zone now).

But...  Why did it not know the Bought Price?  And why did it Sell at a lower price than the Buy Price?

I did see this in the log:
```
2018-04-06 18:41:28 INFO AverageCalculator - Please set BTC-GRS_bought_price
2018-04-06 18:41:28 INFO AverageCalculator - BTC-GRS - Possible avg 1 = 0.00008507
```

Also, do you have a recommendation?  Should I just specify a manual Sell now?

**Comment by taniman** [comment]
Gonna need you to upload your log file
