### ISSUE TITLE
Menu does not collapse in Samsung internet

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#1557]
You can't open the menu in Samsung's default webbrowser. It works fine in Chrome though, but also worked fine in version 1.2.6.25

Android 8
Samsung S8+

**Comment by djmeph** [comment]
I've reproduced this issue in Firefox for Mac OS, Firefox for Android, and Chrome for Android. The hamburger menu doesn't work when the screen collapses at the mobile breakpoint.

**Comment by TomBos** [comment]
Same here, on Android-Phone (Lenovo P2) it works. On Tablet (Huawei MediaPad M3) it doesn't. Both using Chrome.

Tried using "Desktopsite" but is does not make any difference.

Resolution of the Huawei is: 2560 x 1600

**Comment by dmelvin** [comment]
I have the same issue within chrome as well on my Samsung S8.   Opening via DNS entry does not work, the menu won't expand,  opening via IP address DOES work.

**Comment by giantpug** [comment]
it seems to have improved for me on samsung s8 via chrome, issues rectified themselves from around 12:00 bst with nothing changed on my bot or phone, weird.

**Comment by giantpug** [comment]
im opening via ip btw

**Comment by SgtBatten** [comment]
Clearing cache usually resolves this.

**Comment by TomBos** [comment]
Yup, that did the trick for me!

**Comment by timh77** [comment]
Indeed was a caching issue.
