### ISSUE TITLE
API Errors with V2 and Binance?

### ISSUE THREAD

**Issue by dillonm1075** [taniman/profit-trailer#1558]
![error](https://user-images.githubusercontent.com/36042371/39076338-9e07ee0e-44f2-11e8-8f4f-637caa934a73.jpg)

I'm getting these errors trying to start a V2 bot using Binance

**Comment by cryptojay2** [comment]
i'm having the same issues

**Comment by dillonm1075** [comment]
I've rolled back to v1 for now.  I'll wait till they've ironed out all the issues

**Comment by IceDHB** [comment]
Im also having these same issues, clean instal im hoping this will be fixed soon

**Comment by dillonm1075** [comment]
@gallivanmedia no it was a clean install. Two separate bots.

**Comment by cryptojay2** [comment]
I resolved my issue by coping cryptognome config settings and pasting them directly into config tab on the GUI .... i guess it didn't like my config settings.

**Comment by gallivanmedia** [comment]
@cryptojay2 Yeah, I tried CryptoGnome INDICATORS... it was working for a while, but Binance just gave me a 5 min. ban just now. Could it be in the PAIRS or DCA settings do you think?

**Comment by cryptojay2** [comment]
i'm new at this, but i just replaced the whole initialization folder with his. been trading for about an hour with no issues.
