### ISSUE TITLE
Config button/link disappear on GUI.

### ISSUE THREAD

**Issue by Devir71** [taniman/profit-trailer#1560]
It stays there only for 1-2 seconds and disappears. I tried changing the following line in application.properties file to TRUE and FALSE but it did not make any difference.

server.disable_config = false

**Comment by magisterh** [comment]
same problem:
server.enable_shutdown = true  (no button in GUI)
server.disable_config = false (no config in GUI)

**Comment by jmus109** [comment]
same problem here!

**Comment by magisterh** [comment]
OK, now I turned password on and the Config and Stop ProfitTrailer appeared.

**Comment by djcrypto75** [comment]
need password on.
