### ISSUE TITLE
DCA data table

### ISSUE THREAD

**Issue by js8749** [taniman/profit-trailer#1562]
Im having the following error:

DataTables warning: table id=dtDcaLogs - cannot reintialise DataTable. For more Information about this error please see Http://datatables.net/tn/3

Im running it in a raspberry pi

**Comment by js8749** [comment]
In the DCA tab

**Comment by js8749** [comment]
Its give that error when a dca pairs enter

**Comment by timh77** [comment]
I had that for the possible buy log but after restarting it was gone.

**Comment by maah75** [comment]
I also  have it for possible buy log

**Comment by arpty** [comment]
I have the same problem:
DataTables warning: table id=dtDcaLogs - cannot reintialise DataTable. For more Information about this error please see Http://datatables.net/tn/3

I am running on Windows 10.

I erase everything and start again and the problem continues.

**Comment by SgtBatten** [comment]
Were you all using V1 previously.

Does clearing the cache fix it?

Shift + f5 on chrome

**Comment by dmuzizian** [comment]
![screenshot_1](https://user-images.githubusercontent.com/15715474/39193600-25ca5dac-4806-11e8-99b8-e1d14c109931.png)

i'm not found solution for this problem :(

**Comment by arpty** [comment]
There most be something wrong with my DCA settings. I merge the default settings with the template from CryptoGnome.  I just delete all my settings and copy/paste the settings from CryptoGnow and now is working! Here is the file I used.

**Comment by SgtBatten** [comment]
Yes guys sorry i didn't come back to you. I am 95% sure its a config issue. I have solved several individual users with this issue by fixing problems with their configs. especially buy/sell strategies in the file which gives you this error.

**Comment by YoJeff** [comment]
Issue cleanse -- if this is still an issue with v2.0.5 resubmit with proper format.
