### ISSUE TITLE
We were unable to authenticate your license. Check your license and API key

### ISSUE THREAD

**Issue by aditya9787** [taniman/profit-trailer#1565]
Trying to run 2nd instance (and 3rd later) but i keep getting "We were unable to authenticate your license. Check your license and API key" This is on binance different accounts. API keys are activated and v1 runs fine with 3 instances. Has the number of bots you can run been reduced to 1 in v2?

**Comment by aditya9787** [comment]
One instance is working fine. For the second instance, I kept everything same except the API keys.


license = xxxxxxxxxxxxxxxxxxxxxxxx <---- Same for both instances
server.port = 8081
server.test_mode = false
server.sitename = Profit Trailer

trading.exchange = BINANCE
trading.log_history = 99999

server.timezone_offset = +05:30
server.language = engb
server.skin = dark
server.currency = USD

server.disable_password = false
server.disable_notification = false
server.disable_browser = false
server.enable_shutdown = true
server.disable_config = false
server.disable_online_config = true

server.start_trading_delay = 0

default_api_key = xxxxxxxxxxxxxxxx - changed 
default_api_secret = xxxxxxxxxxxxxxxxxxxxx - changed
trading_api_key = xxxxxxxxxxxxxxxxxxxxxxxxxxx - changed
trading_api_secret = xxxxxxxxxxxxxxxxxxxxxxx - changed

#timeout in seconds
connection.timeout = 30

**Comment by dmelvin** [comment]
"I kept everything same except the API keys."  

This, I believe, is the problem.   I believe the licenses are tied to the API keys that you provide when you made the initial purchase.   You'll need to contact support to link your licenses to the new API keys you created.
