### ISSUE TITLE
Rise trigger only resetting afer PT reboot

### ISSUE THREAD

**Issue by d0m1n0o** [taniman/profit-trailer#1570]
I was playing around with the rise trigger percentages, but then I decided to put them back to 0, and the bot got stuck in sell only mode. 
It only works again after rebooting PT.

**Comment by taniman** [comment]
please check the wiki faq. If you set these global triggers to 0 than indeed the bot will never come out of SOM and reboot is required. 
That's how the logic works currently

**Comment by taniman** [comment]
there may have been a small setting incorrectly for rise_trigger recover in the default files. So if you are using the default files. Try downloading the latest version or check the wiki
