### ISSUE TITLE
ConfigApi - Config could not be loaded from the rest api. Received message: 502

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1571]
subject. I'm getting it not regularly but often to create an issue

**Comment by angelsomar** [comment]
he showed me the dca for a few minutes and shows me nothing, no balance, no dca, no pair

only shows in terminal

2018-04-22 23:36:19 ERROR ConfigApi - Config could not be loaded from the rest api. Received message: 502

**Comment by taniman** [comment]
how are you running the bot? are you using something like nginx?

**Comment by jokaorgua** [comment]
Nothing. Just bot. Seems to me this is request to your cloud where you store settings.

**Comment by gh0st2017** [comment]
this error is fix?

**Comment by jokaorgua** [comment]
in 2.0.1 I don't see this error. thanks

**Comment by gh0st2017** [comment]
i use tow bot ,eth bot is ok ,but i startup btc bot is this error

**Comment by efurban** [comment]
similar error except 404: 
ERROR ConfigApi - Config could not be loaded from the rest api. Received message: 404

I think this is also the root cause of my PTMagic (coudn't load config)

**Comment by YoJeff** [comment]
Issue cleanse -- if this is still an issue with v2.0.5 resubmit with proper format.

**Comment by Forallatlantis** [comment]
I still have this issue. I'm using PT 2.0.13
I just installed everything from scratch, set up the api keys, and I put it on test mode ...
Need help
