### ISSUE TITLE
Shows pair as DCAed although it is not truth

### ISSUE THREAD

**Issue by xandorlv** [taniman/profit-trailer#1574]
<img width="960" alt="screen shot 2018-04-21 at 21 14 32" src="https://user-images.githubusercontent.com/17331835/39087414-5012dc2e-45a9-11e8-96d6-2271608df491.png">
<img width="1579" alt="screen shot 2018-04-21 at 21 14 20" src="https://user-images.githubusercontent.com/17331835/39087416-5038f4ae-45a9-11e8-9a32-c8fd6c6d05b8.png">

See attachments - show as if I have 3 DCA however in trade history it is bought only once today.

**Comment by SgtBatten** [comment]
Did you manually buy this coin?

**Comment by YoJeff** [comment]
Housecleaning.
