### ISSUE TITLE
Prevent PT from buying when it shouldn't (SMA, EMA, HIGHBB Crosses)

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer#1577]
In reading your latest PT 2.0 Wiki, it seems there is still some disagreement between what is being said here and what the Wiki authors believe is the case when it comes to being able to buy based on an EMACROSS in the current candle (1), as well as the same principle being applied to HIGHBB to avoid buying well after the initial 0% cross point.

For instance, it states...

"EMA_cross_candles = 5 → DEFAULT_A_sell_value = 0.6 → sell strategy is true when the calculated spread is 0.6% or larger (Fast EMA is HIGHER than Slow EMA) and the Fast EMA crossed above the slow EMA within the last 5 candles (excluding the current candle)."

They still seem to believe the current candle is excluded.  Just pointing out, as it is confusing.

While I was able to recently create my own program to do all of the things I've been describing here in my "EMACROSS- buying on the drop" (#1477), "EMACROSS from candle 0" (#1376), and "Implement check for buy strategies for when the actual trigger happened" (#1251)...its not going to be ready for any public consumption until I get all of the code migrated into Java, but the logic works programmatically in my own personal trading environment.

You asked in one of these posts above (all closed at this point) how it could be accomplished, programmatically and logically.  Well here's how I did it and I think this would be great if such techniques could be integrated into PT (for SMA, EMA, and HIGHBB crosses) without my having to create secondary applications to do the validation work necessary.  I'm using an EMACROSS example, but I've applied the same concepts for HIGHBB and of course applies to SMACROSS as well...

EMA_cross_candles = current candle
DEFAULT_A_buy_value = 0
Current Fast EMA =Current Close Price*(2/(3+1))+Previous Fast EMA*(1-(2/(3+1)))
Last Fast EMA =Last Close Price*(2/(3+1))+Last Fast EMA*(1-(2/(3+1)))
Current Slow EMA =Current Close Price*(2/(24+1))+Previous Slow EMA*(1-(2/(24+1)))
Last Slow EMA =Last Close Price*(2/(24+1))+Last Slow EMA*(1-(2/(24+1)))

1) If the EMACROSS strategy status = "Inactive", then proceed to validation step 2.

2) If the Last FAST EMA <= Last SLOW EMA and the Current FAST EMA > Current SLOW EMA, then a simple EMA cross UP has just occurred.

3) If any Close Price, in the range of the last 15 minutes of Closing Prices (assessed using tick by tick prices over the last 15 minute period, not including the last two ticks), was >Current Close Price + expected Take Profit Amount...then price is coming back down from previous higher trend and it is not safe to buy.  If that condition was false, it is safe to assume the price direction is currently TRENDING UP and not down.  The 15 minute period a variable that can be changed, of course.

Example Formula:  'Price Action'!B5:B34>'Price Action'!B3+(sell_value/100*'Price Action'!B3)

4) If conditions 1-3 above are favorable toward an upward cross, then trigger the Buy and set EMACROSS strategy status to "Active".

5) If price reaches GAIN sell_value goal and sells at a profit, leave the EMACROSS strategy status as "Active" for now.

6) If the price does not reach the GAIN sell_value goal, but rather dips down to the point that the FAST EMA touches/crosses the SLOW EMA again...check to see if the minimum profit value has at least been reached (for EMACROSS down sell strategy).  If in profit, then sell and leave the EMACROSS strategy status as "Active" for now.

7) Once the FAST EMA drops 2% below the SLOW EMA again (the % should be configurable, of course), if there is no trade currently open for this pair...then set the EMACROSS strategy status as "Inactive".  Now it is ready to start looking for new EMACROSS buying opportunities again, unless there was still an open trade for this coin...in which case the normal DCA would apply with whatever strategy is configured for that.

These conditions above this will prevent PT from ensnaring us traders into the following bad trade types:

a) Buying a coin at the top of a trend (just before it crumbles, thereby taking us down for the ride with it), simply because it just happens to be above the EMACROSS, SMACROSS, or BBHIGH  0 cross point.

b) Buying a coin as its price is already in free fall, simply because it just happens to be above the EMACROSS, SMACROSS, or BBHIGH  0 cross point.  Yes, the buy value limit feature of PT can help with this when using EMACROSS or SMACROSS...but not with BBHIGH and there is also that chance the price will skip right over a tight buy value limit- so, missing a good buying point entirely.

c) Buying a coin after it has already made its move up and then back down again, but happens to be in a brief range over and under the EMACROSS point...essentially buying in after the initial trend has died and price is either flat or dropping at this point.

These are problems that currently exist with PT, which make it so that I can't safely trade using the EMACROSS, SMACROSS, or HIGHBB buy strategies in PT and have had to create another program to supplement PT to avoid these dangerous pitfalls.  If rather prefer this type of safeguard be built into PT itself.  Saves us time having to program it ourselves without pay. ;)

**Comment by taniman** [comment]
No new feature requests allowed in this project. 

Ema cross does not excluse the current candle and we will change the documentation accordingly.
@SgtBatten
