### ISSUE TITLE
Sell only mode doesn't work

### ISSUE THREAD

**Issue by cas8180** [taniman/profit-trailer#1578]
SOM doesn't appear to be working in v2. Set in pairs file and hotconfig the UI never updates the SOM status to true.

**Comment by SgtBatten** [comment]
Hotconfig is not the right place to set this. Please confirm what parameter you are entering into config > pairs in the GUI.

**Comment by SgtBatten** [comment]
You can only edit the pairs file using the GUI.

as i said earlier you cannot enter this in the hotconfig. Hotconfig is for 3 parameters only.

PLease tell me exactly what you are writing and where. screenshots would help

**Comment by YoJeff** [comment]
Run through support on discord first.  This is for bugs.

**Comment by cas8180** [comment]
You guys need to offer better customer service than this. Find attached a screenshot
[cid:2f66e7ab-1c3c-487c-9753-be7b9ee4e187]
________________________________

**Comment by SgtBatten** [comment]
Nothing attached

**Comment by cas8180** [comment]
![image](https://user-images.githubusercontent.com/1483688/39261179-895e800e-4870-11e8-898f-8b75314fb5c8.png)

**Comment by cas8180** [comment]
legacy version aka 1.x which I had to rollback too:
![2018-04-25_1009](https://user-images.githubusercontent.com/1483688/39261331-fe1a8712-4870-11e8-845b-ff494483f7d4.png)

**Comment by YoJeff** [comment]
You get better support when you actually use support.  This isn't support.    Parameter names matter, ALL_sell_only_mode does nothing in V2.
