### ISSUE TITLE
Specify a Gain

### ISSUE THREAD

**Issue by larrybtm** [taniman/profit-trailer#1579]
I get SPECIFY A GAIN under Sell Strategy. 

Pairs file:
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1
DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 40
DEFAULT_trailing_profit = 0.16

<img width="998" alt="screen shot 2018-04-21 at 23 53 55" src="https://user-images.githubusercontent.com/24433284/39089442-754f40b8-45c7-11e8-881f-fe595df34395.png">

**Comment by aditya9787** [comment]
DCA.properties has a different syntax now.

DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 0.5
DEFAULT_DCA_trailing_profit = 0.05

**Comment by larrybtm** [comment]
Thanks!
