### ISSUE TITLE
not able to view any logs from mobile device

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer#1580]
The menu does not seem to work on my phone.

Google Pixel XL running latest android 8.1

I can only view the dashboard

**Comment by knowngate** [comment]
Mine is mi a1 device
I too not able to access the pairs dca pairs n stat data on mobile

**Comment by djcrypto75** [comment]
Try with Chrome and Firefox? Cleared cache?

**Comment by orty87** [comment]
Same here but it is a bit strange.

When I access the dashboard locally via IP it works. If i try to access pt via Internet with dyndns the dashboard opens normally but I cant open the menu. In prevous versions it worked perfectly.

**Comment by timh77** [comment]
#1557

**Comment by SgtBatten** [comment]
Clearing the cache fixes this issue as far as I have seen. Myself included.

**Comment by YoJeff** [comment]
Issue cleanse -- if this is still an issue with v2.0.5 resubmit with proper format.
