### ISSUE TITLE
Keep Balance calculation

### ISSUE THREAD

**Issue by MrS1n1st3r** [taniman/profit-trailer#1581]
I want all of my buys to be of the same number.

The release notes say: when doing a initial buy using a percentage, previously it would buy 2% of 1 btc ignoring your min_buy_balance of 0.4btc but now with the renamed keep_balance if will buy 2% of 0.6btc

That means that now, each buy would be les than the previous.  Is there a way to set it so it STILL calculates cost over TCV and not over TCV MINUS KeepBalance?

**Comment by SgtBatten** [comment]
It does not mean it will be less than previous. As far as the logic works it is exactly the same as v1.

Difference is this.
In v2 it buys 2% of TCV- keepbalance.
In v2 it buys 2% of TcV

Keepbalance is a fixed amount or percentage.

**Comment by MrS1n1st3r** [comment]
You're right, it is fixed, but...v1 it buys % of TCV, period.  Now it buys % of TCV-keepbalance.  So it buys less.  But my keepbalance changes depending on market condition. so I guess its a matter if also having an offset for cost AND upping it from hat it used to be, to buy the same number.
