### ISSUE TITLE
Hotconfig to set the bought price is not working

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1582]
Hotconfig to set the bought price is not working.

I created 10 manual pending orders for ELFETH in my exchange to dilute my bag of ELFETH. When I cancel 1 of the 10 orders, the bought price of ELFETH became the marketprice .

[PT DCA Log](https://cdn.discordapp.com/attachments/406439964356640768/437422722826502154/unknown.png)

I set the bought price below but it didn't changed the value (See above)
ELF_reset_stored_average = true
ELF_bought_price = 0.00197833

I tried restarting and try again but it didn't work.

**Comment by dreadddy** [comment]
i am also having this issue with WTCETH

**Comment by dreadddy** [comment]
@cybermizrach i got it to work.
set the _DCA_set_buy_times = to anything but 0
If this changes then try setting the bought_price to something really high.
If this changes then you should be fine to set it to the right price and then set the _DCA_set_buy_times = to what you want it to say

**Comment by cybermizrach** [comment]
@dreadddy  Thanks! I'll try this again if I have a new deep bag.

**Comment by YoJeff** [comment]
>I created 10 manual pending orders for ELFETH in my exchange

I have no idea how the bot would even deal with this.   This is what DCA is for...

**Comment by cybermizrach** [comment]
> I have no idea how the bot would even deal with this. This is what DCA is for...

My ELFETH bag was too big. I need to split the bag into 10 and let the DCA do it's job. You may check the dillusion bag DCA strategy for more details
