### ISSUE TITLE
Bot Making Small buys and Throwing an Error

### ISSUE THREAD

**Issue by CryptoHunter44** [taniman/profit-trailer#1583]
My Bot keeps making small $10 dollar buys. After they sell they amount does not show up in my Sales Log or in my Dust Log. However, If I log into my Bittrex account I can see the sales. I'm also getting an Error when this happens. Bot says I have "insufficient funds". I attached two photos of the issues.
![bot error 2](https://user-images.githubusercontent.com/38597990/39090816-ad00c434-45b6-11e8-9619-b77491be2e0e.jpg)
![bot error](https://user-images.githubusercontent.com/38597990/39090817-afbfc7e2-45b6-11e8-9b42-c0e6287c82b5.jpg)

**Comment by taniman** [comment]
I will need your actual log file as this screenshot is not showing any buys.

**Comment by CryptoHunter44** [comment]
Hi,

Sorry for the delayed response. The issue has been resolved it and it was
an error on my end. I apologize.
