### ISSUE TITLE
Sell Strategy trigger( SST ) col  is hiding in Date Column When true trailing 

### ISSUE THREAD

**Issue by sas7085** [taniman/profit-trailer#1584]
Hi 
The SST column is coming under Date column when there is true trailing  for DCA pairs.  It might be due to the space issue it is done like this .

If need to check what is the Sell Strategy trigger then need to go to Date col click that plus button then it will be displayed. if only "trailing.." will be displayed then it  will be sufficient. 

But it is not necessary to show "true trailing ....." in the Sell column. It will be enough  if mentioned as "trailing" .

**Comment by YoJeff** [comment]
This is by design.   Tradeoffs must be made when accommodating small screens.
