### ISSUE TITLE
SOM is not turning off once the BTC price recovered

### ISSUE THREAD

**Issue by sas7085** [taniman/profit-trailer#1585]
Hi

The SOM triggered based on price_rise_trigger  is not turning off once BTC  price is equal or less than price_rise_trigger_recover  value .  Need to restart the PT to remove SOM . This is related to the BTC price % displayed in the top of the first screen.

**Comment by agaji** [comment]
had the same issue occur. had to restart

**Comment by miladzamani** [comment]
same issue . need restart the bot

**Comment by SgtBatten** [comment]
One of the files had the parameter backwards.

So your price_rise_trigger_recover needed to be price_rise_recover_trigger to work

**Comment by zigzag-way** [comment]
The same problem with ETH. Since SOM turned ON it never turns OFF
