### ISSUE TITLE
Sorting PBL on mobile does not work correctly

### ISSUE THREAD

**Issue by Fransenson** [taniman/profit-trailer#1587]
LIn V1 when I sorted the PBL by buy strategy it showed the ones trailing at the top, followed by the ones with a strategy followed by the ones that are disabled (In V1 with SOM)

Now the sorting is not as coherent. It shows anything with a true indicator at the top, sometimes the top entry has less true indicators than ones further down. Also the ones being disabled through max change percentage show up between actual possible buys. 

Would be neat to have the sorting be:
Trailing
Most true strategies
Strategies
Disabled(SOM/Max change...)

On some occasions sorting by buy strat does not change the pbl at all

**Comment by djcrypto75** [comment]
It is working as intended by design.
