### ISSUE TITLE
Settings not stored

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#1589]
Trying to fine-tune my settings so changing bits and pieces and then verify the behaviour in the pairs/dca log. Sometimes the changes become visible within seconds, sometimes never. When opening the settings it seems the changes have never been stored. New lines and changed values are missing. However after clicking the save button I always received a success notification.

Firefox 59.0.2 / PT 2.0

**Comment by SgtBatten** [comment]
I need to contact form you are on my looking in the GUI when you are talking about settings here 

Changes made to application.properties are the only ones that can be made in a text editor.

Pairs, DCA and indicators must be edited using the GUI and the files in the Initialization folder are not linked in any way. They are used for the initial bootup only and after that an encrypted copy is used.

**Comment by timh77** [comment]
@SgtBatten I changed the settings in the GUI, Saves it and went to for instance the possible buy log checking the result of the changes. Nothing happend. When opening the settings in the GUI again it was still the old version, none of the changes were saved. It happened a few times but the last few it went ok.

**Comment by YoJeff** [comment]
There have been several releases since the last activity on this issue.   If this is still an issue with v2.0.5 resubmit with the proper format.
