### ISSUE TITLE
Data file corruption error

### ISSUE THREAD

**Issue by smportis** [taniman/profit-trailer#159]
The data file is being truncated for some reason, causing a loss of critical data, and an error on restart of the application. 

In my case, it truncated in the pendingLogData area. 

Perhaps during shut down from pm2, it is not cleanly writing the data file before shutting down? 

Of note, I'm using 'pm2 m' to monitor the log file, and having to stop that process before I can do a 'pm2 stop 0' to shut down the bot. 

If anyone else has input to this, please contribute to help solve the problem.

**Comment by taniman** [comment]
seems to be going better with newest release
