### ISSUE TITLE
Changing settings on Android: for every changed/added character the one before the cursor is removed

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#1590]
Can be reproduced in every Android web browser I tried (Samsung Internet / Chrome / Firefox).

Put the cursus somewhere and after adding one character you will notice the character before the cursor is being removed. Add a second character and you will notice the same. Add a third character and nothing is removed. This behaviour repeats itself.

Android 8.0 / Samsung S8+

**Comment by Fogazi** [comment]
This has annoyed me from day one of having gui settings

**Comment by timh77** [comment]
Same for me. Hoped it would have been solved in v2. ;-)

**Comment by SgtBatten** [comment]
yes been around for a while, my personal experience is when pressing SHIFT it deletes a character. so i press space first, then shift every time.

Thanks for the feedback guys

**Comment by djcrypto75** [comment]
This is because of Samsung keyboard, so we tested by installing third party keyboard (GBoard). The UI was fine when we used editor with GBoard. This might be an issue with Samsung device default keyboard.
We tested this issue in other Android devices also but it was only reproducable in Samsung devices.

**Comment by timh77** [comment]
Not entirely true...

It might be reproducable with Samsungs default keyboard, which I don't use, but it's also reproducable with Swiftkey which is a populair keyboard on Android...

**Comment by SgtBatten** [comment]
I also do not use Samsung board I use Google keyboard.

**Comment by timh77** [comment]
By the way... I installed GBoard and reproduced the same issue. So it seems it's not related to the keyboard app.

**Comment by SgtBatten** [comment]
SwiftKey board deletes the preceding character for each character typed.

Google board deletes the preceding character whenever shift key is pressed.

Samsung board has a strange visual glitch but actually seems to work correctly for me
