### ISSUE TITLE
error openorders / completeBalance / Tradehistory

### ISSUE THREAD

**Issue by intemr** [taniman/profit-trailer#1593]
Any ideas guys? PT2.0 @ bittrex
<img width="1678" alt="1" src="https://user-images.githubusercontent.com/38623588/39096472-d717422e-4693-11e8-8224-4e2063750c34.png">

**Comment by ricardodacosta** [comment]
Am also seeing similar errors such as:

- ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60
- ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
- ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in

**Comment by upthedownstairs** [comment]
Same issue here.

**Comment by Richo005** [comment]
Having the same issue

**Comment by SgtBatten** [comment]
Just a reminder this is a huge priority for us. As mentioned above we need to change our API method for bittrex as they changed how they want us to connect to them. We are working on this.sorry for the issues

**Comment by YoJeff** [comment]
Merge #1873
