### ISSUE TITLE
HIdden pairs still showing up and trading. 

### ISSUE THREAD

**Issue by dmelvin** [taniman/profit-trailer#1595]
LInux Ubuntu Server 16.04 x64

From my pairs config:

enabled_pairs = ALL
hidden_pairs = BNB, XRP, SUB, BCD, STORM, BCC, BTG, ETH, LTC, STRAT, CTR, ETC

Although BNB, XRP, BCC, and BTG are listed under hidden, they're still showing up, and I have now confirmed that they are trading.    I really don't want to go through and add every pair but these to then enabled list, but I can if that's what I have to do for now.

**Comment by cobraxp** [comment]
I ended up doing this and it seems to work BNB_trading_enabled = false

**Comment by dmelvin** [comment]
I pulled those settings from my old v1.2 settings, I think "default" is in front of it though.   I'll edit that and see what I get.  Thanks!

**Comment by SgtBatten** [comment]
As per the wiki entry for  hidden_pairs this parameter O my hides coins that are listed if they are disabled from trading also.
