### ISSUE TITLE
Remote Web Gui not loading. PT 2.0

### ISSUE THREAD

**Issue by Stogy** [taniman/profit-trailer#1597]
I have PT 2.0 running in testmode. All is well in the log file, I can see the Gui on my VPS. No errors. For some reason I cannot see it on my local machine with the vps ip etc. The GUI comes up fine with PT 1.26 on my local machine. PT 2.0 I just get the GUI loading wheel. Password has been set API entered etc. I am stumped. To reiterate I can switch back and forth between PT 2.0 and PT 1.26. I see the 1.26 on my remote web session, PT 2.0 just shows loading screen for ever.

**Comment by Stogy** [comment]
Figured it out. It was the GUI script that was running via cjs in the background. Turned it off. Now Gui loads just fine.

**Comment by Monsta1** [comment]
Hi, I am having the same issue. After upgrading from v1 to 2.1.8, uploading to VPS and entering the password I just get the GUI loading wheel, Both PT versions work on my desktop computer but I cant get V2.1.8 to load on my VPS. How did you solve it? Sorry, I am complete newb to this and dont know where to finf the GUI script you refer to. Thanks!

**Comment by SgtBatten** [comment]
@Monsta1 tour issue is different.

You are using internet explorer or Microsoft edge I am 99% sure. Use  Chrome or Firefox and it will work.

**Comment by Monsta1** [comment]
Initially, I had the GUI not loading on chrome. I have deleted chrome and tried running pt on internet explorer with no luck. Now, after reading your comment, I have downloaded and installed chrome again - ant it works! strange. Thank you for your help!!!

**Comment by djcrypto75** [comment]
Internet Explorer is just not a good browser and also not really supported :)
