### ISSUE TITLE
ERROR Util

### ISSUE THREAD

**Issue by Xeckin** [taniman/profit-trailer#1599]
ERROR Util - Unable to retrieve latest settings null.  It just keeps spamming the cmd window.  No idea what caused this.
![ptwhat](https://user-images.githubusercontent.com/31871098/39105193-821d711e-4682-11e8-8d05-c19a1b0cc563.jpg)

**Comment by taniman** [comment]
are you saying it was running fine before?

**Comment by Xeckin** [comment]
Yes I turned it off and restarted the bot still no go.

**Comment by Xeckin** [comment]
Ive tried this on my local network and VPS.  I also tried stock files as well.

**Comment by Xeckin** [comment]
Changed API keys with no success

**Comment by Forallatlantis** [comment]
Encounter the same problem and with new API there's no script working, same error
Need help

**Comment by taniman** [comment]
@Forallatlantis I advise you to contact our support in discord.

**Comment by bartgrefte** [comment]
I just started running into this error as well (for about an hour or so), tried restarting the bot, now it won't start because it can't reach the ProfitTrailer license server. Are the two errors related?
