### ISSUE TITLE
Daily profit display in Monitor

### ISSUE THREAD

**Issue by jadiesel** [taniman/profit-trailer#160]
I just noticed, as the time rolled past midnight UTC tonight, that the daily profit reset to 0.   My sales logs are all fine (I'm UTC -4) but that daily umber definitely reset at UTC 00:00

That also got me to thinking - daily profit for 'today', or should it be a rolling last 24 hour profit? That would align it with the sales logs, wouldn't it?

And of course, yesterday would be 24-48 hours ago - and weekly would be by last 168 hours.

or not. Just pointing out that the metrics are not consistent ;)

**Comment by taniman** [comment]
yes, you were right. pretty inconsistent. So changed now to only show days. not 24 hours but today, or last 2 days etc. So make it consistent with monitoring main screen
