### ISSUE TITLE
What happens when EMACROSS buy/sell value is 0?

### ISSUE THREAD

**Issue by horu23** [taniman/profit-trailer#1600]
In the previous version of PT
when buy strategy = EMACROSS and buy value = 0,
buy occurred when fast EMA goes over slow EMA.

Is it also true in V2.0?

Plus, what happens when sell strategy is EMACROSS and sell value is also 0?
Would the sell trigger activate when fast EMA goes under slow EMA?

**Comment by SgtBatten** [comment]
If you were to set 0 for buy and sell they would both be true at the same time when the fast line crosses above the slow line.

See this link https://wiki.profittrailer.com/doku.php?id=buy_and_sell_strategies#emacross

This can be discussed further in the strategy channel or setup channel on discord.
