### ISSUE TITLE
MACD Parameters doesn't work (or I may use it wrongly?!)

### ISSUE THREAD

**Issue by ARNA001** [taniman/profit-trailer#1603]
Hi There,
I'm looking to how to use MACD strategy in pairs, I used many different numbers in DEFAULT_A_buy_value but it didn't work. There are many articles say signal buy will generate between -0.1 and -0.3, I also used the sample in Wiki (DEFAULT_A_buy_value = 0.0000002 → Triggers “true” when the calculated value of MACD is 0.000000200 or greater. DEFAULT_A_buy_value_limit must be greater than 0.0000002 if used. ) but still is not working or even if it shows some coin is match with MACD is not correct ...

**Comment by SgtBatten** [comment]
Are the coins returning an MACD BSV ? Any screenahits?

**Comment by eatudor** [comment]
Support have confirmed "MACD doesn't have a cross logic behind it.  It is true whether trending up or down"

Can this please be fixed?

**Comment by taniman** [comment]
Adding a trending logic to macd i consider a new feature. I will add it to the list of enhancements and see what we can do.

But currently macd works like all our other strategies. We do not check the direction of the trend.
