### ISSUE TITLE
Trailing is ON when indicators are not in needed range

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1608]
<img width="1590" alt="2018-04-23 12 01 28" src="https://user-images.githubusercontent.com/5228422/39120492-e1db0e60-46ee-11e8-80bb-fecce7c76b91.png">

I have like this right now. Bot restart fixed the problem

**Comment by SgtBatten** [comment]
Once the coin is trailing the indicators are ignored. Only the price going back over the price it started trailing at (or restarting as you did) will stop trailing.
