### ISSUE TITLE
When dca average is done bot didn't show any count .

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer#1609]
Hi
Pt bot is doing dca but it is not displaying any count on screen.
I done mannualy setting in hot config for the count.

**Comment by SgtBatten** [comment]
You are saying after an initial buy, and then a subsequent butt the number still doesn't change to 1?

Please provided more.for us to work with. Screenshots, logs, purchase information. Etc

**Comment by knowngate** [comment]
![aa](https://user-images.githubusercontent.com/9782164/39122505-c422b5f2-4712-11e8-9b9a-72c2d7308c38.png)

**Comment by SgtBatten** [comment]
Please upload log file

**Comment by knowngate** [comment]
i opt out my rsi settings in dca coz it is not doing dca and coins keep falling lower low.
#DEFAULT_DCA_B_buy_strategy = RSI
#DEFAULT_DCA_B_buy_value = 28.5
#DEFAULT_DCA_B_buy_value_limit = 15

**Comment by knowngate** [comment]
[Uploading ProfitTrailer.log…]()

**Comment by JHenneberg** [comment]
this is definetly true. I also was checking my DCA counters. Its not just that sometimes he is not counting. It also happens that he is counting one more then he actually bought.

**Comment by d1rt** [comment]
I have the same problem. Some counters dissapear. Binance ex.

**Comment by Mikeeetrue** [comment]
It doesn't work in testmode as well

**Comment by YoJeff** [comment]
Merging #1857
