### ISSUE TITLE
[Feature Request] - Exchange sell Log importation for manual sells

### ISSUE THREAD

**Issue by BroTastix** [taniman/profit-trailer#1610]
Purpose: 
Add all sells made on the exchange with profittrailer, automaticly and manualy made sells.

My point of vieuw:
-> Create a database of all trading info off the exchange.("Exchange database")
-> Compare it with the exsisting "PTFeeder database"
-> Put pairs in a database that are present in "Exchange database" and "Ptfeeder database"
-> Compare those with the active pairs/DCA and existing Sell database of Profit Trailer.
-> Update "Exchange database" (API)

Hope this sounds possible!
Or sparks an idea

**Comment by zwarbo** [comment]
+1 
PT to track sales made manually on the exchange with base pair.

**Comment by SgtBatten** [comment]
Please post feature requests here:

https://github.com/taniman/profit-trailer-enhancements
