### ISSUE TITLE
Discord Notification Font size  for Rate & Cost are very  Small to read in Cell Phone

### ISSUE THREAD

**Issue by sas7085** [taniman/profit-trailer#1614]
Hi 
This is not a bug . But this can be addressed for better usability purpose. 
The Discord notification added in PT 2.0 is a great value add. 

The notifications header information (BINANCE BTC , Just bought: XMRBTC ) is having good font size But the Details Cost & Rate is having tiny font size. In desktop  Discord version is not an issue to read the Cost and Rate but in Cell Phone it is not possible to read. 

If possible please increase the Font size of Cost & Rate to Font size of header information {Just bought}

![image](https://user-images.githubusercontent.com/36013435/39146239-36feb6fc-4704-11e8-8eb4-90b9ea0f655e.png)

**Comment by YoJeff** [comment]
Active bugs only here please.

**Comment by sas7085** [comment]
Please Keep this in Parking Lot
