### ISSUE TITLE
RSI Frozen

### ISSUE THREAD

**Issue by msaleh3000** [taniman/profit-trailer#1615]
I just upgraded from V1.2.6.25 to V2.0 and the RSI indicator is frozen. it is stuck at the value that I started the bot at and doesn't move although I can see it moving on Trade View. This is preventing buying and selling. I'm Also using EMAGAIN for buy strategy_A and the RSI is buy strategy_B.
I had to comment it out so the bot would work and it is working without it. I'm on Poloniex if this makes a difference.

**Comment by SgtBatten** [comment]
please screenshot your pairs.properties in the GUI

**Comment by msaleh3000** [comment]
Here it is: all the settings did not fit in one screen shot so I did it in 3 : 

![pairs1](https://user-images.githubusercontent.com/8343562/39159958-a52e218a-4736-11e8-8e91-c6eedfad7d31.jpg)
![pairs2](https://user-images.githubusercontent.com/8343562/39159959-a5396004-4736-11e8-9f52-92a5d708eea0.jpg)
![pairs3](https://user-images.githubusercontent.com/8343562/39159960-a54641d4-4736-11e8-869a-d30b2c6a2a21.jpg)

Thanks.

**Comment by SgtBatten** [comment]
I will need to see indicators also please

**Comment by YoJeff** [comment]
RSI strategy is not active??

**Comment by YoJeff** [comment]
Closing.  Create new issue if this problem still exists in 2.0.3.
