### ISSUE TITLE
No Heartbeat in GUI

### ISSUE THREAD

**Issue by msaleh3000** [taniman/profit-trailer#1616]
I only see on heartbeat in the GUI which is the first heartbeat in the console and then nothing!
Although I can see in the console that there is heartbeat and the bot is working.

**Comment by SgtBatten** [comment]
please provide screenshots and your application.properties settings excluding sensitive data like API keys and license

**Comment by msaleh3000** [comment]
Here it is:
[application.properties.txt](https://github.com/taniman/profit-trailer/files/1940436/application.properties.txt)
![scr1](https://user-images.githubusercontent.com/8343562/39159778-79adcfb6-4735-11e8-99cc-af1fa2af31de.jpg)
![scr2](https://user-images.githubusercontent.com/8343562/39159779-79ce7a9a-4735-11e8-851f-76a5719ab7e1.jpg)

as you can see the console has heartbeat but it is not displayed in the GUI.

**Comment by emx0r** [comment]
same

**Comment by SgtBatten** [comment]
are you using PTNotifications

**Comment by YoJeff** [comment]
There have been several releases since the last activity on this issue.   If this is still an issue with v2.0.5 resubmit with the proper format.
