### ISSUE TITLE
Why this API errors? Call to GetOrderHistory was throttled. Try again in ...

### ISSUE THREAD

**Issue by ricardodacosta** [taniman/profit-trailer#1617]
Anyone knows why Im getting all these API errors from Bittrex? My telegram not is filled with 100s of this every day:

PTREX2:
1 BITTREX BTC ERROR: ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i

PTREX2:
1 BITTREX BTC ERROR: ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in

PTREX2:
1 BITTREX BTC ERROR: ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60

**Comment by keithofaptos** [comment]
I also have been having this problem. Sometimes it happens other times it doesn’t.
I’m on v1 still. When this occurs it doesn’t let my pairs log load on GUI. But at some point PT will buy or sell and then the process either continues or doesn’t. This wasn’t happening before v2 came out.has bittrex changed any of there perimeters?

**Comment by kj3407** [comment]
I am having the same problem, I wish someone would address this, I am using V1 until this gets fix, don't know whats going on, I was working on my bot for 6 hours sunday, not happy

**Comment by jmus109** [comment]
Same here but using v2. I also had it on v1. -Bittrex bot

**Comment by keithofaptos** [comment]
maybe useful to ask: https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial) <https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial)>

<thebotguy@protonmail.com <mailto:thebotguy@protonmail.com>>

separately :

there was something about bitter thrilling non corporate account as of 2 weeks ago on PT’s GitHub i read today also….

let me know if you figure it out.

**Comment by keithofaptos** [comment]
issue #1567 ,and taniman added to v2.0.1 10 hrs ago. so PT devs are aware of it.

**Comment by ricardodacosta** [comment]
thanks @keithofaptos !

**Comment by keithofaptos** [comment]
https://stackoverflow.com/questions/40748687/python-api-rate-limiting-how-to-limit-api-calls-globally <https://stackoverflow.com/questions/40748687/python-api-rate-limiting-how-to-limit-api-calls-globally>
