### ISSUE TITLE
Pairs, DCA and PBL no records found after update

### ISSUE THREAD

**Issue by Babidi314** [taniman/profit-trailer#1618]
Just updated to V2.0. Bot starts fine and shows good heartbeat. Monitor shows balance and sales logs shows sales from V1. But Pairs, DCA and PBL are empty ('no records found'). 

server.test_mode = false 

How to fix?

**Comment by gchiham** [comment]
Me too i get the same prob.

**Comment by YoJeff** [comment]
Support issue -- this is for bugs only.
