### ISSUE TITLE
Show currently used settings name in Web GUI

### ISSUE THREAD

**Issue by smoochy** [taniman/profit-trailer#1619]
Heya,

if you set the name of the settings during the initial startup process, and never see it again, the chance is very high you will forget about it. 

That is what happened in my case. I set a name, never used it again, as it is not shown anywhere.

Now I am in the need of this settings name (PTMagic setup) and can not find it anymore. 

I checked the PT logfile and pm2 server logfile.

When the bot is restarted, it is not shown in the log file

1) How can I reset the name of the setting and set a new one?

I found a way:

- save your current settings (pairs, dca, indicators) into files into your computer and upload them to the initialization folder of PT
- set _server.disable_online_config = true_ in applications.properties
- restart pt
- a file name "offlineData" will be created inside pt folder
- stop pt
- delete offlineData file
- start pt
- you will be prompted to  set a new password, confirm your api key
- next step is you will be prompted to set a new name for the settings
- set _server.disable_online_config = false_ if wanted
- restart pt if needed

2) Would it be possible for you to show it somewhere in the GUI? Maybe hidden behind the cogwheel icon where you log out and change the password?

Cheers.

**Comment by djcrypto75** [comment]
We will add the possibility to create, edit, delete and switch settings soon. Its in the works :)
