### ISSUE TITLE
For USDT, Match the Exchange's Level of Precision for Price.  Do Not Round to the Nearest Cent.

### ISSUE THREAD

**Issue by chiznat** [taniman/profit-trailer#1621]
"Armchair Guru - Today at 4:36 PM
Heya Chiz, i got an answer for you...
no the bot does not round out to extra decimals behind the scenes.... just 2
so 1.25 .....not 1.25837453"

This makes a huge difference to those trading coins under $1 and if STR on Poloniex is at 0.37004195, I want that exact price displayed and used in calculations.  According to support, it currently is not being used.  
Binance uses 3 digits for USDT, Polo uses 8 just like btc values...  Cast it and please no rounding.

**Comment by SgtBatten** [comment]
what he meant to say was behind the scenes it goes to 8 decimals. on the gui two because during the beta 8 decimals looked ugly i think.

we can look at changing it back though perhaps

**Comment by chiznat** [comment]
Please change the display to match precision and trim trailing zeroes if the display looks odd.  As someone who trades USDT, I really want to see those values versus  0.39 and 0.39 for bought price and current price.  I wasn't sure if it was truncating or rounding.

**Comment by djcrypto75** [comment]
Will be fixed in next release.
