### ISSUE TITLE
"All PRO users can benefit from a discounted rate on additional API key slots for their licence."

### ISSUE THREAD

**Issue by DjangoReinhardt** [taniman/profit-trailer#1625]
Please, oh please, provide your loyal users/ fans, who are migrating to v.2, one of the following:

1.  The four instances that we enjoyed through v.1 (I, myself, invested in four dedicated NUCs to run my PT instances).

2. Provide functionality that would allow for different pair markets (BTC, ETH, USDT) to be traded on one exchange, on one instance of PT and segregated virtual sums within PT for the same pair market (50% ETH bucket A with strat A, 50% ETH bucket B with strat B).

3. A reasonable flat fee (perpetual use) option for up to 3 additional API slots (again, for the v1 crowd) as early adoption of PT, complete with a license that you own for life was certainly a motivating factor in getting involved with the PT community.

**Comment by keithofaptos** [comment]
+1

**Comment by SgtBatten** [comment]
1. If you bought before 14 Feb you still have 4 APIs. Nothing changed there 

2. Use the enhancements repository for feature requests.

3. Additional API slots are most likely to be a monthly cost in accordance with the current payment model.
