### ISSUE TITLE
2 strategies are not working with trailing

### ISSUE THREAD

**Issue by BOBALLEX** [taniman/profit-trailer#1628]
DEFAULT_A_buy_strategy = LOWBB
DEFAULT_A_buy_value = 0
DEFAULT_A_buy_value_limit = -30
DEFAULT_B_buy_strategy = RSI
DEFAULT_B_buy_value = 35
DEFAULT_B_buy_value_limit = 0
DEFAULT_trailing_buy = 0.25
With this settings its trailing, but not buyng already all day.  When trailing buy set to 0 then its start to buy.
Maby DEFAULT_trailing_buy  need to change to DEFAULT_A_trailing_buy ?

**Comment by SgtBatten** [comment]
Any evidence that the price actually dropped and went back up by 0.25 percent?
I use 5 strategies and trailing is working fine.

**Comment by YoJeff** [comment]
Run this through support first.   How many coins dropped 30% below the lower BB today?

**Comment by XcidTrader** [comment]
Is it possible to do something like this:   

DEFAULT_A_buy_strategy = LOWBB
DEFAULT_A_buy_value = 0
DEFAULT_A_buy_value_limit = -30
**DEFAULT_A_trailing_buy = 0.25**

DEFAULT_B_buy_strategy = RSI
DEFAULT_B_buy_value = 35
DEFAULT_B_buy_value_limit = 0
**DEFAULT_B_trailing_buy = 0**

**Comment by SgtBatten** [comment]
No, trailing is based off price alone and begins when all strategies are true.

**Comment by matbuf** [comment]
Are you sure that, once reached 0.25, the LOWBB -30 and the RSI 35 are still true, because with that jump back probably it could mess eveything.
