### ISSUE TITLE
Warning for stop_loss for DCA and Regular sell situations

### ISSUE THREAD

**Issue by smportis** [taniman/profit-trailer#163]
Please add a warning in the properties files for DCA and PAIRS to remind people to put a NEGATIVE stop loss in their settings so that they don't accidentally sell off all pairs. This is an easy mistake to make. 

 ***** WARNING When adding a stop_loss_trigger ensure that it is NEGATIVE ******

**Comment by YoJeff** [comment]
I would force it negative, just like LOSS strategy.   Got burned by this one once.

**Comment by taniman** [comment]
I read the wiki yesterday about loss strategy. You are right. forcing it!
