### ISSUE TITLE
API data requests returning SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by Juleseck** [taniman/profit-trailer#1630]
I'm trying to use the PT 2 API to get pair and dca data from the PT bot. Whenever I try to run any of the request URLs in the browser, it returns this:

![afbeelding](https://user-images.githubusercontent.com/15907940/39176759-dfd40c38-47ad-11e8-8aaa-9322a06765db.png)

**Comment by YoJeff** [comment]
What is /api/**/dca/log?

Why not use /monitoring/data?

**Comment by taniman** [comment]
api has not been documented yet. and you are using it wrong. it should be
/api/dca/log for example
