### ISSUE TITLE
ERROR ProfitTrailerService - CB - Error in reading response connect timed out

### ISSUE THREAD

**Issue by darkban** [taniman/profit-trailer#1631]
I have a lifetime license with the possibility of having 4 instances (which I bought some time ago)
I have 2 binance accounts (one for the market btc, the other for the market eth)
I registered 4 bees both added on discord (2 for market btc and 2 for market eth)
Both run on the windows 10 platform, with a fiber connection and with profit trailer 2

if I start both instances I get this error:

> 2018-04-24 12:19:59 ERROR ProfitTrailerService - CB - Error in reading response connect timed out
> 2018-04-24 12:20:02 INFO a - API Problems?
> 2018-04-24 12:21:02 ERROR ProfitTrailerService - chartData - Error in reading response connect timed out

this only happens if I start the second instance, if I start only one instance it does not give me any error. How can I solve this problem?

**Comment by SgtBatten** [comment]
Did you increase connection.timeout

**Comment by darkban** [comment]
Did you increase connection.timeout = 30 
change in 60 ?

**Comment by SgtBatten** [comment]
45, 50, 60 etc yes

**Comment by darkban** [comment]
I increased up to 50, 60 and now to 70 and I always have the same problem ... I have yet to increase? why with profit trailer 1 this did not happen?
what does this parameter involve? slows down the bot in performing the transitions?

**Comment by SgtBatten** [comment]
allows the bot more time to receive the data.  How long did you leave them running to test. see if it settles down after 30 mins to 1 hour

**Comment by darkban** [comment]
very thanks .... if I leave the default setting at 30 seconds, what happens? if I leave the setting at 30 seconds the bot still works and buys and sells without problems ... the only problem that is present is on the terminal ... what is recommended to increase the time out or leave it by default?

**Comment by YoJeff** [comment]
Merge #1873
