### ISSUE TITLE
PT bought too many tickers

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer#1632]
Hey guys, I know it real difficult one to reproduce/fix, but this one is pretty big.

Lsat night I had 10 tickers, 6 pairs, and 4 DCA.  Thats a big problem because I only have 8 set for max_trading_pairs.  I have never had more than 8 configured.  I tried refreshing screens a few times etc.  I should have logged into binance, but it was late.

Anyway, most of it sold through the evening, but as you can imagine, DCA would become a problem if I needed it for more tickers than configured.

**Comment by BitRacer** [comment]
I don't think there is a setting to do that.  I don't mean to presume, but I was thinking it was some kind of race condition or synchronization issue that allowed the extra buys through.

**Comment by SgtBatten** [comment]
in your bot folder, ordersettings folder

**Comment by felipeff** [comment]
Had the same issue. my max pairs is set to 5 but the bot bought 9 pairs. 
[ordersettings.zip](https://github.com/taniman/profit-trailer/files/1946854/ordersettings.zip)

**Comment by SgtBatten** [comment]
Can we grab the log file also please. I am guessing binance spat out API errors at the time

**Comment by felipeff** [comment]
That's very likely. I was getting now and then orders being filled but PT was logging errors saying the order did not exist. so I guess the bot was adding to the counter of open pairs in those cases. follow the log

[log.zip](https://github.com/taniman/profit-trailer/files/1946880/log.zip)

**Comment by taniman** [comment]
This is indeed caused by the binance errors. If the bot cannot get the correct amount of coins from the exchange we cannot know how many pairs you have to protect agains going over max_trading_pairs

**Comment by BitRacer** [comment]
my logs are gone now, but I recall two purchases on the same second in the buy logs... FWIW I think the _correct_ behavior when you cant validate the number of pairs would be to not buy.

**Comment by BitRacer** [comment]
might have been theese, note the dates.

-rw-r--r-- 1 pi pi 7978 Apr 20 23:03 14999472
-rw-r--r-- 1 pi pi 7978 Apr 20 23:03 28759400
-rw-r--r-- 1 pi pi 7978 Apr 20 23:03 12678824
-rw-r--r-- 1 pi pi 7978 Apr 20 23:03 8181255
-rw-r--r-- 1 pi pi 7978 Apr 20 23:04 45859313
-rw-r--r-- 1 pi pi 8074 Apr 20 23:27 8186244
-rw-r--r-- 1 pi pi 8074 Apr 20 23:27 13283403

**Comment by YoJeff** [comment]
There have been several releases since the last activity on this issue.   If this is still an issue with v2.0.5 resubmit with the proper format.
