### ISSUE TITLE
Feature Request - have profittrailer pull history from exchange

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer#1633]
In cases where PT datafiles are corrupted or simply on a new install upgrade provide an option in initialization that will get the buy/sell information from the users exchange.

This would not only provide value in PT, but also make PtTrackers value even more evident.

**Comment by SgtBatten** [comment]
we provide 6 backup files and i have never seen an issue with these if used correctly.

https://wiki.profittrailer.com/doku.php?id=common_errors#both_save_files_were_corrupted
