### ISSUE TITLE
‼️****{ Feature Request Ω Reversal Trading.}****‼️

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer#1637]
https://github.com/GuntharDeNiro/BTCT/wiki/Reversal-trading

Reversal trading (RT) is a Gunbot technique to keep on trading profitably when prices move downwards after an asset has been purchased.

The principle is to use the already invested amount of base currency to accumulate more units of the quote currency while prices are moving downwards. When prices eventually rise again, the -then bigger- bag can be sold for profit at a lower price point than without reversal trading.

Trading fees paid while in reversal trading are all accounted for.

![38331646-13c489aa-3854-11e8-95b4-8b9143edf69b](https://user-images.githubusercontent.com/35824627/39187370-81eda00c-47a3-11e8-8c6e-80860c33fd22.PNG)

Reversal trading starts when the current price is a set percentage lower than the average bought price (or last bought price, when using RT together with DU), this is defined with RT_SELL_BUYDOWN. The initial bag gets sold for base currency (RT_SELL) and the invested amount is reserved for buying back more units when prices drop further. When the price then drops by a percentage defined with RT_BUY_BUYDOWN, quote currency gets bought (RT_BUY). You now own more quote currency than you initially bought, at a lower price per unit.

This process will repeat when prices keep dropping, enabling you to keep accumulating quote currency without investing additional assets.

When prices rise again, your normal trading strategy will sell the assets for profit.

In case prices recover before RT_BUY_BUYDOWN is reached, the initial bag will be bought back to continue normal trading (RT_BUYBACK).

Optionally, the AIRDROP feature allows you to cash out accumulated quote assets in base currency. This takes place when the difference between the initial bag and the current bag size is bigger than MIN_VOLUME_TO_SELL. Reversal trading then continues with the initial amount of quote currency bought.

Warnings:

Do not activate reversal trading on existing bags that are already down a lot! The decision to run reversal trading or not should best be made before you start trading a pair, this way the process can kick in timely.
Reversal trading math is done based on your trading history, if your last sell order was at loss (and not caused by stop limit), reversal trading would immediately start when you enable it. To prevent unwanted reversal trading, make sure to either have a profitable last sell order or to have set IGNORE_TRADES_BEFORE at a time after your last sell order at loss. Alternatively, you can set a maximum price difference between current price and average bought price with RT_MAXBAG_PROTECTION, to prevent RT from starting on pairs that already lost a lot of value.
When a buyback occurs during reveral trading, slightly more base currency gets invested.

![38986278-43c97dc6-43cc-11e8-9313-a6bbaeb68be6](https://user-images.githubusercontent.com/35824627/39187400-964dcee6-47a3-11e8-8306-b63b1cb1de24.jpg)

Parameter | Default value | Description
-- | -- | --
RT_ENABLED | false | Values: true or false. When set to true and prices drop, reversal trading will try to use the assets originally invested in your bag to accumulate a bigger bag, which can be sold for profit earlier than the original bag. When double up is enabled, RT will start when DU_CAP_COUNT is reached.
RT_SELL_BUYDOWN | 1 | Values: numerical - represents a percentage. Defines the percentage drop after initial buy or RT_BUY to trigger RT_SELL. Make sure to set this higher then the spread between bid and ask to prevent unwanted buybacks.
RT_BUY_BUYDOWN | 2 | Values: numerical - represents a percentage. This defines the percentage the price has to drop after RT_SELL to trigger RT_BUY.
AIRDROP | false | Values: true or false. Set this to true to enable airdrop and automatically cash out accumulated quote currency during reversal trading. The initial bag size will be kept, surplus bigger than MIN_VOLUME_TO_SELLwill be airdropped.
RT_MAXBAG_PROTECTION | 10 | Values: numerical - represents a percentage. Sets the maximum difference between the average bought price and current price for starting RT. When the difference is bigger, RT won't start. This is used as a protection against starting reversal trading on bags that already dropped too much for the process to work effectively.
IGNORE_TRADES_BEFORE | 0 | Values: unix timestamp in milliseconds (in GMT)Optional parameter to force reversal trading to ignore trades before a set time. Use https://currentmillis.com/to convert human readable time in GMT to unix timestamps in milliseconds.

**Comment by YoJeff** [comment]
As stated in the announcements -- this is for bugs only.    Resubmit to features github -- make sure you specify V2.0.    https://github.com/taniman/profit-trailer-enhancements/issues
