### ISSUE TITLE
[BUG?] STOCH strategy's behavior is different from WIKI.

### ISSUE THREAD

**Issue by yesmider** [taniman/profit-trailer#1638]
here is my config: 
pair:
DEFAULT_B_buy_strategy = STOCH
DEFAULT_B_buy_value = 50
indicator:
STOCH_candle_period = 1800
STOCH_length = 14

from wiki's examples:
DEFAULT_A_buy_value = 20 → buy zone begins when the STOCH value is **less** than or equal to 20.

from my test:
PT will trigger buy signal when value >= buy_value

![default](https://user-images.githubusercontent.com/23432951/39188700-fd904ec6-4802-11e8-926d-90fc865288a7.png)

I'm not sure which case is correct.

**Comment by stevenshizzleh** [comment]
I second this. It appears the implementation is incorrect? STOCHRSI also did not behave as expected, although I'd have to do more research as to what the issue is.

**Comment by SgtBatten** [comment]
Wiki is correct for intended implementaion. But code is implemented incorrectly. Do no use STOCH until recitified.

**Comment by yesmider** [comment]
I found similar issue from MACD strategy.

**Comment by SgtBatten** [comment]
@yesmider please open a seperate issue for that. I use Macd without issue.

**Comment by yesmider** [comment]
okey, thanks
