### ISSUE TITLE
GUI time changes

### ISSUE THREAD

**Issue by Limitrade** [taniman/profit-trailer#164]
hi,
   1. Can you please add a possibility to display on monitoring not only UTC time zone, but servertimezone from application.properties.

   2. Sell log calculation trades problem. This part of monitoring page show trades according to UTC time zone even after i set my time zone in application.properties. What i mean i set +3, and want to show only trades for 1 day logs shows 2 days adding trades PB made this last 3 hours from UTC time. so i always have trades 1 day + trades for last 3 hours previous day. so It don't give real info about trades and traded volume for last 24h in monitoring.
![1508917942009](https://user-images.githubusercontent.com/32781534/31986899-bd54a63c-b972-11e7-8d49-3bcad54a33b6.jpg)

**Comment by taniman** [comment]
#2 will be fixed in 1.2.4.1

#1 in the next release
