### ISSUE TITLE
Disable trading for specfic coin

### ISSUE THREAD

**Issue by victorlmt1** [taniman/profit-trailer#1642]
I use BNB for paying fees on binance.

I need to disable trading for BNB on v2.0, how do I do this?

In previous version I used to set it to watchmode, however, the "hidden_pairs = BNB" its not for this purpose, because I set "enabled_pairs = ALL".

Somebody help please?

Thanks guys. And this version Rocks, congratulation.

**Comment by Jamby93** [comment]
I've just discovered the way to specify option for a coin has changed in 2.0 [How do I Change Settings on a Single Coin?](https://wiki.profittrailer.com/doku.php?id=faq#how_do_i_change_settings_on_a_single_coin)
To put BNB in WATCHMODE simply put `BNB_trading_enabled = false` in PAIR.properties and `hidden_pairs = BNB` if you want to be hidden from the gui.

**Comment by mrulke** [comment]
This does not work if it has put it into DCA. Mine has DCA'ed and now when ever rebuy it, it will sell on profit
