### ISSUE TITLE
STOCHRSI not accurate 

### ISSUE THREAD

**Issue by Batman0323** [taniman/profit-trailer#1644]
My settings:

STOCH_candle_period =3600
STOCH_legnth = 14
RSI_candle_period = 3600
RSI_length = 14

The STOCHRSI Value , when compared to the same time chart on BINANCE is sometimes way off.  ICX showed STOCHRSI at 87, yet Profit Trailer reads it at 34.

Buy Value is set to .15 and sell to .85
Also having issues with .00000000 values, but not all.

**Comment by stevenshizzleh** [comment]
Agree - STOCHRSI is not the same as what is reflected on TradingView for same settings, candles, market, etc.

**Comment by SgtBatten** [comment]
Also know that ProfitTrailer bases the current values on the orderbook. So the highest bid price or lowest ask price. TV looks at actual trades. Can cause variation.

**Comment by Ghostdoge** [comment]
Yeah it needs to be looked at. I use this in combination with others, so I'll be putting the bot on test mode till this gets fixed.

For those that have been using it though. How do you get say StochRSI to calculate say "10"(lower line) from trading view chart. I see the formula on the wiki, but can't seem to understand where I'm meant to get the first RSI number for the equation. I was going to just keep testing numbers from 0 to 1, but since its reading is way off, I don't think I'll even try till its sorted.

**Comment by stevenshizzleh** [comment]
@Batman0323 - I set the time offset in PT to 0 and even changed the time offset on the server to 0 and the STOCHRSI numbers are way off from what I'm seeing on Trading View. I'll see a value of 0.655 in PT for the BSV, but the value as calculated on Trading View is 0.31 -- almost inverse.

**Comment by Heartinhand** [comment]
Guys, this keeps happening. Now it's WTCBTC stochrsi on various diferent stochrsi indicators on TV: 0.6. On PT: 0.19 I heard stochrsi is not working well? way off

**Comment by stevenshizzleh** [comment]
Thanks for confirming @Heartinhand -- hope this is enough info for the devs to work off of. Sounds like they're away of some indicator issues and I'm sure they're working to fix them ;)

**Comment by SgtBatten** [comment]
I know this is no consolation, i am not trying to confront anyone.
 we did mention stock rsi would not match trading view, 
![image](https://user-images.githubusercontent.com/24822223/39498443-6b228dc6-4deb-11e8-9eef-b1763a670a18.png)

https://wiki.profittrailer.com/doku.php?id=changes#version_2

**Comment by stevenshizzleh** [comment]
@SgtBatten thanks for that information good to know. I think we can work around it by using STOCH and appreciate that implementation. Thanks to you and the PT team for your hard work and may the gains be with you.

-Steven

**Comment by hgiddy** [comment]
Guys any idea when this will be fixed please??

**Comment by taniman** [comment]
Reworked in 2.1.0 enhancement branch
