### ISSUE TITLE
Feature Request: DEFAULT_take_daily_profit_percentage = X

### ISSUE THREAD

**Issue by robheath90** [taniman/profit-trailer#1648]
In addition to DEFAULT_take_profit_percentage = X, would it be possible to include something like a DEFAULT_take_daily_profit_percentage = X, which would look at the 24h percentage rise rather than the total percentage rise?

The reason for including this is that I want to trade primarily on an EMACROSS strategy (both buy and sell). As the EMACROSS sell strategy effectively acts as my stoploss, and longer term may be more useful than GAIN, I have GAIN set as a negative value in order to effectively discount it from trading. I have a patient mindset and I wish to generally trade longer term, however I obviously would like to take advantage of outrageous pumps if I hold a coin, and EMACROSS will not accomplish that. DEFAULT_take_profit_percentage = X does, however it would require regular bot maintenance if specific pairs begin to meet the total percentage gain, but not the daily percentage gain. This thought came to me this morning when I realised I had sold DCR on Poloniex for an 11% Profit, despite the coin pumping over 100% overnight. I realise GAIN would have taken advantage of some of this pump, but again this would require maintenance to continuously cater this for each coin (by increasing the GAIN percentage as my coin grew according to my EMASELL buy/sell strategy)

**Comment by SgtBatten** [comment]
Please submit feature requests on this GitHub page.

https://github.com/taniman/profit-trailer-enhancements
