### ISSUE TITLE
DCA max cost set to 0, pairs in DCA log still show MAX COST REACHED

### ISSUE THREAD

**Issue by andreboogaards** [taniman/profit-trailer#1649]
In DCA.Properties:
`DEFAULT_DCA_max_cost = 0`

In my DCA log, many pairs are still showing MAX COST REACHED. I even tried restarting the bot, no change. Other changes in DCA.properties are picked up correctly.

**Comment by SgtBatten** [comment]
Currently there are two messages in DCA log that are backwards.

Insufficient balance and max cost.

Please do firm you have no balance left to DCA and hence are getting the incorrect message.

**Comment by andreboogaards** [comment]
Confirmed, no balance left to DCA. Couldn't find a ticket for the reversal, but if that issue has been logged elsewhere, feel free to close this ticket.
