### ISSUE TITLE
TCV incorrect

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer#1650]
Wiki (http://wiki.profittrailer.com/doku.php?id=web_interface_guide) says: 
> TCV (Total Current Value) - The current value of your coins. It's the sum of your BAL (balance) and the actual value of your coins on the market (it's how much you could get if you sold them at the top bid price right now). This includes the sum of your current values in Pairs Log plus DCA Log plus Dust Log to calculate the TCV.

But it isn't doing that. It is prolly doing something (incorrect) with the Pending Log. For open buy orders, it prolly takes the value of when the order is hit and prolly the same for open sell orders. It should take the value of what it is currently worth. 

But still if I sum up the values that way, there is still a mismatch in what's visible in the Logs and what the TCV in the monitor says. 

Please fix this and I'm also curious of how the TCV is actually calculated, because what the wiki says is not true. It is missing the correct value by a mile. I have 2 bots, 1 should have 1.9 and says 1.4 and 1 should have 1.2 and has 2.5 as value.

**Comment by YoJeff** [comment]
Straight from the code, here is your answer:


`
totalCurrentVal: parseFloat((data.totalPairsCurrentValue + data.totalDCACurrentValue +
        data.totalPendingCurrentValue + data.realBalance).toFixed(precision)).toFixed(precision)
`

**Comment by echthard** [comment]
Then I also need to know how data.totalPendingCurrentValue is calculated ;-)


![image](https://user-images.githubusercontent.com/1479483/39256813-2ac9bf46-48b0-11e8-818a-8ebfe2f61445.png)
![image](https://user-images.githubusercontent.com/1479483/39256933-79da7e72-48b0-11e8-866e-378772876fae.png)

For bot 2 is it  super clear, I have 1.1 BTC in total, but it says current value 1.67 BTC. While more than 50% is in DCA at the moment. I have a few super low open buy orders in Pending, somehow PT sees this as current value. 

Yes I now know it for sure, I think I've found it. Check this:
![image](https://user-images.githubusercontent.com/1479483/39257143-198520c6-48b1-11e8-8eb4-9e2147fedc5a.png)
I have an open order of 2000 BQX. The current value is calculated over the 2000 as if I have the 2000 BQX in my posession. 

What is is in real life: it is 0.004 BTC that is reserved for that 2000 BQX buy order. 

So the solution is: You should switch the current value and the target value for buy orders. (toggle this on positive or negative percentage in Pending Log). I think the Pending Log was originally created for sell orders. The current value is correct for sell orders.


And I don't mind answers straight from the code, I'm also a coder.

**Comment by YoJeff** [comment]
This has morphed into a feature request.   Which go here -> https://github.com/taniman/profit-trailer-enhancements/issues
