### ISSUE TITLE
[Bug?] MACD strategy issue

### ISSUE THREAD

**Issue by yesmider** [taniman/profit-trailer#1651]
here is my test config:
set A:
DEFAULT_B_buy_strategy = MACD
DEFAULT_B_buy_value = 0.000000003  #the value > 0
set B:
DEFAULT_B_buy_strategy = MACD
DEFAULT_B_buy_value = 0 # the value = 0
set C:
DEFAULT_B_buy_strategy = MACD
DEFAULT_B_buy_value = -0.000000003 # the value <0

as the expression on wiki:
This buy strategy is true when MACD =< buy_value. This sell strategy is true when MACD >= sell_value. 

here is my result:
set A:
![default](https://user-images.githubusercontent.com/23432951/39248168-f13a7edc-48cd-11e8-9165-c438fa2ae0e8.png)
![default](https://user-images.githubusercontent.com/23432951/39248246-1cdbc708-48ce-11e8-8dbd-876b6252c44e.png)
set B:
![default](https://user-images.githubusercontent.com/23432951/39248366-76ad53f0-48ce-11e8-8f57-d5906fb66972.png)

set C:
![default](https://user-images.githubusercontent.com/23432951/39248302-4422f214-48ce-11e8-84c1-e4515b822a83.png)

the signal triggered when:

if buy_value >=0: 
      macd_hist >= buy_value
else: 
      macd_hist <= buy_value

 It's huge difference between wiki and PT itself.

**Comment by SgtBatten** [comment]
Bot behaviour is what I would expect. I will review the wiki today. Terribly sorry 

Mac's should work like emacross

**Comment by XcidTrader** [comment]
Is the MAcd + value its cross over value ?

**Comment by yellobello** [comment]
Hi, I would like it as a buy trigger when MACD(Histogram) goes from negative to positive, and then maybe combine it with other triggers..
so, as a buy signal/trigger it would be yesmider´s case B:
DEFAULT_B_buy_strategy = MACD
DEFAULT_B_buy_value = 0 
okay, so far so good, but going from positive to negative, it also crosses the zero line and the
same thing applies, but this time I do not want it to buy...
Is there a way to do it without combining MACD with other factors?

**Comment by raenrfm** [comment]
I'm experiencing the same issue...it appears that PT is looking at the 0 crossover and not as the wiki describes as the macd crossing the signal line which I what I thought and hoped it was doing.

**Comment by KorolCoin** [comment]
Is there something new? Or a solution?

**Comment by SgtBatten** [comment]
The behavior shown in the OP is correct.

If buy/sell value is >= 0 then the MACD value must be > buy/sell value to be true.
is buy/sell value is < 0 then the MACD value must be less than buy/sell value to be true.

PT use histogram for MACD. the cross is not something that is detected. I am still working on improving the wiki entry but waiting on some dev feedback.

**Comment by taniman** [comment]
We have made changes to make all strategies  follow the same rules. 
whether it be >= or > than. < or <=. The wiki should be updated with the new logic hopefully when this is released

Other than that. We are making some extra improvements to buy_on_first_signal so we can buy only on the initial cross and not buy on the way back down.
This all to be added to 2.1.0
