### ISSUE TITLE
Case sensitive or case-sensitive?

### ISSUE THREAD

**Issue by tash649** [taniman/profit-trailer#1653]
is there a difference between DEFAULT_Max_Trading_Pairs and DEFAULT_max_trading_pairs? what will work and what not? and BCH_Dca_Enabled or BCH_DCA_Enable

**Comment by YoJeff** [comment]
Best practice is the use the correct/defined case always.

**Comment by tash649** [comment]
can you please answer the question? @YoJeff

**Comment by YoJeff** [comment]
Just assume yes.   Case matters pretty much everywhere but Windows filenames.

**Comment by YoJeff** [comment]
Not a bug.   Closing.
