### ISSUE TITLE
Poloniex nonce error v2

### ISSUE THREAD

**Issue by GRieVoUS01** [taniman/profit-trailer#1654]
I started getting "ERROR Application - Please fix: default api key -- nonce error: {"error";"Nonce must be greater than 1524653990557000000. You provided 1524637890808000000."}"

https://cdn.discordapp.com/attachments/406439964356640768/438583952576610312/unknown.png

i have tested using 17-20 with no change and i guess it doesnt matter in V2 anyways. I then desided to go back to V1 and now is saying my licence is invalid while v2 if ran again will say the same error above. I checked my poloneix licence and api are correct in discord. i even tried starting from scratch and re did everything. 

please help

**Comment by YoJeff** [comment]
Please use support, this is only for bugs.
