### ISSUE TITLE
PT 2.x ability to sort by 24hr percentage removed

### ISSUE THREAD

**Issue by jas-on-jas** [taniman/profit-trailer#1655]
**Issue:**
Unable to sort 24hr column in PT 2.x. In previous versions of PT 1.x you had a column to sort by 24hr percentage up/down. This has been removed and the column was merged with the coin pair, so you can only sort alphabetically by the pair name.

**Reasons:**
I use this quite often to view which coins are down a lot for perspective and if I'm in DCA mode. If I'm not DCAing them due to my settings, it's possible I would rather manually buy them or look to tweak my DCA strategy, which I'm sure we are all tweaking.. Specifically helpful if FUD or sharp sell-off for a quick buying opportunity.
The last reason I use it, is to further define my strategies with the ability to use multiple indicators in strategies. While it's just a 24hr option it does give some degree of info to add for my specific setting per market trend, sms etc via (PTM). 

**Addition:**
Hopefully this gets added back, as it's a super small column and the data is already there, and was available in the previous PT 1.x versions. 
Adding 1hr, 3hr, 12hr options would be a feature request, and not sure it's doable with the data your receive, but I'd settle for having the 24hr percentage up/down column back.

Thanks and I've enclosed screenshots showing PT 1.x and PT 2.x
## **PT 1.x (24 hr column sortable)**
![pt 1 x sortable](https://user-images.githubusercontent.com/38011991/39260877-5879673c-4880-11e8-9d76-3884549a3bf7.PNG)

## **PT 2.x (24 hr column not sortable)**
![pt 2 x not sortable](https://user-images.githubusercontent.com/38011991/39260880-5ae09d74-4880-11e8-8e5c-0006e6e50396.PNG)

**Comment by YoJeff** [comment]
Bugs only here.  Feature requests -> https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by jas-on-jas** [comment]
Considering it was removed from PT 1.x, I don't consider it a feature request. I'd call it adding back what you takeith away, but sure I'll add a feature request for something which already existed was merged.
