### ISSUE TITLE
Bot crashed on error

### ISSUE THREAD

**Issue by Topsie13** [taniman/profit-trailer#1656]
Hello everyone,
I sometimes have a bug since version 2, an error occurs in the logs and the bot stops.
Here is this error:

![2018-04-25 a 23 00 55](https://user-images.githubusercontent.com/1359387/39273039-fe8e4ef0-48dd-11e8-91d3-9df380cdcebb.png)

EDIT : 
OS : Ubuntu 16.04 x64
Exchange : BINANCE (market BTC)

Thanks for your work !

**Comment by SgtBatten** [comment]
You clock is not synced correctly

**Comment by Topsie13** [comment]
Ok but, why does it work perfectly and SOMETIME it crash ? 
If my clock was not synchronized, it should never work, no ?

**Comment by SgtBatten** [comment]
In theory. But that error specifically says the clock is off.

**Comment by Topsie13** [comment]
It says the request is received too late by BINANCE then server rejected it.
Network can be unstable and a request may arrive too late, out of "recvWindow", but profit trailer should handle this error and continue without crashing out, no ?
A late request is a common error, but I think something happen when catching this error, then bot crashing

**Comment by YoJeff** [comment]
Cryptography demands accurate times.   This is not negotiable/fixable.

**Comment by Topsie13** [comment]
My clock have good time and is perfectly synced, I just came here to say profit trailer crash when api error occure.
