### ISSUE TITLE
Balance is 0 different from start balance - no buys

### ISSUE THREAD

**Issue by dan20101010** [taniman/profit-trailer#1663]
Running V2.0 on VPS. All appears to be running fine however Balance shows 0 even though start balance is 0.5 ETH. 

Lots of Pairs fitting buy rules but no buys happening, most likely due to Balance issue.

Have set server.start_trading_delay = 0 and restarted VPS but no change.

![screen shot 2018-04-26 at 6 04 24 pm](https://user-images.githubusercontent.com/38749893/39293471-4bbb0530-497c-11e8-87f5-d063e9a67969.png)
![screen shot 2018-04-26 at 3 54 37 pm](https://user-images.githubusercontent.com/38749893/39293502-65ffa4dc-497c-11e8-97a4-d026ef75a006.png)

**Comment by SgtBatten** [comment]
1 try resetting testmode data using the reset url in the wiki under testmode.

2 try deleting the profit trailer data.json and the. Restarting. 

3 try the reset url again.

Please let us know what step works.

**Comment by dan20101010** [comment]
Hi,
I tried option 1 and looks like it worked. Balance now show's same as Start Balance.
I have now got 1 buy in the DCA log so I presume it bought then went straight in to DCA but it looks like it's working now.

Thanks.

**Comment by menzmarco** [comment]
hey could you explain further how you did this?
1 try resetting testmode data using the reset url in the wiki under testmode

having same issues with 0 balance although i am having sufficiant balane -.- thanks in advance
