### ISSUE TITLE
Negative EMASPREAD as Sell Strategy

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#1664]
EMASPREAD is true when I set it as negative number on my pairs log. 

When selling it should look for if spread is negatively increasing so it should look for **sell_value < -0.01** in my case. 

**wiki ref: This buy/sell strategy is true when the spread between fast and slow EMA is larger (bigger spread) than or equal to the buy/sell_value.

DEFAULT_B_buy_strategy = EMASPREAD
DEFAULT_B_buy_value = 0.3
DEFAULT_B_buy_value_limit = 0.5

DEFAULT_B_sell_strategy = EMASPREAD
DEFAULT_B_sell_value = -0.01

![image](https://user-images.githubusercontent.com/37293938/39305203-f104d0b0-4964-11e8-837e-d69f257cee5d.png)

Running v2.0

**Comment by cvthub** [comment]
Sorry for the delay. 
A fix is on the way and should be included in the next release.

**Comment by mightysoul** [comment]
Thank you :)
