### ISSUE TITLE
BUY Strategy not showing up in Possible Buy Screen

### ISSUE THREAD

**Issue by sas7085** [taniman/profit-trailer#1665]
Hi 
I enabled the BUY strategy  STOCHRSI  in pair properties file and it didn't reflected in the possible buy . Not sure in other BOT i didn't observed  this issue. 

Properties file -

>DEFAULT_A_buy_strategy = LOWBB
DEFAULT_A_buy_value = 20
DEFAULT_A_buy_value_limit = -20

> DEFAULT_D_buy_strategy = RSI
DEFAULT_D_buy_value = 45
DEFAULT_D_buy_value_limit = 0

> DEFAULT_F_buy_strategy = STOCHRSI
DEFAULT_F_buy_value = 0.20
DEFAULT_F_buy_value_limit = 0

Screen shot of  Possible buy screen -
![image](https://user-images.githubusercontent.com/36013435/39307268-5a9fc1fe-4930-11e8-9ad9-f351208d9bf1.png)

**Comment by sas7085** [comment]
i did some tweak to test why this is happening. Found the interesting scenario.
When i am changing the STOCHRSI  Buy settings  from _F to _E  then STOCHRSI is showing in Possible Buy screen.

Case -->1 --> Changed the DEFAULT_F * to DEFAULT_E *  then i can see the STOCHRSI in Possible Buy Screen.
> DEFAULT_E_buy_strategy = STOCHRSI
DEFAULT_E_buy_value = 0.20
DEFAULT_E_buy_value_limit = 0

Case -->2 --> Changed the DEFAULT_E * to DEFAULT_F *  then the STOCHRSI is missing in Possible Buy Screen.
> DEFAULT_F_buy_strategy = STOCHRSI
DEFAULT_F_buy_value = 0.20
DEFAULT_F_buy_value_limit = 0

I guess it should not matter  E or F . I am using 3 BUY strategy  _A , _D  and _F .  The _B , _C , _E  are commented in the pair file.

**Comment by YoJeff** [comment]
There is no F.   Wikiwikiwiki

**Comment by sas7085** [comment]
Its like some restriction on name . using  3  active settings . it should not matter.

**Comment by sas7085** [comment]
If  F not is  allowed then app should through the error or alert. its not doing anything .
