### ISSUE TITLE
BNBBTC_trading_enabled = false Not working with v2.0

### ISSUE THREAD

**Issue by anandsunpreet** [taniman/profit-trailer#1666]
BNBBTC_trading_enabled = false Not working with v2.0
I am using this command post installing v2.0 its trading BNB as well and it sells it off immediately
I want to use BNB for fees on Binance how it used to work in old version has the command changed ?

**Comment by But4ler** [comment]
BNB_trading_enabled = false
https://wiki.profittrailer.com/doku.php?id=pairs.properties
