### ISSUE TITLE
RSI value lagging behind ?

### ISSUE THREAD

**Issue by B0mBeur** [taniman/profit-trailer#1669]
When i Watch the possible buy page and comparing value with tradingview. The value of RSI rarely match what i see in tradingview.

I think that what i see is the value of the last closed candel not the current one ?

I was watching zen today and RSI dropped to 20 but Pt waited one full candle before dropping to 20. By the time RSI become true my two other indicator become false.

I'm using 5 minute candle.

**Comment by Ghostdoge** [comment]
Wouldn't that be affected by order book spoofing? What's the advantage of looking at order book over actual buy/sells?

**Comment by cabbage4164** [comment]
Just wondering why can’t PT and trading view match by using the same data for the indicators? In developing a buy and sell strat i exclusively used trading view, but now the strategy is close and does not match between the charts and what we see in the GUI. Some clarification would be helpful. Really love pt and all the work that has gone into it. Thanks

**Comment by B0mBeur** [comment]
from what i can see the way Tradingview do it is more accurate. By the time PT think you hit the bottum the price already started to go up and you miss the lowest price to buy.

**Comment by cabbage4164** [comment]
On rsi the buy is closer then the sell as the indicator rises. Over 5 points off between pt and tv

**Comment by YoJeff** [comment]
PT will never be exactly the same as TV.  Data collection methods, intervals, frequency of polling.  I have extensively tested PT's RSI against independent calculations and it's solid.
![image](https://user-images.githubusercontent.com/30263914/39367915-2649db5c-4a06-11e8-821b-86b998e90493.png)

**Comment by YoJeff** [comment]
But as you will notice, even though the overall shape and feel is right --  sometimes there is a spike causing variances.   Such is life.

**Comment by B0mBeur** [comment]
I retested something and i think i found the problem. RSI is working fine in PT BUT with a delay between 2 minutes and 3 minutes.

I watched a chart and timed how long it takes for PT to get the same value and that's the delay i get.

I foud this tread that talk about bittrex delaying some data with there api maybe that's the problem ?

https://bitcoin.stackexchange.com/questions/70272/bittrex-api-3-minute-delay

**Comment by Heartinhand** [comment]
RSI and STOCHRSI are simply wrong here (2.0.1). 
NEO RSI on PT: 33 
RSI on TV: 51 

last time it hit 30's was like 3 days ago.

**Comment by taniman** [comment]
@YoJeff reasearch is reason enough to close. But next to that @B0mBeur is correct with bittrex delay too

So mostly all is well. I advice to create a new issue if someone has solid proof that the data is incorrect. 
Preferably with all the logs and screenshot required

**Comment by B0mBeur** [comment]
@taniman So its a bittrex problem only ?

If it's the case i will ask to switch my license to binance, i'm tired of the low volume on bittrex. 

Thank you
