### ISSUE TITLE
Edit settings outside web gui.

### ISSUE THREAD

**Issue by LoneWolfProductions** [taniman/profit-trailer#1670]
Or I am missing it or it is just not there anymore.

I had writen for V1 an app so I could mod my settings with a gui. is this still possible? even with 'server.disable_online_config = true' it requires to make changes though the web gui (according to the wiki)

So long story short i would really like to have external editing back.

**Comment by YoJeff** [comment]
Not returning.   There will be API docs coming shortly for interacting with your settings/configs.
