### ISSUE TITLE
[REQUEST] Bind instance of ProfitTrailer to a certain IP

### ISSUE THREAD

**Issue by NOP-Commander** [taniman/profit-trailer#1671]
Dear developers,

to overcome -especially on Binance- temp bans for too many API Requests i would like to request the feature to bind an instance of ProfitTrailer to a certain IP. If i have a VPS with multiple IPs I could easily avoid API-Calls per time/per IP ban issues when I run multiple instances of ProfitTrailer on the same VPS (what I actually do on my linux VPS - but not more than 1 instance on Binance anymore). 

Thanks in advance for any kind of response which comes into my favor. (;

sincerely yours,
NOP-Commander

**Comment by SgtBatten** [comment]
I run 3 binance bots same IP currently. The ban issue varies per customer as your account standing has an impact on it..

I still think this is a valid request. However feature requests need to go on the ot enhancements repository.  Can you please resubmit.

https://github.com/taniman/profit-trailer-enhancements
