### ISSUE TITLE
Positive EMASPREAD  range is not working 

### ISSUE THREAD

**Issue by sas7085** [taniman/profit-trailer#1672]
For Positive EMASPREAD limit was 0 to 0.05 but for any value EMASPREAD is showing true.

![image](https://user-images.githubusercontent.com/36013435/39325704-de944856-4960-11e8-8f5f-7600972d85d2.png)

Pair properties
> DEFAULT_C_buy_strategy = EMASPREAD
DEFAULT_C_buy_value = 0.05
DEFAULT_D_buy_value_limit = 0

**Comment by ricardodacosta** [comment]
If you see on your code you have DEFAULT_D_buy_value_limit = 0 when it should be 
DEFAULT_C_buy_value_limit = 0

Swap D for C

**Comment by sas7085** [comment]
My Bad didn't double check the C or D . 
> buy_value_limit  cannot equal 0 as it will disable the limit so you need to add a positive or negative  number  

Can we mention this in wiki Limit value cant be 0  though it is mentioned positive or negative decimal . Assumption is that this includes 0.

**Comment by SgtBatten** [comment]
It says Set to 0 to disable
