### ISSUE TITLE
Rebuy TImeout Not Working

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer#1677]
Rebuy Timeout not appearing to work - it will sell and then buy the same pair, including not in DCA.

Other people have reported this too. 

I have double checked and tried:

DEFAULT_Rebuy_Timeout = 15
DEFAULT_rebuy_timeout = 15

I've attached screenshots to show.

![2018-04-27 13 59 39](https://user-images.githubusercontent.com/18514924/39363774-5f14441e-4a23-11e8-9a43-6d6c6fb64137.png)
![2018-04-27 13 59 39](https://user-images.githubusercontent.com/18514924/39363789-6a8f4bfe-4a23-11e8-936a-da4f9018b510.png)
![2018-04-27 13 59 48](https://user-images.githubusercontent.com/18514924/39363791-6d38382a-4a23-11e8-87fd-458f3d623243.png)

**Comment by marcahx** [comment]
The rebuy timeout (from pairs) also prevents DCA from working altogether BTW (Regardless of how the settings in DCA or Pairs are set to). That bug has been in PT 1.x as well.

**Comment by Uruwashii** [comment]
Thanks - didnt know that. Hope it can be fixed soon.

**Comment by SgtBatten** [comment]
Working fine here. Looks more like the PTN bug where it sends a buy order for the same quantity it just sold. I note you aren't getting a notification from profit trailer for the buy. Only PTN

**Comment by YoJeff** [comment]
Issue timed out from lack of information
