### ISSUE TITLE
Time Difference Issue

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer#1678]
My system is showing correct time (London GMT 00:00 difference).

However PT 2.0.1 is showing 1 hour behind, I have tried the below with no difference? On PT1 I had left it to +00:00 as that as correct.

server.timezone_offset = +00:00
server.timezone_offset = +01:00
server.timezone_offset = -01:00

 P T Ver: 2.0.1 Market: BINANCE BTC Time: 13:11 UTC: 13:11
...... when the actual time is 14:11 ?????? again I tried the above settings to change, no joy? :-(

**Comment by YoJeff** [comment]
Which file did you edit for those?   It seems like something is screwy with your computer's time.  One hour ago, UTC was 13:11 not 14:11.

**Comment by darach96** [comment]
Also have this issue says UTC time is 15:45 as at the time of writing this (16:45 in real world location).

Amending the timezone in application.properties doesn't seem to update it.

**Comment by YoJeff** [comment]
Right now, UTC is 15:49.   I'm not sure which clock you are using.

**Comment by Uruwashii** [comment]
I've tried everything - PT1.0 was no problem on this same system (Raspberry Pi). Upgrade to P2.0 and time just isn't the same?

**Comment by Uruwashii** [comment]
![pi time](https://user-images.githubusercontent.com/18514924/39379848-7bf2bfe4-4a54-11e8-9ea2-99cbc6e4aa10.PNG)
![uk pt lower banner](https://user-images.githubusercontent.com/18514924/39379856-805dc20e-4a54-11e8-82a0-a57a3ccdb83e.PNG)

**Comment by Uruwashii** [comment]
Changing timezone offset by +1 or -1 doesnt have any effect.

**Comment by YoJeff** [comment]
Odd.   I'll mess with mine tonight and see if it changes as expected.  Honestly -- I run UTC because I hate converting to 'exchange time'.   For me, any 24 hour period is fine -- as long as they are regular.

**Comment by darach96** [comment]
I managed to fix mine, not sure exactly what step did it but I'll run through everything in case it helps pin down the reason:

- Stopped PT
- Set server offset to +01:00 in application.properties
- Re-downloaded the latest PT version
- Copied the new ProfitTrailer.jar over the existing one
- Restarted computer
- Started up PT and local time now correct

**Comment by SgtBatten** [comment]
If you live in +1 you have to set +1.

Regardless of what time the computer is set to.

**Comment by Uruwashii** [comment]
I've adjusted to +1 and get this ...............

2018-04-28 11:50:03 INFO GetErrors - 1 Binance BTC ERROR: ProfitTrailerService - Something is really wrong
2018-04-28 11:50:03 INFO GetErrors - 1 Binance BTC ERROR: ProfitTrailerService - Error occured in CB, message null, result: null
2018-04-28 11:50:03 INFO GetErrors - 1 Binance BTC ERROR: ProfitTrailerService - completeBalances - nl.komtek.pt.utils.i: ERROR: -1021, Timestamp for this request was 1000ms ahead of the server's time.
2018-04-28 11:50:03 INFO GetErrors - 1 Binance BTC ERROR: ProfitTrailerService - Something is really wrong

**Comment by Heartinhand** [comment]
It's happening to me too. That same 1h behind. But I'm on vps with a 3h difference, don't think it matters now I see the comments. I'll try replacing the jar thing.

**Comment by YoJeff** [comment]
There have been several releases since the last activity on this issue.   If this is still an issue with v2.0.5 resubmit with the proper format.
