### ISSUE TITLE
Dust Values in Wiki Possibly Incorrect

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer#1682]
Hello, in the Wiki it shows Binance and Bittrex dust as old values? 

 Binance:
BTC = 0.0011 on WIki when dust is 0.0019999 on Binance as mininum to trade is 0.002
ETH = 0.011 on Wiki when dust is 0.019 as mininmum to trade is 0.02
BNB = 1 (im not sure on this, would need checking)
USDT = 10 (again not sure on this)

Bittrex:
BTC = 0.0011 on Wiki but Bittrex is 0.00050000 
ETH = 0.00075 (not sure needs checking)
USDT = 3.75  (not sure needs checking)

Poloniex needs checking.

**Comment by Uruwashii** [comment]
Hello, just sorry just been back on Binance website and app to do manual trade and looks like they have reduced min buy to 0.001 BTC and 0.02 to ETH. I know it was  0.002 as they changed it Jan and looks like very  recently back down 0.01 - my bad should have doubled checked, Binance hadnt announced the drop and just checking other sources it is recent. #doublecheckbeforepostinganissue :-(

Bittrex was doing an online trade directly on site, it stated to me that 0.00050000 is the minimum to trade? Would be worth getting it doubled checked. WIsh I had screenshot the message. I'll see if I can get another one.

**Comment by YoJeff** [comment]
If this is still an issue -- resubmit for current version.
