### ISSUE TITLE
Start Balance duplicates on second bot on same license

### ISSUE THREAD

**Issue by GreenLanternFlash27** [taniman/profit-trailer#1683]
Hi,

I've got 2 bots, which are running on the same license and exchange but with different user accounts and API keys etc.

I've given both bots a start_balance in the pairs file, though for some odd reason if re-starting the bots in PM2 etc, the second bot update it's pairs settings to have the  start_balance of the first bot.

Not sure if this was due to an original duplication of the value in the settings (when I originally uploaded the new version) and as am unable to refresh the settings then each time I update both bots to have their correct starting balance, the second will undoubtedly change to be the same as the first, which is frustrating.

I haven't been able to fully re-create situation to note it down but it has happned a few times.

I hope someone else has reported this issue and I'm not going mad as there is no logic behind why it is doing that.

Cheers.

**Comment by Fogazi** [comment]
It sounds like you gave both settings the same name when you initialised. That will cause the duplication.

**Comment by GreenLanternFlash27** [comment]
Hi Fogazi,

Yeah, I thought that may have been the case, even though it did ask a few times which settings to use.

I assume by deleting everything and starting again should resolve it?

**Comment by cybermizrach** [comment]
@Fogazi where do you put the settings name? I've similar issue see [https://github.com/taniman/profit-trailer/issues/1719](https://github.com/taniman/profit-trailer/issues/1719)

**Comment by SgtBatten** [comment]
If you have this issue you can use the swagger API https://wiki.profittrailer.com/doku.php?id=swagger_api

Or you can change the default API key and it should ask you to choose a unique name on first boot.
