### ISSUE TITLE
Feature Request - Sell now Hot button

### ISSUE THREAD

**Issue by bradbas** [taniman/profit-trailer#1684]
A nice feature to think about adding would be the ability when looking at the pairs and/or DCA pairs to have the ability with a button beside the pair name or somewhere in that row that can be pressed and just immediately create a panic sell on that coin.   I have run into situations where I manually decided I want to sell but have to go into the config files to make the pair change and then it's too late the condition I wanted to sell has changed.

**Comment by YoJeff** [comment]
Feature requests go over here, https://github.com/taniman/profit-trailer-enhancements/issues  and I might add this has been requested several times ;)
