### ISSUE TITLE
Price rise triggers work as they want

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1686]
If I set price rise trigger to 7 and price rise recover trigger to 6 the bot will enable som on 7% rise. When the price will drop to 6% rise it will not disable som. The price dropped to 5% and still we have som. After that I manually disabled som. And bot enabled it when price rised to 6%. I have no idea how to predict this feature with rise. Didn’t tested but I expect that the same issue could be with drop price triggers.

**Comment by SgtBatten** [comment]
The original release had a typo in the recover parameter. Fix that to match the wiki.

**Comment by jokaorgua** [comment]
I don’t see any type of typo in wiki and my config in Parameters names. Please reopen the ticket. The issue exists and it is not in typos.

**Comment by SgtBatten** [comment]
Show me a screenshot of your triggers in the GUI
