### ISSUE TITLE
DCA counts towards consecutive buys and triggers SOM

### ISSUE THREAD

**Issue by benzo8** [taniman/profit-trailer#1687]
v2.0.1

I have consecutive_buy_trigger = 5 set.

DCA buys are counted towards this. Proof attached.

![image](https://user-images.githubusercontent.com/3908561/39381998-50f4e06e-4a64-11e8-9f55-a975e7aee8aa.png)
![image](https://user-images.githubusercontent.com/3908561/39382014-5e45ec0e-4a64-11e8-8bd0-38c6640283e7.png)

![image](https://user-images.githubusercontent.com/3908561/39382025-6abd414e-4a64-11e8-99be-696d8c05cde0.png)
![image](https://user-images.githubusercontent.com/3908561/39382034-74c9da9e-4a64-11e8-96e6-0de4cc3427c7.png)

**Comment by SgtBatten** [comment]
Ahh I had a think about this again. On bittrex and poloniex (at least in v1) the exchange tells us when consecutive buy occur. 

For binance we had to write our own loflgic to work it out as the exchange doesn't tell us.

Devs will have to clarify if all exchanges use the internal logic now. But that might explain why yours counts DCA. And mine does not on binance.

**Comment by benzo8** [comment]
![image](https://user-images.githubusercontent.com/3908561/39421138-eeadeef4-4c67-11e8-915b-8fe9d04a82b2.png)
![image](https://user-images.githubusercontent.com/3908561/39421145-f8d453c8-4c67-11e8-92f3-2c496e9eb39c.png)

And again... 
Also, the wiki method for resetting SOM doesn't work. Well, it does, but once you override the SOMO it sets SOM again. As does restarting the bot.

This, coupled with the constant throttling makes PT2 pretty much unusable on Bittrex atm.

**Comment by SgtBatten** [comment]
SOM will turn back on if the conditions are still true.

So you would need to change  your settings and then use SOMO.

**Comment by benzo8** [comment]
OK, I think I'll just set consecutive_buys/sells to 0 until you guys look into this further. Thanks.

**Comment by taniman** [comment]
if you have your ProfitTrailerdata.json. please provide it . I will look if the DCA data is being recorded correctly. Send it via discord. to me or @SgtBatten

**Comment by taniman** [comment]
fixed in 2.0.4
