### ISSUE TITLE
Invalid setting DEFAULT_min_order_book_volume_percentage in pairs file

### ISSUE THREAD

**Issue by peterpuglisi** [taniman/profit-trailer#1689]
The setting for DEFAULT_min_order_book_volume_percentage  in the PAIRS.properties file of the release has an extra underscore, should be DEFAULT_min_orderbook_volume_percentage going by the Wiki. Can we get this updated please ?

**Comment by YoJeff** [comment]
Release files as of 2.0.4 are fixed.
