### ISSUE TITLE
MAX COST REACHED working incorrect

### ISSUE THREAD

**Issue by zigzag-way** [taniman/profit-trailer#1691]
Im having this settings:
ETH market
DEFAULT_DCA_max_cost = 1
DEFAULT_DCA_max_buy_times = 7

DEFAULT_DCA_buy_percentage_1 = 100
DEFAULT_DCA_buy_trigger = -1.3
#SOM_DCA_buy_trigger = -5
DEFAULT_DCA_buy_percentage_2 = 50
DEFAULT_DCA_buy_percentage_3 = 50
DEFAULT_DCA_buy_percentage_4 = 25
DEFAULT_DCA_buy_percentage_5 = 30
DEFAULT_DCA_buy_percentage_6 = 25
DEFAULT_DCA_buy_percentage_7 = 20

and it gives me this DCA:

27/04/201821:13 (0D) | QSPETH-2.12 % | 0.000280140.00028975 2 | LOWBB RSI MAX COST REACHED | 65.954 | 5.033 | -1.3-1.3 | -2.77 | GAIN RSI (true) | -3.5254 | -3.52 | 579 | 1104 | 0.308656010.31988032 | $199.55 $206.81

So its 2 DCA levels, and total cost aout 200 UDS, with max cost - 1 eth.
What am I doing  wrong?

**Comment by YoJeff** [comment]
Screenshots, whole dca, related log entries related to the buys please.

**Comment by Fogazi** [comment]
Did you update to 2.0.1? Pretty sure this was resolved.

**Comment by zigzag-way** [comment]
Yes, it is now. 2.0.1 fix the problem.
