### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by MarcP1001** [taniman/profit-trailer#1692]
I keep getting this error when trying to upgrade to 2.01 from PT1. 
ERROR ProfitTrailerService - completeBalances - nl.komtek.pt.utils.i: ERROR: -1021, Timestamp for this request was 1000ms ahead of the server's time.
I have only tried to transfer over my BTC bot, not my ETH bot yet.  I have reset my server time, resynced my server time, asked my VPS provider to check the server time and they say there is no issue.  Have it set to sync with internet time.
I only get this error when running 2.0.
I have been working on this for 4 days now and it is really frustrating.  Any assistance would be appreciated.

**Comment by nimmeh** [comment]
I am having this issue too, none of the troubleshooting that @MarcP1001 tried worked for me either.

**Comment by SgtBatten** [comment]
Timestamp issues are time related. The time isn't matching between your bot and the exchange.

**Comment by SgtBatten** [comment]
Can you try on other computers? Just temporarily for testing

**Comment by MarcP1001** [comment]
I have tried different VPS same issue.  It is only an issue when I run 2.01 not PT 1.xx

**Comment by B0mBeur** [comment]
try to sync the time of your linux box

https://www.howtogeek.com/tips/how-to-sync-your-linux-server-time-with-network-time-servers-ntp/

**Comment by MarcP1001** [comment]
They are both windows VPS servers.

**Comment by B0mBeur** [comment]
http://www.thewindowsclub.com/change-time-server-windows-10

**Comment by MarcP1001** [comment]
I already tried that.  My windows time is -08:00.  I set my PT time to -08:00.  However, in PT1 it shows a time of 15:00 and my windows shows a time of 16:00.  Could this be the issue?  If so how would I correct the issue from there?
Thanks!

**Comment by MarcP1001** [comment]
Okay got it working had to change my server time to -9:00. PT time to -8:00.  It is now not getting the errors.
Marc

**Comment by SgtBatten** [comment]
Yes your VPS sounds like it was an hour off.. maybe due to daylight savings. Glad it's fixed

**Comment by MarcP1001** [comment]
Just got the timestamp error again after running 3 hours

**Comment by SgtBatten** [comment]
If you are getting occasional errors of any kind they are generally harmless. If you get constant errors or an error that stops the bot working that's when there is an issue

**Comment by TrueOsiris** [comment]
Same issue in docker ... but bizarrely only occasionaly.

**Comment by YoJeff** [comment]
For docker, map the hosts time down into the container.  (  -v /etc/localtime:/etc/localtime:ro )   if you google docker time drift, you will see this is common.

If your VPS cannot maintain time -- not much PT can do about that.
