### ISSUE TITLE
DEFAULT_take_profit_ settings don't work

### ISSUE THREAD

**Issue by ofilipowicz** [taniman/profit-trailer#1694]
```
DEFAULT_take_profit_wait_time = 5
DEFAULT_take_profit_percentage = 0.25
```

I have these settings. I was watching my bags being in a lot higher profit for over an hour. None of them has been sold (due to one of sell strategies being false)

**Comment by SgtBatten** [comment]
the price would have to be unchanged for 5 minutes with those settings. I find that unlikely.
you are missing the third variable.

https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_take_profit_reset_percentage_move
