### ISSUE TITLE
[DEFAULT_pending_order_wait_time] not working

### ISSUE THREAD

**Issue by Ghostdoge** [taniman/profit-trailer#1695]
DEFAULT_pending_order_wait_time = 120
DEFAULT_combined_cancel_pending_trigger = 1

Some of my coins were last bought well over 2 hours ago and are not being put into pending.

**Comment by SgtBatten** [comment]
Please upload screenshots of your entire pairs file, and screenshot for the riders on the exchange and a screenshot of the coins in the pairs log

**Comment by taniman** [comment]
no response
