### ISSUE TITLE
DEFAULT_take_profit_percentage not working

### ISSUE THREAD

**Issue by GvY85** [taniman/profit-trailer#1697]
I saw this issue being closed earlier but even with the right settings the "DEFAULT_take_profit_percentage" does not seem to work. 
I observed 2 coins for ~25min being around 1.25% gain and never getting above 1.75 or below 0.75 but still the coin was not (attempted to) sold.

Only thing I can think of is that it updates the values outside the normal 'ticker' so you cant see the value being out of range while it actually is? 
Otherwise this setting simply does not seem to work.

My settings:

DEFAULT_take_profit_percentage = 1
DEFAULT_take_profit_reset_percentage_move = 0.5
DEFAULT_take_profit_wait_time = 15

**Comment by GvY85** [comment]
using v2.0.1 btw, not tested on v2.0.0.

**Comment by SgtBatten** [comment]
Your timer would have started the second it hit 1% and would have reset if it dropped under 1 or went to 1.5 or more.

So with your example it's hard to say if there's an issue.

**Comment by arthurengeletrica** [comment]
My take profit isn't working
DEFAULT_DCA_take_profit_percentage = 10
DEFAULT_DCA_take_profit_reset_percentage_move = 3.3
DEFAULT_DCA_take_profit_wait_time = 1
I'm using only 1 minute just to test it, I have a coin in testmode with about 14.40%, according to what I read on wiki, I should sell if not deviate more than 3.3% in 1 minute
It had passed several minutes without changed more than 1% and it not soldtis WANBTC, at binance
the pair is WANBTC

The price haven't deviated more than 2% for several minutes and bot haven't sold it, even after restarting the bot

I was testing from 11:00 AM UTC 04/30/2018 to 11:10 AM UTC same day

**Comment by arthurengeletrica** [comment]
I'm also using vresion 2.01, which is so far the latest

**Comment by NikitaSotnikov** [comment]
@SgtBatten 
My take profit isn't working too.
I use this settings for test mode:
DEFAULT_take_profit_percentage = 0.01
DEFAULT_take_profit_reset_percentage_move = 2
DEFAULT_take_profit_wait_time = 1

Even with these settings, nothing works. In the section Sales, TAKE PROFIT is not displayed.

For example: If i use DEFAULT_max_profit = 1, MAX PROFIT is displayed.

**Comment by SgtBatten** [comment]
Okay thanks guys. Looks like there might be an issue

**Comment by conando2000** [comment]
Yeah it's broken since 2.0.0 and never worked.. would have been a neat way to finally have a timeout for trailing but nooo - hint: gotta save takeProfitData ;)

**Comment by taniman** [comment]
@conando2000 tnx for the hint man. Sorry for wasting your time. Your contribution is really appreciated 👍

**Comment by taniman** [comment]
patched for next release
