### ISSUE TITLE
DEFAULT_trailing_buy with different indicator?

### ISSUE THREAD

**Issue by matbuf** [taniman/profit-trailer#1698]
I think now DEFAULT_trailing_buy is set just on "GAIN" strategy, but I'm wondering if it could be possible to set up with other strategies.

let's made this example:

If I set up something like this
DEFAULT_A_buy_strategy = STOCHRSI
DEFAULT_A_buy_value = 0.02
_DEFAULT_trailing_buy_strategy = STOCHRSI
DEFAULT_trailing_buy_value = 0.2_

this result almost match the cross STOCHRSI of the binance client and I suppose it'll not be a big code work, since we already have this indicators, right?

**Comment by SgtBatten** [comment]
Trailing is based on price only and works on all strategies. 

Once all strategies are true it marks the price and trails it. This is efficient and is not likely to change.

For more info you can read https://wiki.profittrailer.com/doku.php?id=a_trailing_story

**Comment by SgtBatten** [comment]
I will add, if you wish to make a feature request for the ability to trail a certain strategy we have a seperate pt enhancements GitHub for this sorry.
