### ISSUE TITLE
Doubledown //simpledown buy style

### ISSUE THREAD

**Issue by Jonconnect** [taniman/profit-trailer#1701]
Hi,i dont have really try 2.0, but what about something like that :

DEFAULT_DCA_A_buy_style = Doubledown

or

DEFAULT_DCA_A_buy_style = Simpledown//default//normal something else.

**Comment by SgtBatten** [comment]
For double down like in v1 you simply need to set DEFAULT_DCA_buy_percentage = 100

So it's buys 100% of holdings every level. IE, doubles down.

Buy style is not a valid parameter in v2 as the percentages are fully customisable.

If you wish to request a new feature please use the pt enhancements repository. Click on taniman up top to see all the repositories.

**Comment by Jonconnect** [comment]
Ok thank's
