### ISSUE TITLE
Error OO - <!DOCTYPE html> // Api problem

### ISSUE THREAD

**Issue by Jonconnect** [taniman/profit-trailer#1704]
Hi,here the problem whit Polo USDT on pt 1.2.6.19. Tried on Pt 2.0.1.It's the same

 OO - <!DOCTYPE html>
 <html lang="en">
 <head>
 	<title>Po
 2018-04-29 03:11:35 ERROR ProfitTrailerService - CB - <!DOCTYPE html>
 <html lang="en">
 <head>
	<title>Po
 2018-04-29 03:11:36 ERROR ProfitTrailerService - TH - <!DOCTYPE html>
 <html lang="en">
 <head>
 	<title>Po

ERROR ProfitTrailerService - openOrders - nl.komtek.pt.utils.i: No value was returned

## Now i got this on pt 1.2.6.19 ( after tryed on pt 2.0.1)

 ERROR Application - Please fix: trading_apiKey -- nonce error: {"error":"Nonce must be greater than 1524994747665000000. You provided 15249951753090000."}

And Yesterday it was about my "default_apikey"

No any change whit my api.No problem whit my other licences on Bittrex and Binance.

I have tried to change the language on pt 2.0.1, no result .

It's a problem with Poloniex ?

Thank's

**Comment by SgtBatten** [comment]
https://wiki.profittrailer.com/doku.php?id=common_errors#doctype_html

**Comment by Jonconnect** [comment]
Thank you
