### ISSUE TITLE
Selling at a loss, reporting a profit

### ISSUE THREAD

**Issue by CryptoStack** [taniman/profit-trailer#1705]
Hi guys,

Today the bot bought ADAUSDT, sold at a profit but didnt fill the whole order then sold at a loss with the remaining order, but the problem is it reported a 10% profit.

![untitled 4](https://user-images.githubusercontent.com/38832761/39405655-fc4c1c7e-4beb-11e8-83db-4d36db04eb79.jpeg)
![untitled 2](https://user-images.githubusercontent.com/38832761/39405656-fc7e8862-4beb-11e8-924b-47c882ec2971.jpeg)
![untitled](https://user-images.githubusercontent.com/38832761/39405657-fcade44a-4beb-11e8-8cc0-1f353cf9ba6d.jpeg)

I think there was API problems but I am not sure, support on discord said I should post a issue here, so here it is.

**Comment by SgtBatten** [comment]
#777

**Comment by Mikeeetrue** [comment]
I'v faced the same problem once on 2.0.

**Comment by taniman** [comment]
We will continue following this problem in #1725
