### ISSUE TITLE
Paper Trading not working without Real Balance

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1706]
I've set start_balance = 10 BTC in the Pairs properties, and server.test_mode = true in the Application properties.

PT is not doing any paper trading. Is it looking for a real 10BTC balance before doing paper trading? 

I see the BAL: 0.000 and TCV: 0.000.

If this is the case, PT should do paper trading even withouth any real balance.

**Pairs Properties**
#-------------------------------
#CryptoGnome v2.0 Settings
#-------------------------------
start_balance = 10
market = BTC
enabled_pairs = ALL
hidden_pairs = BNB
keep_balance = 0
#-------------------------------
#Options (:P)
#-------------------------------
DEFAULT_buy_max_change_percentage = 8
#DEFAULT_buy_min_change_percentage = -10
DEFAULT_trading_enabled = true
max_trading_pairs = 10
pair_min_listed_days = 14
DEFAULT_DCA_enabled = true
DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 2
DEFAULT_min_buy_volume = 500
DEFAULT_min_buy_price = 0
DEFAULT_max_buy_spread = 1
DEFAULT_min_orderbook_volume_percentage = 100
#-------------------------------
#v2.0 Multiple Buy Strategies
#-------------------------------
DEFAULT_A_buy_strategy = STOCH
DEFAULT_A_buy_value = 17
DEFAULT_A_buy_value_limit = -2.5
DEFAULT_B_buy_strategy = RSI
DEFAULT_B_buy_value = 32
DEFAULT_B_buy_value_limit = 0
DEFAULT_trailing_buy = 0
#v2.0 Multiple SELL Strategies
#---------------------------
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1
DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 40
DEFAULT_trailing_profit = 0.16
#---------------------------
#Hidden Pairs
#---------------------------
BNB_trading_enabled = false
#---------------------------
#Panic Buttons
#---------------------------
#PPT_panic_sell_enabled = true
DEFAULT_panic_sell_enabled = false
DEFAULT_sell_only_mode_enabled = FALSE
DEFAULT_rebuy_timeout = 2
#---------------------------
#Triggers
#---------------------------
price_trigger_market = BTC
price_rise_trigger = 0
price_rise_trigger_recover = 0
price_drop_trigger = 0
price_drop_recover_trigger = 0
#---------------------------
#BTC BLACKLIST
#---------------------------
TRX_trading_enabled = false

**Comment by taniman** [comment]
paper trading works without  a realbalance because it does not even look at your real balance. Try starting from an empty slate

**Comment by SgtBatten** [comment]
Resetting the test data should trigger balance to change to 10

**Comment by cryptomail2018** [comment]
how to reset Test Data ?
