### ISSUE TITLE
ProfittrailerData files gets corrupted

### ISSUE THREAD

**Issue by wasif28** [taniman/profit-trailer#1709]
i want to suggest that in the next update fix this issue where the files get corrupted every time the bot crashes or if running on a raspberry pi it crashes the files get corrupted. do some kind of a fix where the bot is auto backing up after every 10 secs or something like that and whenever the bot feels like its files are corrupted it fetches the last auto save. this will make the process seamless and also help people using DCA who have to manually add the DCA times of certain bought coins if their bot crashes and after they have to delete the DATA.json file. this issue makes a huge problem for users having unexpected crashes or shutdowns. the patch can help people running their bots 24/7 without human attention needed this process will make the bot not requiring attention after power outages or software crashes.

Will be waiting for this patch and your response!

**Comment by cupid-stunt** [comment]
I had the same problem. However, replacing the profittrailerData file with the latest backup file from the Backup folder reset all my trades.

**Comment by wasif28** [comment]
Im asking for a patch to make this process autonomous not manual because the bots primary function is to work while you are sleep so during your sleep when the bot becomes problematic and corrupts the files you miss a lot of opportunities.

**Comment by But4ler** [comment]
While waiting for PT to manage its own backups, you can use Ninjabackup on linux.
It does the job well and simply
https://www.techrepublic.com/article/how-to-automate-database-backup-with-backupninja/

**Comment by wasif28** [comment]
ill try doing this but do consider my request this will be helpful in making the bot more superior and easier for the average consumer!

**Comment by taniman** [comment]
The bot does backup your safe file to backup folder. So you can reset to a previous state if the file gets corrupted.

I have been running multiple bots for months with any data file corruption. 
So while this happens on some systems. I can assure you that most systems run without an issue.

But we are working on better incorruptable systems to save the file
