### ISSUE TITLE
swagger API: settingsapi/settings/save not working correctly

### ISSUE THREAD

**Issue by Juleseck** [taniman/profit-trailer#1711]
Tried using the saveSetting. I filled in all parameters correctly, and this is what happens to my pair settings:

![afbeelding](https://user-images.githubusercontent.com/15907940/39409117-89786356-4be1-11e8-8036-396d91249dd7.png)

Request url used (from swagger-ui after filling in the parameters) :
http://localhost:8081/settingsapi/settings/save?fileName=PAIRS&configName=default&saveData=market%20%3D%20ETH%20start_balance%20%3D%2010%20enabled_pairs%20%3D%20ALL%20hidden_pairs%20%3D%20ALL%20keep_balance%20%3D%200.0%20keep_balance_percentage%20%3D%200%20pair_min_listed_days%20%3D%200%20max_trading_pairs%20%3D%202%20orderbook_profit_calculation%20%3D%20true%20%20consecutive_buy_trigger%20%3D%200%20consecutive_sell_trigger%20%3D%200%20%20price_trigger_market%20%3D%20BTC%20price_rise_trigger%20%3D%200%20price_rise_recover_trigger%20%3D%200%20price_drop_trigger%20%3D%200%20price_drop_recover_trigger%20%3D%200%20%20DEFAULT_trading_enabled%20%3D%20true%20DEFAULT_DCA_enabled%20%3D%20true%20%20DEFAULT_initial_cost%20%3D%200%20DEFAULT_initial_cost_percentage%20%3D%202%20DEFAULT_min_buy_volume%20%3D%200%20DEFAULT_min_buy_price%20%3D%200%20DEFAULT_max_buy_spread%20%3D%200%20DEFAULT_min_order_book_volume_percentage%20%3D%20100%20%20DEFAULT_A_buy_strategy%20%3D%20LOWBB%20DEFAULT_A_buy_value%20%3D%2040%20DEFAULT_A_buy_value_limit%20%3D%200%20%20DEFAULT_B_buy_strategy%20%3D%20RSI%20DEFAULT_B_buy_value%20%3D%2035%20DEFAULT_B_buy_value_limit%20%3D%200%20%20%20DEFAULT_trailing_buy%20%3D%200.25%20%20DEFAULT_A_sell_strategy%20%3D%20GAIN%20DEFAULT_A_sell_value%20%3D%200.4%20DEFAULT_trailing_profit%20%3D%200.5%20DEFAULT_max_profit%20%3D%200%20%20%20DEFAULT_stop_loss_trigger%20%3D%200%20DEFAULT_stop_loss_timeout%20%3D%200%20DEFAULT_panic_sell_enabled%20%3D%20false%20DEFAULT_sell_only_mode_enabled%20%3D%20true%20DEFAULT_rebuy_timeout%20%3D%2015%20%20DEFAULT_buy_min_change_percentage%20%3D%200%20DEFAULT_buy_max_change_percentage%20%3D%200%20%20%23%20Rename%20me%3F%20DEFAULT_pending_order_wait_time%20%3D%200%20DEFAULT_combined_cancel_pending_trigger%20%3D%200%20%20DEFAULT_take_profit_wait_time%20%3D%200%20DEFAULT_take_profit_percentage%20%3D%200&license= removed for obvious reasons

**Comment by SgtBatten** [comment]
Can you please post the formatting of the contents you entered. I will check exactly how it needs to be formatted with the devs

**Comment by Juleseck** [comment]
@SgtBatten ofcourse. Thanks for the quick response: 

market = ETH start_balance = 10 enabled_pairs = ALL hidden_pairs = ALL keep_balance = 0.0 keep_balance_percentage = 0 pair_min_listed_days = 0 max_trading_pairs = 2 orderbook_profit_calculation = true  consecutive_buy_trigger = 0 consecutive_sell_trigger = 0  price_trigger_market = BTC price_rise_trigger = 0 price_rise_recover_trigger = 0 price_drop_trigger = 0 price_drop_recover_trigger = 0  DEFAULT_trading_enabled = true DEFAULT_DCA_enabled = true  DEFAULT_initial_cost = 0 DEFAULT_initial_cost_percentage = 2 DEFAULT_min_buy_volume = 0 DEFAULT_min_buy_price = 0 DEFAULT_max_buy_spread = 0 DEFAULT_min_order_book_volume_percentage = 100  DEFAULT_A_buy_strategy = LOWBB DEFAULT_A_buy_value = 40 DEFAULT_A_buy_value_limit = 0  DEFAULT_B_buy_strategy = RSI DEFAULT_B_buy_value = 35 DEFAULT_B_buy_value_limit = 0   DEFAULT_trailing_buy = 0.25  DEFAULT_A_sell_strategy = GAIN DEFAULT_A_sell_value = 0.4 DEFAULT_trailing_profit = 0.5 DEFAULT_max_profit = 0   DEFAULT_stop_loss_trigger = 0 DEFAULT_stop_loss_timeout = 0 DEFAULT_panic_sell_enabled = false DEFAULT_sell_only_mode_enabled = true DEFAULT_rebuy_timeout = 15  DEFAULT_buy_min_change_percentage = 0 DEFAULT_buy_max_change_percentage = 0  # Rename me? DEFAULT_pending_order_wait_time = 0 DEFAULT_combined_cancel_pending_trigger = 0  DEFAULT_take_profit_wait_time = 0 DEFAULT_take_profit_percentage = 0

**Comment by SgtBatten** [comment]
I am not home to test right now but I'm thinking it may need comma seperators.

Basing this off the way it displays the contents of the file when using the load API operation.

**Comment by Juleseck** [comment]
@SgtBatten I've tried separating the lines with comma's as you said, but it doesn't make a difference.

**Comment by SgtBatten** [comment]
Okay thanks for trying. Exact same result?

**Comment by Juleseck** [comment]
@SgtBatten yes, same result
![afbeelding](https://user-images.githubusercontent.com/15907940/39418367-520d43ea-4c5a-11e8-96cf-1804574391db.png)

**Comment by cvthub** [comment]
you have to encode the special signs like =, '', \n

whitespace = %20
equal-sign = %3D
linebreak = %0A

using curl it looks like this: 

curl -d "license=xxx&fileName=INDICATORS&saveData=#BB_period%20%3D%20300%0A#BB_sma%20%3D%2012%0A%0A" http://localhost:8081/settingsapi/settings/save

would set

#BB_period = 300
#BB_sma = 12

**Comment by Juleseck** [comment]
@cvthub did you test it? I've just used your saveData in my link as a test, and this is what happens:
![afbeelding](https://user-images.githubusercontent.com/15907940/39464856-241f35f8-4d20-11e8-9c6c-fc7ff6f44fdf.png)

**Comment by cvthub** [comment]
Well, the above curl cmd worked just fine for me... 
How do you call the endpoint?

**Comment by SgtBatten** [comment]
i think literally pasting it into the swagger ui

**Comment by Juleseck** [comment]
I'm just using the request url instead of curl. Should also work right?

http://localhost:8081/settingsapi/settings/save?fileName=PAIRS&configName=default&saveData=BB_period%20%3D%20300%0A#BB_sma%20%3D%2012%0A%0A&license= removed

this is the exact url used with your saveData parameter, with result in pic above.

**Comment by cvthub** [comment]
Using the Swagger UI it is not working, since the input fields are generated as simple input fields, which do not allow line breaks. Changing the html element from input to textarea would allow line breaks in the field, but Swagger does not support that configuration, so it must be changed manually using some kind of web-development tools. 

Please note, that the API is interesting when used with external tools/scripts like PTF or PTM. These tools (also curl) are able to build the calls which work with the PT-API.

**Comment by Juleseck** [comment]
@cvthub I know what you mean.. I'm just asking why the request url is not working with the CORRECT saveData parameter you just gave me above. It is supposed to work if that are the right encodes for the special characters right?

I'm creating a tool for PT myself, so that's why I want to use the API. I will look into using curl with java if the request url won't be working correctly.

**Comment by Juleseck** [comment]
Any response?

**Comment by cvthub** [comment]
Its working using curl with the correct (my) saveData parameters, but its not working using the forms provided by the swagger-ui. 

If you plan to use java, then try to pass the parameters like its done when using html <textarea> element. 

The swagger-ui is not working, because the html element <input> does not support linebreaks. As I mentioned above, changing <input> to <textarea> would propagate the linebreaks w/o need to encode then specially.

**Comment by ochiengj** [comment]
@Juleseck Did you ever get this to work?
