### ISSUE TITLE
0% profit calculating 100% bought price as profit

### ISSUE THREAD

**Issue by weirders** [taniman/profit-trailer#1712]
when 0% profit hits in any of the logs, the profit is the total bought amount, not 0. This effects the TCV too. When sold at zero, it also counts the full bought amount as profit incrrectly.
![nilpercent](https://user-images.githubusercontent.com/34236285/39410256-80a7f7aa-4bf5-11e8-96f5-c98e114962a6.PNG)

**Comment by SgtBatten** [comment]
That coin didn't have a bought price set.

You needed to set it in the hotconfig. Otherwise, yes it will be all profit.
