### ISSUE TITLE
No actual RSI value on the SSV column

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1718]
No actual RSI value on the SSV column.  In the Tradingview, RSI is overbought already for 5 min candle.   My ETH bot is working fine which has the RSI value. Not sure if this is due to using USDT.

[Screenshot](https://cdn.discordapp.com/attachments/406439964356640768/440304476507865098/image.png)

**Comment by SgtBatten** [comment]
Screenshot of DCA settings please.

Also clear the browser cache and confirm it's still missing. Shift+f5 on chrome

**Comment by cybermizrach** [comment]
here is the DCA properties
#-----------------------------------
#CryptoGnome v2.0 BETA Settings#
#########-FEED ME DCA-##########
#-----------------------------------

DCA_keep_balance = 0
DCA_keep_balance_percentage = 0
DEFAULT_DCA_max_cost = 0


#-----------------------------------
#v2.0 Multiple DCA Buy Strategies
#-----------------------------------
DEFAULT_DCA_A_buy_strategy = LOWBB
DEFAULT_DCA_A_buy_value = 5
DEFAULT_DCA_A_buy_value_limit = -2.5

DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_value = 33
DEFAULT_DCA_B_buy_value_limit = 5

DEFAULT_DCA_trailing_buy = 0.2


#-----------------------------------
#DCA ME
#-----------------------------------
DEFAULT_DCA_max_buy_times = 20

DEFAULT_DCA_buy_percentage_1 = 50
DEFAULT_DCA_buy_trigger = -0.25
DEFAULT_DCA_buy_percentage_2 = 50
DEFAULT_DCA_buy_percentage_3 = 50
DEFAULT_DCA_buy_percentage_4 = 50
DEFAULT_DCA_buy_percentage_5 = 50
DEFAULT_DCA_buy_percentage_6 = 50
DEFAULT_DCA_buy_percentage_7 = 50
DEFAULT_DCA_buy_percentage_8 = 50
DEFAULT_DCA_buy_percentage_9 = 50
DEFAULT_DCA_buy_percentage_10 = 50
DEFAULT_DCA_buy_percentage_11 = 50
DEFAULT_DCA_buy_percentage_12 = 50
DEFAULT_DCA_buy_percentage_13 = 50
DEFAULT_DCA_buy_percentage_14 = 50
DEFAULT_DCA_buy_percentage_15 = 50
DEFAULT_DCA_buy_percentage_16 = 50
DEFAULT_DCA_buy_percentage_17 = 50
DEFAULT_DCA_buy_percentage_18 = 50
DEFAULT_DCA_buy_percentage_19 = 50
DEFAULT_DCA_buy_percentage_20 = 50


#-----------------------------------
# v2.0 Multiple DCA SELL Strategies
#-----------------------------------
DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 1

DEFAULT_DCA_B_sell_strategy = RSI
DEFAULT_DCA_B_sell_value = 50

DEFAULT_DCA_trailing_profit = 0.2
DEFAULT_DCA_max_profit = 0



#-----------------------------------
# Options
#-----------------------------------
DEFAULT_DCA_min_orderbook_volume_percentage = 100

DEFAULT_DCA_ignore_sell_only_mode = true

DEFAULT_DCA_max_buy_spread = 1.5
#DEFAULT_DCA_rebuy_timeout = 10

#-----------------------------------
# Extra Triggers
#-----------------------------------
DEFAULT_DCA_stop_loss_trigger = 0
DEFAULT_DCA_stop_loss_timeout = 0
DEFAULT_DCA_pending_order_wait_time = 0

**Comment by cybermizrach** [comment]
@SgtBatten I've sold the coins already using GAIN only. I'll check it again once I have some coins on the DCA log.

**Comment by cybermizrach** [comment]
@SgtBatten I've cleared the cache but the RSI value is not displayed.  
[Screenshot](https://cdn.discordapp.com/attachments/406439964356640768/440355609444089857/unknown.png)

Is this a USDT issue only?

**Comment by cybermizrach** [comment]
I've restarted the bot, and it's now working.

**Comment by SgtBatten** [comment]
ahh great. i was really struggling to think what this one might be.

Thank for the update

**Comment by cybermizrach** [comment]
Thanks @SgtBatten !
