### ISSUE TITLE
The content of the pairs, DCA and Indicator Properties are copied to the second bot

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1719]
I have a USDT bot with Port 8070, and created another BTC bot with port 8000 by copying the USDT folder to another folder.

In the BTC bot, I've place cryptognome's PT V2 Pairs, DCA and Indicator settings via the BTC PT bot GUI. To my surprise, the  cryptognome's PT settings were also copied to my USDT bot. 

This should not happen. Where are the Pairs, DCA and Indicator settings saved?  It looks like PT is saving the settings on the bots with the same IP address and same license.

**Comment by SgtBatten** [comment]
You need to use different API keys and different names for the settings files if the bots are on the same license.

Otherwise they will duplicate

**Comment by SgtBatten** [comment]
If you have this issue you can use the swagger API https://wiki.profittrailer.com/doku.php?id=swagger_api

Or you can change the default API key and it should ask you to choose a unique name on first boot.

**Comment by cybermizrach** [comment]
@SgtBatten Do you mean different default key and Trading Key?

**Comment by cybermizrach** [comment]
I've changed a default key and it worked.

**Comment by SgtBatten** [comment]
yes testmode is still an instance you are running. default and trading key should be unique.

**Comment by cybermizrach** [comment]
@SgtBatten It worked. Thanks!
