### ISSUE TITLE
Problem with license keys

### ISSUE THREAD

**Issue by cryptroid** [taniman/profit-trailer#1724]
I keep getting this error.  I am installing on a new VPS server, I have already made brand new API keys and removed the old ones and added the new ones using PTAssistant.

Why else would PT not recognize my license key?

![screen shot 2018-04-30 at 12 05 44 am](https://user-images.githubusercontent.com/35219101/39418129-67017d36-4c0d-11e8-95bc-991fec835668.png)

**Comment by SgtBatten** [comment]
Please check the common errors in the wiki and come to discord for suooort. Gihib is for bugs.
