### ISSUE TITLE
Lost bought price on new purchase

### ISSUE THREAD

**Issue by darkban** [taniman/profit-trailer#1726]
Although using an acconut only for the bot and not having coins purchased by me ... he loses continually the prices that he buys ... on 50 pairs he has lost 5 and it makes you waste time doing the calculations and setting it manually. .. correct this problem because otherwise you can not use profit trailer and it is not reliable if it loses prices continuously ... Please correct the problem of average calculator is an absurd thing.

**Comment by SgtBatten** [comment]
check your log, you likely had api issues at the time of purchase.

**Comment by darkban** [comment]
no I have no problem of api ... this problem often occurs ... and it is not normal that the bot does not resume communication and read what he bought even if he lost the connection with the bees ... is a big bug to correct

**Comment by echthard** [comment]
Looks like same bug I posted : 

https://github.com/taniman/profit-trailer-enhancements/issues/287
https://github.com/taniman/profit-trailer/issues/1725

**Comment by SgtBatten** [comment]
no this is not related to partial sellsas far as i can tell from the OP

**Comment by echthard** [comment]
The issue I posted in enhancements is without partial sells. (first link)

**Comment by XcidTrader** [comment]
<img width="1167" alt="screen shot 2018-05-01 at 09 56 27" src="https://user-images.githubusercontent.com/35023898/39521961-f57bcc92-4e10-11e8-9fb0-69915dcc4b62.png">

Is the attached what you are referring to?
I get it on Bittrex with Ver 2.0, binance works fine.
Bought price and date disappears from PT. 
I havent restarted the bot to cause this. Its just random with the new update.

**Comment by taniman** [comment]
We are aware and are still working on the best way of resolving the average calculator.

But it's not as simple as adding and substracting because of multiple DCA's, partial buys, partial sells, fee, BNB, binance rounding and so on.

So we are working on it.
