### ISSUE TITLE
Bought price edit/reset in hotconfig not working?

### ISSUE THREAD

**Issue by kme77** [taniman/profit-trailer#1729]
I'm currently running PT2.01, I had some manual trades on binance which showed on PT as pending but with $0.00 bought price. When I sold them manually  PT is calculating the profit as the full amount sold (sold price - zero)
I've tried resetting the data and updating the price with

qlc_reset_stored_average = true
qlc_bought_price = 0.1234

but after several attempts it fails to change anything.
Am I doing something wrong?

**Comment by SgtBatten** [comment]
hotconfig doesn't work on the sales log. it would have worked before selling though
