### ISSUE TITLE
Change Log Updates: application.properties

### ISSUE THREAD

**Issue by smportis** [taniman/profit-trailer#173]
Suggest adding these comments to change log in applications.properties:

'### OCT 25, 2017 Removed server.port, server.additionalPort,
'###              commented out server.timeZoneOffset, server.sitename,
'###              and server.password.
'###              Added trading.logHistory = 2

**Comment by taniman** [comment]
Did I do all that? Have not noticed... :(

**Comment by taniman** [comment]
the application.properties is not source controlled so I cannot do a diff on it

**Comment by taniman** [comment]
Something must be wrong I really dont remember doing this....

**Comment by smportis** [comment]
I'm just going from what I downloaded.... Sounds like you need some sleep!!
