### ISSUE TITLE
Editing bought price in sales log after trade complete?

### ISSUE THREAD

**Issue by kme77** [taniman/profit-trailer#1730]
Is there a way to edit the bought price in the sales log (like it is possible in hotconfig for active trades) 

My sales log is VERY wrong and I need to either delete or edit some entries in the logs.

**Comment by Jamavo83** [comment]
Had the same problem here.  Also had a problem with a partial sell, after selling off about 70%, the remaining balance lost its bought price.

**Comment by mavverick** [comment]
Same error here

![image](https://user-images.githubusercontent.com/4382042/39502950-792fd894-4d99-11e8-8075-09119642822d.png)

**Comment by taniman** [comment]
There is no way to edit this other than 
stopping the bot.
editing the ProfitTrailderData.json
restarting the bot
