### ISSUE TITLE
completebalances - nl-komtek. pt. utils. i:error - 1021 timestamp for this request is outside of the recvwindow

### ISSUE THREAD

**Issue by SAMI3711** [taniman/profit-trailer#1731]
I'm getting this error since i changed to pt. v2/
completebalances - nl-komtek. pt. utils. i:error - 1021 timestamp for this request is outside of the recvwindow

**Comment by MisterWonderful** [comment]
Likewise

**Comment by eweblinxwebs** [comment]
Any update on this error as i am getting it as well?? Thanks

**Comment by jolllysworld** [comment]
me too!!!

**Comment by StudioZanforlin** [comment]
same error

**Comment by YoJeff** [comment]
There have been several releases since the last activity on this issue.   If this is still an issue with v2.0.5 resubmit with the proper format.
