### ISSUE TITLE
Every time I restart PT2 lost sales data

### ISSUE THREAD

**Issue by mavverick** [taniman/profit-trailer#1732]
Every time I restart PT2 lost sales data and statistics... 
![image](https://user-images.githubusercontent.com/4382042/39431321-c2e5ca4a-4c66-11e8-9ba4-729421c77923.png)
![image](https://user-images.githubusercontent.com/4382042/39431339-d11edb4c-4c66-11e8-9d6a-a15b21f577fc.png)

**Comment by taniman** [comment]
is your market chaning from BTC to something else when this happens? Cause if you data is being saved there is not reasong for the sales log to disappear. 

Have you tried the latest version?

**Comment by YoJeff** [comment]
issue timed out awaiting information....
