### ISSUE TITLE
Initial_Cost_Percentage

### ISSUE THREAD

**Issue by Noto123** [taniman/profit-trailer#1735]
Dear Team,

This morning I changed my initial buy settings, hoping to get a 0.74% buy of about $15

DEFAULT_Initial_Cost = 0
DEFAULT_Initial_Cost_Percentage = 0.74

Instead the first buy was $1700, about 74% of my budget... luckily I was still in test mode but this could have been a nasty surprise. Attached is a screenshot of the buy in the console. There was an error right after the buy but I don't know if this is related.

Hope it helps to resolve this issue.

Kind regards,
Maarten

![2018-04-30 10_42_09-107 173 250 174 - pt test error and xmr purchase](https://user-images.githubusercontent.com/38527758/39445172-75a1701e-4cba-11e8-9926-977dd4a1370e.png)

**Comment by Noto123** [comment]
0.2 btc

Maybe easier: @maartenniederer on telegram

**Comment by Noto123** [comment]
Btw, it’s a test bot, I don’t mind giving you access so you can see the
settings I was using

**Comment by LoukisD** [comment]
Guys I have the same issue 2 days now. My bot started buying 2x, 3x, 4x even 30x more than what I have set as initial_buy_percentage. (I made the same comment also on issue #1740 which is similar to this, in order to let PT support know that it is one more bot with that problem).

**Comment by carneiroid** [comment]
Same problem here.  Im in test mode on 1.4% initial_buy_percentage ...bot ran fine for a day, now is throwing out atrocious numbers and ran out my capital in a few hour with barely any dca'ing , exactly like above, 2x, 3x, 10x...           running ver v2.0.1

**Comment by BeldarConehead** [comment]
Same problem here. In addition, my DCA log inaccurately shows how many times a coin has DCA'd. I have settings for 20 DCA's yet some coins went wild and exceeded the 20 but only show 6 or 14 times DCA'ing in the log.

**Comment by Noto123** [comment]
Has this been resolved in 2.0.3?

**Comment by SgtBatten** [comment]
No we have not changed anything with this yet. It seems to be isolated to testmode but we will look into it when we can.

**Comment by Noto123** [comment]
Sorry, not just in test mode :(

**Comment by taniman** [comment]
@Noto123 I am looking into this. But from your screenshot I am not seeing any buys that happened with 0.74.

also if you balance is 0.2 it's impossible to buy 0.74 of a coin. 

What coin did you incorreect buy according to you?
Because in th escreenshot you showen XMRBTC. But that is a DCA buy so it's not an initial buy.

**Comment by Noto123** [comment]
The 0.74 was a percentage, wish I had that much btc ;)

**Comment by taniman** [comment]
@Noto123 You did not answer my other question. What coin did buy incorrect? Cause XMRBTC was a DCA buy

**Comment by JiriDrak** [comment]
I had the same problem in 2.0.3, so I used DEFAULT_initial_cost instead of DEFAULT_initial_cost_percentage. Today I tried it again in 2.0.7 and the problem still persists.

My TCV: 6.646 SB: 6.780

DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 1

All my new purchases today are around 0.046-7 ETH instead of 0.066-7 ETH.

**Comment by taniman** [comment]
@JiriDrak What is your available balance for PAIRS? 
Also are you using keep_balance?

Cause initial cost percentage is TCV - keep_balance

**Comment by JiriDrak** [comment]
So my mistake, i did not notice that keep balance affects the initial cost percentage in V2. Now everything is clear to me.

**Comment by taniman** [comment]
@JiriDrak  Great to hear.

**Comment by taniman** [comment]
Original answer is mostly answered with answer I just gave above. Also this issue is a bit outdated as most things in here I see have been solved in the latest versions or missing proper documentation

so any one with a new issue running the latest version should create a new issue
