### ISSUE TITLE
TPV, we miss you! 

### ISSUE THREAD

**Issue by n0ts0subtle** [taniman/profit-trailer#1738]
What ever happened to the Total Pending Value from PT V.1? All these other awesome integrations and metrics have been put into V2 and TPV is gone? I hear the devs thought it was worthless and decided to keep it out but the customers loved it. At least it gives us some semblance of reasonable investment expectation unlike v2. They should really put it back in.

**Comment by NOP-Commander** [comment]
It's already requested: https://github.com/taniman/profit-trailer-enhancements/issues/277 You should give a thumb up or add a comment there since this repo is not for feature requests but for bugs only. Thanks!
