### ISSUE TITLE
[Feature Request] Have PT accept "order" requests from AV

### ISSUE THREAD

**Issue by machyy1** [taniman/profit-trailer#1739]
Instead of having AV place orders on the exchanges directly, have it send the "order" to PT.  PT can then decide whether or not to actually place the order.  Meaning, PT can still enforce things like "Max Pairs" or "Min Balance" etc.  So even if an alert happens via AV, PT still choses based on the standard rules whether or not to send that order on to the exchange.

**Comment by NOP-Commander** [comment]
What is "AV"?

**Comment by SgtBatten** [comment]
Please submit feature requests here: https://github.com/taniman/profit-trailer-enhancements
