### ISSUE TITLE
[Feature Request] New Strategie:  CrossOver DEMA

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer#1741]
Hi
The DEMA CrossOver allows various simple strategies to set up as much for the purchase as for this protected in bearish period. (no buying so fast > slow)

**Formula:** DEMA = ( 2 * EMA(n)) - (EMA(EMA(n)), where n= period
https://www.investopedia.com/ask/answers/121814/what-double-exponential-moving-average-dema-formula-and-how-it-calculated.asp

**Example of a Gekko strategy:**  https://gekko.wizb.it/docs/strategies/example_strategies.html#DEMA
**Many Explanations:** https://bitcointalk.org/index.php?topic=60501.0

Example of a strategy:
Indicator
```
DEMA_cross_candles = 3
DEMA_candle_period = 3600
DEMA_fast_length = 21
DEMA_slow_length = 10
```

Pairie
```
DEFAULT_C_buy_strategy = DEMACROSS
DEFAULT_C_buy_value = 0.25
DEFAULT_C_buy_value_limit = 0

DEFAULT_C_sell_strategy = DEMACROSS
DEFAULT_C_sell_value = -0.25
DEFAULT_C_sell_value_limit = 0
```

Thank you for your work on this great project that is PT!

**Comment by SgtBatten** [comment]
Great post but please submit feature requests on the enhancements repository.

https://github.com/taniman/profit-trailer-enhancements
