### ISSUE TITLE
[PT 2.0.1][Bug] DCA Level Counter does not work correctly

### ISSUE THREAD

**Issue by d1rt** [taniman/profit-trailer#1743]
From time to time DCA couter does not increase DCA Level so I had to increase it in HotConfig (XXX_DCA_set_buy_times).

For example, I get a Telegram message:

```
BINANCE
Just bought: ONTBTC (1)
Cost: 0,00590145
Rate: 0,00087950
```

Then I check in the DCA log and see that the purchased volume has increased, but the DCA counter mark has not changed - still 0 level instead 1.

OR I get:

```
BINANCE
Just bought: STRATBTC (4)
Cost: 0,00928652
Rate: 0,00071600
```

But still see 3 level in DCA log. In the same time the purchased volume = 4 level.

This happens both on Bittrex and Binance accounts.

Another bug in DCA functionality

https://imgur.com/tPBkIPd

Please take a look - there is 3 DCA level for 4 orders but Total Cost is different!
I don't use percentage for initial cost - fixed values only

I guess this is also related with DCA counter. It did not increase, although the purchase was made

**Comment by YoJeff** [comment]
Duplicate #1609
