### ISSUE TITLE
Source code zip/tar File Empty

### ISSUE THREAD

**Issue by MLAnalyst** [taniman/profit-trailer#1745]
I did not find the source code in the listed source code file (Source code (zip) and Source code (tar.gz)) Please advise if it is relocated or misplaced. All other user/developer may not be able to contribute and use this product. 

**Let me know if there is licence restriction apply on Profittrailer opensource code.** 

Thank you!

**Comment by YoJeff** [comment]
There is no source code available.   This is a closed source product.
