### ISSUE TITLE
[REQ] Order book depth setting

### ISSUE THREAD

**Issue by Mtrade** [taniman/profit-trailer#1746]
Requesting a new setting to allow for the ability to go deeper into the order book (configurable by a % limit for example) to execute a trade. This is of particular importance when trying to DCA and buy cost needed is increasing, and the coin volume and order book is thin.
Ex. When trading with higher initial cost on a low volume coin, an Anderson DCA trying to double up might not have enough quantity at the lowest ask to execute.

**Comment by YoJeff** [comment]
This is for bugs only, feature requests go here
https://github.com/taniman/profit-trailer-enhancements/issues
