### ISSUE TITLE
show DEFAULT_take_profit time in PAIRS and DCA table

### ISSUE THREAD

**Issue by JHenneberg** [taniman/profit-trailer#1747]
wouldn't it be nice if the time (TPT = take profit time) which is left before the DEFAUL_take_profit sell takes place would be shown in the PAIR and DCA GUI in the SSV and SST column. Also maybe the limit in which the percentage can move (TPP = take profit percentage)

DEFAULT_take_profit_percentage = 0.8
DEFAULT_take_profit_time = 60
DEFAULT_take_profit_reset_percentage_move = 0.2

| Date       | Coin | Sale | SSV    | SST  | P%  |
|------------|------|------|--------|------|-----|
| 01.05.2018 | XYZ  | GAIN | 0.7    | 1.0  | 0.7 |
|            |      | TPT  | 34     | 60   |     |
|            |      | TPP  | +/-0.2 | -0.1 |     |

**Comment by YoJeff** [comment]
If it looks like a feature request, and smells like a feature request.... It goes in the feature request github ;)

https://github.com/taniman/profit-trailer-enhancements/issues
