### ISSUE TITLE
AverageCalculator FIX IT PLS

### ISSUE THREAD

**Issue by darkban** [taniman/profit-trailer#1748]
Boys fixed this bug ... it's an unprecedented thing loses 5 or 6 times a day the purchase price ... so it's impossible ... I can not manually put it every time ... my server and connection works perfectly and generates me a day 5 or 6 times the exact same problem and I manually have to fix it ... if I do not fix it what happens? why is this problem always generated several times a day?

**Comment by SgtBatten** [comment]
no idea, ive never lost a bought price except bnb whihc will always get lost

**Comment by SgtBatten** [comment]
Duplicate of #1726 

Your own issue
