### ISSUE TITLE
No Heartbeat, Error Refreshing Data after upgrade

### ISSUE THREAD

**Issue by russwoods** [taniman/profit-trailer#1749]
I'm trying to update to version 2 on a RaspberryPI. I followed the upgrade instructions, and double checked everything, but the bot is not running. I just get the error message that "There was an error while refreshing data from ProfitTrailer". Also noticed there is no heartbeat, and the logout, etc is not able to be used. 
![screen shot 2018-05-01 at 3 55 22 pm](https://user-images.githubusercontent.com/26367755/39497686-5cf46aea-4d59-11e8-914d-a09742fccb3c.jpg)

**Comment by SgtBatten** [comment]
that looks like the bot is not actually running, it may have crashed or paused, hence no buttons work

**Comment by russwoods** [comment]
Thanks @SgtBatten, any info on how to get the bot running again? I've run out of ideas.

**Comment by YoJeff** [comment]
Jump in discord support please -- this is for bugs.
