### ISSUE TITLE
API to set the bought price

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1750]
I couldn't find any API option to set the bought price and DCA level in the  https://wiki.profittrailer.com/doku.php?id=swagger_api. Can someone tell me where to find it or how?

**Comment by SgtBatten** [comment]
use the hotconfig for this

**Comment by cybermizrach** [comment]
@SgtBatten I'm working on an add-on that requires setting the  bought price and DCA level. 
@clownfish44 Has asked me to post this here since it should be part of the core functionalities.  See below: 
[https://github.com/taniman/profit-trailer-enhancements/issues/293#issuecomment-385831437
](https://github.com/taniman/profit-trailer-enhancements/issues/293#issuecomment-385831437
)
