### ISSUE TITLE
[FEATURE REQUEST] : Build bot restart functionality into the URL

### ISSUE THREAD

**Issue by kingokeke** [taniman/profit-trailer#1754]
Hi devs. Great work so far. I have a suggestion. Can you build a bot restart functionality into the URL? Just like you have the URL command to stop the bot, you can also have a URL command to restart the bot. Would be very convenient. Thanks.

**Comment by SgtBatten** [comment]
Please submit feature requests into he seperate ProfitTrailer enhancements repository
