### ISSUE TITLE
PT cannot determine BNB average bought price in USDT market

### ISSUE THREAD

**Issue by IAmNigh** [taniman/profit-trailer#1755]
![2018-05-02_0759](https://user-images.githubusercontent.com/37220652/39521992-dbdd4efa-4dde-11e8-9ac0-76310f43baf2.png)

**Comment by SgtBatten** [comment]
If you use bnb for fees it will keep getting forgotten because the amount you own is always changing.

**Comment by YoJeff** [comment]
Yes.  Known.  Not a bug.
