### ISSUE TITLE
Feature request: RSI/STOCH/STOCHRSI to have buy/sell both ways

### ISSUE THREAD

**Issue by joeyoon80** [taniman/profit-trailer#1756]
I wish to request that the RSI/STOCH/STOCHRSI can have buy and sell value that goes both ways.

For example, in RSI if DEFAULT_A_buy_value = 400, currently it means it will only buy if RSI is 40 or below. However, this can be counter-productive if we are doing buys when price is going up (such as using a positive MA cross or positive MACD), as RSI will be going up as well. So, if possible it would be good to have RSI DEFAULT_A_buy_value = 40 means it will buy when 40 and above, then the buy value limit is upwards (say 70), and DEFAULT_A_buy_value = -40 means it will buy 40 and below and the limit then would be -20 for example.

The reason I am asking for this is RSI can show confirmation of price trends also as a leading indicator whereas MA crosses and MACD are lagging indicators.

Hope I'm making sense in my explanation.

**Comment by SgtBatten** [comment]
PT does not compare the direction of the movement.  if you want to buy between 40 and 70 you can achieve this with the current setup using buy value and buy value limit.

I personally do not see the appeal of this when you have up to 4 other strategies you can use to confirm movements but if you wish to request this on the pt enhancements repository (where we track feature requests.) you may resubmit there.
