### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by ramonduraes** [taniman/profit-trailer#1757]
I'd like to suggest an improvement in mobile viewing. The scroll model is not compatible with the current patterns. Ideally, click the menu and show.

Points:

1) Improve the menu and just view the view that was requested in the navigation menu. Today it shows the full panel and then the item. This is not good on the mobile.

2) I am not able to edit a pairs code. When trying to edit the cursor moves on the Iphone.

3) I suggest prioritizing to be as clean as possible

Thanks

**Comment by SgtBatten** [comment]
can you explain point 1 again please

**Comment by ramonduraes** [comment]
The mobile site is heavy. In mobile scenarios the lighter the more efficient. When I click to edit on mobile the cursor changes location. If I am only using the "DCA" file editing I have no need to see my complete above. I suggest using the standard 'hamburger'.

![temp3](https://user-images.githubusercontent.com/2014324/39542084-f4ea6362-4e1d-11e8-8f90-cc2f9c5bbade.jpg)

**Comment by ramonduraes** [comment]
@SgtBatten Sorry, I clicked the close button

**Comment by ramonduraes** [comment]
Sorry, I clicked the close button

**Comment by Mikeeetrue** [comment]
Mobile view is a big pain. Became even worse with 2.0

**Comment by SgtBatten** [comment]
The hamburger doesnt auto close. But you can click it again to close it.

As for the cursed issue on mobile it is reported on many phones already.

**Comment by yellobello** [comment]
I would love to see when the position was bought in mobile view, so I can order them from the recent one to the oldest.

**Comment by securitygeneration** [comment]
I agree the hamburger should auto-close. Also, it's not possible to select text in the textarea in iOS, making it impossible to copy/paste.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
