### ISSUE TITLE
SALES alert tab does not stay Red after a sell 

### ISSUE THREAD

**Issue by eye1care** [taniman/profit-trailer#1758]
The sales alert tab flashes red for a second after a sell and immediately turns back to blue.  I have to manually check if a sale was made.  This happens while on the DCA page and I don't know if the same happens with PAIRS.  Running Windows, PT Ver 2.0.1

**Comment by YoJeff** [comment]
A 'unread sales' notification type of thing sounds like a feature request.   Slap it over here....
https://github.com/taniman/profit-trailer-enhancements/issues

Otherwise, I just use the counter.  When it goes up... NEW SALE!!!   :)
