### ISSUE TITLE
Sales not written to PTData.json

### ISSUE THREAD

**Issue by Nephor80** [taniman/profit-trailer#1759]
PT2 is working correctly except the last 2 days. PT2 shows several sales on that days, but it seems they are not written to the ...Data.json. So other programs like PT Magic show 0 sales.
A restart didn't solve this issue.
Is this a bug or an API-Problem?
THX

**Comment by Nephor80** [comment]
After a restart, all Sales happening the last two days are lost.

**Comment by SgtBatten** [comment]
Duplicate of #1720
