### ISSUE TITLE
Error on MACD to buy. 

### ISSUE THREAD

**Issue by pedrenho** [taniman/profit-trailer#1760]
BCC have in BSV MACD=0.000006358 (POSITIVE) in Possible Buy of PT, but in Trading View the MACD is negative. This is a error, or i'm wrong?
![image](https://user-images.githubusercontent.com/38894700/39542496-1a2e1758-4e1f-11e8-9de9-e76c5fcd0c13.png)
![image](https://user-images.githubusercontent.com/38894700/39542511-24190bb0-4e1f-11e8-929c-106c4521708d.png)
![image](https://user-images.githubusercontent.com/38894700/39542529-33c3af70-4e1f-11e8-86a5-175e4badcacc.png)
![image](https://user-images.githubusercontent.com/38894700/39542535-38a5f00c-4e1f-11e8-9c75-94b629cd85ec.png)

**Comment by YoJeff** [comment]
Histograms look negative to me.   More meat, logs, etc.   Can't make out fuzzy pics.

**Comment by pedrenho** [comment]
O erro permanece hoje. IOTA com MACD cruzando para cima sem visão de negociação e acima do histograma. Nenhuma PT aparece como negativo (-0.000000732).
![image](https://user-images.githubusercontent.com/38894700/39589696-4ea4b800-4ed5-11e8-84fe-c2c32e38efba.png)
![image](https://user-images.githubusercontent.com/38894700/39589717-5e44fb26-4ed5-11e8-94de-d4f3b710bfe1.png)
