### ISSUE TITLE
PT cannot determine QTUM average bought price in USDT market

### ISSUE THREAD

**Issue by IAmNigh** [taniman/profit-trailer#1763]
Same error with QTUM as described in issue #1755 with BNB (which is now closed)

**Comment by IAmNigh** [comment]
It appears manual (directly using the exchange) buying and selling sometimes gives PT some problems.

**Comment by IAmNigh** [comment]
![screen shot 2018-05-02 at 6 23 36 pm](https://user-images.githubusercontent.com/37220652/39552220-4af5335a-4e36-11e8-93e4-21986158ac29.png)

**Comment by SgtBatten** [comment]
yes this is not unusual behaviour for manual trading. 

Any amount of dust will cause this kind of issue. Buying with another currency will cause this issue. API connection issues can also contribute.

ProfitTrailer only checks for manual activities every 10 minutes which is part of the reason things get lost or confused with manual trades. We do not recommend manual trading on the same account although it is possible if it is well considered.

**Comment by IAmNigh** [comment]
Is it more exasperated to the USDT market?

**Comment by SgtBatten** [comment]
the logic is no different so i don't see why it would be

**Comment by IAmNigh** [comment]
Yes...

**Comment by IAmNigh** [comment]
![screen shot 2018-05-05 at 7 45 51 am](https://user-images.githubusercontent.com/37220652/39663052-1d18d5d0-503a-11e8-8a72-c4ddebec016c.png)

**Comment by IAmNigh** [comment]
It appears what is happening it that if a resource is not available via Binance API, PT reverts to a neutral setting of 0, where it should instead refer to locally stored database of average bought price. This is particularly relevant when after a sell action has occurred. I'm guessing of course because I don't have access to the PT sources.

**Comment by YoJeff** [comment]
Merging #1848
