### ISSUE TITLE
[Feature Request] Additional Override settings for buys

### ISSUE THREAD

**Issue by oiler2112** [taniman/profit-trailer#1764]
Was thinking of some additional configs for pairs, something like:

DEFAULT_Override_pairs = 2

DEFAULT_Override_A_buy_strategy = RSI
DEFAULT_Override_A_buy_value = 19
DEFAULT_Override_A_buy_value_limit = 0

DEFAULT_Override_B_buy_strategy = EMAGAIN
DEFAULT_Override_B_buy_value = -0.99

What this 'Override' setting would do is the following:

Assuming you are at your max pairs, but a coin hits DEFAULT_Override buy settings and is still within all other limits such as balance, etc, the coin will be bought. DEFAULT_Override_pairs would be the amount of pairs allowed in addition to max_trading_pairs.

Reason for this is there are many times, when you will be at your max pairs limit, but there will be a coin you can see in your possible buy log that is well below your buy settings, but does not get bought due to being at max pairs. In this situation, i will generally go to the exchange and do a manual buy, but to have it automated would be nice.

**Comment by NOP-Commander** [comment]
Hi @oiler2112 

there is a separate repo for feature requests.
https://github.com/taniman/profit-trailer-enhancements

I would recommend to reopen your request in the correct repo because issues with feature requests in this repo will be closed by the devs.
