### ISSUE TITLE
DCA reset issues ... a lot

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1766]
First I need to mention, that I only use PT for DCA-ing and selling. I make the buys somewhere else and let PT pick up the coins when it sycns with my exchange (Binance), so this might cause this issue.

Sometimes when I buy a coin and PT picks it up, it doesn't reset the DCA times from a previous position I held, same coin.
So I have to go into HotConfig and reset the DCA buy times for these. This is happening more often and when you deal with 30-50 pairs can be very exhausting.

I assume that PT has a function, where it resets the DCA buy times when a new coin is bought by the bot itself, which I never use.
Can you change it to resetting the DCA buy times, when the coin is sold? Maybe this will fix the issue.

Thanks in advance!

**Comment by SgtBatten** [comment]
this is by design actually.

https://wiki.profittrailer.com/doku.php?id=faq#i_manually_bought_a_coin_and_it_already_has_a_dca_count

Youll observe the last dca count on each coin.

**Comment by alexdolli** [comment]
Maybe the developers can find another way to go about this? I understand it's by design, but very frustrating from my point of view. :(
