### ISSUE TITLE
DCA Level is not resetting to 0 

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1767]
Bought the coin manually and has gone through DCA level 4. Then, the coin was sold later.
![image](https://user-images.githubusercontent.com/37259950/39566426-dd8f0d62-4efe-11e8-8b27-7e6215df3d06.png)

When I buy another coin manually, the DCA level is not resetting to zero.

![image](https://user-images.githubusercontent.com/37259950/39566307-80dbb7f0-4efe-11e8-81d2-eb5b600f6507.png)

**Comment by SgtBatten** [comment]
This is expected behaviour. Answered in the faq
