### ISSUE TITLE
Pending order after price drop

### ISSUE THREAD

**Issue by mehtadone** [taniman/profit-trailer#177]
The pending_order_wait_time is a useful feature. It would be great to have a similar feature after a % drop. 

So after DCA has been complete and its dropped -10% from its average price, then place it in pending. After that, if it reaches your min sell, then take it out of pending.

**Comment by Limitrade** [comment]
good idea, +1

**Comment by taniman** [comment]
added price drop send to pending. taking out of pending should follow the combined profit logic for now
