### ISSUE TITLE
Wrong Price in Sales Log

### ISSUE THREAD

**Issue by xxsteven69xx** [taniman/profit-trailer#1771]
I woke up to a nice surprise this morn only to be let down.

![sales log](https://user-images.githubusercontent.com/20728844/39588136-c6346af6-4ec0-11e8-94b5-9113f2e5ee73.png)
![binance](https://user-images.githubusercontent.com/20728844/39588146-ca93e3c4-4ec0-11e8-995a-98c908b281ba.png)
 Some how the average price was calculated to be 0.00159BTC and the price never dipped below 0.00189BTC

[initialization.zip](https://github.com/taniman/profit-trailer/files/1971655/initialization.zip)
[Logs.zip](https://github.com/taniman/profit-trailer/files/1971658/Logs.zip)

**Comment by ilivenicely** [comment]
i'm having the same issue but inverse. a coin is displaying far lower than where it's at

**Comment by taniman** [comment]
@xxsteven69xx This is a duplicate issue. This problem is known as is caused by partial sells. 
See how your EOS was split into 2 sales?
See #1725

**Comment by taniman** [comment]
Version 2.0.4 tries to fix this and adds extra logging just in case
