### ISSUE TITLE
EMA cross is just showing EMA spread values

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer#1772]
EMA Cross is not working correctly. It's just showing the same exact values of EMA spread. 
EMA Cross should only check the past # candles after the cross point (e.g 5 candles). 
 
![image](https://user-images.githubusercontent.com/36821138/39597018-c01f820e-4ed9-11e8-9a20-6e57ea33bb31.png)

**Comment by SgtBatten** [comment]
the buy value used for ema cross is the spread, so this makes sense.
