### ISSUE TITLE
Missing coins in Possible Buy log

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer#1773]
My PT is not showing all pairs in possible buy log. 
I am using simple default settings on Binance exchange.
enabled_pairs = ALL
DEFAULT_min_buy_volume = 0
![image](https://user-images.githubusercontent.com/36821138/39598428-1f508f9e-4ede-11e8-8355-bda69dd81fd2.png)
With this setting all pairs should show in possible buy log! (minus coins in pairs & dca)** 
Some coins are missing. For example ADA, TRX.
Sort by alphabetic order or sort by volume to see easily compare with Binance.

(Sorted by alphabetical order)
![image](https://user-images.githubusercontent.com/36821138/39597787-1fb8b102-4edc-11e8-8faa-31fd57fecaeb.png)
![image](https://user-images.githubusercontent.com/36821138/39599058-266cf93c-4ee0-11e8-9085-e7418743d71a.png)

Missing compared to Binance: 
ADA, BTS, CDT, CHAT, CMT, CND, DNT (plus few more..)

The pairs are NOT in DCA and no balance is holding in Binance. 
Here is DCA.
![image](https://user-images.githubusercontent.com/36821138/39598146-30e24faa-4edd-11e8-90ec-8d467ee00ea1.png)

(Sorted by volume, largest to smallest)
![image](https://user-images.githubusercontent.com/36821138/39600514-9426b7f2-4ee4-11e8-9591-622133bea871.png)
![image](https://user-images.githubusercontent.com/36821138/39600574-bd386ba4-4ee4-11e8-942b-ce2e0a93f71d.png)

Missing compared to Binance: TRX, XVG ADA, IOST, ZIL, STORM, NCASH, XLM ...

There are a few more but especially ADA & TRX should be showing! They are not in DCA or PAirs or Binance hold.

**Comment by YoJeff** [comment]
min price filtering out cheap coins.  not a bug.

**Comment by ochiengj** [comment]
But ADA(tron) and TRX(Tron) are not cheap coins.
Also I have changed 
DEFAULT_min_buy_price = 0
Still missing coins.

**Comment by ochiengj** [comment]
Also I have shown the to 10 high volume coins and ADA is misin

**Comment by ochiengj** [comment]
Yes I know that.
DEFAULT_min_buy_price = 0

**Comment by SgtBatten** [comment]
coins too far from buy values were also excluded in v1, potentially same thing here
