### ISSUE TITLE
Price trigger

### ISSUE THREAD

**Issue by zigzag-way** [taniman/profit-trailer#1774]
Even though I have this settings:
price_trigger_market = ETH
price_rise_trigger = 5
price_rise_trigger_recover = 3
price_drop_trigger = 5
price_drop_recover_trigger = 3

my bot is telling me:
Binance PT2 - BTC Price Rise! Global Sell Only Mode Enabled - 11.752367 -- 5.000000

Is it a bug or am I doing smth wrong?

**Comment by SgtBatten** [comment]
well that says the price has risen 11% in your configured period which is over your 5% limit.

Additionally price_rise_trigger_recover = 3 is wrong. it should be price_rise_recover_trigger = 3.

if your questions is about signs. (+ and -) those are both positive numbers
this is what a drop would look like.

Sell Only Mode Enabled - -11.752367 -- -5.000000

**Comment by zigzag-way** [comment]
No
My qn was different. Price trigger was set to ETH, and bot says BTC.

**Comment by Babidi314** [comment]
I am experiencing the same. Is the bot considering ETH for the trigger and wrongly reporting BTC trigger, or is it actually considering BTC price for the trigger?

**Comment by SgtBatten** [comment]
no its a typo

**Comment by cupid-stunt** [comment]
Just want to say that I had the same issue. It was Cryptognome settings which were copied... I had price_rise_trigger_recover = 3 same as zig-zag and it was causing the bot to stay locked in SOM. Just in case anyone else has this issue.
