### ISSUE TITLE
[REQUEST] Button/hotconfig for immediately enter true trailing

### ISSUE THREAD

**Issue by fadelchaidarf** [taniman/profit-trailer#1775]
As far as I know this feature have been requested a lot of times from the community so I don't know why there is not an open request for this

What I'm proposing is a button so that the bot **immediately set true trailing to a pair** (when buying or selling) regardless of the buy/sell triggers. I see many people requesting manual sell button but in my view it would be better to utilize the trailing feature of the bot, and if we can trigger true trailing manually either for buying or for selling that would be really awesome! 

**Example use case:**
1. When a pair is climbing up and it is still at a loss (deep bag), we want to sell it at the highest price possible using trailing sell
2. When a pair is on a little pullback but the general price is climbing up because of a news (ex: rebranding, partnership, mainnet launch, etc), we want to trailing buy the pair for the lowest price possible without changing the trigger settings

If a button is hard to do (ex: no place for the button) maybe we can get a **new hotconfig command**, for example:
- When we want to sell a pair that we have using trailing sell
`ICX_true_trailing_sell_enabled = true`
- When we want to buy a pair that we don't have using trailing buy
`ICX_true_trailing_buy_enabled = true`

If such a feature is implemented, we can improve the sales that generated by the bot with our help! 

Any discussion and suggestion for additional use case will be appreciated!
Feel free to correct any grammar mistake, as I'm not a native speaker, thanks!

**Comment by SgtBatten** [comment]
you literally opened this request 5 days ago yourself in the correct place.
