### ISSUE TITLE
Swagger /api

### ISSUE THREAD

**Issue by K-Kit** [taniman/profit-trailer#1776]
Hello, I'm trying to figure out how to use the swagger API and keep getting error 401, if anyone could tell me what I'm doing wrong it'd be much appreciated 
url = 'http://<ip_adress>:8081/api/**/data' 
payload = {"api_token" : 'mytoken'}
headers = {"Accept": "application/json"}
r = requests.get(url, data=payload)

**Comment by taniman** [comment]
please check the new swagger api documentation in 2.0.2

also api_token is just a get parameter.
