### ISSUE TITLE
[Feature Request] Change sell stragey for specific pair based on conditions

### ISSUE THREAD

**Issue by yungcoconut** [taniman/profit-trailer#1778]
I use the EMACROSS buy & sell strategy and sometimes I end up with bags. I was wondering if it's possible to change sell strategies based on certain conditions.

For example a pair drops below 5% it will then trigger a different sell strategy for that specific pair only. Then revert back to the default sell strategy once it is sold. This way I wouldn't have to wait for the next cross, I could just have it sell once it reaches a certain gain percentage.

![pt](https://user-images.githubusercontent.com/35947368/39612407-df18bdd8-4f24-11e8-9c61-1638a6df4f4e.jpg)

**Comment by NOP-Commander** [comment]
You could realize this with PTFeeder's Grouping/Overrides. I know this doesn't help you but i just wanted to mention this for the record and for the case you didn't know. Happy trading!
