### ISSUE TITLE
When buy_percentage is too small there is no warning

### ISSUE THREAD

**Issue by SgtBatten** [taniman/profit-trailer#1779]
when a DCA buy should be attempted but the buy_percentage is looking for an amount below the exchange minimum, nothing happens, and no trailing occurs, but there is no warning or message saying why.

**Comment by cvthub** [comment]
There is a log entry in the logfile saying: 
ProfitTrailerService - Cannot buy ***. Please increase buy amount/percentage to something higher than 0.***!

**Comment by jokaorgua** [comment]
but this logfile has INFO level. better to change it to ERROR. I have the same situation and will be glad to be notified to telegram with this issue

**Comment by cvthub** [comment]
The issue if fixed for 2.0.4
If buy value is below dust, then BUY VALUE BELOW DUST will be shown in GUI.
