### ISSUE TITLE
Stop loss not working

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer#1786]
Stop loss not selling:

DEFAULT_stop_loss_trigger = -2.0
DEFAULT_DCA_stop_loss_trigger = 0

![image](https://user-images.githubusercontent.com/36821138/39659300-00a74886-4feb-11e8-97a1-2e7474401a9b.png)

PAIRS settings
![image](https://user-images.githubusercontent.com/36821138/39659372-8422727a-4fec-11e8-9958-3ff55212b27c.png)

DCA settings
![image](https://user-images.githubusercontent.com/36821138/39659308-37f7cdc4-4feb-11e8-8f2b-57512f563887.png)

This has been happening multiple times now where the trigger does not work.

**Comment by SgtBatten** [comment]
All you coins are in DCA and you have it set to 0 for DCA. Which disables it. So, working as designed

**Comment by ochiengj** [comment]
1. not all my coins are in dca. see pairs number.
2. I also tried without that line. And still dint work. I will post screenshots.

**Comment by ochiengj** [comment]
Removed line: DEFAULT_DCA_stop_loss_trigger = 0
Still not working.
![image](https://user-images.githubusercontent.com/36821138/39659543-294c407a-4ff0-11e8-9a34-1079b1572396.png)
![image](https://user-images.githubusercontent.com/36821138/39659563-78ca7928-4ff0-11e8-8681-4f497312bba5.png)

**Comment by SgtBatten** [comment]
# it out is the same as deleting it or setting to 0. You have no DCA stoploss setting still.

if you want to stoploss in dca you need to set is to a number. 

also be aware that it must complete DCA before it will stoploss. definition of completed DCA is in the wiki:

![image](https://user-images.githubusercontent.com/24822223/39659583-d846d2a6-506e-11e8-85d3-8aeeadea7007.png)

**Comment by ochiengj** [comment]
It's not working under pairs either. I will post screenshots of that.

**Comment by SgtBatten** [comment]
ok
