### ISSUE TITLE
Stop loss not working (re test)

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer#1787]
Stop loss not working.
I tried the following:
1. Stop loss in only pairs file
2. Stop loss in pairs and dca file
3. Stop loss in dca only 
None have worked.

DEFAULT_stop_loss_trigger = -2.0

![image](https://user-images.githubusercontent.com/36821138/39659587-2bfdd5d0-4ff1-11e8-93bb-143646d45ee3.png)
![image](https://user-images.githubusercontent.com/36821138/39659614-f0413e78-4ff1-11e8-8fd2-e2dae88e9704.png)
![image](https://user-images.githubusercontent.com/36821138/39659625-2f928d52-4ff2-11e8-9c1b-33bce9d6bef5.png)

**Comment by ochiengj** [comment]
Stop loss not working in pairs either.

**Comment by SgtBatten** [comment]
you have shown me nothing new. stoploss is still disabled in your dca file. and even when enabled it wont trigger until DCA is complete, without seeing the whole file who know when that might be.

as for pairs, i need the entire file and also a screenshot of it. So far, working as designed from your pictures
