### ISSUE TITLE
Feature Request: Disable Gain (for cases when running purely EMACROSS, etc.)

### ISSUE THREAD

**Issue by shadowbladers** [taniman/profit-trailer#1788]
It would be great if there was a setting which allowed us to disable gain. This would allow EMACROSS to be more effective when it is consolidating and buys but continues to go down. With a minimum gain set, this would have caused a loss whilst if it was disabled and with profit trailer taking a 1% hit, avoids a -6-8% loss.

**Comment by NOP-Commander** [comment]
Hi @shadowbladers,

feature requests go here: https://github.com/taniman/profit-trailer-enhancements This repo is for bugs only.
