### ISSUE TITLE
config load screen

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer#1789]
hi, i would like to know how to access the config load screen to switch settings,
this is not written in the wiki
the live support keeps referring me to the wiki and the swagger api , which don't seem to help
i want to create a new settings profile and i can't create it in the swagger api

**Comment by SgtBatten** [comment]
The API is the only resource you have for switching configs until the new GUI is rolled out (currently in beta)

You cant save a new config using swagger itself. But an example curl command is given on that page.
