### ISSUE TITLE
DCA Buy Trigger

### ISSUE THREAD

**Issue by mnanut** [taniman/profit-trailer#1790]
DCA Buy Trigger for individual coins in config not always correctly shown in DCA log.  There is either a heavy delay or it ignores changes.  Keep note that I am using offsets in PTF to make changes to the DCA buy trigger.

Most of the coins in the DCA log screen capture are showing correctly, but APPC has not shown the correct value for around 30 minutes so far (maybe longer).

![image](https://user-images.githubusercontent.com/5732913/39666394-0a2b1212-5071-11e8-813a-682ee246d1bb.png)

Here is the DCA config for APPC (DCA Trigger Value is -13.0 in config, but showing -10 in DCA log):
```

#------------------BTC/APPC------------------

# Last Price: 0.00007239
# Volume: 314.6199
# Coin age: 1/5/2018 12:00 AM UTC
# Price change (10): 0.42%
# Price change (360): -1.46%
# Volume change (10): -66.88%
# Volume change (360): -75.5%
# High/Low price change (10): 0.21%
# High/Low price change (360): -0.74%
# Upside volatility: 0.13%
# Downside volatility: 0.22%

APPC_Dca_A_Sell_Value = 3.2
APPC_Dca_Buy_Trigger = -13.0
APPC_Dca_Ignore_Sell_Only_Mode = true
APPC_Dca_Trailing_Buy = 0.884
APPC_Dca_Trailing_Profit = 0.0659
#------------------------------------

```
EDIT:  I think it's because my Dca_Som_Dca_Buy_Trigger = -8.5

This may not be an issue then...

**Comment by SgtBatten** [comment]
If you were in SOM for that coin then yes the default SOM value would supercede it.

**Comment by taniman** [comment]
http://wiki.profittrailer.com/doku.php?id=dca.properties#som_dca_buy_trigger

use correct setting name

**Comment by mnanut** [comment]
It is the correct name...  Typo.

**Comment by SgtBatten** [comment]
No worries. Regardless you did figure it out it seems
