### ISSUE TITLE
Average bought price setting itself incorrectly.

### ISSUE THREAD

**Issue by Rawhound** [taniman/profit-trailer#1791]
I had an old LTC bag which when it made a partial sell it immediately when to -8% despite the coin price not dropping.   I then noticed with each sell it was setting the bought price wrongly.   I had to keep resetting the storage average and price with each sell until the coin was fully sold.  

I have had similar issue with DCA partial sells losing the price, but this was the WRONG price being applied.

**Comment by SgtBatten** [comment]
Duplicate of #1725
