### ISSUE TITLE
Ichimoku  

### ISSUE THREAD

**Issue by padmaCoin** [taniman/profit-trailer#1792]
Ichimoku means "to see the balance of the market at a glance",
Ichimoku is a trading system, not just an indicator, it is self-sufficient.
allow to anticipate market movements and reduce our losses.
it allows to indicate dynamically:
-short or long term market trend,
-buy signal,
-sales signal,
-the strength of the rise to invest more or less,
-future price movement,
- stop loss,  
- take profits,
- panic sell,
And even a « Super panic sell » which will allow to anticipate a major correction of the market ( make a panic sell Btc followed by a purchase in usdt) ,
it works on all time units :
-long term trades,
-daily ,
-day trading ,
-scalping,
Ideal to put the bot autonomously during an absence.

**Comment by SgtBatten** [comment]
I think this is a feature request?

Please restart on the enhancements repository

**Comment by padmaCoin** [comment]
Have you a link ,i don t find enhancements repository thanks ;-)

**Comment by SgtBatten** [comment]
https://github.com/taniman/profit-trailer-enhancements
