### ISSUE TITLE
PT 1 to PT 2 upgrade issues

### ISSUE THREAD

**Issue by deesun** [taniman/profit-trailer#1795]
hi,

i just tried to migrate the data from version 1 to version 2 like described here:
https://wiki.profittrailer.com/doku.php?id=upgrade_instructions2

...and hit the following problems: (testmode is off)

- the DCA and pairs data was not read in, only the sales log is there
- it does not display anything in possible buys log
- it does not read my trades and/or DCA trades
- it does not read my balance right (because of the missing DCA coins)

what to do?

version 1 does display all the data with the same ProfitTrailerDate.json file.

**Comment by SgtBatten** [comment]
The ProfitTrailerData.json you have is fine then.

Most likely you have trading disabled and hidden pairs = all. This combo hides all existing holdings.

It sound alike you transfered over fine but have not completed configuring the settings.

**Comment by deesun** [comment]
ah now it works. looks like it was the SOM... all trades/coins are displayed now. thank you

**Comment by SgtBatten** [comment]
SOM does not hide pairs. Please come chat in support. Younhave something not configured.

**Comment by deesun** [comment]
now all seems to work... looks like the interface needs some price movements until it displays the coins right. 
i saw none of the DCAs, but price then moved up a bit and this made one trade show up in pairs, then it dropped again and was in the DCA section. 
seconds later the other DCA coins showed up and also the possible buys.

could also be a binance API issue, but the terminal did not show any error and the heart beats were normal. a bit strange, but now it shows all as it should.
thanks

**Comment by SgtBatten** [comment]
Could have been an API issue. Most likely culprit in my eyes is server.start_trading_delay.
Glad it's working for you.
