### ISSUE TITLE
Uhabe to create a new config on a already activated instance

### ISSUE THREAD

**Issue by wfjsw** [taniman/profit-trailer#1796]
#### Version: 2.0.2

So I have a already running instance but I want to create a new config profile. I navigate my browser to `/setup` manually, then I filled the textbox and press Load. I was stuck at that page, so I set up an mitm proxy and inspect into the connection to PT server.

#### Expected Behavior:
3 `/update` and 1 `/select` then redirect my browser to `/monitor`

#### Actual Behavior:
1 `/delete`(new profile) followed by 3 `/data`(old profile), nothing got deleted nor created though, and on the browser I am still at `/setup`

Can be reproduced on both production env and full emulated env.

**Comment by taniman** [comment]
This page is not meant to be navigated to manually... So this is not really a bug..

But I will see if something can be done..

**Comment by taniman** [comment]
I have disabled now the posibility to nagivate to this page after initial setup. 
Proper logic for creating new configs will be added soon
