### ISSUE TITLE
DCA Parameters can't show two digits in parentheses.

### ISSUE THREAD

**Issue by besthigh** [taniman/profit-trailer#180]
27.10.2017 20:13 | BTC-DNT | 0.65 | HIGHBB - (false) | -2.53 | 0.000009300.00000930 | GAIN | 0.000009230.00000948(4) | -3.14 | 1.00 | 112 | 15481.93231696 | 0.142183740.14727706

DCA max_price = 0.01  that's 0.14
0.000009230.00000948(4)<-- You can see..(4). I guess (14)

**Comment by taniman** [comment]
I think you are confusing this parentesys. the value in parentheses is how many times DCA has bought. max_buy_times <-- that parameter
Ao after DCA buy 1 time is will display (1)
second time (2)
etc.

Max cost value is not currently displayed . Or I do not understnad your report
