### ISSUE TITLE
Some Settings for the DCA seems to break the DCA LOG Table

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#1801]
I edited the DCA settings with the default settings of the 2.2 so I don't have it anymore .  But it seem's to be linked to the date  ; The date broke in the table from the column Date to Buy like this

Date------------------Coin------------------Bid.pr------------------Buy
5/5/2018-------------5/5/2018-------------04:29 PM--------------(-1D)
04:29 PM (-1D) 

breaking all the table
I was just using emacross, it's may be linked to the number of lines par row I don't know (I think the "EMACROSS" did not show up ). There was also each time an error of Jquery Datatable about the value of CurrentValue

**Comment by SgtBatten** [comment]
Really need a screenshot. Can't quite follow what the error is

**Comment by AkliOnet** [comment]
I took one but rewritten on it the error in the console . That all i have 
![pt eroor](https://user-images.githubusercontent.com/2818626/39780054-6c8e3348-530b-11e8-8924-1a6f6372e00b.png)

**Comment by YoJeff** [comment]
What does your log say, cause it doesn't look like the bot is running to me.

**Comment by AkliOnet** [comment]
Yes I posted all the errors, the first three error are linked to the problem, the other are me stopping the bot

**Comment by taniman** [comment]
@AkliOnet please provide your log file at the moment this error happens. If there are errors in the log file. 
If not we cannot investigate as this is nt replicatable

**Comment by Mahmud1985** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1991165/ProfitTrailer.log)

**Comment by Mahmud1985** [comment]
@taniman Hi I uploaded my ProfitTrailer.log file pls help me

**Comment by AkliOnet** [comment]
Maybe the  error started at the first buys of the bot when the bot thought it has bought for two pairs(ETC and BTG) while there were no buy on the exchange.
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1991721/ProfitTrailer.log)
[ProfitTrailerData.json.Log](https://github.com/taniman/profit-trailer/files/1991724/ProfitTrailerData.json.Log)

**Comment by Mahmud1985** [comment]
@taniman is there any solution?

**Comment by taniman** [comment]
@Mahmud1985  I am not sure what kind of system you are using. But you are getting a lot of timeouts. So this might be causing your problems. Think about switching to a another machine and trying that

**Comment by taniman** [comment]
@AkliOnet  I am not seeing any errors in your log. Which is unusual if you are getting errors in frontend. So this indicates that there is no error on backend. And maybe you are just having a caching error. 

If you can replicate the error. Contact me on discord and we will look at it together if you send me the URL to the system where it is happening

**Comment by AkliOnet** [comment]
Ok @taniman
