### ISSUE TITLE
I was told that a stop loss counts towards resetting the consecutive buys...

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1802]
As the title says, I was told by support that a stop loss sell also triggers the reset of the consecutive buys, which if true would still get me in a lot of trouble in a downward market swing.
I understand that PT is mostly set up with DCA-ing in mind, but from past experience, I developed a new strategy that includes a stop loss. So if this true, the consecutive buy protection is pretty much useless if using a stop loss.

Can you guys change it, so only positive sells count towards resetting the consecutive buy feature?

**Comment by YoJeff** [comment]
Feature requests go here:  https://github.com/taniman/profit-trailer-enhancements/issues
