### ISSUE TITLE
"Error occured in chartData" after update to 2.0.3

### ISSUE THREAD

**Issue by radeksalomon** [taniman/profit-trailer#1803]
Hi, after updating to 2.0.3 using Bittrex exchange, we are getting the error "ERROR ProfitTrailerService - Error occured in chartData, message INVALID_MARKET, result:    ". It comes every 30 seconds.

Thanks for your advice, how to fix it.
With best regards,
Radek

**Comment by SgtBatten** [comment]
can you please check that your pairs file has not gone missing and that it contains market = parameter

**Comment by radeksalomon** [comment]
I checked the pairs file and market = USDT. The log file contains this error message right after the update 2.0.3. Before the update there are only the throttling errors.

**Comment by Macflurry26** [comment]
Same issue here. Also using USDT.

**Comment by But4ler** [comment]
Same
You know a site that reports the status of binance services (API / website / exchange etc) ?

**Comment by taniman** [comment]
A fix will be done for the next release. But for now make sure to set
price_trigger_market = BTC in your pairs file

**Comment by radeksalomon** [comment]
Hi,

I updated the bot to 2.0.4. and the error message is still the same if I set price_trigger_market = USDT (on Bittrex).

Radek

**Comment by FaithlessVoid** [comment]
Hello,

I am experiencing a similar issue.
Trading on Binance, I had no errors at all in 2.0.2.

In 2.0.3. i get this:
 "2018-05-13 21:38:02 ERROR ProfitTrailerService - Error occured in chartData, message ERROR: -1121, Invalid symbol., result: " 
This message is repeated every 6 to 8 seconds.
Just installed 2.0.4., the error stays the same.

After reading this issue I changed the trigger_market from USDT to BTC.
This workaround works for me.
