### ISSUE TITLE
2.0.3 FileNotFoundException

### ISSUE THREAD

**Issue by Frisk1025** [taniman/profit-trailer#1805]
0|profit-t | 2018-05-07 23:06 +00:00: java.io.FileNotFoundException: /tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/servlet-sessions/1526339215481__0.0.0.0_node0pubiane444targ87c60b6ydj0 (Permission denied)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at java.io.FileOutputStream.open0(Native Method)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.session.FileSessionDataStore.doStore(FileSessionDataStore.java:284)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:103)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.session.AbstractSessionCache.put(AbstractSessionCache.java:541)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.session.SessionHandler.complete(SessionHandler.java:371)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.session.SessionHandler.complete(SessionHandler.java:388)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
0|profit-t | 2018-05-07 23:06 +00:00: 
0|profit-t | 2018-05-07 23:06 +00:00: 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
0|profit-t | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
0|profit-t | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
0|profit-t | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
0|profit-t | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
0|profit-t | 	at org.eclipse.jetty.server.Server.handle(Server.java:561)
0|profit-t | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
0|profit-t | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
0|profit-t | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
0|profit-t | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
0|profit-t | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
0|profit-t | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
0|profit-t | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
0|profit-t | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
0|profit-t | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
0|profit-t | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
0|profit-t | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
0|profit-t | 	at java.lang.Thread.run(Thread.java:748)

**Comment by cvthub** [comment]
Does the error appear again or just that one time? Upgraded PT from 2.0.2 -> 2.0.3?

**Comment by Frisk1025** [comment]
appear again and again~ never stop.

**Comment by cvthub** [comment]
Does the file
/tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/servlet-sessions/1526339215481__0.0.0.0_node0pubiane444targ87c60b6ydj0
exist in you filesystem? Please also check the permissions if the file exists. Is the user which runs PT allowed to write to 
/tmp/
/tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/
/tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/servlet-sessions/
?
Please also try to stop the bot delete /tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/ and restart bot

**Comment by Frisk1025** [comment]
NO such file. and cannot delete /tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/
and restart PT 2.0.3 show this

15 lines:
0|profit-t | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
0|profit-t | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
0|profit-t | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
0|profit-t | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
0|profit-t | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
0|profit-t | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
0|profit-t | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
0|profit-t | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
0|profit-t | 	at org.eclipse.jetty.server.Server.doStop(Server.java:520)
0|profit-t | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
0|profit-t | 	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.stop(JettyEmbeddedServletContainer.java:221)
0|profit-t | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.stopAndReleaseEmbeddedServletContainer(EmbeddedWebApplicationContext.java:306)
0|profit-t | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onClose(EmbeddedWebApplicationContext.java:155)
0|profit-t | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1015)
0|profit-t | 	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:928)

**Comment by YoJeff** [comment]
Does running it directly produce any different results (without pm2)

**Comment by cvthub** [comment]
This seems not to be a PT problem. 
The /tmp/ directory should be writeable for anybody on a unix OS. 

# ll -a /tmp/
**drwxrwxrwt** 45 root root    1120 Mai  8 15:40 ./

If you cant delete /tmp/795AF4003C8DE47EFB34C9365AE14A776BE42F80/ please check the permissions and try deleting as root.

**Comment by Frisk1025** [comment]
drwxr-xr-x  3 root  root    4096 Apr 27 12:35 795AF4003C8DE47EFB34C9365AE14A776BE42F80

**Comment by YoJeff** [comment]
You can continue the discussion if need be, but this is not a bug.
