### ISSUE TITLE
2.0.3 - Dust log has gone

### ISSUE THREAD

**Issue by blackhx** [taniman/profit-trailer#1806]
After upgrading to 2.0.3 on my Binance exchange all dust has gone.
My Bittrex exchange still shows dust and it was upgraded at the same time.

**Comment by SgtBatten** [comment]
nothing should have changed regarding dust. try a restart or simply waiting a little while.

**Comment by blackhx** [comment]
Still no joy. Rebooted completely.
Started Binance exchange no dust values.
Started Bittrex exchange dust is shown correctly.
I will give it another hour to see if it comes up.

**Comment by SgtBatten** [comment]
is trading enabled?

**Comment by blackhx** [comment]
Yes it has been trading. 
Still shows Zero on BINANCE
No settings changed when I upgraded both

**Comment by blackhx** [comment]
although not much activity in the command window for ~50minutes

**Comment by SgtBatten** [comment]
Heartbeats?

**Comment by SgtBatten** [comment]
Screenshot of CMD prompt please

**Comment by blackhx** [comment]
Restarting again looks like I got one heartbeat "cache" but nothing else.
Seems to be not progressing

**Comment by blackhx** [comment]
![untitled](https://user-images.githubusercontent.com/39071232/39732416-abe269ec-525c-11e8-84c5-0848745c6375.jpg)

**Comment by blackhx** [comment]
start delay will finish in a sec

**Comment by blackhx** [comment]
![untitled](https://user-images.githubusercontent.com/39071232/39732457-1b40ae70-525d-11e8-8607-0e6ddd9c3e57.jpg)
Now I'm getting errors

**Comment by blackhx** [comment]
Strange my Bittrex instance is working normally seems to be only affecting Binance at the minute.

**Comment by CptLongbottom** [comment]
Well that's good to know. Binance seems to be working fine as far as I can tell.

**Comment by blackhx** [comment]
![untitled](https://user-images.githubusercontent.com/39071232/39739108-a98686a2-527e-11e8-9343-bd71595c235e.jpg)
Without making any changes I'm getting tons of these errors.

**Comment by blackhx** [comment]
I went back to version 2.0.2 by replacing the .jar file and all is back to normal and trading.

**Comment by CptLongbottom** [comment]
2.0.3 is back to regular trading for me but I still have an issue with missing sells. Binance trade log seems to be correct though.

**Comment by taniman** [comment]
looks to me like conection issues. Also there is no need to use throttling on binance if you don't need it.

This is something that can be better looked at together with support untill a real bug is confirmed
