### ISSUE TITLE
Possible buy  0 

### ISSUE THREAD

**Issue by BOBALLEX** [taniman/profit-trailer#1808]
Bot is not buying 
![image](https://user-images.githubusercontent.com/36281599/39738070-80f17608-5291-11e8-8d2e-738730e5cf0d.png)

![image](https://user-images.githubusercontent.com/36281599/39737889-9e3ab96e-5290-11e8-9002-e731046012c2.png)

**Comment by YoJeff** [comment]
This is for bugs, not questions.  Please jump in support.
