### ISSUE TITLE
Proposal for and UNDCA upgrade/enhancement/add-on...

### ISSUE THREAD

**Issue by Masterofcoinak** [taniman/profit-trailer#1809]
Hallo devs,
i am pretty sure you got already ideas/request for an UN-DCA upgrade/enhancement/add-on...
In times like now, everybody is carrying around huge bags and a lot of us don't have the budge to DCA out of this problem. A simple way would be to sell back DCA steps, but to be honest this is not enough (nobody wants to sell with lost). Maybe we could create a 4th step in PT. PBL > PAIRS > DCA > UNDCA. The last DCA buy would be sold with Profit and this goes not into the sales log. It will improve the status of the main pair. Like this people don't have to carry their back too long (in theory). I am not sure if PT saves all information about each DCA step. In PT1 it would be even easier with the double down strategy, but with PT2 it could be trickier.  I hope this is a possible upgrade for the future.
I know it doesn't make sense, but below are are future settings. hahah ;).

#First we define the parameter to be in the UNDCA.
DEFAULT_UNDCA_enabled = false/true/-20
DEFAULT_UNDCA_min_cost = 1.0
#Than simple sell strategy as always
DEFAULT_UNDCA_A_sell_strategy = GAIN
DEFAULT_UNDCA_A_sell_value = 2.0
DEFAULT_UNDCA_B_sell_strategy = RSI
DEFAULT_UNDCA_B_sell_value = 55
DEFAULT_UNDCA_trailing_profit = 0.5
DEFAULT_UNDCA_max_profit = 0
DEFAULT_UNDCA_min_buy_volume = 100
DEFAULT_UNDCA_min_order_book_volume_percentage = 125
#normally it will go back to DCA
DEFAULT_DCA_rebuy_timeout = 60

Please implement it.

**Comment by YoJeff** [comment]
Bugs only here.    Wishlist items go here -> https://github.com/taniman/profit-trailer-enhancements/issues
