### ISSUE TITLE
Wiki Edit: Pairs, ALL_enabled_pairs clarification

### ISSUE THREAD

**Issue by smportis** [taniman/profit-trailer#181]
Suggest changing from this: 

Use to define what PAIRS you want the ProxyBot to use for trading.
List all pairs you want separated by comma or specify ALL to trade all pairs in your market
ALL_enabled_pairs= ALL

to this:

Use to define what PAIRS you want the *ProfitTrailer* to use for trading.
List all pairs you want separated by comma or specify ALL to trade all pairs in your market. 
ALL_enabled_pairs= ALL
*or
ALL_enabled_pairs= BTC-ETH, BTC-LTC <-- FOR BITTREX
ALL_enabled_pairs= BTC_ETH, BTC_LTC <-- FOR POLONIEX*

**Comment by taniman** [comment]
When I get a better wiki, I will give you wiki editing rights :) tnx!
