### ISSUE TITLE
PT not accounting for all coins

### ISSUE THREAD

**Issue by cedricscheepers** [taniman/profit-trailer#1810]
PT sold LOOMBTC.  It never DCA'd, but is now showing in my DCA log, as well as in my sales log, but on Binance my balance is 0.  Another coin, GVTBTC, disappeared from PT. My account on Binance shows a positive balance for GVTBTC.

My balance therefore is also incorrect.

**Comment by YoJeff** [comment]
To look into this, we need way more information.  Screenshots and logs for starters.

**Comment by cedricscheepers** [comment]
Hi

Sure, can I email this to you?

I did not want to post this on a public forum.

Kind regards
Cedric

**Comment by cedricscheepers** [comment]
My balance is off between 0.2 BTC and 0.8 BTC. 

This is my balance on Binance:
![screen shot 2018-05-09 at 10 31 14](https://user-images.githubusercontent.com/7846485/39804432-47482eae-5374-11e8-91a9-62a4613920af.png)

This is what PT says:
![screen shot 2018-05-09 at 10 28 45](https://user-images.githubusercontent.com/7846485/39804469-5d8d5d38-5374-11e8-9419-efc39d7d3ea9.png)

**Comment by cedricscheepers** [comment]
And now PT is showing this:

![screen shot 2018-05-09 at 10 37 46](https://user-images.githubusercontent.com/7846485/39804717-17e115a8-5375-11e8-94c8-4e647e82d410.png)

**Comment by cedricscheepers** [comment]
We can close this. It seems the Bittrex throttle settings caused many issues for me as a Binance user. Since I removed them, problems seems to be fixed.
