### ISSUE TITLE
2.0.3 - Git Tags // PT tags // Package name // Old release

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer#1811]
Hello
There have been changes in version management (not practical for automation (ex docker etc))
* Tags: v202 => 2.0.3
* Name Package: Profit Trailer.zip => ProfitTrailer-$ {VERSION}. zip
* In the HMI: It says PT Ver: 2.0.2
* Telegram sends a notification with version 2.0.2 while it is the zip of version 2.0.3.

Finally, the old releases are no longer available on github, especially the previous one, 2.0.2, a real shame for rollbacks

I think there was a failure in creating the release;)

**Comment by taniman** [comment]
For the future I can try and leave the latest 2 version.

But people should not create automations and expect that they will not break. 

And yes. Version has nog change to no leading v according to semver
