### ISSUE TITLE
[Enhacement] Add ability to ask for a coin from remote hist

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1812]
A feature to request which coin to buy from remote host. Like in swbot. Instead of trailing in PBL after coin is sold ask remote host which coin to buy. This will give ability to write own strategies. If Remote host return none the bot should use standard algo for PBL

**Comment by YoJeff** [comment]
Bugs only here.   Feature requests go over here: https://github.com/taniman/profit-trailer-enhancements/issues

You may want to add more meat to this request first.
