### ISSUE TITLE
2 Instances problem

### ISSUE THREAD

**Issue by lorddr** [taniman/profit-trailer#1814]
hello, I have a problem with profittrailer. I have two instances installed on a VPS both on separate binance accounts. One is on BTC and the other on ETH. The issue is that when I start the second one (ETH one), the Instance that I have on BTC imports the pairs and dca configs from the ETH. And after that any change that I make on any one of the instance gets imported in the other one. 
why is that happening?

**Comment by SgtBatten** [comment]
Most likely you do not have the web url set correctly 
![image](https://user-images.githubusercontent.com/24822223/39786828-bc76f0c0-5365-11e8-84bf-dc8bf4854b21.png)
