### ISSUE TITLE
Possible Pairs Not updating

### ISSUE THREAD

**Issue by MarcP1001** [taniman/profit-trailer#1816]
There are no errors, Sales are working but no buying happening.  When I go to the possible pairs I get a message on the left saying "there was an error while processing the data received from profit trailer.  Please give Proft Trailer some love, make a coffee, and all will be good soon."
This has been happening for over 24 hours.  I tried resetting my VPS, rebooting PT, changing back to my previous version.  This all started when I went to V2.0.3 from V2.0.1.  Any help on the matter would be appreciated.
![image](https://user-images.githubusercontent.com/37921254/39792076-82a1de58-5371-11e8-93ad-46d1afae2aab.png)

**Comment by SgtBatten** [comment]
according to that screenshot you are still on 2.0.1 so not sure what you have done

**Comment by MarcP1001** [comment]
I went back to 2.0.1 to attempt to fix the issue and it did not fix the issue

**Comment by SgtBatten** [comment]
come chat on discord, i think this is a config issue

**Comment by MarcP1001** [comment]
Thanks for the Help!
Got it fixed.
Marc
