### ISSUE TITLE
Error occurred in ticker, message We got incorrect data, retrying, result

### ISSUE THREAD

**Issue by cedricscheepers** [taniman/profit-trailer#1819]
Being getting them since this morning.

![screen shot 2018-05-09 at 09 32 02](https://user-images.githubusercontent.com/7846485/39801642-24855c5a-536c-11e8-8d95-8f61c53e7ad7.png)

**Comment by stuartc** [comment]
Same here, I'm assuming this is an issue with the Binance API and not PT...

**Comment by TrueOsiris** [comment]
I concur. Are you also on the Binance API?

**Comment by cedricscheepers** [comment]
Binance API yes

**Comment by stuartc** [comment]
@cedricscheepers are they are different hosting providers? or on the same/different box?

**Comment by christoyer** [comment]
Also receiving with a few more messages relating to the Binance API.

![image](https://user-images.githubusercontent.com/19993190/39802316-a278dce2-5365-11e8-9499-772a869ca9b5.png)

**Comment by cedricscheepers** [comment]
@stuartc - Sorry Stuart, I do not understand your question?

But if I have to guess - the other bot is PT Feeder, and the last is Binance Duster (my personal bot for managing my BNB balance). They all use Binance APIs to read data from Binance

**Comment by MarcP1001** [comment]
Just started getting this as well on Binace. 
 ERROR ProfitTrailerService - Error occured in ticker, message We got incorrect data, retrying, result:

**Comment by cedricscheepers** [comment]
Here is an update, also getting other errors. But PT-Feeder is working and Binance Duster is working
![screen shot 2018-05-09 at 09 55 57](https://user-images.githubusercontent.com/7846485/39802795-5cdbbdf8-536f-11e8-84a1-56251bd8e1df.png)

**Comment by TrueOsiris** [comment]
ok auto-solved (for me). 
It was a Binance issue.

**Comment by cedricscheepers** [comment]
Seems mine is also back to normal - just experiencing #1810 still

**Comment by TrueOsiris** [comment]
For me, the issue was solved by Binance. Didn't have to restart bots.
