### ISSUE TITLE
Exchange Requests

### ISSUE THREAD

**Issue by Concept211** [taniman/profit-trailer#182]
In order of importance:

Binance
GDAX
KuCoin
Cryptopia

Thank you for an amazing piece of software!

**Comment by alternativesurfer** [comment]
Any headway made on this request?

**Comment by mkarulin** [comment]
Definatelly interested in Kucoin due to no fees when trading neo.

**Comment by taniman** [comment]
We just implemented the first on the list. Taking a break from exchanges now.

**Comment by lukepighetti** [comment]
GDAX please.

**Comment by jschoenith** [comment]
GDAX & Kraken please

**Comment by moses-aronov** [comment]
Please Support GDAX. Any headway on this?
