### ISSUE TITLE
Sold DCA coins remain in DCA

### ISSUE THREAD

**Issue by cedricscheepers** [taniman/profit-trailer#1822]
Coin was sold, but remains stuck in the DCA. 

Here is the sales entry:

![screen shot 2018-05-09 at 17 00 29](https://user-images.githubusercontent.com/7846485/39822367-a9237f1c-53aa-11e8-8bba-db3bffcebf7c.png)

Here is the DCA entry (which should not be shown here):
![screen shot 2018-05-09 at 17 00 51](https://user-images.githubusercontent.com/7846485/39822379-b4e206d4-53aa-11e8-9029-f5eacaad39e5.png)

As you can se, the volume is 7.63 coins for both, and it is stuck there for some time now.

**Comment by YoJeff** [comment]
What version?
What exchange?
Screenshot of exchange sell?
Copy of relevant PT log entries?
API issues can cause delays as well.   Any API issues?
Try a restart?

**Comment by cedricscheepers** [comment]
Latest version - 2.0.3
Binance

Exchange sell screenshot

![screen shot 2018-05-09 at 18 00 04](https://user-images.githubusercontent.com/7846485/39825732-de864f56-53b2-11e8-8290-b82d9fa128d9.png)

Where do I get the PT log entries?

I can see 1 error before the sell, after the sale nothing:

![screen shot 2018-05-09 at 18 02 07](https://user-images.githubusercontent.com/7846485/39825866-2c287536-53b3-11e8-9715-e64d51c27565.png)

Restart worked - DCA entry is gone.

**Comment by taniman** [comment]
Do not use the new throttle commands with binance. They have not been optimized for binance. So just remove them for now
