### ISSUE TITLE
Wrong calculation EMACROSS

### ISSUE THREAD

**Issue by voreh** [taniman/profit-trailer#1825]
EMACROSS is been calculated wrong in new version 2.0.3 look the difference
![203](https://user-images.githubusercontent.com/30416677/39837236-3faf5ea0-53ac-11e8-98cf-a03a185c95c4.png)
its says here that -0.18 is not TRUE but the -0.09 is...
 
now version 2.0.1
![201](https://user-images.githubusercontent.com/30416677/39837282-6ac28478-53ac-11e8-850b-12c0c55c326b.png)
here we see that everything that is under -0.01 is true... because the Limit was set to -3

**Comment by SgtBatten** [comment]
Most likely this is working as designed.

It wont show true if the cross occurred more than the allowed EMA_cross_candles ago.
