### ISSUE TITLE
Keep_balance_percentage and initial_cost_percentage annoying calculation.

### ISSUE THREAD

**Issue by Domber134** [taniman/profit-trailer#1826]
If you use keep_balance or keep_balance_percentage the balance used to calculate initial_cost_percentage does not include the reserved amount. e.g Balance = 1 BTC, keep_balance = 0.5 BTC, initial_cost_percentage of 1% will equal 0.005 BTC not 0.01 BTC.

Can you give an option to do something like DEFAULT_initial_cost_percentage but for the total amount of coins, so i dont have to calculate the stupid new initial cost percentage.
So if i set keep balance percentage to 50% i dont have to set 3% initial cost percentage instead of 1,5%.

**Comment by YoJeff** [comment]
Feature requests go here:  https://github.com/taniman/profit-trailer-enhancements/issues
