### ISSUE TITLE
Bot will not read balance and has not traded in weeks

### ISSUE THREAD

**Issue by kj3407** [taniman/profit-trailer#1827]
I have V1 and V2, since I have down loaded V2 weeks ago, I have had nothing but problems, I have a Bittrex bot, when I turn it on, it was fine for about 20 minutes, after that, there was a throttle problem at 1st, then it stop reading my files and balance, I don't get a read on pairs, possible buys, Pending log sales, nothing.  I have been spending about 2 hours a day on this new bot and can't seem to get it to do anything but send me messages saying: Ticker update, there is something wrong with your bot, restart.  if there is someone from support who can help me, I will send you the info to look at, and tell me what I am doing wrong. Bear in mind, I am not a rookie, I know a little coding, so unless i am doing something that I cant seem to find, then not sure what up.  I am using V1 until I can get this thing to work.

**Comment by taniman** [comment]
you can find support in our discord channel. This platform is for reporting bugs

**Comment by kj3407** [comment]
@taniman 
I thought that was a bug. ??? I mean, what is a bug if not trading?  I will check discord, but this is not fun at all.

**Comment by taniman** [comment]
There are a lot of known reasons for not trading. And support can help u go through those. 
And once that option has been exhausted we can be certain of a bug or not
