### ISSUE TITLE
STOCHRSI issues still in 2.0.3

### ISSUE THREAD

**Issue by samick123** [taniman/profit-trailer#1830]
STOCHRSI still won't match binance

**Comment by SgtBatten** [comment]
Hey mate, appreciate the report but as i mentioned the existing issues are still open so ill close this one and you can add to the existing ones. Thanks

**Comment by SgtBatten** [comment]
Duplicate of #1644

**Comment by hoffer49** [comment]
Be sure to check the indicator settings in your exchange and make sure they match your indicator settings in PT2...I found that the indicators were different in Binance...so i changed my indicators settings to match what Binance had and it seemed to work
