### ISSUE TITLE
PT ignores DEFAULT_min_buy_volume if a decimal is placed after the desired value

### ISSUE THREAD

**Issue by markcmurphy** [taniman/profit-trailer#1833]
Your issue may already be reported! Please search before creating one.
Talk to Discord Support Staff first if you are not certain this is a bug.

Profit Traile Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

ProfitTrailer entirely ignores DEFAULT_min_buy_volume if a decimal is placed after the desired value. 

## ProfitTrailer info
Version: 2.0.3

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

I feel PT should simply disregard values after the decimal place. 

## Current Behavior

PT treats it as no value having been entered in at all when a decimal is present in value.

## Troubleshooting
What have you tried to do to fix it?
Once noticed, I removed the decimal and PT behaved as expected.

## Steps to Reproduce

1. Add a decimal to the DEFAULT_min_buy_volume value
2. PT will start trading as though value not present

**Comment by taniman** [comment]
In theory it is possible to disregard values after the decimal point. 
But this is not the way to go

I agree that in some cases this convertion to 0 is not ideal. But that's how we handle invalid input now.

BUT we are starting tests on our new config editor, So there will be no need to edit the files.
You will be able to edit GUI fields and thus we can do proper validation for each field

That is the best way to avoid these types of mistakes in my opinion
