### ISSUE TITLE
GUI not displaying some DCA and not updating DCA costs

### ISSUE THREAD

**Issue by scalpasuarus** [taniman/profit-trailer#1835]
Your issue may already be reported! Please search before creating one.
Talk to Discord Support Staff first if you are not certain this is a bug.

Profit Traile Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.02

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version) 
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

Windows server 2016 Contabo VPS

## Expected Behavior

GUI not displaying some of the DCAs and also not updating the cost/amount spent on coin after it was DCAd. 

Please see image (below in log section) for the following:
- POA ans ARN should show DCA. Also CMT did not show DCA but just sold before I did screen cap.
- LINKBTC should be like $66 as it DCAd once at 100%. You can see SNM above it has not DCA'd and is at the correct initial cost.

Multiple errors in log. Please check later part of log for above coins.
I have another bot running off same VPS. It is functioning OK, no errors.

## Troubleshooting
What have you tried to do to fix it?
 Restarting exe

## Steps to Reproduce

1.
2.
3.
4.

## Configuration

https://pastebin.com/uHAMcZ6T

## Log files/console output

 

![disappear_data](https://user-images.githubusercontent.com/39214007/39956350-b33f17d2-55de-11e8-8df8-f3e5c5d796b2.jpg)

Log file too big to attach so here is Wetransfer link:
https://we.tl/Fib1GxfOn7

Thank you!

**Comment by taniman** [comment]
According to your post you are on version 2.0.2
According to your log file you are on 2.0.1

Version 2.0.4 fixes the error with your DCA buys. Was just released
