### ISSUE TITLE
server.currency = DKK

### ISSUE THREAD

**Issue by tes724** [taniman/profit-trailer#1837]
Your issue may already be reported! Please search before creating one.
Talk to Discord Support Staff first if you are not certain this is a bug.

Profit Traile Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.3

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Should give currency in DKK on the monitor page

## Current Behavior

No information is showing in the monitor page

## Troubleshooting
What have you tried to do to fix it?
When changing to server.currency = USD then it will work again.

## Possible Solution
It clearly a bug in the DKK value. Its unable to get the information from where its getting it. In your wiki the server.currency = DKK is an option. I can live with the USD value. Just want to inform that something is wrong.

**Comment by djcrypto75** [comment]
Cannot be replicated. Need more details and screenshots.
