### ISSUE TITLE
Making DCA more dynamic

### ISSUE THREAD

**Issue by Skeptain** [taniman/profit-trailer#1838]
Hey there,

PT 2.0 was such a big step forward with DCA settings though I have an idea that might improve it even more. At the moment we can combine buy options and percentage for DCA but I think this is not perfect yet. I want to have my buy options and the percentage of the coin's price sets the percentage of the DCA buy. Let's see this with an example.

These are my DCA buy options taken for an example:

DEFAULT_DCA_A_buy_strategy = EMAGAIN
DEFAULT_DCA_A_buy_value = -0.30
DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_value = 35
DEFAULT_DCA_B_buy_value_limit = 5
DEFAULT_DCA_C_buy_strategy = LOWBB
DEFAULT_DCA_C_buy_value = 10

Additionally I would prefer a dynamic trigger and no predefined. At the moment I could add something like this:

DEFAULT_DCA_buy_trigger_1 = -1.5
DEFAULT_DCA_buy_trigger_2 = -2.5
DEFAULT_DCA_buy_trigger_3 = -3.5

What I want to achieve is a trigger based on the loss. Something like this:

DEFAULT_DCA_buy_trigger_A_max = 0
DEFAULT_DCA_buy_trigger_A_min = -5
DEFAULT_DCA_buy_trigger_A_percentage = 20
DEFAULT_DCA_buy_trigger_B_max = -5
DEFAULT_DCA_buy_trigger_B_min = -10
DEFAULT_DCA_buy_trigger_B_percentage = 50
DEFAULT_DCA_buy_trigger_C_max = -10
DEFAULT_DCA_buy_trigger_C_percentage = 100

That means, if the price was down between 0 and -5, the DCA will buy 20%. If the price went down between -5 and -10, the DCA will buy 50% and if the price went down more than -10, the DCA will buy 100%. 

The cherry on top of the cream would be a trigger that tells the bot to not buy a DCA more expensive than set compared to the DCA before like:

DEFAULT_DCA_rebuy_max_change_percentage = 0

The change compared to my former DCA must not be bigger than zero.

**Comment by taniman** [comment]
sorry no Enhancements requests are allowed on this reposity.
Please add your enhancement request to https://github.com/taniman/profit-trailer-enhancements
