### ISSUE TITLE
UI barfs if all DCA strategies commented out

### ISSUE THREAD

**Issue by merricrubiyat** [taniman/profit-trailer#1839]
**This is a ridiculous situation but should be caught by the bot gracefully**

## ProfitTrailer info
Version: 2.0.2

## Expected Behavior
If all DCA buy strategies are commented out, GUI or app startup should detect that DCA settings are impossible

## Current Behavior
App starts up and GUI throws the "go get a coffee" general error when looking at DCA tab

## Possible Solution
Add a valid DCA buy strategy

## Steps to Reproduce

1. Comment out all DCA buy strategies

## Log files/console output

 

![image](https://user-images.githubusercontent.com/35739228/39959027-7748eae6-55c0-11e8-9625-decc502211e8.png)

**Comment by cvthub** [comment]
proper output will denote the missing strategies in next release
