### ISSUE TITLE
If strategy goes to false, trailing buy must be deactivated and not bought

### ISSUE THREAD

**Issue by angelsomar** [taniman/profit-trailer#1840]
## ProfitTrailer info
P T Ver:  2.0.2
- [ X] Binance
- [X ] Windows (10)

DEFAULT_E_buy_strategy = RSI
DEFAULT_E_buy_value = 55
DEFAULT_E_buy_value_limit = 40

DEFAULT_trailing_buy = 0.5

buy_value_limit does not give false if it is in trailing_buy

I just want to buy at the best price while the rsi is between 55 and 40, the bot made me purchases in RSI = 36

effectively better price in my favor but I did not want to buy at that point, in my particular case it was bought out of the trend I was looking for

I accompanied with emagain 0.01 and the purchase was made out of that trend because the low price too much

with the macd happens the same thing I tell him to buy if macd is + positive begins to track the price and passes to negative and should be false the macd and not buy as I enter the bearish trend of macd

I understand that trailing works in our favor, but when enabling trailing buy the other indicators should be able to return to false if they fall to levels that indicate it and suspend the trailing without buying

**Comment by SgtBatten** [comment]
This is how it is designed currently. If trailing starts nothing else matters except the price.

**Comment by NOP-Commander** [comment]
Hi @SgtBatten,

is it possible that the design has changed in 2.x? I'm still running 1.x and saw that trailing stopped on multiple occasions when the current buy value dropped below the buy value defined in the config. When i understand the given example from @angelsomar right, the buy value limit wasn't hit while trailing so the behavior from 1.x and 2.x is comparable in that case. Thanks in advance for an enlightenment.

and btw: Kudos for the issue template!

**Comment by taniman** [comment]
Yes, the logic has changed because of multiple strategies being used. Once all strategies are true. 
1. trailing starts.
2. we right down exact price where trailing started
3. trailing ignores any changes to buy values. and only cares about trailign the price
4. trailing ONLY stops if price boes back above the original price when trailing started

**Comment by NOP-Commander** [comment]
Hi @taniman,

thanks for your feedback. My humble opinion is that adding such details in the docs/wiki would be valuable as it clears up how Profit Trailer works in detail plus it could reduce support. This goes for all details about Profit Trailer not yet added to the docs/wiki.

**Comment by SgtBatten** [comment]
It is covered in the detailed look at how trailing works.
https://wiki.profittrailer.com/doku.php?id=a_trailing_story#scenario_2_-_trailing_buy

**Comment by NOP-Commander** [comment]
Uh cool, sorry in that case.
