### ISSUE TITLE
Sales page getting stuck on page number

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer#1841]
Hello,
On the sales page if you click on a different page number it works. But afterwards you cannot click back to page one. For example click on page '2'. Then after refresh try to click back to '1'.  After another refresh it jumps back to '2' and is stuck there. Even if you click '1' or click 'previous it still goes back to '2'.

I also tried to refresh the browser.
![image](https://user-images.githubusercontent.com/36821138/39968023-f59368c4-568b-11e8-8e77-7c0a3b8b7025.png)

**Comment by ochiengj** [comment]
## ProfitTrailer info
Version:2.0.3

 
Exchange:
- [ ] Bittrex
- [ X] Binance
- [ ] Poloniex

 
Operating System:
- [ X] Windows (10)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Should go back to page 1 if you click page 1 and STAY on page 1 even after refresh.
## Current Behavior
Does not STAY on page 1 if you click it. Will go back to whatever page you were after refresh.
## Troubleshooting

Tested it a few times.
Changed items view from 25 to 50 to all. Then back to 25.
## Possible Solution
Don't know
## Steps to Reproduce

1. Click on Sales page
2. Click on page 2
3. Wait for refresh
4. Try to go back to page 1
5. Wait for refresh

**Comment by YoJeff** [comment]
Awesome usage of the template, I must say.

Can verify this.   Some combination of paginating, soft refresh, hard refresh makes the current page number a bit too sticky.

**Comment by djcrypto75** [comment]
Not able to replicate on last build.
