### ISSUE TITLE
negative EMACROSS buying before reaching the number of candles

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer#1842]
NOTE: My bot uses the same UTC as Tradingview

![image](https://user-images.githubusercontent.com/38858258/39970655-a08330be-56c5-11e8-8d6d-54288ba2f30b.png)

**Comment by arthurengeletrica** [comment]
![image](https://user-images.githubusercontent.com/38858258/39970661-ae34d186-56c5-11e8-95cd-ea167f4589d9.png)

**Comment by arthurengeletrica** [comment]
It would happen in 2.03 too

**Comment by arthurengeletrica** [comment]
![image](https://user-images.githubusercontent.com/38858258/39970667-d50351a2-56c5-11e8-89bb-c53aecea9155.png)

**Comment by arthurengeletrica** [comment]
It was supposed to wait for 40 candles after crossing down the EMA, but it bought in less than 15 candles...

**Comment by arthurengeletrica** [comment]
Here is the PAIRS confifguration:

![image](https://user-images.githubusercontent.com/38858258/39970706-8c170320-56c6-11e8-91ed-fd559b0709fe.png)

**Comment by SgtBatten** [comment]
It does not wait 40 candles. It sound alike it is working exactly as designed.

It can buy anytime within 40 candles after the cross if that's what you set it to.
