### ISSUE TITLE
Panicsell trigger needed

### ISSUE THREAD

**Issue by Skeptain** [taniman/profit-trailer#1843]
Our objective is to get more of our mastercoin with help of the bot. But everytime the mastercoin starts to take off, bags and TCV loses of course due to having mostly altcoins instead of your mastercoin in your bot. To prevent this to happen and to make sure being on the plane when it goes to the moon I would suggest implementing a trigger related to the last 24h change of the mastercoin. Since this should be combined with a minimum profit of the last 7 days you can make sure to just take your profit and make a step back to wait for the end of the storm. I think it should look like this:

DEFAULT_panic_sell_min_profit = X
DEFAULT_panic_sell_price_trigger = Y

X = The minimum profit of the last 7 days
Y = The 24h change of the mastercoin

**Comment by taniman** [comment]
I guess you did not see the template. This is for issues only. Enhancements requests need to be added to the correct place
