### ISSUE TITLE
ISSUE: Stringindexoutofboundsexceptionstring_index_out_of_range10

### ISSUE THREAD

**Issue by cryptovictor1188** [taniman/profit-trailer#1845]
Your issue may already be reported! Please search before creating one.
Talk to Discord Support Staff first if you are not certain this is a bug.

Profit Traile Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

I have an interesting issue:
Current Setup: Vultr VPS Server, Windows 10, Profit Trailer Version 2 with PTNotification and PtTracker.
I am using the PtNotifications Addon and I have been receiving these kinds of message every 5 minutes (Reoccurring) :

**"ProfitTrailerService - openOders - java.lang.tringIndexOutOfBoundsException; String index out of range: -10"

"ProfitTrailerService - Error occured in CB, message String Index out of range: -10, result:"

"ProfitTrailer Service - Error occured in ticker, message No value was returned, result:"**

I found the issue on the Wiki but it was of no help:
Here is the wiki link: https://wiki.profittrailer.com/doku.php?id=common_errors#stringindexoutofboundsexceptionstring_index_out_of_range10

I reached out to multiple support members and tried our best to triage the issue....
We tried the following:

Reinstated new API Keys from Bittrex: 2 new keys (Defaults and Private).
Added my VPS (Vultr) IP Address to my Bittrex IP Whitelist (this did not help)
http://localhost:8083/settings/test/reset (This seems to stop the issue but it does not resolve it as it will still happen if I restart the PtNotification system).
Many other trouble shooting with Settings etc.
Hard Reset of VPS
Changed Ports
Please help me !

## Troubleshooting
What have you tried to do to fix it?
Reinstated new API Keys from Bittrex: 2 new keys (Defaults and Private).
Added my VPS (Vultr) IP Address to my Bittrex IP Whitelist (this did not help)
http://localhost:8083/settings/test/reset (This seems to stop the issue but it does not resolve it as it will still happen if I restart the PtNotification system).
Many other trouble shooting with Settings etc.
Hard Reset of VPS
Changed Ports
Updated The Date and Time of the VPS to Automatically Synchronize with time.nist.gov

I also sent this error to PTNotification Github. Here is the response: 
"These are PT errors being redirected to PTN to notify you of them. It has nothing to do with PTN it self. I would suggest looking for support in the PT Discord."

Nothing has solved the issue. 

## Possible Solution

No Idea, 4-5 other people are unsure as well. We have tried many options. 

## Steps to Reproduce

1. Turn the PT Notification Add-on On Run Command
2. Sends the errors messages every 5 minutes
3.
4.

**Comment by SgtBatten** [comment]
Version? Did you try latest release

**Comment by cryptovictor1188** [comment]
Hello.

This issue was occurring on the Version 2.0.3. 
Magpies88: I am not sure why you down graded to the 1.2 version, I would have stayed with the 2.0 Version or better. 

This issue has been reoccurring .

**Comment by SgtBatten** [comment]
Please try 2.0.4

**Comment by cryptovictor1188** [comment]
I currently just downloaded the version 2.0.4, restarted all programs/ add-ons. I will notify you if it occurs. Currently installing PT Feeder.

**Comment by cupid-stunt** [comment]
I'm having the same issue with 2.0.4. "Error occured in CB, message string out of range: -10". On RPi.

**Comment by taniman** [comment]
This message is not an issue. It can happen sometimes on bittrex and is caused because of a communication error with the exchange. 
Mostly caused because of connection timeout.

So try connection.timeout = 60 
But mostly this error is not disturbing the bot unless it's happening continuosly even after increasing the timeout

**Comment by cupid-stunt** [comment]
Good news! Which file do we change to enter connection.timeout = 60?

**Comment by helo03** [comment]
https://wiki.profittrailer.com/doku.php?id=application.properties#connectiontimeout

application.properties :-)
regards,
mario

**Comment by cryptovictor1188** [comment]
the issue has stopped!

**Comment by helo03** [comment]
Love to hear that!

I will close this issue now, if you appear to be having the error again, just comment again.

Thank you and have a great day,
Mario
