### ISSUE TITLE
Feature Request: Buy Strats based on market

### ISSUE THREAD

**Issue by StrattonOakmontCrypto** [taniman/profit-trailer#1847]
Allow different strategies to be used in pairs file based off market conditions.  

For example Strategy A with 3 indicators could be used in a bull market

and Strategy B with 2 indicators could be used in a bear market.

**Comment by SgtBatten** [comment]
as per the issue template which you msut have simply deleted without looking at.

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.
