### ISSUE TITLE
Incorrect bought cost after manual buy

### ISSUE THREAD

**Issue by YukoOshima** [taniman/profit-trailer#1848]
## ProfitTrailer info
Version: 2.0.4

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows server 2016
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
I bought BAT in binance at 4564. But pt thinks the buy value is 4430

## Current Behavior
Then PT sells it in 4554 with loss, but pt says that it sells the coin in profit

## Troubleshooting

PT get the wrong buy value.

## Steps to Reproduce

1. Use market order to buy a coin.
2. The market order price should be compose of different price
3. PT only get the lowest price.

## Configuration
PT should calculate the average price when I use market order to buy a coin.

## order detail
order detail from binance:
05-14 07:39:22 | BAT/BTC | Market | Buy | 0.00004564 | market | 110 | 110 | 0.00502040 BTC |
05-14 07:40:26 | BAT/BTC | Limit | Sell | 0.00004554 | 0.00004554 | 83 | 83 | 0.00377982 BTC | 
05-14 07:40:12 | BAT/BTC | Limit | Sell | 0.00004555 | 0.00004555 | 26 | 109 | 0.00118430 BTC|

I loss some money on this trade, but the order detail in pt says that I get some profit.

13/05/201823:40 (0D) | BATBTC | GAINHIGHBB | 2.60 | 0.00009553 | $0.83 | 83 | 0.000044300.00004554 | 0.003676730.00377226 | $31.91$32.74
13/05/201823:40 (0D) | BATBTC | GAINHIGHBB | 2.62 | 0.00003019 | $0.26 | 26 | 0.000044300.00004555 | 0.001151750.00118193 | $9.99$10.26

**Comment by SgtBatten** [comment]
When you say market order you mean you manually bought the coin?

**Comment by YukoOshima** [comment]
Yes, I buy the coin manually

**Comment by taniman** [comment]
You should avoid doing manual buys. As we tell everybody. manual buys disturb the normal process of the bot. Caching cannot be cleared properly and such.

Also you have not provided your log file

**Comment by YukoOshima** [comment]
Sometimes I use some signals to buy coin manually and use pt to sell it.It's necessary for me to do that.
Is there any way to fixed the problem?
Or how can I use pt to buy manually?

**Comment by taniman** [comment]
We will add buy and sell buttons in next major release
