### ISSUE TITLE
V2.0.4 Websocket error - API Ban

### ISSUE THREAD

**Issue by LarsK81** [taniman/profit-trailer#1849]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.4

 
Exchange:
- [ ] Bittrex
- [ X] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [ X] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

updated to new version 2.0.4 getting these error messages:  2018-05-14 00:54 +00:00: 2018-05-14 00:54:56 ERROR ProfitTrailerService - Error occured in CB, message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API., result: 
7|8081-lar | 2018-05-14 00:54 +00:00: 2018-05-14 00:54:57 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
7|8081-lar | 2018-05-14 00:54 +00:00: 2018-05-14 00:54:58 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
7|8081-lar | 2018-05-14 00:54 +00:00: 2018-05-14 00:54:59 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
7|8081-lar | 2018-05-14 00:54 +00:00: 2018-05-14 00:54:59 ERROR ProfitTrailerService - Error occured in CB, message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API., result: 
7|8081-lar | 2018-05-14 00:54 +00:00: 2018-05-14 00:54:59 ERROR ProfitTrailerService - Error occured in CB, message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API., result

## Current Behavior

as soon as restart
## Troubleshooting

downgrade to 2.0.3
## Possible Solution

2.0.3 works
## Steps to Reproduce

1. update to 2.0.4
2. have 5 bots running and start them all at once
3. however after stopping them all and just run 1 bot its still the same issue
4.server.throttle_millis = 10
server.throttle_calls_amount = 1000
server.throttle_calls_seconds = 30
these settings don´t work either have them in application.properties

## Log files/console output

 

It´s not coming up in the log file, maybe because I went back to 2.0.3?

**Comment by taniman** [comment]
You cannot run 5 bots on the same machine and expect 0 banning errors.
Version 2.0.4 does not bring any changes regarding how calls are done to the exchange.

Binance allows 1200 calls per minute. 
Your setting is allowing 1000  for just 1 bot. 

So starting 5 bots at once will calls over 5000 calls in under 1 minute and thus causing a banning error. 

If you start 1 bot up and you get a banning error.

There is no fix for starting 5 bots simultaneously. Other than changing calls_amount to 1200/5 = 240 or less

**Comment by DKCryptoKing** [comment]
I am experiencing the exact same error, when trying to update my bots. Also had to downgrade to 2.0.3 to make the bots work again. I have a total of 4 bots running on two different VPS, all linux.

**Comment by LarsK81** [comment]
Ok, so why does profit trailer not accept the standard springboot command to assign a specific IP to the second bot? That would solve the problem for me
