### ISSUE TITLE
pair_min_listed_days

### ISSUE THREAD

**Issue by diablocody** [taniman/profit-trailer#1850]
[logs issue.txt](https://github.com/taniman/profit-trailer/files/1999279/logs.issue.txt)

## ProfitTrailer info
Version: 2.0.3

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Should only buy pairs >240 days

## Current Behavior
I have pair_min_listed_days = 240 listed in my pairs, in my possible buy options its marking coins as "too new" but it is still purchasing coins with less than 240 days, such as ENJETH IOSTETH BLZETH

## Troubleshooting
nothing

## Possible Solution
no idea

## Steps to Reproduce
1.
2.
3.
4.

## Configuration
start_balance = 2.15716709
market = ETH
enabled_pairs = ALL
hidden_pairs = ALL
keep_balance = 0
#-------------------------------
#Options (:P)
#-------------------------------
DEFAULT_buy_max_change_percentage = 8
#DEFAULT_buy_min_change_percentage = -10
DEFAULT_trading_enabled = true
max_trading_pairs = 10
pair_min_listed_days = 240
DEFAULT_DCA_enabled = true
DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 0.5
DEFAULT_min_buy_volume = 200
DEFAULT_min_buy_price = 0
DEFAULT_max_buy_spread = .75
DEFAULT_min_orderbook_volume_percentage = 100
#-------------------------------
#v2.0 Multiple Buy Strategies
#-------------------------------
DEFAULT_A_buy_strategy = EMAGAIN
DEFAULT_A_buy_value = -.99
DEFAULT_A_buy_value_limit = 0
DEFAULT_B_buy_strategy = RSI
DEFAULT_B_buy_value = 33
DEFAULT_B_buy_value_limit = 0
DEFAULT_trailing_buy = 0
#v2.0 Multiple SELL Strategies
#---------------------------
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1.15
DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 45
DEFAULT_trailing_profit = 0.12
#---------------------------
#Hidden Pairs
#---------------------------
BNB_trading_enabled = false
#---------------------------
#Panic Buttons
#---------------------------
#PPT_panic_sell_enabled = true
DEFAULT_panic_sell_enabled = false
DEFAULT_sell_only_mode_enabled = false
DEFAULT_rebuy_timeout = 2
#---------------------------
#Triggers
#---------------------------
price_trigger_market = BTC
price_rise_trigger = 0
price_rise_trigger_recover = 0
price_drop_trigger = 0
price_drop_recover_trigger = 0

DCA
DCA_keep_balance = 0
DCA_keep_balance_percentage = 0
DEFAULT_DCA_max_cost = 10
#-----------------------------------
#v2.0 Multiple DCA Buy Strategies
#-----------------------------------
DEFAULT_DCA_A_buy_strategy = ANDERSON
#DEFAULT_DCA_buy_trigger = 0
DEFAULT_DCA_buy_trigger_1 = -1
DEFAULT_DCA_buy_trigger_2 = -1.5
DEFAULT_DCA_buy_trigger_3 = -2
DEFAULT_DCA_buy_trigger_4 = -2
DEFAULT_DCA_buy_trigger_5 = -3.5
DEFAULT_DCA_buy_trigger_6 = -4
DEFAULT_DCA_buy_trigger_7 = -5
DEFAULT_DCA_buy_trigger_8 = -5
DEFAULT_DCA_buy_trigger_9 = -5
DEFAULT_DCA_buy_trigger_10 = -5
DEFAULT_DCA_buy_trigger_11 = -5
DEFAULT_DCA_buy_trigger_12 = -5
DEFAULT_DCA_buy_trigger_13 = -5
DEFAULT_DCA_buy_trigger_14 = -5
DEFAULT_DCA_buy_trigger_15 = -5
DEFAULT_DCA_buy_trigger_16 = -5
DEFAULT_DCA_buy_trigger_17 = -5
DEFAULT_DCA_buy_trigger_18 = -5
DEFAULT_DCA_buy_trigger_19 = -5
DEFAULT_DCA_buy_trigger_20 = -5
DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_value = 35
DEFAULT_DCA_B_buy_value_limit = 5
DEFAULT_DCA_trailing_buy = 0
#-----------------------------------
#DCA ME
#-----------------------------------
DEFAULT_DCA_max_buy_times = 20
DEFAULT_DCA_buy_percentage_1 = 100
DEFAULT_DCA_buy_percentage_2 = 100
DEFAULT_DCA_buy_percentage_3 = 50
DEFAULT_DCA_buy_percentage_4 = 30
DEFAULT_DCA_buy_percentage_5 = 25
DEFAULT_DCA_buy_percentage_6 = 25
DEFAULT_DCA_buy_percentage_7 = 20
DEFAULT_DCA_buy_percentage_8 = 15.5
DEFAULT_DCA_buy_percentage_9 = 12.11
DEFAULT_DCA_buy_percentage_10 = 10
DEFAULT_DCA_buy_percentage_11 = 8
DEFAULT_DCA_buy_percentage_12 = 7
DEFAULT_DCA_buy_percentage_13 = 6
DEFAULT_DCA_buy_percentage_14 = 6
DEFAULT_DCA_buy_percentage_15 = 5
DEFAULT_DCA_buy_percentage_16 = 5
DEFAULT_DCA_buy_percentage_17 = 5
DEFAULT_DCA_buy_percentage_18 = 5
DEFAULT_DCA_buy_percentage_19 = 5
DEFAULT_DCA_buy_percentage_20 = 5
#-----------------------------------
# v2.0 Multiple DCA SELL Strategies
#-----------------------------------
DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 1.02
DEFAULT_DCA_B_sell_strategy = RSI
DEFAULT_DCA_B_sell_value = 40
DEFAULT_DCA_trailing_profit = 0.147
DEFAULT_DCA_max_profit = 20
#-----------------------------------
# Options
#-----------------------------------
DEFAULT_DCA_min_orderbook_volume_percentage = 100
DEFAULT_DCA_ignore_sell_only_mode = false
DEFAULT_DCA_max_buy_spread = 1.5
DEFAULT_DCA_rebuy_timeout = 10
#-----------------------------------
# Extra Triggers
#-----------------------------------
DEFAULT_DCA_stop_loss_trigger = 0
DEFAULT_DCA_stop_loss_timeout = 0
DEFAULT_DCA_pending_order_wait_time = 0

**Comment by SgtBatten** [comment]
This is a new feature that has existed for only around 90 days.

Our database of pair ages only began then and we can't pull the ages from the exchange.

So new coins will get added to the list with their dates and eventually the number of days can be 240 and work. But for now that's beyond what we can see.
