### ISSUE TITLE
Bought prices are not registered

### ISSUE THREAD

**Issue by DrrMrr** [taniman/profit-trailer#1851]
## ProfitTrailer info
Version: 2.0.4

Exchange:
- [ ] Bittrex
- [ X] Binance
- [ ] Poloniex

Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x ] Other linux distro (please specify)
  Raspbian
- [ ] Mac OS

## Expected Behavior
Bought price should be registered.

## Current Behavior
I think bought prices are not registered correctly.

![image](https://user-images.githubusercontent.com/174676/39981163-a6c458f6-574f-11e8-8592-44b148ef858b.png)

## Troubleshooting
I have restarted restarted the profit trailer and delete json file.

## Possible Solution
???

## Log files/console output
![image](https://user-images.githubusercontent.com/174676/39981150-94af15c0-574f-11e8-8932-120a2027deb1.png)

**Comment by DrrMrr** [comment]
Hi,

I I have replaced files with files from 2.0.3 and now I see everythiing correctly and now errors

![image](https://user-images.githubusercontent.com/174676/39981513-23852ebe-5751-11e8-9630-4736e1297bba.png)

![image](https://user-images.githubusercontent.com/174676/39981524-2e02e3fe-5751-11e8-88d8-91b10024f849.png)

![image](https://user-images.githubusercontent.com/174676/39981543-3d630c48-5751-11e8-955f-38f142e91d0c.png)

Best regards
Damjan

**Comment by SgtBatten** [comment]
By deleting the json you cleared the history. And yes restoring the ejson restored the prices.

**Comment by DrrMrr** [comment]
Hi,

Yes, but why has this error even accour?  I don't even know when is the last time I have received this error.

**Comment by SgtBatten** [comment]
You said you deleted the json.

The Json stored all the data. So you deleted the data.

If that's not what happened hen you need to explain the current behaviours and expected behaviour in a LOT more detail.

**Comment by DrrMrr** [comment]
Hi,

but before I didn't do that. I have just restarted the Profit trailer 2.0.4 and it was the same error.

So if I would deleted json data in version 2.0.4 it would also work like later in 2.0.3? So next time I should just delete json file. Is this the correct procedure?

Which logs are best for you, so you can debug an error. That way I can be more detailed next time if same error occours.

Thank you
Damjan
