### ISSUE TITLE
2.0.4 sell at wrong price .

### ISSUE THREAD

**Issue by dechut** [taniman/profit-trailer#1852]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.4

 
Exchange:
- [ ] Bittrex
- [] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

i have setting : 
in Pairs.properties
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 20
DEFAULT_DCA_enabled = false

in DCA 
DEFAULT_DCA_B_sell_strategy = GAIN
DEFAULT_DCA_B_sell_value = 1

with this config , i only want to sell my coin for profit 20% , i dont need DCA .
my coin show at PAIR tabs . but it still got sell with DCA profit ( 1% )

![image](https://user-images.githubusercontent.com/31846587/39985161-d5f5539a-5787-11e8-800a-a5f4c4ffba48.png)

i think bot need seperate sell value of PAIR and DCA
## Current Behavior

Setting PAIR profit very high , and DCA profit smaller .
coin show at PAIR tab , but sold with DCA profit setting .

## Troubleshooting

yes , double check PAIR setting , saved it from web gui , or local save .

## Possible Solution

i set Pair profit same as DCA profit

## Steps to Reproduce

1. set Pair Sell value to 50
2. set DCA sell value to 0.1
3. wait price increase
4.

**Comment by taniman** [comment]
Please provide all required information by the template  else the issue will be closed
