### ISSUE TITLE
Spring boot doesn´t accept different IP

### ISSUE THREAD

**Issue by LarsK81** [taniman/profit-trailer#1853]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.0.3

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [ x] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

I wanted to use the standard spring boot command server.address=<your_ip> to give me second bot a different IP, as I got 2 IP addresses on my VPS.
## Current Behavior

It is ignoring the new IP.
## Steps to Reproduce

1. Put this command server.address=<your_ip> into application.properties.
2.
3.
4.

**Comment by YoJeff** [comment]
This is a feature request....    Post feedback/request/votes here....
https://github.com/taniman/profit-trailer-enhancements/issues/274
