### ISSUE TITLE
StopLoss

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer#1861]
StopLoss don't seem to be selling. 
![screenshot_20180514_134503](https://user-images.githubusercontent.com/36767505/40013989-3b757f70-577d-11e8-84cc-6d6f0c4b3a4e.png)

**Comment by YoJeff** [comment]
No settings, no logs, no mention of your stoploss, no version, not formatted.

**Comment by DragonBtc93** [comment]
DEFAULT_stop_loss_trigger = -4
DEFAULT_stop_loss_timeout = 1
ver 2.0
[Uploading ProfitTrailer.log…]()

**Comment by YoJeff** [comment]
Still, no logs, no formatting.   Version 2.0 is old -- upgrade.

**Comment by DragonBtc93** [comment]
Log is there

**Comment by DragonBtc93** [comment]
Just upgraded will see if that works

**Comment by YoJeff** [comment]
Check your logs for obvious issues (missing prices, spread too big, volume to low, etc, etc)   Resubmit using template, including logs if still an issue.
