### ISSUE TITLE
Wrong profit calculation on PAIRS

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer#1862]
NOTE: Time on PRofiTrailer is UTC, on tradingvirew is UTC, on my computer and telegram bot is UTC-3

![image](https://user-images.githubusercontent.com/38858258/40017299-557f14e6-578f-11e8-8112-3c0f10cb3b45.png)

**Comment by arthurengeletrica** [comment]
![image](https://user-images.githubusercontent.com/38858258/40017311-5f290826-578f-11e8-97ef-6c6f90481c84.png)

**Comment by arthurengeletrica** [comment]
If you see the buying time of ZEC BTC pair on next images, it is clear that  bought price is right on telegram bot, but wrong on ProfitTrailler:
![image](https://user-images.githubusercontent.com/38858258/40017366-92ed0db0-578f-11e8-8341-041f6d631859.png)

**Comment by arthurengeletrica** [comment]
![image](https://user-images.githubusercontent.com/38858258/40017395-a44f7282-578f-11e8-95d5-fefbf7d8d15e.png)

**Comment by SgtBatten** [comment]
Please use the template and resubmit.

**Comment by arthurengeletrica** [comment]
Where is the template?
