### ISSUE TITLE
StopLoss

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer#1864]
Ver 2.0.4
Binance
Ubuntu 16.04
StopLoss at -4%
Stoploss shows in gui but is not executed
Updated did not fix

 DEFAULT_stop_loss_trigger = -4
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2002247/ProfitTrailer.log)

DEFAULT_trading_enabled = true
start_balance = 1.37105975

market = ETH
keep_balance = 0
keep_balance_percentage = 0

BTC_dust = 0.00105
enabled_pairs = ONT,
hidden_pairs = ALL

max_trading_pairs = 4
DEFAULT_min_buy_volume = 150

pair_min_listed_days = 15
DEFAULT_min_buy_price = 0.00000600
DEFAULT_buy_min_price_increase = -10
DEFAULT_buy_max_price_increase = 10
DEFAULT_max_buy_spread = 0.5

DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 100

orderbook_profit_calculation = true

DEFAULT_DCA_enabled = false
DEFAULT_A_buy_strategy = STOCH
DEFAULT_A_buy_value = 20

#DEFAULT_B_buy_strategy = RSI
#DEFAULT_B_buy_value = 66
#DEFAULT_B_buy_value_limit = 62
DEFAULT_buy_on_first_signal = true

DEFAULT_rebuy_timeout = 1
DEFAULT_min_order_book_volume_percentage = 0

#DEFAULT_A_sell_strategy = MACD
#DEFAULT_A_sell_value = 0.00005

DEFAULT_B_sell_strategy = GAIN
DEFAULT_B_sell_value = 0.1
#DEFAULT_trailing_profit = 0.01

DEFAULT_C_sell_strategy = STOCH
DEFAULT_C_sell_value = 70

DEFAULT_max_profit = 0

DEFAULT_take_profit_wait_time = 0DEFAULT_trading_enabled = true
start_balance = 1.37105975

market = ETH
keep_balance = 0
keep_balance_percentage = 0

BTC_dust = 0.00105
enabled_pairs = ONT,
hidden_pairs = ALL

max_trading_pairs = 4
DEFAULT_min_buy_volume = 150

pair_min_listed_days = 15
DEFAULT_min_buy_price = 0.00000600
DEFAULT_buy_min_price_increase = -10
DEFAULT_buy_max_price_increase = 10
DEFAULT_max_buy_spread = 0.5

DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 100

orderbook_profit_calculation = true

DEFAULT_DCA_enabled = false
DEFAULT_A_buy_strategy = STOCH
DEFAULT_A_buy_value = 20

#DEFAULT_B_buy_strategy = RSI
#DEFAULT_B_buy_value = 66
#DEFAULT_B_buy_value_limit = 62
DEFAULT_buy_on_first_signal = true

DEFAULT_rebuy_timeout = 1
DEFAULT_min_order_book_volume_percentage = 0

#DEFAULT_A_sell_strategy = MACD
#DEFAULT_A_sell_value = 0.00005

DEFAULT_B_sell_strategy = GAIN
DEFAULT_B_sell_value = 0.1
#DEFAULT_trailing_profit = 0.01

DEFAULT_C_sell_strategy = STOCH
DEFAULT_C_sell_value = 70

DEFAULT_max_profit = 0

DEFAULT_take_profit_wait_time = 0
DEFAULT_take_profit_percentage = 0

DEFAULT_stop_loss_trigger = -4
DEFAULT_stop_loss_timeout = 1
DEFAULT_panic_sell_enabled = false

DEFAULT_pending_order_wait_time = 0
DEFAULT_combined_cancel_pending_trigger = 0

DEFAULT_sell_only_mode_enabled = false

#price_trigger_market = BTC
#price_rise_trigger = 7
#price_rise_trigger_recover = 6
#price_drop_trigger = 10
#price_drop_recover_trigger = 3

consecutive_buy_trigger = 6
consecutive_sell_trigger = 4

BNB_trading_enabled = false
DEFAULT_hidden_pairs = BNB
DEFAULT_take_profit_percentage = 0

DEFAULT_stop_loss_trigger = -4
DEFAULT_stop_loss_timeout = 1
DEFAULT_panic_sell_enabled = false

DEFAULT_pending_order_wait_time = 0
DEFAULT_combined_cancel_pending_trigger = 0

DEFAULT_sell_only_mode_enabled = false

#price_trigger_market = BTC
#price_rise_trigger = 7
#price_rise_trigger_recover = 6
#price_drop_trigger = 10
#price_drop_recover_trigger = 3

consecutive_buy_trigger = 6
consecutive_sell_trigger = 4

BNB_trading_enabled = false
DEFAULT_hidden_pairs = BNB

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by DragonBtc93** [comment]
![screenshot_20180514_154123](https://user-images.githubusercontent.com/36767505/40019486-61e597a2-578d-11e8-9a3c-5c8ba9d8bbc9.png)

**Comment by YoJeff** [comment]
If that's a straight paste, I would start with eliminating all the duplicates.

Just for kicks, try getting rid of the trailing comma in enabled_pairs and make sure it only occurs once.

**Comment by DragonBtc93** [comment]
Cleaned it up but didn't help

DEFAULT_trading_enabled = true
start_balance = 1.37105975

market = ETH
keep_balance = 0
keep_balance_percentage = 0

BTC_dust = 0.00105
enabled_pairs = ONT
hidden_pairs = ALL

max_trading_pairs = 1
DEFAULT_min_buy_volume = 150

pair_min_listed_days = 15
DEFAULT_min_buy_price = 0.00000600
DEFAULT_buy_min_price_increase = -10
DEFAULT_buy_max_price_increase = 10
DEFAULT_max_buy_spread = 0.5



DEFAULT_initial_cost_percentage = 100

orderbook_profit_calculation = true

DEFAULT_DCA_enabled = false
DEFAULT_A_buy_strategy = STOCH
DEFAULT_A_buy_value = 20

DEFAULT_rebuy_timeout = 1
DEFAULT_min_order_book_volume_percentage = 0

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 0.1
#DEFAULT_trailing_profit = 0.01

DEFAULT_B_sell_strategy = STOCH
DEFAULT_B_sell_value = 70

DEFAULT_max_profit = 0

DEFAULT_take_profit_wait_time = 0
DEFAULT_take_profit_percentage = 0

DEFAULT_stop_loss_trigger = -4
DEFAULT_stop_loss_timeout = 1
DEFAULT_panic_sell_enabled = false

DEFAULT_pending_order_wait_time = 0
DEFAULT_combined_cancel_pending_trigger = 0


DEFAULT_sell_only_mode_enabled = false

consecutive_buy_trigger = 6
consecutive_sell_trigger = 4

BNB_trading_enabled = false
DEFAULT_hidden_pairs = BNB

**Comment by DragonBtc93** [comment]
Ok now it isn't selling at all. I had one in green and did not sell. No trailing is set and both sells where true.

What is this error?
2018-05-15 08:26 -04:00: 2018-05-15 08:26:33 ERROR BinanceWebSocketAdapterKline - onWebSocketError: null

Here is current log
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2005080/ProfitTrailer.log)

Here is my indicator settings 
STOCH_candle_period = 300
STOCH_length = 18

**Comment by helo03** [comment]
"What is this error?
2018-05-15 08:26 -04:00: 2018-05-15 08:26:33 ERROR BinanceWebSocketAdapterKline - onWebSocketError: null"
Websocket error. We can't do anything on that one, that's an error by binance!

For your stoploss problem i'd need more information.
The next time this happens please provide another log and your properties files plus screenshots.
Please specify the timeframe where the stoploss should've triggered but hasn't.

Thank you,
Mario

**Comment by cvthub** [comment]
The behavior happens when the balance is equal to 0, it is a guard for situations when the exchange is delivering wrong data. 
In the latest release the GUI contains an error 'BALANCE CANNOT BE 0' which means the user has to deposit at least 1 satoshi.
