### ISSUE TITLE
LOSS strategy not working

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer#1865]
Strategy: LOSS
The loss trigger does not change to 'true' nomatter the % loss.
The BSV(Buy Strategy Value) values are not correct. They just always equal the set BST(Buy Strategy Trigger) values. 
![image](https://user-images.githubusercontent.com/36821138/40029159-9ccaaca2-57a8-11e8-816f-b805764556db.png)

## ProfitTrailer info
Version: 2.0.3

**Comment by ochiengj** [comment]
Version: 2.0.3

Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

Operating System:
- [X ] Windows (10)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Loss should show actual 24 hr loss (per wiki)

## Current Behavior
constantly equal buy value setting

## Troubleshooting
Tried different buy values
Disabled all other strategies.

## Possible Solution
None

## Steps to Reproduce
1. Set up LOSS strategy
2. Pick any buy value, I used -3.
3. Check if turns 'true' for any pairs under -3

**Comment by Mordozz** [comment]
Not working either

**Comment by cvthub** [comment]
Thanks for reporting! 
Fixed for next release!
