### ISSUE TITLE
EMAGAIN Trailing broken when using positive BST

### ISSUE THREAD

**Issue by HojouFotytu** [taniman/profit-trailer#1869]
When using a positive buy value for EMAGAIN buy strategy, anything above the buy value trigger causes EMAGAIN to show true, and below the buy value trigger is false.  

This was something I used frequently without any issues in PT1.

DEFAULT_A_buy_strategy = EMAGAIN
IOST_A_buy_value = 0.125
IOST_trailing_buy = 0.075

![image](https://user-images.githubusercontent.com/36724681/40041236-44ac4502-5858-11e8-9b51-8f67ef5ddc98.png)
![image](https://user-images.githubusercontent.com/36724681/40041668-c9a526ce-5859-11e8-845a-6aaabc47b9d0.png)

## ProfitTrailer info
Version: 2.0.3

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

EMAGAIN should show true when the BSV is below the BST

## Steps to Reproduce

1.
2.
3.
4.

## Configuration

DEFAULT_A_buy_strategy = EMAGAIN
....
IOST_A_buy_strategy = EMAGAIN
IOST_A_buy_value = 0.1

**Comment by conando2000** [comment]
Imho EMA/SMAGAIN with positive values have alway been "broken" in PT - they always calculate/compare against the _lower_ EMA/SMA line while it should be the lower for negativ values and the upper line for positive values!

Also in PT1 I believe it was even "more broken" as in addition to the wrong line they only checked if the calculated GAIN was below the trigger value, while it should be checked if it's above it for positive values. So it seems like a least this was fixed now and is what you are seeing. ;)

**Comment by helo03** [comment]
Hi HojouFotytu,
The logic for EMA/SMAGAIN has indeed changed in PT2. What you are stating as an issue is working as inteded - so no issue there.
https://wiki.profittrailer.com/doku.php?id=buy_and_sell_strategies#emagain
Please also take a look at the wiki entry.

Hi conando2000,
"broken" is the correct form to put it, as it is designed to work as it is right now. You can always add this as a possible enhancement for upcoming releases and see what the community says.

Thank you,
Mario

P.S I will close this, as it isn't a issue/bug.
