### ISSUE TITLE
2.0.5 - "Error occured in chartData" / price_trigger_market 

### ISSUE THREAD

**Issue by radeksalomon** [taniman/profit-trailer#1870]
The issue #1803 is still not fixed. I am getting the same error on 2.0.3, 2.0.4 and also on 2.0.5. The error appears on USDT market and only if I change "price_trigger_market = USDT" to "price_trigger_market = BTC", the error disappear.

Thanks for fixing it.
Radek

**Comment by YoJeff** [comment]
Verified changing price_trigger_market to USDT (with market BTC) generates invalid api calls, as seen here:

`https://api.poloniex.com/public?command=returnChartData¤cyPair=USDT_USDT&start=1526271960&end=9999999999&period=300-1`

**Comment by radeksalomon** [comment]
OK. Thanks. I am on USDT market with  price_trigger_market=USDT on Bittrex.

**Comment by cvthub** [comment]
The parameter should not be set to USDT as mentioned in the wiki: 
https://wiki.profittrailer.com/doku.php?id=pairs.properties#price_trigger_market

But we will fix that by using BTC as market if users enter USDT here or users leave it empty.
