### ISSUE TITLE
Silent shutdown

### ISSUE THREAD

**Issue by zigzag-way** [taniman/profit-trailer#1871]
## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [x] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Working bot

## Current Behavior
Silent Shutdown once in 2-4 days.

## Possible Solution
Restart

## Steps to Reproduce
Simply run the bot

## Log files/console output

 
No errors in log. The last msgs are HEARTBEATS.

Vultr. CentOS 7 x64
v.2.0.1-2.0.5
Once in 2-4 days the bot silently shuts down.

**Comment by SgtBatten** [comment]
please fill in the template correctly

**Comment by zigzag-way** [comment]
@YoJeff what kind of information can I add here?

**Comment by zigzag-way** [comment]
I`m checking logs with PM2 LOG N. Is it the right way?
If so, then the last line is heartbeat log

**Comment by zigzag-way** [comment]
2.0.5 - silent shutdown again.
Last records from log:
2|BinanceE | 2018-05-19 05:58 +00:00: 2018-05-19 05:58:36 INFO ProfitTrailerService - PAIRS Heartbeat
2|BinanceE | 2018-05-19 06:01 +00:00: 2018-05-19 06:01:57 INFO ProfitTrailerService - DCA Heartbeat
2|BinanceE | 2018-05-19 06:07 +00:00: 2018-05-19 06:07:32 INFO ProfitTrailerService - Cache Heartbeat

**Comment by zigzag-way** [comment]
The only strange thing that I see is the DISK usage spike at the end.

**Comment by SgtBatten** [comment]
Please share the specs of the server

**Comment by mack009009** [comment]
Hi, I have same problem with bot in Binance

**Comment by mack009009** [comment]
VPS in RamNode
RAM / VSwap :+1: 2048 / 256 MB 
CPU 2 Cores 
Storage 60 GB

**Comment by zigzag-way** [comment]
CPU: 1 vCore
RAM: 1024 MB
Storage: 25 GB SSD
OS: CentOS 7 x64

**Comment by zigzag-way** [comment]
One more interesting thing:
I see the DISK usage spike before the crash.

**Comment by SgtBatten** [comment]
I just discovered I could not access my bots. Discovered a similar thing to the Opening Post.

Complete log until crash. Last message is a heartbeat several hours ago.
[ProfitTrailer(pre crash).log](https://github.com/taniman/profit-trailer/files/2041310/ProfitTrailer.pre.crash.log)

![pm2 status](https://user-images.githubusercontent.com/24822223/40572725-108676e2-60f7-11e8-9d33-9436a5f40d62.PNG)
![cpu spike](https://user-images.githubusercontent.com/24822223/40572728-17580030-60f7-11e8-9d27-bcd366dd23aa.PNG)

**Comment by taniman** [comment]
I still believe this to be system dependent. We have some nice improvements in 2.1.0
Not sure if it will make a difference on your system. But not sure we can improve more.

So i am closing this for now
