### ISSUE TITLE
Network, CPU and Disk usage incredibe growth since 2.0.X versions.

### ISSUE THREAD

**Issue by zigzag-way** [taniman/profit-trailer#1872]
## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [x] Other linux distro (please specify)
- [ ] Mac OS

## Possible Solution

After restart, CPU usage decreased from 40% to 20% and network usage from 9.54 Mbps to ~1Mbps (around 10x times less!)

## Log files/console output

 

Vultr. CentOS 7 x64
v.2.0.1-2.0.5

I checked my Vultr stats and see this:
https://yadi.sk/i/qhiLb56c3VyAW2

Looks like memory leaks. Maybe it is the same problem as I mentioned - silent shutdown.

**Comment by SgtBatten** [comment]
please fill in the template and provide more information

**Comment by zigzag-way** [comment]
@YoJeff what kind of information can I add here?

**Comment by zigzag-way** [comment]
Buy EMAGAIN
Sell (PT2x default config):
LOWBB
EMAGAIN
MACD
EMASPREAD
RSI

**Comment by zigzag-way** [comment]
After switching from 2.04. to 2.0.5 CPU decreased from 40->20 and Network decreased about 10x times!

**Comment by djbadders** [comment]
I noticed that the much increased CPU usage only occurs if you are viewing the PT web interface, close this down and the CPU usage per PT instance halves.

**Comment by djbadders** [comment]
Just installed 2.0.9 and unfortunately the CPU usage has doubled per instance of PT even without the web interface open. The CPU usage needs looking at IMO as it is very high. The graph attached shows the CPU before (v2.0.7) and after (v2.0.9), and you can see a significant change to the baseline.

![image](https://user-images.githubusercontent.com/34887832/40679758-f6eaeef2-637b-11e8-84a1-971f766f0043.png)

**Comment by taniman** [comment]
I must admit the bot has a steap cpu usage on startup. But this is how it looks on my machine. And I really do not have to best of laptop
![image](https://user-images.githubusercontent.com/6751341/40681076-67ea4a60-6388-11e8-9542-ffc3dce527f7.png)

**Comment by taniman** [comment]
But working on it.  Looking to find ways to improve

**Comment by djbadders** [comment]
That's good to hear. 

So you are right the CPU did drop back after a while so the start up must have been CPU heavy. Still show a significant CPU jump when I open the web front end though.

**Comment by taniman** [comment]
I have made some progress in V2.1.0. But all in all CPU usage is totally depended on the system being used to run. The bot needs to process lots of data so CPU will need to be used no matter what.
