### ISSUE TITLE
2.0.7 - API Issues MegaIssue.   For API Issues, comment here.

### ISSUE THREAD

**Issue by YoJeff** [taniman/profit-trailer#1873]
## API Issues Megathread

API Issues are always a top priority.    Occasional API errors can be normal.

Comment here with helpful information (screenshots, exchange, relevant log entries)

**Comment by Heartinhand** [comment]
Hi, keep getting error ERROR ProfitTrailerService - CB - Error in reading response connect timed out & 
ERROR ProfitTrailerService - OB - Error in reading response connect timed out

Tried 60 instead of 30. Nothing. 2.0.6

**Comment by YoJeff** [comment]
API issues are continually evaluated/addressed.   Try the latest version.

**Comment by erknie** [comment]
Binance just reset All their API keys an hour ago because of some urgent security issue. That means everyone's PT is no longer registered for Binance until you create two new keys, and go through the process of registering  the default key.
Expect a lot of support queries.

**Comment by Jonconnect** [comment]
Created new api key and changed in the application proprieties.But pt do not reinitialize the new's api key.I have to delete all the pt folder ... ?Deleted ptpw, no change. Thank's for reply
