### ISSUE TITLE
ChartData error

### ISSUE THREAD

**Issue by hrmartins** [taniman/profit-trailer#1877]
Hi,

After the upgrade to version 2.0.5 I get this error in the terminal, every second:

ERROR ProfitTrailerService - Error occured in chartData, message ERROR: -1121, Invalid symbol., result:

any help?

Best regards,

**Comment by YoJeff** [comment]
Does #1803 apply?    What is your price_trigger_market?

**Comment by hrmartins** [comment]
Yes, it applies.
Changed to BTC.

Thank you.
