### ISSUE TITLE
ERROR OCCURED IN CHART DATA

### ISSUE THREAD

**Issue by BOBALLEX** [taniman/profit-trailer#1878]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.05

 
Exchange: 
-  Bittrex
- [ ] Binance
- [ ] Poloniex

 
Operating System:
-  Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

ERROR ProfitTrailerService - Error occured in chartData, message No value was returned, result:
## Steps to Reproduce

1.
2.
3.
4.

## Configuration

#GENERAL SETTINGS#
market = BTC
price_trigger_market = BTC
enabled_pairs = ALL
hidden_pairs = 
DEFAULT_trading_enabled = true
DEFAULT_DCA_enabled = -1.2
start_balance = 0.05
keep_balance = 0
keep_balance_percentage = 1
orderbook_profit_calculation = true
#---------------------------------------------------------------
#INITIAL BUY SETTINGS#
max_trading_pairs = 15
DEFAULT_initial_cost = 0.0012
DEFAULT_initial_cost_percentage = 0
DEFAULT_min_buy_volume = 20
DEFAULT_min_buy_price = 0
DEFAULT_max_buy_spread = 3
DEFAULT_min_orderbook_volume_percentage = 100
DEFAULT_rebuy_timeout = 0
DEFAULT_buy_min_change_percentage = -20
DEFAULT_buy_max_change_percentage = 10
pair_min_listed_days = 5
#---------------------------------------------------------------

DEFAULT_A_buy_strategy = RSI
DEFAULT_A_buy_value = 30
DEFAULT_A_buy_value_limit = 0
DEFAULT_B_buy_strategy = STOCH
DEFAULT_B_buy_value = 20
DEFAULT_B_buy_value_limit = 0
DEFAULT_trailing_buy = 0
#---------------------------------------------------------------
#SELL STRATEGY#
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1
DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 35
DEFAULT_trailing_profit = 0.17
DEFAULT_max_profit = 0
DEFAULT_take_profit_wait_time = 0
DEFAULT_take_profit_reset_percentage_move = 0
DEFAULT_take_profit_percentage = 0
#---------------------------------------------------------------
#SETTINGS THAT CAN LOSE YOU MONEY
DEFAULT_panic_sell_enabled = false
DEFAULT_stop_loss_trigger = 0
DEFAULT_stop_loss_timeout = 0
#---------------------------------------------------------------
#COIN SPECIFIC SETTINGS#
#BNB_trading_enabled = false

#GENERAL SETTINGS#
DEFAULT_DCA_max_cost = 0.1
DEFAULT_DCA_max_buy_times = 3
DCA_keep_balance = 0
#---------------------------------------------------------------
#BUY FILTER SETTINGS#
DEFAULT_DCA_buy_min_change_percentage = 0
DEFAULT_DCA_buy_max_change_percentage = 0
DEFAULT_DCA_max_buy_spread = 3
DEFAULT_DCA_rebuy_timeout = 0
DEFAULT_DCA_min_buy_volume = 10
DEFAULT_DCA_min_orderbook_volume_percentage = 110
DEFAULT_DCA_ignore_sell_only_mode = true
#---------------------------------------------------------------
DEFAULT_DCA_A_buy_strategy = RSI
DEFAULT_DCA_A_buy_value = 30
DEFAULT_DCA_A_buy_value_limit = 0
DEFAULT_DCA_B_buy_strategy = STOCH
DEFAULT_DCA_B_buy_value = 20
DEFAULT_DCA_B_buy_value_limit = 0.1
DEFAULT_DCA_trailing_buy = 0
DEFAULT_DCA_buy_percentage_1 = 100
DEFAULT_DCA_buy_trigger_1 = -5
DEFAULT_DCA_buy_percentage_2 = 60
DEFAULT_DCA_buy_trigger_2 = -8
DEFAULT_DCA_buy_percentage_3 = 30
DEFAULT_DCA_buy_trigger_3 = -10
DEFAULT_DCA_buy_trigger_4 = -10
DEFAULT_DCA_buy_trigger_5 = -20
#---------------------------------------------------------------
#SELL SETTINGS#
DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 1
DEFAULT_DCA_B_sell_strategy = RSI
DEFAULT_DCA_B_sell_value = 35
DEFAULT_DCA_trailing_profit = 0.17
DCA_orderbook_profit_calculation = true
DEFAULT_DCA_max_profit = 0
DEFAULT_DCA_take_profit_wait_time = 0
DEFAULT_DCA_take_profit_reset_percentage_move = 0
DEFAULT_DCA_take_profit_percentage = 0
#---------------------------------------------------------------
#TRIGGERS#
DEFAULT_DCA_stop_loss_trigger = 0
DEFAULT_DCA_stop_loss_timeout = 0
DEFAULT_DCA_pending_order_wait_time = 0

BB_std = 2
BB_candle_period = 900
BB_length = 20
SMA_cross_candles = 2
SMA_candle_period = 900
SMA_fast_length = 12
SMA_slow_length = 24
EMA_cross_candles = 2
EMA_candle_period = 900
EMA_fast_length = 8
EMA_slow_length = 13
RSI_candle_period = 300
RSI_length = 7
STOCH_candle_period = 300
STOCH_length = 7
MACD_candle_period = 900
MACD_fast_length = 12
MACD_slow_length = 26
MACD_signal = 9
OBV_candle_period = 900
OBV_length = 50
OBV_signal = 1

SOM_trigger_length = 288
## Log files/console output

 
![image](https://user-images.githubusercontent.com/36281599/40189443-2625071e-5a05-11e8-8294-f8ad5cfa0484.png)

**Comment by SgtBatten** [comment]
3 questions.

Does increasing connection.timeout help?

What country is the bot in?

Have you tried another internet connection.
