### ISSUE TITLE
[Issue] SOM in http://wiki.profittrailer.com/converter

### ISSUE THREAD

**Issue by tooraj-enayati** [taniman/profit-trailer#1880]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.3

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
http://wiki.profittrailer.com/converter to convert coin specific SOM setting properly. 
converts:

## Current Behavior

http://wiki.profittrailer.com/converter
converts:
ADABTC_sell_only_mode = true
to:
ADA_sell_only_mode = true

It should convert it to ADA_sell_only_mode_enabled = true

## Troubleshooting

Tested both ADA_sell_only_mode = true and ADA_sell_only_mode_enabled = true. ADA_sell_only_mode = true doesn't work.

## Possible Solution

Fix http://wiki.profittrailer.com/converter

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
fixed now.
