### ISSUE TITLE
again problems with loss bought price of the price at sale

### ISSUE THREAD

**Issue by clippart** [taniman/profit-trailer#1882]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x] Other linux distro (centos 7)
- [ ] Mac OS

## Current Behavior

Again problems with loss of the price at sale

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 
![default](https://user-images.githubusercontent.com/33903011/40269296-e28e49d6-5ba6-11e8-987a-820fbe9067d0.PNG)

**Comment by echthard** [comment]
They closed the previous bug bc it should be fixed in 2.0.7. But I think there are more bugs now, concerning calculation of avg bought price, then there were before.

**Comment by taniman** [comment]
@clippart  without log fiels this issue will be closed. just a screenshot is not enough to figure our your particular problem

**Comment by clippart** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2020914/ProfitTrailer.log)

**Comment by taniman** [comment]
@clippart your screenshot shows ELFBTC but your log file does not contain any info about this pair

**Comment by clippart** [comment]
![zrx](https://user-images.githubusercontent.com/33903011/40311797-1b76a776-5d3b-11e8-8bd6-e7797838a867.PNG)
sorry. reupload

**Comment by YoJeff** [comment]
So what are we supposed to do with this?  I see a screenshot with circled prices.   The price is not "lost", it's there.  

If the price is wrong, how do you know it's wrong.  Show your calculations.

**Comment by clippart** [comment]
Are you laughing? How does the purchase price after 3 minutes become less?

**Comment by clippart** [comment]
unloading from the exchange
![default](https://user-images.githubusercontent.com/33903011/40313752-a9a1a438-5d40-11e8-9837-c31e3606e848.PNG)

**Comment by clippart** [comment]
[TradeHistory.xlsx](https://github.com/taniman/profit-trailer/files/2023027/TradeHistory.xlsx)

**Comment by taniman** [comment]
2.0.11 has a fix for this
