### ISSUE TITLE
Manual buy (DCA) results in incorrect Avg Price 

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer#1883]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

I just bought ZIL manually, while I have it in DCA at -10%. After the buy was hit, I then checked if it would go to -4% or something in DCA, but it was at +16.95% 

Luckily I quickly closed PT, bc otherwiste it would have sold it with a loss.
## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

![image](https://user-images.githubusercontent.com/1479483/40270081-849e0790-5b87-11e8-8bd8-2be0ff5c7a7b.png)

**Comment by taniman** [comment]
Update to 2.0.11. If problem reoccurs you will need to provide a log file with your new issue
