### ISSUE TITLE
Buying in Sell zone instead of Buy zone

### ISSUE THREAD

**Issue by Manix343** [taniman/profit-trailer#1885]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.5

 
Exchange:
- [X] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [X] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (10)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The bot purchased three pairs when the price was in Sell zone (STOCH high, LOWBB value also high) instead of Buy zone.

## Current Behavior

It's only happened this one time. I'm in Testmode. I'm restarting the bot 2-3 times a day in non crucial times, because it hangs and STOPS EVERYTHING :-/ when I don't restart it every so often. 

## Troubleshooting

I've tried restarting the bot with CTRL-C. I've checked PAIR settings and DCA settings to ensure correct buy/sell values. 

## Possible Solution

Ask devs to fix major bugs before releasing new versions. I can't even take my bot out of TESTMODE because of so many bugs. 

## Steps to Reproduce

1. Testmode
2. LOWBB 10
3. STOCH 0
4. USDT Market

## Configuration

https://pastebin.com/ZRSgQw7B

## Log files/console output

 

Log File attached

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2019946/ProfitTrailer.log)

![omg early buy chart](https://user-images.githubusercontent.com/5381013/40274903-6eb99da8-5b97-11e8-8145-4c2bcdec4aad.png)
![omg early buy](https://user-images.githubusercontent.com/5381013/40274904-6ed47a56-5b97-11e8-9100-b1b1afe52a5e.png)
![profit trailer early buys](https://user-images.githubusercontent.com/5381013/40274905-6ef4a93e-5b97-11e8-953f-b2be73e333af.png)

**Comment by cvthub** [comment]
Thanks for the accurate problem description!! 
We could not reproduce the behavior, but have enhanced logging in the latest version. If it happens again, please create a new issue and provide the log entries (like that one of the current issue).
