### ISSUE TITLE
manual 1x time bought coin shows a DCA level of 5 after PT2 picked up the buy

### ISSUE THREAD

**Issue by jpfl** [taniman/profit-trailer#1886]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:
2.0.7
 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [ x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ x] Windows (please specify version) 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

coin should not show any DCA level as it was just bought 1x manually using the binance windows app

## Current Behavior

coin shows  DCA level of 5 and also shows "BUY VALUE BELOW DUST" though the bought price was much higher than the BTC dust level.

## Troubleshooting

restarting bot 2

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

![image](https://user-images.githubusercontent.com/8434770/40275280-dae1d0d4-5bda-11e8-8c9b-7423e23e0861.png)

![image](https://user-images.githubusercontent.com/8434770/40275284-e0c44aea-5bda-11e8-8189-9bdc1c695d4e.png)

**Comment by SgtBatten** [comment]
https://wiki.profittrailer.com/doku.php?id=faq#i_manually_bought_a_coin_and_it_already_has_a_dca_count

**Comment by SgtBatten** [comment]
Well that would be very interesting.

Please provide your log file and the entire exchange history for the affected coin.

Buy value below dust is a completely seperate thing and simply says your DCA buy percentage 6 would be too small for the exchange minimum.

**Comment by jpfl** [comment]
ok, I added the logfile from the PT2 main folder and the binance order and trade history for the coin PPT. it started 5/13 until now. 
This is the first time looking at log files for PT, the odd thing to me is that logs don't cycle and get compressed regularly and don't cover every day of trading.
there are only 2 log directories 2018-04 with data from 4/29 onward (time the bot was installed on this machine). bot not covering data until the end of april but only containing one file covering 180426-2239 - 180429-0215
and 2018-05 directory containing two compressed files one covering 180504-0049-180504-0152 and the other covering 180504-0151 - 180513-0401.
I am missing log data between 4/29-5/4 it seems.
the bot was running 24/7 with very little downtime for booting or updating since 4/26

[ProfitTrailer-180513-0400-180521-0413.zip](https://github.com/taniman/profit-trailer/files/2021264/ProfitTrailer-180513-0400-180521-0413.zip)
[PPT-OrderHistory.xlsx](https://github.com/taniman/profit-trailer/files/2021267/PPT-OrderHistory.xlsx)
[PPT-TradeHistory.xlsx](https://github.com/taniman/profit-trailer/files/2021268/PPT-TradeHistory.xlsx)

**Comment by SgtBatten** [comment]
PT does not compress logs on its own. Nor does it omit anything. It has one log file that should have the entire history since you first ran the bot unless you clipped or deleted it yourself.

I have not looked at your logs as I cant on my phone, but that doesn't make sense to me what you are describing.

**Comment by YoJeff** [comment]
PT does in fact compress logs on it's own, but it's a work in progress.

**Comment by SgtBatten** [comment]
Well then. My bad

**Comment by jpfl** [comment]
happened again today. Bot bought BCN 1x and it showed DCA 1x right away. and wrong average price. I did correct the DCA count and purchase price in the hotconfig.
![image](https://user-images.githubusercontent.com/8434770/40355788-e222e522-5da6-11e8-8ce7-d96845736bad.png)
![image](https://user-images.githubusercontent.com/8434770/40355803-e9791c88-5da6-11e8-9a4e-967743e2a28b.png)
![image](https://user-images.githubusercontent.com/8434770/40355825-f494caf4-5da6-11e8-857e-82cc3fc8b3c3.png)
![image](https://user-images.githubusercontent.com/8434770/40355834-fa9f4686-5da6-11e8-8729-56f03e5eb757.png)
![image](https://user-images.githubusercontent.com/8434770/40355842-007b05d6-5da7-11e8-9163-d9544bb3b50d.png)
![image](https://user-images.githubusercontent.com/8434770/40355859-06154d76-5da7-11e8-9e50-ac28cb80c342.png)
![image](https://user-images.githubusercontent.com/8434770/40355869-0accab20-5da7-11e8-9ba9-1eff3c22a514.png)
[ProfitTrailer.log-180513-0400-180522-0949.zip](https://github.com/taniman/profit-trailer/files/2026044/ProfitTrailer.log-180513-0400-180522-0949.zip)

**Comment by taniman** [comment]
As you can see from your log file DCAStrategyRunner bought BCN. There is 0% chance that DCA will run for a coin if you do not own this pair.

The DCA you show in your log file bought 1681 BCN

![image](https://user-images.githubusercontent.com/6751341/40450747-dca0fea4-5edc-11e8-8df1-99239a99f31b.png)


So where did this other 1681 BCN come from as you own actually total of 3362 as I can see from yuor screenshot.

Looking forward to hearing this answer from you

**Comment by taniman** [comment]
I have gone and looked further into this. Cause your tradehistory screenshot shows up until the 17th. But the first DCA happened on the 22nd

So my screenshot from above is from the 22nd.

The following screenshot is from when the bot bought on the 17nd
![image](https://user-images.githubusercontent.com/6751341/40451039-9ad554a6-5edd-11e8-9166-6a726d405198.png)


So initial buy 17nd price is 119
on the 22nd bought price is 104

rough calculation
(119+104) /2   = 111

So the average price was 100% correct. You have now made it incorrect

Please check your Binance tradehistory again and fix the date to show buys after the 21st too. 
You will see that I am correct in what I am explaining to you

**Comment by taniman** [comment]
Hi. The PPT is also correct.
Manual buys that by pass the bot functions will prevent the bot from reset the logic it needs to reset correctly.

The buy times you can reset using the hotconfig option. 

This 'issue' is not really an issue as there is no smarter way to deal with this from the bot perspective. yet.

**Comment by jpfl** [comment]
it worked before and still works with many manual buys. coins which at the time of the manual buy were not in the binance account. that's why people are able to use signals (or buy manual) and have the bot do the DCA and selling part. just with PPT this one time it did not work out. 1x buy and showing DCA 5 is a bit messed up.

**Comment by omarmoss** [comment]
I experienced the same issue yesterday manually buying TUSD.
Hope the latest update today (2.1.18) resolves this 'DCA count' problem.
