### ISSUE TITLE
DCA Always buying 100% even if settings set to 100,50,40... etc.

### ISSUE THREAD

**Issue by shadowbladers** [taniman/profit-trailer#1887]
Version: 2.0.4

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Dca should be buying at levels 100,50,40,30,20 but always dca's at 100%
## Current Behavior

Every coin is always dca'ing as 100%

## Troubleshooting

- talk to discord staff. (told me to submit report)
- check over settings
- i am running feeder but it shouldnt affect the bug.

## Possible Solution
No idea
## Steps to Reproduce
--
## Configuration

https://pastebin.com/eNJ9Uqbr
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2020000/ProfitTrailer.log)

## Log files/console output

 

^^

**Comment by SgtBatten** [comment]
Please submit:
1. Screenshot of exchange order history for one of these example coins.
2. The ordersettings file that corresponds with one of the DCA  purchases that should not be 100.

Without these we can not investigate anything.

**Comment by taniman** [comment]
@shadowbladers Please provide your zipped ordersettings folder.
