### ISSUE TITLE
Bought price gets lost

### ISSUE THREAD

**Issue by xandorlv** [taniman/profit-trailer#1889]
## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Binance

 
Market:
- [ ] BTC

 
Operating System:
- [ ] Windows (please specify version)
- [X] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Coin bought before started using PT where I manually set the price with hotconfig should stay.

## Current Behavior
I have BNB bought before I started using PT and its price is reset to unknown as of 2.0.5

## Troubleshooting
Manual bought price setting in hotconfig temporary fixed, but later it gets reset without me restarting the bot.

**Comment by SgtBatten** [comment]
Are we on my talking about BNB here?

It will contact get forgotten because the amount you own changes constantly. The bit cannot safely assume this is only due to fees. You might be depositing and withdrawing so we can't assume and keep the same price.

**Comment by xandorlv** [comment]
Yes, BNB. Only for fees. Before 2.0.5 it was stably keeping the bought price since upgrade to 2.0.

**Comment by SgtBatten** [comment]
You were lucky with it sticking before.

This is normal for BNB. Most people choose to hide it. If you don't want to hide it then you will need to ignore any messages about BNB bought price.

**Comment by xandorlv** [comment]
OK, I will use your suggestion and hide it.
