### ISSUE TITLE
Indicator Request: RSI

### ISSUE THREAD

**Issue by Concept211** [taniman/profit-trailer#189]
I feel that RSI is incredibly useful.

**Comment by minerdude** [comment]
agreed

**Comment by dechut** [comment]
agreed , waiting for it

**Comment by Concept211** [comment]
The ultimate strategy would be a combination of RSI + BB for both buy and sell triggers on longer time frames like 1HR, 4HR, 1DAY. Patient, but very profitable potential swings.
