### ISSUE TITLE
Wrong purchase. The bot bought against my buying strategy

### ISSUE THREAD

**Issue by LoukisD** [taniman/profit-trailer#1892]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
![image](https://user-images.githubusercontent.com/37137814/40312290-2435b624-5d1b-11e8-88b9-0fd4baf420c6.png)

As you can see in the screen shot above, the bot reads "true" the OBV & MACD strategies even if there are not! A couple of minutes later makes the buy as you can see in the image below.

![image](https://user-images.githubusercontent.com/37137814/40312413-7c85b13a-5d1b-11e8-8208-dd88fface234.png)

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output
[PT LOG FILE.txt](https://github.com/taniman/profit-trailer/files/2022983/PT.LOG.FILE.txt)

**Comment by LoukisD** [comment]
Please check the log file after 10:15 when I installed the new PT version

**Comment by SgtBatten** [comment]
Once trailing starts the strategy values are ignored. This has been this way since v2 launch.

The bit only cares about the price once trailing starts. For it to buy it must have dropped enough to then trail back up but remain under the price at which trailing started.

Unless you can demonstrate how this did not occur it looks to be working as designed.

**Comment by taniman** [comment]
I am fairly certain that al strategies need to be true before trailing starts. As far as I can see there is no bug in this logic. 
The newer versions have extra logging logic that we could use in the future if this happens again
