### ISSUE TITLE
How to sell coin by an indicator signal, no matter what GAIN value is

### ISSUE THREAD

**Issue by DmitryBychenko** [taniman/profit-trailer#1893]
## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ x] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Bot to sell coins when indicator signal becomes true, no matter what current GAIN value is. For example,

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 2.0

DEFAULT_B_sell_strategy = MACD
DEFAULT_B_sell_value = -0.000000001

DEFAULT_stop_loss_trigger = -1

Bot should sell the coin even if current Profit value =1%, or 0.5%, or -0.5%.

## Current Behavior
1. If GAIN is > 0, for example GAIN = 2.

  1a. If Profit is > 2% of buy price, PT sells coin after MACD intersection (GAIN = 2 is true, MACD = -0.000000001 is true)
  1b. If Profit is < 2% of buy price, PT will not sell the coin after MACD intersection (GAIN = 2 is false, MACD = -0.000000001 is true)
  1c. If  Profit is < 0% of buy price, PT will not sell the coin after MACD intersection (GAIN = 2 is false, MACD = -0.000000001 is true)

2. If GAIN is < 0, for example -1.
   
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = -1

DEFAULT_B_sell_strategy = MACD
DEFAULT_B_sell_value = -0.000000001

DEFAULT_stop_loss_trigger = -1

[https://www.dropbox.com/s/8h8qcra4hcq3jmt/gain-1.png?dl=0](url)

In this case coin most likely will be sold by stoploss. One positive deal is done by DEFAULT_trailing_profit = 0.45.

[https://www.dropbox.com/s/omvsh5d3cggrnhe/gain-1_stoploss.png?dl=0](url)

## Troubleshooting
I tried to set GAIN to negative value, but in this case almost all deals close at stoploss.

## Possible Solution
1. Create one more command

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 2.0

DEFAULT_B_sell_strategy = MACD
DEFAULT_B_sell_value = -0.000000001

DEFAULT_stop_loss_trigger = -1

DEFAULT_forcesell_strategy = MACD           _(solution)_
DEFAULT_forcesell_value = -0.000000001    _(solution)_

or

2. Create one more parameter for DEFAULT_X_sell_strategy = XXX

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 2.0

DEFAULT_B_sell_strategy = MACD
DEFAULT_B_sell_value = -0.000000001
DEFAULT_B_sell_on_single_signal = true   _(solution)_

DEFAULT_stop_loss_trigger = -1

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output
Settings, logs:
[https://www.dropbox.com/s/mdaeig10kyywvd7/ordersettings.zip?dl=0](url)

**Comment by YoJeff** [comment]
This is by design.

>  Remember that with multiple indicators for selling, you must use GAIN as the base strategy to set the minimum % profit gain.

**Comment by DmitryBychenko** [comment]
Right, GAIN is mandatory setting, but how to sell by signal ? 
There is signal to sell (changing volume, emaspread is too big or too low, emacross, or whatever), but bot doesnt sell, and you need to watch bot time after time, and sell coins manually when there is signal to sell.

Bot should do the job automatically, this is bot's purpose.

**Comment by YoJeff** [comment]
It is not possible to ignore GAIN.

**Comment by YoJeff** [comment]
As stated.  GAIN is required.   If this is a question, use support.   If this is a feature request, post request here:  https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by SgtBatten** [comment]
I recently learned GAIN can be negative.

So if someone wants to risk this they can set GAIN to be negative so it's always true

**Comment by DmitryBychenko** [comment]
It is written in Current Behavior #2
