### ISSUE TITLE
Panic Sell caused partial sell with incorrect profit information

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#1895]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version) 
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

Bought price has changed after the first partial sell. 0.00016077 is the correct bought average.

## Steps to Reproduce

1. Coin DCA'ed few times.
2. Panic sell the coin XXX_panic_sell_enabled = true
3.
4.

## Log files/console output

 
[Profit Trailer Log.txt](https://github.com/taniman/profit-trailer/files/2027606/Profit.Trailer.Log.txt)

![image](https://user-images.githubusercontent.com/37293938/40376235-8995f688-5df6-11e8-99d6-a7ec34d1fab4.png)

**Comment by HomeY** [comment]
I can confirm this is still broken in 2.0.8
![wan_panicsell_incorrect_bought_price](https://user-images.githubusercontent.com/1996332/40584571-4c2ce1b6-61a3-11e8-9ddd-8d00c2fefa0e.JPG)
https://pastebin.com/NybSVw7X

**Comment by HojouFotytu** [comment]
I've also noticed after every panic sell, the bot recalculated the average purchase price incorrectly, after a partial sale.

**Comment by taniman** [comment]
2.0.11 has a possible fix
