### ISSUE TITLE
Panic Sell off DCA'ed coins doesn't show the 'x times DCA' number in Sales log

### ISSUE THREAD

**Issue by HomeY** [taniman/profit-trailer#1896]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (Server 2012 R2)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When a coin has been DCA'ed and the sale is finished, i would expect a 'number' showing in the Bought/Sold Price column. This seems to work fine for automated sells, but not for Panic Sells.

DCA indicator in sales log (only working for automated sales):
![image](https://user-images.githubusercontent.com/1996332/40434909-b7a087f0-5eaf-11e8-8ef0-e67961601a7f.png)

## Current Behavior

Execute a Panic Sell of a DCA'ed coin and check the Sales log for the number (it's not showing)
## Troubleshooting

Upgraded to latest version, but issue still present
## Steps to Reproduce

1. Have a DCA'ed coin in your DCA log
2. Execute a Panic Sell of the coin
3. Check Sales log to see the number that indicates the x times a coin got DCA'ed
4.

## Log files/console output

 
https://pastebin.com/D5WzWvX1

**Comment by SgtBatten** [comment]
Just to clarify you have done a panic sell on 2.0.7 yes?

**Comment by HomeY** [comment]
Yes.
