### ISSUE TITLE
Feature Request: Custom Strategies using Multiple Indicators

### ISSUE THREAD

**Issue by Concept211** [taniman/profit-trailer#190]
Would it be possible to use a combination of indicators? For instance, I usually use BB in conjunction with RSI and sometimes MACD to confirm my buy/sell levels when I trade manually. This would be the perfect feature! 

Thinking further, it would be great if in the future there was some sort of plugin system to allow us to code our own logic for our own custom strategies.

I'm just daydreaming, but I believe people would love something like this.

Thank you!

**Comment by taniman** [comment]
see this #82
