### ISSUE TITLE
PT + PTFeeder do not trade for 2 weeks

### ISSUE THREAD

**Issue by Alexbkk18** [taniman/profit-trailer#1901]
## ProfitTrailer info
Version: 2.0.6

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [x] Mac OS

## Expected Behavior
Automatic trades with Profit Trailer Feeder

## Current Behavior
the bot is active for 2 weeks now and no trades, no possible buys until now

## Troubleshooting
none

## Possible Solution
bad configuration

## Configuration
[application.properties](https://pastebin.com/e8xpaq5k)
[PAIRS.properties](https://pastebin.com/cpDQvnv2)
[INDICATORS.properties](https://pastebin.com/M38eFfHj)
[DCA.properties](https://pastebin.com/0DqQEk6z)

## Log files/console output
[ProfitTrailer.log](https://pastebin.com/x2TSaMDi)

**Comment by SgtBatten** [comment]
This is not really a bug. You almost certainly have a config issue as you suspected. 

This can be resolved on discord however feeder specific support is not available from our discord. They have their own discord for feeder.

As for an empty possibly buy log we have an FAQ entry for this.

https://wiki.profittrailer.com/doku.php?id=faq#why_is_my_possible_buy_log_empty
