### ISSUE TITLE
Exceptions with google.gson and cache

### ISSUE THREAD

**Issue by GuillerVks** [taniman/profit-trailer#1907]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.9

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [X] Ubuntu (16.04.3)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

I don't know exactly what is the problem, but with previous versions, I never had problems with them. I had errors and this problems create a high load average in my server.

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

[ProfitTrailer_short.log](https://github.com/taniman/profit-trailer/files/2057159/ProfitTrailer_short.log)

**Comment by taniman** [comment]
fixed in next release
