### ISSUE TITLE
Strange behavior after fresh install 2.0.9

### ISSUE THREAD

**Issue by LordRofl** [taniman/profit-trailer#1908]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.9

 
Exchange:
- [x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x] Other linux distro (please specify) Debian 8
- [ ] Mac OS

## Expected Behavior

When visiting the Webpage the first time it asks you for new password and after that it asks you for settings name. To get this done you need to enter a name. This name i dont know why, is also available when you delete the whole folder and reupload the files for a new install. Where the heck saves pt this information? I use the pm2 method.

After naming the settings it delete the files in /initialization folder and creates a /old folder where the files are now. But where are the active files?

This is a bit hard for me to tell you what is wrong, please do a fresh install of 2.0.9 and you should see that something is strange.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
settings are stored encrypted online or encrypted offline. But yes. initialization folder is only for first setup
