### ISSUE TITLE
Many Problems with Ver 2.0.10

### ISSUE THREAD

**Issue by xyr0x** [taniman/profit-trailer#1909]
I have the following errors with the verse 2.0.10

- Euro (€) is set as currency, but $ is displayed
- The dashboard does not show a conversion into the currency
- The dahboard does not show values from the logs to e.g. EUR Estimated Value

**Comment by taniman** [comment]
Please take a look at https://demo.profittrailer.io/monitoring
EUR values are working for 2.0.10

I understand from the frontend that this is caching problem. Please try ctrl + f5 or a difference browser or incognito to verifiy if there is a problem or not.

On my end this is working correctly though

**Comment by hirostredor** [comment]
I have the same problem. V2.0.10 does not show me the amounts in an alternative currency. CTRL + F5 did not help but it works properly in incognito mode with Chrome.

**Comment by xyr0x** [comment]
STRG + F5 dosnt work!

**Comment by SgtBatten** [comment]
Shift +f5 loads the page without cache in chrome. Not sure ctrl+f5 does

**Comment by taniman** [comment]
@hirostredor if incognito works this means it's a cache problem. Please try also @SgtBatten suggestion above.

@xyr0x  did you try incognito ?

**Comment by smoochy** [comment]
I was faced with the same issue after updating to 2.0.10.
In another browser and in incognito Mode of Chrome, € were correctly displayed.

Solution was quite simple: Delete cookies and cache for the website of PT. Now everything is displayed correctly again.

**Comment by clownfish44** [comment]
Clearing the cookies and cache has worked for everyone so far in the support channel.
