### ISSUE TITLE
min volume at DCA

### ISSUE THREAD

**Issue by freeebits** [taniman/profit-trailer#191]
Hi,

Sometimes we realized the DCA'd coin has a very small volume at the exchange and it's difficult to sell them with gain.

So wonder if you can add the new option called min volume at DCA properties so that DCA can only happen when the coin's volume is higher than the specific volume size.

Thanks.

**Comment by taniman** [comment]
What you are asking is the same as this right?

Allow DCA to buy if there's enough volume in order book to fill the order
This prevent partial buys that might disturb the DCA strategy
100% means there should be at least the amount we wanna buy in the orderbook
150% means. there shoud be 150% of the amount we wanna buy in the orderbook to issue the buy order
So if you need 5 coins at price A..orderbook should have atleast 7.5 coins at price A or lower
`buy_available_volume_trigger = 150`

So DCa will only buy if there is enough volume

**Comment by freeebits** [comment]
No. It means BTC volume not the volume in order book.
It's something like ALL_min_buy_volume when applying DCA. 
i.e. I want my bot only to run DCA for the coins where BTC volume is higher than 500. I set ALL_min_dca_volume = 500.

**Comment by openbcc** [comment]
Yep +1 on this request. Some markets are too small to play with.
