### ISSUE TITLE
PT 2.0.10 - Bot sold with 13,75% profit but on binance it is a loss

### ISSUE THREAD

**Issue by Skeptain** [taniman/profit-trailer#1910]
Just some minutes ago my bot bought a coin and sold it just seconds afterwards with a predicted 13,75% profit. But on binance I can see clearly it has been sold with a loss.

![pt1](https://user-images.githubusercontent.com/29499347/40872667-68adbffa-6652-11e8-85cc-1a60b068f7b6.png)
![pt2](https://user-images.githubusercontent.com/29499347/40872670-6d21196a-6652-11e8-83ae-32da5a02b394.png)
![pt3](https://user-images.githubusercontent.com/29499347/40872671-716487f0-6652-11e8-9876-a8bffa574c12.png)

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [X] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [X] ProfitPi
- [ ] Mac OS

## Expected Behavior

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1
DEFAULT_trailing_profit = 0.15
DEFAULT_max_profit = 3

## Configuration
[PAIRS](https://pastebin.com/p4C0Sp9L)
[DCA](https://pastebin.com/sPzQGMQV)
[INDICATORS](https://pastebin.com/5QBNqwQQ)

## Log files/console output
[Profittrailer.log](https://pastebin.com/MtJDY3F5)

**Comment by dyvosvit** [comment]
![image](https://user-images.githubusercontent.com/22565655/40877241-e1a291f0-666c-11e8-9d04-8f8b40963a65.png)
different amounts of buy/sell

**Comment by taniman** [comment]
That's because he was not using BNB when thisbuy happened. So he could not sell the whole amount purchased because of fees Binance took.

But in any case I have fixed this problem for the next release
