### ISSUE TITLE
Average price missing again

### ISSUE THREAD

**Issue by vennechris** [taniman/profit-trailer#1911]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.10

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Average price was fixed since 2.0.7 version.  Updated to 2.0.10 yesterday and missing average price on one pair in each of my bots.
## Current Behavior

Monitoring for further lost pricing, will updated here.
## Troubleshooting

Attempted restart, no change.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Please provide a logfile and profittrailerdata.json. 

The price would not just disappear jsut with the update as there was no significant change for buy price calculation

**Comment by taniman** [comment]
fixed in 2.0.11 for 99% of cases
