### ISSUE TITLE
wrong profit calculation

### ISSUE THREAD

**Issue by gasperzupancic** [taniman/profit-trailer#1916]
## ProfitTrailer info
Version: 2.0.10

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x] Other linux distro (please specify) / Raspbian
- [ ] Mac OS

## Expected Behavior
it should at least calculate right percentage

## Current Behavior
After a few weeks i spun up my binance bot and upgrade it to 2.0.10. I was pleasantly surprised that it done some trading at night but something was odd. That was ~20% gain in TRX trade. After i checked it out i found that bot wasnt getting data from exchange right or it was doing something on its own. The trade that is wrong has said that my bot bought TRX at 0.00000662 and sold TRX at 0.00000794. When it actualy it was bought at 0.00000795 and sold at 0.00000794.

## Troubleshooting
dont know of anything that i can do

## Steps to Reproduce

1. it happened first time

## Configuration
i dont think its necessary to give you my config, but if needed i can do.

## Log files/console output

![image](https://user-images.githubusercontent.com/2493125/40937444-f199af52-683e-11e8-9248-ccacb5308203.png)
![image](https://user-images.githubusercontent.com/2493125/40937476-128b6e80-683f-11e8-8887-74616d850411.png)
[ProfitTrailer_1.log](https://github.com/taniman/profit-trailer/files/2069736/ProfitTrailer_1.log)

**Comment by SgtBatten** [comment]
Whilst this should not be happening I think you.will find if you used BNB for fees then it will stop for now.

**Comment by gasperzupancic** [comment]
this is from my PAIRS.properties

# BNB fees are not yet supported in Binance, so dont buy BNB until you disable the setting
BNB_trading_enabled = false

**Comment by SgtBatten** [comment]
Well that statement is inaccurate or incomplete. You can have your fees by using BNB so I don't know why anyone wouldn't be using it unless you were desperate to trade BNB as a pair.

**Comment by gasperzupancic** [comment]
this is commented in my pairs.properties (using one from cryptocoyns or smth). That aside, something was clearly wrong with profit calculation also with registering when the bot bought the coin.

**Comment by SgtBatten** [comment]
I'm not discounting the fact it should work how our are using it now. Im Just giving you an option that I am fairly sure will stop it happening in the mean time

**Comment by taniman** [comment]
Fixed in 2.0.11
