### ISSUE TITLE
ERROR ConfigApi - Config could not be loaded from the rest api. Received message: 404

### ISSUE THREAD

**Issue by CryptoCapo** [taniman/profit-trailer#1917]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.10

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [X] Ubuntu 17.10
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
I believe this issue is also causing my PTMAGIC to have issues.

## Current Behavior
Error does not correct even after restarting profit trailer

## Troubleshooting
checked the config files and monitor the logs after a restart

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Sorry, this is the other way around. It's a bug in PTMagic that is causing that error to be displayed as it's trying to load a non existing config. 
2.0.11 now has a way to properly handle this. But magic should make sure on their end too to load existing configs
