### ISSUE TITLE
New buy - Average price doesn't match on binance

### ISSUE THREAD

**Issue by neilspenz** [taniman/profit-trailer#1918]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.10

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When there's a new buy, the average price in profit trailer needs to match the average price in order details in the binance account.

## Current Behavior

Happened at least 3 times as i've seen.
Profit trailer makes a new buy, i see the average price in profit trailer and then i'm going to binance to confirm that the order has the same average price. but it doesn't. the average price in profit trailer is higher than the one stated in binance.

## Images
![ptb](https://user-images.githubusercontent.com/4414889/40973881-7cafb5ac-68ce-11e8-81d9-e728c7992fc3.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
update to  2.0.11 and if this happens again you will need to create a new issue and make sure to add your logfile
