### ISSUE TITLE
Bot missed profit price

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1920]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.10

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x] Other linux distro (please specify) CentOS
- [ ] Mac OS

## Expected Behavior
Must sell

## Current Behavior
Didnt sell

## Steps to Reproduce
Quick price increase and decrease

## Log files/console output
1m graph from binance
<img width="651" alt="2018-06-05 14 19 15" src="https://user-images.githubusercontent.com/5228422/40975499-7cda699e-68cb-11e8-893c-dd3c3696cd62.png">
<img width="1598" alt="2018-06-05 14 19 25" src="https://user-images.githubusercontent.com/5228422/40975500-7cf9486e-68cb-11e8-8f86-df453124ed80.png">

**Comment by taniman** [comment]
Sorry. Missing an opportunity can have many reasons. If according to the bot it was not moment to sell. Then it was not. 

That spike is not depicting the actual bid price. it might have been 1 small sale at that high price.

So without further real proof of the bot actually doing something wrong this is not a bug

**Comment by jokaorgua** [comment]
as you can see sell strategy is only gain. and if you'll compare prices you will see that the spike was more than 5% and only 0.9 is needed to make a profit. so bot missed the price. I think this is a bug.

**Comment by SgtBatten** [comment]
No it isn't. For the bot to attempt a sell a sustained buy order would have had to exist at a high school ice and then a sustained buy order low enough to meet your trailing value also. I guarentee it did not.  It would have been a one time buy irewr, possibly even by accident.
