### ISSUE TITLE
Mobile menu (and reduced browser window) icon not working in 2.0.10

### ISSUE THREAD

**Issue by blindaim** [taniman/profit-trailer#1922]
## ProfitTrailer info
Version: 2.0.10

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [ x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x ] Ubuntu (16.04.3)  
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When the browser is reduced in size (Chrome) to where the top menu is not present or on a mobile Chrome browser, there are three horizontal bars (menu icon) to the right of the PT logo. When you click this, a menu should appear allowing you to click on the DCA log, sales log, config settings. Also if you type "http://(ip_address):8081/dca-log" in the address bar, it should go to the dca-log. 

## Current Behavior

When I click on the menu icon in either browser configuration (desktop reduced size or mobile chrome browser), the background behind the icon changes with the click/tap, indicating a response, but no menu appears. If I type "http://(ip_address):8081/dca-log" in the address bar, it loads "http://(ip_address):8081/monitoring" instead.
 
## Troubleshooting

* Logged out and back in (before realizing it happens both on my laptop with the browser window reduced as well)
* stop and restart the server on the server
* manually type the dca-log url in (as noted above)
* compare to the instance I have with a friend that is still on 1.2.6.25 in the same browsers, verifying the behavior works correctly there.

## Steps to Reproduce

1. Open Chrome
2. Reduce window to a narrow size that causes the 3 horizontal bars to be present (unless on mobile)
3. Click on the 3 horizontal bars 
4. Conversely, type in the url noted above. 

## Configuration

application.properties (keys redacted) : https://pastebin.com/rNALCJLc

I don't imagine the other log files would impact browser behavior so will leave those out for now.

## Log files/console output

 
Note: renamed old log file to .old, stopped profit trailer, started, then performed replication steps above in Chrome then shutdown again. Here is the output:
2018-06-05 21:44:53 INFO Application - PT Version: 2.0.10
2018-06-05 21:44:53 INFO Application - Java Version: 1.8.0_151
2018-06-05 21:45:05 INFO ProfitTrailerService - Cache Heartbeat
2018-06-05 21:45:05 INFO ProfitTrailerService - PAIRS Heartbeat
2018-06-05 21:45:05 INFO ProfitTrailerService - DCA Heartbeat

**Comment by SgtBatten** [comment]
You most likely just need to clear browser cache.

This has been the fix since v2 was released so I am imagining it's no different this time.
