### ISSUE TITLE
Lost avg price

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1925]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.11

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version) 16.04
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Good work

## Current Behavior
Lost avg price

## Log files/console output

 
<img width="1586" alt="2018-06-06 17 48 19" src="https://user-images.githubusercontent.com/5228422/41049705-d30418f6-69b1-11e8-974e-6106557205ba.png">

**Comment by jokaorgua** [comment]
After update Bot lost couple days of prices for couple of coins. This issue is about price lost during regular work.

**Comment by CywucT** [comment]
the same thing happened to me
http://prntscr.com/jrq6pj
http://prntscr.com/jrq76z

**Comment by Heartinhand** [comment]
BNBBTC lost price, How the heck do enter average DCA'ed price now??

**Comment by alexdolli** [comment]
Same problem here on 2.0.11. Lost the price for my BNB token on Binance.

**Comment by SgtBatten** [comment]
If you use BNB for fees expect the bot to lose this price often. you can ignore the message or hide that coin. We have always sad it will forget BNB and it's not worth entering its price in hotconfig.

For everyone else, try updating to 2.0.12

**Comment by alexdolli** [comment]
Well, I don't only use it for trading. I also keep an amount to hodl.

**Comment by taniman** [comment]
Seems to be solved for TS in 2.0.12
