### ISSUE TITLE
Errors API shows INFO|DEBUG entries

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1927]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.12

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Show only errors on higher 

## Current Behavior
Shows entries from the level set in application.properties

## Possible Solution
Show only errors or rename the api 

## Steps to Reproduce

1. Enable INFO log level in application.properties
2. query the API https://bot_url/api/errors/log?token=TOKEN_HERE

**Comment by taniman** [comment]
I amnot sure why this issue was created, but this function is not something that has the possibility to be buggy.
It is a built in logic.

`Shows entries from the level set in application.properties`
Yes. That's what it is supposed to do
