### ISSUE TITLE
Health api has incorrect explanation in swagger-ui.html

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1928]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.12

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Token field should be added to explanation

## Current Behavior
No token field in swagger-ui.html for health api endpoint

## Possible Solution
Add correct explanation

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Thank you. But the health api is not for public use. I will see if I can hide it from the documentation. 
it's  for internal automated tests

But I will have a look and see if I can make it publicly available for API users
