### ISSUE TITLE
Wrong estimated profit calculation

### ISSUE THREAD

**Issue by vrmg1221** [taniman/profit-trailer#1929]
![unknown 1](https://user-images.githubusercontent.com/13337186/41119564-6450ffa4-6a93-11e8-8b41-e766f038025f.png)

Do the math:
Start balance: 0,102
Current balance: 0,169
Estimated profit: 1,32%
So logicly if my daily estimated gain is 1,32% it should be calculated from my current balance and not from my starting balance: 0,169 * 0,0132 = 0,0022308 BTC
If my daily profit is 1,32% I would have made 0,0022308 BTC. I made  0.00134924

That value comes from my starting balance: 0.102 * 0,0132 = 0.00134924 BTC
It is basicly cheating. It reports the daily profit waaay to high, the correct calculation will be: profit in BTC/total current value *100
0.00134924/0.169*100 = 0,798%
My actual daily profit is 0.798%

Try changing your start balance and watch the estimated profit change.

## ProfitTrailer info
Version: 2.12
Exchange: Binance
Market: BTC
OS: Linux

**Comment by GvY85** [comment]
yes, please make the calculation more 'honest'

**Comment by YoJeff** [comment]
If I am being 'honest', then the calculation above isn't accurate for a daily profit either.   It's a 15-second profit.

**Comment by djcrypto75** [comment]
Have discussed this, it is an estimate and not a number to go after. Both will show a results that is not 100%

**Comment by taniman** [comment]
we will see what we can come up with. But the current calculation is an estimate like we said above
