### ISSUE TITLE
Mass price lost after the update to 2.0.12

### ISSUE THREAD

**Issue by Mikeeetrue** [taniman/profit-trailer#1930]
## ProfitTrailer info
Version:2.0.12

 
Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

 
Market:
- [ X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ X] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
After the update lots of coins lost their price
## Current Behavior
Right after the update
## Troubleshooting
Hotconfig for manual fixing
## Possible Solution
Add the button "read last order price from the exchange"
## Steps to Reproduce
1. Update to 2.0.12
2. That's it
3.
4.

**Comment by taniman** [comment]
Please provide your log file as required by the template
