### ISSUE TITLE
Not any information loading in profit trailer afther update to 2.0.12

### ISSUE THREAD

**Issue by MORD0R** [taniman/profit-trailer#1932]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.0.12
 
Exchange:
- [ x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:

- [x ] Ubuntu 14.04

## Expected Behavior
See image.

## Current Behavior
![image](https://user-images.githubusercontent.com/6746199/41192760-0a0e4634-6c03-11e8-8e7f-f0f0cda51e5b.png)

## Troubleshooting
Restarted profit trailer.
Restarted Ubuntu.
Tested in firefox and chrome.

Cant find any information for this problem in https://wiki.profittrailer.com/doku.php?id=faq
## Steps to Reproduce

1.Update from 2.0.10 to 2.0.12
2.start profit trailer.
3.
4.

## Log files/console output

 
Cant find log option.

**Comment by SgtBatten** [comment]
There's several things that could cause this.

Timezones issues, not being on version 2.0.10 or newer, bad configs, browser cache needs clearing etc

Whatever it is you'll have a much better chance of working it out in discord chatting with someone from support. This isn't a bug really, we just need to work out what it is you need to do.
