### ISSUE TITLE
Stochastic RSI inaccurate

### ISSUE THREAD

**Issue by n0ts0subtle** [taniman/profit-trailer#1935]
The Stochastic RSI is inaccurately reflected in the bot from that of Binance. My bot has been buying too high.

**Comment by SgtBatten** [comment]
It is in the V2 full release notes on the wiki that stochrsi does not match any charts.

Please fill out the issue template correctly and open a new issue. You need to provide logs, screenshots etc. Simply reporting something with a 1 sentence description gives the Devs nothing to test or look for.
