### ISSUE TITLE
remove type from GET /api/sellOnlyMode

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer#1936]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.12

 
Exchange:
- [X] Bittrex
- [X] Binance
- [X] Poloniex

 
Market:
- [X] BTC
- [X] ETH
- [X] USDT
- [X] BNB
- [X] XMR

 
Operating System:
- [X] Windows (please specify version)
- [X] Ubuntu (please specify version)
- [X] Other linux distro (please specify)
- [X] Mac OS

## Troubleshooting

This is a problem with the API so not necessarily attached to ay particular platform.  GET /api/sellOnlyMode has a parameter that is required called "type".  It is unclear what it is there for.

Attempting to call this API without this parameter fails as the field is required.  I am able to put a dummy value in this field but it is concerning there may be a side effect.

## Possible Solution

It either needs clarification, as to what it is there for, or it should be removed.  Certainly concerning there may be some side effect setting this field to something.  If it genuinely has no effect, then is simply should not be there.

## Steps to Reproduce

1. curl -X GET --header 'Accept: application/json' 'http://192.168.1.175:8081/api/sellOnlyMode?token=<YOUR TOKEN HERE>&enabled=true'
this will fail

2. curl -X GET --header 'Accept: application/json' 'http://192.168.1.175:8081/api/sellOnlyMode?token=<YOUR TOKEN HERE>&enabled=true&type=asdf'
This will work, 200:OK
3.
4.

**Comment by SgtBatten** [comment]
Type= blank, rise or drop
Used for setting or resetting it due to price rises or falls

**Comment by BitRacer** [comment]
so this persists a note somewhere?

**Comment by SgtBatten** [comment]
Nope. I'll get to it when I can
