### ISSUE TITLE
[Wiki] Update Binance API Candle Period Support Guidance

### ISSUE THREAD

**Issue by goferit** [taniman/profit-trailer#1937]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Wiki guidance should match API guidance.

## Current Behavior

Wiki indicates less periods are available than the Binance API docs indicate.

## Steps to Reproduce

1. Visit https://wiki.profittrailer.com/doku.php?id=exchanges
2. Note Binance period guidance.
3. Visit https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md
4. Search 'kline'.
5. Note Binance period guidance.

## Log files/console output

 
![image](https://user-images.githubusercontent.com/8900109/41236018-0d883020-6d5e-11e8-887f-c659219f706b.png)

**Comment by goferit** [comment]
The underlying question is, then, will a period setting like "60" (1m), in **indicators.properties**, function correctly, with the bot's current implementation, for the Binance exchange?

If not, it should -- unless I'm missing something?

If it does, the Wiki should say it does, and the sample Periods should be expanded accordingly.

**Comment by taniman** [comment]
The wiki is correctly reflecting the options the bot can handle.

1m candle will not work correctly as the bot does some caching to prevent spamming the exchange.

Other longer periods will be added in V2.1 as they currently are not implemented
