### ISSUE TITLE
Stoploss Trailing

### ISSUE THREAD

**Issue by Mahmud1985** [taniman/profit-trailer#1939]
Hi Dear Developer team. @taniman 

I have an issue about stoploss that at the moment PT stoploss just stay static level which we set it when start trading and what ever the price go up near to the target sell price it don't change it self automaticly.

for example: we bought a coin at 100 satoshi and set target sell persentage 10%( 110 satoshi ),
stoploss 5%(95 satoshi) then PT start trailing the price go up to 108 then down ofcourse PT don't sell it because target didn't reached here we didn't account the trailing percentage. however our stoploss didn't changed still at 95 satoshi and the price going down and down to 95 the stoploss reached PT sell the coin we loss 5% on this trade. 

I am thinking that if the PT trailing the stoploss when the price going up(just when price going up!) for example there is a stoploss trailing option at pair setting and we set it 1% then when price up to 108 at last senario the price already increased 8% from bought price and because of we set the stoploss trailing our stoploss price increased to 95+8=103 satoshi now and when price going down our new stoploss price don't change because it just work upside not downside then price down to 103 satoshi the PT sell the coin and we got 3% gain even PT execute stoploss process.

if you add this option in the next update(s) that will be so benificient for all of us. thanks.

**Comment by taniman** [comment]
Here is the place to place bugs and not feature requests. As stated by the template
Check the profittrailer-enhancements repo to add your request if it does not exist.
