### ISSUE TITLE
[Feature Request] - Add date/time purchased to the Excel export on the Sales page.

### ISSUE THREAD

**Issue by datapicard** [taniman/profit-trailer#1940]
It would make it much easier to track a strat's performance if we had this historic data.  I know you have this info in the Pairs log and Pairs log export, but as soon as a coin is sold if you didn't record the data in time it's gone.

Would be great if the coin date/time purchased were included in the Excel export from the Sales page  :)

**Comment by taniman** [comment]
Only bug reports are allowed here
