### ISSUE TITLE
Buy On First Signal - Potential Bug

### ISSUE THREAD

**Issue by datapicard** [taniman/profit-trailer#1941]
## ProfitTrailer info
Version: 2.0.10

Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [x ] Mac OS

I'm not sure if this really a bug - but it does behave in a way contrary to what I was expecting / hoping.

This issue has to with using the pair_min/max_change_percentage parameters in conjunction with a buy strat with buy_on_first_signal.  

If a coin is out of the min/max change percentage range, as it comes into range, it's giving what I would call false positives to the buy on the first signal parameter.

Let's say you are using a positive EMASPREAD value.  If you look at the chart, the EMASPREAD value entered your range 5 ticks ago - so this is technically the time when buy on first signal becomes true (5 ticks ago).  If the coin is outside your min/max percentage change when this buy on first signal becomes true, the system doesn't know.  So what happens is: as soon as the coin drops into the min.max range, if the indicator is true, it gives a positive buy on first signal value - even if the indicator became true 5 ticks ago.  

The way I expect it to work would be:
- Coin drops into min/max range.
- If the indicator is true, it doesn't buy immediately.  
- Instead it waits for the indicator to drop out of range, and then only buys when the indicator flips to true again.  (so it actually catches the first signal)

**Comment by cvthub** [comment]
Thanks for reporting. We could reproduce the behavior.
It should be fixed for next release version.
