### ISSUE TITLE
Incorrect Bought Price After Partial Sell v2

### ISSUE THREAD

**Issue by SkyHighStacks** [taniman/profit-trailer#1945]
## ProfitTrailer info
Version: 2.0.11

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu 17
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Bought Price should stay the same after a partial sell.
It's like issue #1898

## Current Behavior
Bought Price drops after a partial sell.

![incorrect bought price after partial sell v02](https://user-images.githubusercontent.com/39431801/41431733-32cee226-7014-11e8-9c7c-075bca22083a.jpg)

## Log files/console output
I will send a log file via discord support.

**Comment by taniman** [comment]
2.0.12 would have made the price 0.00 because it could not calculate it.

I have now fixed this though in version 2.0.13 to calculate price correctly
