### ISSUE TITLE
Wrong Bought Price and not recording manual trades

### ISSUE THREAD

**Issue by n0ts0subtle** [taniman/profit-trailer#1948]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [x ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (10)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
With the Stochastic RSI Indicator, the lowest it will let me set it for is .001 - 0.00 and the bot is expected to buy on first signal. If I set it between .0001 and 0.0, the bot doesn't trail. 

## Current Behavior
Buying at higher Stoch RSI therefore, price. Most recently, it bought at around .38 on the stochastic which is way off the set parameters. When I sell manually, the bot doesn't pick it up. 

## Troubleshooting
Sell and buy manually at true indicator setting.

## Possible Solution
Increase the decimal points to ten thousandths (.0001) or less on A_Buy_Value than to tighten buying possibilities.  

## Steps to Reproduce
1. Set Buy Value to .001 and the Limit to 0.0
2. Buy and sell manually with the bot running to see if it will reflect in the GUI. 
3.
4.

## Configuration
Here, it shows exactly when the bot made it's purchase at 0315. Trailing buy is false. 

![image](https://user-images.githubusercontent.com/36770743/41500245-367f1028-715c-11e8-9c5c-e09ebff62b9c.png)

===================================================================

DEFAULT_sell_only_mode_enabled = false

market = USDT
start_balance = xxxxx
enabled_pairs = BNB, ETH, BTC, BCC
hidden_pairs = 0
BNB_trading_enabled = true
keep_balance = 0.0
keep_balance_percentage = 0
pair_min_listed_days = 0
max_trading_pairs = 0
orderbook_profit_calculation = true

consecutive_buy_trigger = 0
consecutive_sell_trigger = 0

price_trigger_market = BTC
price_rise_trigger = 0
price_rise_recover_trigger = 0
price_drop_trigger = 0
price_drop_recover_trigger = 0

DEFAULT_trading_enabled = true
DEFAULT_DCA_enabled = true

DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 5
DEFAULT_min_buy_volume = 0
DEFAULT_min_buy_price = 0
DEFAULT_max_buy_spread = 1
DEFAULT_min_order_book_volume_percentage = 0

DEFAULT_A_buy_strategy = STOCHRSI
DEFAULT_A_buy_value = 0.001
DEFAULT_A_buy_value_limit = 0.000
DEFAULT_A_buy_on_first_signal = true

DEFAULT_trailing_buy = 0

DEFAULT_A_sell_strategy = STOCHRSI
DEFAULT_A_sell_value = .92

DEFAULT_B_sell_strategy = GAIN
DEFAULT_B_sell_value = .69

DEFAULT_trailing_profit = .24
DEFAULT_max_profit = 0

DEFAULT_stop_loss_trigger = 0
DEFAULT_stop_loss_timeout = 0

DEFAULT_rebuy_timeout = 0

DEFAULT_buy_min_change_percentage = 0
DEFAULT_buy_max_change_percentage = 0

# Rename me?
DEFAULT_pending_order_wait_time = 2880
DEFAULT_combined_cancel_pending_trigger = 0.1

DEFAULT_take_profit_wait_time = 0
DEFAULT_take_profit_percentage = 0

DEFAULT_panic_sell_enabled = false

===================================================================

DCA_keep_balance = 0
DCA_keep_balance_percentage = 0
DCA_orderbook_profit_calculation = true
DEFAULT_DCA_max_cost = 0
DEFAULT_DCA_max_buy_times = 6
#----------------------------#
DEFAULT_DCA_A_buy_strategy = STOCHRSI
DEFAULT_DCA_A_buy_value = .2
DEFAULT_DCA_A_buy_value_limit = 0.000
#---------------------------------
DEFAULT_DCA_trailing_buy = 0
DEFAULT_DCA_buy_trigger = -.5

DEFAULT_DCA_buy_percentage_1 = 100
DEFAULT_DCA_buy_percentage_2 = 100
DEFAULT_DCA_buy_percentage_3 = 50
DEFAULT_DCA_buy_percentage_4 = 50
DEFAULT_DCA_buy_percentage_5 = 25
DEFAULT_DCA_buy_percentage_6 = 25
DEFAULT_DCA_buy_percentage_7 = 10

#---------------------------------
DEFAULT_DCA_A_sell_strategy = STOCHRSI
DEFAULT_DCA_A_sell_value = .92
DEFAULT_DCA_B_sell_strategy = GAIN
DEFAULT_DCA_B_sell_value = .69
DEFAULT_DCA_trailing_profit = .252
DEFAULT_DCA_max_profit = 0
#---------------------------------
DEFAULT_DCA_min_buy_volume = 0
DEFAULT_DCA_min_orderbook_volume_percentage = 100
DEFAULT_DCA_ignore_sell_only_mode = true
DEFAULT_DCA_max_buy_spread = 2
DEFAULT_DCA_rebuy_timeout = 0
DEFAULT_DCA_stop_loss_trigger = 0
DEFAULT_DCA_stop_loss_timeout = 0
DEFAULT_DCA_pending_order_wait_time = 0
DEFAULT_DCA_buy_min_change_percentage = 0
DEFAULT_DCA_buy_max_change_percentage = 0
DEFAULT_DCA_take_profit_wait_time = 0
DEFAULT_DCA_take_profit_percentage = 0

===================================================================

#5m = 300 // 15m = 900 // 30m = 1800 // 1h = 3600 // 2h = 7200 // 4h = 14400 // 6h = 21600 // 12h = 43200// 1d = 86400#

BB_std = 2
BB_candle_period = 900
BB_length = 20
SMA_cross_candles = 2
SMA_candle_period = 900
SMA_fast_length = 12
SMA_slow_length = 24
EMA_cross_candles = 3
EMA_candle_period = 900
EMA_fast_length = 3
EMA_slow_length = 24
RSI_candle_period = 900
RSI_length = 14
STOCH_length = 14
MACD_candle_period = 900
MACD_fast_length = 12
MACD_slow_length = 26
MACD_signal = 9
OBV_candle_period = 900
OBV_length = 50
OBV_signal = 1
#Always uses 5 minute candles
SOM_trigger_length = 288
## Log files/console output
===================================================================

Nothing appears in the CMD window when I sell manually however it does tell me to enter Bought_Price when I purchase manually.  I have to restart bot everytime I manually purchase. The wiki shows us how to set bought_price, but there is nothing for sold_price.

**Comment by taniman** [comment]
I think there are a few confusion here.
Also in the future create 1 issue for 1 problem do not combine them

Let me start with the most easy one.

If you sell manually on the exchange The bot will not safe this in sales log.
The bot will only save in sales log things it sold itself. This behaviour will not change.
If you want to see sales in the sales log. You should let the bot sell them or use panic sell.

Second
Current PT StochRSI does not match Binance or TV STOCHRSI. So you cannot compare the value of Binance with what the bot showed and say that the bot bought incorrectly. 
Binance shows a value between 0 - 100 that is being smoothed out using the K and D value.

PT shows a value between 0 - 1 and does not use this K and D values. 
So they are totally different. 

In version 2.1 we will introduce a STOCHRSI that matches TradingView and Binance
Until then All I can tell you is that the buy most likely happened at the correct setting and you are comparing apples with pears.

**Note:** You can use up to 8 decimal places for setting your buyvalue. It's the frontend that is not displaying it. But does not mean that the bot is not using all those decimal places

**Comment by n0ts0subtle** [comment]
Thank you for the clarification. Excited for the 2.1 release.
