### ISSUE TITLE
Missing bought price - average price and total cost is 0.00

### ISSUE THREAD

**Issue by radeksalomon** [taniman/profit-trailer#1949]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.13 (appeared in 2.0.12)

 
Exchange:
- [x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [x] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x] Other linux distro (please specify) Raspbian
- [ ] Mac OS

## Current Behavior

Average price and total cost is 0.00 for 12 from 13 pairs (only 1 pair is ok)

## Troubleshooting

update to 2.0.13

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
I mentioned this problem in 2.0.9 I think.
You will have to set your bought prices for bittrex one last time.

So use hotconfig to fix the prices and they should remain correct going forwards.

Beware though that bitttex loses prices after 30 days as they do not return everything we need to calculate prices correctly after 30 days.

There is nothing that we can do to fix this. You will need to set the prices with hotconfig manually so they are stored again.

If you have a backup of your pt folder before you upgraded to 2.0.12 we can look into your ProfitTrailerData.json maybe we can find something to help setting the prices again. Contact support on discord
