### ISSUE TITLE
Suggestion: Deposited altcoins to register current price

### ISSUE THREAD

**Issue by joeyoon80** [taniman/profit-trailer#195]
I have a suggestion. When I deposit any altcoin from other places (mining pools, wallet), when it enters the exchange, it should register in Pairs log as price that it recorded when coins first came in. That way it will follow the sell strategy accordingly.

Currently when altcoins are deposited from external sources into the exchange, the purchased price shows as 0.000000000.

**Comment by taniman** [comment]
yes, and for these coins we have the  BTX-ETH_override_bought_price =  and override_bought_date options. Check the wiki pairs.porperties
