### ISSUE TITLE
Asking for bought price after bot purchase

### ISSUE THREAD

**Issue by n0ts0subtle** [taniman/profit-trailer#1950]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [x ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (10)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Price and time should be recorded in GUI under DCA. I have the newest bug patch version 12. 

## Current Behavior
Not recording purchase price

## Troubleshooting
enter price in hot config

![image](https://user-images.githubusercontent.com/36770743/41501523-0d93d5c8-7174-11e8-81db-533ce70e6726.png)

![image](https://user-images.githubusercontent.com/36770743/41501525-1624245e-7174-11e8-9a69-c1b6a193cbee.png)

**Comment by taniman** [comment]
I am sorry but what you are doing is not really a good idea. And it will always cause problems for BNB.

We always recommend disabling trading for BNB if you are paying fee with BNB.

The bot always loses BNB price when you are paying fees with BNB. Cause the amount you own changes and so the bot cannoy figure out the correct price.

So I advice to to disable trading for BNB or disable paying fees with BNB or just continue to set the price manually if you want to trade BNB.

There is no other way around this until Binance comes with a way to better check for this

**Comment by n0ts0subtle** [comment]
Okay, I trade BNB USDT exclusively and its been only recently that it asks for BNB_Bought_Price...?

**Comment by SgtBatten** [comment]
If it was in the bnb market it would work fine as it's the base market currency being used for fees. But because it's in the usdt market it doesn't work nicely.
