### ISSUE TITLE
Need to restart bot after each manual sale for pair to show up in Possible BUys

### ISSUE THREAD

**Issue by MrS1n1st3r** [taniman/profit-trailer#1952]
Whenever I buy then sell a pair manually, it will not show up again under Possible Buys unless I restart the bot.

Version: 2.0.13
Exchange: Binance
Market: BTC
OS: Linux

**Comment by SgtBatten** [comment]
It will if you wait longer. The bot gets no notification of a manual sale. So it takes time for it to detect that change.

**Comment by MrS1n1st3r** [comment]
Even after waiting an hour, it still shows no Possible Buys, unless I restart the bot.  The pair will disappear from Pairs, as it should, bit it still does not sbow it under Possible Buys.

**Comment by taniman** [comment]
I did a manual sell on the exchange. The coin appeared immediatelly in PBL. This was using 2.0.14

One of my coins did not appear. That's because it's BTC volume was lower than my min_buy_volume
When I changed min_buy_volume the coin appeared.
