### ISSUE TITLE
STOCHRSI is "false" when: BSV: 1.0 / BST: 1.0 / BSL: 0.xx

### ISSUE THREAD

**Issue by Ivanverdonck** [taniman/profit-trailer#1953]
## ProfitTrailer info
Version:2.0.13

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [ ] BTC
- [ ] ETH
- [x] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
STOCHRSI to be "true" when:
BSV: 1.0
BST: 1.0
BSL: 0.85
STOCHRSI should be "true" when: BST >= BSV >= BSL

## Current Behavior
STOCHRSI is "false" when:
BSV: 1.0
BST: 1.0
BSL: 0.85
STOCHRSI should be "true" when: BST > BSV >= BSL

## Troubleshooting
-

## Possible Solution
STOCHRSI should be "true" when: BST >= BSV >= BSL

## Steps to Reproduce
-
## Configuration
DEFAULT_B_buy_strategy = STOCHRSI
DEFAULT_B_buy_value = 1
DEFAULT_B_buy_value_limit = 0.85

## Log files/console output
-

**Comment by cvthub** [comment]
For stochrsi the logic is: 
buy_value > strategy_value > buy_value_limit

Wiki will be updated according to the above.
