### ISSUE TITLE
DCA incorrect number reading

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer#1954]
using test mode
enabled_dca = true
initial_cost = 0.0012
dca_trigger = -0.1
DCA_buy_strategy = Anderson
DCA_buy_value = -1.9
DCA_percent_1 = 100
DCA_percent_2 = 50
![screenshot_10](https://user-images.githubusercontent.com/38658320/41690757-55f4560e-74f7-11e8-92c2-32017c157ccf.png)
![screenshot_8](https://user-images.githubusercontent.com/38658320/41690758-561efef4-74f7-11e8-9940-8bdfaaf33c14.png)
![screenshot_9](https://user-images.githubusercontent.com/38658320/41690759-564ac96c-74f7-11e8-8d7a-826fa2e12246.png)

when my bot buys the pair, it goes immediatly to dca as DCA +1 without actually buying the coin (0.0012)
when it needs to dca , it looks for DCA +2 , which is 50% , which would be, (0.0006), which is below dust level, > so the bot can't dca now forever
--------------------------------------
i've contacted the live support and they located these in my logs
![unknown](https://user-images.githubusercontent.com/38658320/41690779-6cfcf702-74f7-11e8-877b-1b8859b9e8bf.png)
########################
this is my log file , you will find sky & theta, the other coins are from other test bots > so different logs
https://github.com/pheonix727/texts/blob/master/README.md
######################
my pairs
https://github.com/pheonix727/texts/blob/master/pairs
my DCA
https://github.com/pheonix727/texts/blob/master/dca

**Comment by cvthub** [comment]
Thanks for reporting! 
Error fixed in next release version
