### ISSUE TITLE
Price Rise Trigger does not turn off Sell Only Mode

### ISSUE THREAD

**Issue by chrismpalmer** [taniman/profit-trailer#1955]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.12

 
Exchange:
- [ ] Bittrex
- [ X] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [X ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [X ] Mac OS

## Expected Behavior

Given the settings below:
price_trigger_market = ETH
price_rise_trigger = 4
price_rise_trigger_recover = 2

The price rise trigger recover should turn off sell only mode. It does not.

## Current Behavior

Sell only mode is not turned off.

## Troubleshooting

I restart the bot and it turns off sell only mode.

## Steps to Reproduce

1. Configure the bot with a price rise trigger and ETH
2. Observe ETH passes the threshold
3. Observe SOM is on
4. Observe ETH drops back below 2% rise
5. Observe SOM is still on

## Configuration

Pairs
https://pastebin.com/HySsXdCU
DCA
https://pastebin.com/BVewBM4Z
INDICATORS
https://pastebin.com/hiy7nzxh

**Comment by SgtBatten** [comment]
The parameter you have is incorrect.

If you use price_rise_recover_trigger ( instead of trigger_recover) it will work
