### ISSUE TITLE
Can't start ProfitTrailer  - ERROR ProfitTrailerService

### ISSUE THREAD

**Issue by DrrMrr** [taniman/profit-trailer#1957]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.13

Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

Market:
- [X ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ X] Other linux distro (please specify)
Raspian Os
- [ ] Mac OS

## Current Behavior
I get an error when I try to start ProfitTrailer. I also tried to extract  clean zip from your site and replaced application.properties file. But I still get the same error.

Please check log file

## Log files/console output
[error.log](https://github.com/taniman/profit-trailer/files/2136125/error.log)

**Comment by erknie** [comment]
Binance is down for mantenance
