### ISSUE TITLE
Binance. New api's required. Steps to follow?

### ISSUE THREAD

**Issue by Heartinhand** [taniman/profit-trailer#1961]
Just create new ones or is there a procedure?

Edit:
Just saw the steps on dischord:

In order to continue using your Binance ProfitTrailer Bot, you will need to make new Default and Trading API keys on your Binance account, replace them in the proper locations within the application.properties file of your bot(s) and also register the new Default API with @PT Assistant if you need help with that click here https://wiki.profittrailer.com/doku.php?id=pt_assistant

**Comment by twig123** [comment]
Nothing special about it, just new API keys have to be generated on Binance itself. General steps are listed in step 1 of the quick instructions:
http://wiki.profittrailer.com/doku.php?id=instructions

Once you have new API keys created, you'll need to register the new default_api_key with the PT Assistant bot:
http://wiki.profittrailer.com/doku.php?id=pt_assistant

Also, please come see us on discord for support questions like this:
https://discord.gg/K9a37Vh
