### ISSUE TITLE
Max Pairs count when individual markets have DCA Trading disabled

### ISSUE THREAD

**Issue by goferit** [taniman/profit-trailer#1962]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

Under the following conditions, PT's Max Pairs setting must include all pairs, including DCA'd pairs, and so Max Pairs must be set artificially higher, in order for PT to make new pair buys.

Start condition: 7 pairs in DCA
Objective: Keep the deep DCAs in DCA; pull the other ones into Pairs; do some new Pair buys, by opening up two trading slots

Pairs Settings:

DEFAULT_DCA_enabled = true
ABC_DCA_enabled = false
DEF_DCA_enabled = false
GHI_DCA_enabled = false
JKL_DCA_enabled = false

Result: 3 pairs remain in DCA, 4 come into Pairs

Expected followup setting, to trade two new pairs:
max_trading_pairs = 6 (4 DCA pairs, now Pairs, plus 2 new slots)

Required setting:
max_trading_pairs = 9 (4 DCA pairs, now Pairs, plus 3 DCA pairs, still in DCA, plus 2 new slots)

Improved UX: max_trading_pairs setting renders the expected result

Verification method: incremental increase of max_trading_pairs setting, from 6 to 9, and observing "Max Pairs" flag in Possible Buys tab, until 9 was reached

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by SgtBatten** [comment]
It always includes all pairs.

From the wiki:

Valid values: Integer greater than or equal to 0.

Set the maximum number of pairs that the bot is allowed to own at one time. Pending log coins do not count however coins in WATCHMODE do.

Calculated by adding up all the coins in Pairs Log, and DCA Log. Pending log does not count. Once the max is reached, the bot will not buy any new pairs until some are sold. DCA is still allowed to buy.

0 will allow unlimited coins (not recommended)

**Comment by goferit** [comment]
Thanks my mistake. Haven't been out of SOM for awhile ;P

**Comment by SgtBatten** [comment]
No worries mate.
