### ISSUE TITLE
Coin in DCA but does not rebuy after SOM mode manually set

### ISSUE THREAD

**Issue by joeyoon80** [taniman/profit-trailer#1965]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

I set manual SOM on in PAIRS. 1 of my current coins drops into DCA because DEFAULT_DCA_enabled = -5. It stays in DCA, doesnt rebuy when my buy settings become true.

## Current Behavior

It has stayed in my DCA for the last 24 days with no rebuys.

## Troubleshooting

I checked all my settings and they seem to be working properly. Went through my settings in PT support discord channel.

## Steps to Reproduce

1.
2.
3.
4.

## Configuration

https://pastebin.com/zmwekXdJ
https://pastebin.com/qwMfkaTz
https://pastebin.com/dqzzgNXL

## Log files/console output

 

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2177034/ProfitTrailer.log)

**Comment by joeyoon80** [comment]
![capture](https://user-images.githubusercontent.com/32901879/42462432-d67073e8-83d5-11e8-91fa-e8d3d42daa2a.JPG)

**Comment by taniman** [comment]
As support will tell you. There was no buying opportunity. So that is the reason this coin did not buy

**Comment by joeyoon80** [comment]
I checked the charts against my buy settings, there were rebuy numerous opportunities. This coin was sitting in my DCA for 24 days.

**Comment by taniman** [comment]
yes. and in those 24 days there were only 2 buy opportunies where macd was true. But there was no cross for EMA. So 
Did you not receive the screenshot from Botjuice? Check in discord. As this is not an issue

**Comment by joeyoon80** [comment]
didnt get any screenshots from botjuice, but thanks for the confirmation. guess this was a really odd case of no rebuys in 24 days.
