### ISSUE TITLE
Panic Sell is selling Pending Log Coins.

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer#1968]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

<img width="521" alt="captura de pantalla 2018-07-11 a la s 14 08 56" src="https://user-images.githubusercontent.com/35824627/42588364-025680a8-8514-11e8-8a81-9e4bf9bbaf79.png">

WIKI:

> Note:
Coins in WATCHMODE and in the Pending Log will not be sold.

> 

## ProfitTrailer info
Version: 2.

**Comment by jadiesel** [comment]
What is a 'defended pair' ?

**Comment by taniman** [comment]
Just as the wiki says. This is not true.  
I have done multiple panic sells today for that matter. My binance pending coins are still there. 

Please re open this issue if you can provide any evidence of this happening.
