### ISSUE TITLE
Nano bought Display different on PT than PT TRACKER

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer#1970]
<img width="1673" alt="captura de pantalla 2018-07-14 a la s 11 18 15" src="https://user-images.githubusercontent.com/35824627/42725360-af7973bc-8758-11e8-802a-9535c5eb2fa6.png">

<img width="1664" alt="captura de pantalla 2018-07-14 a la s 11 18 19" src="https://user-images.githubusercontent.com/35824627/42725363-b36b6340-8758-11e8-9785-1b35f4d9e6b8.png">

**Comment by taniman** [comment]
Please add more description to this issue according to our issues template or I will have to close this issue.

As currently I am not seeing any error

**Comment by juato4** [comment]
look at Bought Cost & Current Value.. 

PT TRACKER says Bought cost : 14
PT: 9

**Comment by taniman** [comment]
This is a PT Tracker bug. You should report a bug on their issues site. https://github.com/bTayFla/PtTracker/issues

I did a quick calculation for you.

your avg price = 0.00653561
you have 1390.88 NANOETH

0.00653561 * 1390.88 = 9.0902492368

This is the value PT is showing. And this is correct.

**Comment by juato4** [comment]
ok, Thanks

**Comment by LiamAird** [comment]
FYI: This will be fixed in the next version of PtTracker :)
