### ISSUE TITLE
[feature request] manual sells visiable

### ISSUE THREAD

**Issue by yannickweijenberg** [taniman/profit-trailer#1971]
Will it be able to make manual sell order visiable in PT / PT tracker?

**Comment by CryptoReis** [comment]
This would be extremely helpful! We need this to have a clearer picture of our profits.

**Comment by taniman** [comment]
This has been asked and answered many time. It is not possible. 
You should not do manual actions outside of the bot.

Also this here is not the place for feature request.  You should follow the issue template rules
