### ISSUE TITLE
DCAed Coin selling under PAIRS Config MAX Profit

### ISSUE THREAD

**Issue by perplex51** [taniman/profit-trailer#1973]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

My coins that DCA at least once sometimes sell under my PAIRS Config but only under MAX PROFIT.
so Pairs config max profit is set to 1.75% and DCA doesnt have max profit it has a sell value of 4.69 with a trailing of .19, its happened about 5 times now, the most recent DCAed 2 times and was at 2% then next time i looked at it it was sold as max profit at 2.85% in my sale log, but my DCA config doesnt have max profit it only has a sell value, so somehow they are using my PAIRS config and selling it at max profit.

have has a support staff look at certain files that he asked for and he confirmed it sold as max profit

## ProfitTrailer info
Version: 2.0.12 and 2.0.13

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When it DCAed at least once it should wait for the sell value at 4.69 before trailing

## Current Behavior

once the DCAed coins gets above 1.75% they are selling as max profit what is only in my PAIRS config
out of my last 6 coins that were DCAed at least once its happend to 5 of them only 1 worked correct, i dont know how long its been doing it for, i dont have alot of dca sales so thats why there is only 6 atm

## Troubleshooting

i tried going back a version i was on 2.0.13 and i went back to 2.0.12 but it still happened it worked correct once in 2.0.12, but recently sold as max profit even though it has DCAed 2 times and there is no max profit in my DCA file

## Possible Solution

im guessing its some type of code issue

## Steps to Reproduce

1. im not sure, if this is a issue to everyone, but i know not alot of people use max profit, but ive got max profit in pairs and just a sell value in dca config

## Configuration

PAIRS Config
market = BTC
start_balance = 0.78989882
enabled_pairs = ETH, ZRX, AE, BNT, BAT, BCC, BTS, BLZ, BCN, ADA, LINK, CND, DASH, ENG, EOS, ETC, LEND, BQX, GAS, GVT, GTO, ICX, IOST, IOTA, KMD, LSK, LTC, LRC, LUN, XMR, NANO, NEBL, XEM, NEO, NCASH, NULS, OMG, ONT, PIVX, PPT, POWR, NPXS, QTUM, QSP, XRP, SALT, SNT, XLM, STEEM, STORJ, STORM, STRAT, SUB, TRX, VEN, XVG, WABI, WAN, WAVES, WPR, ZIL
hidden_pairs = ALL
keep_balance = 0.0
keep_balance_percentage = 0
pair_min_listed_days = 14
max_trading_pairs = 30
orderbook_profit_calculation = true

#Triggers
price_trigger_market = BTC
price_rise_trigger = 5
price_rise_recover_trigger = 4.5
price_drop_trigger = 5
price_drop_recover_trigger = 4.5

#Options
DEFAULT_trading_enabled = true
DEFAULT_DCA_enabled = -0.25

DEFAULT_initial_cost = .002875
DEFAULT_initial_cost_percentage = 0
DEFAULT_min_buy_volume = 0
DEFAULT_min_buy_price = 0
DEFAULT_max_buy_spread = 3
DEFAULT_min_order_book_volume_percentage = 100

#Buy Strategies
#LOWBB
DEFAULT_A_buy_strategy = LOWBB
DEFAULT_A_buy_value = -2
DEFAULT_A_buy_value_limit = -35
#RSI
DEFAULT_B_buy_strategy = RSI
DEFAULT_B_buy_value = 28
DEFAULT_B_buy_value_limit = 0
#EMASPREAD -1 original
DEFAULT_C_buy_strategy = EMASPREAD
DEFAULT_C_buy_value = -1.25
DEFAULT_C_buy_value_limit = -4

DEFAULT_trailing_buy = 0

#SELL Strategies
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1.27
DEFAULT_trailing_profit = 0.05
DEFAULT_max_profit = 1.75

DEFAULT_B_sell_strategy = RSI
DEFAULT_B_sell_value = 40

#Hidden Pairs
BNB_trading_enabled = false

#Panic - Stop Loss - Sell Only Mode
DEFAULT_stop_loss_trigger = 0
DEFAULT_stop_loss_timeout = 0
DEFAULT_panic_sell_enabled = false
DEFAULT_sell_only_mode_enabled = false
#Panic Sell Certain Coin
#QSP_panic_sell_enabled = true

#Others
DEFAULT_rebuy_timeout = 4
DEFAULT_pending_order_wait_time = 0
DEFAULT_combined_cancel_pending_trigger = 0

DEFAULT_take_profit_wait_time = 0
DEFAULT_take_profit_percentage = 0

DEFAULT_buy_min_change_percentage = -7
DEFAULT_buy_max_change_percentage = 5

consecutive_buy_trigger = 0
consecutive_sell_trigger = 0

DCA Config
DCA_keep_balance = .02
DCA_keep_balance_percentage = 0
DCA_orderbook_profit_calculation = false

#DCA Times
DEFAULT_DCA_max_cost = 10
DEFAULT_DCA_max_buy_times = 2

#DCA Buy Strategies
#LOWBB
DEFAULT_DCA_A_buy_strategy = LOWBB
DEFAULT_DCA_A_buy_value = -2
DEFAULT_DCA_A_buy_value_limit = -35
#RSI
DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_value = 28
DEFAULT_DCA_B_buy_value_limit = 0
#EMASPREAD -1 and -4 orginal
DEFAULT_DCA_C_buy_strategy = EMASPREAD
DEFAULT_DCA_C_buy_value = -1.25
DEFAULT_DCA_C_buy_value_limit = -4

DEFAULT_DCA_trailing_buy = 0

#DCA SELL Strategies
DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 4.69

DEFAULT_DCA_B_sell_strategy = RSI
DEFAULT_DCA_B_sell_value = 40

DEFAULT_DCA_trailing_profit = 0.19
DEFAULT_DCA_max_profit = 0

#DCA Settings
DEFAULT_DCA_buy_trigger = 0
DEFAULT_DCA_buy_trigger_1 = -1
DEFAULT_DCA_buy_trigger_2 = -1.25
DEFAULT_DCA_buy_trigger_3 = -1.5
DEFAULT_DCA_buy_trigger_4 = -1.75
DEFAULT_DCA_buy_trigger_5 = -2
DEFAULT_DCA_buy_trigger_6 = -2.25
DEFAULT_DCA_buy_trigger_7 = -2.5
DEFAULT_DCA_buy_trigger_8 = -2.75
DEFAULT_DCA_buy_trigger_9 = -3
DEFAULT_DCA_buy_trigger_10 = -3.25
DEFAULT_DCA_buy_trigger_11 = -3.5
DEFAULT_DCA_buy_trigger_12 = -3.75
DEFAULT_DCA_buy_trigger_13 = -4
DEFAULT_DCA_buy_trigger_14 = -4.25
DEFAULT_DCA_buy_trigger_15 = -4.5
DEFAULT_DCA_buy_trigger_16 = -4.75
DEFAULT_DCA_buy_trigger_17 = -5
DEFAULT_DCA_buy_trigger_18 = -5.25
DEFAULT_DCA_buy_trigger_19 = -5.5
DEFAULT_DCA_buy_trigger_20 = -5.75
DEFAULT_DCA_buy_trigger_21 = -6
DEFAULT_DCA_buy_trigger_22 = -6.25
DEFAULT_DCA_buy_trigger_23 = -6.5
DEFAULT_DCA_buy_trigger_24 = -6.75
DEFAULT_DCA_buy_trigger_25 = -7
DEFAULT_DCA_buy_trigger_26 = -7.25
DEFAULT_DCA_buy_trigger_27 = -7.5
DEFAULT_DCA_buy_trigger_28 = -7.75
DEFAULT_DCA_buy_trigger_29 = -8
DEFAULT_DCA_buy_trigger_30 = -8.25
DEFAULT_DCA_buy_trigger_31 = -8.5
DEFAULT_DCA_buy_trigger_32 = -8.75
DEFAULT_DCA_buy_trigger_33 = -9
DEFAULT_DCA_buy_trigger_34 = -9.25
DEFAULT_DCA_buy_trigger_35 = -9.5
DEFAULT_DCA_buy_trigger_36 = -9.75
DEFAULT_DCA_buy_trigger_37 = -10
DEFAULT_DCA_buy_trigger_38 = -10.25
DEFAULT_DCA_buy_trigger_39 = -10.5
DEFAULT_DCA_buy_trigger_40 = -10.75
DEFAULT_DCA_buy_trigger_41 = -11
DEFAULT_DCA_buy_trigger_42 = -11.25
DEFAULT_DCA_buy_trigger_43 = -11.5
DEFAULT_DCA_buy_trigger_44 = -11.75
DEFAULT_DCA_buy_trigger_45 = -12
DEFAULT_DCA_buy_trigger_46 = -12.25
DEFAULT_DCA_buy_trigger_47 = -12.5
DEFAULT_DCA_buy_trigger_48 = -12.75
DEFAULT_DCA_buy_trigger_49 = -13
DEFAULT_DCA_buy_trigger_50 = -13.25

DEFAULT_DCA_buy_percentage_1 = 100
DEFAULT_DCA_buy_percentage_2 = 100
DEFAULT_DCA_buy_percentage_3 = 75
DEFAULT_DCA_buy_percentage_4 = 25
DEFAULT_DCA_buy_percentage_5 = 20
DEFAULT_DCA_buy_percentage_6 = 15
DEFAULT_DCA_buy_percentage_7 = 10
DEFAULT_DCA_buy_percentage_8 = 9
DEFAULT_DCA_buy_percentage_9 = 8
DEFAULT_DCA_buy_percentage_10 = 6
DEFAULT_DCA_buy_percentage_11 = 6
DEFAULT_DCA_buy_percentage_12 = 5
DEFAULT_DCA_buy_percentage_13 = 5
DEFAULT_DCA_buy_percentage_14 = 5
DEFAULT_DCA_buy_percentage_15 = 4
DEFAULT_DCA_buy_percentage_16 = 4
DEFAULT_DCA_buy_percentage_17 = 4
DEFAULT_DCA_buy_percentage_18 = 4
DEFAULT_DCA_buy_percentage_19 = 4
DEFAULT_DCA_buy_percentage_20 = 4
DEFAULT_DCA_buy_percentage_21 = 3
DEFAULT_DCA_buy_percentage_22 = 3
DEFAULT_DCA_buy_percentage_23 = 3
DEFAULT_DCA_buy_percentage_24 = 3
DEFAULT_DCA_buy_percentage_25 = 3
DEFAULT_DCA_buy_percentage_26 = 3
DEFAULT_DCA_buy_percentage_27 = 3
DEFAULT_DCA_buy_percentage_28 = 3
DEFAULT_DCA_buy_percentage_29 = 3
DEFAULT_DCA_buy_percentage_30 = 3
DEFAULT_DCA_buy_percentage_31 = 2
DEFAULT_DCA_buy_percentage_32 = 2
DEFAULT_DCA_buy_percentage_33 = 2
DEFAULT_DCA_buy_percentage_34 = 2
DEFAULT_DCA_buy_percentage_35 = 2
DEFAULT_DCA_buy_percentage_36 = 2
DEFAULT_DCA_buy_percentage_37 = 2
DEFAULT_DCA_buy_percentage_38 = 2
DEFAULT_DCA_buy_percentage_39 = 2
DEFAULT_DCA_buy_percentage_40 = 2
DEFAULT_DCA_buy_percentage_41 = 2
DEFAULT_DCA_buy_percentage_42 = 2
DEFAULT_DCA_buy_percentage_43 = 2
DEFAULT_DCA_buy_percentage_44 = 2
DEFAULT_DCA_buy_percentage_45 = 2
DEFAULT_DCA_buy_percentage_46 = 2
DEFAULT_DCA_buy_percentage_47 = 2
DEFAULT_DCA_buy_percentage_48 = 2
DEFAULT_DCA_buy_percentage_49 = 2
DEFAULT_DCA_buy_percentage_50 = 2

#Others
DEFAULT_DCA_min_buy_volume = 0
DEFAULT_DCA_min_orderbook_volume_percentage = 100

DEFAULT_DCA_ignore_sell_only_mode = false

DEFAULT_DCA_max_buy_spread = 5
DEFAULT_DCA_rebuy_timeout = 5

#Triggers
DEFAULT_DCA_stop_loss_trigger = 0
DEFAULT_DCA_stop_loss_timeout = 0
DEFAULT_DCA_pending_order_wait_time = 0

DEFAULT_DCA_buy_min_change_percentage = -7
DEFAULT_DCA_buy_max_change_percentage = 5

DEFAULT_DCA_take_profit_wait_time = 0
DEFAULT_DCA_take_profit_percentage = 0

## Log files/console output

ive attached the log file, the most recent coin it happened on was BCC, it was DCAed 2 times but it sold as MAX PROFIT, it doesnt show you its DCAed but you can look at the USD value
![q](https://user-images.githubusercontent.com/38233913/42792354-f98f8d8a-89b3-11e8-9c42-36716db1c23e.JPG)

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2199841/ProfitTrailer.log)

**Comment by taniman** [comment]
Yes, i think I have seen this bug before. It's can happen when we get a false signal causing the DCA pair to move to PAIRS.
This needed a bigger change to fix so it has been fixed but in 2.1.0 release. 
Scheduled for 2 weeks or so

**Comment by perplex51** [comment]
ah ok, well guess nothing else i can do to fix it. is there another version that it may of worked on?

**Comment by perplex51** [comment]
yea but that doesnt work for my PAIRS config, so that wont work. i hope it is fixed in the new version
