### ISSUE TITLE
Binance API IP error

### ISSUE THREAD

**Issue by Dekline71** [taniman/profit-trailer#1977]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2224750/ProfitTrailer.log)

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [x ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Hi I have two binance bots on two different accounts that havent been able to run for weeks, before I had left it on for a few days and when I came back it was spamming errors. After that I could no longer run either bot with updated versions and waited a week and still I get this error. I dont know if my API or IP have been permanently banned by Binance.
![image](https://user-images.githubusercontent.com/5232454/43156332-d6bfb14c-8f47-11e8-9074-ea376b49024e.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Binance removed all API keys a couple of weeks ago.
Please create new API keys
and register the new default_api_key with PT assistant.

Also here is a place to report bugs. Next time contact support regarding these kind of questions

**Comment by Dekline71** [comment]
I was unaware. Thanks!

**Comment by Rswtrader1** [comment]
Did they only eliminate the APIs for PT bots? My mobile binance app still works fine with old APIs.

Thank you

**Comment by taniman** [comment]
No, it was all API keys. Please find below their announcement from a couple of weeks ago
https://support.binance.com/hc/en-us/articles/360006669152-Security-Update-API-Key-Reset-

**Comment by taniman** [comment]
@Dekline71  Yes. just create like you did initially
