### ISSUE TITLE
Max Pairs not working

### ISSUE THREAD

**Issue by sas7085** [taniman/profit-trailer#1978]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

The maximum pair set pairs.properties file is not working properly. It seems this is considering the DUST count.
I set the maximum pair to 20 and Pairs - 3 DCA -16 and Dust -1  total is 20 (including the DUST) .
In possible buy it is showing MAX Pairs reached. 

![image](https://user-images.githubusercontent.com/36013435/43208253-0532d9fe-8ff8-11e8-86b6-2ee42b2c13c5.png)

![image](https://user-images.githubusercontent.com/36013435/43208324-29f0b98c-8ff8-11e8-8d19-7d1e7af0662f.png)

![image](https://user-images.githubusercontent.com/36013435/43208573-bc5d76fc-8ff8-11e8-88c5-c0e9a37b394c.png)

## ProfitTrailer info
Version: 2.0.16

 
Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

 
Market:
- [X ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ X] Ubuntu (16.04 LTS)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

PT should buy  1 more coin to achieve the Max Piar set in Pair properties.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Please provide your logfile

**Comment by sas7085** [comment]
Sold the DUST manually . In PT  now the DUST is 0 but in possible buy screen still it is showing Max Pirs. May be the count is not refreshed.

![image](https://user-images.githubusercontent.com/36013435/43209003-ae1c4608-8ff9-11e8-9c1e-985b31348591.png)

**Comment by taniman** [comment]
restart the bot and see what it says.  If it still shows max pairs then it is counting another pair that is not being shown

**Comment by sas7085** [comment]
After restart no changes. PT showing the max pair with 3 - pairs and 16 DCA. 
Please find the attached log file . 
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2228424/ProfitTrailer.log)

**Comment by sas7085** [comment]
Now got the issue. It was due to the VET allocation. Now it is showing up in pairs properties.  Now it is correct Pair - 3 and DCA -17. Total is 20
![image](https://user-images.githubusercontent.com/36013435/43209840-a413d570-8ffb-11e8-97f8-d50e5edeeb06.png)

**Comment by taniman** [comment]
Aah. nice one. So you just need to set the correct price and the problem is solved right?

**Comment by sas7085** [comment]
Yes now set the price for VET.  Now it is fine. At Least expectation was VET should appear earlier but after restart it showed up. Thanks
