### ISSUE TITLE
[FEATURE request] Instant strategy simulator fully based on chart history

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer#1979]
The basic problem with Profit Trailer, trading random stock markets is, that you dont really know whether you will have success with your PT settings or not, because you dont really know what is going to happen. 

I know there is this Paper Trading feature so far. But its actually too slow. In order to give a real judgment on individual settings you would probably needed to test everything for at least half a year without modifying it. But to be honest noone would actually be patient enough to do so. And meanwhile you would have probably changed the settings several times. So you cant really give a useful statement by that method, it just takes too long.

But i have an idea. What if there was an instant strategy simulator based on the chart history of all coins. 

The idea is, you have a start time and end time (User input / or time period). During that time period PT needs to fully store the chart history of the coins or at least have access to it. Now you could press an "Instant simulate" button and what PT does, it instantly simulates your PT settings based on the charts, just limited by your CPUs calculation power and not by the real time. The output might be, that the user sees the balance, before and after the simulation. Also how often the simulated coins got sold (with their profits) or rebought or what their current profit percentage is at the end.

Please let me know what you think about this idea. Imo it could save a lot of time.

If you got further idea about that, just feel free.

Kind regards,
Robert

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by SgtBatten** [comment]
Hi Robert. Great idea but please post it in the PT enhancements repository. This one is for bugs only.
