### ISSUE TITLE
TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer#1981]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ X] Poloniex

 
Market:
- [X ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
## Current Behavior

just happen
## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

[PTNotifications.log](https://github.com/taniman/profit-trailer/files/2250418/PTNotifications.log)
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2250419/ProfitTrailer.log)

**Comment by felipeqga** [comment]
PTTracker sends this message to my telegram BOT "TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task."

**Comment by taniman** [comment]
please provide your log file as required by the template

**Comment by taniman** [comment]
Also maybe support on discord could help u faster with this

**Comment by taniman** [comment]
I have inspected your log file.  But there are no errors in your PT log file. Looks to me that it's a PTN compatibility issue. The bot seems to be running fine. 

You should create an issue on the PTN site. I will contact the DEV also. hopefully we can find the issue ASAP

**Comment by felipeqga** [comment]
Thank you for that.!
I will close this issue.!
