### ISSUE TITLE
Changing Advanced config comment lines does not change config

### ISSUE THREAD

**Issue by ArmchairGuru** [taniman/profit-trailer#1982]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.0

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
the advanced config should save changes as typed

## Current Behavior
every time any changes are made, any commented lines are left as a single string, not on separate lines

## Troubleshooting
cleared browser cache, used different browser

## Possible Solution
unknown

## Steps to Reproduce

1. 
2.
3.
4.

## Configuration

http://prntscr.com/kdh2tm

## Log files/console output

 
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2250495/ProfitTrailer.log)

**Comment by atomize** [comment]
I am going to give a go at reproducing this. Just to be clear, if you change a commented line, then save, this is what your comments look like the next time you load?

**Comment by SgtBatten** [comment]
I can repro this and I know the fix for now

Don't leave blank after the = signs.

If you enter a value after the = it won't combine them

**Comment by atomize** [comment]
I just realized what you meant in your description to reproduce this. This isn't preferred behavior so now that I know how it is happening I think I should be able to easily prevent this. Good catch.

**Comment by taniman** [comment]
Seems Berti is working on this. But seeing as this bug was the result of another bug that was fixed . I am closing this.
