### ISSUE TITLE
PT web ui doesnt load data because of https mismatch

### ISSUE THREAD

**Issue by apondman** [taniman/profit-trailer#1984]
## ProfitTrailer info
Version: 2.1

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows Server 2016
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
PT web ui displays data

## Current Behavior
PT web ui doesnt display data

## Possible Solution
Let PT use the derived protocol and not only http when calling the monitoring data endpoint

## Steps to Reproduce
Run PT in a reverse proxy https setup. The setup has been working correcly with previous versions of PT.

Chrome reports:

`The page at 'https://my.profittrailer.bot/monitoring' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://my.profittrailer.bot/monitoring/data?_=1533146945884'. This request has been blocked; the content must be served over HTTPS.`

i have replaced the actual url with a made up one in the message above.

**Comment by taniman** [comment]
What is your actual PT configuration. Are you using some kind of proxy?

**Comment by apondman** [comment]
i'm running PT on a Windows Server 2016  VPS  exposing it to the internet using an Internet Information Services setup with Application Request Routing. This is reverse proxy setup that will route my "external" domain with https to the internal PT host. This has always worked in previous PT versions.

Locally on the machine PT works fine.. it's just that there is probably a hard reference to "http" in the script calls that is causing this.

**Comment by taniman** [comment]
Yes. for this to work with PT 2.1.0 you will need to add this to your configuration.
I am not sure how to do that for IIS. But this is what I have in nginx.
The scheme part is really important

      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

**Comment by sergeysolovev** [comment]
@apondman I got the same issue on nginx, forwarding the protocol helped me `proxy_set_header X-Forwarded-Proto $scheme;`. For IIS check out this doc:

https://docs.microsoft.com/en-us/iis/extensions/configuring-application-request-routing-arr/creating-a-forward-proxy-using-application-request-routing

I guess you need to tweak Proxy Setting -> Http Version.

**Comment by apondman** [comment]
i've added the following server variables to every request pass through the proxy:

HTTP_X_FORWARDED_SCHEMA   https
HTTP_X_FORWARDED_PROTO   https

and now it works.

**Comment by taniman** [comment]
awesome

**Comment by haydenyoung** [comment]
Had the same problem in Apache2. Settings to fix:

RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
