### ISSUE TITLE
DEFAULT_combine_pending_orders = false #orders shown in PT dashboard bug

### ISSUE THREAD

**Issue by nostrakhan** [taniman/profit-trailer#1985]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.0

 
Exchange:
- [x] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version) 7
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When multiple pending orders of the same coin exist they should each show their own respective order data in the PT Dashboard -> Pending section.
## Current Behavior

I created 3 pending orders on bittrex.  Each has a different sell price.  The PT Dashboard's Pending section shows all 3 separate orders, but it shows them all with the exact same order data (does not display each of their own order data).
## Troubleshooting

I tried restarting PT.  I tried changing DEFAULT_combine_pending_orders back to TRUE, and then back again to FALSE.
## Steps to Reproduce

1. Set DEFAULT_combine_pending_orders = false in the PAIRS.
2.  Make multiple sell orders for different prices for the same pair on the exchange.
3.  Check the PT Dashboard -> Pending to see if it shows the correct pending order data in the PT Monitor's Dashboard -> Pending section.

## Configuration

PAIRS https://pastebin.com/8F5DSRJ9
INDICATORS https://pastebin.com/uFdySu6P
DCA https://pastebin.com/r5QRKGQx

**Comment by SgtBatten** [comment]
Can confirm this is happening. Throws off TCV also

**Comment by echthard** [comment]
Wanted to create an issue for this as well. I have it on Binance.

**Comment by taniman** [comment]
Fixed for next release
