### ISSUE TITLE
Safari UI problem on hotconfig at  2.1.0

### ISSUE THREAD

**Issue by t1m3c** [taniman/profit-trailer#1986]
Safari Version 11.1.2 (13605.3.8):
<img width="485" alt="pt 2 1 0" src="https://user-images.githubusercontent.com/32812997/43543529-f55109c0-95d8-11e8-8987-5f0180a8fdce.png">

**Comment by atomize** [comment]
Other reports of this modal bug have been resolved by doing a hard reset on the browser cache. Give this a shot and see if it remedies your issue and comment here if successful/unsuccessful.

**Comment by t1m3c** [comment]
Yes, it's helped. Thanks! I'll close this issue later. Others peeps will need it probably in short. :)
