### ISSUE TITLE
Endless loading screen

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#1988]
## ProfitTrailer info
Version: 2.1.0

 
Exchange:
- [x] Bittrex
- [x] Binance
- [x] Poloniex

 
Market:
- [x] BTC
- [x] ETH
- [x] USDT
- [x] BNB
- [x] XMR

 
Operating System:
- [x] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
GUI should load

## Current Behavior
endless loading screen
https://cdn.discordapp.com/attachments/401029239647895574/474344316874260501/2018-08-02_00-32-46.gif

## Troubleshooting
Clear cache does not help. F12 shows that the ` characters are invalid for javascript in IE

## Possible Solution
Remove these invalid character

## Steps to Reproduce
1. Use version 2.1.0
2. Open the bot using  Internet Explorer
3. Voilá

**Comment by felipeqga** [comment]
I have the same on my Iphone(safari).

**Comment by djcrypto75** [comment]
IE not supported. On IOS and Safari its working fine here. Did you try and clear safari cache on the phone? Also what IOS version and safari version?
