### ISSUE TITLE
Pop up dialogues not rendering properly

### ISSUE THREAD

**Issue by djbadders** [taniman/profit-trailer#1990]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

One of my upgraded PT instances isn't able to render any of the pop-up dialogues correctly it would seem. Initially they did work but even after a restart I see pop-ups but only the title and OK buttons are rendered and where the message should be it reads [object Object]. This happens if I try a buy button or the Stop button and I suspect any other button.
![image](https://user-images.githubusercontent.com/34887832/43605634-d9b79036-9690-11e8-9001-0475e6bc361f.png)
![image](https://user-images.githubusercontent.com/34887832/43605639-dfd62ec8-9690-11e8-86ee-f55229f86366.png)

## ProfitTrailer info
Version: 2.1.0

 
Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

 
Market:
- [X ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [X 18.04 ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Dialogues should render correctly with the multiple choice buttons.

## Current Behavior

I always see pop-ups but only the title and OK buttons are rendered and where the message should be it reads [object Object]. This happens if I try a buy button or the Stop button and I suspect any other button.
![image](https://user-images.githubusercontent.com/34887832/43605634-d9b79036-9690-11e8-9001-0475e6bc361f.png)
![image](https://user-images.githubusercontent.com/34887832/43605639-dfd62ec8-9690-11e8-86ee-f55229f86366.png)

## Troubleshooting

* Restarted PT several times

## Steps to Reproduce

1. Click on any of the buy, sell or stop buttons in PT's web UI
2.
3.
4.

## Log files/console output

 
No log data when the issue occurs.

**Comment by taniman** [comment]
There were some other users with this error. A simpel ctrl + f5 or browser cache clear fixes it on chrome, firefox and safari.

**Comment by djbadders** [comment]
That appears to have fixed it for now. Thanks
