### ISSUE TITLE
Frontend clear commented value/text

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer#1991]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.1

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [X] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

if you have this in your PAIRS.PROPERTIES

the information  `= XYZ ` is removed and you lost informations in your file.

supply this  information/word  after `DEFAULT_A_buy_value ` in all your commented lines "#"
Before:
`#DEFAULT_A_buy_value = 0.1`
After:
`#DEFAULT_A_buy_value `

frontend supply this  informations/word `= 0.1 ` in all your commented lines "#"

## Steps to Reproduce

```
enabled_pairs = ALL
enabled_pairs = AMP,ARDR,BCH
```
and comment this way
```
#enabled_pairs = ALL
enabled_pairs = AMP,ARDR,BCH
```
and then shortly thereafter 
... you go to the frontend and make  changes in the "Blacklist"  add/remove new PAIR and save
the following happens:
```
#enabled_pairs
enabled_pairs = AMP,ARDR,BCH
```
the information `= ALL ` is removed and you lost informations in your file.
this behavior occurs here too
#DEFAULT_A_buy_value
#DEFAULT_A_buy_value_limit
supply this  informations/words `= ALL ` in all your commented lines "#"

**Comment by SgtBatten** [comment]
Perhaps its not affecting all parameters the same way.

For my examples all i lose is the space before and after the = sign

![image](https://user-images.githubusercontent.com/24822223/43613741-f47053e6-96f3-11e8-93f6-6e0b887fe404.png)

**Comment by felipeqga** [comment]
SgtBatten you are right ,
Could you make this test:
put false .. typing manually.. save (adv mode)
TRX_trading_enable = true
and go to the frontend and put false.

**Comment by SgtBatten** [comment]
it worked as expected.

changed it to true in advanced and saved. went to basic, selected TRX from the dropdown, toggled trading back to false and saved. went back to advanced and it was false again.

**Comment by felipeqga** [comment]
disappear all my settings
See, no` = XX`
#DEFAULT_A_buy_strategy
#DEFAULT_A_buy_value
#DEFAULT_A_buy_value_limit

#DEFAULT_B_buy_strategy
#DEFAULT_B_buy_value
#DEFAULT_B_buy_value_limit

#DEFAULT_C_buy_strategy
#DEFAULT_C_buy_value
#DEFAULT_C_buy_value_limit
#
#DEFAULT_D_buy_strategy
#DEFAULT_D_buy_value
#DEFAULT_D_buy_value_limit
#
#DEFAULT_E_buy_strategy
#DEFAULT_E_buy_value
#DEFAULT_E_buy_value_limit

**Comment by SgtBatten** [comment]
yes we've already established the issue, the devs will be looking into it.

**Comment by atomize** [comment]
resolved in next PR, good catch, this was tricky. Let's keep an eye on it.
