### ISSUE TITLE
The DCA rebuy timeout is not updated when changed (DEFAULT_DCA_rebuy_timeout)

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer#1993]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [X] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

set the time here :
`DEFAULT_DCA_rebuy_timeout = 40`
and after DCA complete a Buy  Ex: DCA number |1| apper like that `REBUY TIMEOUT (38m)`..
after some minutes `REBUY TIMEOUT (21m)`
and you want reduce the rebuy time  for 12 minutes for example.
set  new time `DEFAULT_DCA_rebuy_timeout = 12`
The Expected Behavior is that system do update in time DCA rebuy clock 
so new expected time to the PAIR is = 12 REBUY TIMEOUT (12m)

## Current Behavior

Regardless of whether you change the "Rebuy" time of the DCA "rebuy clock" continues to count according to the time it was originally purchased(first Buy) and dont update new puted/inserted time
`DEFAULT_DCA_rebuy_timeout = 12`.
if the pair was bought when the time was 40 `DEFAULT_DCA_rebuy_timeout = 40` minutes and you change to 12 `DEFAULT_DCA_rebuy_timeout = 12` the DCA "rebuy clock" does not reset the clock/time and the new value is not seted/posted by the system

## Steps to Reproduce

1. set new value here DEFAULT_DCA_rebuy_timeout = 30
2. Wait DCA buy once and count time wait 3 minutes and time will be  REBUY TIMEOUT (27m) +-
3. Make change here DEFAULT_DCA_rebuy_timeout = 5
4. Nothing happens. Time does not change is not updated

**Comment by SgtBatten** [comment]
A restart is required to change timer based settings.

**Comment by SgtBatten** [comment]
but in your example it would not have a 12 minute timer btw, it would be already expired

**Comment by felipeqga** [comment]
SgtBatten, You said "A restart is required to change timer based settings." on P T Ver:  2.0.16
I can do this , I change the time wothout restart PT bot.

**Comment by felipeqga** [comment]
if I force a "buy" by the button "BUY" the new time becomes valid the system updates to the new value placed

**Comment by SgtBatten** [comment]
Well yes that would reset the value as it's a new rebuy timeout.

What I meant was for a coin that has already got a timeout you cannot reset it without restarting.

**Comment by taniman** [comment]
As sgtBatten says. Once the rebuy timeout is triggered for a coin. It runs it's course. There is no way around that. 
New buys will have the new timeout
