### ISSUE TITLE
Mega Slow scrolling GUI.

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer#1994]
MacBook Pro (Retina, 15-inch, Mid 2015), 2,5 GHz Intel Core i7, 16 GB 1600 MHz DDR3

I get a very slow GUI with new versión when i scroll:

VIDEO:
https://www.dropbox.com/s/tatdewebr1liyb3/megaslow.mov?dl=0

**Comment by djcrypto75** [comment]
What Browser?
Have you tried to clear cache?
What MacOs version?

**Comment by juato4** [comment]
@djcrypto75 Yes, cleared cache many times. 

Safari: Versión 11.1.2 (13605.3.8)
Os Version: High Sierra 10.13.6 (17G65)

**Comment by juato4** [comment]
i have this on the console:

< <html class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms no-csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths">
<head>…</head>
<body class="fixed-left widescreen">…</body>
</html>
[Warning] Automatically scrolling cursor into view after selection change – "this will be disabled in the next version" – "set editor.$blockScrolling = Infinity to disable this message" (ace--.js, line 1)
[Warning] Automatically scrolling cursor into view after selection change – "this will be disabled in the next version" – "set editor.$blockScrolling = Infinity to disable this message" (ace--.js, line 1)

**Comment by djcrypto75** [comment]
fixed in last GUI build.

**Comment by juato4** [comment]
@djcrypto75 after 30min i got the same problem.

**Comment by juato4** [comment]
Video:

https://www.dropbox.com/s/r2uuko1z0af0mk0/Sin%20t%C3%ADtulo2.mov?dl=0

**Comment by felipeqga** [comment]
I am using Yosemite 10.10.5 with Chrome Version 67.0.3396.99 (Official Build) (64-bit).
No Problem Here.

**Comment by juato4** [comment]
@felipeqga the problem is on safari.

**Comment by djcrypto75** [comment]
Yes its fixed on last GUI build, its not on the last release 2.1.3, it should be included on the next release.

**Comment by felipeqga** [comment]
My Safari Version 10.1.2 (10603.3.8) Its OK here.
Could you create a second User on you Mac and test it ?

**Comment by juato4** [comment]
@felipeqga you need to wait 1 hour at least. then the video will happen.
