### ISSUE TITLE
Consecutive Buy problem

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#1995]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1 Test Mode

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

PT should disable SOM when a sell is made after x consecutive buys. 

## Current Behavior

I'm using Monte Carlo settings. PT bought 6 coins and SOM is activated since consecutive_buy_trigger = 6.
After that, PT sold a coin and SOM is still active. I believe this was working fine before 2.1
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2256089/ProfitTrailer.log)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
I will need also your ProfitTrailerData.json to confirm the buys and sells. And are you ignoring SOM for DCA buys?

**Comment by mightysoul** [comment]
I've reset the  Test data after but I'm attaching it anyways.  Also setting consecutive_sell_trigger = 1 seems like a workaround fix for the problem.
[ProfitTrailerData.zip](https://github.com/taniman/profit-trailer/files/2256538/ProfitTrailerData.zip)

**Comment by taniman** [comment]
@mightysoul  Now you have me confused. 
consecutive_buy_trigger is supposed to only disable if consecutive_sell is set. 

If you did not have consecutive_sell set. Than it would indeed not disable the consecutive_buy. I am certain even in 2.0.X it was not disabling it.

So you are saying you had no consecutive_sell set?

**Comment by mightysoul** [comment]
I had it set 0 for testing. Wasn't able to disable SOM. I'm closing the case since setting consecutive_sell=1 solved my problem. Thank you for looking in to it anyway.
