### ISSUE TITLE
Dust Bought Value keep resetting to 0

### ISSUE THREAD

**Issue by AhmedRHS** [taniman/profit-trailer#1998]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

The dust amount of a coin keeps reseting to 0 even when I use hot config to set the price. It shows up correct for few seconds but then it loses the price.
## ProfitTrailer info
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2259467/ProfitTrailer.log)

Version: 2.1.1

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Could you please  tell us a bit more. What coin are you resetting price. And when is it relosing it's price?

**Comment by taniman** [comment]
Also provide your profittrailerdata.json

**Comment by AhmedRHS** [comment]
Hello,

I'm using PT Defender to defend DNT coin, once it goes to dust, the price
shows up for few seconds and then disappear. This happens also when I try
to hot config the bought price.
Attached is the requested file.

Thanks

**Comment by taniman** [comment]
Sorry, I am nmot seeing the requested file

**Comment by taniman** [comment]
If you could please contact us on discord so we can have a faster check and resolution would be great. 
As we do not support PT Defender I would really like to know where the problem is coming from.

Have you tried turning off PT Defender and then setting the bought price? Does the price stay set if you do that?
