### ISSUE TITLE
Changing values in a configuration will copy the entire configuration to another

### ISSUE THREAD

**Issue by belvi82** [taniman/profit-trailer#2002]
## ProfitTrailer info
Version: 2.1.1

 
Exchange:
- [ x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ x] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ x] Mac OS

## Expected Behavior
Changing values in strategy2 must change nothing in strategy1 

## Current Behavior
I have 2 strategy in config menu (strategy1 - strategy2): when I change something in strategy2 (no matter if I am in basic or advanced mode) and click on save button and then switch to strategy1 (in config menu) I find strategy1 is a copy of strategy2 

## Troubleshooting
used different browser (chrome, firefox, opera), issue is the same

## Steps to Reproduce
1. change some values in strategy2
2. save changes
3. switch to strategy1 (in config menu)
4. strategy1 now has the SAME values of strategy2 (before was very different), it happens every time

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2260658/ProfitTrailer.log)

**Comment by taniman** [comment]
I would like if you could create a screen recording of this happening. 
Cause this seems very unlikely and without a bit more concrete evidence I would not want to search further.

As I asked in discord. Are you waiting enough time for the settings to get loaded.

**Comment by belvi82** [comment]
Here is the video. Sorry if I do something wrong.
[PT_save_changes_issue.mov.zip](https://github.com/taniman/profit-trailer/files/2263708/PT_save_changes_issue.mov.zip)

**Comment by taniman** [comment]
wow, interesting. I will try to reproduce on my machine too

**Comment by taniman** [comment]
There is still 1 small problem even though the files will not be copied incorrectly anymore. It has been fixed in 2.1.4
