### ISSUE TITLE
Config changes are lost too easily

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer#2003]
## ProfitTrailer info
Version: 2.1.1

 
Operating System:
- [x] Windows 

## Expected Behavior

Show a pop-up telling me that I will lose my changes.
I think it's more important that when I change stuff in Pairs and then click DCA (Advanced config), there's no pop-up telling me that I will lose my changes.

## Current Behavior

When I change stuff in Pairs and then click DCA (Advanced config), there's no pop-up telling me that I will lose my changes.

The pop-up that you do get when clicking on a different link from the top navigation, could refer to the floppy disk icon. Instead of only "Changes that you made are not saved. Do you still want to leave this page?". Because I saw people on Discord having trouble finding it.

## Steps to Reproduce

1. Have the Advanced config enabled
2. Click on Config
3. Click on Pairs
4. Change something
5. Click on DCA
6. Go back to Pairs

You'll see the changes are gone.

**Comment by atomize** [comment]
resolved in next PR
