### ISSUE TITLE
buy log prices incorrect for DCA'd coins 

### ISSUE THREAD

**Issue by boltron1** [taniman/profit-trailer#2006]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.1.1

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [x] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

the price for bought coins on the exchange and profit trailer should match in the buy log. 
## Current Behavior

when a coin is purchased via DCA, the exchange shows the actual price the coin was purchased at. (much higher than what profit tailer is reporting). The buy log shows a lower bought price for the coin.   
## Troubleshooting

lowered DCA purchase point from -0.5% to -1.5%
## Possible Solution

maybe possible that the buy log is using the current tick price the DCA log used to trigger a buy. 
## Steps to Reproduce

1.buy coin in BNB market 
2.set DCA to something just below zero
3.wait for DCA to purchase coin again 
4.view buy log
5.view transactions on the exchange 

## Log files/console output

 

![bnbdca](https://user-images.githubusercontent.com/7003194/43758306-884980fe-99d0-11e8-96a3-b5a8de46f1eb.PNG)
![bnbdca2](https://user-images.githubusercontent.com/7003194/43758307-8865401e-99d0-11e8-8f30-a3f9e58d8987.PNG)
[tochi-DCA (1).txt](https://github.com/taniman/profit-trailer/files/2265246/tochi-DCA.1.txt)
[tochi-INDICATORS (1).txt](https://github.com/taniman/profit-trailer/files/2265247/tochi-INDICATORS.1.txt)
[tochi-PAIRS (1).txt](https://github.com/taniman/profit-trailer/files/2265248/tochi-PAIRS.1.txt)

**Comment by taniman** [comment]
For all intents and purposes I do not see why the buylog is showing incorrect data.  The log file is showing the same data as Binance.

So please provide your ProfitTrailerData.json so I can confirm

**Comment by taniman** [comment]
Okay, Found it finally.  Fixed in next release
