### ISSUE TITLE
Automatic backups not working on windows systems

### ISSUE THREAD

**Issue by ArmchairGuru** [taniman/profit-trailer#2008]
Automatic backups every 5 minutes are not working on windows systems.

## ProfitTrailer info
Version:2.1.3

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
automatic backup should make a new file every 5 minutes

## Current Behavior
automatic backups are not happening

## Troubleshooting
refreshed explorer window, reloaded explorer window, restarted bot

## Steps to Reproduce

1. start 2.1.3, check for automatic backups on windows system
2.
3.
4.

## Configuration
N/A

## Log files/console output
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2267043/ProfitTrailer.log)

![image](https://user-images.githubusercontent.com/42007672/43786269-3cc1fab0-9a36-11e8-8539-2f8a15e65452.png)

**Comment by taniman** [comment]
Yes thank you. That was a quick find
