### ISSUE TITLE
Stop PT in settings not working on ports other than 8081

### ISSUE THREAD

**Issue by BurnData** [taniman/profit-trailer#2009]
When running a PT from another port (8082  in my case), when you go to shut down the bot via {settings-stop profit trailer} you get this popup. Note that I have another PT running on 8081 at the same time and it gives the normal shutdown confirmation as it should.

the message is STOP, [object Object] with and OK button but no confirmation like it should have
![image](https://user-images.githubusercontent.com/34041159/43792158-e692b78c-9a45-11e8-8cf7-01d6676216dd.png)

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X ] Windows (server 2012) 
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
press ctrl +  F5 to clear the cache of your browser and fix this problem.
