### ISSUE TITLE
DCA not triggering in test mode

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#2010]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.2

 
Exchange:
- [x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

DCA trigger in PAIRS is set to -1
## Current Behavior

DCA is not triggered. Second coin I have now in the test bot, where the coin goes under -1 % and DCA is not triggered, coin remains in PAIRS folder.
It was working fine prior to updating to 2.1.2
## Troubleshooting

I sold the first pair it happened to manually, since it is only a test bot, thinking it might just have been a glitch. But now I have another pair not DCA-ing. (see screenshot of pair folder)
![image1](https://user-images.githubusercontent.com/36098310/43798078-7082a5f4-9a57-11e8-8185-1c235ecc407b.png)
![image2](https://user-images.githubusercontent.com/36098310/43798249-f9c77006-9a57-11e8-83ec-ae7c7cd13c47.png)

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 
[log.zip](https://github.com/taniman/profit-trailer/files/2267807/log.zip)

**Comment by taniman** [comment]
Please click on the downlaod button on your configs page. And attach your configs too

**Comment by alexdolli** [comment]
It's the Default Monte Carlo Settings. Here ya go:
[Config.zip](https://github.com/taniman/profit-trailer/files/2267831/Config.zip)

**Comment by taniman** [comment]
@alexdolli The default settings have this inside. Scroll down. LTC_DCA_enabled = false
So yes. LTC will never DCA

I will close this now. :)

**Comment by alexdolli** [comment]
Ooh! I did not see that. Thanks!
