### ISSUE TITLE
server.exchangeUrl = https://www.binance.com/en/trade/?symbol=%c_%b not working

### ISSUE THREAD

**Issue by cryptocoyns** [taniman/profit-trailer#2011]
## ProfitTrailer info
Version: 2.1.3

Exchange:
- [ ] Bittrex
- [ X] Binance
- [ ] Poloniex

Market:
- [X ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

perating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [X ] Mac OS

## Expected Behavior
This is from a support request the user wanted the Basic view of Binance Exchange instead of the Advanced view, which appears to be  PT's default.

Should act as described here: https://wiki.profittrailer.com/doku.php?id=application.properties#serverexchange_url

## Current Behavior
Default path of https://www.binance.com/tradeDetail.html?symbol=%c_%b is overriding the user defined server.exchangeUrl = https://www.binance.com/en/trade/?symbol=%c_%b

## Troubleshooting
After user tried it I tested it out on on my Binance test bot and confirmed it wasnt working.

## Steps to Reproduce
1. stop test bot running
2. set server.exchangeUrl = https://www.binance.com/en/trade/?symbol=%c_%b in applications.properties
3. restart test bot
4. hover over and click on a trading pair in ProfitTrailer PBL

## Configuration
Running Golden Cross default settings

## Log files/console output
DM me on discord for logs if required

**Comment by taniman** [comment]
Check the wiki again. The vorrect naming is.
server.exchange_url

That should make it work. We did ptovide the incorrect naming in files of 2.0 though.
