### ISSUE TITLE
Basic config - PAIR specific dropdown

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#2015]
## ProfitTrailer info
Version: 2.1.4-B4

Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
When I select the pair specific dropdown my current config should not change

## Current Behavior
My current editingConfig changes when I choose a pair specific from dropdown

## Troubleshooting
clear cache

## Possible Solution
No idea

## Steps to Reproduce
![2018-08-09_10-07-12](https://user-images.githubusercontent.com/6751341/43886465-14243172-9bbc-11e8-9a60-4b0c02ce110b.gif)

**Comment by atomize** [comment]
will close issue when I make PR with fix later today
