### ISSUE TITLE
DCA Button State Confusion - DCA button is true / false only but dca state can have an 'on' active value

### ISSUE THREAD

**Issue by ArmchairGuru** [taniman/profit-trailer#2018]
the DCA button state is confusing, as it only shows true / false , but if DEFAULT_DCA_enabled = -1 for example, the DCA state button shows off, even though DCA is active

## ProfitTrailer info
Version: 2.1.x

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1. set a DEFAULT_DCA_enabled = <number> value in pairs config advanced, save, check button state, it should be 'off' even though DCA is enabled
2.
3.
4.

## Log files/console output
![image](https://user-images.githubusercontent.com/42007672/43903464-81dd89b8-9bba-11e8-8e42-e3b37ad0d163.png)
![image](https://user-images.githubusercontent.com/42007672/43903505-9ae229c8-9bba-11e8-8a5c-c9682b49cb26.png)

**Comment by atomize** [comment]
yes i will implement
