### ISSUE TITLE
On pending log not showing bought price

### ISSUE THREAD

**Issue by JeppeJ** [taniman/profit-trailer#2019]
On pending log only "bid price" and "target price" is showing, why not bought price?
(have put manual sell)
Would be great to see the % from bought price to bid price

**Comment by taniman** [comment]
That's not an issue. You have a pending order. We get the data from your exchange. And the exchange never tells us what the bough price is. Because pending orders do not have a bought price. It can be anything
So the exchange does not know, and we do not know
