### ISSUE TITLE
SOMO button is missing from the config UI

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#2021]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.4 B4

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

A button in the sidebar or config that enables and disables SOMO

## Current Behavior

No button 😭so sad.

## Troubleshooting

Tried adding a button. Didn't work.

## Possible Solution

Add a button. 🤪

## Steps to Reproduce

1. Look at UI
2. See? No button!

**Comment by djcrypto75** [comment]
Working on it @Helmi :)

**Comment by djcrypto75** [comment]
Fixed
