### ISSUE TITLE
GUI not accessible after update (vps, Apache, Reverse Proxy)

### ISSUE THREAD

**Issue by Odiben123** [taniman/profit-trailer#2022]
## ProfitTrailer info
Version: 2.1.3

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (Ubuntu 16.04.4 LTS)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

If i acces my Profittrailer instance on my vps I can acces the GUI,

## Current Behavior
It doesn't work. I get redirected to 127.0.01.

## Troubleshooting
I have read discord and found the likely cause. 

Between 2.0.15 and 2.1.0 something has changed that messes up my apache https -->  http proxy mechanisme (see config section). There are additional commands to get it working on for example Nginx. However I am unable to find/implement such a solution for apache.

I was unable to get it to work even with the  suggestions made in discord by StgBatten.

(added)
The suggestion by StgBatten were

'https://www.google.com.au/url?sa=t&source=web&rct=j&url=https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup&ved=2ahUKEwivx7DBs97cAhXJ7WEKHaBxAEcQFjAEegQIABAB&usg=AOvVaw0Ogd_jsscrnqa40jzCEbNs&cshid=1533764009743

This may help
https://wiki.apache.org/httpd/RewriteHTTPToHTTPS
'
## Steps to Reproduce

1. install 2.1.x
2. try to acces the GUI, on remote vps with apache and  reverse proxy setup, to finish the setup
3.
4.

## Configuration
My current apache conf is

listen 6801

<VirtualHost *:6801>

    # SSL Engine
    SSLEngine on

    SSLCertificateFile /var/opt/ssl-keys/ptmagic-cert.pem
    SSLCertificateKeyFile /var/opt/ssl-keys/ptmagic-key.pem

    SSLHonorCipherOrder On
    SSLCipherSuite  ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH
    BrowserMatch "MSIE [6-9]" ssl-unclean-shutdown

    ProxyRequests Off
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS
    ProxyRequests On
    ProxyPreserveHost Off

    ProxyPass "/" "http://127.0.0.1:8081/"
    ProxyPassReverse "/" "http://127.0.0.1:8081/"

</VirtualHost>

This works up untill 2.0.15. ProfitTrailer 2.1.0 and upwards don't work.

## Possible Solution
I think the solution should be in changing the config file of apache2 since it works with for example nginx. However i have no idea what needs to be changed.

## Log files/console output

log with working (GUI is accessible) 2.0.15

2018-08-10 15:53:50 INFO Application - PT Version: 2.0.15
2018-08-10 15:53:50 INFO Application - Java Version: 1.8.0_171
2018-08-10 15:53:55 INFO Application$a - Server initialized with port: 8081
2018-08-10 15:54:01 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-10 15:54:01 INFO ProfitTrailerService - DCA Heartbeat
2018-08-10 15:54:01 INFO ProfitTrailerService - Cache Heartbeat
2018-08-10 15:54:04 INFO ProfitTrailerService - The bot will start trading at 2018-08-10T16:03:53.802

log with **not** working (GUI is not accessible) 2.1.3

2018-08-10 15:56:22 INFO Application - PT Version: 2.1.3
2018-08-10 15:56:22 INFO Application - Java Version: 1.8.0_171
2018-08-10 15:56:26 INFO Application - Please finish the setup process in your browser
2018-08-10 15:56:28 INFO Application$a - Server initialized with port: 8081

Note 2.1.4 also does not work,

**Comment by taniman** [comment]
Though this is not a bug and it's your setup I will do a small attempt to help you.

You should just use your public ip or domain name instead of pointing your proxypass to 127.0.0.1 see if that works

**Comment by Odiben123** [comment]
Thanks, unfortunately it does not solve the issue.

I get the warning about the authority invalid (which is ok) but if i continue i get a timeout.

Do you know what has changed to cause this? If I know perhaps i can search in a certain direction.

**Comment by taniman** [comment]
This is a working nginx configuration. Only thing that changed between the versions is that the protocol and scheme should be properly forwarded.

```
server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {

    listen 443;
    server_name demo.profittrailer.com;

    ssl_certificate           /etc/letsencrypt/live/demo.profittrailer.io/cert.pem;
    ssl_certificate_key       /etc/letsencrypt/live/demo.profittrailer.io/privkey.pem;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/nginx.log;
    proxy_set_header Connection keep-alive;

    client_max_body_size 10M;
            

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_set_header           Connection keep-alive;

      proxy_pass          http://localhost:8083;
      proxy_read_timeout  90;

      proxy_redirect      http://localhost:8083 https://demo.profittrailer.com;
    }

}
```

**Comment by taniman** [comment]
Here is a working apache2 configuration.

<VirtualHost *:8888>
	ServerName demo.profittrailer.com
	ServerAlias demo.profittrailer.com
	ServerAdmin webmaster@mydomain.com
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	ProxyRequests Off
	<Proxy *>
	  Order deny,allow
	  Allow from all
	</Proxy>
	
	ProxyPreserveHost On
	ProxyPass / http://127.0.0.1:8083/
	ProxyPassReverse / http://127.0.0.1:8083/

	<Location />
	  Order allow,deny
	  Allow from all
	</Location>
</VirtualHost>

This is not redirecting me to 127.0.0.1 so maybe it's the preserveHost that you turned off. Try turning that on.

I ma not using https for this configuration. But if you say this does not help you. I will change my machine to use https. But that should not make much more difference

**Comment by taniman** [comment]
I can now confirm that your problem is that preserveHost off you have set. It should be On. 
Once I changed my config to Off the 127.0.0.1 was being sent instead of my host

**Comment by Odiben123** [comment]
I can confirm that this solved the issue. Thank you.

**Comment by SgtBatten** [comment]
Nice one boss. I couldn't get there.

**Comment by stuartc** [comment]
This is a bit tough, I have apache with a http -> https redirect. I can get the UI to show but all the api requests are going to http and chrome denies the request due to 'mixed content'. My bot being served over https, and the api calls being http, so apache doesn't even get to rewrite the url.

This wasn't an issue in prior versions, would changing all the api calls the client to being relative fix this?
i.e. `//private?xyz` instead of `http://host/private?xyz`

**Comment by taniman** [comment]
@stuartc The user that started this is using https. So you should fix your configuration accordingly and it should work.
One important bit it so use 

RequestHeader set X-Forwarded-Proto "https" env=HTTPS

I do not have https setup because I do not use apache. But I am sure the internet can give you the answer you seek

**Comment by acefed** [comment]
Thanks a lot for the info, gents. After upgrading from PT v1 to v2, I needed both directives to fix my reverse PT proxies on a HSTS domain:

```
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto "https" env=HTTPS
```

All is well again now... having my first look at the v2 interface -> mind blown
