### ISSUE TITLE
Stop support for ARM version?

### ISSUE THREAD

**Issue by radeksalomon** [taniman/profit-trailer#2023]
Hello,

regarding the official add-on for PT called PT Tracker, there in info, they stopped supporting ARM version, even they inform customers the Tracker works on every version of PT.
https://github.com/bTayFla/PtTracker/issues/165

Do you plan to stop supporting ARM too? Because version of PT Pro contains PT Tracker and PT Notification. So the bought licenses of PT Pro will be not fully working.

Thanks.
Radek

**Comment by taniman** [comment]
This is a place to report bugs. Please be aware of that

We do not plan to change the supported devices of ProfitTrailer.
Also your license is fully functional You are not required to run PtTacker on the same machine as you run ProfitTrailer. 
So you could run ProfitTrailer on your ARM and tracker on a different machine pointing to the ProfitTrailer bot url for example
