### ISSUE TITLE
If I switch config. It loads the config and then does the switch.

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#2025]
## ProfitTrailer info
Version: 2.1.5-B2

Please do the switch, wait for confirmation and then load the settings.
This is causing timing issues.

Switch
![image](https://user-images.githubusercontent.com/6751341/44000118-6815d348-9e1a-11e8-91e8-4c854940a708.png)

Calls
![image](https://user-images.githubusercontent.com/6751341/44000123-7b6f665c-9e1a-11e8-8098-65effdffea20.png)

See how the switch is the last call being done? (Most recent call is lower in the list)

Well actually all these 4 calls are done almost simultaneously. So this is the biggest problem. now.
I have build in a delay now in the bot. But I would rather the frontend do the calls in the correct order

**Comment by atomize** [comment]
fixed in https://github.com/profittrailerbv/PTFrontend/pull/123
