### ISSUE TITLE
Basic HotConfig Typo

### ISSUE THREAD

**Issue by mhardy85** [taniman/profit-trailer#2027]
## ProfitTrailer info
Version: 2.1.5-B3

Operating System:
- [x] Windows (please specify version)
- [?] Ubuntu (please specify version)
- [?] Other linux distro (please specify)
- [?] Mac OS

## Expected Behavior
Basic editor HotConfig success dialog typo displays "Sent ADA_bought_price = 0.00001770 to monte_carlo"

## Current Behavior
Basic editor HotConfig success dialog typo displays "SentADA_bought_price = 0.00001770 to monte_carlo"
Just a small typo between "Sent" and the hotconfig command

## Steps to Reproduce
1. Set config editor to basic
2. Send hotconfig command
3. Read message

**Comment by atomize** [comment]
Thanks! Will close this when it gets fixed up.
