### ISSUE TITLE
PT update removed parameters of all #'out config entries

### ISSUE THREAD

**Issue by jpfl** [taniman/profit-trailer#2028]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.4

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ 10] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

after the update from PT 2.1.4 all the " =  values" in my config files of entries starting with # were removed as follows:

# ENJ_DCA_ignore_sell_only_mode
# ETH_DCA_ignore_sell_only_mode
# GTO_DCA_ignore_sell_only_mode
# ICX_DCA_ignore_sell_only_mode
# INS_DCA_ignore_sell_only_mode
# NEO_DCA_ignore_sell_only_mode
# NULS_DCA_ignore_sell_only_mode

# 180711-2123 DEFAULT_DCA_take_profit_percentage
# 180711-2116 DEFAULT_DCA_trailing_profit
# 180710-1840 DEFAULT_DCA_C_sell_strategy
# 180710-1800 added: DEFAULT_DCA_B_buy_strategy
# 180710-1800 added: DEFAULT_DCA_C_buy_strategy
# 180710-1615 #singles DEFAULT_DCA_max_buy_times
# 180710-1615 DEFAULT_DCA_buy_trigger
# 180710-1615 DEFAULT_DCA_max_buy_times
# 180710-1615 DEFAULT_DCA_buy_trigger

this happened in all 3 configs. basically if it was a valid parameter syntax but #'out then every numerical value like price or percentage or true / false has been removed including the " = ".
I use the config to note down changes including values used. they are all gone. gladly I did a backup before updating of the settings via clipboard into text files.
this is very annoying though and i hope this gets fixed soon.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by XannyD** [comment]
Note for devs: This happened with one of my config files, but not my other config file. Odd.

**Comment by jpfl** [comment]
for me all three pairs, dca and indicators were affected.

**Comment by taniman** [comment]
What version did you upgrade from? As this was a bug in 2.1.0/2.1.1/2.12 maybe but has already been fixed in 2.1.4 for certain.

**Comment by taniman** [comment]
So I would assume those values where already missing and you are only noticing now

**Comment by taniman** [comment]
It would have been great to have the replication steps next time.  you create an issue. Else we cannot find a solution.

With that being said. I have found 1 way to reproduce this problem. By copying a config with the values commented already.

**Comment by jpfl** [comment]
@taniman I did upgrade from 2.1.0, but I couldn't tell if the values were missing before. most likely not though as I was multiple times copying and pasting my set price for BNB as PT 2.1.0 still kept losing the buy price. I had the full command with price in DCA to copy and paste from there into the hotconfig.
