### ISSUE TITLE
Leak Profile manager

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer#2030]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [x] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

I can't see and I can't manage my profile configurations in localhost:8081/setup.
I can only choose between 5 profiles/configs and  I can't delete or rename.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by SgtBatten** [comment]
Can you please explain the issue a bit more.

Deleting and renaming configs is not done on the setup screen. I'm not sure what you are trying to do.

**Comment by SgtBatten** [comment]
Filling out the expected behaviour section would have helped me understand

**Comment by taniman** [comment]
Does not sound like an issue to me seeing. Please contact support on discord. 
Don't create issues if it's not really an issue or if you need support

**Comment by felipeqga** [comment]
Friend, 
![screenshot 2018-08-13 21 57 27](https://user-images.githubusercontent.com/40903953/44065943-1f920454-9f44-11e8-813f-e48d3ddb892d.png)
I Can't see "Delete" button, I only see "Load your settings" and the is no button to rename your "settings". in short, there is no way for me to manage the settings.
I can,t rename and can't delete, see:
![screenshot 2018-08-13 22 04 19](https://user-images.githubusercontent.com/40903953/44066110-e6861942-9f44-11e8-9e3a-a0e1b1bcc105.png)

**Comment by SgtBatten** [comment]
As i mentioned above, this is not where you rename or delete settings.

https://wiki.profittrailer.com/doku.php?id=faq#deleting_a_config

**Comment by SgtBatten** [comment]
yes, so what si your end goal here? what config are you trying to import?

**Comment by felipeqga** [comment]
Only one tool/function to facilitate configuration management.
I thought I was missing this  "function" on "setup" screen.
Excuse me. You can close the ticket/issue.
Thank you for your promptness.
