### ISSUE TITLE
FF vs Chrome config buttons

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#2035]
## ProfitTrailer info
Version: 2.1.5

Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
![image](https://user-images.githubusercontent.com/6751341/44212253-26d70b00-a16b-11e8-8dac-b8290739d0bb.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/6751341/44212220-10c94a80-a16b-11e8-9995-5078c301ff5e.png)

## Troubleshooting
ctrl + F5

## Possible Solution
Some minor CSS changes I beleive. 
1. Also the coin specific dropdown is missing something so people know it's a dropdown.
2. Could we add some seperator between the 2 fields and the icons. cause currently it's all like 1 line

**Comment by djcrypto75** [comment]
fixed
