### ISSUE TITLE
Switching from test mode, test buys and sells are showing in the logs on the live bot.

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer#2037]
![capture](https://user-images.githubusercontent.com/42469965/44267338-b50fc780-a225-11e8-95a7-71b7e85c2a65.JPG)

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.5

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x ] Other linux distro (please specify) - unsure which linux linkuphost use!
- [ ] Mac OS

## Expected Behavior
From the wiki: "When changing from test mode to live trading a restart is required. You may see some incorrect balances in your live bot for a minute or so after the restart. The test data will automatically clear itself completely."

## Current Behavior
I switched my PT live bot to test mode for a week to try various configs. This morning I updated to 2.1.5 and then switched it to live mode. Now the test buys and sells are showing in the sales and buy logs on the live bot.

## Troubleshooting
I hashed out the the start balance setting. That didn't work.

## Steps to Reproduce

1. Switch live pt bot to test mode and run it for some time
2. Stop the bot using pm2 stop all
3. Switch test mode to false in application settings.
4. Start the bot normally using pm2 start pm2-ProfitTrailer.json

## Configuration

Is this needed? Will upload later if needed.

## Log files/console output

 
Is this needed? Will upload later if needed.

**Comment by taniman** [comment]
Sorry, but the wiki is incorrect in this case. 
If you want to get rid of your testdata when switching to live you can either.

1. in testmode press the reset button, then switch to live.
2. stop the bot. delete profittrailerdata.json and its backup and start the live bot

These are your options. The bot will not delete log data without your consent. As this causes other kinds of discussions

**Comment by m4xson** [comment]
OK. Maybe test mode should run a seperate set of log files in that case.
Please update the wiki.

**Comment by m4xson** [comment]
In fact if you're updating the wiki for test mode I would tell users to run test mode from a different installation folder to your live bot. That would prevent people from having the problems I had. My VPS had to be deleted and re-installed.
