### ISSUE TITLE
GUI Config should default to Active

### ISSUE THREAD

**Issue by jadiesel** [taniman/profit-trailer#2039]
I'm gonna call this a fix, not an enhancement.

If I am in editing configs, and close the bot, then come back the next day and open her up - the config displaying is defaulting to the last one loaded in the editor, not the active config.

This is dangerous, especially when there is no easy way to tell if you are looking at the active config or not.  Some huge indicator that lets you know active config vs non active config is loaded.

I did have a gui enhancement for moving the config switcher to the config screen (rather than buried in the side menu)... but I think we need a visual 'this is active, this is not active"

Hell, we may need a way to tell if another bot is USING that config as well. Cause danger.

But please, default load to active if possible.

**Comment by XannyD** [comment]
I believe that an indicator would be the best option. I have a feeling that defaulting to active when you leave and come back would be troublesome as well. If someone is editing a non active config and has to switch to it every time that they reentered Config, it seems like it would be a nuisance. An in Config indicator would be nice.

**Comment by SgtBatten** [comment]
How big an indicator do you need. There are already two visual signs you are in an active config or not.

1. The name matches the active config at the top right.

2 the hotconfig/trashcan icon is visible. Hotconfig means active. Trashcan means not active.

**Comment by m4xson** [comment]
I would say we need a slightly bigger indicator. It's confusing to be able to edit a config you are not currently running as we couldn't do that in the GUI before. It needs to be really obvious.

**Comment by atomize** [comment]
So I actually put in this as a feature at request that the bot refresh to where you were previously. So we would need some sort of consensus on this, but I see why you say it may be dangerous. The main take away from this imho is what @jadiesel mentions about not knowing if another bot is running a configuration that you are editing. This is another issue though.

**Comment by m4xson** [comment]
"Hell, we may need a way to tell if another bot is USING that config as well. Cause danger."
Yes I agree with this point strongly.

**Comment by djcrypto75** [comment]
Added "Active Config" when you are working on the active one. Thats all the changes we will add on this one :)
