### ISSUE TITLE
An incorrect result in calculating the profit (P%)

### ISSUE THREAD

**Issue by Quillian** [taniman/profit-trailer#2042]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.4

 
Exchange:
- [ ] Bittrex
- [х] Binance
- [ ] Poloniex

 
Market:
- [х] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [х] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior
I noticed an incorrect results in calculating the profit (P%, "Sells") in some deals. 
Last ones: 

8/19/2018 04:43 PM (0D) | ADABTC         P% = 0.69%, have to be 0.56%

8/19/2018 00:39 AM (-1D) | NEOBTC        P% = 0.79%, have to be 0.48%

8/18/2018 12:20 PM (-2D) | ZILBTC        P% =1.36%, have to be 1.18%

## Steps to Reproduce

1.
2.
3.
4.

## Configuration

ProfitTrailerData.json + logs I will send in privat message on discord

**Comment by taniman** [comment]
[ProfitTrailerData.txt](https://github.com/taniman/profit-trailer/files/2301926/ProfitTrailerData.txt)
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2301927/ProfitTrailer.log)

**Comment by taniman** [comment]
It's a display issue. As you are using orderbook profit calculation. So the orderbook profit % should have been displayed instead of the profit. 

Fixed in 2.1.6, but those wrong logs will remain wrong
