### ISSUE TITLE
Manual buy in DCA does not work as expected

### ISSUE THREAD

**Issue by xandorlv** [taniman/profit-trailer#2044]
## ProfitTrailer info
Version: PT Ver:  2.1.5

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [x] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version) Ubuntu 17.10 (GNU/Linux 3.21.1-openvz-042stab131.1-amd64 x86_64)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
When I press manual buy in DCA I expect PT to buy amount based on DEFAULT_DCA_Buy_Percentage defined irrespective if defined strategies are true or not

## Current Behavior
PT does not buy anything (reproduced on ICXBNB and ZILBNB pairs).

## Steps to Reproduce
See: <img width="1594" alt="screen shot 2018-08-22 at 01 20 53" src="https://user-images.githubusercontent.com/17331835/44432339-55f5de00-a5aa-11e8-88c2-a11cdd622255.png">
I have 15 DCAs and total amount of ICX = 505.8.

Here is my DCA config: 
[BNB_Setting-DCA.txt](https://github.com/taniman/profit-trailer/files/2308253/BNB_Setting-DCA.txt)

When I pressed 'Buy' button I got following in log:
`1|profit-t | 2018-08-21 22:21 +00:00: 2018-08-21 22:21:32 INFO ActionController - Manual buy ICXBNB
1|profit-t | 2018-08-21 22:21:32 INFO ActionController - Manual buy ICXBNB - INSUFFICIENT BALANCE`

Based on setting DCA 16 is 6.25, so PT should have tried to buy 31.5625 icx which is about ±2 bnb.
My available balance is ±30 bnb.

**Comment by taniman** [comment]
Post a screenshot of your monitoring screen showing all your balance information and also the reserve balance information

**Comment by xandorlv** [comment]
Here you go:
<img width="1659" alt="screen shot 2018-08-22 at 11 46 36" src="https://user-images.githubusercontent.com/17331835/44453158-13abbb80-a601-11e8-82f8-378b8bdd78c3.png">
I have keep balances set to 0 in settings.

**Comment by taniman** [comment]
Fixed in 2.1.6

**Comment by xandorlv** [comment]
@taniman tried to manual buy in DCA with 2.1.6:
1|profit-t | 2018-08-23 12:33 +00:00: 2018-08-23 12:33:50 ERROR ProfitTrailerService - {"CODE":-1111,"MSG":"PRECISION IS OVER THE MAXIMUM DEFINED FOR THIS ASSET."}

Any idea?

**Comment by taniman** [comment]
Yes. Seems like manual buys on binance are broken now in 2.1.6 due to rounding issues. 
I will fix this in 2.1.7. So you better roll back if manual buys were working for you before.

**Comment by xandorlv** [comment]
@taniman would you mind unrelease 2.1.6 making 2.1.5 as latest (https://api.github.com/repos/taniman/profit-trailer/releases/latest)? :) also after an upgrade in BTC basecoin bot it somehow oddly work, and I do not see all the coins which I have although they are enabled.

**Comment by taniman** [comment]
sorry no, that won't happen. There is nothing wrong with 2.1.6. A bug got in, yes. 
But that's manual buys. The bot it self is buying and selling without any issues.
There are bigger things that got fixed in here

Not sure about this coins you are not seeing but that's something for support until it is defined to be a bug.

**Comment by xandorlv** [comment]
Confirm fix in 2.1.7.
Thanks!
