### ISSUE TITLE
PT does not always fully buy or sell in DCA

### ISSUE THREAD

**Issue by xandorlv** [taniman/profit-trailer#2045]
## ProfitTrailer info
Version: 2.1.5

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [x] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version) Ubuntu 17.10 (GNU/Linux 3.21.1-openvz-042stab131.1-amd64 x86_64)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Either manually or automatically based on strategy I expect PT to buy or see exactly the amount defined in configs/available amount. If for some reason for a defined price there are no bid orders to execute it should still buy full amount from higher price orders and in buy or sell log show average buy/sell price

## Current Behavior
Sometimes (no clear reproducible scenario) does partial buy / sell

## Steps to Reproduce
No special steps performed

## Configuration
[BNB_Setting-INDICATORS.txt](https://github.com/taniman/profit-trailer/files/2308275/BNB_Setting-INDICATORS.txt)
[BNB_Setting-DCA.txt](https://github.com/taniman/profit-trailer/files/2308276/BNB_Setting-DCA.txt)
[BNB_Setting-PAIRS.txt](https://github.com/taniman/profit-trailer/files/2308277/BNB_Setting-PAIRS.txt)

## Log files/console output

Log indicate non-zero amount unfilled, but the reason is not written

Unsuccessful sell:
`2018-08-16 08:43:58 INFO ProfitTrailerService - Sell order for PPTBTC sold amount 262.26000000 for price 0.00061060 -- {"orderNumber":"24667945","error":"","amountUnfilled":119.34,"resultingTrades":[{"date":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":8,"minute":43,"second":57,"nano":0}},"rate":0.00061060,"amount":142.92000000,"total":0.1601359560000000,"fee":0,"orderNumber":"24667945","type":"sell"}],"done":false}
2018-08-16 08:44:04 INFO ProfitTrailerService - Get order information -- {"orderNumber":"24667945","error":"","amountUnfilled":119.34,"resultingTrades":[{"date":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":8,"minute":43,"second":57,"nano":0}},"rate":0.00061060,"amount":142.92000000,"total":0.1601359560000000,"fee":0,"orderNumber":"24667945","type":"sell"}],"done":true}`

Unsuccessful buy:
`2018-08-21 15:53:42 INFO ProfitTrailerService - Buy order for BNBBTC -- {"orderNumber":"75201884","error":"","amountUnfilled":4.94,"resultingTrades":[{"date":{"date":{"year":2018,"month":8,"day":21},"time":{"hour":15,"minute":53,"second":40,"nano":0}},"rate":0.00148000,"amount":0.01000000,"total":0.0073260000000000,"fee":0,"orderNumber":"75201884","type":"buy"}],"done":false}
2018-08-21 15:53:47 INFO ProfitTrailerService - Get order information -- {"orderNumber":"75201884","error":"","amountUnfilled":4.94,"resultingTrades":[{"date":{"date":{"year":2018,"month":8,"day":21},"time":{"hour":15,"minute":53,"second":40,"nano":0}},"rate":0.00148000,"amount":0.01000000,"total":0.0073260000000000,"fee":0,"orderNumber":"75201884","type":"buy"}],"done":true}`

**Comment by xandorlv** [comment]
[BNB_Setting-INDICATORS-2.txt](https://github.com/taniman/profit-trailer/files/2309533/BNB_Setting-INDICATORS-2.txt)
[BNB_Setting-DCA-2.txt](https://github.com/taniman/profit-trailer/files/2309534/BNB_Setting-DCA-2.txt)
[BNB_Setting-PAIRS-2.txt](https://github.com/taniman/profit-trailer/files/2309535/BNB_Setting-PAIRS-2.txt)

**Comment by taniman** [comment]
There is a fix in 2.1.6 that may help a little with the manual buys.
Manual sell has always been that it retries for the same price to sell. Cause it's a limit sell. and can certainly happen that it does not manage to sell all.
We only retry 3 times when doing a manual sell for the price you wanted at the moment you clicked the button. It's not a panic sell button.

**Comment by xandorlv** [comment]
I see, so if I want to get rid, I use panic sell. tnx.
P.S. please do not create button for panic sell - too dangerous ;)
