### ISSUE TITLE
Sold 2 pending orders at  22/08/2018 1:30 UTC, but PT shows zero profit for today and yesterday

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer#2046]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

Sold 2 pending orders at 22/08/2018 1:30 UTC, but PT shows zero profit for today and yesterday

My computer time is UTC -3, and my bots are UTC,  that's very important

## ProfitTrailer info
Version:
 2.1.5
 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x ] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

![image](https://user-images.githubusercontent.com/38858258/44455139-af263780-a5d3-11e8-9f83-b19637c2de1b.png)

This next image shows telegram bot, time in Brazil is UTC -3, so it isn't august 21, it is august 22

![image](https://user-images.githubusercontent.com/38858258/44455215-dd0b7c00-a5d3-11e8-8914-9f6ceda65c84.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/38858258/44456442-e9450880-a5d6-11e8-9a19-b100f32f99f3.png)

## Steps to Reproduce

1. Just use spanish cross V3 strategy, let it have a pending order, and let the pending order being sold, it  should sell only at 1.25%, which is the strategy gain 
2.
3.
4.

## Configuration

[SpanCrossV3_arthur-DCA (1).txt](https://github.com/taniman/profit-trailer/files/2309666/SpanCrossV3_arthur-DCA.1.txt)
[SpanCrossV3_arthur-INDICATORS (1).txt](https://github.com/taniman/profit-trailer/files/2309667/SpanCrossV3_arthur-INDICATORS.1.txt)
[SpanCrossV3_arthur-PAIRS (1).txt](https://github.com/taniman/profit-trailer/files/2309668/SpanCrossV3_arthur-PAIRS.1.txt)

## Log files/console output

 

[PTLogAndDataJSON.zip](https://github.com/taniman/profit-trailer/files/2309734/PTLogAndDataJSON.zip)

**Comment by taniman** [comment]
If you look at the sales log, you can see PT is saying that the pending orders were sold on 20-08. So that explains why it does not show in today and yesterday.

Are you sure the sell happened on the 21st?

**Comment by taniman** [comment]
Fixed in 2.1.6
