### ISSUE TITLE
Test Mode: Pairs showing incorrect profit %

### ISSUE THREAD

**Issue by cryptocoyns** [taniman/profit-trailer#2048]
## ProfitTrailer info
Version: 2.1.7

 
Exchange:
- [X ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [X ] Mac OS

## Expected Behavior
Test bot was showing a profit when it should have shown a loss.

## Current Behavior
Test bot was running on Bittrex running 2.1.7 released today.
Pair showed up as being in profit but when it sold off it sold for a loss.
The bought price was the same as the sale price so with fees it should have been showing as a loss.

## Steps to Reproduce

1. Run a test bot on Bittrex
2. Load 2.1.7 release
3. Let it trade using any settings
4. Note the pairs in profits to see if they really are being shown correctly

## Log files/console output

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2317144/ProfitTrailer.log)

[ProfitTrailerData.json.zip](https://github.com/taniman/profit-trailer/files/2317149/ProfitTrailerData.json.zip)

**Comment by mhardy85** [comment]
Attaching log/json/ordersettings for another example, this one on a Binance test bot
[PT.zip](https://github.com/taniman/profit-trailer/files/2321170/PT.zip)
