### ISSUE TITLE
Buying even with 2 pairs on DCA and max_trading_pairs = 2

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer#2049]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.8

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ x] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Should not buy anything, it had 2 coins at DCA, and max_trading_pairs = 2,
## Current Behavior

It simply bought sub, at least sold it, and ironically SUB shows "MAX PAIRS" at possible buy log now
 You will see with logs and screenshots that nothing were sold to lower pair number to less than 2 ind order to SUB can be bought

![image](https://user-images.githubusercontent.com/38858258/44627450-af407300-a904-11e8-88b2-28be91d974ff.png)

![image](https://user-images.githubusercontent.com/38858258/44627455-c1221600-a904-11e8-920f-1ce338c1423a.png)

![image](https://user-images.githubusercontent.com/38858258/44627457-ca12e780-a904-11e8-8e86-5ed3fc603fd3.png)

## Possible Solution

I don't know

## Steps to Reproduce

1. Use my configs and wait the bug to happen
2.
3.
4.

## Configuration

[Spread_master_bin_V2-INDICATORS (2).txt](https://github.com/taniman/profit-trailer/files/2321441/Spread_master_bin_V2-INDICATORS.2.txt)
[Spread_master_bin_V2-PAIRS (2).txt](https://github.com/taniman/profit-trailer/files/2321442/Spread_master_bin_V2-PAIRS.2.txt)
[Spread_master_bin_V2-DCA (2).txt](https://github.com/taniman/profit-trailer/files/2321443/Spread_master_bin_V2-DCA.2.txt)

## Log files/console output

 

![image](https://user-images.githubusercontent.com/38858258/44627492-61783a80-a905-11e8-88f6-7a6489a2f70d.png)
![image](https://user-images.githubusercontent.com/38858258/44627500-78b72800-a905-11e8-9e19-2a0801667ada.png)
![image](https://user-images.githubusercontent.com/38858258/44627505-82409000-a905-11e8-98ea-d3ed07257b62.png)

[logs.zip](https://github.com/taniman/profit-trailer/files/2321447/logs.zip)

**Comment by arthurengeletrica** [comment]
The problem is that when the volume bought become less valuable than dust, it goes to dust list, and PT thinks I have less coins, and then try to buy more!

**Comment by taniman** [comment]
When a coin value drops below the exchange min buy amount it goes into dust log. Which frees up the bot to buy this coin again. On this next buy the 2 values will be merged
