### ISSUE TITLE
exporting of log exports everything including properties in random order

### ISSUE THREAD

**Issue by jpfl** [taniman/profit-trailer#2051]
## ProfitTrailer info
Version: 2.1.9

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [10 ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

when showing logs in GUI and clicking the export button logs should be exported and nothing else.

## Current Behavior

it exports the 3 property files and the log file in random order. each time different.

## Troubleshooting

bot restart and reboot

## Steps to Reproduce

1. see above
2.
3.
4.

**Comment by djcrypto75** [comment]
fixed in last gui build
