### ISSUE TITLE
Cancel Order

### ISSUE THREAD

**Issue by Neous1** [taniman/profit-trailer#2052]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When User cancels order on exchange , order should appear in the PT Pairs log.
## Current Behavior

Cancel order appears in the Pairs Log but this notification appears in console.
![image](https://user-images.githubusercontent.com/22582499/44763201-1da94f00-ab18-11e8-8d24-3efdea64401f.png)

## Troubleshooting

Placed a pending order in Binance and the message went away
## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
update to 2.1.9 fixes this error
