### ISSUE TITLE
PBL BSL displays scientific notation

### ISSUE THREAD

**Issue by cryptocoyns** [taniman/profit-trailer#2053]
## ProfitTrailer info
Version:

 
Exchange:
- [X ] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ X] Mac OS

## Expected Behavior
Display of MACD should show decimal notation

## Current Behavior
Display of MACD in PBL BSL is showing scientific notation

## Steps to Reproduce
1. Create MACD settings as follows
DEFAULT_B_buy_strategy_label = DOABROWNIEMACD
DEFAULT_B_buy_strategy = MACD
DEFAULT_B_buy_value = 0.000000001
DEFAULT_B_buy_value_limit = 0.000000200
2.
3.
4.

## Log files/console output

 

https://media.discordapp.net/attachments/400383734777511936/484541729349959680/unknown.png?width=1080&height=152

**Comment by cryptocoyns** [comment]
Elroy advised DJ already on it

**Comment by djcrypto75** [comment]
Correct :)
