### ISSUE TITLE
Profit % is positive, and profit in BTC is negative

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer#2056]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.9

 
Exchange:
- [ x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ x] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

![image](https://user-images.githubusercontent.com/38858258/44932403-b7047b00-ad3b-11e8-8f4b-1c840641e2bd.png)

The sale of DGB on above screenshot should give consistent values, posoitive profit% positive btc, and positive USD profit

## Current Behavior

Profit % is positive, BTC prfoit is negative, USD profit is negative

## Troubleshooting

No

## Possible Solution

I don't know

## Steps to Reproduce

1. Buy DGB with given config
2. Wait DGB to be sold with given config 
3. Expect the error, miscalculation or whatever
4.

## Configuration

[Spread_Master_Bit-DCA.txt](https://github.com/taniman/profit-trailer/files/2341354/Spread_Master_Bit-DCA.txt)
[Spread_Master_Bit-INDICATORS.txt](https://github.com/taniman/profit-trailer/files/2341355/Spread_Master_Bit-INDICATORS.txt)
[Spread_Master_Bit-PAIRS.txt](https://github.com/taniman/profit-trailer/files/2341356/Spread_Master_Bit-PAIRS.txt)

## Log files/console output

 

--------------- ORDER HISTORY FOR DGB -----------

from August to Setember:

![image](https://user-images.githubusercontent.com/38858258/44945375-769a1100-adbe-11e8-8464-31dfe467e08e.png)

I guess this screenshot will make your life easier

![image](https://user-images.githubusercontent.com/38858258/44945427-b1e90f80-adbf-11e8-8062-8b290b97799a.png)

Isn't Bittrex fees 0.25% for taker and maker? Thus total fees are 0.5%

-----------------------------------------------------------

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2341347/ProfitTrailer.log)
[ProfitTrailerData.json..zip](https://github.com/taniman/profit-trailer/files/2341350/ProfitTrailerData.json.zip)

**Comment by taniman** [comment]
I need to see the exact information the exchange says this coin sold for. As something is not correct. As the actual sell value is not matching the sell value the bot send
