### ISSUE TITLE
PT is not buying any Pairs only DCA? Using Binance 

### ISSUE THREAD

**Issue by Joshguys** [taniman/profit-trailer#2057]

**Comment by Joshguys** [comment]
Not sure if I’m using this correctly. As it is all new to me. My PT bot seems to be running ok. Has all the proper heartbeats but for some reason theres no Pairs in my log. Only DCA.  If I’m not mistakin doesn’t a Pair have to be purchased first before it can DCA. Not just automatically go into DCA first?

**Comment by taniman** [comment]
These type of question indeed need to be asked in our discord support server or you can create a support ticket. github is only for reporting actual bugs.

coins will not be displayed in PAIRS if you have DEFAULT_DCA_enabled = true.
This means that after buying coins will go directly under DCA tab. 
Only coins in DCA tab are eligible for DCA.

If a coin is in PAIRS tab it will not DCA.

Try going through the wiki a bit more and check out beginners channel on discord.
