### ISSUE TITLE
loading new settings does not work if more than 7 settings are loaded

### ISSUE THREAD

**Issue by jpfl** [taniman/profit-trailer#2058]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.10

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ x] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ 10] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

http://localhost:8081/setup#publicConfig

loading public setting via pulldown menu

## Current Behavior

I have currently 7 stored settings and it won;t allow me to load any more (public) settings:

getting: "Public setting public-ProfitTrailer_xxxxx_vX could not be copied"

no matter which public setting I chose.

In case there is a limit of maximum 7 settings then take this as a suggestion to allow more stored settings. if not then please fix the bug.

## Steps to Reproduce

1.  gear icon
2. settings
3. setup
4. public
5. select existing setting
5. pick a setting
6. enter a unique name
7. load your settings

error: e.g. "Public setting public-ProfitTrailer_ElToro-V3 could not be copied"

**Comment by jadiesel** [comment]
Config settings are limited to 7. 
Make room for another by deleting one.
This is not a bug.
