### ISSUE TITLE
start balance in test mode with usd base currency pairs shows always 1,000.000

### ISSUE THREAD

**Issue by jpfl** [taniman/profit-trailer#2059]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

no matter what amount I specify in the pairs.config GUI for:

market = USDT

start_balance = 100
or
start_balance = 1000
or
start_balance = 10000

it always shows:

1,000.000 as a starting balance.

this was tried only in test mode so far with usd base currency on a test bot I just set up to test some new configs before putting them "live".

application.properties:
server.currency = USD
server.test_mode = true

bot was restarted after changing the starting amount and still showed 1,000.000

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [x ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [10 ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

BAL: 1,000.000 shown in GUI should change accordingly to start balance amount specified in pairs.config

## Troubleshooting

restarting bot, trying various start balance amounts

also tried 

start_balance = 100

in hot config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
You cannot change your balance once the test mode bot has a balance. As this balance is used by test mode as your actual balance.
If you would like to change your test mode balance.

Change start_balance
then press the reset button on settings menu
and wait 5 minutes for the bot to start trading again.

FYI, this is not a bug and should have been handled in support
