### ISSUE TITLE
losing price between pending and pairs

### ISSUE THREAD

**Issue by BlitzKC** [taniman/profit-trailer#2060]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by BlitzKC** [comment]
I have the exact same setting in my test bot and this did not occur if that helps.

**Comment by taniman** [comment]
I am assuming this is the issue we looked at together. So it's fixed now. in 2.1.11
