### ISSUE TITLE
Excel Output Combining Coin & 24h Change in One Column

### ISSUE THREAD

**Issue by mhardy85** [taniman/profit-trailer#2061]
Spreadsheet exports for PBL, Pairs, DCA, Pending, & Dust combine the coin name and 24 hour change in one column rather than two separate columns.

## ProfitTrailer info
Version: 2.1.11-B1

## Expected Behavior
Coin name should be exported in a column on it's own. It works correctly for the Buy and Sales logs as they don't contain any other info in the same table cell.

## Steps to Reproduce

1. Export data from PBL, Pairs, DCA, Pending, or Dust
2. Check the Coin column

![image](https://user-images.githubusercontent.com/33883642/45002219-71d58880-af89-11e8-8327-642bc29ff2a2.png)

**Comment by djcrypto75** [comment]
fixed in last GUI build
