### ISSUE TITLE
pairs losing bought price

### ISSUE THREAD

**Issue by PricelessTradings** [taniman/profit-trailer#2062]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [10 ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Not enough description.

**Comment by hkhan24** [comment]
![image](https://user-images.githubusercontent.com/6436539/45926870-612d8800-bf21-11e8-9e84-6a70331bf3a5.png)

Happening to me a lot recently. Bittrex, Ubuntu PT version 2.1.12

**Comment by hkhan24** [comment]
Those empty pairs are probably the cause of this:

![image](https://user-images.githubusercontent.com/6436539/45926883-a2259c80-bf21-11e8-8b91-c835eee39400.png)
