### ISSUE TITLE
ORDERBOOK LOW with DEFAULT_min_orderbook_volume_percentage = 0

### ISSUE THREAD

**Issue by CryptoScalpel** [taniman/profit-trailer#2063]
I'm running in Testmode on P T Ver:  2.1.10 Market:  BINANCE BTC 

But I pretty much can't buy anything with a starting balance of 10 BTC because of the ORDERBOOK LOW error. Isn't PT supposed to execute partial orders if the full volume isn't in the order book?

I also put this in as support ticket #129005

Thanks
Ruben

**Comment by taniman** [comment]
I suggest you handle this trough a ticket indeed or through support on discord. As I highly doubt it is a bug. So first support needs to confirm that something is wrong and then you can feel free to reopen this ticket if it is a bug. 
We do not offer support on github
