### ISSUE TITLE
combined_cancel_pending_trigger also cancels pending BUY orders (after restart)

### ISSUE THREAD

**Issue by SjaaLom** [taniman/profit-trailer#2064]
## ProfitTrailer info
Version: 2.1.11

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64))
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
I had an open position of a specific coin @18 sats and three pending buy orders at 18, 17 and 16 sats.
I would expect that the pending BUY orders be left alone by PT, because they are waiting to be filled

## Current Behavior
After a restart PT cancels my pending buy orders, removing them from the orderbook at that price level. This causes me to lose my "place in line", because the orderbook is packed.

## Troubleshooting
I have experienced this before (< v2.1.11), but never bothered to troubleshoot what happened. This time I think that my DEFAULT_combined_cancel_pending_trigger (0.01) is the culprit and is causing PT to cancel my outstanding orders before they are filled.
I have changed the DEFAULT_combined_cancel_pending_trigger to 0, hoping to avoid these premature cancels.

## Possible Solution
As said, I think setting DEFAULT_combined_cancel_pending_trigger to 0 (or removing it from the config) is a probable workaround for this problem.
A real solution would be a fix where PT checks the orderside (buy/sell) of the order and only cancels the order when it is a SELL order.

## Steps to Reproduce
1. Configure DEFAULT_combined_cancel_pending_trigger = 0.01
2. Buy some HOTBTC (currently at 17) and wait for the order to fill
3. Create a pending buy order for HOTBTC at 10 for the same amount or more. The combined pending profit should be > DEFAULT_combined_cancel_pending_trigger
4. Now restart the bot
5. After the restart, the bot will cancel the pending buy order

## Configuration
DEFAULT_combined_cancel_pending_trigger = 0.01
DEFAULT_B_sell_strategy = GAIN
HOT_B_sell_value = 3
HOT_trailing_profit = 0
HOT_trailing_profit_type = DEFAULT

## Log files/console output
0|pt-seven | 2018-09-11 12:09 +02:00: 2018-09-11 12:09:40 INFO Application - PT Version: 2.1.11
0|pt-seven | 2018-09-11 12:09 +02:00: 2018-09-11 12:09:40 INFO Application - Java Version: 1.8.0_181
0|pt-seven | 2018-09-11 12:09 +02:00: 2018-09-11 12:09:50 INFO Application$a - Server initialized with port: 8081
0|pt-seven | 2018-09-11 12:09 +02:00: 2018-09-11 12:09:59 INFO ProfitTrailerService - Cache Heartbeat
0|pt-seven | 2018-09-11 12:10 +02:00: 2018-09-11 12:10:00 INFO ProfitTrailerService - PAIRS Heartbeat
0|pt-seven | 2018-09-11 12:10 +02:00: 2018-09-11 12:10:00 INFO ProfitTrailerService - DCA Heartbeat
0|pt-seven | 2018-09-11 12:10 +02:00: 2018-09-11 12:10:14 INFO ProfitTrailerService - Cancelling HOTBTC order 1703573, data {"success":1}
0|pt-seven | 2018-09-11 12:10:14 INFO StrategyRunnerHelper - Storing cancelled data {"currencyPair":"HOTBTC","lastBoughtDate":{"date":{"year":2018,"month":9,"day":11},"time":{"hour":10,"minute":10,"second":14,"nano":851000000}},"lastOrderId":"","lastAveragePrice":0E-8,"boughtPrice":0E-8,"boughtPriceOrderId":"","lastTotalAmount":0E-8,"lastRealTotalAmount":0E-8,"pendingAmount":173585.00000000,"pendingAvgPrice":9.876543209876542E-8,"pendingLastAvailableBalance":102312.00000000,"validUntil":{"date":{"year":2018,"month":9,"day":11},"time":{"hour":10,"minute":11,"second":14,"nano":851000000}},"overridden":false}

**Comment by taniman** [comment]
Fix so only sell orders are cancelled
