### ISSUE TITLE
Pending order sales not reported sometimes

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#2065]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x ] Ubuntu (please specify version)
- [] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

PT should report a sale in SELL log when a sale occured in pending order.

## Current Behavior

PT sometimes doesnt report  a sale from pending orders. I've checked from exchange a sale is occured but PT didn't report it. Also I could see the pending order were still on PT for a while after the order executed on exchange.

## Possible Solution

I've realized PT is checking BID price to check if pending orders are executed. I think for pending orders PT should check ASK prices.

## Steps to Reproduce

1.  Create a setup with pending order.
2.  If current ask price meets your sell order,  order is executed as expected. For my case bid price didn't meet with exchange price thats why PT were not able to report it as a sale.
3.
4.

## Log files/console output

I can provide any other data if requested.

[ptlog-16092018-115234.txt](https://github.com/taniman/profit-trailer/files/2386425/ptlog-16092018-115234.txt)

**Comment by mightysoul** [comment]
Here is the exchange sale not reported on PT.

![photo5832524794824863223](https://user-images.githubusercontent.com/37293938/45594706-c58f9b00-b9a7-11e8-90b5-1be0e3f7088b.jpg)

**Comment by taniman** [comment]
PT does not use bid/ask prices to put pending orders in the sales log. It uses the order number. We only have the pending order if it's the bot that created the pending order. 

So something happened to the order number we stored and the bot did not find the order when it got sold. This is an unforeseen event but there is not much we can do about that. 
Pending orders being stored in the sales log is fairly new and is not a 100% guarantee thing as most of the selling is handled on the exchange. 

I will keep my eye open but can't promise a solution. Too many moving parts
