### ISSUE TITLE
Bot TESTMode sync config to Real Mode with both share the "same config name"/"config Profile"

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer#2068]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [x] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The test mode configuration reflects to the other bot that is running in real mode and the expected is it's not synchronized at all.
## Current Behavior

If you have two instances of BOT running the same configuration sample_name: "ConfigSeptember" and the first one is in test mode and another one running in real mode.
The test mode settings/profile reflects for the second BOT that is in real mode.
## Steps to Reproduce

1.Just keep changing some parameters after a while synchronism takes place.
2.
3.
4.

**Comment by taniman** [comment]
This happens because configurations or attached to your license and not to a bot. So you should be sure to use different configs for different bots. 

Please consult on discord with support before creating incorrect bug reports
