### ISSUE TITLE
BlackList removes the pair even when it is in trade.

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer#2069]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [X] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The expected behavior is that the pair should only leave the trade after the purchases / sales are completed either manually or automatically.
## Current Behavior

If you have a pair that is in trade and you put it in blacklist the pair disappears from the pairs-log or dca-log list and the values(bought) get stuck in the exchange because the transaction is still active.
## Possible Solution

Regardless of whether the pair is blacklisted, it must be removed from the pairs-log or dca-log locations after the trade ends manually or automatically
## Steps to Reproduce

1.Choose a pair that is pairs-log or dca-log
2.Then add it to the blacklist.
3.The pair is no longer anywhere in BOT.
But the pair is in the exchange with paralyzed value because the BOT does not read it.

**Comment by taniman** [comment]
This is not how the bot works. A blacklist is a blacklist.
When people blacklist a coin they sometimes want to keep it and don't want the bot to sell it or see it. 

So there is nothing wrong with the behavior.

If you want the bot to sell a coin and not buy new ones. You put the coin in sell only mode. That's the best you can do in this situation. 
Or you create a manual sell order for the coin on your exchange and afterwards you blacklist it.
