### ISSUE TITLE
"Download Config Files" corrupted settings

### ISSUE THREAD

**Issue by twig123** [taniman/profit-trailer#2070]
When selecting "Download Config Files" from the Config screen, the bot re-filters/changes the config and re-removes duplicate settings that are commented out.

For example:
If these comments are in the bot's actual saved config:

> #DEFAULT_B_buy_strategy_label = LONGTERMTREND
> #DEFAULT_B_buy_strategy = EMACROSS
> #DEFAULT_B_buy_value = 0.01
> #DEFAULT_B_buy_value_limit = 5

it results in the downloaded config file option re-filtering the settings and saving the file with this contents instead:

> LONGTERMTREND
> EMACROSS
> 0.01
> 5

## ProfitTrailer info
Version: 2.1.12

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [x] Windows (Server 2016)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Selecting "Download Config Files" should result in the downloaded files containing identical settings as shown in the bot.

## Current Behavior
Selecting "Download Config Files", the downloaded file gets modified/filtered to remove duplicate lines, even if those duplicates are commented out.

## Troubleshooting
Saved config in PT, clicked to Download Config Files and verified that the downloaded file is altered and isn't an identical match to the bot settings.

## Possible Solution
All filtering for duplicate settings is already performed when you save the config settings in the bot. There shouldn't be a need to perform additional checks/filtering for duplicates when generating the Download Config Files.

## Steps to Reproduce
1. Add "duplicate", commented out, settings to a config and save it
2. Use the Download Config Files option to download the settings to a text file
3. Observe that the "duplicate" commented out settings are partially removed.

## Configuration
Configuration with commented out settings, such as the Public "GOLDEN CROSS" settings.

## Log files/console output
N/A

**Comment by djcrypto75** [comment]
fixed in last gui build
