### ISSUE TITLE
Bot has a memory error and crashes

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer#2071]
## ProfitTrailer info
Version: 2.1.10, 2.1.9 and possibly earlier. I keep hoping a new release will have fixed it.

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [x ] Other linux distro : Linkuphost VPS, not sure the version of Linux
- [ ] Mac OS

## Expected Behavior
PT runs smoothly

## Current Behavior
Roughly once a week PT crashes. I get this in telegram: 'Binance Bot - It's been a while since the tickers updated, try restarting your bot'
The monitor screen either can't be accessed or has no data.
Sometimes I can't open a command window to restart the bot with Winscp and I have to get Linkuphost to restart the VPS. Sometimes I can open a command window and restart the bot.

## Troubleshooting
I contacted support previously and it's a possible memory problem. I restarted the bot afresh and it's been OK for some days, now it's crashed again.

## Possible Solution

Memory leak? Don't know.

## Steps to Reproduce

1. Run PT for some days.
2. Nothing seems out of the ordinary then it has this error.
3.
4.

## Configuration

[JK4_OldFaithfulStoploss-PAIRS.txt](https://github.com/taniman/profit-trailer/files/2407522/JK4_OldFaithfulStoploss-PAIRS.txt)
[JK4_OldFaithfulStoploss-DCA.txt](https://github.com/taniman/profit-trailer/files/2407523/JK4_OldFaithfulStoploss-DCA.txt)
[JK4_OldFaithfulStoploss-INDICATORS.txt](https://github.com/taniman/profit-trailer/files/2407524/JK4_OldFaithfulStoploss-INDICATORS.txt)

## Log files/console output

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2407518/ProfitTrailer.log)

 (If only I could restart it)

**Comment by taniman** [comment]
If there is a memory leak you will see all over in your log file that the bot ran out of memory.
The problem you are experiencing is on your VPS machine and cannot be solved on our side.

To me it sounds like your network connection resources are depleting on your machine. Causing this to happen.

I found this is your log.
```We could not create a session. Please check your internet connection```

so definitely something wrong with connections on your machine causing this to happen. Would also explain why you could not connect to your VPS when this happened.

**Comment by m4xson** [comment]
So this is a Linkuphost problem, not a PT problem. I'm not sure I can get Linkuphost to agree that they are causing this issue and fix it so I'm going to switch to another VPS provider.
