### ISSUE TITLE
Still problems with Bittrex api

### ISSUE THREAD

**Issue by bluefuzz** [taniman/profit-trailer#2072]
I'm still having problems with Bittrex pending orders - both buying and cancelling apparently

## ProfitTrailer info
Version: 2.1.12

 
Exchange:
- [X] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [X] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

Log file attached:
[bittrex.log](https://github.com/taniman/profit-trailer/files/2407556/bittrex.log)

**Comment by taniman** [comment]
Please contact PT-Elroy on discord
