### ISSUE TITLE
Feature request: different DCA buy times

### ISSUE THREAD

**Issue by swanfield1979** [taniman/profit-trailer#2074]
I would like to use different strats per DCA level. So like this:

DEFAULT_DCA_A_buy_strategy_label_1 = RSI900
DEFAULT_DCA_A_buy_strategy_1 = RSI

DEFAULT_DCA_A_buy_strategy_label_2 = RSI1800
DEFAULT_DCA_A_buy_strategy_2 = RSI

DEFAULT_DCA_A_buy_strategy_label_3 = RSI3600
DEFAULT_DCA_A_buy_strategy_3 = RSI

Is this possible to add to PT?

Why I would like to see this is to get a better bottem on DCA levels when the price drops. This way I can filter more on overbought on multiple timeframes.

**Comment by taniman** [comment]
This is the bug report github. Please create this on the feature request github. 
https://github.com/taniman/profit-trailer-enhancements
