### ISSUE TITLE
new feature request: new type of EMACROSS highly profitable

### ISSUE THREAD

**Issue by pablitoamigu** [taniman/profit-trailer#2080]
Since classic emacross cant buy in the cross or in "candle 0" many profitable healthy pumps are lost becouse are seen in 1hr candle in the first or second minute after the cross so its imposible to catch big movements with emacross. The problem is that it buys 1 candle or 1hr later invalidating its porpuse and leaving obsolete the main porpuse of high reward/risk of big crossings.

My request is a new emacross strategy that buys in candle 0 and doesnt wait a entire candle.

Thank you

**Comment by pablitoamigu** [comment]
to add an idea firstly it could use previous candle information of emacross to build the lines and secondly to have realtime crossing would use tick price data or smallest posible independent of main candle size and convert to correspondent timeframe to calculate the cross in the current candle on the fly "in memory".

**Comment by jadiesel** [comment]
Does https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_a_buy_on_first_signal
Buy on first signal not work for you? With EMACROSS, it will by at the cross.

**Comment by pablitoamigu** [comment]
Ok i will check the behavior with that setting in next hours and post result here

**Comment by taniman** [comment]
Your understanding of EMA cross is flawed. We do not buy 1 candle later. We buy as soon as a cross happens. Up untill the amount of candles you specified. 

Also this is not a place to request new features if there was something missing
