### ISSUE TITLE
Buy Pagination is broken

### ISSUE THREAD

**Issue by sroberson** [taniman/profit-trailer#2081]
Pagination for Buy orders is broken.  When you first navigate to Page 1 of Buy listings, you are actually on page 6 of results (in my case).  If you then click on Page 1, as soon as the next heartbeat happens, you will be auto-forwarded to some page deep page (6?).  

If you try to click onto page 1 to see what you just bought, you see it for a second then it goes again to some deep page after the heartbeat happens.

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:  2.1.13

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x ] Ubuntu (Ubuntu 18.04 LTS)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When you click to view page 1 of Buy list it should stay there until you advance to other pages, or click somewhere else,

## Current Behavior

click to page 1, see the date of the first item, wait a few seconds and you will see that the first buy listed is not today's date (assuming buys happened today)

## Steps to Reproduce

1.  Go to Buy listings.
2. Notice that the first item in the results is not today's Buy orders
3. Scroll down to click on Page 1 and notice the items have changed.
4.  By the time you scroll up to see the latest Buy orders, the heartbeat has happened and you no longer see what happened today.

**Comment by SgtBatten** [comment]
Pleas try clearing the browser cache

**Comment by sroberson** [comment]
It's not the cache.  When I load the page after a clear cache, I'm on page 6 of Buy results. I then click to page 1 of results to see what happened today. But as soon as the next heartbeat happens, it goes back to page 6 of results.

I also emptied my LocalStorage and the same thing happens.

**Comment by djcrypto75** [comment]
Fixed in last GUI build
