### ISSUE TITLE
Bittrex fails to reconnecting after interruption

### ISSUE THREAD

**Issue by twig123** [taniman/profit-trailer#2083]
If there is a temporary interruption to between the bot and Bittrex, or if Bittrex has API issues the bot will get caught in an endless error loop and won't reconnect websockets to reestablish connectivity. Some of the error logs include the following:

> 2018-09-14 02:23:39 ERROR AppErrorController - org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException

and

> 2018-09-30 17:37:48 ERROR BittrexExchange - queryExchangeState - there was an error invoking. error: Connection closed
> 2018-09-30 17:37:48 ERROR WebSockets - HubConnection - Error: java.lang.Exception: Connection closed
> 2018-09-30 17:37:48 ERROR BittrexExchange - error subscribeToExchangeDeltas. Connection closed

## ProfitTrailer info
Version: v2.1.14

Exchange:
- [X] Bittrex
- [ ] Binance
- [ ] Poloniex

Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [X] Windows (Windows 7)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
The bot successfully reestablishes connection to the exchange and resumes trading after network/api issues resolve themselves  

## Current Behavior
Bot goes into an endless loop of "Connection closed" errors and never recovers without a manual restart of the bot.

## Steps to Reproduce
1. Start the bot
2. Temporarily interrupt network connectivity to the exchange (Ex: disconnect network and reconnect it)

## Configuration
N/A

## Log files/console output
With DEBUG mode on, logs fill and rolls over itself, but is filled with the above noted errors.

**Comment by CmC353** [comment]
errors appearing in V2.1.16: Log and cmd screen file appended
[ptlog-04102018-172826.txt](https://github.com/taniman/profit-trailer/files/2447337/ptlog-04102018-172826.txt)

**Comment by taniman** [comment]
@CmC353 please create a propper new issue. This error u are posting is unrelated
