### ISSUE TITLE
Profit amount or the profit % is reported wrong

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer#2084]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

I keep having sales where either the profit amount or the profit % is reported wrong. Such as this:
Just sold: DATABTC
Sell strat: GAIN,RSI
Cost: 0.00600127
Rate: 0.00000613
Profit: 0.78%
Profit BTC: -0.00000221

![screenshot_20181001-1720262](https://user-images.githubusercontent.com/42469965/46333615-dcc1c000-c618-11e8-95c4-c9c4fef61815.png)

## ProfitTrailer info
Version: 2.1.14

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ x] Other linux distro (please specify) Profit Trailer VPS (not sure which Linux it is)
- [ ] Mac OS

## Expected Behavior

Positive profit amount should match positive profit % in sales log

## Current Behavior

Using negative gain to make small but positive profits. About 1 in 4 sales shows positive % but negative amount of profit.

## Troubleshooting

Asked for help on Discord. Elroy said to post an issue here.

## Steps to Reproduce

1. Trade with small profits
2. 
3.
4.

## Configuration

[JK4_OldFaithfulStoploss-DCA.txt](https://github.com/taniman/profit-trailer/files/2436782/JK4_OldFaithfulStoploss-DCA.txt)
[JK4_OldFaithfulStoploss-INDICATORS.txt](https://github.com/taniman/profit-trailer/files/2436783/JK4_OldFaithfulStoploss-INDICATORS.txt)
[JK4_OldFaithfulStoploss-PAIRS.txt](https://github.com/taniman/profit-trailer/files/2436784/JK4_OldFaithfulStoploss-PAIRS.txt)

## Log files/console output

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2436787/ProfitTrailer.log)

**Comment by taniman** [comment]
@djcrypto75 This is indeed a display problem. If orderbook profitcalculation value != 0 in saleslog. Display that negative profit.

User is selling with a gain of -1 so a negative profit % is the correct value to display in this case.

**Comment by djcrypto75** [comment]
fixed in last GUI build
