### ISSUE TITLE
Trying to upgrade from 1.x to 2.1.16

### ISSUE THREAD

**Issue by projecthate** [taniman/profit-trailer#2085]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.16

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [X ] Poloniex

 
Market:
- [ X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X ] Windows Server 2008 R2
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

I should be able to follow the upgrade guide on your wiki and have a working bot,.

## Current Behavior

I've updated the application.properties parameters as instructed and upon running the bot I am met with the error message "Your license is not valid. Verify that you have typed it in correctly.

## Troubleshooting

Triple checked parameter values match old configuration.

## Steps to Reproduce

1.
2.
3.
4.

## Configuration

https://pastebin.com/SiPni6yc

## Log files/console output

https://pastebin.com/3a9ztc2L

**Comment by taniman** [comment]
You should contact support on Discord.This place is for bugs
