### ISSUE TITLE
StochRSI display wrong value, it should be 1 instead of 0

### ISSUE THREAD

**Issue by leminhduc** [taniman/profit-trailer#2086]
With this parabolic movement and RSI reaching 100, StochRSI display as 0, which forbid me to sell. 

![image](https://user-images.githubusercontent.com/278861/46383942-9ede9d80-c6e5-11e8-8fff-e85beac1ed37.png)
![image](https://user-images.githubusercontent.com/278861/46383949-a9993280-c6e5-11e8-911d-af23408e9366.png)

**Comment by taniman** [comment]
Please use TVSTOCHRSID instead of STOCHRSI if u want to compare values with tradingview.

Please go through support channel on discord or the strategy channel if u have questions cause this does not look like a bug and also u have not provided the information required.
