### ISSUE TITLE
Wrong buy amount calculation in testmode

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2087]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.16

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
When TCV is 1 BTC and DEFAULT_initial_cost_percentage = 33 the order must be made for 0.33 BTC

## Current Behavior
When TCV is 1 BTC and DEFAULT_initial_cost_percentage = 33 the order is made for 0.195 BTC

## Troubleshooting
Updated to latest version from github

## Possible Solution
Dont know

## Steps to Reproduce
1. Enable testmode
2. set DEFAULT_initial_cost_percentage = 33
3. Push BUY button on any coin in Possible Buy
4. Check Pairs section

## Configuration
start_balance = 1
keep_balance = 0.0
keep_balance_percentage = 40
BTC_dust = 0.001
DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 33

## Log files/console output
2018-10-04 18:54:51 INFO ProfitTrailerService - Test mode: ["MANUAL"] bought 11178,00000000 APPCBTC price: 0,00001751, cost: 0,19572678
2018-10-04 18:54:51 INFO TelegramService - TEST MODE - Telegram message sent - TEST My BTC Bot
Just bought: APPCBTC
Cost: 0,19569872
Rate: 0,00001751

**Comment by SgtBatten** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_initial_cost_percentage

This behaviour is correct.
