### ISSUE TITLE
Feature Upgrade Request | FREE COINS | reserve_amount[_percentage]

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer#2089]
A variation on:
ACME_reserve_amount = 200
to:
ACME_reserve_amount_percentage = 25
with accompanying:
ACME_reserve_amount_percentage_min = 1

With the example above of 25(%):
if we had a 2% sell trigger then the bot would sell for only a 1.5% base pair profit and the remaining coin/bag gets added to an ever-accumulating (dust) [reserve] pair list of free coins).
This would only execute if the profit amount being triggered is 1% or higher.

**Comment by taniman** [comment]
This is not the place for feature requests. Here is only for bug reports.

When you opened the issue it shows you the url you need to be where you csn place festure requests
