### ISSUE TITLE
BNB No price bug

### ISSUE THREAD

**Issue by DaFreibier** [taniman/profit-trailer#2090]
## ProfitTrailer info
Version:2.1.16 and older

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ x] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (2012)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
When pt buys bnb coin @ the usdt market the bot does not have a price. every time in have to add it manuel 

## Current Behavior
every time 

## Steps to Reproduce

1. i can show you in a movie the problem

sorry my english is not the best i hope you guys understand me ;)

**Comment by SgtBatten** [comment]
This is expected behaviour.  whether you use BNB for fees or not the amount of BNB bought does not equal the amount the is left after fees. So PT cannot match a holding to the exchange history.

We do not have a solution for BNB at this time.
