### ISSUE TITLE
BUY button buys even when COIN_trading_enabled = false

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2091]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

If in config is set COIN_trading_enabled = false and send a request to BOT as BUY button was hit the PT will buy the coin

## ProfitTrailer info
Version: 2.1.16

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
The buy should not happen

## Current Behavior
The coin is bought

## Possible Solution
When buy button is hit check the config if coins are enabled for trading

## Steps to Reproduce
1. add to config ICN_trading_enabled = false
2. send POST request to action/buy?currencyPair=ICN

## Configuration
ICN_trading_enabled = false

## Log files/console output

2018-10-09 09:43:48 INFO ActionController - Manual buy ICNBTC
2018-10-09 09:43:48 INFO ProfitTrailerService - Test mode: ["MANUAL"] bought 5606,00000000 ICNBTC price: 0,00005594, cost: 0,31359964
2018-10-09 09:43:48 INFO TelegramService - TEST MODE - Telegram message sent - TEST My BTC Bot
Just bought: ICNBTC
Cost: 0,31357654
Rate: 0,00005594
2018-10-09 09:44:03 INFO ActionController - Manual buy ICNBTC

**Comment by taniman** [comment]
This is working as it should. The buttons override everything. 
If you click a button you have clicked i.t You chose to do so. So why should we block it. Its a manual decision.
