### ISSUE TITLE
[2.1.16] Sales missing: "CODE":-2010,"MSG":"ACCOUNT HAS INSUFFICIENT BALANCE FOR REQUESTED ACTION."

### ISSUE THREAD

**Issue by HomeY** [taniman/profit-trailer#2094]
PT puts a sales order on the exchange, it gets executed within 5 seconds. Then (according to the log) PT checks the exchange for the sell order and can't find it and throws the error:
"CODE":-2010,"MSG":"ACCOUNT HAS INSUFFICIENT BALANCE FOR REQUESTED ACTION."

According to the exchange the orders are executed, but i'm missing all 3 of them on my Sales log.
![image](https://user-images.githubusercontent.com/1996332/46940827-f24bd680-d069-11e8-9074-037d867d8335.png)

## ProfitTrailer info
Version: 2.1.16

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Expecting the Sales to show up in the Sales tab
## Troubleshooting

Restarted trader, but since the sales aren't in the data file, they don't show up.
## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2478070/ProfitTrailer.log)

**Comment by taniman** [comment]
There is nothing we can do about this currently. 
We have code to retry 3 times. 

If the exchange cannot say an order does not exist we cannot keep assuming it exists.
And if the failure happens we cannot log any sales in the sales log. 
So for now this problem will not be fixed further.
