### ISSUE TITLE
Unexpected DCA buys, DCA level not increasing

### ISSUE THREAD

**Issue by xandorlv** [taniman/profit-trailer#2096]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.17

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [X] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [X] Ubuntu (please specify version): 17.10
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Each buy in DCA should increase DCA level

## Current Behavior

Seems not working.
<img width="1301" alt="screenshot 2018-10-16 at 08 34 20" src="https://user-images.githubusercontent.com/17331835/46994912-0f8eac80-d11f-11e8-8cf4-fa6c59a7d529.png">
<img width="891" alt="screenshot 2018-10-16 at 08 34 44" src="https://user-images.githubusercontent.com/17331835/46994916-13baca00-d11f-11e8-8f54-517ba4f196e9.png">

## Steps to Reproduce
Don't know. Given this impacts buying I don't even want to try to.

**Comment by NomadFX** [comment]
Same for me on Windows 10. Also im missing the Hot Config Option.

**Comment by xandorlv** [comment]
I have downgraded to the last version I used before an upgrade: 2.1.11, all seems good.

**Comment by NomadFX** [comment]
Same here, works with 2.1.16 for me.

**Comment by taniman** [comment]
fix in 2.1.18
