### ISSUE TITLE
Stopping Binance with ctrl + C causing errors

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#2098]
## ProfitTrailer info
Version: 2.1.18

Operating System:
- [X ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Less errors

## Current Behavior
Lots of errors

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/6751341/47150288-74d8ce00-d2d6-11e8-8f97-6e92846e149c.png)

**Comment by des1re10** [comment]
https://support.binance.com/hc/en-us/articles/360018428871-Binance-System-Maintenance-Extension

**Comment by taniman** [comment]
Could not reproduce.
