### ISSUE TITLE
Pending Orders Sale not showing up in Sales log

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#2102]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.19

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Sales log listing pending order sales

## Current Behavior
Sales log not showing pending order sales

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

[ptlog-24102018-035844.zip](https://github.com/taniman/profit-trailer/files/2509480/ptlog-24102018-035844.zip)

**Comment by SgtBatten** [comment]
Did you place the orders or the bot placed them?

**Comment by alexdolli** [comment]
I placed them. That's why they don't show?

**Comment by MAXPROPHET** [comment]
Right.



Sent from my Sprint Samsung Galaxy Note9.


-------- Original message --------

**Comment by taniman** [comment]
Correct. Only pending orders placed by the bot can be dispalyed in the sales log.
