### ISSUE TITLE
New pairs calculating incorrect bought price using pending orders

### ISSUE THREAD

**Issue by AmadeoGaming** [taniman/profit-trailer#2103]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

When buying a new pair for ZRX/BTC the bot had calculated the bought price incorrectly much lower then it actually has and sells for a double digit gain take profit. This has happened twice since updating to 2.1.18 and both instances were on ZRX/BTC. My bot is currently using pending orders instead of DCA and is also using the combined pending order trigger as well. What i have noticed in the logs is that when i already have a pair in pending order...and i rebuy that same pair again....it cancels the pending order....recalculates the prices to adjust the average to include the newly bought pair...and then re-posts the pending order. Somehow this caused the bot to set my newly bought pairs bought cost much lower then it should have. 

## ProfitTrailer info
Version: 2.1.18

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows Server 2016 v1607 (Vultr VPS)(please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The bought price should be accurate on newly bought pairs and not lose price.

## Current Behavior

The bought price for ZRX/BTC has twice been inaccurate when bought using my current strategy that includes using the pending order system. Once today 10/24 and again on 10/21.

## Troubleshooting

I have not tried to fix it because it happens when i am away and too fast to do any kind of hot config adjustment because the issue happens immediately upon purchase.

## Steps to Reproduce

1. Set up pending orders for ZRX/BTC 
2.  Rebuy a fresh new pair of ZRX/BTC
3.  See if the bot incorrectly sets the new pairs price much lower then it should
4.

## Configuration

https://pastebin.com/Vhu10XwR

## Log files/console output

 
[ProfitTrailer (1).log](https://github.com/taniman/profit-trailer/files/2512058/ProfitTrailer.1.log)

ZRX exchange trades

![screenshot 61](https://user-images.githubusercontent.com/44446792/47457272-85cc8800-d78b-11e8-987d-6314c7f4713d.png)

**Comment by taniman** [comment]
Please zip and upload the data/unaccounted folder.
I will be needing some files from there.

**Comment by AmadeoGaming** [comment]
[unaccounted.zip](https://github.com/taniman/profit-trailer/files/2513434/unaccounted.zip)

**Comment by taniman** [comment]
Fix in 2.1.22
