### ISSUE TITLE
Bought Price in PT is different than in Binance

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer#2104]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.16

 
Exchange:
- [x] Binance

 
Market:
- [x] BTC

 
Operating System:
- [x] Windows 10

## Expected Behavior

Values should be the same in PT and Binance.

## Current Behavior

The values are not the same.

![image](https://user-images.githubusercontent.com/1479483/47516223-3bc7cd00-d885-11e8-9077-927a907369c9.png)

![image](https://user-images.githubusercontent.com/1479483/47516255-54d07e00-d885-11e8-9c1f-09efe47241e0.png)

4753 * 0.00001498 = 0.07119994 (PT)
4753 * 0.00001504 = 0.07148512 (Binance)

PT says it was 1498, but does also say that the total bought cost = 0.07148512.
So the math is not right in PT, because 4753 * 0.00001498 != 0.07148512

## Possible Solution

 PT can calculate the actual bought price on Binance by this: 0.07148512 / 4753 = 0.00001504 

I think Binance gives back the amount and the total bought cost. Just divide the last by the first and you'll get the bought price.

## Log files/console output

 

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2515948/ProfitTrailer.log)

**Comment by taniman** [comment]
I will need your ProfitTrailerData.json

**Comment by taniman** [comment]
from unaccounted folder get the new_buy_calculated-22114960 file for me too

**Comment by taniman** [comment]
1 week has passed and the data I need is not available in PT folders anymore.

I will be fixing 1 thing in 2.2 for calculations. Not sure if this will fix your problem too. But we shall see by that time.

**Comment by echthard** [comment]
Log file was already included in the issue. 

The other file is not present in the unaccounted folder. Nor is any file with BTS in the filename.

**Comment by taniman** [comment]
that's why I said it's too late :D
They get cleaned up after 1 week. ;)

I still might be able to use ProfitTrailerData.json though. Hopefully
