### ISSUE TITLE
Stop triggered without having stop configured

### ISSUE THREAD

**Issue by ThecRw** [taniman/profit-trailer#2107]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:  P T Ver: 2.1.20 

 
Exchange:
- [X] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (Windows Server 2012 R2 Datacenter )
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Stop loss trigger is not configured, meaning, it's set at zero. Bot should not trigger stop loss

## Current Behavior
I have no stop loss trigger configured, however, yesterday the bot sold a coin in loss and the sell strategy message was STOPLOSS

## Troubleshooting
Nothing

## Possible Solution
No solution

## Steps to Reproduce

1.
2.
3.
4.

## Configuration
files attached
[dca.txt](https://github.com/taniman/profit-trailer/files/2531630/dca.txt)
[indicators.txt](https://github.com/taniman/profit-trailer/files/2531631/indicators.txt)
[pairs.txt](https://github.com/taniman/profit-trailer/files/2531632/pairs.txt)

## Log files/console output
logs attached
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2531636/ProfitTrailer.log)

**Comment by ThecRw** [comment]
Hi there.

Thanks for your prompt reply. Attached the 2 screenshots, however, unfortunately I did not find the test-588110 file you mentioned.

Let me know if you need anything else.

![capture](https://user-images.githubusercontent.com/31865936/47754066-9ac88000-dc91-11e8-8997-eb879c901139.PNG)
![config-editing](https://user-images.githubusercontent.com/31865936/47754067-9ac88000-dc91-11e8-9e65-45efbcd47e7f.PNG)

**Comment by SgtBatten** [comment]
Hi again.

Can you please include the full header/page in the second screenshot.

**Comment by SgtBatten** [comment]
Actually, i can see what i need to.

The config image shows a trashcan icon. This icon only appears when editing a non-active config. So the config you are viewing is NOT the one being used by the bot.

**Comment by ThecRw** [comment]
Ahhhh.. I see what you mean... the default was the active one... sorry for the mess... I've activated the correct config and will monitor results

Thanks for your help

**Comment by SgtBatten** [comment]
Perfect. That should give you you what you are expecting now.
