### ISSUE TITLE
[bug] 2018-11-05 23:38:30 ERROR ProfitTrailerService - Occured in chartData, handled result exception PT Huobi does not support this period 14400

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer#2109]
v2.1.21
Huobi

It should support the 4 hourly for sure.

**Comment by taniman** [comment]
Huobi does not support 4hour klines
https://github.com/huobiapi/API_Docs_en/wiki/REST_Reference#get-markethistorykline--get-candlestick-data
