### ISSUE TITLE
[bug] PT display disappears in Chrome after a while

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer#2116]
When i run PT in the sales tab for a while, the display disappears, while PT in the background runs fine. I estimate after 12h - 24h this display issue happens.

v2.1.23

I doubt this is a chrome bug, since all the other windows such as tracker and so, stay alive.

![screenshot](https://user-images.githubusercontent.com/11975743/48677400-c8a83280-eb74-11e8-8722-cac296382c99.png)

**Comment by taniman** [comment]
Is this not something a simple page refresh fixes? F5?

**Comment by des1re10** [comment]
Ofc i need to refresh the page, and everything is fine again after. But this shouldnt even happen, that the display disappears.

**Comment by des1re10** [comment]
![screenshot 2018-11-22 18 34 37](https://user-images.githubusercontent.com/11975743/48917209-e1bb2700-ee85-11e8-939c-80fcc2a48104.png)

**Comment by djcrypto75** [comment]
What language have you set in your bot?

**Comment by des1re10** [comment]
English

**Comment by MAXPROPHET** [comment]
I have noticed this for a long time also… I just refresh the page and it comes back.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by des1re10** [comment]
Yes i know. But for me it should not disappear for some reason.

**Comment by djcrypto75** [comment]
Fixed in later versions
