### ISSUE TITLE
Reflective access warning in Java 10 - not a bug

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2117]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.23

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (18.04.1)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
No error

## Current Behavior
We have a warning

## Possible Solution
Code rewrite

## Steps to Reproduce
1. Upgrade from ubuntu 16.04 to 18.04.01
2. Start bot

## Configuration
Doesnt matter

## Log files/console output

1|profit-t | 2018-11-19 10:28 +01:00: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
1|profit-t | 2018-11-19 10:28 +01:00: WARNING: An illegal reflective access operation has occurred
1|profit-t | WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/home/joka/ProfitTrailerBTC/ProfitTrailer.jar!/BOOT-INF/lib/spring-core-4.3.17.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
1|profit-t | WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
1|profit-t | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
1|profit-t | WARNING: All illegal access operations will be denied in a future release

This ticket is just FYI. Default Java version on Ubuntu 18.04.1 is 10.0.1. So when you install java on this system you get a warning after bot starts

**Comment by taniman** [comment]
This is a java 9 error. Please downgrade to java 8. As the bot does not support java 9 else you get these warnings
