### ISSUE TITLE
PAIR Disappears from Pairs log while PT trying to cancel pending order TEST MODE

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#2120]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.25

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Pair should be visible when PT cancels pending order

## Current Behavior

Sometimes pair disappears from both from pending orders and pairs log. Restarting the bot brings back the pair in pairs log.

## Troubleshooting

Restart the bot

## Steps to Reproduce

1. Issue is intermittent. when pt tries to cancel pending order sometimes pair is lost.
2.
3.
4.

## Log files/console output

 
[ptlog-27112018-222152.txt](https://github.com/taniman/profit-trailer/files/2621529/ptlog-27112018-222152.txt)

**Comment by taniman** [comment]
I would advice you next time this happens to contact support and we can do a live debugging. As the logs do not show any reason why this would happen. 
I have create a change in 2.1.27 that fixes coins disappearing and reappearing. But not sure if this will fix your problem too.

So once this release is out. Keep an eye out and contact  support if this happens with 2.1.27 version too.
