### ISSUE TITLE
Bot returns too much data for gui - not a bug

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2122]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.26

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (18.04.1)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Request only needed data from bot ticker

## Current Behavior
When GUI sends request to bot for coins' data it makes request to /private?command=returnTicker and this URL returns info about all the coins on exchange from all markets. But bot is working only with BTC currently. So there is no need to take additional data from bot and spend a lot of traffic and time to parse it. 

## Troubleshooting
Can be fixed only by  developers

## Possible Solution
Remove excess data from response to save traffic and CPU time on client

## Steps to Reproduce
Just start the bot

## Configuration
Does not matter

## Log files/console output

No logs

**Comment by taniman** [comment]
I understand your point. But this is a request we get from the exhcange which also returns all this data. We don't go and fetch all the coins 1 by 1.
I see on my binance bot this request is 15KB, that about 130 MBin 24 hours at the rate the requests are done.
Compared to the amount of GB's being retrieved by the bot this is nothing.
I would say that goiing through the data and filtering other markets would cause extra CPU usage than just sending what we got.

So your intentions are good, but this is not really something that will be changed
