### ISSUE TITLE
Can't push SELL button in GUI on iOS Chrome

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2124]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

Really hard to push SELL button on mobile. Need to hit it 5-10 times with different short intervals

## ProfitTrailer info
Version: 2.1.26

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (18.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
One button hit - confirm popup at once

## Current Behavior
Hit 5-10 times with different time intervals to get confirm popup

## Possible Solution
Fix GUI

## Steps to Reproduce
1. Take Iphone with iOS 12
2. Install latest Chrome
3. Ty to hit SELL button

## Log files/console output
No LOGS. Nothing related to bot itself

**Comment by djcrypto75** [comment]
It is working fine here. Try again with clearing cache and also in incognito mode.
