### ISSUE TITLE
Profit Yesterday Estimated Gain % Value is inaccurate

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer#2126]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.1.28

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

I have Total current value of ETH 21.08 yesterday's profit was 0.0269 ETH and it shows Estimated gain 0.93% should be 0.127% My profit Tracker shows the right value, that's how I noticed this.

## Current Behavior

I have Total current value of ETH 21.08 yesterday's profit was 0.0269 ETH and it shows Estimated gain 0.93% should be 0.127% My profit Tracker shows the right value, that's how I noticed this.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by smoochy** [comment]
PT 2.1 changed the behavior.

![image](https://user-images.githubusercontent.com/34371932/51474801-b61ec500-1d80-11e9-9a92-d13f90005c17.png)


See an example here: https://www.investopedia.com/ask/answers/102714/whats-difference-between-profit-margin-and-markup.asp

**Comment by taniman** [comment]
@smoochy has answered above
