### ISSUE TITLE
I am trading on ETH I think it should show the  ETH USDT price not the BTC USDT price

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer#2127]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.1.28

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (10)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

I am trading on ETH I think it should show on the Monitor page in the grid's first column second row the  BINANCE ETH USDT price not the BINANCE  BTC USDT price since that's what i generally care about.

## Current Behavior

Right now it shows: 
3,832.04 (3.95%)  BINANCE  BTC USDT price 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
@atka007 Please make sure to at least post a screenshot next time to make it clearer what screen you are talking about.

@djcrypto75  Is this a bug or working as expected?

![image](https://user-images.githubusercontent.com/6751341/50609401-e2dc6c80-0ea5-11e9-8594-4b0927bcc6f8.png)

**Comment by djcrypto75** [comment]
As intended. You have the ETH price in the ticker. BTC is the mother coin :)

**Comment by atka007** [comment]
Is this just me?  That for me as Bot user the mother coin is ETH because that's what I am trading on.

**Comment by djcrypto75** [comment]
It was created like this as all coins move with BTC. 
I am creating a «widget» system for the dashboard so in the future you can choose yourself what you want to see :)
