### ISSUE TITLE
keep_balance_percentage not working properly

### ISSUE THREAD

**Issue by victorlmt1** [taniman/profit-trailer#2129]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.29

 
Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

 
Market:
- [X ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [X ] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
keep_balance_percentage expected to don`t buy a coin if it would get your balance below set percentage. This would help me to keep my balance if a coin in DCA is consuming it and I need to keep it to get out of a bag.

I have set keep_balance_percentage = 50 in PAIRS config, and expected the bot to keep buying until it reaches 50% of my balance (I wanted to save 50% to DCA). If my balance is below 50% it would be a "DCA only mode".

## Current Behavior

I`m using DEFAULT_initial_cost_percentage = 8.

Instead of initial buy of 8% of my TCV, the bot only bought 50% of it, equals to 4% of my TCV.

I think it is some problem between keep_balance_percentage and DEFAULT_initial_cost_percentage.

## Troubleshooting
I have set keep_balance_percentage = 0 and it came back to normal, buying 8% of my TCV (which as I said is set on my configs)

## Possible Solution
Somehow make the bot still buy the "DEFAULT_initial_cost_percentage" and if the balance is bellow the "keep_balance_percentage" it will stop buying.

## Steps to Reproduce

1. Set DEFAULT_initial_cost_percentage = 8 in PAIRS.
2. Set keep_balance_percentage = 50 in PAIRS
3. Let the bot buy (it will buy 4% instead of 8%
4. Set keep_balance_percentage = 0 in PAIRS
5. Let the bot buy (it will buy 8%, which is set in configs)

## Configuration
As it is very easy to reproduce this error, and it is probably some variable being calculated in the wrong formula, I think you guys don`t need my configs.

## Log files/console output
[ptlog-17012019-214353.txt](https://github.com/taniman/profit-trailer/files/2771016/ptlog-17012019-214353.txt)

**Comment by taniman** [comment]
We indeed do not need your configs as this is not a bug.
Your TCV changes to whatever the balance after keep balance becones plus your curent holdings.

So you basically have 2 TCV's if you are using keep_balance.

One the main monitor page you can see the
PAIRS balance 
DCA balance

So if you own 1 BTC. And 0 coin holdings.
And your have a keep_balance_perc of 40% in PAIRS config.

Means you can use 60% or 0.6 BTC for pairs. 
TCV for pairs is 0.6 BTC + holdings (0BTC)

This is a question support could have answered. 

So All in all.Working as expected
