### ISSUE TITLE
v2.2's README intro paragraph should been on v2.1.30's README

### ISSUE THREAD

**Issue by sroberson** [taniman/profit-trailer#2130]
The intro paragraph on the README for PT v2.2 looks like It was written for the 2.1.30 release:

### Important!
This is a minor update so the upgrade should go smoothly
Best to upgrade from version 2.1.29 or 2.1.30
Due to the database upgrade and the different cases we urge you to
Create a backup, make a screenshot of your prices and DCA levels
Make sure you know your bot's GUI password before upgrading.
If anything goes wrong. Contact support

It seems like Version 2.2 is NOT a "minor update".

-- Scott

**Comment by taniman** [comment]
![image](https://user-images.githubusercontent.com/6751341/51494443-0bfa6980-1d8f-11e9-8817-6878c56ae6ee.png)

https://semver.org/

Please have a read. 2.2.0 comes after 2.1.x version. So it is indeed a minor update. Whereas  going from 2.1.29 to 2.1.30 is a patch/bugfix release

**Comment by SgtBatten** [comment]
Just to clarify for you scott. it says best to upgrade to 2.2 from 2.1.29 or 2.1.30. You may have read that as best to upgrade from  2.1.29 to 2.1.30.
