### ISSUE TITLE
lowbb is -1250 and growing. incorrect values shown bot cant dca

### ISSUE THREAD

**Issue by didzjones** [taniman/profit-trailer#2131]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Please create a mew issue and fill out the form. You did not even mention bot version or provided required data.
