### ISSUE TITLE
XBT current value is way too high

### ISSUE THREAD

**Issue by connde** [taniman/profit-trailer#2133]
## ProfitTrailer info
Version: 2.2.0

Exchange:
- [ ] Bittrex
- [ ] Binance
- [ ] Poloniex
- [X] Bitmex

Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR
- [X] XBT

Operating System:
- [ ] Windows (please specify version)
- [X ] Ubuntu (18.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Current price should be similar to bought price

## Current Behavior
Current price is too high, not related to actual price
![image](https://user-images.githubusercontent.com/1514559/51574474-adb3b080-1e8c-11e9-991b-101541ec4745.png)

## Troubleshooting
Server restart
Manually sold and bought again

## Steps to Reproduce
1. New installation with fibonacci day trade
2. Config and db bellow

## Configuration
[Fibonacci_Day-INDICATORS.txt](https://github.com/taniman/profit-trailer/files/2785142/Fibonacci_Day-INDICATORS.txt)
[Fibonacci_Day-PAIRS.txt](https://github.com/taniman/profit-trailer/files/2785143/Fibonacci_Day-PAIRS.txt)
[Fibonacci_Day-DCA.txt](https://github.com/taniman/profit-trailer/files/2785144/Fibonacci_Day-DCA.txt)

## Log files/console output
[ptdb.mv.db.zip](https://github.com/taniman/profit-trailer/files/2785146/ptdb.mv.db.zip)

**Comment by connde** [comment]
This is what is showing, took a screenshot before reseting the bot.
![image](https://user-images.githubusercontent.com/1514559/51695337-933f1b80-1fe1-11e9-897d-69fd8045a2ce.png)

**Comment by taniman** [comment]
fixed in 2.2.5
