### ISSUE TITLE
Bot suffering OutofMemory exceptions since upgrade to 2.2

### ISSUE THREAD

**Issue by djbadders** [taniman/profit-trailer#2134]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

Bot suffering OutofMemory exceptions since upgrade to 2.2 and then the UI is no longer accessible nor the API for PT Magic. I am also seeing very high CPU on the java processes for Profit Trailer since the upgrade.

## ProfitTrailer info
Version: 2.2

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [x ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x ] Ubuntu (18.04.1)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Stable running without exceptions like I had on v2.1.29

## Current Behavior
Throwing OutofMemory exceptions when accessing the UI or API via the Spring framework. The Server has plenty of RAM left. Error example below:
![image](https://user-images.githubusercontent.com/34887832/51592358-54c53600-1ee7-11e9-85c0-8d76e1c92c43.png)

The UI then becomes unresponsive with just a spring logo being rendered and PT Magic is unable to access the bots API.

## Troubleshooting
Restarting the bot works for a while but the issue often returns quickly.

## Steps to Reproduce

1. Start bot
2. Access the UI
3.
4.

## Log files/console output

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2786275/ProfitTrailer.log)

**Comment by taniman** [comment]
A mew set of options to run the bot with were published with the new release. Are you using these? 

You should increase your XMX value if you have Heap Space Problem. 
The bot connects now to a database and all these new changes require a bit more memory.

We ofcourse could not test 100+ different setups. 
Please use the new startup scripts and increase XMX value if needed.

**Comment by taniman** [comment]
Using PM2 means you have to do a PM2 reload PM2-ProfitTrailer.json --update-env
for new script changes to take effect

**Comment by taniman** [comment]
Any more queries can be handled through support on discord. As this is setup related

**Comment by aquanuke** [comment]
Hi do you have link to the new options you mentioned?

**Comment by taniman** [comment]
They are included in the ProfitTrailer.ZIP file of the 2.2 release

**Comment by aquanuke** [comment]
I only have these files in the zip

**Comment by taniman** [comment]
@aquanuke Please visit support on discord. You can get better help there.

**Comment by djbadders** [comment]
Thanks @taniman I had missed the changes to the pm2 files for the Java args. I will apply them and see if it resolves it.
