### ISSUE TITLE
Manual action timer

### ISSUE THREAD

**Issue by hyperUnkn0wn** [taniman/profit-trailer#2135]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.2.0

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [x] Mac OS

## Expected Behavior

Manual 'SELL'
User GUI confirmation - 'YES/NO'

## Current Behavior

Manual 'SELL'
User GUI confirmation - 'YES'
**"ActionController - Please wait x seconds before performing this manual action"**

## Possible Solution

The reason for the issue as a bug is that the software is not doing what the user has requested it to do after confirmation. Not being able to sell several positions in a row renders the software/gui non-responsive. **_Time is money._**

1. Removal of manual action timer.
  - No gui changes.

2. Possibility to disable manual action timer.
  - If enabled, it would be informative for those users that are not watching console that they cannot perform next manual action before x seconds has passed. ex. YES button could be disabled, show the countdown and re-enabled when the timer has finished.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Manual action timer has been removed in 2.2.3
