### ISSUE TITLE
[PT 2.2] SOMO settings not 'sticky' after restart

### ISSUE THREAD

**Issue by HomeY** [taniman/profit-trailer#2136]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.2

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

When you set SOMO to 'Forced On' and restart the trader, SOMO is disabled again. I would expect the settings to 'stick' till changed by the user, since it's forced setting.
Not sure if this should be a bug report or a feature request (since it's probably working 'as designed'), but since it's a 'forced' setting, i think the user should have full control over it.

## Current Behavior

After restart of PT, SOMO is 'disabled' again

## Possible Solution

Make the setting permanent, so the user has to disable it again when wanted.

## Steps to Reproduce

1. Enable SOMO 'Forced On' 
2. Re-start PT
3. Check SOMO Setting
4.

**Comment by taniman** [comment]
This is not a bug. That is how the function works. 
You can set SOM manually in the PAIRS file is you want no new coins to be bought.
