### ISSUE TITLE
Linux-update.sh script doesnt work

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2137]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

The update doesn't work

## ProfitTrailer info
Version: 2.2.0

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (18.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
The bot should be updated and restarted

## Current Behavior
ProfitTrailer.jar is deleted from the bot's dir

## Steps to Reproduce
1. Install a bot
2. Got to its directory
3. Run ./linux-update.sh

## Log files/console output
`./linux-update.sh

##################################################
          ProfitTrailer Update Script
##################################################

Loading from saved setup...

Your current configuration is:
Name/ID 	Path
3       	/home/.../ProfitTrailerBTC

Do you wish to proceed with this configuration? (Y/N) y

##################################################
                      Update
##################################################

Latest release is version  2.2.1

Do you want to continue? (Y/N) y

 === Downloading ProfitTrailer 2.2.1 ===
######################################################################################################################################################### 100.0%

 === Extracting download ===

 === Stopping 3 ===
[PM2] Applying action stopProcessId on app [3](ids: 3)
[PM2] [3](3) ✓
┌────────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name       │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├────────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ profit-trailer │ 3  │ fork │ 0   │ stopped │ 45      │ 0      │ 0%  │ 0 B    │ ... │ disabled │
└────────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬──────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼──────┤
│ pm2-logrotate │ 2.6.0   │ N/A        │ online │ 0       │ 0%  │ 48.281 MB   │ root │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴──────┘
 Use `pm2 show <id|name>` to get more details about an app

 === Replacing jar file ===
cp: 'ProfitTrailer.jar' and '/home/.../ProfitTrailerBTC/ProfitTrailer.jar' are the same file

 === Restarting 3 ===
Use --update-env to update environment variables
[PM2] Applying action reloadProcessId on app [3](ids: 3)
[PM2] [profit-trailer](3) ✓

 === Cleaning up ===

##################################################
     Finished updating to ProfitTrailer 2.2.1
##################################################

┌────────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name       │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├────────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ profit-trailer │ 3  │ fork │ 0   │ errored │ 60      │ 0      │ 0%  │ 0 B    │ ... │ disabled │
└────────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬──────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼──────┤
│ pm2-logrotate │ 2.6.0   │ N/A        │ online │ 0       │ 0%  │ 48.281 MB   │ root │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴──────┘
 Use `pm2 show <id|name>` to get more details about an app`

**Comment by jokaorgua** [comment]
I'm using the pm2 - everything is in the logs

**Comment by taniman** [comment]
Please is something is not a bug. Go through support. I won't handle non bugs on github. 

Support on discord is open 24/5. So let support help you with this.
