### ISSUE TITLE
manual sale not recorded in sales log

### ISSUE THREAD

**Issue by helojoe** [taniman/profit-trailer#2139]
I've seen that this issue (or similar) has already been happening in the past, but the tickets are all closed, so I guess this is a new issue.(?)

## ProfitTrailer info
Version: 2.2.2

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows 10 x64
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
show record of sale in sales log

## Current Behavior
PT missed to log one manual sell (EOSETH) in the sales log. Binance processed it as usual, without any problems.
![unbenannt](https://user-images.githubusercontent.com/36679477/51830939-44e79080-22f1-11e9-8a89-65068b276789.png)
![unbenannt2](https://user-images.githubusercontent.com/36679477/51831044-86783b80-22f1-11e9-8110-8c947f63205a.png)

## Configuration
[oldfaithfulV4-INDICATORS (1).txt](https://github.com/taniman/profit-trailer/files/2802501/oldfaithfulV4-INDICATORS.1.txt)
[oldfaithfulV4-PAIRS (1).txt](https://github.com/taniman/profit-trailer/files/2802502/oldfaithfulV4-PAIRS.1.txt)
[oldfaithfulV4-DCA (1).txt](https://github.com/taniman/profit-trailer/files/2802503/oldfaithfulV4-DCA.1.txt)

## Log files/console output
relevant log @ 2019-01-28 11:22:21
[ptlog-28012019-113432.txt](https://github.com/taniman/profit-trailer/files/2802506/ptlog-28012019-113432.txt)

**Comment by taniman** [comment]
Please post your entire log. As now you posted what you though was a relevant log and is now causing me to ask additional questions.

Was this a normal sell or a DCA sell?

**Comment by taniman** [comment]
This issue has been fixed in 2.2.3
The lost sale is lost forever though.
