### ISSUE TITLE
Feature request - Excel export mod

### ISSUE THREAD

**Issue by Davethegithub** [taniman/profit-trailer#214]
Re exporting to excel - awesome function : ) thank you - but figuring the Profit or Loss in $US on a given trade is difficult.  The column with CURRENTVALUE/TOTALCOST is combing the amounts as one.  Might be my older version of excel??.  Would not be a problem if there was a separate column with actual Profit or Loss in USD form. Primarily for loss assessment.  A punter can then tell at a glance how fucked they are for that particular trade (instead of trying to figure out satoshis at 8 friggin decimal places with BTC constantly changing converted to $US).  Stop loss is OK but an unsophisticated tool.  Prefer my own 'human' based calculations as to whether or not to exit a position based on future prediction.

Then I would suggest a CLOSE positon button (with secondary confirmation) right in the browser/interface - if possible.

![image](https://user-images.githubusercontent.com/33383595/32410683-d55cde78-c216-11e7-8447-a59f34012c80.png)

**Comment by djcrypto75** [comment]
Fixed in future release.
