### ISSUE TITLE
Losing average price after DCA buy

### ISSUE THREAD

**Issue by djbadders** [taniman/profit-trailer#2141]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

Since version 2.2 I have been seen pairs lose their average price after a DCA buy. This is being seen approx every 5 days or so, and didn't occur on 1.9.

## ProfitTrailer info
Version: 2.2.2

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (18.04.1)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Average price calculated correctly post DCA buy.

## Current Behavior
About once every week a pair loses its average price.

The DCA list shows:
![image](https://user-images.githubusercontent.com/34887832/52147651-4b626900-265f-11e9-952f-2d6528c9fc3d.png)

The buy log shows:
![image](https://user-images.githubusercontent.com/34887832/52147633-3a195c80-265f-11e9-9795-e161687f56c1.png)

## Troubleshooting
I have to calculate a set the price manually

## Possible Solution
May only affect bots in test mode.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
2.2.3 has already a fix for this. Indeed it is a problem with test bots

**Comment by djbadders** [comment]
Thanks
