### ISSUE TITLE
Binance Stop-Limit Orders show in Pending Log and Dust Log

### ISSUE THREAD

**Issue by HojouFotytu** [taniman/profit-trailer#2143]
## ProfitTrailer info
Version: 2.2.3-B4

Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [x] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Should only show in Pending log

## Current Behavior
Create stop-limit SELL order on Binance.  The order shows up in both Pending log AND Dust log. 

## Troubleshooting
Restarted PT - order still shows.    Only Stop-Limit SELL seems to cause trouble..  
Stop-Liimit BUY orders show correctly, only in Pending Log.

## Steps to Reproduce

1.  Create a stop-limit SELL order on Binance
2.
3.
4.

**Comment by jsnx** [comment]
Do you have a dilution script running like PT-Defender? Usually this behavior is seen when the Dilution Tool cuts the slice in too small pieces which profittrailer then recognizes as dust.

**Comment by HojouFotytu** [comment]
> Do you have a dilution script running like PT-Defender? Usually this behavior is seen when the Dilution Tool cuts the slice in too small pieces which profittrailer then recognizes as dust.

Thanks, but nothing to do with that.  An order on the exchange is showing simultaneously in the Pending log and the Dust log.

**Comment by HojouFotytu** [comment]
I'm not sure if this was what you fixed in 2.2.6-b1:  "- Fix incorrect dust value displayed when a coin is sent to pending"

But i currently have a stop-limit buy in, and it seems to fixed.  The coin only shows in pending now, not dust.

**Comment by taniman** [comment]
I have not look at this issue yet.
