### ISSUE TITLE
Currency Profit output incorrectly in the Sell Logs Page

### ISSUE THREAD

**Issue by DrFREEST** [taniman/profit-trailer#2145]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.2.5

 
Exchange:
- [O] Bittrex
- [O] Binance
- [ ] Poloniex

 
Market:
- [O] BTC
- [O] ETH
- [O] USDT
- [O] BNB
- [O] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [O] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The CURRENCY PROFIT calculation on the SELL-LOG page is output incorrectly.

## Current Behavior

Staying still, watching, constantly happening.

## Troubleshooting

When I checked the SELL LOGS source in my browser, the
"var currentTrendProfitTmp = dtCache.marketPrice * profitValue;" 
part of the 
"dataTableHelper.js" 
file was incorrectly written.
The process of multiplying "dtCache.currencyValue" is missing.

## Possible Solution

 in the "dataTableHelper.js"

var currentTrendProfitTmp = dtCache.marketPrice * profitValue;

to

var currentTrendProfitTmp = dtCache.marketPrice * profitValue * dtCache.currencyValue;

## Steps to Reproduce

1.
2.
3.
4.

**Comment by djcrypto75** [comment]
fixed
