### ISSUE TITLE
Partial Sell on Binance puts correct sold TAM into Pending but puts full original TAM into Dust

### ISSUE THREAD

**Issue by eye1care** [taniman/profit-trailer#2147]
## ProfitTrailer info
Version: 2.2.5

Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [X] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Partial sell on Binance should put TAM sold into Fixed Pending on Profit Trailer and the remaining TAM into Pairs (or if very small amount into Dust)

## Current Behavior
The correct sold amount goes into Pending (as it should), nothing goes into Pairs, but the full TAM owned goes into Dust.     ie: Sold 89.1 of TAM 89.5 shares NEO.  89.1 shows up in PT Pending and the full 89.5 shows up as Dust.  Nothing shows in Pairs.  
CMD Says:  ERROR BinanceWS - Restarting ChartData websocket

![pending](https://user-images.githubusercontent.com/36254677/52525507-73118c80-2c70-11e9-8523-d17d8c5f77b2.jpg)
![dust](https://user-images.githubusercontent.com/36254677/52525511-7f95e500-2c70-11e9-9d4a-4dd46ec8cce7.jpg)

## Troubleshooting
Shut down PT many times, full TAM still in Dust.  Cancelled NEO sell order, everything went back to normal and TAM NEO went back to DCA.  Tried Selling NEO on Binance again but TAMs did the same (Full TAM into Dust, correct TAM into Pending)

## Possible Solution
None

## Steps to Reproduce

1.
2.
3.
4.

**Comment by eye1care** [comment]
LOG File
https://pastebin.com/1CWBWNDj

**Comment by eye1care** [comment]
Pairs File
https://pastebin.com/FUY1NCVK

**Comment by eye1care** [comment]
DCA File
https://pastebin.com/PJQMDG4V

Indicators File
https://pastebin.com/sL8hqr5w

**Comment by taniman** [comment]
There is 1 thing that is not correct here. The bot does not send things to pending when you sell. Even a partial sell is sold partially rest is cancelled.

So I am wondering where you are getting your pending orders from.

But indeed this bug with dust value looks familiar. And I am fairly certain is has been fix in 2.2.6 already.

You are welcome to contact me on Discord if you want to try the beta. Or wait a few 1 or 2 days while we finish testing

**Comment by eye1care** [comment]
I went back to PT 2.2.2 and all works.  I am not selling through the BOT, selling manually on Binance to get rid of bags.

**Comment by taniman** [comment]
ooh in that case. indeed that has been fixed in 2.2.6.
