### ISSUE TITLE
No Average Price Recalculation after Exchange Partial Sale

### ISSUE THREAD

**Issue by HojouFotytu** [taniman/profit-trailer#2148]
## ProfitTrailer info
Version:
2.2.6

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [x] Windows 10-64b
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
PT should recalculate the average price of a position after selling part of the position manually on the exchange.

## Current Behavior
When holding a coin purchased by PT then manually buying more on the exchange, PT correctly recalculates the new average price.  

However, when manually selling only part of the position on the exchange, PT doesn't recalculate the new price at all.  It does recognize the sale, and correctly updates the number of coins held, but the average purchase price doesn't change.

## Troubleshooting
Have only been able to test with position currently at a negative profit.

PT bought:  188.22 KMDBTC @ 0.00020720
Exchange sale:  -47 KMDBTC @ 0.00020470
New average should be:  0.00020803
PT still using:  0.00020720

## Steps to Reproduce

1.   Sell only part of a position manually on Binance.

## Log files/console output
Nothing related in logs, order settings, or unaccounted

**Comment by HojouFotytu** [comment]
Doing some more testing, I decided to make a buy:

47 KMDBTC @ 0.00020540

New PT Avg Price for 188 coins:  0.00020675

But according to my math, the correct Avg Price (ignoring fees) should be:  0.00020737.  Including fees, the average price PT shows should actually be above 0.00020737, around 0.00020778.  

So PT does recalculate when adding to a position (but incorrectly), but doesn't do any recalculation at all when selling part of a position.

**Comment by taniman** [comment]
no a bug. works as designed
