### ISSUE TITLE
SET BOUGHT PRICE WHEN DCA

### ISSUE THREAD

**Issue by didzjones** [taniman/profit-trailer#2150]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:2.2.6

 
Exchange:
- [ ] Bittrex
- [X ] Binance
- [ ] Poloniex

 
Market:
- [ X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ X] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

AVERAGE PRICE SHOULD BE CALCULATED
## Current Behavior

LOOSES BOUGHT PRICE ON NEARLY EVERY PAIR
## Troubleshooting

UNINSTALLED REINSTALLED 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by SgtBatten** [comment]
PLease edit original post and include circumstances where this is occuring. What addons you use and upload your log file and screenshots of coins with this issue
