### ISSUE TITLE
Poloniex testbot losing prices

### ISSUE THREAD

**Issue by bluefuzz** [taniman/profit-trailer#2152]
## ProfitTrailer info
Version: 2.2.7

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [x ] Poloniex

 
Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Bot should 'buy' a coin and remember the price.

## Current Behavior
My Poloniex testbot loses the bought price immediately after 'buying' a new coin. Restarting the bot gets the price again. (I have three other bots with identical settings on Bittrex and Binance running on same VPS that are working fine)

## Troubleshooting
Restart fixes the price until it buys again.

## Steps to Reproduce
Testbot on Poloniex

## Log files/console output
An example: 

```
2019-02-21 09:34:57 INFO ProfitTrailerService - Test mode: ["FIBSWING_144_233","FIBSWING_21_55"] bought 125.58869702 BTC_KNC price: 0.00003822, cost: 0.00480000
2019-02-21 09:34:59 INFO NormalStrategyRunner - Normal Pair - currency pair BTC_KNC, MTP 11, TTP 11
2019-02-21 09:35:05 INFO AverageCalculator - Please set KNC_bought_price (-1686674418)
```
But it happen with every coin I think.

**Comment by taniman** [comment]
This was fixed already in 2.2.8. Please upgrade
