### ISSUE TITLE
DEFAULT_A_Sell_strategy_direction = DOWN  , not working for RSI

### ISSUE THREAD

**Issue by nureddino** [taniman/profit-trailer#2153]
## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [x ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x ] Windows (Win server 2008 R2 , VPS)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

**_DEFAULT_A_Buy_strategy_direction = UP is working but,
DEFAULT_A_Sell_strategy_direction = DOWN  , not working for RSI_**

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Default behaviour is down. So I can assure you it works. 
Please go through support on Discord. So you can look together as They must do the pre investigation.

**Comment by nureddino** [comment]
default_BUY_strategy_direction = UP is working but,
default_a_ SELL_strategy_direction = DOWN , not working for RSI

'BUY'  is working but 'SELL' is not working...............

for RSI,
for example,

default_a_ SELL_strategy_direction = DOWN
default_sell_value = 62,
default_sell_value_limit= 60

for RSI (true),
first,
must be greater than 62 then
between 62 and 60, 
but it didnt work.

![rsi](https://user-images.githubusercontent.com/31002477/53546987-d2134480-3b3e-11e9-8336-85c2ff952e2a.PNG)

**Comment by taniman** [comment]
As i said. Cobtct support on discord. This is not a bug. there is no direction down for sell strategy.
