### ISSUE TITLE
reset adminpassword

### ISSUE THREAD

**Issue by mikdesign02** [taniman/profit-trailer#2155]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [x] Bittrex
- [ ] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Check the wiki on how to reset your password
