### ISSUE TITLE
PTTracker pro link in my dashboard  appears and then disappears 

### ISSUE THREAD

**Issue by mikdesign02** [taniman/profit-trailer#2156]
Hi,

I have the 2.2.10 version live PTTracker pro link in my dashboard  appears and then disappears after 5 second. But on my smartphone the link is there and actif but there is an error in the balance convert to USD. it seems he still use the BTCUSD has convertion reference despite my bot is in the ETH market. (see pictures in attach). I am using chrome but this is the same observation with firefox and explorer.
![e81b5046-2362-4c2c-ba56-3eb77654f257_li](https://user-images.githubusercontent.com/34874555/53793814-838eed00-3f26-11e9-858a-fc0f16764ddf.jpg)
![1f9d552d-0fcb-4af4-a9c3-86c31dd7c41e_li](https://user-images.githubusercontent.com/34874555/53793829-8984ce00-3f26-11e9-85f1-016cdeeff92d.jpg)
![1f9d552d-0fcb-4af4-a9c3-86c31dert7c41e_li](https://user-images.githubusercontent.com/34874555/53793950-d8cafe80-3f26-11e9-8461-156a4f2c3344.jpg)

**Comment by taniman** [comment]
The pro tools veing shown is a bug. As it should not be shown at all and will be removed.

The pro tools is a beta feature we are still testing and will be released when it is finished.
