### ISSUE TITLE
Monitor page is missing market data

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#2157]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.2.10

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [x] ETH
- [ ] USDT
- [x] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Forntapge Market Cap and other market data showing on Monitor page of PT

## Current Behavior

With version 2.2.10 I don't get any market data, other than the BTC price on the Monitor page of PT (see screenshot). You can actually see that on your demo servers, too.

## Possible Solution

While you guys work on fixing it, is there a chance to get the up to date price in the currency we're trading? (I marked the spot in the screenshot). For example, if my base currency is ETH, I'd like that marked field to show the ETH price. Currently it shows BTC, no matter what base currency I'm using.
I know, on the top right is the correct base currency, but when you look at the monitor page on a mobile, you only get the "always BTC' price.
![capture](https://user-images.githubusercontent.com/36098310/53944342-2bbec600-408d-11e9-80fa-f29bc89b1009.PNG)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Not a bug. Your adblocket is blocking coin market cap. Contact support on Discord hf u need more help debugging
