### ISSUE TITLE
Différence ETHUSD rate on the dashboard

### ISSUE THREAD

**Issue by mikdesign02** [taniman/profit-trailer#2158]
As you can see there is a difference rate of convertion in the dashbord. Please make the correction

![image](https://user-images.githubusercontent.com/34874555/54045640-100d0a00-41ca-11e9-84ad-0418e3e675c2.png)

I notice the same difference of pair value  between  PT and PT Tracker 
![image](https://user-images.githubusercontent.com/34874555/54045858-9590ba00-41ca-11e9-9421-88cbee0b844b.png)

![image](https://user-images.githubusercontent.com/34874555/54045874-a0e3e580-41ca-11e9-92b5-db1ce961896d.png)

**Comment by djcrypto75** [comment]
It calls the exchange and currency API every few seconds and not always at the same time, so the numbers can have very small differences. On the dashboard we get numbers from both CMC and the exchange so they will be different.
