### ISSUE TITLE
Latest 2 builds (2.2.12 / 2.2.11) intermitently cease buying or selling until restarted, 2.2.10 does not have this issue

### ISSUE THREAD

**Issue by jshplayer** [taniman/profit-trailer#2162]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
I am gonna have to ask you to go to discord and let support help you there.
