### ISSUE TITLE
update from 2.0.16 to 2.2.*

### ISSUE THREAD

**Issue by bartgrefte** [taniman/profit-trailer#2163]
I haven't updated PT in a while and now I'm curious if I can update from 2.0.16 to 2.2.* directly or if that will cause problems with the existing config. I've checked the wiki, only saw the instruction to check the release notes, but there are several pages of those to go through.

Isn't there a page that only shows things to look out for?

edit: Just tried to update an old bot directly, it's asking for a new password (it didn't reuse the one I set) and it's asking for the default api key that is still in application.properties, same with trading settings., have to select (or import) those again.

**Comment by taniman** [comment]
This is not a support channel. join our discord Server and you can geld support there. 
https://discord.gg/eakB23b

**Comment by bartgrefte** [comment]
Well, it would help if I can actually post there. It says I have to register my phonenumber before I can do that, haven't had that before on other channels.

**Comment by taniman** [comment]
That's a discord feature to prevent spammers and scammer joining the server
