### ISSUE TITLE
MAX COST REACHED - The rounding seems to be at 0.01

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer#2166]
## ProfitTrailer info
Version: 2.2.12

 
Exchange:
- [ x] Binance

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [ x] Ubuntu (please specify version) 16.04
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
DEFAULT_DCA_max_cost = 0.03
All pairs above 0.03BTC should be in "MAX COST REACHED"

## Current Behavior
MAX COST REACHED seems to be random
![image](https://user-images.githubusercontent.com/15019378/55741403-771e1880-5a2d-11e9-81dd-a3e4d2a2c7f3.png)

## Troubleshooting
- Change the value of DEFAULT_DCA_max_cost, same
- MAX COST REACHED seems to be random
- And if DCA MAX PAIRE is displayed, the MAX COST is no longer displayed

## Steps to Reproduce

1.
2.
3.
4.

## Configuration

![image](https://user-images.githubusercontent.com/15019378/55741605-fca1c880-5a2d-11e9-8bd7-330ef1f301e5.png)

**Comment by taniman** [comment]
I am sorry. But you need to go through support channel on discord before posted something here. 
As it seems you do not quite understand how MAX COST works.

And on your other note. 
We only display 1 info at a time in the GUI.  

So please head over to Support on Discord or ask in the beginners channel as I see no bug.
