### ISSUE TITLE
(feature)Bump & dump protection: Avoid coins that are up xx% in 24h - plus limit

### ISSUE THREAD

**Issue by mkarulin** [taniman/profit-trailer#219]
To avoid buying during dump it would be nice to have a setting like ALL_buy_max_price_increase that allows avoiding coins that are up xx% in the past 24 hours. 
The info is already displayed in the dashboard so it should not be difficult to implement.

Example: ALL_buy_max_price_increase = 20 # Only buy coins whose price has not risen more than 20% in the past 24 hours
Or ALL_buy_max_price_increase = -20 # Can also be used to buy from bottom.

**Comment by Davethegithub** [comment]
Yes I like this kinda idea.  Failing a more sophisticated approach its a good start.  May save us buying late into pumps or early into dumps.  Problem is the coin may be on its way up over all so no harm buying in as dump may not be certain.  Thats why a 3 stage, 3 different period analysis, approach might work better.

**Comment by xAndyxNL** [comment]
I would love this feature aswell, im seeing pairs that have increased +200% in 24hrs. You can just wait for those to get dumped eventually. Good to see its already added to planned updates.

**Comment by taniman** [comment]
DEV INFO: Use a 24% range to buy
