### ISSUE TITLE
Optional decrement or Increment option for the trailing profit value for Buy and Sell

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#227]
Create a property to decrement or increment the trailing profit value

For example, a value of 0.1 will decrement the trailing by 0.1 at each breathing room. That way we can reduce the risk that the price will fall back and we can try to target a profit of 3% for example or more

Maybe people might want to increase it to take advantage of the velocity of the price..

Same for the buy trailing

**Comment by AkliOnet** [comment]
Another option more simple to implement is to have a sell_now property to sell immediately if the profit reached 5% or 14%.

**Comment by YoJeff** [comment]
You can now customize the trail, profit percent and others per DCA level.

If some subset of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
