### ISSUE TITLE
(bug?)TRAILING_BUY: positive buy_value and trailing_buy trail upwards

### ISSUE THREAD

**Issue by mkarulin** [taniman/profit-trailer#235]
ALL_buy_strategy = EMASPREAD

All_buy_value: -0.01
All_trailing_buy: 0.3
Current Value: -0.39, Buy Value: -0.64 (Works as intended)

All_buy_value: 0.01
All_trailing_buy: 0.3
Current Value: 0.90, Buy Value: 1.12 (Seems to be trailing upwards which is nonsence)

All_buy_value: 0.01
All_trailing_buy: -0.3
Buy Value stays at 0.1 and does not trail at all?

**Comment by taniman** [comment]
> All_buy_value: 0.01
> All_trailing_buy: 0.3
> Current Value: 0.90, Buy Value: 1.12 (Seems to be trailing upwards which is nonsence)  

Working as designed, so not nonsence. Documentation clearly states that it will buy on higher values.
Some people want to buy on an uptrend.
If you really want to use positive EMASPREAD value, do not use trailing.


> All_buy_value: 0.01
> All_trailing_buy: -0.3
> Buy Value stays at 0.1 and does not trail at all?

Trailing buy/sell dont work like that. It should always be a positive number. 


There is an open issue to maybe address this trailing with positive  EMA value.
