### ISSUE TITLE
New Pairs are continued to be bought even if already more than Max_Trading_Pairs (Bittrex ETH Market)

### ISSUE THREAD

**Issue by johnalindogan** [taniman/profit-trailer#238]
Hi,

When using PT on the Bittrex ETH Market, new pairs are continued to be bought even if already more than Max Trading Pairs (Bittrex ETH Market)

On my setup, Max Pairs is set to 6 but PT still continues to buy (there are13 pairs in the Possible Buy Log) even if I already have 11 pairs in my DCA. 

I am currently running on v1.2.5.1

See attached screenshots of my config

![photo_2017-11-10_12-20-29](https://user-images.githubusercontent.com/15606255/32655324-1113aa7a-c648-11e7-96ea-be9e6d582c17.jpg)
![photo_2017-11-10_12-36-12](https://user-images.githubusercontent.com/15606255/32655325-1175c4c6-c648-11e7-89f0-956cac7e5f09.jpg)

**Comment by taniman** [comment]
fixed in 1.2.5.3

**Comment by johnalindogan** [comment]
Confirmed. Max_Trading_Pairs working in ETH. Thanks Elroy!
