### ISSUE TITLE
memorize entry coin prices / store buying prices 

### ISSUE THREAD

**Issue by Al0815** [taniman/profit-trailer#240]
The bot is unable to determine a purchase price if was to long ago. (around 30 days for bittrex).
This is a limitation of the API. 
Then the bot can't sell, because he has no entry price or he can not calculate the DCA average.
To cover this, he should keep all the values in memory/cache file as long as the specific coin is not sold.

**Comment by lenardbang** [comment]
Would be awesome, for wordaround of some sort, with those 'forgotten' buy prices. maybe indeed some local price db.
