### ISSUE TITLE
Feature: Pyramid buy: Increase stake as price increases

### ISSUE THREAD

**Issue by mkarulin** [taniman/profit-trailer#241]
All_pyramid_buy = 2 # (positive value only) Double the stake as price increases 2%, then double again when price increases another 2% and so on. 
Could also be divided into steps similar to Anderson strategy. 
Also needs a max_buy_times setting, similar to Anderson strategy.

This would greatly increase profits on coins that are bumping and allows setting initially lower starting bid = smaller bags.

**Comment by Concept211** [comment]
Interesting idea!

**Comment by Davethegithub** [comment]
hmmmm I understand your logic but it has high risk, if not entirely likely, of buying in at the top
