### ISSUE TITLE
Property to Trigger sell only mode if the trend(top 50) go below 1% to avoid crash and lost

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#247]
ProfitTrailler should follow the 24h global trend! A profitable trading bot is not only good to make a profit but also to avoid losing profit.

If the top coins average trend is in the negative the others are most likely to be in the negative. For those that don't agree the property is optional and adjustable

The indicator is already there so i think Elroy has already thought about this feature..

**Comment by AkliOnet** [comment]
Minimum volume

**Comment by AkliOnet** [comment]
Today I wake up the top trends is between 0 and 0.5 no more sale and 36 bags. (I disabled all consecutive buys trigger as it limit to much the trading as the good settings is hard to find with all consecutive sell trigger)

**Comment by AkliOnet** [comment]
I have seen the btc trigger .. but why trying to dedect with difficulty the trends based on bitcoin when we already have it.

**Comment by AkliOnet** [comment]
After 15 day .. I re conclude that this is the most neeeded feature that is the most simple and has the most impact ! ! Why adding new exchange before adding this feature that save our profit and our money.

**Comment by ulearn** [comment]
Bump to second this - its vital. A large minus Bollinger Band setting would be almost completely safe and without downside if triggered in a bullish trend. In a bearish trend it may just be the start or middle of a greater slide that triggers losses and stops. It's a must IMO :)

**Comment by YoJeff** [comment]
#80
