### ISSUE TITLE
sales log doesn't include the sales completed from pending list

### ISSUE THREAD

**Issue by neongas** [taniman/profit-trailer#249]
While comparing the trade history in bittrex, I found that a sale(a pair of buy and sell) which was coming from pending list didn't show in the sales log. Even though a sale was made from the pending list, it also has a profit. I think this record should be included in the sales log and overall profit calculation.

**Comment by taniman** [comment]
No, trades not done by the bot will not be included at the moment in the sales log. This is not a small task. too many turning parts.
1. buy, send to pending. 
2. after wards , you buy sell buy buy sell buy sell.
3. now you sell the pending.

How do I know what buy value belonged to this sell? I need the original buy prie to be able to calculate profit.
