### ISSUE TITLE
Upgrading causes loss of Sales Log

### ISSUE THREAD

**Issue by Davethegithub** [taniman/profit-trailer#251]
Upgraded several times now form 124 onwards and every time I loose Sales Log data.  I copy it over, new sales data is added to the log so all the history is there, but Sales Log shows nothing 0.  Pain in the rssss

**Comment by Davethegithub** [comment]
which by the way removes all ANDERSON history ie resets back to (0) which for a trade that was already at (5) buys and eating a lot of the capital, can cause another sudden double up or 2 as the earlier triggers are at lower %

**Comment by taniman** [comment]
This has nothing to do with upgrading. I am not sure how you upgrade. But if you just replace the jar file save file is being read properly. But there is an issue open to make backups of the save file. 
See #207 

This might help you in the future

**Comment by DaltonHart** [comment]
I am having the same issue. I updated the bot no issue except for the sales log is now empty. The profittrailerdata.json and backup are there and the data is on them but PT now does not show the sales log.
