### ISSUE TITLE
WARNING Error - 

### ISSUE THREAD

**Issue by NAZ7777** [taniman/profit-trailer#252]
I receive this -

 :: Spring Boot ::        (v1.5.4.RELEASE)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/NAZ/Desktop/ProfitTrailer/ProfitTrailer.jar!/BOOT-INF/lib/spring-core-4.3.7.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1

**Comment by taniman** [comment]
could you send me your log file in telegram?

**Comment by NAZ7777** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1476521/ProfitTrailer.log)

**Comment by NAZ7777** [comment]
Can you shed some light for me on this matter ?

**Comment by omarmoss** [comment]
I have the same problem.

**Comment by omarmoss** [comment]
Uninstall any other Java versions (I had v9 installed + v9 Developer kit).
Still had v8 installed, so left that installation.
Now runs without that error.

**Comment by oviwan** [comment]
same problem for me, I have uninstalled jave 9 and tried installing java 8 and still get the warning messages

**Comment by omarmoss** [comment]
@oviwan, try turning your firewall and antivirus etc off if you are running anything on top of Microsoft.
See if the problem persists. If not, then you will need to add the PT app to the list of safe apps.
If it still persists, then uninstall all Java applications, restart your computer, Switch off Anti virus & firewall, then install Java 8. Once done try running PT again.
