### ISSUE TITLE
ERROR Application - Please fix: trading_apiKey -- INVALID_SIGNATURE

### ISSUE THREAD

**Issue by platinumxgithubx** [taniman/profit-trailer#256]
I'm running bot version 1.2.5.4

Everything I start the bot, an error message comes up saying:

ERROR Application - Please fix: trading_apiKey -- INVALID_SIGNATURE

What does this mean?

I've already entered my purchased license key and all my keys from Bittrex into the application.properties.
Am I missing something?
Is there an order I need to enter it in as in the application.properties?
Please help.

Thanks you.

**Comment by wassimchelfi** [comment]
Hi, i have the same error

ERROR Application - Please fix: trading_apiKey -- INVALID_SIGNATURE

How can i fix it

Thanks

**Comment by alternativesurfer** [comment]
I also am encountering this error.

**Comment by adamwhitlock1** [comment]
I am also having the same issue, I tried making a new key as the wiki mentions and had the telegram bot register the new key, but that didnt work, and now if I ask the bot to list keys it asks for my license key and then tells me it is invalid :( just bought the application and cant get it to work 😞

**Comment by Rimbit** [comment]
I am having this issue as well
Any solution?

**Comment by mathewhawkins** [comment]
I just bought the software v 1.5.4 and getting the same issue.

**Comment by mathewhawkins** [comment]
FYI , i did what it said on this page and it fixed the issue : 
https://github.com/taniman/profit-trailer/wiki/Known-issues
