### ISSUE TITLE
Monitor: Make decimals more dynamic

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#257]
Hey,

it would be good if we could make the decimal places in the monitor more dynamic so that we don't show 8 decimals no matter how great the number is.

- USDT values usually tend do be greater than one and to our understanding more than 2 decimals really rarely make sense in a Fiat context.
- ETH/BTC: When profits are around 0.x btc/eth it's usually enough to know a few decimals.

Numbers could get smaller this way and we can get a clearer view of what's going on.

**Comment by taniman** [comment]
some thing like. number great than 0? only show 2 decimals or something

**Comment by djcrypto75** [comment]
Need more details and examples
