### ISSUE TITLE
trade data log

### ISSUE THREAD

**Issue by tomd2001** [taniman/profit-trailer#258]
could you please add a feature which writes/appends all data for each trade to a log file to the local 
"profit-trailer" folder?

specifically, when the bot makes a buy or sell order, i would like to know the values of the EMA's, the BB's, the bid/ask, GAIN, EMAGAIN, EMASPREAD, etc.

Thanks!

**Comment by wejo13** [comment]
+1

**Comment by symbion6** [comment]
+1 
Currently, it's quite hard to measure detailed results and change settings accordingly.
Would really like to see the spread % that triggered a trade, the start and end-date (for calculating throughput), sell strategy and anything else that helps to see how effective current settings are.

**Comment by orionmodern** [comment]
+1
