### ISSUE TITLE
[Feature Request] Embed or Popup/Overlay Charts

### ISSUE THREAD

**Issue by Concept211** [taniman/profit-trailer#259]
It would be really useful to have a button next to each pair that's in any of the Log screens to quickly view an embedded TradingView chart. It would either pop up as an overlay over the UI or expand the table row down. It would be faster and more convenient than opening up the pair's Bittrex page which is usually very slow and clunky.

**A rough example of what I'm thinking:**
![Embedded Chart](http://concept211.com/gfx/PT-Chart.png)

Not sure how customizable it is, but I know TV has multiple embedding options:
https://www.tradingview.com/publishing-tools/

Alternatively, they also offer a complete stand-alone library to give you more charting freedom:
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

**Comment by AkliOnet** [comment]
This idea is great as if their api allow to specify the indicators length (I don't think their widget offer that) we can track in live where the bot trigger is positioned in live !

**Comment by taniman** [comment]
This has already been added to PTTracker. So any PRO user has access to it.
