### ISSUE TITLE
INFO message when max cost in USD is too low in USDT market setup.

### ISSUE THREAD

**Issue by freeebits** [taniman/profit-trailer#260]
Hi,

Please display INFO message at the console when too low USD value for Max Cost like 0.002 is entered at pairs.prop file of USDT trading.
Ppl get used to BTC market sometimes mistakenly enter those values in BTC currency.
Showing this INFO will let the user know his misconfiguration.

Thanks.

**Comment by taniman** [comment]
Is this request still valid?

**Comment by minerdude** [comment]
I think better bot sends a telegram notification when "MIN TRADE SIZE REQUERIMENT NOT MET" message received, by bittrex for example

**Comment by YoJeff** [comment]
I think the current error messages in the log are sufficient.
