### ISSUE TITLE
Don't buy brand new coins

### ISSUE THREAD

**Issue by twig123** [taniman/profit-trailer#261]
Can there be something put in place to restrict the bot from not buying brand new coins? Like the coin must be at least X days old to enable trading?

For example:
https://bittrex.com/Market/Index?MarketName=BTC-RCN

This coin was a bloodletting on release day... and the bot bought on the first candle, which triggered it to DCA itself into a rabbit hole.

**Comment by Concept211** [comment]
Excellent idea. These new coins usually have a nasty sell off as soon as they hit Bittrex.

**Comment by Condor60** [comment]
i would definitely like to see this feature.  I'm also holding a nice bag of RCN and see it as a future vulnerability if you don't switch to defining all your pairs, which I would like to avoid and let PT find pairs that fit my settings.

**Comment by mkarulin** [comment]
I think everyone has a VIB bag today xD

**Comment by vicenterusso** [comment]
+1

**Comment by antknight** [comment]
+1

**Comment by angelsomar** [comment]
To avoid at the moment they can create white lists

in binance CryptoRireal I created a plugin https://github.com/CryptoRireal/binance-auto-blacklist

**Comment by gambcl** [comment]
I would really like to see this feature, was just about to raise a ticket when I found this one.
Damn you BLZ!!!

**Comment by steveman223** [comment]
BLZ got me too!

**Comment by orionmodern** [comment]
yes pleases!
+1
