### ISSUE TITLE
Total must be at least 0.0001

### ISSUE THREAD

**Issue by kidoux** [taniman/profit-trailer#263]
Hi,

when I start the bot it gives me that line for every  pairs trade, of course my balance on Poloniex is way above that, so Im looking for a solution, thats all Ive got so far, I saw on several topics that sometimes Poloniex APi fucked up and give this error, if you've got any tips about it or somewhere to look at, hit me up

Thank you

**Comment by taniman** [comment]
What is your ALL_max_cost set at in PAIRS.properties? Can you send me your log file?

**Comment by kidoux** [comment]
`##################  PAIRS.properties ##############################
################### VERSION CONTROL ###############################
### Read the wiki for more explanations about the properties    ###
### https://github.com/taniman/profit-trailer/wiki              ### 
###                                                             ###
### OCT 23, 2017 Add file version control                       ###
### NOV 05, 2017 Add new property ALL_stop_loss_timeout         ###
### NOV 05, 2017 Add new property ALL_DCA_enabled_trigger       ###
###################################################################
###################################################################

MARKET = BTC

ALL_trading_enabled = true
ALL_enabled_pairs = ALL

ALL_max_cost = 0.00010000
ALL_min_buy_balance = 0
ALL_min_buy_volume = 200
ALL_min_buy_price = 0
ALL_max_trading_pairs = 10
ALL_max_buy_spread = 1

ALL_buy_strategy = EMASPREAD
ALL_buy_value = -0.50
ALL_trailing_buy = 0.1

ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_min_profit = 1
ALL_trailing_profit = 0.5

All_stop_loss_trigger = 0
ALL_stop_loss_timeout = 0
ALL_panic_sell_enabled = false

ALL_DCA_enabled = false
ALL_DCA_enabled_trigger = 0

ALL_sell_only_mode = false

ALL_btc_price_drop_trigger = 0
ALL_btc_price_drop_recover_trigger = 0

ALL_btc_price_rise_trigger = 0
ALL_btc_price_rise_recover_trigger = 0

ALL_consecutive_buy_trigger = 10
ALL_consecutive_sell_trigger = 5

ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0`

**Comment by taniman** [comment]
well, aas poloniex takes the fee from the max_cost I think that is causing the problem. I recommend using 0.0003 as ALL_max_cost. or 0.0002 in the least. 0.0001 is too close to the border
