### ISSUE TITLE
Telegram Notifications SlimEdition™️

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#267]
It would be good to have a slimmer version of the TG notifications to save some space in height and use more in width.

On sales IMHO Cost and Rate could go. Profit is key.

BX 1 BTC 💰 sold BTC-ADA (Gain)
Profit: 0.98% (BTC: 0.00006856)

PX 2 USDT 💸 bought USDT_ETH
Cost: 1.99999927 @ 337.13667484

Here's some piece on using Emoji for Telegram in Java. This might help https://monsterdeveloper.gitbooks.io/writing-telegram-bots-on-java/content/lesson-4.-emoji.html

Also the Emoji used above should be Telegram Save as they were selected from a TG client (they use a limited subset).

Alternatively something like → and ← could work too for incoming and outgoing.

**Comment by Helmi** [comment]
nAffie added another link in TG: https://core.telegram.org/bots/api#formatting-options

**Comment by surfr10132** [comment]
I wish we could have a way that shows the profit amount in USD and not just a percentage.

**Comment by taniman** [comment]
This will either be done in milestone 1.2.8 or we will start using a third party

**Comment by Mikeeetrue** [comment]
the most useful part would be adding current TCV for sell notifications and current free Balance for buy notifications

**Comment by taniman** [comment]
Some of this is already of will see what can be added to PTN
