### ISSUE TITLE
Feature: set date / days listed

### ISSUE THREAD

**Issue by MLD89** [taniman/profit-trailer#270]
To be able to set a range of coins to trade based on either date being listed or minimal number of days passed since listing on exchange.

**Comment by Concept211** [comment]
Extremely important! I've accumulated an enormous 8x DCA bag due to VIB hitting the exchange and dumping all the way down to the original ICO price.

**Comment by mkarulin** [comment]
This thema has allready been brought up here https://github.com/taniman/profit-trailer/issues/261
