### ISSUE TITLE
Feature: Bag filler :-)

### ISSUE THREAD

**Issue by MLD89** [taniman/profit-trailer#271]
Is it possible to make a feature to set a certain coin of which the goal is to increase your bag. For instance you want to accumulate as much as possible of a certain coin and want PT to swing trade the BB on a larger timeframe (probably best due to liquidity). The option for PT to take last sold value as the next buy value to incrementally increase the positions and bag would be great!

**Comment by mkarulin** [comment]
Why not just turn off sell and use DCA to fill it up the bag as the price goes down?
