### ISSUE TITLE
[FEATURE] Add external order for bot

### ISSUE THREAD

**Issue by Lorcan1001** [taniman/profit-trailer#272]
I would like to create my own strategy on tradingview and send my orders the bot ? 
Is it  possible future feature ?

**Comment by menzmarco** [comment]
Yeah that would be awsome!!

**Comment by DevilSquare** [comment]
any update on this ? i wanted to use mininghamster signals to buy in PT

**Comment by taniman** [comment]
This has been labeled Q3. So Q3 just started and we are working on this. There is no ETA.
