### ISSUE TITLE
[FEATURE] Add trailing buy for all buy strategy based on the strategy not price

### ISSUE THREAD

**Issue by cryptotrader-1** [taniman/profit-trailer#276]
Add a feature to buy trail based on the strategy not price for example. LOWBB buy set at 25 trail set 10

Bot won’t buy until the BB rises by 10 so for example in a dump it may hold below or at the low BB until it hits the bounce. Then would hit the trail. Sometimes the price might rise quickly in a candle causing trailing buy to trigger based on price but the lowBB could still be heading down and further. Sometimes to avoid this setting trailing buy too large then causes you to miss the bottom of the buying strategy. 

Another example would be Emaspread being able to trail the spread value.

**Comment by taniman** [comment]
emaspread already trails the spread
