### ISSUE TITLE
[FEATURE] Alternate charting URL option for market links.. 

### ISSUE THREAD

**Issue by RchGrav** [taniman/profit-trailer#278]
Here is an easy one and useful...
It would be very nice to have the market link be able to go to a better website than just the exchange.. the existing functionality would occur as default unless this config value was present.

This could be accomplished simply by having an ALTURL option in the config somewhere.
Examples:   
alt_chart_url = https://www.coinigy.com/main/markets/BTRX/${coin}/${market}
alt_chart_url = https://www.tradingview.com/chart/?symbol=BITTREX:${coin}${market}

Bittrex site is so resource intensive and having the ability to launch to an alternate could allow the user to save indicators which match the bot for analysis and strategy.

**Comment by Concept211** [comment]
Great idea! I've been wanting the same thing since Bittrex is just so slow. This would be an easier/quicker alternative to the feature I requested for embedded charts here: https://github.com/taniman/profit-trailer/issues/259

**Comment by RchGrav** [comment]
Leaving the existing link and having an option to turn on coinigy or tradingview links in the same cell of the gui tables would be maybe even better, so you could leave the exchange link.   I cant think of any other charting sites that would fit the bill anyway..   Just being able to launch to a fast charting site with saved indicators would be awesome.

coinigy_links = true/false
tradingview_links = true/false

**Comment by cryptorole** [comment]
This feature would greatly improve my productivity in analysing data and adjusting configuration.
Since I'm not using one of the charting sites mentioned above (tradingview, coingy, whatever), I'd prefer the generic approach mentioned initially by @RchGrav
