### ISSUE TITLE
Debagging strategy: Ouroboros, use your BAG its volume, make profit!

### ISSUE THREAD

**Issue by Utone** [taniman/profit-trailer#285]
**Codename: Ouroboros**
_The ultimate de bagger, without the need for extra BTC._
**Application:** _BIG_ bags of low volume coin. (under 5BTC volume, where buying more would make you the major shareholder if you aren't already..))

Like my 1.2BTC bag from getting a lesson in getting hustled in a pump (fuck you Cryptoqueen XD) 
A coin now only 2.5 BTC in volume (once almost sold when was pumped 5% from my selling price (we pumped that to my price with 5 people in 5 minutes so im sure it can and will happen some day..

But until then it basically just sits there....at 40% of the bought price I have half the volume on 
Bittrex.... :/

Strategy in short: Become a Market maker for that pair until you earned back the difference from spread or if you're happy, keep doing it as it's now free cannon fodder earning money and when it gets pumped you'll pop a bottle of bubbles.. :)

Use a reverse sell/buy market maker strategy with your coin volume: (to not have other spread bots temporarily place a wall to close the spread) 

I always buy at BID and sell at ASK when manual trading often for an easy instant profit...
and on your regular trades from the bot when you see it's time to sell it's an easy extra 1-2%

Sell high and buy low...Sell at ask first and then buy it back at bid to profit from spread. but you got to mix it up a bit but still theres also volatility...

Debag even low volume coins without extra BTC

Easier than buying and then selling, because more difficult to defend against.

Would be best to do this in timed intervals with random offset and a small enough amount that doesn't appear as a huge wall to scare people into dumping, but similar or slightly smaller than walls in front of bigger walls that get moved when eaten.

If you do this to blatantly, a few times in a row they temporarily close the spread or just so you will make a small loss 0.01-0.05% (so i suspect they don't pay fees either ;)  
(I always buy at BID and sell at ASK when manual trading often for an easy instant profit.) 

On your regular trades from the bot when you see it's time to sell it's an easy extra 1-2%..
I don't know if PT does this already but if it only buys at ask and buys at bid it is missing out and often you can still sell a bag at ask price but definitely not at bid..

Remember, coin has no fixed price attached it's just volume that generates BTC so use it. ;)

Sell high... Buy low....!
Tested manually, just need a way to keep track of profits made until done..

![](https://user-images.githubusercontent.com/5865016/32701934-b9c202ce-c7de-11e7-8cbc-0bac3777a906.jpg)

**Comment by Concept211** [comment]
Intrigued because I'm sitting on a huge bag with a 40%+ loss as we speak. What chart timeframe are you looking at to do this? Or does it even matter?

What's your username on Telegram, btw?

**Comment by Utone** [comment]
time frame is irrelevant only the spread and avoiding then close it temporally because you do obvious expatiation of (their spread)
