### ISSUE TITLE
BBRSI debagger

### ISSUE THREAD

**Issue by Utone** [taniman/profit-trailer#287]
I know RSI is in the works, So won't dive in that too deeply..

read this for starters no one thinks about this one and its pretty damn important for day traders:

https://www.dailyfx.com/forex/education/trading_tips/trend_of_the_day/2014/08/27/3-Trading-Tips-for-RSI.html

But like to share my experience. 
I currently use bbrsistepgain on all pairs for for big buys and 90-95% sell rate often in minutes.
The cool thing is using tradingview you can measure the lowest gain such dips have given in the past and set that as minimum gain, my default minimum for pairs I have not analysed is 3% and measured pairs some of what i call 'frequent flyers' regular cannon fodder popular for pumps these often also start pumping right after it over sells: reason me thinks: people accumulate and when they see it going they say what the heck lets do it again....  

For a lot of regular big volume pairs I have at a minimum of 5 to 8% on my first step (just because I want it to sell and not depend on trend viewer.. Here minimum gain 4% (my max at a bit under the left one not the obvious oversold one right before that that comes well within my range its measuring the lowest vs highest gain, just so you understand why those non obviously oversold correction lines, that was the max peak)
![min gain 4](https://user-images.githubusercontent.com/5865016/33154837-947c8ff6-cfeb-11e7-84c6-8e1be987565d.jpg)

I will still be buying big with RSI and let PT do the selling part and run a bunch of pairs with a proper DCA!

Now for the actual tip, besides huge gains you can actually petty much count on when you measure the past performance: De-Bagging plus profit guys!

xxxxxx[18.11.17 01:06]
most definitely as you already aim for oversold dips and those are the spots that are often in a straight line value I got VTC at RSI 39 and it always shoots at least 2% in a few minutes, So for debagging it would be very easy to calculate the cap needed to debag
then you wouldn't need multiple double ups at sometimes less than optimal points because it only buys 1x the bag then sees it needs more so it buys double later etc..

RSI with quick to fill trailing buy added to the main buy/sell strategies,  would be the ultimate de bagger, just the coin amount of what is needed but count on 60% of past performance gains so its a sure sell, with PT im very curious how deep of the dip it can buy :)  I would be liberal and trow in at least double of what is necessary, to be sure it sells and for a nice profit ;)
![rsigains](https://user-images.githubusercontent.com/5865016/33154867-b453c902-cfeb-11e7-981a-0b0bfe60ff9b.jpg)

**Comment by Concept211** [comment]
Is all of this referring to Gunbot? For instance, PT doesn't have "bbrsistepgain" and no TradingView integration.

**Comment by Utone** [comment]
i use a chrome tradingview extension no plugin, i have experience with the implementation from day one, just migrated some of my posts i thought would be helpful as for 127 rsi is on the to do list
