### ISSUE TITLE
Feature request: ALL_max_cost_percentage of the TCV instead of the available balance

### ISSUE THREAD

**Issue by nAffie** [taniman/profit-trailer#288]
Can there be an extra option or parameter to set ALL_max_cost_percentage to be calculated of the TCV instead of the available balance.
This so that the trade amount grows (or shrinks) with the TCV, and not with the available balance.

**Comment by TheGobOne** [comment]
Would love this so much. As your balance grows you use more thus really turning on the compounding aspect of the bot.

**Comment by Murtpoiss** [comment]
Same here ... would like to see it take the percentage of TCV instead of my available BTC ...

**Comment by johnnycash1** [comment]
Yes this would be a great addition to a already great bot

**Comment by jadiesel** [comment]
and available BTC... that can shrink to almost nothing, making new buys worthless. Or am I missing something?

**Comment by nAffie** [comment]
I even think it would miss out on trades if it's a percentage of the available balance and the trade amount would get below dust levels.

**Comment by antened** [comment]
yes, please add this feature

**Comment by AkliOnet** [comment]
I prefer the percent based on the available balance. But if Naffie and theGobOne want that I want it too ! ^^
