### ISSUE TITLE
Technical : Trailling profit = Smart

### ISSUE THREAD

**Issue by dechut** [taniman/profit-trailer#289]
i have 2 strategy for trailling profit .

strategy  1  . 

trailing profit = X% of total profit   .
example : X% = 30%
if total profit  = 1 % , then ALL_trailing_profit = 0.3
when total profit = 5% , then ALL_trailing_profit = 1.5
when total profit = 10% , then ALL_trailing_profit = 3  .

cons :  this strategy will work good with both small pump or big pump .
defs : when total profit too big ( > 20 % ) ALL_trailing_profit will big too , then we need a hard take profit , like if when total profit >= 30% , then panicsell .

strategy 2 .
multi step trailing profit . 

if total profit >1 % then ALL_trailing_profit = 0.3
if total profit >3 % then ALL_trailing_profit = 0.5
if total profit >5 % then ALL_trailing_profit = 1
if total profit >10 % then ALL_trailing_profit = 2
if total profit >30 % then ALL_trailing_profit = 0.1

cons : this strategy help us ride big wave pump very good .
defs : hard to config , hard to code .

**Comment by dechut** [comment]
update 1 .

in strategy 1 . 

we have 2 option to do .

1 - set ALL_FOMO_take_profit = 30
or
2 - set ALL_Maximum_trailing_profit = 5 .

**Comment by Antrazzz** [comment]
Good idea! I also thaught about it! But maybe the steps are not necessary if you use a linear adjustment of trailing.

Something like:
if profit <  1  ==> ALL_trailing_profit = 0.3 
if profit >  1  ==> ALL_trailing_profit = profit * 0.3

**Comment by MeisterPilaf** [comment]
this feature would be great!

**Comment by DemoFreak** [comment]
Good idea!

**Comment by Mikeeetrue** [comment]
I tried to use sell value over 30 with trail profit 5 and it only played versus me. For pump the most important thing is to use very low trailing profit to catch immediate price raise and not to lose the time and it goes down. So it's rather for market growth, but bad for pumps

**Comment by robheath90** [comment]
Mikeeetrue it's not necessarily bad for pumps though. If a coin pumps 50%, I'd much rather guarantee taking say 80% of the pump, than risk the bot selling at 30% of the pump because it hit my trailing limit. Having a hard trailing limit is a huge disadvantage at times because you cannot program for both gradual gains and rapid pumps. Whether it takes an hour, a week or a month, if I know the coin will sell at a fixed percentage below it's maximum, then I'm taking an appropriate amount of risk for an appropriate amount of gain.

**Comment by Utone** [comment]
In pumps that start to dump trailing profit can cost you a huge part of profit. So an RSI sell at 80-85 with the exception that mid sells before this are allowed would be the perfect solution.

so a non needs true, but if true = sell l (to avoid dunps and rapid price drops)

**Comment by taniman** [comment]
added to 2.1.0
