### ISSUE TITLE
Setting request: ignore maximum 24H% pair greater than xx%

### ISSUE THREAD

**Issue by joeyoon80** [taniman/profit-trailer#290]
I have an idea on avoiding pump and dump coins, which is to ignore coins that have a 24-hour % change greater than xx%. I notice that max_buy_spread = 1 can only hold off a coin for short period of time, as the spread tends to normalize after a while. the 24-hour change indicator lasts much longer, so if we ignore the coin that goes beyond, say, 25%. this could significantly reduce the pump and dump risk.

**Comment by mkarulin** [comment]
I already submitted this feature request in #219 :)

**Comment by xAndyxNL** [comment]
I would love this feature aswell, im seeing pairs that have increased +200% in 24hrs. You can just wait for those to get dumped eventually.
