### ISSUE TITLE
INFO DCAStrategyRunner - You are not allowed to buy. ...

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#293]
`INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance`

The above INFO log does not state for which currency pair, could that be added please?

**Comment by taniman** [comment]
Why would the currency matter in this case?

**Comment by louisswart** [comment]
When I later analyze the logs and currency pair graphs, this will enable me to see when PT wanted to do this action in order to evaluate my strategy. At the moment I see these entries but can not relate them to a coin pair.

**Comment by louisswart** [comment]
`INFO ProfitTrailerService - You are not allowed to buy. Sell Only mode is active for BTC-SWT`

Above is an INFO log that does report the currency pair. I suggest the following possibilities:

```
INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance when buying BTC-SWT
INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance (BTC-SWT)
INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance for BTC-SWT
INFO DCAStrategyRunner - You are not allowed to buy. Buying BTC-SWT will exceed min buy balance
```
