### ISSUE TITLE
Moving wiki to markdown files and use ReadTheDocs

### ISSUE THREAD

**Issue by lazywinadmin** [taniman/profit-trailer#296]
Would be nice to contribute to documentation.
Any plan to move the wiki pages to markdown files ?

You could use ReadTheDocs to generate the front end.

Example:

Editable page on github: https://github.com/rtfd/readthedocs.org/blob/master/docs/contribute.rst
Page on ReadTheDocs: https://docs.readthedocs.io/en/latest/contribute.html

**Comment by taniman** [comment]
We literally just moved the wiki over to wiki.profittrailer.io, :D

So unles docuwiki supports markdown, I do not think we will be moving ;)

**Comment by lazywinadmin** [comment]
Alright, just thought it would have been nice to have everything at the same place :)
