### ISSUE TITLE
[FEATURE] Limit simultaneous DCA pairs

### ISSUE THREAD

**Issue by RchGrav** [taniman/profit-trailer#299]
Setting to limit max DCA pairs..
*Wishlist - Value Ranking for Priority

max_dca_pairs = 1

**Comment by DadOfMad** [comment]
ohh snap did you change it to this today? or did i just write one that had already been brought up since i didnt see it?
its a brilliant idea... it really should be implemented

**Comment by Tomokrypto** [comment]
+1

**Comment by rshinall** [comment]
+1

**Comment by YoJeff** [comment]
#554
