### ISSUE TITLE
Possible alternative to avoid dangerous pumped coins: Create a filter by market cap with cmc or another source

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#303]
This has the effect to allow the bot to trade the peak (on the both side) on coins with big market cap and filter the dangerous peaks of the very pumped coins.

**Comment by Concept211** [comment]
This! We need smarter buys because all PT can do at the moment is bag hold.

**Comment by AkliOnet** [comment]
Exactly !! The thing is that the growth of bitcoin make the price of every coins falling days after days ! This is why we are forced to dca again and again ! until all our money is blocked after n days. If we look at the common price, the real value of coins which is expressed in usd,  the curve are the inverse,  there are mostly in grow (I saw that on more 60 coins) . So if we  come across a coins that is falling in usd plus we trade this coins on the btc market , to get out we don't need a double down we need a triple down ! I asked Elroy to add more exchange for that and add coinigy which offer most exchange(15$ but exchange also are not free) to have the most coins on USDT market(I know i also prefer getting btc than usdt) and eth market on which the curve of the price is more similar to the price in usd . But this two market is less active , unless if we have a lot of pairs available.
