### ISSUE TITLE
Stoploss sell not reported in ProfitTrailer.log

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#304]
Please report the stop-loss sell in the ProfitTrailer.log, example:

`INFO DCAStrategyRunner - DCA - Stoploss sell -- currency pair BTC-QTUM - current profit -5.4228875499043205`
or
`INFO NormalStrategyRunner - Normal Pair - Stoploss sell -- currency pair BTC-QTUM - current profit -5.4228875499043205`

**Comment by taniman** [comment]
Sorry gonna have to decline this. The idea is to develop the software in the GUI. Please read /monitoring/data to get a json file with the sell log. and in there you will find also that sale was triggered by stoploss. 

Most code in the console was put there for debugging reasons. Not to provide information
