### ISSUE TITLE
Dump protection & Smarter buys. Create a buy_value_limit for lowbb or other strats for the initial buy

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#306]
We assume that if the price goes down the price will go up so we buy. So even if the price go below lowbb 0 or -20% we buy ! whereas in fact it's at this time that we can avoid the falling coins. If the price go below lowbb -20 it has maybe 50% more chance to continu to fall .  With a buy_value_limit we avoid most of the time to a buy a falling coin and enter in dca and we can even avoid the buy on dump in a certain amount of time .

I think this solution is a lot more easy to implement than an second indicator (if the BB is provided by the exchang it's basicly just a If) 

<del>Otherwise for the buy trailling , I am not sur if the bot buy as soon as the price do a negative move bigger than our specified trailling value. But if it do so, as Diesel confirmed, we need to have the possibility to change this behavior ! (with a boolean property) As this make us buys before the price end its fall !! In a middle of a dump/ or an average price fall !</del>

**Comment by cvthub** [comment]
available in v2.0
