### ISSUE TITLE
DCA: Strategy HIGHBB triggers incorrectly [BUG]

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#309]
The stetting as shown below seem to cause DCA to buy at HIGHBB 50 instead of 0.
```
buy_strategy = HIGHBB
buy_value = 0
```

**Comment by taniman** [comment]
Please read the description of DCA HIGHBB carefully. This strategy works different than the other strategies. This is a deviation from the normal logic, and I think it's this behaviour that you are experiencing.

In DCA we actively display the current BB value and B trigger, if that value is incorrect I welcome you to reopen this issue

**Comment by louisswart** [comment]
I did see that the "buy_value" sign works different. 
Please verify if this behavior below is correct?

![2017-11-29 btc-ada highbb incorrect true](https://user-images.githubusercontent.com/29467849/33385468-5fecea10-d531-11e7-9984-df812f4dd3f8.JPG)

This is a clip from the monitor showing HIGHBB(true) while "BB / Trigger" is above the "Current Price".
I've given the setting for DCA.properties below that I think is applicable:
```
buy_strategy = HIGHBB
buy_value = 0
buy_trigger = -7.0
max_buy_times = 2 < I know this has been reached, but should not be in influence in the HIGHBB(true) signal.
```

**Comment by taniman** [comment]
The correct behaviour as depicted in your image  is.

Average price of 1252 is higher than HIGHBB trigger. 1105
so buy again

in other words.
if HIGHBB trigger (1105) goes below average bought price (1252). than we buy again.

**Comment by louisswart** [comment]
Okay I understand your description, there in then lies the misunderstanding. The dca.properties wiki does not state which price is being used when comparing the HIGHBB. This would explain why the DCA buys that I checked seems to be at random priced not related to the HIGHBB when compared to the Bittrex charts. Where as the HIGHBB with the initial buy exactly matched the Bittrex charts.

I would not expect the average price to be used as it is not related to the intention of the BB strategy. I would think that it is necessary to compare the current price to the current (HIGHBB + buy_value ) price in order to get the exact intend price as it would be on the Bittrex charts.

**Comment by taniman** [comment]
I totally aree with you. but this was implemented in the old days. when we had ties to another bot...  Let me reopen this issue and rewrite the highBB logic. 

let's break all ties

**Comment by louisswart** [comment]
Would it be possible to connect this to v1.2.6 instead?
