### ISSUE TITLE
Consecutive buy trigger prematurely active [BUG]

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#310]
When setting the pair specific consecutive buy trigger as shown below:
`BTC-XLM_consecutive_buy_trigger = 5`

The buys for the pair is immediately prevented after start-up and the ProfitTrailer.log shows: 
`INFO ProfitTrailerService - You are not allowed to buy. Sell Only mode is active for BTC-XLM`

When the pair specific consecutive buy trigger is removed and the ALL setting is used as shown below, the pair is bought:
`ALL_consecutive_buy_trigger = 5`

**Comment by taniman** [comment]
I suspect this to be coincidence. As the only difference between those 2 is that it reads a different property...

**Comment by louisswart** [comment]
I think I see the coincidence.

The BTC-XLM_consecutive_buy_trigger seem to relate to all coin buys and not the specific BTC-XLM_consecutive_buy_trigger buys. Thus blocking the specific coin based on the all coin buy count.

This is then not a but, just a misunderstanding.
