### ISSUE TITLE
ProfitTrailer.log: "You are not allowed to buy/sell" needs more information

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#311]
In the the ProfitTrailer.log, need to know what setting is causing this, e.g: _consecutive_sell_trigger, _btc_price_rise_trigger, _btc_price_drop_trigger, ...

`INFO ProfitTrailerService - You are not allowed to buy. Sell Only mode is active for BTC-BTG`

Suggested:

```
INFO ProfitTrailerService - You are not allowed to buy because BTC-BTG consecutive sell trigger(3). Sell Only mode is active for BTC-BTG
INFO ProfitTrailerService - You are not allowed to buy because ALL btc price rise trigger(5%) is at 6.3%. Sell Only mode is active for BTC-BTG
```

Then on the Telegram message, need to know which pair please, the ProfitTrailer.log does give the pair but not the reason:
```
ProfitTrailer.log:
   2017-11-28 16:28:58 INFO ProfitTrailerService - You are not allowed to buy. Sell Only mode is active for BTC-DASH
Telegram at 16:28:
   PT: Bittrex - Consecutive Buys - Global Sell Only Mode Enabled
```
Suggested:

`PT: Bittrex - Consecutive buys(3) - Global sell only mode enabled for BTC-BTG`

**Comment by jadiesel** [comment]
Doesn't the tooltip hovering over the SOM label on the monitor tell you this? (I'm asking because I don't use the triggers)

**Comment by louisswart** [comment]
I do not use the monitor much, so I do not know.

I changed some setting just to find that more than half a day's buys were blocked by SOM and it took a few tries to find out which setting it was.

I use the ProfitTrailer.log and the exchange charts to evaluate ProfitTrailer's decisions to refine strategy as often as possible because of the dynamic nature of the markets. This ends up a time consuming effort when looking at 30 pair. So, at the log entry where the ProfitTrailer's decision is noted, its good to have all the information at hand that the decision was based on as well as the result of the decision. This speeds up the evaluation process if you don't have to jump around too much to find relevant information. At the point where ProfitTrailer makes the decision it has the relevant information, so it just needs to write it into the log.

**Comment by taniman** [comment]
I see wheere you are going with this. But the idea is to not clutter the logs. The logs should be reserved for some special cases. But seeing as this line is already logged I can check to see if the information you request can be added to it

**Comment by taniman** [comment]
Yeah, looking at your request a bit better, it is not just a simple change. When the bot tries to buy. we only check if a boolean is true or false. All the information you want to see are not readily available at that moment without doing extra work. 

I can add some quick wins for you though.

About the telegram message. it is a 1 time message. So this one will not indicate the currencPair. I will not change that one as there is no added value.

**Comment by louisswart** [comment]
Yeah, logging is an art, you never know what to log until you need to know something after the fact.

I think the best effort is to at least have the decision's input and output. Especially for your purpose of logging where a clients says something went wrong.  Because the settings create so many complex scenarios and are tweaked so often, a log entry of moments ago might have previous setting and then its difficult to know if the client made a setting error or if there is really a bug. 

I did find this elusive button on the the monitor called "Excel", that gives a very good end result summery, but still not the decision parameters. 

This is such an amazing project, I'm actually jealous of not being part of the development team.

**Comment by louisswart** [comment]
No need to rush anything, as this is a request, not a bug.
