### ISSUE TITLE
DCA: Pair specific enabled trigger not working [BUG]

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#315]
It seems that the BTC-COIN_DCA_enabled_trigger does not work, the pair stays in the "Pairs Log" and does not move to the "DCA Log"
```
BTC-ETH_DCA_enabled = false
BTC-ETH_DCA_enabled_trigger = -3.0
```

The following settings does work:
```
ALL_DCA_enabled = false
ALL_DCA_enabled_trigger = -3.0
```

**Comment by taniman** [comment]
Yup, I see it now.  Tnx. will fix it
