### ISSUE TITLE
Binance EMAGAIN not buying

### ISSUE THREAD

**Issue by jadiesel** [taniman/profit-trailer#318]
40 BTC pairs waiting on an EMAGAIN of -0.5.  I'm not sure what the values were showing in the monitor, but they were not emagain levels.  I charted a few, and some of the coins were well below the ema, and none matched the value being displayed in the buy log. and no buys.

When I switched on lowbb, bam, started getting buys.

**Comment by jadiesel** [comment]
Crap. Not getting buys, but it is trying to buy.  I am getting the same error I was getting on USDT. But on my BTC account which was working earlier today. Now it hits the lowbb and starts trailing, but won't buy - it gives me the error below:

0|BI BTC   | 2017-11-29 03:09 +01:00: 2017-11-29 03:09:11 INFO ProfitTrailerService - Occured in 24hInfo, result: Market Symbol should be ending with BTC, ETH oir USDT. Example: BQXBTC
0|BI BTC   | 2017-11-29 03:09 +01:00: 2017-11-29 03:09:19 INFO ProfitTrailerService - Occured in volume, result: Market Symbol should be ending with BTC, ETH oir USDT. Example: BQXBTC
0|BI BTC   | 2017-11-29 03:09 +01:00: 2017-11-29 03:09:39 INFO ProfitTrailerService - Occured in 24hInfo, result: Market Symbol should be ending with BTC, ETH oir USDT. Example: BQXBTC

**Comment by taniman** [comment]
any problems since the latest releases?

**Comment by jadiesel** [comment]
Just switched back to emagain to test. emaspread was working great though.

**Comment by jadiesel** [comment]
0|BI BTC   | 2017-12-01 22:45 +01:00: 2017-12-01 22:45:03 ERROR ProfitTrailerService - nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
0|BI BTC   | 2017-12-01 22:45 +01:00: 2017-12-01 22:45:03 INFO ProfitTrailerService - Occured in buy, result:
![image](https://user-images.githubusercontent.com/20715803/33504840-1a5696cc-d6b7-11e7-8a97-bd2acaba2eac.png)

EMAGAIN -0.1, trail .1

I had 10 coins trailing, and a lot of those errors above. Finally made a buy of KMD - but there should have been more buys.

Set it to trail 0, and it bought the coins at the right ema...


0|BI BTC   | 2017-12-01 22:54 +01:00: 2017-12-01 22:54:28 INFO ProfitTrailerService - Buy order for QSPBTC -- {"symbol":"QSPBTC","orderId":884728,"clientOrderId":"nDjtK7KpbzNzXoo2sV5kCO","transactTime":1512165268078,"price":"0.00001065","origQty":"235.00000000","executedQty":"235.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|BI BTC   | 2017-12-01 22:54 +01:00: 2017-12-01 22:54:34 INFO ProfitTrailerService - Get order information -- {"symbol":"QSPBTC","orderId":884728,"clientOrderId":"nDjtK7KpbzNzXoo2sV5kCO","price":0.00001065,"origQty":235.00000000,"executedQty":235.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1512165268078}
0|BI BTC   | 2017-12-01 22:54 +01:00: 2017-12-01 22:54:34 INFO NormalStrategyRunner - Normal Pair - EMAGAIN bought -- currency pair QSPBTC
0|BI BTC   | 2017-12-01 22:54 +01:00: 2017-12-01 22:54:40 ERROR GainStrategyRunner - An error occured
0|BI BTC   | java.util.ConcurrentModificationException: null
0|BI BTC   |    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_151]
0|BI BTC   |    at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_151]
0|BI BTC   |    at java.util.AbstractCollection.toArray(AbstractCollection.java:141) ~[?:1.8.0_151]
0|BI BTC   |    at java.util.ArrayList.<init>(ArrayList.java:178) ~[?:1.8.0_151]

So - it buys, but I need to let it run for a few hours t see how that trail is actually working.
I also noticed it takes a long time to update after a config change, much more so that Trex or Polo. Could be me though.

**Comment by zvaran** [comment]
Hello, I also have a similar issue, but I do not get the error above. I get no errors, it just doesn't want to buy...it's been like this for 8 hours already.  

Submitted a ticket on profittrailer.io a couple moments ago.
