### ISSUE TITLE
Create a better DCA - Based on Prefix. The balance is power and it's only what we have.

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#319]
I will complete this feature request later, just a draft(need to spleep) to not forget

The goal is to accelerate at the maximum the speed at which we sell all the bags in DCA, make the flow of the balance better and let the bot solve the bad situtation itself . Suppose we have a very big balance we could get out of any bad bigs bags situation right ?(almost) very very quickly compared to days (1->30 days). So as balance is Power in trading, particularly for us as our main strat is the double down, we need to sell out our bags aas soon as possible.

First we need to merge the Default DCA with the Anderson as the first assure us to only buy at the best time so with lowbb 10 or 0 and the Anderson strat is just a serie of trigger that allows us to create our own purchasing strategy with triggers positioned irregularly if desired.

**The idea is to have something like that**

Range_1 = 2.0-5.9 // We set our range 
Range_2 = 6.0-13
Range_3 = 13-23
...
**And then, it's simple, the conf that apply is the one in which the current price diff is in the range.**

buy_strategy = LOWBB
sell_strategy = GAIN

Range_1_buy_value = 15
Range_1_trailing_buy = 0.40
Range_1_sell_value = 0.55
Range_1_sell_trigger = 0.55
Range_1_trailing_profit = 0.20

Range_2_buy_value = 5
.............

One of the big advantage of using range is that it's the best way to characterise the situation of a buy and it help us reduce the number of double down with specific lowbb, trailling, spread ... 

**With that we can treat the difference situation with specific settings without adding complexity in the code . Simplicity is the best strategy in front of complexity..**

Then there is the problem of priority. There are two situtation : the situation where we have not accumulated bags and the other where we have accumulated too much bags.

When we do't have a lot of bags we can let the bot take the oportunities to buy freely but we need to prevent the accumulation of bags. 

When we have accumulated a lot of bags we need a strategy to refill our balance step by step to dca the big bags.

**Strategy to prevent the accumulation of bags.**
Simple fact : oportunities need to be valued, but an oportunity to buy at -3 is better than an oportunity to buy at -12%.
So let the dca run freely but just wait that All coins in range 1 end their trailing and then allow the buy for range 2 .. coins. Same for range 2 coins : wait range 2 coins trailling and then allow range 3 coins buys. 

**Strategy to refill our balance step by step**

Now currently you know that happen every 3 days, the bot will double the units of coin at -12% or more on which we already put one third of our balance with 6 dca. So after this buy we have no more balance and you know the suite (wait and loose).

There are three simple facts : 
A buy at - 3% has a lot more chance to raise the 1.00% than a buy at -12%. 
A buy at -3% will use less balance if it dca as there is lot more chance that it has still triggered any double down than a buy at -12%. 
A buy at -3% which has triggered 5 double down will use a lot of our balance compared to a buy at -12% which has triggered 3 double down, but it has a lot more chance to refill our balance compared to the -12% buy.

With a simple priority for the coins which are in the first range (the more close to the positity) we can get out each coin one after the other as our balance is refilled whereas the other range wait (as they go dowwn , it's better to wait ! no more -20% with 6 double down! ). 

So as soon as we have too much bags we need to trigger this strategy so this give :

Range_1_max_pairs = 10   
Range_2_max_pairs = 5  
Range_3_max_pairs = 2  
 
So now if they is more than 10 pairs in the range 1, only this range is allowed to dca. The range 2 and 3 will not double down before we have less than 10 pairs in the range 1. Same behaviour if we have more than 5 pairs in the range 2:  only the range 2 will be allowed to buy, not the range 3. <del>Not even the range 1 ? we can have a boolean property strict_priority.. to choose. </del>The range 1 need to be allowed to not break the logic of "three simple facts" and because most coins at -3% go -10, -20 after x time on the btc market.see https://github.com/taniman/profit-trailer/issues/303#issuecomment-347289442 .

With that the bot will solve the bags problem itself !

**As we all know**, bigs bags with big negative Profit% is the best indicator of the situation (better than max_trading_pairs). So now that we have range we can trigger the SOM as soon as we have 7 coins in the -6.0-13 range if we want.

sell_only_mode = range_2 // it will trigger it if they are more pairs than Range_2_max_pairs value.

**Then the other problem is that we apply the double down on every situation**. We need to have the possibility to adjust the money we put in dca for the different situation. For a -2.5 the situation is not dangerous I want to do a X1.7 , but for a -15 I know that there is bigger chance that the coin go -23 ... I want to do a X2.4 (this is financialy possible because for example for -2.5-4.5 I only done a 1.7) to stop this dangerous coin that will make me lose money.

So this give : 

Range_1_coefficient = 1.6 // Here we cut 
Range_2_coefficient = 2.0 // Here we really cut 
Range_3_coefficient = 2.4 // Here we really really cut 
...

Here the strategy is good but it will be also good to have an alternative to the double down, an Auto Coeff which average at the current price so when we dca ,we don't dca by hoping that the price increase what is needed to be 1% above our average price , but we average to be at 0% by hoping than the price just increase of 1%.  So Range_5_coefficient = Auto

The solution In resume :
Range prefix : Range_1 , Range_2
Priority for inferior range trailling
Range max pair : Range_1_max_pairs
Range DCA coeff : Range_1_coefficient

For now if we cannot have that for the next version.. it will be good to just let ALL_DCA_enabled_trigger accept a range so if the situation is bad we can treat each bags by range on our phone :) to refill the balance so we don't need to double down manually on the exchange, so by default we will put  -2.5:-60 and with a bad situation  -2.5:-6 , then -6.1:-13 ... until all the bags are sold.

**Comment by taniman** [comment]
Too complicated
