### ISSUE TITLE
Feature Request: Plugin Development API

### ISSUE THREAD

**Issue by colinmasters** [taniman/profit-trailer#320]
Develop a plugin API that exposes certain features and functions to plugin developers to allow us to enhance the PT offering.

Initial Features Requested:

Broadcast
- Pre-buy signal
- Buy initiated
- Pre-sell signal
- Sell initiated
- Allow a BUY/SELL/MODIFY/CANCEL response to any of the above broadcast events

Request
- PTQuote - An exact state of a coin before strategies have been applied
- PTTick - An exact state of a coin at any given requested second AFTER strategies have been evaluated, along with weighted information on where the strategy currently sits

- BUY order
- SELL order
- CANCEL order
- MODIFY order

**Comment by Concept211** [comment]
YES! I would definitely take advantage of this. In turn, this would help out Elroy and the PT community.

**Comment by mkarulin** [comment]
For an actual API he would need more full time developers :) mabe an URL to trigger an sell or buy of a particular coin would be an easy start.

**Comment by AkliOnet** [comment]
I think it's better to first make PT profitable, by focusing on the things that make it no profitable :
(sorted by simplicity to implement / and impact)

1. Stop buying when the market go in direction to a bad state of the market with the trend indicator. This will make PT  more unstopable but we will still end with accumulated bags
2. Success is all about prioritizing the balance than holding bags, Let the bot clear the dca trades the the most quickly and let it resolve the Big bags problems itself #319 . With the SOM on Trend, this will make the bot UNSTOPABLE
3. Avoid the Dump, A limit buy value can easily filter falling coin #306  . But it's not perfect, it's a complexe task, Elroy thought about a second a lot more slow indicator, or third(if EMASPREAD..) .

After that come the API ... It's quicker to make it profitable working on PT directly than to create an API to make it profitable . I think

**Comment by AkliOnet** [comment]
And it's probably quicker to build a bot directly

**Comment by Concept211** [comment]
Agreed. This is definitely lower priority because for weeks now I haven't even been able to use the bot due to severely heavy bags accumulated in DCA.

**Comment by colinmasters** [comment]
None of these comments are helpful or are aimed at the issue being discussed, if you have an issue, open it, do not hijack other threads to complain.

**Comment by alexpica** [comment]
Getting back to the original thread topic, I do agree a Plugin API would be great!

**Comment by taniman** [comment]
Will continue with #272
