### ISSUE TITLE
Panic_Buy_USDT after panic sell

### ISSUE THREAD

**Issue by BotWaldo** [taniman/profit-trailer#325]
So today has been quite a bad day and i tried to stay ontop of it thinking it was going to stop being nuts around 7 am i went to sleep @11KBTC... to wake up at 11am to a 8KBTC. in which my STOPLOSS was triggered and sold my big bags because of the % drop. something i wouldn't have done myself. but that is my bad for sure. BUT in this loss comes an idea for a feature and i hear that this is a known bug. so here is my idea:

PANIC_Buy_USDT = +-10% BTC trend
BTC-USDT_panic_buy_enabled = true
#all my BTC buys USDT and holds it there in tether when it goes crazy +-10%? 

or is that a bad idea? thoughts?

**Comment by taniman** [comment]
not really liking the idea. we might add some buttons soon
