### ISSUE TITLE
[Help] Running 2 bots

### ISSUE THREAD

**Issue by proxyLegs** [taniman/profit-trailer#328]
Probably is a silly question, but do I need 2 licenses to run two bots in different markets?

I can't seem to run two instances of PT, one trading in BTC and the other in USDT, without trades appearing in both DCA and/ or Pair logs. Each instance has a different API key for trading, but the same license key. I've tried the wiki's guide but with the current build, market specific API prefixes no longer apply. I've also tried setting the bought_price and override_bought_price, but then each bot tries to sell or DCA the other's trades.

Any help would be greatful

Thanks

**Comment by jadiesel** [comment]
You need to run two seperate accounts to trade on, one for BTC and one for USDT. You bots have no idea how to seperate the orders because they are intermingled on one account.

**Comment by proxyLegs** [comment]
I've just tried using a different account for the trading_apiKey but still no luck, do you mean I will need a different default_apiKey instead for each bot?
