### ISSUE TITLE
[Idea] DCA Scale

### ISSUE THREAD

**Issue by proxyLegs** [taniman/profit-trailer#332]
I was wondering if you could add in a DCA scale that controls the amount at which DCA will buy. 

Something like 100% being the normal doubling each trigger 

Example:

`DCA_scale = 75 (percent)`

therefore the trigger amounts would be the following

```
trigger 1 amount: 75% of original
trigger 2 amount: 75% of trigger 1 amount
trigger 3 amount: 75% of trigger 2 amount
```

or conversely

```
DCA_scale = 120 (percent)

trigger 1 amount: 120% of original
trigger 2 amount: 120% of trigger 1 amount
trigger 3 amount: 120% of trigger 2 amount
```

Either that or have the ability to change the DCA scale for each trigger, like:

```
trigger_1_DCA_Scale = 75
trigger_2_DCA_Scale = 100
trigger_3_DCA_Scale = 125
```

Let me know what you think?

**Comment by Anderson-PB** [comment]
message me on telegram @anderson_drsub for help with that.
