### ISSUE TITLE
Alternative BTC rise/drop triggers for SOM

### ISSUE THREAD

**Issue by nocturnal86** [taniman/profit-trailer#333]
The thought is, every user to be able to specify a BTC price range, where the SOM goes in action.

For example, let's suppose we have BTC on a steady price range of 9.400-9.700 a week now.

So the user will put a command on the bot "9.100-10.300_enable_SOM" & SOM will be enabled only when BTC price goes above 10.300 or under 9.100.

Studying the overall recent pump & dumps of BTC i noticed that our current SOM triggers were enabled many hours, while BTC came back to steady levels and was very safe to trade.

The current 24h triggers calculate percentage difference of BTC, according to the price BTC was, the exact time 24h ago. So for example if BTC went crazy last night and went to 11.000 and today is at steady levels 10.000 for hours, the percentage difference will be -9% and will put the bot in SOM wrongly.

With these alternative triggers, each user will specify at the time being, which range consider as safe to trade and as time goes by, will adjust the range according to future BTC steady prices.

**Comment by taniman** [comment]
There is also a request open to use flexible instead of 24 hours trigger. This might also make the bot more exact

**Comment by nocturnal86** [comment]
Yeap those requests are exactly on point and improvise my idea.

https://github.com/taniman/profit-trailer/issues/420

https://github.com/taniman/profit-trailer/issues/196
