### ISSUE TITLE
Configurable base URLs

### ISSUE THREAD

**Issue by skazazes** [taniman/profit-trailer#336]
Being able to specify some sort of base URL to be dynamically sued on a per instance basis would be nice. At the moment to host multiple bots from the same server and port, you must use Nginx and subdomains. This would make hosting multiple instances of the bot significantly easier especially when considering automation

Allowing a configurable URL would in theory enable a url scheme as follows.

domain.com/bot1/monitoring
domain.com/bot2/monitoring

domain.com/bot1 
domain.com/bot2 

being the proposed base URLS

**Comment by mgladwin** [comment]
I have wanted to run Profit Trailer behind nginx reverse proxy. I think this base URL needs to be set before it will work the way i want it to?

**Comment by taniman** [comment]
Added support in 2.1.0
