### ISSUE TITLE
Overriden Sellonly still buying after sell?

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#338]

**Comment by mirrormirage0** [comment]
I have the same issue.
Even after enabling SELL ONLY MODE (tried manual, URL, global setting, individual pair setting etc..) 
Profit trailer continues to buy

**Comment by nibarulabs** [comment]
I'm seeing this happen pretty consistently.

Tried to set ALL_max_trading_pairs = 0 to see if this would be a workaround..

**Comment by nibarulabs** [comment]
@taniman do we know what version(s) this affects?

**Comment by nibarulabs** [comment]
I think should be a really high priority because I am seeing that this prevents clearing out bags and dca list. Dca will still continue to buy and this overrides SOM completely. Even with these two configs set

**Comment by taniman** [comment]
@nibarulabs I think you may be getting 2  things confused.  This issue is more about initial buys. Can yo sent me your settings? Because if you have in DCA ignore_sell_only_mode = true. than DCA will keep on buying

**Comment by taniman** [comment]
should be fixed in 1.2.6-B6 else we reopen this
