### ISSUE TITLE
Overridden disabled stoploss not working with dca?

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#339]

**Comment by smportis** [comment]
Stop loss only works for a specific coin override in Pairs. DCA is a flat stop loss setting for all. 

I believe that this should be changed. 

Suggestion would be to add a DCA coin specific stop loss, or a flag in the Pairs area to set per coin that would “follow” it into the DCA area. 

Pairs file:
BTC-ETH_stop_loss_trigger= -15 
# *** NEW FLAG - Tells bot to honor the stop loss, even during DCA ***
BTC-ETH_stop_loss_DCA= true 

Or DCA File:
# *** NEW SETTING - Tells bot to stop loss during DCA ***
BTC-ETH_stop_loss_trigger= -15

I guess the latter would be cleaner for the end user to remember that is affecting his or her DCA settings. 

If the stop was lower or in the middle of, say, the Anderson DCA limits, it would simply sell when the limit was reached. 

I’m not saying this is the biggest issue out there but to me it’s a medium to high that’s cost me 2x now. Others can comment on their opinions. If seen as valid I’ll add a github entry.
