### ISSUE TITLE
No Sales Log

### ISSUE THREAD

**Issue by mwelkins** [taniman/profit-trailer#341]
Sales log has no entries.
Monitoring Page; Profit Last Week, Profit Yesterday, Profit Today remain at 0.00000000

-over 100 sells verified on Bittrex
-trading.logHistory = 7, not commented out
-/logs directory exists, rwxr-xr-x
-ProfitTrailer.log exists and is being written to, rw-r--r--, no other log files
-verified API keys and no whitespace in string
-originally installed on Amazon AWS Windows server and had this issue
-new install on Vultr Ubuntu server, clean install, nothing copied or moved over, same issue

**Comment by taniman** [comment]
Did PT sell all these 100 items? 
The bot will only display sales log for coins it has sold it self. This data is stored in ProfitTrailerData.json
So if the bot sold these items and the ProfitTrailerData is not corrupted, you will see a sales log. and thus profit calculations

**Comment by mwelkins** [comment]
Yes, the bot did all the selling.

**Comment by mwelkins** [comment]
I cleared ProfitTrailerData.json. It was 27k. Nothing had been written to it since the very first time I started the bot. I restarted it and it did write the exact same 27k to the file. So it can write to the file, it just doesn't want to?

**Comment by taniman** [comment]
hmm. that's strange. But once it's gone, it's gone. So you will have to wait on some new sells

**Comment by mwelkins** [comment]
Bot has 100's of new sells. Looks like ProfitTrailerData.json is being written to. File size and timestamp keeps changing, however there are no sold orders showing.

**Comment by taniman** [comment]
can you contact me on telegram? @elroy
