### ISSUE TITLE
Problems with SOM

### ISSUE THREAD

**Issue by nibarulabs** [taniman/profit-trailer#345]
I have a bot that has config files generated with Feeder. Stopped Feeder after seeing SOM mode being ignored and tried to just troubleshoot the generated properties files.

**The problem: the bot bought (and then sold) MTL when SOM was on.**

![mtl-trade](https://user-images.githubusercontent.com/22958894/33528772-19ac6656-d81b-11e7-932b-2d1fc3220a79.png)

Looking at the logs, here are the entries for what I think the buy/sell are:

```
Dec  3 18:54:36 ip-172-31-83-178 profittrailer[5701]: 2017-12-03 18:54:36 INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance

Dec  3 18:56:57 ip-172-31-83-178 profittrailer[5701]: 2017-12-03 18:56:57 INFO ProfitTrailerService - Sell order for BTC-MTL -- {"OrderId":"799d32e8-09d7-48e8-bb42-da8a49d25603","MarketName":"BTC-MTL","MarketCurrency":"MTL","BuyOrSell":"Sell","OrderType":"LIMIT","Quantity":9.26303308,"Rate":0.00054680}
```

You'll notice the buy message that it would exceed the min balance. However, the next log entry is that MTL has a sell order.

If you look at the image times, the hours are off (because of TZ) but the minutes and seconds are on or very close - close enough to be probably _correct_.

PAIRS.properties

```
ALL_min_buy_balance = 0.5

ALL_btc_price_drop_trigger = 0
ALL_btc_price_drop_recover_trigger = 0

ALL_btc_price_rise_trigger = 0
ALL_btc_price_rise_recover_trigger = 0

ALL_consecutive_buy_trigger = 8
ALL_consecutive_sell_trigger = 3

ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0.8

All_stop_loss_trigger = -100

ALL_max_buy_spread = 1

# ---------------USING 01-superbear. WRITTEN ON Sun, 03 Dec 2017 13:08:54 GMT---------------

MARKET = BTC
ALL_trading_enabled = false
ALL_buy_strategy = LOWBB
ALL_buy_value = 30
ALL_sell_strategy = GAIN
ALL_sell_value = 0.8
ALL_trailing_profit = 0.3
ALL_trailing_buy = 0.3
ALL_DCA_enabled = true
ALL_min_buy_volume = 300
ALL_min_buy_price = 0.00000001
ALL_min_profit = 1
ALL_enabled_pairs= ALL
ALL_panic_sell_enabled = false
ALL_sell_only_mode = true
ALL_max_cost = 0.05
ALL_max_trading_pairs = 5

# MTL has been set to SELL ONLY mode
# Reason: Sell only mode activated for market condition
# Volume was 338.2229061
# Actual trailing profit was 0.7426
# Notes: 
BTC-MTL_trading_enabled = true
BTC-MTL_trailing_profit = 0.255
BTC-MTL_DCA_enabled = true
BTC-MTL_sell_value = 0.8
BTC-MTL_sell_only_mode = true
```

DCA.properties

```
enabled = true
max_cost = 0.16
max_buy_times = 6

buy_strategy = ANDERSON
buy_style = DOUBLEDOWN

buy_trigger_1 = -7
buy_trigger_2 = -9
buy_trigger_3 = -9
buy_trigger_4 = -11
buy_trigger_5 = -11
buy_trigger_6 = -15

sell_strategy = GAIN
stop_loss_trigger = -100
max_buy_spread = 1
min_buy_balance = 0.50
buy_available_volume_trigger = 100
pending_order_wait_time = 0
ignore_sell_only_mode = false

# ---------------USING 01-superbear. WRITTEN ON Sun, 03 Dec 2017 13:08:55 GMT---------------

trailing_profit = 0.15
trailing_buy = 0.15
sell_value = 0.8
```

Few things to note:

* ALL som is set to false, but MTL overrides it to true
* DCA is not set to ignore SOM mode

Questions:
---

1. Why would the bot be buying, first question.
2. Second more minor question is why isn't that buy logged?

v1.2.5.5 (same thing happened with 1.2.5.6, 1.2.5.7, 1.2.5.6-B6)

**Comment by taniman** [comment]
Aaah. So its not the bot buying. All and I will put my hand in fire. But all buys and sells are logged. So you got a rogue bot somewhere buying stuff. Or you missed something in your logs

**Comment by taniman** [comment]
Also I see a sell and a buy. In your bittrex log. You mean to say that that buy that got sold should not have happened?

**Comment by nibarulabs** [comment]
So the buy happened at 10:54p, the sell happened at 10:56p.

The buy should not have happened at all and there is no log of it - only that entry "You are not allowed to buy. Buy will exceed min buy balance".

I have the same entry in the ProfitTrailer.log and the linux syslog. No where is it logging buys.

There was only java process running.

Nothing was changed in the configs regarding logging and even if there were a rogue bot running, for instance, I would think it would still log buys as well as sells.

I did notice that the next few seconds after the sell, the order information came back with no account id...?

```
2017-12-03 18:57:03 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"799d32e8-09d7-48e8-bb42-da8a49d25603","Exchange":"BTC-MTL","Type":"LIMIT_SELL","Quantity":9.26303308,"QuantityRemaining":0.00000000,"Limit":0.00054680,"Reserved":9.26303308,"ReserveRemaining":9.26303308,"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00001279,"Price":0.00511773,"PricePerUnit":0.00055248000000000000,"Opened":"2017-12-03T18:56:58.257","Closed":"2017-12-03T18:56:58.32","IsOpen":false,"Sentinel":"260850bc-b3d9-41ce-bba4-6b982daa9789","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
```

The sell worked, so I'm guessing that's not a big issue.

The big thing is just that there should be a buy order logged and it isn't, which is probably connected somehow to SOM being ignored.

**Comment by taniman** [comment]
There is only 1 place to do buys. And unless there is an exception thrown. the very next line after a buy is this
logger.info(String.format("Buy order for %s -- %s", currencyPair, result));

So this line is always displayed after a buy.

![image](https://user-images.githubusercontent.com/6751341/33530224-dd6c261a-d87c-11e7-8e7f-f16dc6a37273.png)

That's why I am betting on some other running bot doing the buying. So check if you hae anothe PT running or something

**Comment by nibarulabs** [comment]
Bot was moved off to a different vps and the issue went away. So, somehow, it does look like another process was running or api keys were being used elsewhere. Thanks.
