### ISSUE TITLE
Feature Request: Separate passwords for monitoring and config

### ISSUE THREAD

**Issue by blastoplast** [taniman/profit-trailer#347]
My friends and I monitor each other's bots, would be cool to have a monitor-only password so that I didn't have to give config access to people.

**Comment by skazazes** [comment]
Was about to come post the same thing. The no-user simplicity is amazing, but just having one password that would enable editing and one that wouldn't would be amazing.

**Comment by cvthub** [comment]
A role based auth will be available in next release, with a role which is able to change configurations and another which can only access the monitoring. Furthermore, a possibility to logout from PT will be available.

**Comment by mayday79** [comment]
Any News regarding this Feature? We are on .21 now and it is still not available.
