### ISSUE TITLE
[FEATURE] Adjustable window for BTC Rise / Lower Trigger

### ISSUE THREAD

**Issue by robn1972** [taniman/profit-trailer#349]
I’d like to see a setting for a changeable interval for btc price rise sell only trigger.  I believe this would be more effective if it used a rolling hourly percentage instead of 24 hours.  Market sentiment changes quickly and basing this on shorter intervals can possibly avoid some bags and also allow the bot to jump back in faster.

**Comment by taniman** [comment]
See #196
