### ISSUE TITLE
MalformedJsonException - Binance error in log output

### ISSUE THREAD

**Issue by christianlanz** [taniman/profit-trailer#350]
The bot is up and running but I think the communication to Binance does not really work yet.

I'm periodically seeing this error in my logs:

```
ERROR ProfitTrailerService - Handled exception com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
```

**Comment by christianlanz** [comment]
My bot is up and running, but this error keeps showing in the logs

**Comment by InsomniakSam** [comment]
i have the same issue, downloaded the latest version and just copied my setting from bittrex

**Comment by taniman** [comment]
This was a binance API issue. Caused by binance update
