### ISSUE TITLE
[Feature] Exclude pairs that gained more than x% in the past 24 hours

### ISSUE THREAD

**Issue by christianlanz** [taniman/profit-trailer#351]
I'd love a setting to disable trading for pairs that gained over x% in the past 24 hours.

I think this could preventing buying any pump and dump coins.

Could look something like that (in PAIRS.properties):

```
ALL_disable_trading_for_pairs_with_gain_greater_than_percent = 30
```

**Comment by smportis** [comment]
Upvote for this.

**Comment by taniman** [comment]
There is already an issue open for this. Try to search before adding please.
See #219
