### ISSUE TITLE
[GUI] Panic Sell button for each pair in DCA log

### ISSUE THREAD

**Issue by d1rt** [taniman/profit-trailer#353]

**Comment by taniman** [comment]
I need more description. What are you trying to achieve?

**Comment by Fogazi** [comment]
I think d1rt wants a button on the GUI that you can click to panic sell an individual pair in the DCA log.

**Comment by d1rt** [comment]
Yes, Fogazi is right.

**Comment by cryptt** [comment]
I like this idea but only when the button is clicked it asks for confirmation eg sure? or cancel.
And also if the button would be clicked PT would only try to sell it once and doesn't leave it in PANIC sell mode. You want to try again, didn't fill the order or only partial? click again ;)

**Comment by taniman** [comment]
Buttons will come soon enough
