### ISSUE TITLE
[GUI] Translation files

### ISSUE THREAD

**Issue by mrlex** [taniman/profit-trailer#354]
Hi, 

Would it be possible to implement translation files that we could edit ourselfs? That way we could have the bot in different languages and you would'nt have to do all the hard work. 

Just an idea :)

**Comment by djcrypto75** [comment]
If done with translations from my side yes. Will look into it.

**Comment by mrlex** [comment]
Great, thank you very much sir! :)

**Comment by djcrypto75** [comment]
in the works now, will close this one.
