### ISSUE TITLE
Trex null pointer status in webui

### ISSUE THREAD

**Issue by skazazes** [taniman/profit-trailer#355]
Would be nice if there was an indicator similar to the SOM ones now, just lets you know it the exchange API the bot is on is currently responding favorably. Similar to the case of the bittrex api null pointer

I realized the only reason I SSH to my bot nowadays, is to run pm2 log on a screen so i know if the bot goes down. Would be nice to be free from that

**Comment by taniman** [comment]
Well we are working on a way to auto restart the bot.
Also you can currently access your log. al be it unformatted with. /monitoring/log

We are also working on adding a notification panel.
