### ISSUE TITLE
Binance BTC price rise/fall trigger problems

### ISSUE THREAD

**Issue by danenright** [taniman/profit-trailer#358]
I keep seeing BTC SOM kick in and out in a strange fashion, as compared to Bittrex.

Both bots are using the same settings but it seems that Binance does it's own thing, this happened in quick succession (within a minute):

Dan's BinanceBot - BTC Price Drop Recovered! Global Sell Only Mode Disabled
Dan's BinanceBot - BTC Price Rise! Global Sell Only Mode Enabled
Dan's BinanceBot - BTC Price Rise Recovered! Global Sell Only Mode Disabled

**Comment by InsomniakSam** [comment]
Your problem is the same as this open issues. Check you logs am i right ?
#350

**Comment by danenright** [comment]
Ah yes, this is the same issue

**Comment by christianlanz** [comment]
Actually I think this is not the same issue. I experience the same strange BTC price drop / rise behavior.

![image](https://user-images.githubusercontent.com/6087393/33599356-32d1fa56-d9a6-11e7-94bc-bfea7db5e9f2.png)

Within a matter of seconds SOM gets enabled and disabled.

**Comment by mkarulin** [comment]
Same here on Binance. Trend: (5.16 % 24H)  BTC: 11647.25 (4.52 %) Rise 3 Recovery 2
every minute or so i get a telegram message:
Binance BTC - BTC Price Rise! Global Sell Only Mode Enabled
Binance BTC - BTC Price Rise Recovered! Global Sell Only Mode Disabled
Also when i reload the page the SOM is sometimes on and sometimes off.

**Comment by christianlanz** [comment]
Ah, I actually forgot. This are my settings:

```
ALL_btc_price_drop_trigger = 10
ALL_btc_price_drop_recover_trigger = 2

ALL_btc_price_rise_trigger = 10
ALL_btc_price_rise_recover_trigger = 2
```
