### ISSUE TITLE
Suggestion for Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by owner232** [taniman/profit-trailer#362]
Adding a feature like this would be amazing, You could add in twitter sentiment analysis to determine if the coin is going to pump. It could check each coin its about to buy in and see If its in FUD or if its being hyped.
https://www.csc2.ncsu.edu/faculty/healey/tweet_viz/tweet_app/

Example when searching $NXT

EmilyJPhotoDeco

Dec 5, 8:25am: RT @skyrbs: Mark my word #nxt is going to $2 before #ardor launch #newyear grab your $nxt $ignis 🛒🛒🚀🚀🚀🔭🔭 https://t.co/VC1KJIizrD

v = 5.65, a = 5.32

mark, v = [ μ: 5.48, σ: 1.3 ], a = [ μ: 4.79, σ: 2.11 ], fq = 50
word, v = [ μ: 5.56, σ: 1.15 ], a = [ μ: 5.17, σ: 2.11 ], fq = 50
going, v = [ μ: 5.42, σ: 1.16 ], a = [ μ: 6.21, σ: 2.51 ], fq = 50
launch, v = [ μ: 6.4, σ: 1.88 ], a = [ μ: 5.26, σ: 2.16 ], fq = 21

**Comment by kazazes** [comment]
While this is a great idea with demonstrated merit, running the SA and converting it to a signal is a huge undertaking. Also, the pump and dumpers are all over twitter, making it hard to discriminate between real user hype and FUD distributed by the pumpers.

**Comment by Utone** [comment]
maybe these guys have ready to implement solutions their TA (AI) based is about 96% accurate... o_O   ans they are woking on similar projects.. https://xypher.io/ also a bot
these guys rock almost as much as pt no i think they will like what they see and might ask you to work with them....perhaps run pt as a fork for kooper. have a good look. Elroy.. this is what is being proposed above already to a next level.can only imagine what Galileo holds in petto..
