### ISSUE TITLE
Create our own DCA Rule: DCA_validation = balance > 1.00 AND Bought_since >3 days AND Total_cost_percent_tcv > 10% AND Profit% > -10 AND (Trend < -3.00 OR PAIR_Trend < -10.00) 

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#363]
DCA_validation = balance > 1.00 AND Bought_since >3 days AND Total_cost_percent_tcv > 10% AND Profit% > -10 AND (Trend < -3.00 OR PAIR_Trend < -10.00) 
This is just an illustrative rule..

This kind of modularity avoid writing n strategies, then change them , remove them ..., until we fund the best formula which could take years..(more years before the altcoins market die! quickly) Gunbot is 
a good example ..

The variables provided are just replaced with the true variables.
The rule is just treated like an IF.

**Comment by taniman** [comment]
This kind of compelxity will not be added in current version of the bot
