### ISSUE TITLE
[GUI] Auto output periodic excel report

### ISSUE THREAD

**Issue by billyico** [taniman/profit-trailer#365]
dj, I love the feature for excel output so much, but I am lazy and always missed the sales log over the timelimit, if we have a periodic excel report auto save to our pt folder and we can even set the interval  would be nice :) Thanks

**Comment by mrlex** [comment]
Indeed, that would be a good option

**Comment by Stein276** [comment]
+1

This would be a great idea. Export and save excel output (based on days set in options) and clear sales log.
