### ISSUE TITLE
auto restart broken

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#367]
[ProfitTrailer (7).log](https://github.com/taniman/profit-trailer/files/1534399/ProfitTrailer.7.log)

**Comment by kennethkalmer** [comment]
It seems to be the `"autorestart": false` in `pm2-ProfitTrailer.json`. Simply removing the line and restarting ProfitTrailer with the new settings solves this.

This is duplicate of #308 as well

**Comment by taniman** [comment]
@kennethkalmer tnx for input, but most users do not use pm2 and still get a problem with this. Because all processes are not closed correctly so the ports remain in use

**Comment by kennethkalmer** [comment]
I think the default pm2 config should at least be configured this way so people don't get a nasty surprise.

We tested these changes with reboots and randomly applying `kill -9` to the PT instances and seeing pm2 bring them back to life as expected.
