### ISSUE TITLE
Feature Request: Day trading method EMACROSS for both Buys and Sells, MACD, Volume and RSI

### ISSUE THREAD

**Issue by cryptocoyns** [taniman/profit-trailer#370]
Would appreciate it if you could implement EMACROSS for both Buys and Sells. 
I use this for day trading manually on Bittrex using Coinigy.
I bought PT in the hopes of automating the manual day trading method I use and developed over 2 years of hard work.
I use the EMACROSS 13/34 on 5 minute candles as a trigger for implementing either a buy or sell strategy. 
I also use Volume increase or waning, MACD crosses 12/26 with 9 length and RSI to strengthen the cases that the EMACROSS is a true cross and not a false positive.
Then use the EMA spread to determine when to buy or sell. 
I also use DCA to both buy into and sell out of a trade position.
That way you can Buy Low and Sell High every time.
You never get bags this way and you can make money regardless of if the market and the pair is trending up or down.

**Comment by smportis** [comment]
Upvote for this. Sounds very strong if automated. Using 3 indicators to reinforce a strategy is something that is not being done in any bot in this space at the moment.

**Comment by jhual** [comment]
Upvote! This is awesome

**Comment by Zombato** [comment]
Nice, would like to see it implemented.

**Comment by danenright** [comment]
Great idea, please listen to this suggestion!

**Comment by xpforex** [comment]
yes we need this

**Comment by ahumadaz** [comment]
Great idea!

**Comment by johnalindogan** [comment]
Upvote

**Comment by Pintinero** [comment]
upvote

**Comment by DomoKB** [comment]
We definitely need this. +1

**Comment by CryptoSpike** [comment]
Upvoted, this would be an amazing feature to have implemented.

**Comment by dechut** [comment]
good featured , but need very much work for developer .

**Comment by joeyoon80** [comment]
Hmm, while trading from a human manual procedure seems sound, I’m just trying to picture it in an IF/ELSE point of view. I’m not an experienced coder, but maybe if u could structure the idea into a series of logic statements, it could give the devs a better idea on how to code it. Just my 2 cents.

**Comment by bverkron** [comment]
Yes please!

**Comment by Circumvenscion** [comment]
I came to this same exact conclusion by doing my own research on charts, though I use a slightly different set of EMAs. Being able to not only buy but also SELL using EMAs would be a phenomenal addition to Profit Trailer. You get all the upvotes.

**Comment by alvinphang** [comment]
i agree.. is there a way to have two Buying Strategies running on the bot? with AND Clauses

**Comment by alfonskb** [comment]
+1 This is exactly what is missing in PT. It would be a great improvement and added value to combine multiple indicators for triggering buys and sells.

**Comment by corklaassebos** [comment]
+1

**Comment by JulesBern** [comment]
+1

**Comment by LRpz** [comment]
100% would love this feature!

**Comment by zapedge** [comment]
As an addition it would be awesome if we could add StochasticRSI.
My short term trading strategy is based on BollingerBands and StochRSI.
I Buy when %D > %K and HODL until %K > %D.

**Comment by drumont-13** [comment]
MACD is what we need to optimize ProfitTrailer strategies ! 
Please don't make us wait any longer, as you know, time is money !!

**Comment by YeL6** [comment]
+1

**Comment by a7777777v** [comment]
+1

**Comment by wartimekillers** [comment]
+5

**Comment by zooboa** [comment]
+1

**Comment by dblasi69** [comment]
+1

**Comment by CousinEddie** [comment]
Looks like this is pretty active... so, here are my ideas. 

I’d like to suggest RSI/MACD/stochastic or combo of MACD/RSI.  There are plenty of explanations available of these strategies. Prior to getting PT I used this with pretty good success.  

Links: https://www.investopedia.com/articles/technical/073001.asp     

2nd link: https://www.investopedia.com/articles/trading/08/macd-stochastic-double-cross.asp   

3rd link: https://www.investopedia.com/terms/m/macd.asp   

4th Link: https://www.investopedia.com/articles/forex/08/rsi-rollercoaster.asp 

RSI alone would be sweet with trailing buy/sell. It might be easier to initially implement than combined strategies. Just something I was thinking would be a good addition... a damn good one imo

**Comment by CousinEddie** [comment]
How to calculate RSI
http://www.macroption.com/rsi-calculation/

**Comment by luisjotapepe** [comment]
+1

**Comment by dilak85** [comment]
+1

**Comment by wahbalami** [comment]
+1 RSI MACD

**Comment by keithofaptos** [comment]
+1
really can't understand why MACD with RSI hasn't been built into PT from DAY 1 .
PLS get this this done Elroy.

**Comment by DragonBtc93** [comment]
Yes please give us emacross sell with a minimum profit

**Comment by ahumadaz** [comment]
Elroy, this feature is A MUST!
Please include it as soon as possible.

**Comment by mnanut** [comment]
+2

Need this.  Bags killing us with just one indicator.

**Comment by flmst** [comment]
+1 for  EMACROSS sell

**Comment by Tosko4** [comment]
+1!

**Comment by SPANDOOS** [comment]
+1

**Comment by Wolfwood1** [comment]
Have been waiting for this for awhile, is there any word on when 2.0 will bring these highly necessary features?

**Comment by NigglesSquiggles** [comment]
Please add MFI! it's the volume weighted version of RSI.
Calculation:
Typical Price = (High + Low + Close)/3

Raw Money Flow = Typical Price x Volume
Money Flow Ratio = (14-period Positive Money Flow)/(14-period Negative Money Flow)

Money Flow Index = 100 - 100/(1 + Money Flow Ratio)

**Comment by HudsonTiger** [comment]
hi i see ema cross as a sell but i hope it will also have sma as a sell thanks
