### ISSUE TITLE
[Suggestion] Switching settings by files

### ISSUE THREAD

**Issue by mrlex** [taniman/profit-trailer#371]
Good day, 

Don't know if it would be possible or too much of a hassle to implement, but being able to have multiple setting files and simply switch between them by clicking the config name. 

Lets say I have 3 other .properties files for DCA and PAIRS. Each file would be named DCA2.properties, DCA3.properties and so on. In the GUI, simply have a "settings manager" which would list the name of the other setting files and I would only have to click on it to activate. 

Just a suggestion. :)

Have a nice day.

**Comment by taniman** [comment]
Nice suggestion. But not something we will be implementing in the coming versions. Maybe a pro version

**Comment by mrlex** [comment]
Thanks for the answer Taniman, happy new year and keep up the good work :)
