### ISSUE TITLE
SOM override enable = false doesn't seem to work first time (combined with login)

### ISSUE THREAD

**Issue by SanderGith** [taniman/profit-trailer#372]
Hi,

When using the following URL to SOMO (override sell only mode) "/settings/overrideSellOnlyMode?enabled=false". It doesn't work if you're not logged in yet. First you get redirected to the login screen, but after logging in you just end up on the monitoring page with SOM still enabled and not overridden.

If you try it a second time, so already logged in, it does work. So it seems to lose it's deeplink action during logins. Nice if it can be fixed, but a switch/button in the gui next to SOM might even be better/more userfriendly ;-)

Cheers,

Sander

**Comment by taniman** [comment]
I vote for a button. and will close this one down
