### ISSUE TITLE
USDT pairs volume and price paid lost

### ISSUE THREAD

**Issue by strongcraig** [taniman/profit-trailer#375]
My poloniex usdt bot keeps losing the price and volume of pairs it’s bought. If I manually set the price it finds them again and shows the actual price, not the price I’ve set in PAIRS. 

It most recently lost REP with 5 DCAs and a balance of $134. It had done a partial sell of my balance. Not sure if this was what triggered the bug as I’ve not looked too deep into that the previous times this happened. 

I manually set all pairs with $1 buy price to avoid this in the future. All balances and prices paid in the pairs and DCA log match poliniex ‘s records now.

**Comment by taniman** [comment]
What version of the bot are you using?
