### ISSUE TITLE
Manually override SOM when it gets "triggered"

### ISSUE THREAD

**Issue by zin22** [taniman/profit-trailer#376]
For V1.2.5.6
i currently have SOM triggered with BTC_price_rise and consecutive_buy. However i want to still trade certain coins whilst in this SOM.  I have tried all options but it does not seem to work.   Is this something that can be added? Reason i would like this option is that even though when BTC moons  there are still some coins that trade very strong through out the entire moon period. 

What i have already tried whilst in SOM which did not work is 
ALL_btc_price_rise_trigger = 5     
BTC_XXX_btc_price_rise trigger = 0

ALL_consecutive_buy_trigger = 4
BTC-XXX_consecutive_buy_trigger = 0

**Comment by taniman** [comment]
You already can manualyl override som to forcefully turn it off. There is not an option to force it per coin. But you can force it all off. So you could use that. Check the wiki in pairs.properties. scrolls all the way down
