### ISSUE TITLE
Binance PT ETH market selling at loss. 

### ISSUE THREAD

**Issue by cryptotrader-1** [taniman/profit-trailer#378]

**Comment by cryptotrader-1** [comment]
Bot when dcaing lowers the bought cost. Below any price it ever bought. Thinking profit is higher and then selling at a loss. It always seems to happen after a dca

**Comment by Zombato** [comment]
Yes, I can confirm it sells at loss after DCA. I've checked logs - it's not always the case, but very often. Had to turn off DCA for now.

**Comment by Zombato** [comment]
PT log (profit)
https://i.gyazo.com/4f30f6dbef8861384b41170c06c7baf4.png

Binance log (a loss actually)
https://i.gyazo.com/43f35df09fe2d7959c0cc96044277344.png

**Comment by antknight** [comment]
Was this issue fixed? I have had several orders sell at a loss after DCA?
