### ISSUE TITLE
Disable buying for specific pairs. (But allow DCA buys)

### ISSUE THREAD

**Issue by JReich82** [taniman/profit-trailer#379]
Ill give a brief discription of my problem so you will better understand. 

Normally i will disable certain trading pair with
"XXX-XXX_trading_enabled=false"
But i sometimes screw something up and forget.
Now if i have a pair in that was accidently purchased, and is sitting in the "Pairs log" , using "XXX-XXX_trading_enabled=false" will prevent said pair from being sold, or transfered to "DCA", or if in "DCA" it will not get averaged down. It just sits there stagnating. 
If it is a common coin for pump and dump, your timing has to be spot on in order to disable it before being repurchased making it very dificult to get rid of and disabled.
My solution is ""XXX-XXX_buy_disabled=true" which would allow the coin to run its course thru the bot until it is sold or averaged down then sold, but it will not be repurchased. 
Sorry if i was long winded.  Didnt know how else yo better explain my self properly.
Keep up the incredible work, and THANK YOU!.

**Comment by taniman** [comment]
That's why we have
XXX-XXX_sell_only_mode=true

**Comment by taniman** [comment]
or use
XXX-XXX_buy_strategy=DISABLED

**Comment by JReich82** [comment]
Duhh, thank you.

**Comment by hotpt** [comment]
On Binance, is this for exemple like BTCETH_buy_strategy=DISABLED, so XXXXXX_buy_strategy=DISABLED?

**Comment by hotpt** [comment]
I mean without the dash?
