### ISSUE TITLE
DCA Suggestion

### ISSUE THREAD

**Issue by DadOfMad** [taniman/profit-trailer#382]
First let me thank you for all that you have done for all of us using your ProfitTrailer.

So, people with a little purse can find that dca can really hurt them.
a strat that i am using, it is very time consuming, is that i only allow DCA to focus on one coin at. time.
my suggestion is a setting that allows the user to pick how many coins to allow dca to attack at a time.
once it gets rid of one it is making more coin to attack the next with....
i reaLly think this could help.

**Comment by RchGrav** [comment]
https://github.com/taniman/profit-trailer/issues/299

**Comment by RchGrav** [comment]
Something like that?   I had nothing bagged up in DCA for almost a week.. My DCA was tuned really well.. typically only one or two things would be in DCA anyway.   I took a nap at the wrong time.. woke up and had 12 pairs in DCA and was in sell only mode.  Yes.. This would be a really good feature to have.. no doubt.
