### ISSUE TITLE
Allow to disable SOM for coin specific pairs

### ISSUE THREAD

**Issue by zin22** [taniman/profit-trailer#383]
Wondering if you can add a function to disable SOM for coin specific pairs.  
Reason being: Often even when BTC is mooning or there are conditions which we have to enable SOM  , there are still some alt-coins that are trading very well, so an option to allow these specific coins to trade even when SOM is enabled would be good. 

What do you think?

**Comment by Anderson-PB** [comment]
You already can do that.

For bittrex
BTC-XXX_sell_only_mode = false 

For Poloniex
BTC_XXX_sell_only_mode = false

**Comment by zin22** [comment]
But my SOM is triggered by btc  price rise and consecutive buys ,  i have tried to disable it for coin specific pairs but it didnt work
