### ISSUE TITLE
Monitoring / Home page doesn't fully adjust when MARKET = ETH

### ISSUE THREAD

**Issue by ZachGoldberg** [taniman/profit-trailer#388]
When Market = ETH

* In the headline the price of BTC is shown (instead of ETH, maybe show both?)
* The top row, last column on the right shows BTC Trend 24H, ETH would be more helpful
* The middle row shows BTC Trends
* The top row uses BTC icons.

**Comment by djcrypto75** [comment]
Correct :) I will see if I can implement the other markets per exchange on the ticker and monitoring data. Good idea.

**Comment by djcrypto75** [comment]
Fixed.

**Comment by Tjosy** [comment]
On my GUI, the "ETH Trend 24H" always reads zero.
