### ISSUE TITLE
[DCA] [Feature Request] Separate DCA setting built into DCA.properties when entering SOM

### ISSUE THREAD

**Issue by dyvosvit** [taniman/profit-trailer#389]
Hello, Elroy!
The main idea we have is to have variables like
SOM_buy_strategy = ANDERSON
SOM_buy_style = DOUBLEDOWN
SOM_buy_trigger1 = -10
SOM_buy_trigger2 = -10
SOM_buy_trigger3 = -10
SOM_buy_trigger4 = -10

That DCA settings should be  **automatically** switched to when PT triggers SOM using pre-defined triggers. Thus, in my personal case, and i believe a lot of us had this situation, when you wake up in the morning with a ton of heavy bags.
So in case of BTC fast rise/fall as we seen these days, we have better chances to survive alts dumps, instead of using usual DCA settings, that of course will lead to really heavy bags.

Thank you,
deep respect,
Andrew.

**Comment by taniman** [comment]
I  see the appeal, but at same time think it will complicate things
