### ISSUE TITLE
[Feature Request] Delisting coins, panic sell and auto blacklist

### ISSUE THREAD

**Issue by twig123** [taniman/profit-trailer#395]
I'd like to add a feature request to be able to panic sell and auto blacklist coins that are scheduled to be delisted.

Ex: SAFEX on Bittrex

Appears that the delisting notice is available via the API:
https://bittrex.com/api/v1.1/public/getmarkets

`{"MarketCurrency":"SAFEX","BaseCurrency":"BTC","MarketCurrencyLong":"SafeExchangeCoin","BaseCurrencyLong":"Bitcoin","MinTradeSize":185.18518519,"MarketName":"BTC-SAFEX","IsActive":true,"Created":"2016-02-13T22:14:21.14","Notice":"This market is being delisted on December 15th, 2017.","IsSponsored":null,"LogoUrl":"https://bittrexblobstorage.blob.core.windows.net/public/95e9f419-6392-4551-a7e4-72498098e952.png"}`

**Comment by Utone** [comment]
great must have feature cant imagine the delisted coins out there i just missed..

didn't knew about the api, good news i would tink for implementing this

**Comment by twig123** [comment]
Bittrex is delisting 3 more coins on the 12th (TRIG, MTL, DGD).

At the very least, can we have the bot auto enable sell_only_mode=true for delisting coins?

**Comment by eddied316** [comment]
Super helpful. I got burned over the weekend by 2 coins that were getting delisted soon. Price dropped over 30% and PT kept doubling down. Would be really helpful if PT could check and set that coin to panic sell if it find its getting delisted.

**Comment by maxaudet** [comment]
+1

**Comment by cmer** [comment]
+1

**Comment by tomastoth** [comment]
+1

**Comment by limitlessent** [comment]
+1

**Comment by sil3ntcor3** [comment]
+1

**Comment by alexdolli** [comment]
+1

**Comment by cryptomail2018** [comment]
you got this for binance as well ?

**Comment by taniman** [comment]
I have searched 
1. Binance api
2. Poloniex api

It seems the only api with this data is Bittrex API. 

Due to this reason I will not be implementing this feature until we have a wat to implement this feature for all our supported exchanges.

I am not into the business of developing features that work only on 1 exchange
