### ISSUE TITLE
min_buy_balance ignored for 2-3s after sell

### ISSUE THREAD

**Issue by loopy83** [taniman/profit-trailer#398]
Hi Elroy,
I saw a bug tonight and just wanted to let you know.

PAIRS ALL_min_buy_balance = 0.1
DCA min_buy_balance = 0.08

And I got the following this night:
https://pastebin.com/GbyFru2u

He was on min balance edge and was not able to buy anything.
As soon as he sold ARDR for 0.006 he did three DCA buys:
STR = 0.00650387 BTC
OMG = 0.00567378 BTC
DGB = 0.00344662 BTC

So now I'm at 0.071 BTC and he is aware of the min_buy_balance again.
But within 2-3s second he was not.

Log attached:
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1546929/ProfitTrailer.log)

**Comment by taniman** [comment]
try the latest version and give me some feedback if it still happens
