### ISSUE TITLE
very important! DCA buys more than maximum allowed (BUG)

### ISSUE THREAD

**Issue by cryptt** [taniman/profit-trailer#400]
I noticed 2 coins being DCA'd more than they should.
In the properties file it is restricted to max 4 DCA's
These coins were bought with ALL_max_cost = 0.004
Which should result in max 0.064

One coin showed 3 DCA's but was at 0.14598960 when I noticed it and took it out of DCA
I checked the history Log on bittrex and a total of 6 purchases were made (see picture)
![screen shot 2017-12-11 at 14 46 28](https://user-images.githubusercontent.com/34436021/33821189-7d3affe6-de85-11e7-92a1-7c3419eb5078.png)

This should never happened as it is limited by this setting: max_buy_times = 4

The other coin showed 4 DCA's but was clearly bought more as well

![screen shot 2017-12-11 at 14 52 15](https://user-images.githubusercontent.com/34436021/33821197-8adc8976-de85-11e7-8356-d648bea0d06e.png)

All other coins were acting normal but these 2 dragged my balance down.

Love PT but this makes me worry leaving it alone which beats the purpose having a bot right?

Running the stable version PT Ver: 1.2.5.6 on a VPS server

**Comment by Fogazi** [comment]
Did you at anytime in the last few days delete your profittrailer.json and/or it's backup?

**Comment by cryptt** [comment]
No it's running for 7 days without touching the json or backups. This is the first time that this happened. I checked the history but couldn't find any other issue.

**Comment by taniman** [comment]
Send me your log file. To see what happened

**Comment by cryptt** [comment]
Just happened again... while I was watching even ;)
This shows on the DCA log, only 1 DCA made right?
![screen shot 2017-12-12 at 11 35 20](https://user-images.githubusercontent.com/34436021/33867664-d337cfcc-df30-11e7-9da2-3edfdf51fc3c.png)
Actually it made 4 additional sales already. Now I'm going up so that's okay but when going down from here would result again in higher investment then should be.
![screen shot 2017-12-12 at 11 35 42](https://user-images.githubusercontent.com/34436021/33867696-098708ea-df31-11e7-8453-26db1b0075fc.png)

**Comment by cryptt** [comment]
@taniman where can i send the log file?

**Comment by cryptt** [comment]
Luckily it is sold now and didn't go lower. But that's not the point :)

![screen shot 2017-12-12 at 11 47 27](https://user-images.githubusercontent.com/34436021/33867933-625ccdd2-df32-11e7-89fc-70977c9210e4.png)

**Comment by sudden-break** [comment]
I can confirm that kind of behavior.
Had the same issue yesterday when btc pumped and alts dumped in the same second, PT overbought by 3 pairs to the max.
I will try to locate the log entry and upload it here

**Comment by cryptt** [comment]
Not sure what the issue is. First I thought it had to do with orders being partially filled. But that doesn't deem to be it. Yesterday I had 2 identical buys within seconds. PT did register the total amount spend and amount of coins but it didn't register it as 2 buys.
For now I have my DCA's set to max 4 but I limit the bot with the max cost as well. Although the bot doesn't register all buys it doesn't go over the limit set.
I'm hoping that in the future the bot will have more fail safes build in.
Don't get me wrong overall I'm very happy with the bot and I understand It's still a young puppy that needs to mature. Keep it going guys love the effort so far!

**Comment by cryptt** [comment]
Ok found another one this time the bot bought 7 times with no DCA's being logged.
If I hadn't restict by specifying the max cost I would have a monster of a bag.
![screen shot 2017-12-16 at 11 10 19](https://user-images.githubusercontent.com/34436021/34067242-503b1730-e252-11e7-990c-29c03661ab1c.png)
As you can see below DCA showing 0
![screen shot 2017-12-16 at 11 08 23](https://user-images.githubusercontent.com/34436021/34067246-67175f68-e252-11e7-8e0e-785e3b9010e4.png)

I have no clue where it goes wrong but I really think this is a mayor thing.
Does the bot not double check in the history what is bought?
Is this an API BUG? using bittrex BTW @taniman 

Cheers

**Comment by Fogazi** [comment]
Can you post your dca.properties and pairs.properties here?

**Comment by cryptt** [comment]
DCA buying strat:

max_cost = 0.064
max_buy_times = 4

#--------------------------------------------------------------#
#BUY SETTINGS #
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -0.85
buy_trigger_2 = -1.85
buy_trigger_3 = -2.60
buy_trigger_4 = -3.50
buy_trigger_5 = -3.75
buy_trigger_6 = -3.75

trailing_buy = 0.1

pending_order_wait_time = 0

In the pairs I send it directly to DCA:
ALL_max_cost = 0.003
ALL_DCA_enabled = true
ALL_DCA_enabled_trigger = 0

**Comment by Fogazi** [comment]
That's odd for sure, seems like an api issue, maybe try using to completely new api keys?

**Comment by cryptt** [comment]
Okay guys 1 more and then I stop. I think you get the picture....
DCA.... No DCA's???
![screen shot 2017-12-18 at 00 07 08](https://user-images.githubusercontent.com/34436021/34081899-8946ec58-e387-11e7-9f17-884bdadb8a53.png)
Actual buys.....
![screen shot 2017-12-18 at 00 06 33](https://user-images.githubusercontent.com/34436021/34081902-a766af02-e387-11e7-8638-aa69bcc54407.png)


Over and out ;)
