### ISSUE TITLE
Invalid license!!!!

### ISSUE THREAD

**Issue by rlorenzo316** [taniman/profit-trailer#401]
When trying to run the bot I keep getting an invalid license. I have been trying to trouble shoot the problem for the last two days NOTHING works!

The only thing I can think of is I tried running it on my MacBook bro and iMac and neither of them worked. So now I'm running it on my ASUS windows. Maybe having the files on multiple laptops is a problem?

Please help

**Comment by Fogazi** [comment]
What exchange are you using?

Have you activated your API keys?

Have you join the ProfitTrailer telegram group, there is a world of knowledge there that are solving these issues by the minute.

**Comment by rlorenzo316** [comment]
I have activated my API keys. I'm using and asus for windows

**Comment by Fogazi** [comment]
What Exchange? Bittrex/poloniex/binance?

Seriously though,  join the telegram group.

**Comment by rlorenzo316** [comment]
Bittrex. I just joined the telegram group. Nobody responded

**Comment by taniman** [comment]
Please contact me on telegram @elroy
