### ISSUE TITLE
ALL_max_trading_pairs ignored on binance in 1.2.6-B6

### ISSUE THREAD

**Issue by halofx82** [taniman/profit-trailer#402]
Title says all...

have ALL_max_trading_pairs = 2 and DCA log gets filled with 5 pairs. Which is max for USDT market on binance.

**Comment by taniman** [comment]
can you show me you settings?

**Comment by taniman** [comment]
send me a pm

**Comment by halofx82** [comment]
Stupid question: How do I send a pm on github?
