### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sethiano** [taniman/profit-trailer#405]
Hoping for a way we can issue a command to the web server similar to this: this: http://localhost:8081/settings/sellOnlyMode?type=&enabled=false

that will reset the bot.

Got spammed by telegram telling me to reset it and ended up having to RDP in (not a big deal, but a web command would be nice)

maybe require a password?

Thanks!

Seth!!!

**Comment by Jaapapa** [comment]
Or maybe directly through the BOT? Like a /reset command.
