### ISSUE TITLE
Auto-buy BNB

### ISSUE THREAD

**Issue by XRIICrypto** [taniman/profit-trailer#408]
Since BNB is used to lower the fees on Binance it would be great if PT could auto-buy some BNB if your running low.

**Comment by zin22** [comment]
great idea i think .

**Comment by Fogazi** [comment]
Fantastic idea, updoot!

**Comment by taniman** [comment]
I do not agree with this idea. As this is an exchage specific idea. features in the bot should be usefull and should work on all exchanges.
