### ISSUE TITLE
profit today/yesterday need to use UTC + timezoneoffset

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#409]

**Comment by cryptt** [comment]
I notices the same issue, I saw this open issue and didn't want to open a new one.
Too bad there is no description so I'm hoping the devs will see it.
Anyway, as the title suggests the profit section eg today and yesterday won't show correct value until UTC 0.00. 
The logs are correct but when my clock is 0.00 UTC still has 7 hours to go.
So what happens? 0.00am the today profit freezes until UTC hits 0.00am the value is still correct as it seems to use the correct (adjusted) time in the background. see screenshots

![screen shot 2017-12-17 at 00 55 06](https://user-images.githubusercontent.com/34436021/34073158-ed151786-e2c5-11e7-8c2d-5787dacd2c51.png)
As you can see we're in a new day already due of the server off set setting. All sales after the local 0.00am time will not show until UTC hits 0.00am
Sales log is fine BTW it shows the correct time

![screen shot 2017-12-17 at 01 04 14](https://user-images.githubusercontent.com/34436021/34073174-3f771e0c-e2c6-11e7-9ba3-73f2f6dc19d0.png)
entry 1 will show in about 6 hours from now as todays profit.

Cheers

**Comment by taniman** [comment]
Problem fixed in 1.2.6.1
I am the dev so that's why I dont put descriptions :)
