### ISSUE TITLE
Error - "unable to access jarfile ProfitTrailer.jar. "

### ISSUE THREAD

**Issue by ben7700** [taniman/profit-trailer#413]
Hey Team.

 Im have PT up and running on my MAC find for the past few days. Today i want to set it up on a windows VPS. I set everything up and when i tried to run the file i got the error 
"unable to access jarfile ProfitTrailer.jar. 

Im running it on windows server 2012.

Can you please help? 

Thanks

**Comment by t1m3c** [comment]
That's because of the space you have in the path name. On Windows, use quotes:
java -jar "C:\bot folder\ProfitTrailer.jar"

**Comment by taniman** [comment]
You need to CD to the correct directory.
If you dont know how to to this. please as for support in one of our telegran channels.

**Comment by RICHIRICH64** [comment]
hi Ben , im having issues setting up PT on my mac , could you help me, im getting error messages as well

**Comment by brian30** [comment]
....# java -jar sign.jar my.apk
Error: Unable to access jarfile sign.jar
