### ISSUE TITLE
Consecutive buy trigger not working 

### ISSUE THREAD

**Issue by zin22** [taniman/profit-trailer#414]
In the latest release for both binance and bittrex as i have tried, Consecutive buy trigger did not work and initiate SOM.   In bittrex I have it set a 6 , i made over 10 consecutive buys and it did not trigger a SOM. 
Was working in previous version.

I need this working before i invest large amounts into bittrex for the bot. i need to make sure all safety features are 100% working

Please confirm.

**Comment by zin22** [comment]
Please get this working asap, this trigger is important to protect from crash in altcoins. The trigger did not work and i bought over 35 coins due to the most recent crash. this needs to be looked at asap please.

**Comment by taniman** [comment]
I can confirm this trigger works on both bittrex and poloniex. It has triggered multiple times on my bots.
It has never worked on binance and will not work until further notice.

**Comment by taniman** [comment]
Please contact me on telegram if youdid not already
