### ISSUE TITLE
Always loop "Detected Configuration Change"

### ISSUE THREAD

**Issue by sovanndy** [taniman/profit-trailer#415]
Hi Sir,

After I run PT, in command prompt show like this "Detected Configuration Change". after I press ctl+c, it show java error
![capture](https://user-images.githubusercontent.com/277450/33987377-440a7ab0-e0f3-11e7-8df9-5cac9869a461.PNG)
![capture2](https://user-images.githubusercontent.com/277450/33987378-443fc134-e0f3-11e7-98b7-09f19791bc09.PNG)

You know I just move from laptop to VPS running window 8R2 Datacenter. on my laptop it runs perfectly but after I moved it show error As I mentioned above.

Please help to fix me

**Comment by taniman** [comment]
This is most likely do you the system times not being the same. Please edit the files once on your VPS and save. to correct the dates on the files
