### ISSUE TITLE
Coins considered dust, but are not

### ISSUE THREAD

**Issue by dignus** [taniman/profit-trailer#416]
When first starting the bot, I put in a lower max buy, 0.0001.  I raised it, but I see about 10 of my bags worth 0.0001 or a little less are now considered dust, while bittrext will allow me to manually sell them.

![screen shot 2017-12-14 at 16 03 13](https://user-images.githubusercontent.com/107180/33998600-53d1184c-e0e8-11e7-9e04-576d4816fea8.png)

**Comment by chrisek** [comment]
Yes, i have the same problem.

**Comment by tim1256** [comment]
Same here

**Comment by zin22** [comment]
can someone pin a message on the telegram group explaining how to minimise these dust levels . binance seems to have bad dust problems which over time add up alot, and some are confused on how it works or what settings we should put to ensure we sell the dust or minimise it significantly. please help.

**Comment by taniman** [comment]
0.0001 is certainly not sellable on bitrex. i guess you mean 0.001
The bot has a way to configure the amounts is sees as dust. 0.00105 is the default. So anything below tht is dust.

https://wiki.profittrailer.io/doku.php/configuration.properties

Use configuration.properties so change the dust level if you need to.

**Comment by BitBomse** [comment]
Do you have to manually sell them if you have dust logs ?

**Comment by cryptolegendx** [comment]
I am having an issue with dust log for a specific coin pair on binance.  GTOBTC.  my bot purchased 21 of them but its stuck in the dust log.  It just keeps losing value.
![dustlog](https://user-images.githubusercontent.com/36631398/36381069-6a866d82-1552-11e8-92db-6bf006bee70c.png)

**Comment by Stratonite5858** [comment]
@cryptolegendx I have the exact same issue. I made a comment about this on the PT discord and someone else said they had the same issue and to just ride it out. I just don't understand why it keeps losing value and I want to stop the bleeding...
