### ISSUE TITLE
Last 2 days: {"error":"Please specify a valid period."}

### ISSUE THREAD

**Issue by mrlex** [taniman/profit-trailer#419]
Hello, 

I have this message constantly spaming in my logs, been like this for the last 2 days as I know of. Is it normal?

0|BTC Polo | 2017-12-15 10:44 +00:00: 2017-12-15 10:44:31 INFO ProfitTrailerService - Occured in chartData, result: {"error":"Please specify a valid period."}
0|BTC Polo | 2017-12-15 10:44 +00:00: 2017-12-15 10:44:31 INFO ProfitTrailerService - Occured in chartData, result: {"error":"Please specify a valid period."}
0|BTC Polo | 2017-12-15 10:44 +00:00: 2017-12-15 10:44:36 INFO ProfitTrailerService - Occured in chartData, result: {"error":"Please specify a valid period."}
0|BTC Polo | 2017-12-15 10:44 +00:00: 2017-12-15 10:44:42 INFO ProfitTrailerService - Occured in chartData, result: {"error":"Please specify a valid period."}
0|BTC Polo | 2017-12-15 10:44 +00:00: 2017-12-15 10:44:52 INFO ProfitTrailerService - Occured in chartData, result: {"error":"Please specify a valid period."}
0|BTC Polo | 2017-12-15 10:44 +00:00: 2017-12-15 10:44:52 INFO ProfitTrailerService - Occured in chartData, result: {"error":"Please specify a valid period."}

Bot is running fine and trades are being made when not in SOM. 

Any clue about it?

Thanks a lot.

Alex

**Comment by jadiesel** [comment]
You need a valid time period in your indicators file.  
60, 300, 900, 1800, 86400

And we need to get the valid time periods per exchange listed in the wiki....

**Comment by mrlex** [comment]
Haaa thanks :)
