### ISSUE TITLE
Request: BTC Rise & Drop trigger should be based on 1 or 2 hours rather than 24 hours.

### ISSUE THREAD

**Issue by Mikeqhu** [taniman/profit-trailer#420]
I think the subject pretty much hits on the spot as the drop in altcoin is based upon the speed of the rise and fall rather than the day. Thanks and keep up the good work.

**Comment by Mikeqhu** [comment]
Or another thought, have the option to base it on the trend, but also have time intervals options of say, the 5, 15, 30, 60 minutes, etc. Again, thanks.

**Comment by nocturnal86** [comment]
https://github.com/taniman/profit-trailer/issues/196  this is added in milestones ;)

**Comment by Mikeqhu** [comment]
Excellent!



--
Mike Hu
President/CEO
TRIO Custom Clothiers
mike@triotailoring.com

**Comment by taniman** [comment]
See #196
