### ISSUE TITLE
How to fully disable DCA buy?

### ISSUE THREAD

**Issue by SallyDT** [taniman/profit-trailer#429]
I want to fully disable DCA buy.
Is it possible?

In dca file, I put: 
enabled = false

... but it still continue to buy randomly. And what happen? Just STOPLOSS in many coins, like this ProfitTrailer produces -$100, -$50, -$200 every day..., which is stupid...

![losses](https://user-images.githubusercontent.com/5926925/34068542-3fbb6e08-e277-11e7-973a-a820c991ce9e.PNG)

So every day trading this stupid DCA make all negative purchases...

So how to fully disable DCA?

**Comment by Fogazi** [comment]
In pairs, ALL_DCA_enabled = false

**Comment by SallyDT** [comment]
Seems to work! Thanks.

**Comment by SallyDT** [comment]
I'm going to re-open it. It still buys when ALL_DCA_enabled = false. Any ideas?

**Comment by SallyDT** [comment]
What is the correct values for ALL_DCA_enabled = ? <-- the default is -2.

**Comment by SallyDT** [comment]
![losses2](https://user-images.githubusercontent.com/5926925/34072206-0dc8028e-e2be-11e7-8fe1-6de813c7df1f.PNG)

The DCA log is losing lot of money.... It's going -10%, -15% and does not respect STOPLOSS.

**Comment by taniman** [comment]
ALL_DCA_enabled = false

and make sure you dont have  pair specific overrides that reenabled DCA.
also what version are you using? 

enabled in DCA.properties does not work anymore. has been removed a few versions ago

**Comment by SallyDT** [comment]
ok. I'm using latest version.

**Comment by taniman** [comment]
Lets look at this in 1 of our telegram support channels. as this is not a user specific issue
