### ISSUE TITLE
New Feature Request - Pair Support Levels to trigger Stop Loss

### ISSUE THREAD

**Issue by cryptocoyns** [taniman/profit-trailer#431]
Could you please add a feature for Support Levels to trigger stop loss.
If you know what the previous support level for a pair was it would be good to be able to define a
support level for a pair in order to trigger a stop loss if the pair goes below its previous support level. i.e.
BTC-LTC_Previous_Support_Level = 0.04164025

**Comment by ahumadaz** [comment]
Upvote

**Comment by danenright** [comment]
This would be amazing

**Comment by johnnycash1** [comment]
this would be great
