### ISSUE TITLE
[Feature Request] Backtest / Config Benchmark

### ISSUE THREAD

**Issue by aft** [taniman/profit-trailer#435]
Ability to test config files (buy/sell strats) based on the historical data that the bot collected and saved to the disk would be awesome.

Importing past data will not work on all platforms since some of them (like Bittrex) doesn't have export option. So no need to implement it in the early stage.

PS. Btw, great job, Taniman.

**Comment by github-4me** [comment]
+1 for this!

**Comment by trippinCode** [comment]
+1 Would really help tune your settings more efficient!
I currently spent 4h per day watching my bot trade and fine tune my settings

**Comment by nric** [comment]
+1 ! With clean and complete command line output on every virtual trade and the amount bound in DCA, please! So we can use go an algoithmic way to optimise the settings, guess work is bad here.

**Comment by rayholland** [comment]
+1 for backlogging testing. maybe a 3rd party interested in programming a script for this? for me, i would pay for such thing

**Comment by smoochy** [comment]
Why has this been closed without any comments from the dev side?

**Comment by rayholland** [comment]
Maybe they don't want this feature, because it will show profit trailer isn't as 'profitable' as they want people to believe ;-)

**Comment by taniman** [comment]
well @smoochy  it's simple. 

For backtesting strategies you need ticker data. not chartdata, but real live on the second ticker data. 
The bot does not collect any data, so the bot does not have that kind of database.

It requires a lot of time and effort to build something like this. And if it is ever built it will be a seperate product with a seperate price. 

So I welcome anybody that feels like they can build this feature. But it's not on our road map currently

**Comment by smoochy** [comment]
Thank you for taking the time to explain.

**Comment by oldmankit** [comment]
I'm just considering getting into bot trading, and I think back-testing is probably a deal-breaker for me. Anyway, thanks @taniman for explaining why it's not likely to be a feature in the near future.
