### ISSUE TITLE
Error Application Please Fix: trading_APIkey -- String Index out of range: -10

### ISSUE THREAD

**Issue by Cadminer** [taniman/profit-trailer#436]
Hi there

I'm installed Profit Trailer on Windows VPS.  I've updated all my settings but the application won't start.  The following error is logged:

Error Application Please Fix: trading_APIkey -- String Index out of range: -10

Any ideas on what I need to do to fix (I've check the API details are accurate).

Thanks
C

**Comment by taniman** [comment]
Sounds like a setup problem. This should be handled via our Telegram support channel
