### ISSUE TITLE
[Feature Request]  Use RSI to filter enabling trading for a Pair

### ISSUE THREAD

**Issue by bmanb** [taniman/profit-trailer#438]
In order for a buy strategy to become active for a pair the RSI would have to drop below a configurable RSI level.  For example below RSI 40

At that point the pair would become a possible buy candidate and execute based on the strategy chosen like emagain.  

Once a buy and sell for a pair had completed based on your buy and sell strategies, that pair would not be available again to trade until the RSI dipped below 40 again.

**Comment by taniman** [comment]
See #82 

This issue request will incorporate RSI indicator into the bot. You can then set it up to buy or nor buy according to normal buy_value options. That's how far we will go with strategies setup
