### ISSUE TITLE
Bought amounts are all different instead of fixed

### ISSUE THREAD

**Issue by automaticprofits** [taniman/profit-trailer#439]
How do we add a suggestion for the development team here on Github about perhaps having a ie. Min Cost = $75 and a Max Cost = $80   and a Max Number of Initial Trades = 1

This way the amount invested per trade can be contained within those parameters.  

The reason this is important is because having multiple initial orders is consuming a larger amount of capital and leaving less for the other pairs and for DCA trades.   And having a Max Number of Initial Trades = 1 will also help with restricting the amount of initial trades as well.  These are all important aspects of having proper money management in trading.

Thank you for your consideration of these ideas in upcoming versions.

Mike

P.S. You will see in the screen shot below trades with all different bought amounts.  And in the second screen shot you will see that it entered 3 initial trades when it was supposed to be only one.  You will notice that this is not a DCA trade.

![image](https://user-images.githubusercontent.com/30329206/34088813-f8265b26-e379-11e7-908b-a9b4f23f4e06.png)

![image](https://user-images.githubusercontent.com/30329206/34088859-48374c9c-e37a-11e7-9cc6-11eb5e3899ef.png)

**Comment by taniman** [comment]
You can use min_buy_available_volume_trigger to let to bot try to make the complete order amount when buying.

This issue you are experiencing with 'multiple' initial trades is caused by a bug in bittrex api. Normally the bot only does 1 initial trade.
