### ISSUE TITLE
UI Request: Add digits to the profit display to see daily profit (0.0000)

### ISSUE THREAD

**Issue by iAmVaeVictus** [taniman/profit-trailer#440]
At the top of all the pages except Monitoring, it would be nice to have an extra digit to see BTC profit amounts gained, where currently, unless you are Sam big bags, you are below 0.00 in daily BTC profit. 

Add one or two zeros to make it look like this: 

BAL: 0.0660 TCV: 0.1180 TPV: 0.1180 Profit: (0.0178 LW)  (0.0009 YD)  (0.0004 TD)  Trend: (13.98 % 24H)  BTC: 18739.41 (-2.30 %)

![screen shot 2017-12-18 at 2 07 19 pm](https://user-images.githubusercontent.com/7082654/34125763-038f3090-e3fd-11e7-91c6-d5aab9ac5d83.png)

**Comment by Xyxo** [comment]
Good Idea, mine shows most of the Time 0.00 and sometimes 0.01

**Comment by djcrypto75** [comment]
Not enough space, full data on the dashboard :)

**Comment by GeoffBoyle** [comment]
If space is the issue, why not reduce the precision of the larger values, BAL, TCV, TPV and add to the smaller values TD and YD?

**Comment by djcrypto75** [comment]
I am adding 3 digits on a future version.
