### ISSUE TITLE
Hide BNB pair completely in UI

### ISSUE THREAD

**Issue by krims0n32** [taniman/profit-trailer#441]
Currently the BNB pair on Binance is displayed as in watchmode (trading disabled). Add an option to disable BNB completely in the UI. I suspect it also counts as a real pair so that would effect max_trading_pairs as well.

**Comment by Fogazi** [comment]
If max pairs is something your worried about, just add another 1 to your pairs,

**Comment by DoowronDesign** [comment]
BNBBTC_trading_enabled = false
ALL_hidden_pairs = BNBBTC

**Comment by NenadX** [comment]
If you want to hide more pairs, put the comma between pairs

ALL_hidden_pairs = BNBBTC, XRPBTC, NEOBTC, IOTABTC, ADABTC, NBTBTC
