### ISSUE TITLE
Sales log disappearing

### ISSUE THREAD

**Issue by FedericoGM** [taniman/profit-trailer#445]
So I just lost 16 hours of trades. I have 7 days log history and the ones ive lost are all today tradings.

19.12.2017 22:13
19.12.2017 04:40

This is the jump ive got

**Comment by taniman** [comment]
There can be many reason why this could have happenend. But your sales are still on your exchange. You should always use your exchange as  the true source. the sales log of the bot is jsut a reference. And there might be file corrutions and such that can cause the log to disappear.

The comming version has some extra checks. So we can see if this happens too in that new version
