### ISSUE TITLE
Slope based purchasing

### ISSUE THREAD

**Issue by Bbrandwin** [taniman/profit-trailer#446]
Is there any way to add the ability to declare a minimum ema/sma slope for purchasing. For instance, i would like to use the emaspread for purchasing but only execute if the slope of the fast ema is greater than 0 (indicting a turning point)

**Comment by taniman** [comment]
What do you mean with slope?

**Comment by Bbrandwin** [comment]
The slope would be The change in EMA over  time.  eg:
 (EMA(at current time) - EMA(at previous time))/(Change in time)

 If the EMA is going downwards it's equivalent to a falling price and the above equation would be negative, while a rising price would have be positive . If the price remains constant than the slope is 0. This also indicates the turning point (That's the point where the line is flat). See the image below (it's not super pretty cause I'm drawing in my phone but I've labeled the 0 points and where the slope is negative or positive).




Best,
Ben Brandwin

**Comment by Bbrandwin** [comment]
Just wanted to update this a little. I realize now it may be more effective to use slope as the change in spread over time. The spread would be calculated the same as EMASPREAD and over time It would have units of "percent/minute", a positive value would indicate that the fast EMA is moving up relative to the slow, while a a negative value indicates the opposite. 

For example - "buy when EMASPREAD is less than 1 and EMASLOPE is greater than or equal to .2" (in otherwords, buy when the fast EMA is 1% less than the slow and is now rising around .2% every minute). 

This can also be used as a sell strategy to say "sell when EMASPREAD is greater than 1 and EMASLOPE is less than .2" (indicating that the fast EMA is 1% higher than the slow, and has now started moving down at .2% per minute)

These strategies should help prevent purchases of coins that are still moving down, as well as help prevent sales of coins that are still moving up.
