### ISSUE TITLE
Issue with Profittrailerdata.json & backup file for Polo exchange after power outage

### ISSUE THREAD

**Issue by kryptekk** [taniman/profit-trailer#447]
Happened twice this week running 3 exchanges....only polo has this issue. If the server experiences a power loss and gets shutdown abruptly, the ProfitTrailerData.Json file and it's backup both get corrupted and when examining both files, just have a continuous line of NULL in it. Does not happen with TREX or Binance. This has happened twice in 7 days. The only way to get Polo back up and running is to delete the file.

**Comment by taniman** [comment]
In 1.2.6.1 we have made some adjustments to the backup file saving. We will keep making improvements to make it the files less prone to data corruption.
