### ISSUE TITLE
[Feature Request] - Add $ Gain into Telegram Message 

### ISSUE THREAD

**Issue by Flosen86** [taniman/profit-trailer#448]
Would be great to add the $ Gain into the telegram meassage

**Comment by minerdude** [comment]
UP

**Comment by zin22** [comment]
UP

**Comment by QXR987** [comment]
Up

________________________________

**Comment by tatarin38** [comment]
Up

**Comment by github-4me** [comment]
up

**Comment by Jaapapa** [comment]
I agree it feels good to see $$$, but remember: USD Gains depends on the BTC/USD rate, so it may change over time... So your Telegram message will lie to you one second after it's sent. Start thinking about money in BTC instead of USD! :)

**Comment by Xyxo** [comment]
Up

**Comment by loopy83** [comment]
Yes!

**Comment by daemolition** [comment]
UP

**Comment by magyosha** [comment]
up

**Comment by vicenterusso** [comment]
+1

**Comment by swoopsus** [comment]
+1

**Comment by ramonduraes** [comment]
up USD

**Comment by YoJeff** [comment]
Issue purge.   PT notifications does this now.
