### ISSUE TITLE
BNBBTC trading enabled but option to set BNB reserve for fees for all trades, And we can also trade some BNB with discounted fee..;)

### ISSUE THREAD

**Issue by Utone** [taniman/profit-trailer#451]
Hey,

BNB is getting nice trades has good volatility.. 
It would be nice to be able to set a reserve BNB amount for fees, to be ignored for trading.

So we can trade some volume BNB (with discount ;))

**Comment by Jaapapa** [comment]
A reserve setting for any pair would be the way to go. For example, I'd like to be able to set a reserve for BNBBTC of 10 actual coins, and have PT trade with anything above that.

**Comment by taniman** [comment]
see #496 

I will investigate if possible to add in next major release

**Comment by taniman** [comment]
or the one after that
