### ISSUE TITLE
idea for SOM triggers Binance

### ISSUE THREAD

**Issue by cryptt** [taniman/profit-trailer#455]
Could you the data from coinmarketcap?
I know they have API's for that, not sure if you could implement it.

to prevent the ip ban described in the new release coming:
Core
Binance Exchange
No support for BTC rise and drop triggers (IP ban enhancements)
Missing 24h change and trend percentages (IP ban enhancements)

https://coinmarketcap.com/api/

**Comment by taniman** [comment]
But the data from coinmarket cap is not the exact value for the exchange. It would lead to an incorrect reperesentation. 

Thanks for the tip though.

**Comment by moses-aronov** [comment]
What’s the expected eta on this?
