### ISSUE TITLE
profits section in the GUI freezing and displaying incorrect profits 

### ISSUE THREAD

**Issue by ThrasherHammer** [taniman/profit-trailer#457]
I've noticed something strange in the GUI, Yesterday's profits disappeared and the today's profits froze(stuck with a certain value and not counting profits), even though the bot has made sales which appear on both the sales log and the exchange, also the balance is increasing so that confirms that trading wise everything is ok.
Even the weekly profits seems to have 1 full day of profits missing.

now that the day has ended the "incorrect" today's profits is in yesterday and the today's profit is counting normally again.

I don't think I can trust the GUI to display the correct earnings with these random freezes in profits displayed, and dropping of profit days.

Can somebody shed some light on this issue ? 

I'm using Bittrex and bot version 1.2.6
haven't had any errors as far as i can tell.

**Comment by taniman** [comment]
Have you checked if all heart beats were okay? and that those sales were send to sales log?
Only sales in the sales log will be used to count profits.

**Comment by ThrasherHammer** [comment]
the heart beats were ok, but the sales did not appear in the sales log..even though im sure they were there before
