### ISSUE TITLE
[Request] Disable any XSS

### ISSUE THREAD

**Issue by d1rt** [taniman/profit-trailer#462]
All changes to the settings through the address bar should be disabled in the code, or in the default bot settings.

Many people share their URL with monitorings, but they do not understand that anyone can change their settings through the address bar

For example:
/settings/overrideSellOnlyMode?enabled=true
/settings/overrideSellOnlyMode

I consider this a potential danger feature.

**Comment by taniman** [comment]
Yes. This has already been disabled in 1.2.6.1. Please update your version accordingly. 
To make changes you will need to set a password for your monitoring
