### ISSUE TITLE
[Request] Use "MinTradeSize" from API for placing Buy Orders

### ISSUE THREAD

**Issue by renderyourworld** [taniman/profit-trailer#463]
Currently if you place a buy order on Bittrex (maybe Binance as well) the exchange will let you place the order but you will not be allowed to place a sell order and will recieve the "MINIMUM_TRADE_REQUIREMENT_NOT_MET" error.

I'm wondering if PT can scrape the Bittrex API and grab the "MinTradeSize" for each pair PT its looking to buy so we don't get this error when trying to sell.
https://bittrex.com/api/v1.1/public/getmarkets

For instance, PT bought 12.4 USDT-XRP this morning but it can't sell the pair because the "MinTradeSize" for that pair is (currently) 14.77.

This seems like a major error on Bittrex's part; basically allowing you to buy a pair but not sell it (which encourages you to buy more), so maybe PT can account for this error.

**Comment by minerdude** [comment]
up
