### ISSUE TITLE
INFO ProfitTrailerService - Occured in 24hInfo, result: Error in reading response Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by RichardLuo0506** [taniman/profit-trailer#464]
started happening today:

`INFO ProfitTrailerService - Occured in OO, result: Error in reading response Software caused connection abort: recv failed`

`INFO ProfitTrailerService - Occured in 24hInfo, result: Error in reading response Software caused connection abort: recv failed`

Also, I'm noticing configuration changes in the logs happening multiple times today even though I didn't change anything.
`INFO Util - Detected configuration changes`

**Comment by taniman** [comment]
Please check your server time.  and check if your machine can communicate properly to binance. I suppose this is Binance? 

Else ask for guidance in your local Telegram support channel or main channel.
