### ISSUE TITLE
[Feature request] Manual Buy/Sell bottuns

### ISSUE THREAD

**Issue by anon059** [taniman/profit-trailer#468]
It would be nice to have manual 
-BUY and "Temporary pause trade this pair" option in Possible buy section next to trading pair
-SELL now in Pairs Log section

**Comment by dechut** [comment]
i love this setting , but i think we need 1 tab is manual trade .

part 1 - buy now + sell now . just select coin , and total btc you want , and bot will buy now with bid/ask price .

part 2 - pending order : 

buy with maximum price XXX   :  if coin drop to lower price XXX then start trailling buy .
sell with minimum price YYY    : if price higher than YYY , start trailing sell  ( YYY can ignore bought price )

---------------------------------------------

all order just work 1 time .

**Comment by anon059** [comment]
my idea was while are you entertained by PT GUI and watching your pairs and looking at charts at same time, sometimes you know better than bot and if you think "this is going to dump hard, i don't want it to become my 30% bag it's 1% at loss now" just make quick sell at market price at loss and go next... also if you set 2-3% EMA for buy value and somehow bot got up to 10% and trailing, maybe you know it will stop just there and you place market buy at that price, you don't wait for bot to get 10%-[trailing] to buy. Bot works great, most of the time, depends on your settings, but sometimes you feel very right about price change and don't want bot to trade it and if you are on andoid, ios etc, it sometimes takes up to 5min to login into bittrex (pass, 2FA, mail, pass, 2FA, BUY)

**Comment by Jaapapa** [comment]
Can't you just sell at the exchange? In my experience, PT is pretty cool about that and will just forget about the pair alltogether.

**Comment by dechut** [comment]
![image](https://user-images.githubusercontent.com/31846587/34342212-0f6f00a0-e9db-11e7-8b55-fbafb314a4c0.png)

you can see this chart 1 min . when you notice a very high price , and you know it will down soon .

you login bittrex , oh it require 2FA , then it require to verify IP address by email , then login and 2 FA again . total around 5-10 min .

then if we have a "sell now" button is very good .

**Comment by minerdude** [comment]
must have

**Comment by anon059** [comment]
yes, also sometimes we can see profit after long time then it dips below our profit line because there was no enough support at profit<X-trailing>highest price.
I would put bounty on this for developer to have this feature.

**Comment by jbhitman** [comment]
I too would absolutely LOVE to have this button along side the pairs in the pair/DCA logs..as was mentioned above sometimes you just have a gut feeling about something and you want to act _Now_ instead of waiting for the bot to react.  Plus it would be another way for people to feel more "engaged" in the trading process as it would allow them a since of "I can help the bot out" when they feel like it... would pay real money for this feature.

**Comment by taniman** [comment]
Buttons will start to come soon
