### ISSUE TITLE
Error in command prompt when launched: 'java' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by zvaran** [taniman/profit-trailer#469]
Hello, 
I purchased the Profit Trailer bot yesterday, set up the API Keys, Pairs, however I am unable to get the program running on this laptop. When I launch command prompt I get this error: 

'java' is not recognized as an internal or external command, operable program or batch file. 
Press any key to continue 
And when I press something it closes. 

Needless to say, http://localhost:8081/monitoring is showing as inexistent page. 

Can you please tell me which step I skipped ? Or what to do to fix this situation ? (I was looking to start the bot running on bittrex and binance for a week). 

Thanks,

**Comment by zvaran** [comment]
I installed Java runtime environment, think this fixes it.

**Comment by helo03** [comment]
great news you fixed it! I'll close this now! :-)
Happy Trading!
