### ISSUE TITLE
Possible Buy Log is at 0

### ISSUE THREAD

**Issue by ccook029** [taniman/profit-trailer#472]
I just recently made a couple changes to the files and now notice that my possible buy log is at 0.  The Bot is still trading for profit on the coins that it had already purchased, but doesn't look to be buying anything more.

**Comment by helo03** [comment]
You just said it yourself. You made a couple of changes to the files.
You probably have set your max_pairs and you have more active pairs than you've set in your max_pairs.
For this kind of problems, please use the chat to resolve them, as Issues should be used for enhancements, feature requests and bug reports.
Thank you! Have a great day!
