### ISSUE TITLE
Possible Buy Log stays active when ballance exceeds min_buy_balance_percentage = 50

### ISSUE THREAD

**Issue by DeWim** [taniman/profit-trailer#473]
On binance account.

When setting min_buy_balance_percentage = 50 in the pairs config the PB log stays active with trailing pairs when the balance goes below 50%.
This means the 50% gets ignored and the bot keeps buying new pairs instead of preserving the balance for DCA.

Setting min_buy_balance_percentage = 10 in yher DCA properties is working as intended.

On a more cosmetic note. The profit values at the top 'Profit: (0.01 LW)  (0.01 YD)  (-0.00 TD)' arte incorrect. Looks like some of thje values get compounded somehow.

**Comment by taniman** [comment]
Have you actually seen the bot keep buying? PB log stays active bot the bot does not buy anymore. 
It will say in console 'Not allowed to buy ...'

**Comment by DeWim** [comment]
Thank you for your quick responce even during this time of the year, that was a plessant surprise :)

After your explanation of how te bot should react i went through my settings again abd spotted the mistake.
I used 'min_buy_balance_percentage' in both pairs and dca cobfig while it shoul be 'ALL_min_buy_balance_percentage' in the pairs file.

Also want to mention i'm loving your product and the community behind it. Its worth every satoshi spent on it.

Merry Xmas to you and your loved ones and keep up the good work.
