### ISSUE TITLE
PT on Mac

### ISSUE THREAD

**Issue by RICHIRICH64** [taniman/profit-trailer#476]
i cannot get PT dashboard up on mac pro, can anyone help with this please?

**Comment by michel-moreau** [comment]
Maybe I can help. Tell me more

**Comment by RICHIRICH64** [comment]
i did the terminal as you said there, but still no dashboard in brackets

**Comment by michel-moreau** [comment]
you don't need brackets.

Open you webbrowser go to  : http://localhost:8081
