### ISSUE TITLE
Safety feature for stop loss based systems

### ISSUE THREAD

**Issue by cryptojay90** [taniman/profit-trailer#480]
Hi,

ProfitTrailer absolutely needs to have an automatic stop trading feature for stop loss based systems, in case the market takes a giant dump on the bot while you are sleeping.

It could be something like a variable for example x amount of stop losses triggered or consecutive stop losses triggered.

This would be an amazing addition to the bot and I doubt it would be too hard to implement?

Thanks for taking the time and reviewing my request.

With best regards,

CryptoJay

**Comment by Yamakaza** [comment]
Great idea @cryptojay90. I would love this feature aswell. So stop selling via stop loss after x amount of stop losses triggered in a certain timeframe?

Kr,

Yama

**Comment by symbion6** [comment]
+1

**Comment by erknie** [comment]
What I would like to see as a safety feature is the ability to delay the stop loss by a certain number of candles you can set. The idea being to stop crazy sell offs like what happened to GDAX with ETH last year, causing them to issue a massive refund. If you get a huge sell order that buys up the order book, it can cause a massive drop in price on just one candle, causing stop loss and margin calls to trigger. If you have the option to delay the stop loss by a candle or two, that will prevent these kind of short duration downward spikes that usually recover on the next candle.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
