### ISSUE TITLE
confusion on wiki page about pending order cancellation 

### ISSUE THREAD

**Issue by vincent0923** [taniman/profit-trailer#481]
https://wiki.profittrailer.io/doku.php/pairs.properties

"ALL_combined_cancel_pending_trigger = 0
Valid Values: true, false or 0
Cancel pending order for specified coin if avg profit reaches specified amount"

can anyone from the team explain what this means?
i thought this command was supposed to be used with a positive number?

**Comment by taniman** [comment]
it has been fixed now

**Comment by Mikeeetrue** [comment]
Where can I read the answer? Is it possible to use negative numbers which are more usefull?

**Comment by taniman** [comment]
yes. you can sue negative numbers too
