### ISSUE TITLE
bot tries to buy EVERYTHING

### ISSUE THREAD

**Issue by deesun** [taniman/profit-trailer#485]
so i got this nice bot running for weeks now, not a single problem until today:

the telegram bot sent me the message: "there is something wrong with your bot, restart it"

the message came every minute, so i watched the bot what it does... it bought every pair from the "possible buys log"
(only 2/30 were trailing, the others not but the bot bought ALL pairs until it reached the min buy balance!)

the possible buys log did not update any more, but it wanted to do further buys... i restartet it, same issue again, no "possible buys log" update and bot still tries to buy.

i updated to 1.2.6.6 and enabled the testmode, but the bot still wants to buy, even there is nothing in the possible buys log.

**Comment by deesun** [comment]
watched it a while now (1.2.6.6 running on a Pi 3, trading on binance):

the telegram error "something is wrong with your bot, restart it" did not appear again.
the "possible buys log" filled again after i reduced the pairs from 50 to 30.
its trailing 3 pairs, and did not try to buy again.

if i switch testmode off, the log says: "you are not allowed to buy [pair]. buy will exceed min buy balance" which it misunderstood as a "try to buy", but the bot does not buy if i reduce the min balance.
i guess this is just a status update and the testmode disables this (too).

but the bot bought some pairs which were flagged "false" in the possible buys log until it ran out of funds.
maybe the log is lagging a bit and this was a real market movement, i watched the charts after this happend with the same indicator settings as the bot has.
there was a drop in some pairs, but not strong enough to buy, the bot bough anyways.

**Comment by taniman** [comment]
A log file whould be great to debug this. Please upload or send to me on telegram

**Comment by deesun** [comment]
i can send it on telegram. same name as here? taniman?

**Comment by taniman** [comment]
@elroy on telegram
