### ISSUE TITLE
Sold Value in Sales log appears incorrect when using Bittrex

### ISSUE THREAD

**Issue by tcoffman** [taniman/profit-trailer#489]
In reviewing the sales log data and comparing the 'Sold Value' to the bittrex sell 'proceeds' data. It appears this calculation is using a .5% commission modifier. This should not be the case as bittrex uses a .25% commission.

-Tim

**Comment by taniman** [comment]
You should only look at the profit. and compare those. The first .25% is taken on the buy and on sale another .25% so .5% need to be taken of to display the correct profit
