### ISSUE TITLE
[Feature Request]  Do not purchase a pair after a certain % rise.

### ISSUE THREAD

**Issue by bmanb** [taniman/profit-trailer#490]
It would track the 24H% gain column of the ALT pair and a user could indicate not to trade any pair above a certain percentage.

For example you set it to not trade any pair above 20% for all alt pairs.  If any of the pairs that would normally be eligible per your trade criteria go over 20%, they would be excluded from entering new positions.  It would work similar to sell only mode for BTC itself except applied to each ALT pair.

**Comment by mecutemecute** [comment]
I second this idea. most of my bags are from coins that are already pumped.  A configurable setting to not buy XX coin after YY rise would be very smart and useful.

**Comment by shawndamon** [comment]
this would be handy indeed....

**Comment by taniman** [comment]
See #219
