### ISSUE TITLE
Data is DOWN: "There was an error while refreshing the data"

### ISSUE THREAD

**Issue by oneezy** [taniman/profit-trailer#491]
I thought this was something I did, but it looks like it's even happening everywhere. Even on your **Demo** page.

![image](https://user-images.githubusercontent.com/7369575/34401931-fb105340-eb63-11e7-9b71-88a81b72b2bd.png)

![image](https://user-images.githubusercontent.com/7369575/34401862-a53fa56a-eb63-11e7-8a2a-f4c6e577ea15.png)

![image](https://user-images.githubusercontent.com/7369575/34401927-f61076d6-eb63-11e7-8be4-90ec9e71e4aa.png)

**Comment by Murcho** [comment]
Seconding this issue on my instance.

**Comment by CryptoTropico** [comment]
I am having the same error
