### ISSUE TITLE
binance - mod suggestion to bypass the btc trigger issue

### ISSUE THREAD

**Issue by bloodbit** [taniman/profit-trailer#492]
Hi,

First of all, I would like to thank the team for Profit Trailer and their commitment to keep up with the updates.
I have been starting in Binance and lately missed the possibility to automate SOM because of BTC rise and drop triggers issue.

On a global note, it would help to have the possibility to automate 3 sets of properties for the different trends: bullish, bearish and something in between. 
And if we use existing properties for “something in between” everybody’s life will be easier.
To bypass the btc trigger issue and deploy the different sets of propertie I would suggest calculating the weighted average of what we have in DCA and/or PAIRS.

To the PT team and community, I wish a Happy New Year!
rui

**Comment by taniman** [comment]
You idea just made me realise that I have a task open to make the BTC tirggers more flexible in version 1.2.7
So that will fix the binance problem too. 

See #196 

your idea is good, but I will go with the most simple option first and than build on top of that. But tnx
