### ISSUE TITLE
[Feature Request] Build long-term position in Coin

### ISSUE THREAD

**Issue by steveoneal** [taniman/profit-trailer#501]
I would like to see a way to build a position in a particular coin.  For example, I want as many COIN_X as possible.  I start by buying .5 BTC worth.  Then let the bot buy/sell to build the position, selling x% when it's high and using the received funds to purchase as many as possible when the price drops. 
Not sure if this is feasible or how it would be implemented, but I do this now manually and it works well to build a long-term position.

**Comment by taniman** [comment]
@RchGrav

**Comment by Stoley** [comment]
+1

**Comment by sebi1505** [comment]
+1
