### ISSUE TITLE
Always on Buy: ERROR ProfitTrailerService - Error occured in buy, message String index out of range: -10, result:

### ISSUE THREAD

**Issue by Dimeg** [taniman/profit-trailer#502]
Always getting "ERROR ProfitTrailerService - Error occured in buy, message String index out of range: -10, result:" on buy.

Maybe it is possible to enable more enhanced log?

**Comment by oJshua** [comment]
Also noticing this in 1.2.6.7. Using Bittrex. No buys are going through.

**Comment by taniman** [comment]
enhance can already be enabled. please contact support as this is not an issue

**Comment by oJshua** [comment]
I'm sorry @taniman . I'm new to Profit Trailer is this a Bittrex thing or something I need to fix in my settings?

**Comment by Dimeg** [comment]
Found the issue for my problem. Was problem with IP filtering in Bittrex.

**Comment by oJshua** [comment]
@Dimeg so do I just add my IP to the whitelist? I didn't know that applied to the API settings in Bittrex.

**Comment by oJshua** [comment]
It worked:). Thanks @Dimeg .
