### ISSUE TITLE
[Request] Excel output logs

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#505]
I have the following request ("sales-log.xlsx" being the most important):

1) Using Excel 2007, in "sales-log.xlsx", "pairs-log.xlsx" and "dca-log.xlsx", it does not understand the date format "26.12.2017 09:09".
   **Request:** Is it possible to rather have the same format "2017-12-26 09:09" as the "ProfitTrailer.log" file.

2) The "sales-log.xlsx" column "Bought Price" contains merged values that is not usable.
   **Request:** Could they rather be split into 2 columns namely "Bought Price" and "DCA" each just containing one value.

3) The "dca-log.xlsx" column "BB / Trigger" contains merged values that is not usable.
   **Request:** Could they rather be split into 2 columns namely "BB" and "Trigger" each just containing one value.

4) The "dca-log.xlsx" column "Current PriceAverage Price" contains merged values that is not usable.
   **Request:** Could they rather be split into 3 columns namely "Current Price", "Average Price" and "DCA" each just containing one value.

5) The "dca-log.xlsx" column "Current ValueTotal Cost" contains merged values that is not usable.
   **Request:** Could they rather be split into 2 columns namely "Current Value" and "Total Cost" each just containing one value.

I have not used "pending-log.xlsx", but similar requests might apply.

**Comment by DemoFreak** [comment]
+1

**Comment by vicenterusso** [comment]
+1

**Comment by Stein276** [comment]
+1

But for now, as an example, I dump my sales data to a dummy page with the first date in cell B2.
In cell A2 I use the formula =DATE(MID(B2,7,4),MID(B2,4,2),LEFT(B2,2)) to extract the date from B2

On my main page I use countif, countifs and sumif formulas to grab all data needed from my dummy page.

Of course all work is done in vba and I just click a button once my sales log is on the clipboard.

But I'd prefer to have what you've described.

**Comment by swoopsus** [comment]
+1, but also would like to date the positioned was opened, not just closed. Otherwise there is no way to go back and look at the charts and learn from those charts what to tweak in the config because you don't know when it was bought.

**Comment by Stein276** [comment]
A Buy date (with time) and a Sell date (with time) would be very useful. We could use these in excel to further analyse coins to come up with a list of the quickest trades, thus giving us a whitelist, blacklist and a quicklist of all coins.

**Comment by chrisek** [comment]
Take a look at my file, 
https://docs.google.com/spreadsheets/d/1_S4WjqOHdXW2eLCu3eUN5m2PSasK5PHkayuxieelglE/edit?usp=sharing
