### ISSUE TITLE
Profit Trailer Stop

### ISSUE THREAD

**Issue by mailpramodkg** [taniman/profit-trailer#506]
Hello Team,
I am running profit trailer on VPS and currently around 17 trades open! and DCA also have some trades! I would like to replace the pairs DCA and indicators files with new settings! how to safely stop and update the new settings! what will happen to the current open trades and on DCA? will it goes loss? please help

Regards,
Pramod

**Comment by mailpramodkg** [comment]
currently i have settings on DCA,PAIRS and Indicators files to be replaced with new files and settings! I m worried what will happen to the Open trades and the trades on Dust Log and DCA logs! Your suggestions will be more helpful

**Comment by YoJeff** [comment]
Ask in the support channel -- this is for bugs.
