### ISSUE TITLE
[Feature Request] Log of Daily profit to keep track

### ISSUE THREAD

**Issue by razorseal** [taniman/profit-trailer#507]
Hello,

I think it would be very beneficial if you could make the daily profit a log, so we can keep track of it automatically. I know some users including me create an excel sheet to try to keep track of things. It would be great if we could get an excel created, or a small log just to show our daily profits. I would assume it would be fairly easy to implement.

Thank you.

**Comment by mrlex** [comment]
Isn't the Excel CSV file generated in the Sales Log of PT exactly for that? 

You have the dates, the pairs, profit in BTC and USD. I use it with CoinMarketCap's API in Excel to create my charts and my analysis.

I don't meen to be rude here, I am simply wondering why you're requesting this if you already have all the tools and the data to accomplish this.

**Comment by razorseal** [comment]
Not really...

Try adding up how much you made for a week or a month without doing tedious work. You cant auto sum because the btc and USD values are put together. You have to take out dollar or btc value out.

Getting average profit % is not too hard, but why not open another page where daily profit in percentage, USD and btc is displayed? 

I mean you're doing work to get information (you opening excel and calculating) when it could just be displayed? 

I know you're not being rude, but you are doing work to get numbers. Why not automate it? 

Can ya tell me. How much USD you made in less than 1 minute?

**Comment by taniman** [comment]
'fairly easy to implement' is a  big sentence. 

The more things we try and safe. The more data that get's lots if the safe file gets corrupted.
The dollar values are not helping with calculations in excel. But this will be fixed in a future version.

**Comment by razorseal** [comment]
Well at least I appreciate your response, and you are the developer, but I'm trying to figure out how much I made in the past week, and it's physically not possible right now on excel. I would have to format hundreds of cells from BTC (USD) to BTC or USD...

it's simply not managable to figure out how much you've made unless you spent hours trying to figure it out.

I didn't make this so I can't imagine if it would be easy to implement what I'm asking, but your software already does the calculation for profit made for the day. All it would have to do it is log that profit made to a file before writing over it. I can't imagine it being too involved. the calculation is already made, instead of dumping it, it just would log it somewhere. 

I just tried to figure out how much I made for last week, and I gave up after 20 lines... I have hundreds of lines to go through

**Comment by cguanzon** [comment]
@razorseal while there is no fix yet, what I do to split the btc profit and the dollar equivalent is to use Desktop Excel's and Google Spreadsheets' Text to Columns functionality. you first split using `(` as the delimiter, then do another split after that using `)` as the delimeter. This is much faster than manually deleting each opening and closing perenthesis.

I hope this helps.

**Comment by chrisek** [comment]
You can use this file:


https://docs.google.com/spreadsheets/d/1OXcZfx6pJ5kuB20rnqTWj_HzxBDgjxslU8-YDTci0tY

Have a nice day!

**Comment by mrlex** [comment]
Nice work there Chrisek. This sheet will be very useful :)

**Comment by clownfish44** [comment]
I use the one linked by chrisek and it is excellent!

**Comment by minerdude** [comment]
Thanks @chrisek !

**Comment by razorseal** [comment]
@chrisek Thanks for that! That's great!

However I have one question (I can't seem to find your username on telegram with chrisek)

When I paste into the PT DUMP, it's only for the let's say last 7 days of data. everyday, the "8th" day gets deleted as it rolls over... How do you keep copy pasting? When I copy paste, it will roll over the previous stuff and delete the data on that "8th day" on the PT tab...

hope what I'm saying makes sense?

**Comment by YoJeff** [comment]
Daily profits are now available in PT-tracker.   If some subset of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
