### ISSUE TITLE
Can't DCA warning

### ISSUE THREAD

**Issue by simo-simo** [taniman/profit-trailer#508]
![dca error](https://user-images.githubusercontent.com/34457590/34442137-3d50422e-ecd1-11e7-9d0f-45c5320e3f2b.png)
so this warning keeps going off, I get it, I have DCA disabled anyway. It's spamming my log.

**Comment by simo-simo** [comment]
weirdly enough, if I ENABLE DCA, the warning comes up once only.

**Comment by taniman** [comment]
Well the warning is already telling you the problem. So change your configuration.properties back
