### ISSUE TITLE
ERROR Application - INVALID LICENSE (windows only)

### ISSUE THREAD

**Issue by lukas-dev** [taniman/profit-trailer#509]
I was able to successfully start profit trailer on a mac. However when I stopped profit trailer on the mac and started the application on a windows server instance which is running on a virtual server the following message is displayed on the console:

ERROR Application - INVALID LICENSE

Then the application stopps. What does this mean? My license IS valid, otherwise I would not be able to run the application on my mac.

**Comment by lukas-dev** [comment]
Ok here is what I to make sure the problem is **not** related to the the bittrex api or any ip address issues.

I used an http client (postman) and sent two http requests (one for each api key/secret pair) to get my balances as described in the bittrex rest api documentation. I executed these requests on the same maschine where I get the "ERROR Application - INVALID LICENSE" message when I run profit trailer. However I was able to successfully load my balances!

So obviously something is wrong with profit trailer. Can somebody help me out please?

**Comment by lukas-dev** [comment]
3 days passed and still not even 1 answer? I expected to get more support for a 400$ software which right now is completely unusable for me.

**Comment by felipeff** [comment]
You should probably use the telegram support channel instead of github. github is for improvement suggestions/bugs.

**Comment by lukas-dev** [comment]
I tried! I repeatedly posted my question there, but did not get any help except for people questioning me if I use the right java version (which of course I do)!

**Comment by felipeff** [comment]
Did you tried to check if there isn't any spaces in the end of your license? 
it should be default_apiKey = LICENSE
1 space after the = sign and no spaces in the end.

You may also try to use some text editor other than notepad. Notepad doesn't handle the file encoding properly and the documentation does not recommend using it. I did change my settings using Atom editor.

**Comment by lukas-dev** [comment]
Yes, there is not any space behind the keys and 1 space between the = sign and the key.
I edited the files on my mac. The program works on the mac but fails (with the same files!) on windows.

**Comment by taniman** [comment]
Most probably because you the files are safed differently on the 2 systems. When on windows open the files with notepad++ edit and save again. So the file formats can be converted properly.

What version of the bot is this?

**Comment by taniman** [comment]
and to answer your complain about support. This is not the place to get support. So you cannot expect answers here. This is a setup issue and you should join our support channel on Telegram for this

**Comment by lukas-dev** [comment]
The bot is running now. The problem was not caused by the file formatting. I could not ping profittrailer.io. As it turned out my VPS and the profit trailer server are hosted by the same host. I contacted the support and they fixed their incorrect network configuration.

**Comment by ahmedabdrapo** [comment]
Sorry @taniman 
Here is not the right place to get help?
Your clients will not spread their issues and problems and your robot bugs every where seeking for help if you are giving them the proper support through your Tickets and email like any respected company.

I started to hate your robot for the horrible support and the feeling that I'm left alone.

Oh yea .. I have the same INVALID LICENSE SHIT in my Raspberry pi 3 while it's working on Windows 10

**Comment by jasonet** [comment]
same INVALID LICENSE problem on cantos 6
