### ISSUE TITLE
Possible Buy Log: Current BB, BB Trigger, Current Value fields not populating after switching to VPS

### ISSUE THREAD

**Issue by BGL1000** [taniman/profit-trailer#510]
Hey, 

Everything was working fine on my personal computer, but after I switched to a VPS service, the Possible Buy Log is not working correctly. I still get all of the pricing data and the Buy Value. However, the "Current BB," "BB Trigger," "Current Value" fields will not populate. I have triple checked that test mode, sell only mode, balance, and buy value issues aren't present, and the bot runs fine when I turn it back on using my Desktop with the same settings.

**Comment by taniman** [comment]
Please this is not an issue. Ask for support in our support channel
