### ISSUE TITLE
[Request] Price Fall Protection

### ISSUE THREAD

**Issue by Bbrandwin** [taniman/profit-trailer#511]
Often times when the bot goes to sell, the price is falling rapidly. This cause the sale to cancel several times before executing. Can you implement a value that we can subtract from the bid price in order to "catch" a falling price. In other words when the bot executes a limit sell, it will instead be for X percent lower than the bid price. A value of 0 will limit sell at bid and a value of -.25 will limit sell at .25% LOWER than the bid.

**Comment by DJSean00** [comment]
Totally agree - great idea!

**Comment by Utone** [comment]
+1 this with rsi would be killer, good idea now trailing buy can't grab these and waits for next target or drop.  So they get snatched away under your nose;) what trailing profit size have you used so far?
I hear negative bb or high ema gain without trailing does come close

**Comment by taniman** [comment]
The bot does not do limit sell order. All orders done are fill or kill. And this is the desired way of using the bot.
