### ISSUE TITLE
ALL_min_buy_volume ... history/average

### ISSUE THREAD

**Issue by Al0815** [taniman/profit-trailer#512]
I hope this is no doublett, 'cause I where talking so often about this.
But I searched over the issues and find nothing.

How would it be, if the bot could hold a history of past coin volumes?
Say for example x Points, 12 hours ago, 24h ago, 36h ago,... with a moving marker once an hour.

And then, you can set an option buy only, if x of the last markers where above the given limit. 

Or an average of multiple markes, like 24 markers, one for every hour of the last 24h Marker moved and average calculated once an hour. With a difference of a few sec between each coin, to lower load.
And then an option to buy only if average volume of the last 24h hours is over that limit.

Yes, we can spin this even further. Like an options to set an pair to SOM if it goes under the given average value. 

But for startes, just the buy options would be another nice option to avoid some pumps&dumps.

**Comment by YoJeff** [comment]
#80
