### ISSUE TITLE
INFO: Initializing Spring FrameworkServlet 'dispatcherServlet' Stuck

### ISSUE THREAD

**Issue by bvandermeersch** [taniman/profit-trailer#515]
Try to start the bot and its stuck at:

.8.0_151
Dec 29, 2017 6:41:59 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Dec 29, 2017 6:41:59 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.15
Dec 29, 2017 6:41:59 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
2017-12-29 18:42:00 INFO Util - Detected configuration changes
Dec 29, 2017 6:42:00 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8081"]
Dec 29, 2017 6:42:00 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8081"]
Dec 29, 2017 6:42:00 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
2017-12-29 18:42:00 INFO ProfitTrailerService - Cache Heartbeat
2017-12-29 18:42:01 INFO ProfitTrailerService - Normal Heartbeat
2017-12-29 18:42:01 INFO ProfitTrailerService - DCA Heartbeat
Dec 29, 2017 6:42:12 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'

The console shows this, then nothing else. GUI loads but no trading or anything and the GUI isnt up to date.

**Comment by taniman** [comment]
This is a setup/system problem. not an issue. please contact one of our support agents on telegram
