### ISSUE TITLE
PT won't abide to ALL_max_trading_pairs on Bittrex

### ISSUE THREAD

**Issue by razorseal** [taniman/profit-trailer#516]
I currently have ALL_max_trading_pairs = 5, but this is the 3rd time Bittrex has now over purchased pairs...

I'm currently at 9... 

Running 1.2.6.6... It's done this multiple times with 1.2.6.1 but first time on 1.2.6.6... Any ideas? I can provide a log, but not sure how to do it. 

It's eating up my reserves real bad, and kills my DCA strategy when it does this. Thanks

**Comment by taniman** [comment]
upgrade to 1.2.6.7 and if it happens on that version send me a log file on telegram
