### ISSUE TITLE
ERROR Util - Error reading file java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by theMadMonster** [taniman/profit-trailer#517]
PC running PT crashed. When restarting PT I get the following error in the console. 
ERROR Util - Error reading file java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by taniman** [comment]
This issue is described on the wiki
https://wiki.profittrailer.io/doku.php/common_errors

**Comment by theMadMonster** [comment]
Still getting the error after replacing ProfitTrailerData.json with the backup. I just deleted the json files and restarted. Lost history, but its running again. Thanks
