### ISSUE TITLE
activation of another key issue

### ISSUE THREAD

**Issue by m4k3rz** [taniman/profit-trailer#520]
I originally bought PT Bittrex and licensed an API key from my Bittrex account X. Days after, I decided I wanted to get my PT Bittrex both to trade on my other Bittrex account Y. So I went to PT assistant on TG and got the API key from Bittrex account Y activated. Then, I modified file application.properties and used the licensed API key from Bittrex Y under default_apikey AND I generated another API key from Bittrex Y to be used on trading_apiKey. This made the bot throw constant java errors on the console. It got fixed when I moved the licensed API Key from Bittrex Y to trading_apiKey field. So as of now, the licensed API Key from Bittrex Y is being used in both fields, default_apiKey and trading_apiKey. Although the bot is working fine now, I remember reading this is not optimal and can result in slowness. Hence, I would like to now what API key should I use where. 
Thanks

**Comment by taniman** [comment]
using same api key for bittrex should work fine. 
please contact support for more information on this. This is not a software issue

**Comment by m4k3rz** [comment]
do you mean using the same API in the default_apikey and trading_apikey is fine? How do i reach out to support? I thought this was support. thanks
