### ISSUE TITLE
When using percentage show calculated value in monitor

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#521]
When min_buy_balance_percentage or max_cost_percentage are used it would be great to see the calculated values on the monitor.

This could also help newcomers to better understand what‘s going on.

**Comment by bverkron** [comment]
Is this max_cost_percentage in DCA settings?  I can't find a reference to that setting anywhere. Just max_cost

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
