### ISSUE TITLE
Auto Refresh Prevents me From reveiwing my sales log

### ISSUE THREAD

**Issue by Bbrandwin** [taniman/profit-trailer#523]
The auto-refresh causes the sales log to jump to page one. I can't review sales on older pages because there's not enough time to look at them before it refreshes back to page one.

**Comment by taniman** [comment]
workaround. create an excel export

**Comment by djcrypto75** [comment]
Can you give me more details how you have set up the bot so i can replicate the problem?

**Comment by YoJeff** [comment]
fwiw, this has always happened to me as well.   Goto sales page, click page > 1, wait for background refresh.

**Comment by DemoFreak** [comment]
+1

**Comment by djcrypto75** [comment]
Not able to replicate the problem, i need some more details on how you have set up your bot, perhaps a reverse proxy is in use or some other details.
