### ISSUE TITLE
Please add a minimum balance for each trading pair after a sell

### ISSUE THREAD

**Issue by DrewKiino** [taniman/profit-trailer#524]
I would like to hold a coin and simply make profits off the trailing peaks. 

ex:
$0.50 -> $1.0 -> DIP trigger. then sell only 30% but keep 70% in balance so I'm left with $0.70 in balance but sold $0.30 to market pair like ETH or BTC.

I think this would be an amazing feature to help HODL users like me while still making use of PT as a margin profit maker.

**Comment by ChrisBridle** [comment]
+1
