### ISSUE TITLE
[REQUEST] "I'll Take That"

### ISSUE THREAD

**Issue by c64audio** [taniman/profit-trailer#525]
How about an "I'll take that" button next to a pair that activates when the pair is over the designated profit and does an immediate sell? Quite often I've been watching the bot and the profit gets to e.g. 5% and then the trail drops it to 1.4 or something. I'd quite like to be able to say "Yeah, I'm happy with that", and cash it out.

**Comment by MeisterPilaf** [comment]
I would prefer a button and a config wich says "if the pair/DCA is over XX% stop to trail and sell it immediately".

**Comment by DemoFreak** [comment]
Good ideas both. :-)
ALL_max_trailing_profit = 
and a "Sell immediate" button next to the coin in pairs log and DCA log.

**Comment by taniman** [comment]
I am pretty sure there is already an isue for everything currently said in this issue. 

Please try to search before creating new issues.
