### ISSUE TITLE
[REQUEST] Time Zone and 24/12 format adjustment

### ISSUE THREAD

**Issue by Bbrandwin** [taniman/profit-trailer#527]
It looks like the time zone for the bot and logs are in GMT. At the very least a GMT adjustment would be a great addition to the config or application files. A 12 hr format would be nice too but not as essential. It's tough to back test strategies when the time is off.

**Comment by taniman** [comment]
I suggest you take a look at the wiki again. We do support other times zones. You just have to set it.

https://wiki.profittrailer.io/doku.php/application.properties

**Comment by Bbrandwin** [comment]
Thank you!
