### ISSUE TITLE
Issues with life update bar

### ISSUE THREAD

**Issue by clownfish44** [taniman/profit-trailer#528]
Live bar at the top shows 0.00 for profit even though I have a profit, please add more places for longer numbers like 0.0005. I would also like to see the trend and other numbers also not say 0.00 like btc trend 24 hour on the right!
![image](https://user-images.githubusercontent.com/15145228/34462666-d5a1aa2c-ee16-11e7-8147-e5974e2fc435.png)

**Comment by taniman** [comment]
Places up there are limited. so actually this is not an issue. Also somone already requested something simialr
