### ISSUE TITLE
SMA/EMACROSS sell strategy

### ISSUE THREAD

**Issue by tjeenz** [taniman/profit-trailer#530]
I'm currently using the SMACROSS to define when the bot needs to buy. However, for the strategy I would like to test, I would like to use the SMACROSS to trigger the sell as well. 

I already tried to configure the PAIRS file with an SMACROSS as a sell triger but when the conditions are met, it doesn't sell. So I suppose this is not supported (yet) by Profit Trailer. 

Is this in development? It would be great a great feature :).

**Comment by taniman** [comment]
see #370
