### ISSUE TITLE
Sell Log doesn´t work - no profit/loss history - BITTREX

### ISSUE THREAD

**Issue by wolfman77** [taniman/profit-trailer#533]
Instead I always get this error message when bot sells. 

2018-01-01 12:34:54 INFO ProfitTrailerService - Get order information -- 200 - We got some incorrect data from the exchange -
2018-01-01 12:34:54 ERROR ProfitTrailerService - Error occured in sell, message Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive, result: {"OrderId":"a727caba-1bef-4959-95f4-dc858f82e68e","MarketName":"BTC-XRP","MarketCurrency":"XRP","BuyOrSell":"Sell","OrderType":"LIMIT","Quantity":10.76580779,"Rate":0.00014383}

**Comment by taniman** [comment]
What versionof the bot is this?

**Comment by wolfman77** [comment]
All versions, on Bittrex, although i set history = 30 days.

**Comment by wolfman77** [comment]
Hi,

 

I　am running the bot on Win10. Since I started the Bittrex License, I never saw buys/sells in history, hence no profit calculation or daily turnaround.

I tried the recent 4 versions, all showing me the same issue. Trading/selling works, but there is an error msg like the one I posted ON EVERY buy/sell.

 

I am not having this issue with my Polo Bot, it is working fine without trouble.

 

What is causing this issue?

 

Cheers,

Wolf

 



Gesendet: Montag, 01. Januar 2018 um 13:37 Uhr
Von: taniman <notifications@github.com>
An: taniman/profit-trailer <profit-trailer@noreply.github.com>
Cc: wolfman77 <der__wolf@web.de>, Author <author@noreply.github.com>
Betreff: Re: [taniman/profit-trailer] Sell Log doesn´t work - no profit/loss history - BITTREX (#533)


What versionof the bot is this?

**Comment by taniman** [comment]
Sell log works fine. So please ask support to help you with setup as this is not an issue

**Comment by wolfman77** [comment]
This is NOT a setup issue! The bot uses exactly the same setup as my Polo bot - only logical details are different (login details, etc.).

 

So there must be another reason for this. I GET HISTORY on Polo, and telegram bot works on Polo, BUT NOT ON BITTREX.

 

Gesendet: Dienstag, 02. Januar 2018 um 19:59 Uhr
Von: taniman <notifications@github.com>
An: taniman/profit-trailer <profit-trailer@noreply.github.com>
Cc: wolfman77 <der__wolf@web.de>, Author <author@noreply.github.com>
Betreff: Re: [taniman/profit-trailer] Sell Log doesn´t work - no profit/loss history - BITTREX (#533)


Sell log works fine. So please ask support to help you with setup as this is not an issue

**Comment by taniman** [comment]
The error message you posted in the issue has been fixed in 1.2.6.8
So if you can try that version and let me know if you sell log still does not appear.

**Comment by wolfman77** [comment]
I am already using that version, deleted logs. stopped/restarted bot countless times AND restarted Win inbetween.

Nothing helps. Polo runs flawlessly in parallel.

 

Gesendet: Dienstag, 02. Januar 2018 um 22:43 Uhr
Von: taniman <notifications@github.com>
An: taniman/profit-trailer <profit-trailer@noreply.github.com>
Cc: wolfman77 <der__wolf@web.de>, Author <author@noreply.github.com>
Betreff: Re: [taniman/profit-trailer] Sell Log doesn´t work - no profit/loss history - BITTREX (#533)


The error message you posted in the issue has been fixed in 1.2.6.8
So if you can try that version and let me know if you sell log still does not appear.

**Comment by wolfman77** [comment]
Since yesterday night I get followin error message on Polo:

 

2018-01-03 11:26:53 ERROR Application - Please fix: trading_apiKey -- nonce error: {"error":"Nonce must be greater than 151388396329900000. You provided 15149752122720000."}

 

Trading key is valid. What is the problem?

 

 

 

 

 

Gesendet: Dienstag, 02. Januar 2018 um 22:43 Uhr
Von: taniman <notifications@github.com>
An: taniman/profit-trailer <profit-trailer@noreply.github.com>
Cc: wolfman77 <der__wolf@web.de>, Author <author@noreply.github.com>
Betreff: Re: [taniman/profit-trailer] Sell Log doesn´t work - no profit/loss history - BITTREX (#533)


The error message you posted in the issue has been fixed in 1.2.6.8
So if you can try that version and let me know if you sell log still does not appear.

**Comment by taniman** [comment]
looks like your poloniex api key with some other bot
