### ISSUE TITLE
[Feature Request] - HODL Log

### ISSUE THREAD

**Issue by BassJunkieeeee** [taniman/profit-trailer#535]
I would like to classify a coin as holding and for the GUI to have a section (HODL Log) where these coins are stored.  For example

BTC-DGB_hodl_enabled=true

If this is set to true then the coin is also not traded, but you should still be able to set bought price, date, etc

Note that coins set with BTC-DGB_trading_enabled=false also get counted as a trading pair in the ALL_max_trading_pairs = 5 setting. Would be great if the hodl coins weren't included in this count.

Thanks

:)

**Comment by Q-Rush** [comment]
> Note that coins set with BTC-DGB_trading_enabled=false also get counted as a trading pair in the ALL_max_trading_pairs = 5 setting. Would be great if the hodl coins weren't included in this count

https://wiki.profittrailer.io/doku.php/pairs.properties says:

```
ALL_hidden_pairs = BTC-ETH, BTC-LTC
BTC-ETH_trading_enabled =  false 
BTC-LTC_trading_enabled =  false
```

(This setting is used in version 1.2.6.1 or later) 
If you would like to hide coin pairs from the bot, use the above “hidden” settings. Trading for each pair must be disabled as shown above. 
Note: Remember to change the BTC-XXX to be formatted properly for the exchange. (BTC-XXX is for Bittrex, BTC_XXX is for Poloniex, and XXXBTC is for Binance)

**Comment by taniman** [comment]
You can just disable trading for that coin.
