### ISSUE TITLE
Use system/java proxy settings for http/https connections

### ISSUE THREAD

**Issue by cmstest** [taniman/profit-trailer#537]
Hello and happy new year!

We were notified that our hosting provider would require use to use a http/https proxy to connect to the internet due to stricter regulations.

Could you please include a possibility to specify http/https proxy ip and port? We already tried by setting global java proxy settings, but the bot is ignoring them and can't connect to the internet.

I don't know what java library you are using for making the http connections, but with Apache HTTP Client for example, it would only take you one method call (useSystemProperties()) when you're already using HttpClientBuilder to use system proxy settings, specified in net.properties:
`HttpClientBuilder.create().useSystemProperties().build();`

Thank you very much and best wishes!

**Comment by taniman** [comment]
I fail to see how a proxy to connect to the internet will make the bot fail to work properly. A proxy setting is a global internet setting you set right? 
Will you be changing any games that connect to the internet too? Or your microsoft office or any other program?
yes I know you are talking about a VPS. But my point is. This proxy settings should be a global setting and should work for all programs that connect to the internet

Or am I missing something

**Comment by cmstest** [comment]
Ummm there is no chance for the bot to connect to the internet without passing the proxy, as the proxy is the gateway to the internet.
Proxy settings are set for the system, but the bot is not using them. The bot is trying to connect to the internet without the proxy. We've already tried to set java/jvm properties for http.proxyHost and https.proxyHost, but that doesn't work either, as those settings are not used by the bot either.
We don't know what http client library you are using with the bot, we only found out that the Apache Http Client needs special configuration to use system proxies, as it defaults to not using any proxy.
More information here: https://stackoverflow.com/questions/5165126/without-changing-code-how-to-force-httpclient-to-use-proxy-by-environment-varia

This blog entry states a possible quick fix for Apache Http Client to use system proxies: https://texnoblog.wordpress.com/2013/06/24/java-httpproxy-apache-httpclient/

Our connection in the datacenter is like this:
Our virtual machine for ProfitTrailer -> datacenter internet gateway (http/https proxy) -> internet

Every traffic from internal systems has to pass the internet gateway, as this is due to regulations (we are not hosting in a normal datacenter with open internet access for everyone, this is a high security banking datacenter with special security restrictions in place).

> I fail to see how a proxy to connect to the internet will make the bot fail to work properly.
The bot won't work at all without internet access :) And internet access is only possible when using the proxy from system settings or jvm http.proxyHost/https.proxyHost. Otherwise the bot won't ever be able to connect to the internet.

> Will you be changing any games that connect to the internet too? Or your microsoft office or any other program?
Yes, we have to change every other program too, so every program will be using the proxy. Otherwise no internet connection is possible.

I'm happy to assist you with anything that helps resolving this issue and getting proxy support into the proxy :) Please feel free to ask and get back to me.

Thank you very much and best wishes.
