### ISSUE TITLE
[Bug] Sales log search not working for some coins

### ISSUE THREAD

**Issue by twig123** [taniman/profit-trailer#540]
So, I found a strange thing. I'm able to search the sales log for most coins no problem. However, when trying to search for "ARK" absolutely nothing happens, and all of the unfiltered coins are still shown. The search works when I look for "BTC-ARK", but fails to properly search/filter if I just type "ARK".

This is the only coin that I noticed it on as other that I've tried have worked just fine, so I'm not sure if this effects other coins or not.

**Comment by djcrypto75** [comment]
Try and clear cache.
