### ISSUE TITLE
Forgive me, I'm a NOOB (Can't get profit trailer up and running)

### ISSUE THREAD

**Issue by barryjenk777** [taniman/profit-trailer#543]
I can't get my dashboard up and running.. i paste the final java code and get the below error.  Any ideas?  

.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/barryjenkins/Desktop/ProfitTrailer/ProfitTrailer.jar!/BOOT-INF/lib/spring-core-4.3.7.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
9.0.1
2018-01-02 13:31:29 ERROR Application - Please install java 8

**Comment by taniman** [comment]
the error says.  Please install java 8
Remove java 9 and install latest java 8 version
