### ISSUE TITLE
Sell order not working but shows entries in log - Gain Strategy on Bittrex

### ISSUE THREAD

**Issue by OneCryptoSon** [taniman/profit-trailer#544]
Using PT version 1.2.6.8 on Bittrex with GAIN strategy

I'm getting intermittent sell issues where the sell order shows in log, but doesn't go through on Bittrex.

The only pattern I see in all of these is that QuantityRemaining doesn't go to zero and the following variables are such:

"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000000,"Price":0.00000000,"PricePerUnit":null,

Here's an example of orders that didn't go through for the same pair on the exchange:
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:08 INFO ProfitTrailerService - Sell order for BTC-TRIG sold amount 2.886767 for price 0.000426 -- {"OrderId":"1a211b08-20cf-46b0-a6e4-fd6c342fcf60","MarketName":"BTC-TRIG","MarketCurrency":"TRIG","BuyOrSell":"Sell","OrderType":"LIMIT","Quantity":2.88676658,"Rate":0.00042551}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:14 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"1a211b08-20cf-46b0-a6e4-fd6c342fcf60","Exchange":"BTC-TRIG","Type":"LIMIT_SELL","Quantity":2.88676658,"QuantityRemaining":2.88676658,"Limit":0.00042551,"Reserved":2.88676658,"ReserveRemaining":2.88676658,"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000000,"Price":0.00000000,"PricePerUnit":null,"Opened":"2018-01-02T21:15:10.107","Closed":"2018-01-02T21:15:10.183","IsOpen":false,"Sentinel":"46c3c959-b171-465e-9447-24367adb12f2","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:27 INFO ProfitTrailerService - Sell order for BTC-TRIG sold amount 2.886767 for price 0.000424 -- {"OrderId":"8fece2f2-ce5b-419a-bead-cc83b06f5d2c","MarketName":"BTC-TRIG","MarketCurrency":"TRIG","BuyOrSell":"Sell","OrderType":"LIMIT","Quantity":2.88676658,"Rate":0.00042434}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:32 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"8fece2f2-ce5b-419a-bead-cc83b06f5d2c","Exchange":"BTC-TRIG","Type":"LIMIT_SELL","Quantity":2.88676658,"QuantityRemaining":2.88676658,"Limit":0.00042434,"Reserved":2.88676658,"ReserveRemaining":2.88676658,"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000000,"Price":0.00000000,"PricePerUnit":null,"Opened":"2018-01-02T21:15:28.577","Closed":"2018-01-02T21:15:28.7","IsOpen":false,"Sentinel":"4dc6d8f1-b6e5-4327-b854-d1791b5c954e","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:38 INFO ProfitTrailerService - Sell order for BTC-TRIG sold amount 2.886767 for price 0.000424 -- {"OrderId":"c3b96f4f-eaeb-4a61-832d-5a3ee235b19e","MarketName":"BTC-TRIG","MarketCurrency":"TRIG","BuyOrSell":"Sell","OrderType":"LIMIT","Quantity":2.88676658,"Rate":0.00042434}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:43 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"c3b96f4f-eaeb-4a61-832d-5a3ee235b19e","Exchange":"BTC-TRIG","Type":"LIMIT_SELL","Quantity":2.88676658,"QuantityRemaining":2.88676658,"Limit":0.00042434,"Reserved":2.88676658,"ReserveRemaining":2.88676658,"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000000,"Price":0.00000000,"PricePerUnit":null,"Opened":"2018-01-02T21:15:40.28","Closed":"2018-01-02T21:15:40.327","IsOpen":false,"Sentinel":"56f2d7ae-f512-4c83-b2c7-0ac82ffb64d1","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:54 INFO ProfitTrailerService - Sell order for BTC-TRIG sold amount 2.886767 for price 0.000423 -- {"OrderId":"66ffbbe2-63c2-43ab-9b45-58962a997435","MarketName":"BTC-TRIG","MarketCurrency":"TRIG","BuyOrSell":"Sell","OrderType":"LIMIT","Quantity":2.88676658,"Rate":0.00042301}
1|PT_Bittr | 2018-01-02 21:15 +00:00: 2018-01-02 21:15:59 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"66ffbbe2-63c2-43ab-9b45-58962a997435","Exchange":"BTC-TRIG","Type":"LIMIT_SELL","Quantity":2.88676658,"QuantityRemaining":0.00000000,"Limit":0.00042301,"Reserved":2.88676658,"ReserveRemaining":2.88676658,"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000305,"Price":0.00122113,"PricePerUnit":0.00042300000000000000,"Opened":"2018-01-02T21:15:55.653","Closed":"2018-01-02T21:15:55.81","IsOpen":false,"Sentinel":"36cfce19-1687-4c54-ba45-31f7dec8bd38","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}

**Comment by taniman** [comment]
This is not an issue.

Sell orders are by default immediate or cancel. So the bot will try to sell. But if there is not enough coins to cpmplete the order. It will be canceled and the bot wil ltry again.
