### ISSUE TITLE
[BUG] ALL_max_cost_percentage uses TPV not TCV

### ISSUE THREAD

**Issue by wiseold** [taniman/profit-trailer#545]
ALL_max_cost_percentage is currently being calculated on TPV not TCV as per the wiki

**Comment by taniman** [comment]
Than I will change the wiki

**Comment by wiseold** [comment]
I beg to differ. My current TCV is 1.219. Current TPV is 1.449. My min buy balance is 50%. Buy cost 1.5%
most recent line from my log
Buy will exceed min buy balance 0.72453091. BAL: 0.37829917 - MC: 0.0183

**Comment by taniman** [comment]
I am not seeing this comment, did you delete it?

1.5% of TCV (1.219) = 0,0183

So max_cost is indeed based on TCV

**Comment by wiseold** [comment]
Apologies I am an idiot - was getting confused between min cost and min balance - sorry for the trouble
