### ISSUE TITLE
Customize Telegram messages

### ISSUE THREAD

**Issue by lars974** [taniman/profit-trailer#546]
Hi there, 

It would be great to define more precisely in the application.properties the kind of messages we'd like to receive.

For example : 
telegram.postBuyOrders = true
telegram.postSellOrders = true
telegram.postDailyGain = true (for example every hour)

**Comment by clownfish44** [comment]
I would also like to see this and also have a notification when something buys more on dca.

**Comment by minerdude** [comment]
I suggest a notification when min trade requeriment not met

**Comment by LoneWolfProductions** [comment]
I would also suggest to send a heartbeat every no and then (maybe let us set the time) so we know the bot is running, and nothing happend to it.

**Comment by taniman** [comment]
@LoneWolfProductions  If the bot is not running you will get a Telegram notification. That is already implemented.

@minerdude  this will not be implemented

**Comment by LoneWolfProductions** [comment]
@taniman if this is true then i dont get those messages

**Comment by Stoley** [comment]
Yes I'd like to customize Telegram, at the moment I'm not getting any pop-up notifications from the bot on Desktop, since it doesn't have an @mention, kinda useless.

**Comment by taniman** [comment]
@LoneWolfProductions Maybe I said that wrong. The process is running. But the bot is stuck. And so will send a message

**Comment by LoneWolfProductions** [comment]
@taniman ah ok makes more sense now :p

**Comment by lars974** [comment]
Moreover it'd be awesome to get not only the percentage profit of the trade compared to the bought price (calculated with (sell value - bought value) * 100 / bought value)) but also the percentage profit of the trade compared to the TCV (calculated with ((TCV +trade profit) * 100 / TCV)

Indeed actually the profit written in the Telegram message is not an accurate indicator to realize the profit we made. A small profit percentage coming from a deep DCA can earn much more than a big percentage from a pairs trade).

This could be for example written this way : 

ProfitTrailer BITTREX
Just sold: BTC-XXX
Sell strat: GAIN
Cost: 0,01284507 (3)
Rate: 0,00000342
Trade Profit: 2,20%
Profit BTC : 0,00027380
TCV Profit : 0.03%

**Comment by Mikeeetrue** [comment]
Would also be nice to show the current TPV in USD (like the Current Balance in bank sms)

**Comment by RunPlz** [comment]
Can we add a Telegram notification for DCA purchases?
I would like to keep track of these as well.

**Comment by RunPlz** [comment]
Adding DCA purchase notifications would be great!

**Comment by jodee8** [comment]
"telegram.disableSilentMode = true"

**Comment by frydrce** [comment]
I think it would be great if I could set an above or below price for a coin and when target price is reach get a telegram message.

**Comment by JaySNL** [comment]
What about the ability to show the target that's been set, when pushing the buy notification, i.e:
EXCHANGE BTC
Just bought: XXXBTC
Cost: 0,00249041
Rate: 0,00220390
Target: xxx
