### ISSUE TITLE
Nonce Error - Polo

### ISSUE THREAD

**Issue by wolfman77** [taniman/profit-trailer#550]
Since yesterday night I constantly get this:

2018-01-03 11:45:11 ERROR Application - Please fix: trading_apiKey -- nonce error: {"error":"Nonce must be greater than 151388396329900000. You provided 15149763110530000."}

Bot doesn´t trade, just stops after this message.

Also, it doesn´t show actual balances, and still open trades are completely missing.

I completeley replaced all files, re-installed java, with multiple restarts of my PC. Nothing helps. I also replaced the tradingAPI, to no avail.

Please investigate.

**Comment by taniman** [comment]
Hello there is nothing to investigate.

You should create 2 new api keys for PT and not use them with any other bots
