### ISSUE TITLE
FAQ page in the wiki - Temporary manual override

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#555]
I don't understand this part in the FAQ page of the wiki (the last line):
"Temporary manual override
http://localhost:8081/settings/sellOnlyMode?type=&enabled=false
Be sure to change the port (8081) to the port you are using on your bot.
This disables global sell only mode, but it will reactivate on next buy attempt if price is still below/above your trigger"

- why is reactivating SOM on the next buy attempt based on price? And it says "if price is still below/above your trigger". Which trigger is that and is it above or below? I thought sell only mode doesn't depend on my buy prices, it only depends on BTC price fluctuations if it jumps suddenly too high or low

Thanks,
Steven

**Comment by taniman** [comment]
"if price is still below/above your trigger", with price we mean indeed the change % for BTC.

**Comment by nstefi** [comment]
So if it disables global sell only mode, it means it should allow to buy too, not sell only, right? But if at the next buy attempt it reactivates, it means it cannot buy, so it means the override didn't have any effect (not working). Or is it because if a trigger activates the SOM, the get the bot out of SOM, it would need another "recover" trigger? And with this temporary override we can get it out from SOM even before the release trigger occurs? So if the price is not below/above my activation trigger, but it didn't reach the recover trigger yet, normally the bot would be still in SOM, and buy doing the override we can take it out from that mode and it can buy?
