### ISSUE TITLE
prevent buying a COIN that already has 70% profit !!!

### ISSUE THREAD

**Issue by albator5151** [taniman/profit-trailer#556]
hello and thank you for your work,

it is urgent to add the possibility of excluding the COINS who made a huge profit these last 24 hours

profit trailer sometimes buys a COIN with 75% progression, suddenly this COIN undergoes a correction, which is logical about 20%, and we remain stuck with this unsaleable pair several days

this option is urgent because sometimes we find it to buy at the most expensive, at the very beginning of a big dump

thank you

**Comment by lutzleonhardt** [comment]
+1
Very important. Today it happened for me with ADABTC! -20%

**Comment by lutzleonhardt** [comment]
Is there a way to workaround it! I am using emaspread buy. Thx

**Comment by albator5151** [comment]
no unfortunately there is no parade, profit trailer is almost perfect, but this problem can be wasting time or even money quickly

**Comment by lutzleonhardt** [comment]
Thanks. But is there some kind of workaround for that problem?

**Comment by albator5151** [comment]
yes i think the trailer profit developer can do something but they have to worry about it
