### ISSUE TITLE
Can't do EMACROSS buys at any period

### ISSUE THREAD

**Issue by ricardodacosta** [taniman/profit-trailer#557]
I have a feeling EMACROSS is not working since I cant get an order in no matter how I tweek it.

On the monitor I can see all 140 Possible Buy coins listed on the log but none of them show EMACROSS (true) even when they have just crossed. 

Any help will be greatly appreciated.

My Indicator:

EMA_period = 300 (my ideal period is 3600 but that didn't work so I thought the problem was long scale periods but even with 300 didnt work)
EMA_1 = 50
EMA_2 = 10
EMA_cross_candles = 1

My Pairs:

ALL_trading_enabled = true
ALL_enabled_pairs = ALL
ALL_max_cost = 0
ALL_max_cost_percentage = 20
ALL_min_buy_balance = 0.24
ALL_min_buy_volume = 10
ALL_min_buy_price = 0.00000100
ALL_max_trading_pairs = 5
ALL_max_buy_spread = 1
ALL_buy_strategy = EMACROSS
ALL_buy_value = 1
#ALL_trailing_buy = 0
ALL_sell_strategy = GAIN
ALL_sell_value = 4.8
ALL_min_profit = 3
ALL_trailing_profit = 2.2
All_stop_loss_trigger = 0
ALL_stop_loss_timeout = 0
ALL_panic_sell_enabled = false
ALL_DCA_enabled = false
ALL_sell_only_mode = false
ALL_btc_price_drop_trigger = 0
ALL_btc_price_drop_recover_trigger = 0
ALL_btc_price_rise_trigger = 0
ALL_btc_price_rise_recover_trigger = 0
ALL_consecutive_buy_trigger = 0
ALL_consecutive_sell_trigger = 0
ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0

Configuration:

#sell options
sell_fillOrKill = false
sell_immediateOrCancel = true
#buy options
buy_fillOrKill = false
buy_immediateOrCancel = true
BTC_dust = 0.00105
testMode = false

**Comment by aaronssu** [comment]
I have had similar issues recently when testing EMACROSS.  Finally once showed as True briefly but I still don’t think it is working right.

**Comment by taniman** [comment]
with emacross candles of 1 it would be really difficult to get buys locked
especially is you have a buyvalue of 1% or more. Tha'ts just something that does not happen that much.

lower your buy_value to like 0.01 or increase cross candles.

FYI I have been runiing EMACROSS for some weeks now. No problem
