### ISSUE TITLE
binance eth crashing but binance btc isn't

### ISSUE THREAD

**Issue by github-4me** [taniman/profit-trailer#558]
Binance is down for maintenance and noticed that my windows bot hasn't crashed but my linux vps (westhost ubuntu 16.04) has crashed multiple times.  
See logs here https://pastebin.com/JLWNJ9kW
In the logs, PT tries restarting but last log shows that it is already started. Find that odd.

I can understand PT crashing because binance is down but I expect windows to crash as well or linux to handle problem like windows.  This is the 4th time today I have had to start linux PT.

It would be nice if PT could show API status lights for each exchange so we can tell if something is wrong with exchanges.

thanks

**Comment by taniman** [comment]
You should not use server.rebootOnFailur is it a beta feature that proved to not work correctly
