### ISSUE TITLE
Fix consecutive buys on binance

### ISSUE THREAD

**Issue by Jonconnect** [taniman/profit-trailer#559]
Hi, it's dam, no btc,eth drop protection,and no consecutive buy trigger on binance.
No protection,

**Comment by taniman** [comment]
consecutive is not possible on binance, unless.... let me think about it

**Comment by chrismpalmer** [comment]
What does consecutive buys mean? I have a problem with my orders getting through quick enough... then retry is too long it leaves a lot of bags. Is this what you mean?
