### ISSUE TITLE
Possible Buy Log is at 0

### ISSUE THREAD

**Issue by CryptocPT** [taniman/profit-trailer#560]

**Comment by lutzleonhardt** [comment]
same here; without any log entries

**Comment by lutzleonhardt** [comment]
![image](https://user-images.githubusercontent.com/11898898/34551987-baef512e-f11e-11e7-9ca5-7fcc293f4804.png)

**Comment by lutzleonhardt** [comment]
using latest version

**Comment by taniman** [comment]
https://wiki.profittrailer.io/doku.php/faq#why_is_my_possible_buy_log_empty
