### ISSUE TITLE
[Partially SOLVED] ERROR Util - Error reading file null

### ISSUE THREAD

**Issue by bredanaar** [taniman/profit-trailer#561]
![image](https://user-images.githubusercontent.com/35095979/34556404-6c56bcf6-f136-11e7-87b8-23a23ccebe33.png)

The cmd file display's this error right after starting up. (I hid part of the filepath) 
After pressing any key the program just closes itself. 

This is the cmd file in notepad: 
[ProfitTrailer cmd file.txt](https://github.com/taniman/profit-trailer/files/1602870/ProfitTrailer.cmd.file.txt)

As you can see the pause line does not belong there..

**Comment by Meandmymonkey2** [comment]
I have had the same issue on Pi this morning........PT not working as a result. When I open the Tail log I get the same error message  2018-01-04 09:21:03 ERROR Util - Error reading file null

**Comment by bredanaar** [comment]
I have fixed the problem, although I do not recommend it if you have a large log history.
What I did was: I replaced every file in the folder with the original PT file, turns out the ProfitTrailerData.json file had been corrupted or something. So I left everything as-is and only replaced the .json file with the original. Now the program runs just fine, but the sell history in the monitor unfortunately got reset. 

Hope someone here finds a solution on how to retrieve my sell history..

**Comment by Meandmymonkey2** [comment]
AH thanks bredanaar.  Great that saves me reinstalling the whole thing on Pi. If I just delete the ProfitTrailerData.json and backup (as they are both at 0kb) it then creates the files if they are missing and starts from afresh as you say. Lost my sales history but at least I wont have to re-install. Thanks!

**Comment by Meandmymonkey2** [comment]
Ps - I think what caused the corruption was the power cut off from my Pi....hence in my case it was probably writing to the file or something when that happened rather than a PT error.

**Comment by bredanaar** [comment]
I think that's exactly what happened to me! The last thing I did was closing my laptop. 
Do you know how to contact the devs to report this issue? (besides this thread)

**Comment by taniman** [comment]
This cannot be fixed. A corrupted file is a corrupted file. I can only try improving the backup logic.
