### ISSUE TITLE
[Feature Request] COINPAIR_DCA_reset_count = #

### ISSUE THREAD

**Issue by Fogazi** [taniman/profit-trailer#562]
Along with the ability to set bought prices for when PT loses them due to corrupted profittrailerdata.json or other reasons. It would be good to have the ability to also reset the DCA counter when resetting the bought/average price.

**Comment by johnalindogan** [comment]
recently ive been doing manual buys. for some reason PT thinks its another DCA even if there was already a previous sell. would be great to have this manual DCA count reset functionality

**Comment by YoJeff** [comment]
Implemented in v2.0 hotconfig.
