### ISSUE TITLE
[Feature Request] Improved "Please increase max_cost!" feedback

### ISSUE THREAD

**Issue by kennethkalmer** [taniman/profit-trailer#563]
It would be great if the `Cannot buy XXXXXX. Please increase max_cost!` message could indicate by how much it should be raised, or at what cost the bot wanted to place the order.

I've been trying to look at the pairs in the Binance interface to reverse engineer this, but have come up empty handed. I couldn't find any reason the bot couldn't place these orders (yet).

**Comment by kennethkalmer** [comment]
OK, I just figured out that by looking in the price in the _Possible Buy Log_ I could see the amount, at least for one pair I just spotted in the log file.

Maybe the _Possible Buy Log_ could visually indicate that the bot can't afford to place the order even though other parameters make it match.

**Comment by minerdude** [comment]
and send a notification to telegram bot when this happens

**Comment by YoJeff** [comment]
Exchanges set the limits, and sometimes change these limits without any prior notification.   

The wiki is updated as information is available.
https://wiki.profittrailer.io/doku.php/exchanges

Further, the API does not tell you how much you are short -- just that you are short.
