### ISSUE TITLE
GUI Issue

### ISSUE THREAD

**Issue by samirsayz** [taniman/profit-trailer#564]
Dear Taniman,

I am confused regarding something with my GUI. I just recently purchased my license a couple days back. Since then I've been working on my configuration and getting acquainted with the software. 

I saw that you recently released v.1.2.6.8 "Bug Fix" which I wanted to update with my software. What I did was, I copied the the "ProfitTrailer.jar" file from your release to the destination folder where my software is and replaced the same file in the respective folder. After restarting the bot, I still do not see the Config section within the GUI. What could be the reason for this?

Please help with this.

Warm Regards,
Sameer Saluja

**Comment by kennethkalmer** [comment]
@samirsayz do you have the following in your `application.properties` file:

```
server.password = something
server.enableConfig = true
```

If not, add it and restart the bot.

**Comment by samirsayz** [comment]
@kennethkalmer thanks a lot! That worked perfectly!

**Comment by kennethkalmer** [comment]
@samirsayz my pleasure! Mind closing this issue for us?
