### ISSUE TITLE
[REQUEST] Hot Config for Occasionally lost sales recods

### ISSUE THREAD

**Issue by Bbrandwin** [taniman/profit-trailer#565]
Sometimes Bittrex spits out invalid sales data. When it does, that particular sale fails to be recorded in the sales log.This has happened to me multiple times. Can you guys add something to the Hot Config options that will allow us to retrieve the sales info and have it recognized by PT. If that process is too complicated then alternatively, we could input a full manual sales info in Hot Config based on what we see in the Bittrex order history.

**Comment by LuckyJay402** [comment]
I am running with Poloniex and have found some sales missing from the log as well.  Looking into the logs, it appears that sometimes the quantity gets off between PT and Poloniex and the sale goes through, but with an error back from Poloniex about not enough available and it misses the sales log.

**Comment by Bbrandwin** [comment]
Exactly

**Comment by Bbrandwin** [comment]
So I've realized that this occurs when the sale is completed in more than one part. Initially the sale is partially filled so PT gets confused about what happened. It would be nice if when PT issues a sale order, that it performs some basic error checking when it receives invalid data. For example, has the number of pairs decreased and have the number of sales increased? If the # pairs went down and the sales stayed the same then PT should check your order history to see what happened and calculate the sale price. 

Also If the the number of pairs is the same then has the volume you own decreased? (meaning a partial sale). Again, there should be a quick check and data retrieval for this.

**Comment by helo03** [comment]
Sorry LuckyJay402, that was not on purpose. Can you please add your comment again?
