### ISSUE TITLE
Getting Started with Trading

### ISSUE THREAD

**Issue by samirsayz** [taniman/profit-trailer#566]
Hey Guys,

I now have everything in place with the configuration settings and all initial things setup. I now wanted to get started with trading. I have no money in my Bittrex account. When looking at my GUI, I see that there are no data values, nor any coins that are being watched/trailed. 

Is there a possible simulation mode in which I can do testing? If so, how do start testing? Do I have to put money into my Bittrex account and start trading to get any sort of data values?

Please advise! 
Thanks

**Comment by Q-Rush** [comment]
https://wiki.profittrailer.io/doku.php/configuration.properties

You can change testMode to true. But you can not simulate Balance as far as i know. it can only work with real balance and just writes the buy and sells in the console. so you would either need to manually write down the statistics or write a script to parse the results.
