### ISSUE TITLE
REQUEST - Desktop Browser Fields vs. Mobile Browser Fields

### ISSUE THREAD

**Issue by tmoffett** [taniman/profit-trailer#567]
The "Total Amount" column doesn't seem to be available on my mobile browser even if it's opened using the "desktop version" option in Chrome-Android.

**Comment by Fogazi** [comment]
there is a little '+' on the left of the pairs/dca log, tap it and it has all that info there.

**Comment by taniman** [comment]
Which log do you mean? I am seeing it just fine @tmoffett

**Comment by tmoffett** [comment]
Thanks Fogazi, I didn't know what was there.
