### ISSUE TITLE
FEATURE REQUEST - Historical Simulation Model

### ISSUE THREAD

**Issue by mikobeaudry** [taniman/profit-trailer#568]
It would be awesome if there was a way to run simulations on historical data, utilizing various PAIRS, DCA, and INDICATORS settings. This would allow you to test different settings and see how they would've performed given the historical market data. For example, one could look at a time period during which BTC was pumping and alts were dropping, run different simulations and, theoretically, build a template of settings for a similar future market trend.

**Comment by coaxx77** [comment]
This wouldt be awsome
