### ISSUE TITLE
MalformedJsonException error log

### ISSUE THREAD

**Issue by Gitulu** [taniman/profit-trailer#570]
Hello guys,

sometimes (today twice) I got on binance the following error message: 

Error:
"2018-01-04 21:01:08 ERROR ProfitTrailerService - Handled exception com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $"

[log.txt](https://github.com/taniman/profit-trailer/files/1604605/log.txt)

Attached you will see my logfile.
Why I get this error and how can we fix this?

Settings:
Binance with 2 API keys as recommended
Version: 1.2.6.8
2 instances on the same rig but with different ports etc (works well)
newest Java and Windows 10 64 - 1703

Thank you
Gitulu

**Comment by taniman** [comment]
Looks like binance is having hiccups.  Will look into it tonight if it continues

**Comment by JonnyClean** [comment]
I am seeing the same. I have two bots on Binance, one running BTC and one in USDT. Thanks for looking into it!

**Comment by c7oud** [comment]
Having this issue now as well. Could you somehow fix it / @taniman could you solve this issue?
