### ISSUE TITLE
[Feature request] Hold some crypto

### ISSUE THREAD

**Issue by lars974** [taniman/profit-trailer#573]
That'd be awesome to be able to easily hold some crypto on a exchange.

Let's take an example : I'm on Bittrex, with MARKET = BTC.
On this exchange I've some crypto I don't want to trade (for example ADA and XLM).

We could implement a feature like
ALL_hold_enabled = ADA, XLM
or
ADA_hold_enabled = true
XLM_hold_enabled = true

meaning that
- the bot doesn't trade these crypto
- the ADA and XLM amounts are NOT taken in account in the BAL, TCV and TPV values.
This could help hold cryptos AND keep good ratios or stats for variables like ALL_max_cost, ALL_min_balance_percentage etc.

What do you think of it ?

**Comment by taniman** [comment]
See #496
