### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by sorentorp** [taniman/profit-trailer#574]
Hi

It would be nice to have a Discord bot, just lige the telegram bot already implemented!

Mostly for Sale and Profit % monitoring.

**Comment by LiamAird** [comment]
Makes sense, as the entire profit trailer chat also moves to discord for ease of use :)

**Comment by sorentorp** [comment]
I think this should be revisited..

**Comment by louisswart** [comment]
Please do not remove the Telegram messaging.
