### ISSUE TITLE
[BUG] MIN_NOTIONAL ERROR

### ISSUE THREAD

**Issue by yuvalbar84** [taniman/profit-trailer#576]
Binance probably updated their min buy/sell to 0.002. 
Even though I updated the ALL_max_cost to 0.002, the error persist.
Let's say we bought X ETH for 0.002 BTC,
ETH price went down in the DCA program, and hits the first trigger.
DCA would like to buy now another X ETH but this time the price is 0.0018 - boom. it can't buy with this price. minimum is 0.002 now.
There's no configuration in the bot which allows to set minimum cost to buy in DCA

**Comment by taniman** [comment]
there is a configuration to set the correct dust value. So change the dust value for binance in configuration.properties 

BTC_dust = 0.00205
and use ALL_max_cost of 0.0022 to buy recommended
