### ISSUE TITLE
Error: Unable to access

### ISSUE THREAD

**Issue by bernhard82** [taniman/profit-trailer#577]
Hi I am new to CMD and Profil Trailer. I am trying to run the .jar file and get this error 
"Error: Unable to access jarfile ProfitTrailer.jar"

I have tried to "CD" to the correct directory as per previous issues on this site but there were no solutions and the issues were closed. I have terrible checked my API keys and also the Java V 8 

What else may I have missed

**Comment by taniman** [comment]
This is not an issue so it does not belong here. 

We have a support channel and resellers that can help with setup problem.
and it's 'cd' without caps

**Comment by bernhard82** [comment]
Thank you 

Thanks again
John Duenzl 😀

**Comment by proglo** [comment]
where is the support channel?
