### ISSUE TITLE
[REQ] Mined coins default price

### ISSUE THREAD

**Issue by Brisco00** [taniman/profit-trailer#581]
I use Bittrex as the destination for my mined coins, when the coins are deposited could we make a setting to have PT use the last traded price as the "purchase" price?  Currently we have to go to the hotconfig and set a purchase price.

i.e.
MINED_COINS = BTC-ETH, BTC-DCR, BTC-SC
MINED_COINS_USE_LAST_TRADED_PRICE = true

**Comment by YoJeff** [comment]
I don't really see this as a concern of PT.   

What if your mining deposits are very small, and frequent?   Should PT keep a rolling average of hundreds of datapoints?   Is today's spot price an accurate representation of cost?
