### ISSUE TITLE
Simple ustd-btc bot

### ISSUE THREAD

**Issue by Scoby1knoby** [taniman/profit-trailer#582]
Bot is connecting but getting 
Exchange spitting out invalid data.... does this mean not enough $ in the ustd acct on bittrex?

**Comment by Scoby1knoby** [comment]
Do i need to connect on 2 new seperate API keys?

Or just 1 as it is now

**Comment by taniman** [comment]
This is not the place for setup problems. Please contact support in our telegram channel or send an email to support profittrailer.com
