### ISSUE TITLE
Enable SOM or Disable Buy Orders for Markets which will be de-listed on Bittrex

### ISSUE THREAD

**Issue by hyperuk** [taniman/profit-trailer#587]
Hi All,
Just noticed, my PT instance purchased 2x coins which were announced by Bittrex to be de-listed.
Metal (MTL)
TRIG Token (TRIG)

This can be a feature we can adopt for all the other exchanges to minimize the potential losses.

**Comment by hyperuk** [comment]
It appears Bittrex do announce these in their support forums. https://support.bittrex.com/hc/en-us/sections/200560334-Coin-Removals

The high level logic will be to enable the PT Clients to daily query a central service managed by the PT Dev team and get a list of high risk markets per exchange, so the clients can exclude the tokens from being purchased. Hope this helps.

Thanks.

**Comment by taniman** [comment]
see #395
