### ISSUE TITLE
MIN_NOTIONAL errors persist even after using recommended settings (BTC)

### ISSUE THREAD

**Issue by grandmore** [taniman/profit-trailer#588]
I have added all the suggestions from PTAnnouce but I still get a flood of the MIN_NOTIONAL errors.

Added ALL_max_cost and disabled ALL_max_cost_percentage for the moment so that the cost is not too small because its a percentage fo the balance.
(added) ALL_max_cost = 0.0025
(disabled) ALL_max_cost_percentage = 8

Added Dust settings to configuration.
BTC_dust = 0.00205
ETH_dust = 0.0105
BNB_dust = 0.0105
USDT_dust = 1.05

Added every XXXXXX_min_buy_price from Binance from their list to
ETHBTC_min_buy_price = 0.000001
LTCBTC_min_buy_price = 0.000001
BNBBTC_min_buy_price = 0.00000001
... etc etc

I'am streaming the error log from stdout to Papertrails to make it easier I can grant you access and you can see all of them yourself.

There is ample balance (0.04231724BTC)

Here are some hilights:

MIN_NOTIONAL log
Jan 06 13:29:43 4f3aef37341a pt_app_1: 2018-01-06 13:29:43 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:
Jan 06 13:30:00 bc331948866e pt_app_1: 2018-01-06 13:30:00 INFO ProfitTrailerService - SOM is active for CTRBTC. -- Manually set in PAIRS.properties
Jan 06 13:30:05 4f3aef37341a pt_app_1: 2018-01-06 13:30:05 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:
Jan 06 13:30:58 4f3aef37341a pt_app_1: 2018-01-06 13:30:58 INFO DCAStrategyRunner - There is not enough volume to make a successfull DCA ETCBTC
Jan 06 13:31:02 bc331948866e pt_app_1: 2018-01-06 13:31:02 INFO NormalStrategyRunner - There is not enough volume to buy POEBTC
Jan 06 13:31:07 4f3aef37341a pt_app_1: 2018-01-06 13:31:07 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:
Jan 06 13:32:16 bc331948866e pt_app_1: 2018-01-06 13:32:16 INFO ProfitTrailerService - SOM is active for LSKBTC. -- Manually set in PAIRS.properties
Jan 06 13:32:33 bc331948866e pt_app_1: 2018-01-06 13:32:33 INFO ProfitTrailerService - SOM is active for POEBTC. -- Manually set in PAIRS.properties
Jan 06 13:32:54 4f3aef37341a pt_app_1: 2018-01-06 13:32:54 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:
Jan 06 13:33:03 bc331948866e pt_app_1: 2018-01-06 13:33:03 INFO Util - Detected configuration changes
Jan 06 13:33:16 4f3aef37341a pt_app_1: 2018-01-06 13:33:16 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:

ERROR: -2010, Account has insufficient balance for requested action.
Jan 06 03:27:27 bc331948866e pt_app_1: 2018-01-06 03:27:27 INFO ProfitTrailerService - Sell order for XVGBTC sold amount 423.000000 for price 0.000010 -- {"symbol":"XVGBTC","orderId":10254287,"clientOrderId":"dDBNcGiMTk1gA8Zl1ZsDY0","transactTime":1515209247308,"price":"0.00001015","origQty":"423.00000000","executedQty":"0.00000000","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
Jan 06 03:27:32 bc331948866e pt_app_1: 2018-01-06 03:27:32 INFO ProfitTrailerService - Get order information -- {"symbol":"XVGBTC","orderId":10254287,"clientOrderId":"dDBNcGiMTk1gA8Zl1ZsDY0","price":0.00001015,"origQty":423.00000000,"executedQty":0E-8,"status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1515209247308}
Jan 06 03:27:41 bc331948866e pt_app_1: 2018-01-06 03:27:41 INFO ProfitTrailerService - Sell order for XVGBTC sold amount 423.000000 for price 0.000010 -- {"symbol":"XVGBTC","orderId":10254376,"clientOrderId":"UuYvitxBknKTRkMDnNdkFl","transactTime":1515209261090,"price":"0.00001015","origQty":"423.00000000","executedQty":"423.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:768) ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke() ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: 2018-01-06 03:27:42 ERROR GainStrategyRunner - An error occured
Jan 06 03:27:42 4f3aef37341a pt_app_1: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$6d0894d2.sellOrder() ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: nl.komtek.pt.utils.PTHandledErrorException: ERROR: -2010, Account has insufficient balance for requested action.
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:859) ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$20(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
Jan 06 03:27:42 4f3aef37341a pt_app_1: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Jan 06 03:27:46 bc331948866e pt_app_1: 2018-01-06 03:27:46 INFO ProfitTrailerService - Get order information -- {"symbol":"XVGBTC","orderId":10254376,"clientOrderId":"UuYvitxBknKTRkMDnNdkFl","price":0.00001015,"origQty":423.00000000,"executedQty":423.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1515209261090}
Jan 06 03:27:48 bc331948866e pt_app_1: 2018-01-06 03:27:47 INFO TelegramService - We got a response Not Found
Jan 06 03:27:49 4f3aef37341a pt_app_1: 2018-01-06 03:27:49 ERROR GainStrategyRunner - An error occured
Jan 06 03:27:49 4f3aef37341a pt_app_1: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
Jan 06 03:27:49 4f3aef37341a pt_app_1: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
Jan 06 03:27:49 4f3aef37341a pt_app_1: at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$6d0894d2.sellOrder() ~[classes!/:1.2.6.8]
Jan 06 03:27:49 4f3aef37341a pt_app_1: at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.8]
Jan 06 03:27:49 4f3aef37341a pt_app_1: at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.8]
Jan 06 03:27:49 4f3aef37341a pt_app_1: at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
Jan 06 03:27:49 4f3aef37341a pt_app_1: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
Jan 06 03:27:49 4f3aef37341a pt_app_1: nl.komtek.pt.utils.PTHandledErrorException: ERROR: -2010, Account has insufficient balance for requested action.

**Comment by taniman** [comment]
contact me on telegram @elroy
