### ISSUE TITLE
Error on startup: An Illegal reflective access operation has occured

### ISSUE THREAD

**Issue by MattWellman** [taniman/profit-trailer#589]
![image](https://user-images.githubusercontent.com/5161716/34644894-dc8b75ce-f30d-11e7-976b-7f8e4a70a986.png)

**Comment by MattWellman** [comment]
![image](https://user-images.githubusercontent.com/5161716/34644893-d41f4992-f30d-11e7-814f-8c2106e9b2dd.png)

**Comment by taniman** [comment]
Please read the compelte message. It says right at the end. Please install java 8
