### ISSUE TITLE
Binance - Issues purchasing coins

### ISSUE THREAD

**Issue by damajicman3** [taniman/profit-trailer#591]
everytime PT attempts to purchase a coin this error comes up...

2018-01-06 21:53:22 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:

please advise me as to what to do.

**Comment by LordZive** [comment]
I have the same issue. Log is completely filled. It started at: 2018-01-05 07:10:15 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL

**Comment by damajicman3** [comment]
Binance: ERROR: -1003, Way too many requests
Full error message:

ERROR AllScheduledTasks - 
nl.komtek.pt.utils.PTHandledErrorException: 
ERROR: -1003, Way too many requests; 
IP banned until 1512488458967.


hope this helps. im still working on adjusting my properties now.

**Comment by damajicman3** [comment]
sorry. the answer is 

ERROR: -1013, Filter failure: MIN_NOTIONAL
Your trading with too little funds. You need to increase your ALL_max_cost, or increase your ALL_max_cost_percentage.

increase your max cost per coin. so i recommend change your COST in the pairs file. change it to atleast the minimum values below or higher.

ALL_max_cost = 0.0012
Valid Values: Decimal value greater or equal to 0. 
The amount in the current base currency (BTC, ETH, or USDT) we will use to buy a pair. This amount is used for EACH purchase. If this amount is not available, the bot will not buy.

MINIMUM VALUES: The minimum ALL_max_cost for each exchange is shown below:

Binance: 
BTC = 0.0022 
ETH = 0.025 
BNB = 1 
USDT = 1

Bittrex: 
BTC = 0.0011 
ETH = 0.00075 
USDT = 3.75

Poloniex: 
BTC = 0.0011 
ETH = 0.0075 
XMR = 0.00025 
USDT = 1.25

COIN-PAIR ENABLED: This setting works with single coins. See here for more info.

**Comment by PeyoHristov** [comment]
i increase  all max cost ... and still get error 1013 ? min national ... idk that is last 3 days i loose pations.... and why binance icrease cost? Bittrex and poloniex dont ?!

**Comment by LordZive** [comment]
Yeah me too, it's not a max cost problem. I'm trading with 6 precent per buy on my budget and my budget is high enough.

**Comment by YoJeff** [comment]
[https://wiki.profittrailer.io/doku.php/common_errors#error1013_filter_failuremin_notional](https://wiki.profittrailer.io/doku.php/common_errors#error1013_filter_failuremin_notional)

**Comment by LordZive** [comment]
I solved it on my bot. Problem was nog it trying to buy with to low max cost. There was an open trade under BTC = 0.0022 which should have been moved to dust log, but it wasn't. So PT tried to sell it all the time for under 0.0022 BTC. I think this is a setting issue (or bug) in PT. I manually sold the pair and the problem was solved.
