### ISSUE TITLE
[REQUEST] Show USD currentvalue next to each pair and DCA bags

### ISSUE THREAD

**Issue by gittygoo** [taniman/profit-trailer#593]
Show USD currentvalue next to each pair and DCA bags so we know how big each bag is at themoment in FIAT

**Comment by djcrypto75** [comment]
You want it next to the values under, or I misunderstand something? :)
**PAIRS LOG.**
Current Price
Bought Price
Current Value
Bought Cost
**DCA LOG**
Current Price
Average Price
Current Value
Total Cost

**Comment by djcrypto75** [comment]
Will add on some of them, on roadmap
