### ISSUE TITLE
[BUG] sell_only_mode in combination with disabled DCA creates pending sale order

### ISSUE THREAD

**Issue by mkarulin** [taniman/profit-trailer#594]
The following config causes a pending sale order for the pair at 1.5% profit without any trailing.

ALL_sell_strategy = GAIN
AIONBTC_trading_enabled = true
AIONBTC_trailing_profit = 0.77
AIONBTC_DCA_enabled = 0
AIONBTC_sell_value = 1.5
AIONBTC_sell_only_mode = true

**Comment by magyosha** [comment]
up..
this has happend to me also

**Comment by steveoneal** [comment]
I've got something similar happening.   My coin that it's happening to does not have SOM enabled, however it does have DCA disabled.  Maybe that's the connection.
