### ISSUE TITLE
[REQUEST] Roll log files daily

### ISSUE THREAD

**Issue by ba32107** [taniman/profit-trailer#597]
Could you implement a simple configurable feature that would enable log file rolling? Bascially, log entries for each day should end up in their own log files.

**Comment by hheexx** [comment]
Log files are small, not sure it should be priority

**Comment by ba32107** [comment]
Agreed, should be low priority.

**Comment by cpass78** [comment]
With the new tax laws, this should be at least medium priority. Adding a new log file named {{ timestamp }}.log should be relatively simple.

**Comment by YoJeff** [comment]
This is a 'nice to have' built-in feature, but is easily accomplished using existing tools such as logrotate.

**Comment by cpass78** [comment]
@YoJeff , You say that as if the majority of the people know what logrotate is or are running on linux systems. The systems already creates the log, how hard is to not overwrite it 😒

**Comment by YoJeff** [comment]
I'm just saying that in the grand scheme of features and bugs -- this feature already exists.    Its a good idea, but low priority.   I'm sure Windows alternatives exist as well.   If this is an issue for you now -- there are existing solutions.

**Comment by ba32107** [comment]
Not an issue currently, but a nice to have I agree. But the solution is to just simply add the date to the log file pattern. Literally one line of config change. These low hanging fruits are really beneficial to take care of sooner than later.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
