### ISSUE TITLE
[BUG] empty values on binance

### ISSUE THREAD

**Issue by Werewolve** [taniman/profit-trailer#598]
Many of the values in the monitoring view are empty, see image!
Using ETH Market and binance exchange.

<img width="1188" alt="bildschirmfoto 2018-01-08 um 01 23 41" src="https://user-images.githubusercontent.com/3767530/34655980-c7dd61ae-f412-11e7-8ff0-dcf0bd23cf76.png">

Thanks!

**Comment by djcrypto75** [comment]
Yes its related to the Binance IP Ban issue, we cannot pull so much data from Binance yet. When that is fixed you will see more data.
