### ISSUE TITLE
Suggestion: BTC/USD price on Binance

### ISSUE THREAD

**Issue by bloodbit** [taniman/profit-trailer#600]
Hi,

Now the BTC/USDT price fails to show and may be messing my lists.
I am sure you savvy people can make USDT/BTC dust to keep track
... and manage it like IT dust --> never touch it!  =-)

kind regards,
rui

**Comment by YoJeff** [comment]
The BTC/USDT price in the gui is dependant on coinmarketcap.   If they are having issues, the gui will reflect those issues.
