### ISSUE TITLE
Binance bug: manually sold coin not removed from DCA log

### ISSUE THREAD

**Issue by japsen** [taniman/profit-trailer#603]
Using 1.2.6.9 / Binance.
The HSRETH pair that was showing up in my DCA log has been manually sold completely through the Binance interface. It is now a few hours later but the coin still shows in the DCA log. 

Expected behavior: The bot should fetch the difference in coin balance and remove the coin from pairs or DCA log.     
or - it should fetch all latest filled orders from the api and fix the pairs/DCA log.

Things I tried to resolve the issue:
- restart the bot
- enable config and try to do a XXX_XXX_reset_stored_average = true  (no result) and a HSRETH_panic_sell_enabled = true (also no result)
- I stopped the bot and manually removed all references to this coin in the ProfitTrailer data json file. Initially the coin was gone from the DCA log, some time later it popped back up in the DCA log showing as 0 DCA with a huge buy amount.

**Comment by mather21** [comment]
simlar thing happened to me i had two orders in dca after i had updated a few settings when i refershed its says theirs no DCA in the log but the GUI still shows i have half my money in dca so where did they go?

**Comment by t0mNL** [comment]
I had a similar problem. After shutting down PT, doing upgrades to a newer version (2.0.2) and manually selling a coin for BTC in the meantime, PT kept the coin in the DCA log and didn't made any new purchases.
I've fixed this by doing:
1) Shutting down PT.
2) remove/rename/move the files ProfitTrailerData.json, ProfitTrailerData.json.backup and removing all the files in the folder backup (ProfitTrailerData-{numbers}.json.backup).
3) Starting PT again, checking config for unwanted/lost changes.
After that, PT was working again.

Please note: Maybe this is not the best way to do it, but in my case I had 0 pairs/DCA so removing the whole json file was the easiest for me. If you have a lot of pairs/DCA's and only need to remove 1 pair, maybe it's better to remove that specific pair from the json files.

**Comment by SgtBatten** [comment]
Manual actions can take 10 minutes to be recognised. Generally if it has glitched out a restart will fix it immediately
