### ISSUE TITLE
The Java JAR file "ProfitTrailer.jar" could not be lauched ?

### ISSUE THREAD

**Issue by Cryptastic** [taniman/profit-trailer#605]
Hello, I'm running MAC OSX
I downloaded the Profit Trailer, Downloaded Java 8, updated all the specs for the bot.
When I start the BOT I get the Error
The Java JAR file "ProfitTrailer.jar" could not be lauched

thx

**Comment by YoJeff** [comment]
Github issues are not for support.   Please visit the telegram support group.
https://wiki.profittrailer.io/doku.php/start
