### ISSUE TITLE
ALL_max_cost and ALL_max_cost_percentage simultaneously

### ISSUE THREAD

**Issue by Sergzy** [taniman/profit-trailer#606]
Currently, settings ALL_max_cost and ALL_max_cost_percentage are excluding each other. My suggestion is to make them work simultaneously.

Example:
ALL_max_cost = 0.0022
ALL_max_cost_percentage = 5

The bot should use percentage setting, but if the percentage of the balance comes lower than ALL_max_cost, it should use ALL_max_cost setting. This way, we can always set ALL_max_cost in our setting to make sure that the bot doesn't run in a problem when it's trying to deal with an amount that our exchange doesn't allow.

**Comment by YoJeff** [comment]
This would be  confusing having 2 max_cost's like this, particularly because you'd like the ALL_max_cost to behave (in certain circumstances) like a minimum, not a maximum.

For this suggestion, a new configuration value like:
ALL_min_cost= 

Would be more descriptive.   But still this only affects people who want to dabble with percentages right around the bottom limits.    Let's see if there is any interest.

**Comment by Sergzy** [comment]
I understand your concern, so here is an updated version. Make a new setting which is exchange specific in format like EXCHANGE_min_buy (eg. BINANCE_min_buy) where user can specify minimum buy value. This value would have first priority in case that ALL_max_cost or ALL_max_cost_percentage equeals to less than EXCHANGE_min_buy, the latter value would be used.

**Comment by YoJeff** [comment]
I still think the right answer is to not use percentages if you are that close to the minimum.   Or use reasonable percentages with a buffer.

**Comment by Sergzy** [comment]
Of course you can do that, but with this new setting you could just do set&forget, no matter what you are doing with your balance. Currently you have to calculate percentage manually and set max_cost manually in case it's too low = manual labour that can be avoided in a few lines of code.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
