### ISSUE TITLE
[Feature Request] View last hours logs within web GUI.

### ISSUE THREAD

**Issue by Macflurry26** [taniman/profit-trailer#608]
Hi, would it be possible to get a tab in the web GUI that displays the last hours logs?

It would be nice to be able to run the bot remotely day to day without needing to RDP.  The hot config was a great touch but the only thing missing now is the ability to check your logs on the fly so you can see what is happening if you suspect issues or want better insight into what the bot is doing at any point.

**Comment by YoJeff** [comment]
You can view logs by /monitoring/log

But it's unformatted.

**Comment by Macflurry26** [comment]
Ha, I just tried reading that one and almost went blind when it popped up on the screen!! lol

I think it definitely needs formatting for the average minion like me.

**Comment by YoJeff** [comment]
I was just saying.  If you NEED it -- there it is.   You could post it into a json editor, or pull it with postman (or similar app) to prettify it client side.   But yea, it needs a gui treatment.

**Comment by djcrypto75** [comment]
I Agree, its on the roadmap for a "soon" release.

**Comment by YarTheBard** [comment]
I just stumbled across this post.  This Chrome extension formats the json log in the browser. May get you by for a while.  It's called "json viewer" by tulios.

[https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh?hl=en-US](url)

**Comment by djcrypto75** [comment]
on roadmap
