### ISSUE TITLE
Front page always showing BTC price

### ISSUE THREAD

**Issue by Sergzy** [taniman/profit-trailer#610]
Just started running ETH market, but the front page still shows BTC USD Price. I guess it should show ETH USD price in that case?

**Comment by djcrypto75** [comment]
Its showing the ETH USD Price in the Ticker and BTC USD Price in the Dashboard. Its meant to be like that :)

**Comment by nstefi** [comment]
That's what I noticed too. What's the point of showing the BTC price if the base is ETH? I might not even trade BTC-ETH pair, so I should not care about BTC price.

**Comment by djcrypto75** [comment]
Design choice. It will stay like this :)
