### ISSUE TITLE
Weight profit % based on age of bags

### ISSUE THREAD

**Issue by phildlight** [taniman/profit-trailer#613]
Can you add the ability to decrease profit % based on the age of the bags?

Maybe setup A,B,C and 1, .5, .25 etc. values below as user config values?;
 
If the bag age is greater than A, use profit of 1
If the bag age is greater than B, use profit of .5
If the bag age is greater than C, use profit of .25
If the bag age is greater than D, use profit of 0

Then on to loss;
If the bag age is greater than E, use profit of -.25
If the bag age is greater than F, use profit of -.5
If the bag age is greater than G, use profit of -1

I have very little code experience or I would try to help here.  I would personally like the ability to use this kind of strategy.

**Comment by BeldarConehead** [comment]
I second this, unless you can figure out how to NEVER have and bags :)

**Comment by woodyalien** [comment]
Great idea, that would address some situations where I need to manually interfere to get rid of stuck trades!

**Comment by YoJeff** [comment]
There are various options to take profits at different times in v2.x.  

If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
