### ISSUE TITLE
Add "watch log"

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#616]
Most users have one or several coins they want to hold. These are currently being displayed in the pairs log and mess up the statistics. I still want them displayed. Would it be possible to add a "Watch log" next to the already existing "Pairs log", "DCA log" and "Pending log"?

**Comment by minerdude** [comment]
I think a "Watch log" is a better term to a watch mode section that show stats from the testmode

**Comment by timh77** [comment]
Pairs which you have specified as "trading disabled" get the watchmode strategy. So in that sense it might be less confusing to move those pairs to the new overview.

**Comment by halimozturk** [comment]
Maybe you can call  it HODL lod :)
