### ISSUE TITLE
Binance websocket API

### ISSUE THREAD

**Issue by Sergzy** [taniman/profit-trailer#618]
I guess that currently the bot is pooling RESTAPI for its operation. I was monitoring my sales log and slippage is a disaster. I have a trailing_profit = 0.33, but slippage (Trigger%-Profit%) is usually around 1% or worse (just got a trade with 3%!! slippage).
I checked the bot log and saw that it tried to sell for X price at first, but it expired and in second attempt it sold for Y. However, the gap between first and second sale call was 20 seconds! I suggest you to switch to websocket at all points where it can replace RESTAPI and make the bot behave much faster.
 
In worst case, you should drastically decrease the pool time when the bot sent sell and is waiting for trade to be confirmed or if it's not, send a new sell signal much much sooner.

**Comment by lutzleonhardt** [comment]
+1

**Comment by sebi1505** [comment]
+1

**Comment by cristianserban** [comment]
you cannot use the websockets to make trades only to see trends 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

we can use them to make last 24h price evaluation that are not working properly at the moment on binance

**Comment by Sergzy** [comment]
I understand you can't place trades, but you can get user data through web socket which would be a major improvement: https://www.binance.com/restapipub.html#user-wss-endpoint

After placing sell signal, you can track in real time whether order was filled or not. If not, you can again track websocket to see in real time when the balance was restored and you can send another sell signal immediately (a few ms delay). 

Also you should use websocket for tracking trades and whatever other things you need in background and you can get via sockets. That way, you wouldn't use RESTAPI calls, so you would be able to call them much more frequently in events that you need them (since you wouldn't be hitting the limits because of the savings of API calls provided by the usage of the socket).

For example price tracking could be done via socket and the bot would have access to them in real time meaning, it could react with a few milliseconds difference (when for example sending sell signal after trailing_profit requirement is fullfilled).

One of the main points of profit-trailer is to be extra fast because GAIN strategy can work its best when reactions are very fast, so I think implementation of the web socket should be your top priority. I predict that the improvements in profits would be massive.

**Comment by cristianserban** [comment]
you are correct but I have been testing the websocket api for little while and there were some conectivity issues.. .maybe with the last update on the api they are solved.. dont know.. need to look into it again.. 
also this must be aproved by @taniman

**Comment by chrismpalmer** [comment]
I agree, I have other bugs reported regarding this. In the last 3 days its added up to hundreds of misses.

**Comment by YoJeff** [comment]
Websockets are a mess.   And for multiple exchanges, a multi-dimensional mess.

**Comment by Sergzy** [comment]
@cristianserban you should push on Binance to fix it then. I'm sure they are also interested in people doing more trades there. I don't have enough information about those issues, so can't help unfortunately.

**Comment by chrismpalmer** [comment]
Hardly...its a core component of almost every messaging solution on the planet. If they host api doesn't know what they are doing is another story.

Perhaps we focus on the requirement: "If we have less misses we accrue more profits and less bags". This scenario works very well when the market is just sitting around 1-3% up and down.  If your not willing to explore the web sockets what can be done? I am interested in assisting if anyone needs help.

**Comment by YoJeff** [comment]
Websockets are not on the roadmap.
