### ISSUE TITLE
[Feature Request] Configure Time frame for Short Term BTC Price Drop/Rise

### ISSUE THREAD

**Issue by LoganH1985** [taniman/profit-trailer#619]
While a 24 Hr BTC Price Drop/Rise trigger has its uses, the bot would be much more accurate at avoiding 
sudden price fluctuations and loading up on bags if the price drop/rise trigger was based on a shorter time frame of 14,400 - 21,600 seconds. It would be great to have a SOM trigger for both Long Term, Short Term and Long Term/Short Term Cross Overs.

**Comment by alcar2** [comment]
+1

**Comment by Macflurry26** [comment]
I was talking to someone about this wondering if it would be more responsive if you could configure it to be looking at BTC over the last hour  or two to catch the drop faster.

**Comment by minerdude** [comment]
up for it

**Comment by taniman** [comment]
if you guys would search the isues before creating new ones would be very helpfull to me.

this one is even worse because it is in the milestone for 1.2.7

Please read before creating issues or I will have to disable this

**Comment by LoganH1985** [comment]
Not a problem, I was told that if I wanted to post a suggestion to do so
here. I will look through

*Logan Harrington*
*Managing Director*
*HALI Capital Group LLC*
*Cell: 443-486-8663 Open calls from 4-6PM*
*(Text only w/o appt Outside of open call)*
*www.HALICapitalGroup.com <http://www.HALICapitalGroup.com>*
*Facebook <https://www.facebook.com/profile.php?id=100009491289935>*
*LinkedIn
<https://www.linkedin.com/profile/view?id=103992086&trk=hp-identity-name>*


SECURITIES DISCLAIMER: Sender is not a United States Securities Dealer,
Broker or US Investment Advisor. This electronic transmission and or
attached documents are not to be considered a solicitation for any purpose
in any form or content, nor an offer to sell and/or buy securities. Merely
describing the details of an existing private placement program
doesnot constitute
an offer or solicitation of any kind and, if presented, is done so as a
request for information. If you are notthe intended recipient, you should
delete or destroy this message immediately and/or any of its attachments
and are hereby notified that any disclosure, copying, or distribution of
this message and/or its attachments, or the taking of any action based on
it, is strictly prohibited as noted above. This email letter and any and
all attachments and related documents are never considered to be a
solicitation for any purpose in any form or content. Upon receipt of these
documents you, as the Recipient, hereby acknowledge this Warning and
Disclaimer. These Confidential communications are protected under the
Gramm-Leach-Bailey Act 15 USC, Subchapter 1, sections 6801-6809 and other
laws addressing the disclosure of Non-Public Personal Information.

CONFIDENTIALITY DISCLAIMER: This email and any files transmitted with it
are confidential and intended solely for the use of the individual or
entity to whom they are addressed. If you have received this email in error
please notify the system manager. This message contains confidential
information and is intended only for the individual named. If you are not
the named addressee you should not disseminate, distribute or copy this
e-mail. Please notify the sender immediately by e-mail if you have received
this e-mail by mistake and delete this e-mail from your system. If you are
not the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.
