### ISSUE TITLE
How to Open and run  the PT Java Files on Mac

### ISSUE THREAD

**Issue by gitHappy2** [taniman/profit-trailer#621]
Hello, 
This may seem basic, but Im having trouble opening these files on my MacBook
My default browser is Safari, and the latest Java is installed

I downloaded  all the Profit Trailer  files and moved them to my Application folder

When I  open "ProfitTrailer.cmd" the message says

"There is no application set to open the document “ProfitTrailer.cmd”.

"Search the App Store for an application that can open this document, or choose an existing application on your computer."

What do I do?

gH2

**Comment by YoJeff** [comment]
This is for bug reporting.   Use regular support channels.
https://wiki.profittrailer.io/

**Comment by Cryptopdmoney** [comment]
How do I stop these emails?  It said I was removed from the group

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 9, 2018 at 4:30 PM, YoJeff<notifications@github.com> wrote:   
Closed #621.
