### ISSUE TITLE
Feature Request: Clear Dust Bags in Binance

### ISSUE THREAD

**Issue by vbootstrap** [taniman/profit-trailer#623]
As a result of PT not correctly identifying dust on Binance in versions prior to 1.2.6.9, I am left with 45 dust bags.  It would be wonderful to have PT clear those bags and prioritize dust clearing going forward.

**Comment by YoJeff** [comment]
Dust is an ongoing issue for everybody.   All options are being considered, although the ultimate fix is on Binance.
