### ISSUE TITLE
My Current Value not populating

### ISSUE THREAD

**Issue by charliea77** [taniman/profit-trailer#624]
Hello, New user here trying to get the hang of things. Any help would be much appreciated. 

Issue: The "current value" column is not populating in the possible buy log window. 
It shows all Zeros. However, when I run ProfitTrailer on my desktop at home, the list populates just fine. 
Is this something to do with the VPS service I am using? 

I am using a VPS service (Virmach) I have the "SSD2G XLUSV KVM & SSD Windows VPS"
Have Java 8
Google Chrome

![12345](https://user-images.githubusercontent.com/35284998/34756292-fbff8a3c-f586-11e7-9e50-3b61347dcb95.JPG)

**Comment by WolNielsen** [comment]
This is a Date issue. Check the date on your VPS, once the date is correct (ie not a day ahead) the Current Value will work.

**Comment by taniman** [comment]
try opening cmd and running this command if you are on a windows machine
w32tm /resync

other wise, just make sure your time is correctly synced and that you have a correct timezone set.

**Comment by cjbender1** [comment]
I'm also having this problem - have checked the time zone info is correct.  any ideas?

**Comment by cupid-stunt** [comment]
Yes, same here. Time is set correctly and the bot shows zero for all the current values.

**Comment by SgtBatten** [comment]
current value should be zero if using a BB buy startegy.

If not using a BB buy strategy and current values are 0 then your clock is not synced to the internet.

**Comment by cupid-stunt** [comment]
I'm using GAIN. I have two bot working on a Raspberry Pi. Both are working fine except one bot (USDT) is showning zero for current value. So both times are synced to the same clock. One working, one not working.
