### ISSUE TITLE
Backtesting of strategies

### ISSUE THREAD

**Issue by abhirb1** [taniman/profit-trailer#626]
Feature request -> When we apply strategies then we need to actual wait and see if its working or not! Instead of that if backtesting of applied strategy feature is there then we can save lot of time and money.

Are you planning to provide this feature?

**Comment by tatarin38** [comment]
Test mode = true?

**Comment by helo03** [comment]
https://github.com/taniman/profit-trailer/issues/435
please use search function.
I'll close this issue.
Thanks
