### ISSUE TITLE
To be able to use it at ease from the Japan.

### ISSUE THREAD

**Issue by 1985kurosawa** [taniman/profit-trailer#627]
You。 How do you do. I am called Kurosawa. In Japan, the cryptographic currency is called the virtual currency, the market is very large, and enforcement of regulations such as laws has made its own progress. It is said that the ratio of bitcoins is accounted for 40% of the world. Profittrailer This product is excellent, and Japanese do not even know that there is an automatic robot for purchase. I want more Japanese people to know this wonderful. Everyone is good there, I currently use this product Japan, the Exchange is Binance. The very trouble is error:-1003, way too many requests stops working. I want to know how to fix this.

I've never done any of the programs, and since my English is poor, I'm currently experimenting with the settings that are being released and sending out my days of automated trading.

I want someone to help me. And if possible, I want to arrange this product for Japanese people and support it so that it can be easily purchased.

I use the translation tool. (Microsoft translation)

**Comment by YoJeff** [comment]
This is a Binance issue,  they seem to have issues with servers in Japan.
