### ISSUE TITLE
[Bug] Coin-Pair Enabled Panic Sell not working

### ISSUE THREAD

**Issue by benoc** [taniman/profit-trailer#628]
In the most recent release on Binance, Coin-Pair enabled panic sell does not do anything.

I have ensured correct syntax as per the Wiki:
XXXBTC_panic_sell_enabled = true

I have also tested:
XXXBTC_panic_sell_enabled = True
XXXBTC_panic_sell_enabled = TRUE
XXXBTC_panic_sell_enabled = 1

Coin-pair commands for sell_value, trading_enabled etc work still.

**Comment by YoJeff** [comment]
Panic sell works fine.   Check the wiki for support options:
https://wiki.profittrailer.io/doku.php/pairs.properties

**Comment by benoc** [comment]
This was related to Coin-Pair Panic Selling on Binance, not just Panic Selling in general.

As I already stated the syntax was as per the wiki link you provided:

> ALL_panic_sell_enabled = false
>Set to “true” to sell all of your coins with a balance IMMEDIATELY for current market prices. It does what >it says, and does it now. Use with caution.
>
>COIN-PAIR ENABLED: This setting works with single coins. See here for more info.
> 

And as per the link to Coin-pair settings:

> Example: I want to panic sell a single coin.
>Add BTC_ETH_panic_sell_enabled = true to your pairs.configutation file.
>
>This is assuming you are on Poloniex and selling your ETH bought with BTC.
>
>COIN-PAIR syntax: Poloniex coin pairs are defined like BTC_ETH 
>Bittrex coin pairs are defined like BTC-ETH 
>Binance coin pairs are defined like ETHBTC 
> 

As stated I have used the correct Binance syntax and configuration setting:
`MCOBTC_panic_sell_enabled = true`

I have tried multiple currency pairs and reinstalled the newest patch.
After an hour of waiting for the 'immediate' sale nothing occurs and I am forced to sell via Binanace directly.

Is something missing from the Wiki, such that coin-pair settings must be adjacent to the ALL settings?
As this setting should override the ALL setting as per the wiki:
>A coin pair setting takes priority over ALL_ settings 
>
