### ISSUE TITLE
Help!  cant load profit trailer after purchase

### ISSUE THREAD

**Issue by MPete10** [taniman/profit-trailer#630]
I have been working on this all day.  If someone can help me it would be greatly appreciated.  

When I get to the  Windows command script and hit the enter key, it gives me an error 
 "unable to access jar file".
Not sure what it wants .

**Comment by MPete10** [comment]
Do i need to register my license with  telegram first?  if so Im having a hard time doing that as well.

**Comment by YoJeff** [comment]
This is for bugs only.    Check the wiki for support options:
https://wiki.profittrailer.io/

**Comment by MPete10** [comment]
I did look at wiki. 


Sent from Yahoo Mail for iPhone


On Wednesday, January 10, 2018, 12:08 PM, YoJeff <notifications@github.com> wrote:


This is for bugs only. Check the wiki for support options:
https://wiki.profittrailer.io/
