### ISSUE TITLE
[FEATURE REQUEST] All Price Rise/Drop Triggers

### ISSUE THREAD

**Issue by mattrdp77** [taniman/profit-trailer#631]
I have a request for the Dev team.

It would be very powerful if a feature like the ALL_btc_price_drop_trigger could be coin pair enabled. 

For example, if the market trends up or down for an individual pair like BTC-ETH the bot would enable or disable trading for that pair.  At the moment this trigger only works for SOM, but a similar feature to enable/disable trading (or turn on SOM for individual pairs) based on market trend for each pair would help decrease bags and help the bot make smarter trades.

Would a feature like this be possible?

**Comment by YoJeff** [comment]
#80
