### ISSUE TITLE
Showing incorrect data

### ISSUE THREAD

**Issue by clownfish44** [taniman/profit-trailer#635]
Hello the bot says that this coin has dca'ed once and yet it has not.

https://gyazo.com/84b526c00f934d8bfe211ef4e0f85eab
https://gyazo.com/6bb96fd6e8e039cde9c880fb58e38d03
https://gyazo.com/c2258939e7176947f295bdfb2f87afff

**Comment by taniman** [comment]
Did you buy manually or sell this coin manually? That's the one reason that this can happen.
