### ISSUE TITLE
Error occured in TH, message null, result: null

### ISSUE THREAD

**Issue by minerdude** [taniman/profit-trailer#636]
I'm receiving this error message continually in log.
I tried a fresh install, deleted ProfitTrailerData and the error persists.

2018-01-10 21:13:52 ERROR ProfitTrailerService - Tradehistory - Please fix your dust levels in configuration.properties
2018-01-10 21:13:52 ERROR ProfitTrailerService - Error occured in TH, message null, result: null

my configuration file:

#sell options
sell_fillOrKill = false
sell_immediateOrCancel = true

#buy options
buy_fillOrKill = false
buy_immediateOrCancel = true

hideDust=true

testMode=false

BTC_dust = 0.0011
ETH_dust = 0.0007 
USDT_dust = 3.50#sell options
sell_fillOrKill = false
sell_immediateOrCancel = true

#buy options
buy_fillOrKill = false
buy_immediateOrCancel = true

hideDust=true

testMode=false

BTC_dust = 0.0011
ETH_dust = 0.0007 
USDT_dust = 3.50

**Comment by Ninio1973** [comment]
Hello there! 
I have exactly the same problem! Tried everything to no avail!  Did you get any answer/solution? The bot is not trading anything!

**Comment by taniman** [comment]
will release today a fix

**Comment by Mattchew86** [comment]
How to fix this?

**Comment by Mattchew86** [comment]
I'm also getting this error now

**Comment by helo03** [comment]
Have you updated to the most recent version?
