### ISSUE TITLE
[Bug] Ongoing  From #628 Coin-Pair Enabled Panic Sell not working

### ISSUE THREAD

**Issue by benoc** [taniman/profit-trailer#638]
This is a continuation from #628 which I cannot reopen.

>  @YoJeff
>  Collaborator
> YoJeff commented 13 hours ago
> Panic sell works fine. Check the wiki for support options:
> https://wiki.profittrailer.io/doku.php/pairs.properties
> 
>  @YoJeff YoJeff closed this 13 hours ago

This was related to Coin-Pair Panic Selling on Binance, not just Panic Selling in general.

As I already stated the syntax was as per the wiki link you provided:

> ALL_panic_sell_enabled = false
> Set to “true” to sell all of your coins with a balance IMMEDIATELY for current market prices. It does what >it says, and does it now. Use with caution.
> 
> COIN-PAIR ENABLED: This setting works with single coins. See here for more info.

And as per the link to Coin-pair settings:

> Example: I want to panic sell a single coin.
> Add BTC_ETH_panic_sell_enabled = true to your pairs.configutation file.
> 
> This is assuming you are on Poloniex and selling your ETH bought with BTC.
> 
> COIN-PAIR syntax: Poloniex coin pairs are defined like BTC_ETH
> Bittrex coin pairs are defined like BTC-ETH
> Binance coin pairs are defined like ETHBTC
> 

I have used the correct Binance syntax and configuration setting:
`MCOBTC_panic_sell_enabled = true`

I have tried multiple currency pairs and reinstalled the newest patch.
After a day of waiting for the 'immediate' sale nothing occurs and I am forced to sell via Binanace directly as the pairs just sit in the Pending List.

Is something missing from the Wiki?
As this setting should override the ALL setting as per the wiki:

> A coin pair setting takes priority over ALL_ settings

Coin-Pair Panic Sell for Binance is not working fine. It is not functioning at all.

**Comment by taniman** [comment]
I think you are trying a functionality that does not exist. 
You cannot sell neither panic sell stuff in pending log.
The bot does not really do interactions with the pending log. That is why when a pending log item is sol it will not appear in sales log either.

So panic sell works. but only for DCA and pairs log
