### ISSUE TITLE
Invalid License when hardening firewall

### ISSUE THREAD

**Issue by spanznet** [taniman/profit-trailer#639]
Hi,

ProfitTrailer was working fine under Ubuntu 15.04 until I hardened the firewall by adding 3 accept rules and a DROP ALL:

iptables -A INPUT -p tcp -m tcp --dport 8081 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A INPUT -j DROP

At this point, launching PT will always result in "ERROR Application - Invalid License".

If I remove the DROP ALL rule, ProfitTrailer will immediately work fine again as expected.

I also have SSL enabled on port 8081 in case that 's relevant.

**Comment by taniman** [comment]
well the license server goes through portt 443 if that helps

**Comment by spanznet** [comment]
Sorry mate, opening inbound port 443 didn't resolve the Invalid License issue.  All outbound ports remain open.
