### ISSUE TITLE
EXPIRED buys showing in telegram as BOUGHT

### ISSUE THREAD

**Issue by SinFuego1** [taniman/profit-trailer#645]
PT sends a message to telegram that a crypto is bought before it has checked if it has been "expired" or "filled". 
It should only send if a buy has been filled or it should show up as an unsuccessful buy instead of a successful buy.

**Comment by taniman** [comment]
Ant buys are checked for success before a message is send. Can you provide some data?
Log files
acreenshots etc..

**Comment by enric34** [comment]
Hi , sorry for wrong section, i want to add 2 id , how to add "," after one code..
telegram.chatId =AccountChatid1,Accountchatid2

is right this "," ?

**Comment by SinFuego1** [comment]
I have been checking it again and again. I have not been able to reproduce as of yet, so this issue can be closed.
