### ISSUE TITLE
REQUEST PT sends extra information

### ISSUE THREAD

**Issue by SinFuego1** [taniman/profit-trailer#646]
It would be great to have an option that occasionally sends OPEN trades and/or DCA, daily sells and overall profit so far to telegram. Option would be either OFF or a set amount of time, based on world clock and not PT running time.

Personally I restart the bot every so many hours to make sure it keeps running and isn't sitting all day on an error.

**Comment by dkrym** [comment]
I was actually thinking it would be cool to have some simple template syntax and predefined variables so you could change what the telegram messages contain, something like that:
{{server.name}}
Just bought: {{bought.currency}}
Cost: {{bought.cost}}
Rate: {{bought.rate}}

So you could modify it lets say to send:
{{server.name}}
Just bought: {{bought.currency}}
Cost: {{bought.cost}}
Rate: {{bought.rate}}
Remaining Balance: {{user.balance}}
Curr DCA cost : {{user.dca.cost}}

**Comment by taniman** [comment]
This is a trading bot, not a reporting system. So I would like to concentrade on making the bot better instead of aesthetics
