### ISSUE TITLE
New error message

### ISSUE THREAD

**Issue by Effenberg0x0** [taniman/profit-trailer#648]
I started getting this message today.

2018-01-11 19:49:14 ERROR ProfitTrailerService - Tradehistory - ERROR: -1000, An unknown error occured while processing the request.

I'm on Binance. Other users started reporting the same error simultaneously on Telegram.

**Comment by samuelGrahame** [comment]
yeah i am getting this too, after around 40 mins

**Comment by cristianserban** [comment]
Binance have problems with their api due to large number of accounts ... 
They have also closed the account registration....
