### ISSUE TITLE
Monitor Enhancement: Profit Column

### ISSUE THREAD

**Issue by lenardbang** [taniman/profit-trailer#65]
add a % sign next to value, for clarification, if possible add amount of BTC being profit within the ( ), next to percentyle (fancy ;)

**Comment by taniman** [comment]
What tab is this? The sell log will show the profit in btc actually

**Comment by lenardbang** [comment]
Im still getting used to the split tabs, yea, it was about the DCA tab, to see next to the 'current' profit etc, so we see if its near etc, good to know while still trading, not sold yet
