### ISSUE TITLE
ERROR GainStrategyRunner - An error occured

### ISSUE THREAD

**Issue by sil40dori** [taniman/profit-trailer#650]
This suddenly took over my log today (in the last hour or so). Using Binance. I looked at the past issues of this and it seems it came down to DUST entries or API/Licensing issues. I have not done anything weird or different with my APIs or license and I have added the DUST setting...still getting it. All my coins values are well above the DUST setting.

Unfortunately I don't get any expanded error info to give me a hint at what the problem is =\

Thanks

**Comment by sil40dori** [comment]
Just following up- I noticed a pair that was sold in Binance but it still shows in my PAIRS log, I believe it is trying to sell non-existent coins...

**Comment by MeisterPilaf** [comment]
I have the same error with WABIBTC... how we can fix this?

**Comment by sil40dori** [comment]
I am trying to disable trading for the coin in question (MOD) and restarted bot for good measure. We'll see.

**Comment by MeisterPilaf** [comment]
this works for me. but i think this is not the best solution.

**Comment by sil40dori** [comment]
Definitely not, but I can't think of anything else until a dev gives some insight.

**Comment by MeisterPilaf** [comment]
yeah. i can follow the error! he sells a coin in profit and i got a message on telegram and i can see the sell on binace. but the coin is yet in dca/pairs log. I have this issue with WABIBTC and BQXBTC...

**Comment by MeisterPilaf** [comment]
oh my god... now he buys every coin -.-

**Comment by samuelGrahame** [comment]
I had this happen, just press Control  + C in the CMD - then start profit trailer - then it fixed it self

**Comment by cryptonautic** [comment]
I also started getting this. I've been running fine for a few days with no problem. Two things happened today, they might be unrelated but want to mention in case it helps the devs track it down.

1. My VPS provider did a patch on the Windows machine today for meltdown. They must not have shut it down correctly... the machine was offline afterwards so I manually started it. Then when I started PT, it said my ProfitTrailerData.json file was messed up and I had to delete it.

2. I noticed a sell in the logs right before this error started happening. PT tried to sell twice and the order expired. The third time it said it was filled, although it also said that the transaction couldn't be found. I confirmed on the exchange (binance) that it did in fact go through.

I added the coin to the exception list and removed the ProfitTrailerData.json files just to be safe. The problem just occurred again and I got a screen shot (and this order did go through)... 
<img width="1247" alt="screen shot 2018-01-11 at 6 33 08 pm" src="https://user-images.githubusercontent.com/35355440/34857186-3b503a10-f6fe-11e7-93e3-b6f5934b9541.png">

**Comment by taniman** [comment]
Yes. This is binance api returning incorrect data and causing the bot to misbehave.

Are you on the latest version? What version are you running?

Not much we can do to protect agains invalid data

**Comment by sil40dori** [comment]
I am on the latest- v1.2.6.9

**Comment by cryptonautic** [comment]
I realize the problem isn't caused by PT, but can you handle it more gracefully? Once this error occurs, it writes this error to the console every 5 seconds and the pair log is out of sync with the exchange. Users have to delete the ProfitTrailerData.json file and lose their sales log and analytics  data to get it to stop flooding the console. For example, maybe you could sync the pair log data with the exchange every so often (maybe you do but I didn't see it happen).

**Comment by YoJeff** [comment]
If you let it be, it eventually fixes itself when the exchange stops acting up.

**Comment by cryptonautic** [comment]
Alright cool, whatever you guys think is the most graceful way to handle application errors is fine with me.
