### ISSUE TITLE
PT on VPS after update VPS wont work

### ISSUE THREAD

**Issue by Matej326** [taniman/profit-trailer#652]
C:\Users\Administrator\Documents\MATEJ\PROFIT 2018\PROFIT 11012018\ProfitTrailer
>java -jar ProfitTrailer.jar -XX:+UseConcMarkSweepGC -Xmx512m -Xms512m

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtil
s$1 (jar:file:/C:/Users/Administrator/Documents/MATEJ/PROFIT%202018/PROFIT%20110
12018/ProfitTrailer/ProfitTrailer.jar!/BOOT-INF/lib/spring-core-4.3.7.RELEASE.ja
r!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int
,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframewor
k.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
2018-01-11 22:09:17 ERROR ProfitTrailerService - Please use one of the following
 values in trading.exchange (application.properties). POLONIEX,BITTREX,BINANCE

C:\Users\Administrator\Documents\MATEJ\PROFIT 2018\PROFIT 11012018\ProfitTrailer
>pause
Press any key to continue . . .

Before update VPS no problems (Windows server 2012)
Please help.
Thanks

**Comment by taniman** [comment]
Please ask for help in rhe support channel. This is for actual issues / bugs
remove java 9 and install java 8
instal version 1.2.6.9
