### ISSUE TITLE
Incorrect Buy price - At zero...

### ISSUE THREAD

**Issue by samuelGrahame** [taniman/profit-trailer#654]
![image](https://user-images.githubusercontent.com/13449963/34857156-5b9628ee-f79d-11e7-9ed5-396043c07229.png)

**Comment by cristianserban** [comment]
Hi
did the bot both this pair?

**Comment by taniman** [comment]
The bot losy the price of this pair. Can we many reasons. please set the bought price manually

**Comment by samuelGrahame** [comment]
Bot created this, i think it was an issue with binance api. i manually sold. it got removed okay.

**Comment by pauldehav** [comment]
This is a persistent problem. Is there actually a fix?

**Comment by pauldehav** [comment]
found!
