### ISSUE TITLE
Feature request: Addition of RSI and Multiple buy strategies

### ISSUE THREAD

**Issue by VipPat** [taniman/profit-trailer#655]
It would be great if we can get RSI added and also if we can combine multiple strategies -

E.g. RSI is going down, price is going up - don't buy

RSI up, EMA up, Low BB - Buy

**Comment by cristianserban** [comment]
please check https://github.com/taniman/profit-trailer/issues/370

**Comment by cristianserban** [comment]
closed #370

**Comment by bbrodka** [comment]
http://jbmarwood.com/rsi-2-trading-strategy/

                        100
    RSI = 100 - --------
                       1 + RS

    RS = Average Gain / Average Loss
