### ISSUE TITLE
Ports (On Exchange while PT Runs)?

### ISSUE THREAD

**Issue by oliverb456** [taniman/profit-trailer#658]
At times, I like to have Binance open as PT runs. But it seems like that is causing issues with ports. I get an error about "Port 8081" sometimes. Is there a work around or should I just stay off the exchange while PT runs?

**Comment by cristianserban** [comment]
Maybe you tried to open again the PT. 
Send us the log file for this issue

They dont have anything in commune ... I mean PT runs on 8081.. and you access binance from the browser - a page that runs on a different server (binance infrastructure).

regards,

**Comment by YoJeff** [comment]
You can run both without any problems.
