### ISSUE TITLE
Expected JsonArray

### ISSUE THREAD

**Issue by murl** [taniman/profit-trailer#659]
**1.2.6.9**
**ubuntu 16.04**
**Exchange = BITTrex**
API Problems?

0|profit-t | 2018-01-12 03:40 -05:00: 2018-01-12 03:40:09 ERROR ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $
0|profit-t | 2018-01-12 03:40:09 ERROR ProfitTrailerService - Error occured in volume, message java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $, result: 200 - We got some incorrect data from the exchange -
0|profit-t | 2018-01-12 03:40 -05:00: 2018-01-12 03:40:09 INFO DCAStrategyRunner - API Problems?
0|profit-t | 2018-01-12 03:40 -05:00: 2018-01-12 03:40:12 ERROR ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $
0|profit-t | 2018-01-12 03:40 -05:00: 2018-01-12 03:40:12 ERROR ProfitTrailerService - Error occured in ticker, message java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $, result: 200 - We got some incorrect data from the exchange -
0|profit-t | 2018-01-12 03:40 -05:00: 2018-01-12 03:40:13 ERROR ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $
0|profit-t | 2018-01-12 03:40 -05:00: 2018-01-12 03:40:13 ERROR ProfitTrailerService - Error occured in volume, message java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $, result: 200 - We got some incorrect data from the exchange -

**Comment by taniman** [comment]
Yes. api or connection problems
