### ISSUE TITLE
lowBB value remains at 0

### ISSUE THREAD

**Issue by cryptobobross** [taniman/profit-trailer#662]
EMA startegy works just fine, but I was trying to try out the lowBB but the feature remains at 0 at all times.
Anyone having the same issue? or is it normal?

**Comment by taniman** [comment]
check your error log.
check you system clock.
did you change your system time manually?
let your system time synchronize with the internet

**Comment by orionmodern** [comment]
i also have this issue... how to resolve?

**Comment by orionmodern** [comment]
sorry, was looking at the wrong column (current value vs bb trigger)
