### ISSUE TITLE
Java error when trying to run Profit Trailer

### ISSUE THREAD

**Issue by Oval61251** [taniman/profit-trailer#663]
[ProfitTrailerlog.txt](https://github.com/taniman/profit-trailer/files/1626492/ProfitTrailerlog.txt)

[ProfitTrailerlog.txt](https://github.com/taniman/profit-trailer/files/1626491/ProfitTrailerlog.txt)
Hello,

I purchased Profit Trailer a few days ago (order 51219) and have been having issues trying to get it to run.  java.lang.IllegalStateException: The ticker Cache is not alive (STATUS_SHUTDOWN)

I will attach my log as well as the screen shot of what is happening 
![pt3](https://user-images.githubusercontent.com/35375405/34881867-bcdc9482-f782-11e7-8924-39f3491d0c66.png)

EDIT: I have down graded to version v1.2.6.8 and it is now working.

**Comment by YoJeff** [comment]
The top part of the error message is the interesting part, and... This is a support issue, not a bug.
https://wiki.profittrailer.io
