### ISSUE TITLE
[ERROR] Application - Please fix: trading_apiKey -- String index out of range: -10

### ISSUE THREAD

**Issue by Ghostdoge** [taniman/profit-trailer#666]
Hi, 

Bot running fine until I recently reboot. I changed no config files at all.

I did manual trading on Bittrex while bot was running a couple of times, but that has not been an issue in the past.

Screen shot of error - https://puu.sh/yZNCV/3ab1365745.png

I have tried new API's and also white listing my IP on Bittrex. The error still pops up on bot startup.

Any help would be great. 
Thank you.

**Comment by YoJeff** [comment]
This is a support issue, not a bug.
