### ISSUE TITLE
Bot not execute commands

### ISSUE THREAD

**Issue by Jarel298** [taniman/profit-trailer#669]
my bot stops working before 1day. everything before was run smoothly. I didn't change anything in the settings.
Now it's not buy anything. I asked in support channel And I didn't get any answer.
I am running the bot and it's not execute any command. the bot just became a zombie.
I have tried new API key, New VPS, reinstalled, changed configs. seems like the bot is not executeing any command.
I am using Binance exchange.
Please take a look my screenshots. Thanks.
https://image.prntscr.com/image/kHtfnE1KT6eNo5I4na5l9w.png
https://image.prntscr.com/image/I-XW--4vSaSuh-rCRRIqVg.png
https://image.prntscr.com/image/uBKwCACfRJCJ9RFTiBsW7w.png
Binance settings that I use: (Tried ALL)
https://github.com/CryptoGnome/Profit-Trailer-Settings
It's not work on default settings too.

**Comment by taniman** [comment]
fix your server timezone and date and clock. sync it with the internet

**Comment by Jarel298** [comment]
Which timezone should I put? 
what do you mean sync it with the internet?
Thank you for your quick response.

**Comment by jaklin231** [comment]
I have the same issue and I would like to know please, what do you mean by "fix your server timezone" ? 
Thanks.
