### ISSUE TITLE
Feature Request: Status via Telegram

### ISSUE THREAD

**Issue by celli030** [taniman/profit-trailer#67]
I have a suggestion for a new feature: status via telegram.

It would be nice if you can configure telegram messages per day, week or month. Some people want to get daily, some monthly notification. Also when (hour:minute) the message gets send could be configurable.

The message could contain those infos for the given period:
- number of buys
- number of sells
- profit / gain
- total btc balance (when the message gets triggered)
- available btc balance (when the message gets triggered)
- status about settings like sell mode on (when the message gets triggered)

This message could also help to know if the Bot/Server is still running.

What do you think? :-)

Cheers

**Comment by loopy83** [comment]
Sounds NICE!!!!!

**Comment by taniman** [comment]
I have decided that these features are taking my focus away from the bot. So won't fix. Will look for great addons instead
