### ISSUE TITLE
Provide "Sell now" button in Pairs and DCA

### ISSUE THREAD

**Issue by Scyks** [taniman/profit-trailer#673]
Sometimes a coin is moving very slow and reaches a small plus percentage and do not trigger the sell action before it went down again.

Therefore a "sell now" button could make sense to free the DCA/Pairs.

**Comment by Utone** [comment]
very good, like if your DCA just barely reaches it saves reconfiguring gain or manual selling, in short one press of a button would be very nice.

**Comment by alvinphang** [comment]
yes please add in a quick buy now or sell now button on the BOT.. it will be very useful :)

**Comment by taniman** [comment]
I will ask you guys one more time to search before creating issues. This has already been asked.
