### ISSUE TITLE
FEATURE REQUEST : 1 Min chart support for Poloniex

### ISSUE THREAD

**Issue by alvinphang** [taniman/profit-trailer#675]
as I was using the EMACross I notice the bot is slow by 1 candle and
most times it did not caught the right timing to do a buy trigger so
it would be great if you add support for 60s Period indicator instead of just 300s (5min)

**Comment by taniman** [comment]
We can't add a period that is not supported by the exchange api

![image](https://user-images.githubusercontent.com/6751341/34905448-1149decc-f859-11e7-92b2-11c5f44b5dc8.png)
