### ISSUE TITLE
Manual sell option

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#677]
Sometimes I choose to sell my coins manually. In those case the results are missing in the sales log.
There's already a hotconfig option to (re)set the bought price (XXX_XXX_bought_price = 0.123456). How about implementing something like this for when you sold everything (XXX_XXX_sold_price = 0.123456).

**Comment by taniman** [comment]
we are planning on adding a sell button. you can use that in the future to sell

**Comment by timh77** [comment]
Cool, but will it support pairs you sold thru the exchange?
Sometimes the spread is so big you want to sell it manually to achieve maximum result.

**Comment by taniman** [comment]
The idea is to sell it through the bot and not go through the exchange to sell it manually.

**Comment by timh77** [comment]
I understand, that's why I propesed the hotconfig option (eg (XXX_XXX_sold_price = 0.123456). Easiest way to implement such a feature and keep the reporting in PT accurate.

**Comment by YoJeff** [comment]
How is clicking a button in a gui less desirable than clicking hotconfig, typing in a long string, and clicking save?

**Comment by timh77** [comment]
Depends on what the button does. If it tells PT to send a sell request to the exchange resulting in a sell on the bid price then I'd say it doesn't resolve my "problem".
Sometimes there's a big spread and PT will sell the coin at the bid price whereas people might be willing to buy it at a higher price. I do that manually on the exchange. So I just want to register the sale in PT, if the button does that: Fine! If not, then still a hotconfig option would be best for my case
