### ISSUE TITLE
[FEATURE REQUEST] Custom JS and CSS for frontend

### ISSUE THREAD

**Issue by masterpropper** [taniman/profit-trailer#678]
It would be nice if you will provide a way to load a custom.js and custom.css file into the frontend so we can tweak some small things to our needs and overwrite some css styles.

Maybe 2 settings inside application.properties:

frontend.custom_css_file = /path/to/css/file.css
frontend.custom_js_file = /path/to/js/file.js

**Comment by soltao** [comment]
@masterpropper I was able to increase the font-size for the mobile table_wrapper class by using mobile stylish in firefox. Now I'll try turning off the collapsible columns in mobile as there is very little time between refreshes to read the info there. Good luck customizing your css!
