### ISSUE TITLE
DCA not selling/buying after 1.2.6.7

### ISSUE THREAD

**Issue by jld13** [taniman/profit-trailer#680]
DCA is not selling/buying with same config file on any version after 1.2.6.7.  

max_cost = 0
max_buy_times = 5
min_buy_balance = 0

buy_strategy = ANDERSON
buy_type = DOUBLEDOWN
buy_trigger = -1.2
buy_trigger = -2.2
buy_trigger = -6
buy_trigger = -8
buy_trigger = -12
trailing_buy = .4

sell_strategy = GAIN
sell_value = .3
trailing_profit = .15

stop_loss_trigger = 0
stop_loss_timeout = 0

buy_available_volume_trigger = 0
ignore_sell_only_mode = false
max_buy_spread = 2

**Comment by taniman** [comment]
we are currently at 1.2.6.10 and no there have been no complaints. So it is safe to conclude that this is a setup problem and needs to be handled in the support channel.

This should be used to log actual issues

**Comment by taniman** [comment]
Also as I have seen the problem quickly I can tell you.

ANDERSON strategy has never supported triggers like this

buy_trigger = -1.2
buy_trigger = -2.2
buy_trigger = -6
buy_trigger = -8
buy_trigger = -12

the correct syntax is 
buy_trigger_1 = -1.2
buy_trigger_2 = -2.2
buy_trigger_3 = -6

etc

**Comment by jld13** [comment]
There is no support in the support channel. I can send logs if you would like and screenshots.
