### ISSUE TITLE
Request: Let me help you update the Monitoring page to look better

### ISSUE THREAD

**Issue by sroberson** [taniman/profit-trailer#682]
I'm a web developer with an ad agency and would love to update the Monitoring page so that it's more user-friendly.  Would you be open to my helping with html/css updates to the monitoring page?  I love PT, but that home page is a bit hard to read.  I don't mean to offend anyone, but there are some minor improvements that will help make it a lot more user-friendly.  

Thanks.

**Comment by antknight** [comment]
Agreed, I wish it looked less hazy

**Comment by djcrypto75** [comment]
Send me an email on support@profittrailer.com with your suggestions and I will take a look :)
