### ISSUE TITLE
missing Config button on localhost monitoring page

### ISSUE THREAD

**Issue by JxNull** [taniman/profit-trailer#684]
Hello there,
I am new to PT and starting with1.2.6.9  and recently update to vision 1.2.6.10.
I find out that monitoring panel is missing the Config button introduced on the wiki in either PT vision.  How could I fix it up? Or somehow I can set up brought price in case that to tell the bot to trade when a new deposited coming into the trading account.

![2018-01-13 1 08 37](https://user-images.githubusercontent.com/35373708/34908858-01257e96-f865-11e7-9200-fc5606e83448.png)

**Comment by YoJeff** [comment]
This is for bugs only.
https://wiki.profittrailer.io/
