### ISSUE TITLE
ALL_min_buy_balance_percentage not accepting live changes.

### ISSUE THREAD

**Issue by YarTheBard** [taniman/profit-trailer#687]
This may be a bug. In a nutshell.  Buy will exceed min buy bal error. Changed min buy bal % in Pairs. Changes detected. Same error.  Exact same error. Too the penny. Restarting the bot with pm2 doesn't work.  Have to kill the bot completely make the change. Restart bot.  I tried changing ALL_min_buy_balance_percentage from 50 to 90 and from 50 to 10.  Log files detects changes but exact same error persists.  Latest version of PT from last night. 1.2.6.10 

Snippet>
1|ptJRbin  | 2018-01-13 17:06 -05:00: 2018-01-13 17:06:29 INFO NormalStrategyRunner - You are not allowed to buy EDOBTC. Buy will exceed min buy balance 0.03094729. BAL: 0.02584794 - MC: 0.0025
1|ptJRbin  | 2018-01-13 17:09 -05:00: 2018-01-13 17:09:53 INFO NormalStrategyRunner - You are not allowed to buy BCDBTC. Buy will exceed min buy balance 0.03094729. BAL: 0.02584794 - MC: 0.002625
1|ptJRbin  | 2018-01-13 17:11 -05:00: 2018-01-13 17:11:28 INFO Util - **Detected configuration changes**
1|ptJRbin  | 2018-01-13 17:12 -05:00: 2018-01-13 17:12:13 INFO ProfitTrailerService - SOM is active for REQBTC. -- Manually set in PAIRS.properties
1|ptJRbin  | 2018-01-13 17:13 -05:00: 2018-01-13 17:13:00 INFO NormalStrategyRunner - You are not allowed to buy EDOBTC. Buy will exceed min buy balance 0.03094729. BAL: 0.02584794 - MC: 0.0025

**Comment by taniman** [comment]
just tested this on my machine. Working normally. How's your pairs.proeprties look like?

**Comment by YarTheBard** [comment]
Hmmn. Go ahead and close it out. I think my Pairs are fine.  But I will watch the logs in pm2 again. If you say the software is fine then most likely I have a conflict somewhere.  I'll run some more tests and see if I can duplicate it. Thanks.
