### ISSUE TITLE
Unable to turn off DCA with feeder, It keeps buying - PLEASE HELP

### ISSUE THREAD

**Issue by commandocrypto** [taniman/profit-trailer#688]
I am using the new PT Feeder add on.

I have:
ALL_DCA_enabled = false

In also every document now...
In all the pair folders in Superbear, bear, boring, bull, and superbull
In the appsettings document (in the main code and in boring)

And still EVERY five minutes by pairs document in PT gets the five minute update which turns on DCA again. Please help resolve this. This is ridiculous.

**Comment by mehtadone** [comment]
This is the profit trailer wiki not the feeder one. Please raise the issue on the feeder github or our discord https://github.com/mehtadone/PTFeeder
