### ISSUE TITLE
If CMC-API fails, the Monitor breaks

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#689]
I just saw all of my bots failing to display data on the monitor, instead I saw the red error box. Investigating it down a bit I saw that the CoinMarketCap API was failing with an error.

It looks like this causes the Frontend JS of the bot to just break. It would be good if this error could be handled - the CMC API info is clearly unimportant and the Monitor should continue to work if they have problems.

**Comment by djcrypto75** [comment]
Already fixed :)
