### ISSUE TITLE
Getting Error -1003 with newest profit trailer release

### ISSUE THREAD

**Issue by Roxxiga** [taniman/profit-trailer#693]
I have been running profit trailer on my home pc without issues for the past two weeks.  I downloaded the new profit trailer release earlier today and followed the upgrade instructions on the wiki (by putting the new .jar in the profit trailer folder) and now have the error saying

 2018-01-14 05:03:58 ERROR Application - Please fix: trading_apiKey -- ERROR: -1003, Way too many requests; IP banned until 1515928360880.

It was running for hours before this started.  Is this an issue with the newest profit trailer release and does anyone know how to fix it?  Is it as simple as making new api keys?

**Comment by nejinx** [comment]
I am having the same issue, i'm guessing the exchange has changed the limit for api requests.

**Comment by Roxxiga** [comment]
I think Binance is just having issues.  None of the coins on the exchange are loading the price chart or trade orders/history.  Hopefully the problem fixes itself and this IP ban isn't anything to worry about.

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/34915422-7c484cd2-f97a-11e7-8c4b-173bc6ef393f.png)

**Comment by sebi1505** [comment]
I have the same error ( German VPS)

**Comment by Lidskialf** [comment]
**Binance.com**

`Currently we are logging site errors, we had to limit your api connections for the estimated update. Visit us back in around 3 hours.`

**Comment by Roxxiga** [comment]
Thanks for the update.  Hopefully these IP bans get rescinded.

**Comment by commandocrypto** [comment]
Same error. I tried to switch the port to 8082, still doesn't work.

**Comment by Roxxiga** [comment]
I just tried starting the bot and it seems to be working now.

**Comment by samuelGrahame** [comment]
yep working for me too now

**Comment by treboul01** [comment]
Also work for me right know

**Comment by charliea77** [comment]
Woke up to this error, Now it seems to be working ok. Just restarted the bot

**Comment by charliea77** [comment]
Ok just kidding, it is still having issues. Any updates on this one?

**Comment by Morrowless** [comment]
After the update, using 5 sec throttle on Binance. Still getting this error. Wonder if using 2 or more bots (2 diff accounts) has a factor.

**Comment by ceedees23** [comment]
Getting the same error now after 1 day of running the bot.
Please @taniman take a serious look at the before we get permanent IP bans and the the product that I just bought is useless.

**Comment by digitaljon** [comment]
Hey Guys - I'm yet to get PT but could this be a solution? Would be good to hear 
![5af1a713-622d-4187-bab2-a70f8ab84b32](https://user-images.githubusercontent.com/35509515/35017182-707ef81c-fb67-11e7-94ef-cb94e73a7dcf.jpg)
how it goes

**Comment by YoJeff** [comment]
Ongoing api issues we are aware of.
