### ISSUE TITLE
Binanace IP bann since today

### ISSUE THREAD

**Issue by Gitulu** [taniman/profit-trailer#694]
Hello guys,

I get every time since today an instant IP bann on Binance.

Settings:
ProfitTrailer 1.2.6.10 and 1.2.6.9 same issue
2 different API keys as recommended
2 instances on Binance with different user and keys on the same PC
German dedicated dynamic IP address worked before 1 week

It seems binance bann since 12 o´clock GMT+1 the IP
I have created a ticket on Binance if they have feedback or make a API server upgrade.

Does anyone have here more information?
Log file is attached.

Thank you
Gitulu

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1629330/ProfitTrailer.log)

**Comment by Gitulu** [comment]
It seems it worked again, I will monitor this.

**Comment by efurban** [comment]
ok . i logged into Binance and changed the setting of "IP Access Restriction:" from "unrestricted" to  "Restrict access to trusted IPs only" and now it works again.   that seems fixed it coz my ip ban is till later today

**Comment by pmedia1000** [comment]
I installed the new release, and i got banned again, and I'm not sure the console message changed, would the message be different in the new release?

**Comment by XcidTrader** [comment]
Pause trading on BAN to prevent further banning. Saw this in the release notes, any idea what the code is to activate it.

**Comment by kfajardo** [comment]
How do you know if you're banned? I'm not seeing any on the logs but my PT has not gotten up-to-date values since this afternoon. And it's not trading (buying or selling) anything.

**Comment by johnlean90** [comment]
Why people get banned ?

**Comment by johnlean90** [comment]
The say if you use two bots same ipa they banned you that’s truth ?
