### ISSUE TITLE
Request: Abillity to disregard coins that have risen/fallen a certain % the last 24 hours

### ISSUE THREAD

**Issue by Miwala77** [taniman/profit-trailer#696]
Abillity to disregard coins that have risen/fallen a certain % the last 24 hours.

In the "Possible buy log" it could be a good feature (i think) to be able to filter out coins that have risen to much or fallen to far in the last 24 hours. Could help avoid catching "falling knives"... 

Maybe not a setting everybody would use, but i personally would like to try it out with a setting of +10%/-10% rise/fall to see if that would give better coin buys.

![image](https://user-images.githubusercontent.com/32440596/34918730-c09c82f4-f957-11e7-966e-c759f260c5f9.png)

In this example NEO shouldnt be consider a buy possibility and ETC should be, if my settings where at 10% for rise/fall over the last 24 hours...

Hope my suggestion makes sense :-)

Edit: Or maybe even an option to set the % number different for rising/falling coins:

Exampel:

Max_rise_percentage_24h:  XX%
Max_fall_percentage_24h:  XX%

**Comment by YoJeff** [comment]
dup #80
