### ISSUE TITLE
DCA Log page - Sell Strat column

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#698]
Can we have it showing in the "Sell Strat" column in DCA Log page similar how it shows in the "Buy Strat" column if it's trailing or not?
For example in "Buy Strat" column it either shows:
"LOWBB - (false)" or
"LOWBB - (true trailing)"

Thanks.

**Comment by taniman** [comment]
You don't need that in the SELL Strat. 
We already have Profit% and ST% 
They will keep moving up if the bot is trailing.
