### ISSUE TITLE
Request- Dynamic Settings if value of bitcoin changes

### ISSUE THREAD

**Issue by agcrypto** [taniman/profit-trailer#699]
Ability to use different settings if bitcoin has dropped or risen  X%

**Comment by cristianserban** [comment]
for the moment we have the ability to move to SOM if conditions are meet.
[https://wiki.profittrailer.io/doku.php/pairs.properties](url)
> TRIGGERS
> Triggers are used to control risk with the bot. Set these carefully if you wish to control when the bot buys. Often when the market makes a swing, it is caused by the underlying currency (BTC) moving up or down wildly. When it does so, these triggers will help to turn on “Sell Only Mode” (SOM).
