### ISSUE TITLE
Lots of pairs not going to Sales Log

### ISSUE THREAD

**Issue by bQvle** [taniman/profit-trailer#701]
I can see on binance that they were bourght and sold, the PT interface doesn't get the sales log. but it shows the leftover dust

**Comment by bQvle** [comment]
![image](https://user-images.githubusercontent.com/12952595/34927182-9d699882-f9b4-11e7-9f40-cc528e920f4c.png)

**Comment by bQvle** [comment]
![image](https://user-images.githubusercontent.com/12952595/34927191-ac79bbd6-f9b4-11e7-93e4-375286a9e64f.png)

**Comment by bQvle** [comment]
![image](https://user-images.githubusercontent.com/12952595/34927199-bc2857c2-f9b4-11e7-96b0-c2dd634a1c48.png)

**Comment by bQvle** [comment]
Maybe its because the order first expired?

**Comment by YoJeff** [comment]
Did it ever show up?  If it was pending, it will not show up.

**Comment by bQvle** [comment]
No it never showed up, this is just one of many :S

**Comment by taniman** [comment]
So you are either sending pairs to pending log or you have 2 bots running at the same time.
Simple question. What port are you running your bot on? 8081?

**Comment by bQvle** [comment]
Yes its running on 8081, I downgraded PT for now which seems to work as intended.

Heres the log (regarding the buy spam of MDA and ELF) 
https://justpaste.it/1fsz7
