### ISSUE TITLE
HotConfig Not Working

### ISSUE THREAD

**Issue by wetfiregames** [taniman/profit-trailer#702]
My bot is running on the Exchange: POLONIEX
After Transferring my ETH balance from coinbase, and applying BTC_ETH_bought_price = 0.07153072  into the hotconfig, the console still asks for me to set the Price. I upgraded to latest version v1.2.6.11 and still no luck. 

Going to just sell the ETH so it has a log to read. Thanks for iAmVae Victus advice on that.

**Comment by drapper1** [comment]
+1 
Same problem. Altcoins on bittrex and it asks for the bought price. setting it in the hotconfig and saving doesn't work.

**Comment by dennerikhub7** [comment]
Was hitting this problem too.
Solution!

In first line : XXX_XXX_reset_stored_average = true
Second line the bought price ( wiki hotconfig)

![b9f9ba14-d6c1-48fb-952a-ffcb8b1ac107](https://user-images.githubusercontent.com/4641454/35004099-33d33964-faef-11e7-90a6-6de247ff3b1d.jpeg)
