### ISSUE TITLE
Please check your VPS / PT connection

### ISSUE THREAD

**Issue by mcniick9** [taniman/profit-trailer#704]
![photo_2018-01-15_01-36-17](https://user-images.githubusercontent.com/35450105/34935986-96d8d9ee-f994-11e7-8c52-a6c6951a2293.jpg)

I'm not using a VPS and my internet connection works perfectly fine.
Tried restarting profit trailer multiple times.
I keep getting this error and need help.

**Comment by YoJeff** [comment]
This is not support.
https://wiki.profittrailer.io
