### ISSUE TITLE
PT sells at a loss when using DCA

### ISSUE THREAD

**Issue by antknight** [taniman/profit-trailer#705]
PT sold at a loss using DCA

![2018-01-15 11_26_00-binance bot](https://user-images.githubusercontent.com/1137677/34940768-cb4a3692-f9e8-11e7-8aa6-117d9fafb4a0.png)
![2018-01-15 11_28_50-order history-binance com](https://user-images.githubusercontent.com/1137677/34940769-cb5e95d8-f9e8-11e7-976e-02b8e8f77be5.png)
![2018-01-15 11_37_56-book1 - excel](https://user-images.githubusercontent.com/1137677/34940770-cb818c0a-f9e8-11e7-83bf-de882c596dc0.png)

Similar issues closed without explanation:
#378 
#651

**Comment by YoJeff** [comment]
You still have dust, so it's not a loss.

**Comment by antknight** [comment]
I checked back through my trade history and I found that at one point in the past I did indeed buy NEO for 0.005544 BTC. I subsequently sold that NEO but PT has used the 0.005544 for the calculation of profit which I believe to be the actual problem.

**Comment by dennerikhub7** [comment]
![d3f7de27-df4c-490b-9ea2-afe18be7bce1](https://user-images.githubusercontent.com/4641454/35003489-4e2efbd8-faed-11e7-9006-301dabd2785e.jpeg)

Few days ago, also had a bad trade with NEO.
Nice profit, but low in money.
