### ISSUE TITLE
PT Bought a Pair but it's missing! Didn't realize for an hour, completely missed out on the sale

### ISSUE THREAD

**Issue by commandocrypto** [taniman/profit-trailer#711]
PT bought a pair per NormalStrategyRunner, the coins are in my binance account, but the PT GUI can't find the pair... so it is not tracking it in any way... I realized an hour after the purchase because I was running errands. 

The purchase is recorded in the PT log, right there in black and white...

I used hot config on the GUI to set the price for the pair, and still it will not show up. I restarted PT and Feeder. It will not find the pair. The pair is not in my excluded pairs.  

I set a manual sell in Binance to get rid of it at a minimal profit, but the window is gone... and I can't DCA the pair if it is not in being tracked by PT.

This is a small problem since I caught it, but the HUGE red flag is for how many more pairs did this happy to? I need to be able to trust PT to do what it is supposed to do with my funds.

Does anyone have any insight on the missing pairs?

**Comment by commandocrypto** [comment]
It just did it again... Bought two different pairs within a minute of each other. One is in the GUI and one is not. What is going on??

**Comment by commandocrypto** [comment]
Now the other pair that PT bought, the one that was visible, has dropped from the GUI. Not sure if this is a PT glitch or a Feeder glitch... 

I am shutting it down until I can't figure out what is going on. Got a rogue bot here...

**Comment by taniman** [comment]
Is this not a dust problem? Are you not maybe buying dust or something similar? send your log

**Comment by bQvle** [comment]
Same problem for me
https://github.com/taniman/profit-trailer/issues/701

Also it went on a buying frenzy and spend my entire balance on two losing pairs. even though the GUI only sais it DCAed once and twice.

Pairs
![image](https://user-images.githubusercontent.com/12952595/35007931-4890c234-fafb-11e7-9e1d-60db42018426.png)


MDA Binance log
![image](https://user-images.githubusercontent.com/12952595/35007927-4142db34-fafb-11e7-8392-0198be19fca6.png)

ELF Binance log
![image](https://user-images.githubusercontent.com/12952595/35007962-67427f4c-fafb-11e7-81c8-acbc25b11afd.png)


Why is everything Expired? maybe thats whats messing with the bot?

**Comment by taniman** [comment]
@bQvle  Missing sales in the lgos log. can happen and will not be looked at currently. Always look at the exchange for your actual sales. The slaes log is just a reference.

Expired orders are not filled orders. So look at your trade history because I feel you are confusing things. 
Als sent you log file cause that will tell us what the bot actually bought

**Comment by commandocrypto** [comment]
Just turned on the bot again, and within 10 hours, I have a purchase that is not being tracked.

**Comment by BaliDog** [comment]
Hello, this may be the wrong place, but ... I sent soem BTG to Binance in order for PT and PT Feeder to pick it up and run with it. The BTG was seen, however I need to manually enter the price for it. I have looked and looked and can find nowhere in Binance, PT or PT Feeder where we may manually adjust the bought price for a coin.  Can you advise where I may find this? Many thanks!

**Comment by commandocrypto** [comment]
Use hot config:

https://wiki.profittrailer.io/doku.php/hotconfig

**Comment by commandocrypto** [comment]
What is BTG? You mean BTC?

**Comment by BaliDog** [comment]
Bitcoin Gold. And thanks very much. Hotconfig worked a treat. Cheers, and have a great day. :-)
