### ISSUE TITLE
Make the settings less confusing and more consistent. 

### ISSUE THREAD

**Issue by Utone** [taniman/profit-trailer#712]
For example this had me puzzled for a while as in the default config: The only sell strategy given is a very confusing GAIN sell strategy formatted like this:

ALL_sell_strategy = GAIN
**ALL_sell_value = 1**  (what of min profit is 1.25 or this set to 0.9? catch my 22?)
**ALL_min_profit = 1** (wiki enlightens us with the slightly hidden knowledge, to the greater part of PT community that this is wrong) (perhaps also because you provide this without a HIGGBB config??)
**ALL_trailing_profit = 0.5** pretty high in my personal config but i'm not running something like
ALL_max_cost_percentage = 1
ALL_max_trading_pairs = 15 where i can afford 7 levels of DCA while it misses sells because the high trail fires back on you..)

After combing trough the wiki for some answers to these catch 22 like settings I encounter from people most likely because of this very bad starting point

From the wiki:
ALL_sell_value = 1
The strategy sell value. Meaning what triggers a sell. 
Pretty straightforward right?...As the chosen word value implies, this can be anything and is used for different 'values' across the settings. And.. it does..

For GAIN: 
ALL_sell_value = is the profit % over the bought price. (Why not use  ALL_min_profit ???)

For HIGHBB:
Valid Values from -100 to 100. (Jesus.., Have you ever worked with -100 BB settings or anything less than -30? It just confuses people)

Default is 0. Lower is more aggressive. Higher is more conservative.  
(Why not specify positive and negative 'values' instead of high or low, I get -10 is lower than 30 but the target is higher) 
Represents the percentage over the high BB line. 0 is equal to the high BB line. 50 is 50% between the high and low BB, or the middle line. 100 is the Low BB line, or 100% from the high BB line. -10 is 10% ABOVE the high BB line. (which is not unusual and makes this a bit less prone to misinterpretation)

Here comes the final AHA that's why this shit had me confused for a month punchline.
(always read the small print folks;)
ALL_min_profit = 1
Valid Values: Decimal numbers greater than or equal to 0.
Use the value to ensure you have reached a suitable profit level _when using HIGHBB as a sell strategy._ **Not used with GAIN strategy.** 

WHY NOT? You keep the incorrect ALL_min_profit = 1 in gain and remove that ALL_sell_value 
(provide helpful #comments in the config perhaps too..)

At least change this to something like this:

-----GAIN SETTINGS---------
 ALL_sell_strategy = GAIN
 ALL_sell_value = 0.75
 ALL_trailing_profit = 0.24
 
-hashed out # in front of text create huge bold text and in the context of this post was like I was: 
# SHOUTING THEM AT YOU... **LMAO...**
 ----HIGHBB SETTINGS--------
ALL_sell_strategy =  HIGHBB
ALL_sell_value = 25
ALL_min_profit = 1
ALL_trailing_profit = 0.25

Much clearer to all would be:
-----GAIN SETTINGS---------
 ALL_sell_strategy = GAIN
 ALL_min_profit = = 0.75
 ALL_trailing_profit = 0.24
 
----HIGHBB SETTINGS--------
ALL_sell_strategy =  HIGHBB
ALL_sell_value = 25 (ALL_HIGHBB_sell= 25 is a bit much but it's pretty clear what it represents) ALL_min_profit = 1
ALL_trailing_profit = 0.25

Feel free to copy and include any of my included settings which at the moment, does not include the full wiki, but it's a start..;)

[KOBALT NITRO SETTINGS 1.5.1.zip](https://github.com/taniman/profit-trailer/files/1633254/KOBALT.NITRO.SETTINGS.1.5.1.zip)

(Pardon my tone but am irritated after finding this while looking for answers to why 'something else' happened and this little thing ticks me right off and Mr Hyde comes out to vent)
hashtag sorry;)
# sorry ;)

**Comment by taniman** [comment]
just a note. min_profit only works for BB strategies. Instead of all the comments try reading a bit more slowly.
