### ISSUE TITLE
Cant start VPS Ubuntu

### ISSUE THREAD

**Issue by spraydenis** [taniman/profit-trailer#714]
I m in a VPS located in UK . I did all the steps, but at the end, after enter the line 
 pm2 start pm2-ProfitTrailer.json
[PM2] Applying action restartProcessId on app [profit-trailer](ids: 0)
[PM2] [profit-trailer](0) ✓
┌────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name       │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ profit-trailer │ 0  │ fork │ 22037 │ online │ 0       │ 0s     │ 49% │ 3.2 MB   │ root │ disabled │
└────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘

It appears to work but when i try to see the log ( pm2 log 0 ) i cant see anything but:

[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/profit-trailer-out-0.log last 15 lines:
/root/.pm2/logs/profit-trailer-error-0.log last 15 lines:
0|profit-t |    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
0|profit-t |    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
0|profit-t |    at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)2018-01-16 04:04 +00:00:
0|profit-t |    at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
0|profit-t |    at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
0|profit-t |    at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
0|profit-t |    at java.security.AccessController.doPrivileged(Native Method)2018-01-16 04:04 +00:00:
0|profit-t |    at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
0|profit-t |    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
0|profit-t |    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
0|profit-t |    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
0|profit-t |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
0|profit-t | 2018-01-16 04:04 +00:00:   at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
0|profit-t |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
0|profit-t |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by taniman** [comment]
for support ask in the support channel
