### ISSUE TITLE
[Feature Request] Sell only mode but allow DCA for pairs already bought

### ISSUE THREAD

**Issue by antknight** [taniman/profit-trailer#716]
I want to sell everything but allow DCA so it is still a profit eventually.

**Comment by halimozturk** [comment]
when you are in sell only mode DCA still works.

**Comment by taniman** [comment]
read the wiki a bit more. This option is already available

**Comment by antknight** [comment]
OK I found it. For other looking for this:

In PAIRS.properties set ALL_sell_only_mode = true
In DCA properties set ignore_sell_only_mode = true
