### ISSUE TITLE
[Feature Request] Base Bounce Buy Strategy

### ISSUE THREAD

**Issue by nric** [taniman/profit-trailer#722]
This tool here calculates bounce lines on hour candles for every pair: https://qft.hodloo.com/
Trailing when it breaks through a base and buying on its way down (or at the return point) has a very high percentage win rate for most crypto coins. https://steemit.com/@quickfingersluc
This base break event relatively "rare" compared to low-bb or EMA and often more long-term than the built-in strategies but I would love to have a separate bot doing nothing else with higher percentage investments.

**Comment by YoJeff** [comment]
Interesting site, not on the roadmap.
