### ISSUE TITLE
[Bug] telegram report broken on v1.2.6.11 per release ver.

### ISSUE THREAD

**Issue by yesmider** [taniman/profit-trailer#723]
I used same config files between 1.2.6.10 and 1.2.6.11
Only 1.2.6.10 version,bot send message successfully.

**Comment by noothing** [comment]
Working fine on 1.2.6.11 here. Are you sure you have the right ids?

**Comment by yesmider** [comment]
yes,it work fine  on 1.2.6.10.

**Comment by taniman** [comment]
So users confirm nothing wrong with 1.2.6.11. I confirm too.
