### ISSUE TITLE
[Feature Request] max_DCA_trading_pairs setting

### ISSUE THREAD

**Issue by poempiedoem** [taniman/profit-trailer#727]
hi,
i'd like to see a max_DCA_trading_pairs setting, which would allow us to specify a max number of pairs that's in DCA.

thanks

**Comment by mrhasbean** [comment]
Yes please. This option opens up strategies not currently possible and is programmatically such a simple addition.

**Comment by cristianserban** [comment]
you can enable/disable DCA per pair but in this case you need to have in pairs.properties only the pairs you are trading

> BTC_AMP_trading_enabled = true
> BTC_AMP_trailing_profit = 0.025
> BTC_AMP_DCA_enabled = -3.6
> BTC_AMP_sell_value = 0.75
> BTC_AMP_sell_only_mode = true
