### ISSUE TITLE
Feature Request - Please show why Possible Buy Log = 0

### ISSUE THREAD

**Issue by neo302** [taniman/profit-trailer#731]
Even outputting to the console would be great as a start.  It would be greatly appreciated.

**Comment by YoJeff** [comment]
It's in the wiki.

**Comment by neo302** [comment]
I see what it says in the wiki.  The reason I'm asking for it is b/c there can be several reasons.  It is easier if the user can immediately see why there are none besides having to think of all the possible reasons such as not enough funds, max number of pairs / dca reached etc.  I'm recommending it so the app is more user friendly.
