### ISSUE TITLE
Coinmarketcap API limit breaks monitor page

### ISSUE THREAD

**Issue by imphocused** [taniman/profit-trailer#732]
The 'Monitor' page should not fail due to CMC api failures.

<img width="1432" alt="pt-cmc-error" src="https://user-images.githubusercontent.com/501310/35081334-4612a728-fbd9-11e7-9418-d1148058ff63.png">

 
I started to see the following error:

`There was an error while refreshing the data. Please check your VPS / PT connection. If your VPS / PT are fine, please have a beer and a smoke, this should fix itself.
`

Looking at the browser console, it shows

`Failed to load https://api.coinmarketcap.com/v1/ticker/?convert=usd&limit=21&_=1516247461977: No 'Access-Control-Allow-Origin'`

The URL shows:

```
Error 1015 Ray ID: 3dee99978d85585b • 2018-01-18 03:52:10 UTC
You are being rate limited
What happened?
The owner of this website (api.coinmarketcap.com) has banned you temporarily from accessing this website.
```

**Comment by djcrypto75** [comment]
This has been reported many times and fixed, will be in "soon" version.

**Comment by songxiaoxiao** [comment]
我遇到了相同的问题，可有导道友解决方案

**Comment by songxiaoxiao** [comment]
可解决了？如何解决的
