### ISSUE TITLE
[Feature Request] ALL_ / coin pair enablement of DCA settings / volume levels

### ISSUE THREAD

**Issue by Utone** [taniman/profit-trailer#733]
Would be great to be able to optimise DCA on a per coin basis.

Or more (or less;) globally for example make 3 sets of ANDERSON according to volume.

When you see a coin move sideways according to BB you set it to LOWBB value+5  instead of the coins current assigned Anderson DCA set... So it doesn't  trigger an early DCA because you typically don't run large trailing buys of say 1. ... or run into trouble with large trailing buys in the General LOWBB setting. Which is a non issue in this example.. but you'd have to set that globally now or too so it still would need a big trailing buy..

**Comment by YoJeff** [comment]
There are already several issues for variable DCA.
