### ISSUE TITLE
Why the bot didn't trail in this case?

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#734]
PT bought ADA, and it ended up in a bag now.
The log says it bought at 2018-01-17 23:31:31
So I tried to identify the time on Tradingview at 1 minute scale, and it shows like this:
![image](https://user-images.githubusercontent.com/6478474/35082744-7f0203b6-fbe9-11e7-8d7c-c5b5d93033c5.png)
it still shows red candles after that. Why didn't it continue to trail?
My buy strategy is this:
ALL_buy_strategy = LOWBB
ALL_buy_value = 10
ALL_trailing_buy = 0.25

**Comment by taniman** [comment]
I am also seeing a green candle right before that.  So most likely that's the reason
