### ISSUE TITLE
Profit trailer on for 2 days with Cyptognome's Biance settings

### ISSUE THREAD

**Issue by kalisfun** [taniman/profit-trailer#742]
How come i have 22 possible buy log, but have not made any trades yet.

THanks is going on?
<img width="981" alt="screen shot 2018-01-19 at 2 10 22 am" src="https://user-images.githubusercontent.com/35596929/35145798-f45b1556-fcbd-11e7-90f4-4dc93d94305b.png">

**Comment by elcryptocapo** [comment]
This is for bugs, not support.
https://wiki.profittrailer.io
