### ISSUE TITLE
Please set BNBBTC_bought_price

### ISSUE THREAD

**Issue by Seabhac1** [taniman/profit-trailer#743]
Can you verify what this means in Profit Trailer please?
R

**Comment by elcryptocapo** [comment]
It means that PT can't determine the price for the BNBBTC price and you need to manually set the value.

**Comment by antknight** [comment]
I have tried both hotconfig and the old method to set the BNBBTC bought price and it is still not set? Bug?

**Comment by cristianserban** [comment]
what version ?

**Comment by antknight** [comment]
v1.2.6.11

**Comment by Tank33au** [comment]
I dont know why the bot tries to calculate the price BNB if the trading is disabled. 
The average price of BNB changes everytime its spent on trading fees.
