### ISSUE TITLE
Java version check fails

### ISSUE THREAD

**Issue by cvthub** [taniman/profit-trailer#745]
Java version check fails on java: 
1.8.0_161-heroku

**Comment by chattaway** [comment]
Even the new java update triggers this on masOS

**Comment by taniman** [comment]
java 9 is not support @chattaway

**Comment by cvthub** [comment]
Will be fixed in the next realease.

**Comment by chattaway** [comment]
latest was still a new v8.

**Comment by cvthub** [comment]
@chattaway please provide the output of "java -version"

**Comment by chattaway** [comment]
8 update 161 (build 1.8.0_161-b12

**Comment by cvthub** [comment]
"1.8.0_161-b12" should work with the fix
