### ISSUE TITLE
When using ALL_buy_strategy = LOWBB Current Value in Possible Buy Log always 0.0

### ISSUE THREAD

**Issue by antknight** [taniman/profit-trailer#747]
v1.2.6.11

BINANCE USDT

![2018-01-19 16_44_30-binance usdt](https://user-images.githubusercontent.com/1137677/35161485-4cc1208a-fd38-11e7-95db-049f462a55e0.png)
![2018-01-19 16_44_00-binance usdt](https://user-images.githubusercontent.com/1137677/35161493-52025dca-fd38-11e7-9ba5-769737e4a4bd.png)

If I switch to say, EMAGAIN it works correctly:

![2018-01-19 16_47_17-binance usdt](https://user-images.githubusercontent.com/1137677/35161577-8b73ffc8-fd38-11e7-9ebd-ee5eab95d253.png)
![2018-01-19 16_47_51-binance usdt](https://user-images.githubusercontent.com/1137677/35161587-8f8cd1ca-fd38-11e7-8472-4336b8550cd4.png)

**Comment by taniman** [comment]
That's because current value is not for BB strategies.

you see that current BB & BBtrigger are all 0.000 for EMA strategy right? 
So same reason. 

BB does not display current value. BB trigger is the value that will trail
