### ISSUE TITLE
New Feature: DCA profit% Graph

### ISSUE THREAD

**Issue by gregbillings** [taniman/profit-trailer#748]
I've written some add-on code that is able to draw line-graphs of the profit% on the DCA Log view. I think it would be cool to get this integrated into the base website. See the repo here: https://github.com/gregbillings/PT_Tracker_Graph

Thanks.

**Comment by taniman** [comment]
@djcrypto75 Is this anything?

**Comment by GeoffBoyle** [comment]
+1 for this functionality, I've been using the code for the past few days and it's very useful to see a simple price trend in the gui.

**Comment by djcrypto75** [comment]
You have some screenshots to show me?

**Comment by gregbillings** [comment]
Yeah, Here you go:
https://i.imgur.com/BFPn3NU.png

**Comment by cmartin81** [comment]
Just for the record. It works only for pairs and dca, but not for pending pairs.

**Comment by merricrubiyat** [comment]
Now add a line in the middle of the graph showing your bought price and another line showing the sell price :)

**Comment by gregbillings** [comment]
@merricrubiyat Done! Head on over to the repo to grab the latest.

**Comment by djcrypto75** [comment]
Closing as it merges with our charting plan.
