### ISSUE TITLE
[Feature request]: Integrate Tulip Indicators 

### ISSUE THREAD

**Issue by yaruzo11** [taniman/profit-trailer#750]
Tulip indicators could allow users to trade based on a much wider range of indicators (over 100) compared to only the EMA/SMA/BB strategies we have now.

Second, you could also implement it in a way that users could use multiple indicators at the same time and force a buy only when say 10 different indicators match whatever settings the users set for them (like say EMACROSS with RSI over 75 and volume increased by 15% in the past hour - something along those lines).

https://tulipindicators.org/

There's also the similar http://ta-lib.org/ but The Tulip developers say it has significantly less performance for some indicators in their benchmarks, and also I saw the Gekko bot developer says TAlib doesn't work on Windows, except on Windows 10 with bash/Windows Subsystem for Linux enabled, and they are also switching to Tulip because of that:

https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html

**Comment by taniman** [comment]
Not interested in this. This will make the bot too complicated for some people.

**Comment by ansonphong** [comment]
Gekko has support for Tulip Indicators, why not use Gekko?
