### ISSUE TITLE
[Feature Request]: Integrate/Overhaul PT with Bowhead

### ISSUE THREAD

**Issue by yaruzo11** [taniman/profit-trailer#751]
The author of Bowhead describes it as a "trading bot factory," so it's not necessarily a competitor (it's open source), but a tool that maybe Profit Trailer could use to gain more functionality, especially in terms of enabling users to pick the best strategies for them. 

Bowhead is still a work in progress, it seems, but I figured at the very least Profit Trailer developers may want to take a look at the project and the author's blog posts. He has some very cool ideas there that maybe Profit Trailer could use, too. 

I especially like the idea of being able to use 20 different indicators at once (as well as high-probability candlestick patterns!) to pick the right entry and exit points in the market. However, PT would also need to develop a nice UX for that feature to make it easy to use.

If PT developers don't think allowing so many strategy configurations in PT is a good idea for their regular customers, maybe this would be a better idea for add-ons like PT Feeder?

https://github.com/joeldg/bowhead

https://medium.com/@joeldg/an-advanced-tutorial-a-new-crypto-currency-trading-bot-boilerplate-framework-e777733607ae

https://medium.com/@joeldg/lets-write-a-cryptocurrency-bot-part-2-7adf47f5a80e

https://medium.com/@joeldg/lets-write-a-cryptocurrency-bot-part-3-826d65e55184

**Comment by antknight** [comment]
My feeling is that PT doesn't need a ton of extra indicators because of the trailing profit feature. Correct me if I am wrong.

**Comment by cristianserban** [comment]
for the moment we choose to stay and enhance what we have
