### ISSUE TITLE
[feature request] please make telegram message with parameters

### ISSUE THREAD

**Issue by bwired-nl** [taniman/profit-trailer#752]
the telegram message is very limited regarding the information
please make this configurable by user
so also profit, total profit etc.
thanks

**Comment by Cryptomi** [comment]
A Dayreport message will be nice

**Comment by taniman** [comment]
well this is a trading bot, and currently I would like to concentrate on that.

**Comment by Ronanza** [comment]
@taniman Yes, it is a trading bot. And a great one! 
However, for me Telegram is the only easy way to monitor trading activity during the day (e.g. in the office). So some Parameters would be nice. The following would be great:

- BNB almost depleted

- Turn off buy notifications, display sells only

- Configure a label/custom name of the bot posting the message. I’m running several BTC bots on Binance (yes, reasons are valid 😉) and it would be cool to know from witch “BTC Binance” bot the notifications are coming from.

Thanks for considering this request...

**Comment by Ronanza** [comment]
@taniman Never mind. Just found out about PT Notifications. Great stuff. 
Sorry to bother you 😉
