### ISSUE TITLE
[Feature Request] Accumulate a coin

### ISSUE THREAD

**Issue by Tjosy** [taniman/profit-trailer#753]
It would be awesome to have PT help laddering accumulation buys. 

I am not sure if this would work, but what if a variable sell percentage for a coin was added so that when a sell event was triggered, only a percentage of the total amount in the bags was sold. 

For example...

XRPETH_accumulate = 50 

.... would hold back 50% of the total amount of XRP originally purchased via our buy strategy rather than sell the entire lot as usual.

**Comment by malfusion** [comment]
+1. What's the duplicate issue for this? And what is its status?  I haven't been able to find it.
