### ISSUE TITLE
[Feature Request] Sales log API/CSV

### ISSUE THREAD

**Issue by chrisek** [taniman/profit-trailer#755]
Hey, 

I have created a little tool for your PT, that is PT Tracker of sales log: 

https://docs.google.com/spreadsheets/d/1DJlREBTlrDvQMUpootwonPBTd3hkvoJf_mGHQ4kw9dU/edit?usp=sharing

For now to get data you need to copy & pasate it from Sales log, is it possible you coud give small API or unrestricted XML acces to saleslog so spreadsheet could automaticly get sales data. 

Thanks

**Comment by minerdude** [comment]
up for it
btw thanks Chrisek for this spreadsheet!

**Comment by s31teg** [comment]
Please support this request

**Comment by cryptocoyns** [comment]
Please implement this request

**Comment by Cryptomi** [comment]
That will be great

**Comment by taniman** [comment]
can you not just use /monitoring/data ?

**Comment by Helmi** [comment]
@taniman adding to the discussion we had about that. This issue is about that already. Having Key/Secret access to the API could help a lot. Everything else is hard to implement because of the cookie thing.

**Comment by YoJeff** [comment]
Or even just a key (which is just another name for a password).    If PT could simply scrape the key from a URL parameter, ala   

`/monitoring/data?key=mysupersecretkeyorpassword`

Then auto-pulling this should be trivial.

**Comment by swoopsus** [comment]
This would be great. I think almost everyone is having to manually copy the sales log every day. I am running on multiple exchanges so its a chore. I would like to be able to access any of the logs with a URL and password as suggested by YoJeff. If we can do that Excel can treat it as a data source natively, and we can build a consolidated view of all of the instances. That would be very awesome!

**Comment by cryptomail2018** [comment]
or have a allocated forder where all sales logs are held on main C drive , when different bots are running they can all log to there and consolidate all lost and missing trades , it be also nice that if we trade a manual trade on one of the exchanges then it Does come up in PT it would also be nice to have this part of the log to keep in PT as such .. same goes for initial deposit of BTC , ETH and or other coins , also incase there is a short sell or loss sale manually created as a emergency if this would be also on the log it be great as well so at the end of the day we don't need to look everywhere to find and do this all manually on a spreadsheet.
just my 2 cents :)
