### ISSUE TITLE
[Bug] Profit Calculation and Binance Fees

### ISSUE THREAD

**Issue by BritoSupreme** [taniman/profit-trailer#756]
I was going over my sales log and calculating Binance Fees and noticed the Profit(BTC), Profit %, and Sold Value were different than my calculations.  It appears PT is simply taking 0.2% off the Sold Value rather than 0.1% off of each Bought Cost and Sold Value for the Binance Fee.  
```
Using PT column headers, if B = Bought Price, S = Sold Price, A = Sold Amount, and F=0.1%, then
````
PT calculations: 
```
  Bought Cost(BC) = B*A
  Sold Value(SV) = S*A - Fees,  where Fees = 2*S*A*F
  Profit = SV - BC
  Profit% = Profit / BC
```
Should be:
```
  BC = B*A
  SV = S*A
  Fees = B*A*F + S*A*F = (B+S)*A*F  (this is where the difference comes in)
  Profit = SV - (BC + Fees)
  Profit% = Profit / (BC + Fees)  (Fees need to be added to the Cost Basis to calculate ROI correctly)
```

Recommend adding a Fees column to PT interface or just adding the Fees to the Bought Cost column.

Also, using the BNB coin for fees reduces it by half to 0.05% (for now), so is it possible to detect this or add a setting for this?

**Comment by taniman** [comment]
I am not really interested in this currently. We take by default the most amount of fee. If your BNB is used up. Binance will switch over to old fee calculation system.
So this will make the logic too difficult.
