### ISSUE TITLE
Putting me in more pairs than I have set in Pairs.Prop 

### ISSUE THREAD

**Issue by Kickinbird** [taniman/profit-trailer#757]
So... It currently has me in 8 pairs and 2 DCA, however, My ALL_max_trading_pairs = = 4

This seems like a serious bug that should not occur considering the cost we all paid for this program. 

Please help!

feel free to email me at kickinbird7@gmail.com

**Comment by Stein276** [comment]
Dumb question but do you have,

ALL_max_trading_pairs = = 4 or ALL_max_trading_pairs = 4 in your pairs file?

Should only have 1 equals sign.

**Comment by Kickinbird** [comment]
I actually figured out the issue. I don’t know what caused it but I
restarted my computer reextraccted the files folder and then setup my
settings from scratch and everything is fine now. Thank you for your time!

**Comment by Stein276** [comment]
No problem, glad it's all working for you.
