### ISSUE TITLE
[Feature Request] Sales Log JSon Feed

### ISSUE THREAD

**Issue by cryptocoyns** [taniman/profit-trailer#758]
Would it be possible to get a JSon feed from ProfitTrailer for the SalesLog?

Something like:  http://localhost:8081/sales-log/feeds?type=json

The data appears to already be sitting in the ProfitTrailerData.Json file and just sending it in that format is fine. A live JSon feed via a URL would be brilliant we could then import it directly into spreadsheets or other apps for doing analytics on the data.

Having the parameter Type would allow you later to do CSV or XML feeds if you wanted to add that as a feature of ProfitTrailer.

**Comment by gregbillings** [comment]
You can just directly hit the data call and get exactly what you're looking for:
 http://localhost:8081/monitoring/data

**Comment by cryptocoyns** [comment]
Excellent 👍

**Comment by dimmyr** [comment]
How would you process the password for a programmatic call to get json data?
