### ISSUE TITLE
Help | Bot Trading only .02BTC

### ISSUE THREAD

**Issue by freerosey** [taniman/profit-trailer#759]
I cant tell if the image i posted will be presented to you to see.  I have .4 BTC set a buy % limit at 25% but bot only trading .02BTC

<img width="590" alt="screen shot 2018-01-20 at 1 00 16 am" src="https://user-images.githubusercontent.com/35621663/35180575-4c39a120-fd81-11e7-8110-230581b94af5.png">

DCA Properties
enabled = true
max_cost = 0
max_buy_times = 5

buy_strategy = ANDERSON
buy_value = DOUBLEDOWN
buy_trigger_1 = -3.5
buy_trigger_2 = -5.5
buy_trigger_3 = -7.5
buy_trigger_4 = -9.5
buy_trigger_5 = -12.5
trailing_buy = 0.0777

sell_strategy = GAIN
sell_value = .86
trailing_profit = 0.15
stop_loss_trigger = 0

ignore_sell_only_mode = TRUE
max_buy_spread = 1
ALL_min_buy_balance_percentage = 25

pending_order_wait_time = 0

Pairs
MARKET = BTC

ALL_trading_enabled = true
ALL_enabled_pairs = ALL
ALL_DCA_enabled = true

ALL_max_cost = 0.0025
ALL_min_buy_balance_percentage = 25
ALL_min_buy_balance = 0
ALL_min_buy_volume = 400
ALL_min_buy_price = 0.0005
ALL_max_trading_pairs = 6
ALL_max_buy_spread = 0.65

ALL_buy_strategy = EMAGAIN
ALL_buy_value = -0.49
ALL_trailing_buy = 0.35

ALL_sell_strategy = GAIN
ALL_sell_value = 0.89
ALL_trailing_profit = 0.144

All_stop_loss_trigger = 0
ALL_panic_sell_enabled = false

ALL_DCA_enabled = -1.5

ALL_sell_only_mode = false

**Comment by taniman** [comment]
Please ask for support in the support channel. This is for real bugs
