### ISSUE TITLE
[Feature Request] Parse environment variables in property files

### ISSUE THREAD

**Issue by alexsante** [taniman/profit-trailer#760]
I would like the ability to use environment variables in my property files.  For example in `application.properties`, it would be great to use an environment variable `${PT-LICENSE}`.

```
#Put here your licensed API key
default_apiKey = ${PT-LICENSE}
default_apiSecret = ${PT-SECRET}
```

**Comment by cristianserban** [comment]
you cab create a script on your env to modify those settings as you wish and that start the bot

....
