### ISSUE TITLE
[Feature Request] Option for ALL_max_cost to be % of TCV - Compounding profit

### ISSUE THREAD

**Issue by antknight** [taniman/profit-trailer#761]
I am trying to think of a way for the bot to automatically compound profit.

If each day I make 2%, then I need to manually add 2% to my ALL_max_cost to realise compounding profit, right?

So how about ALL_max_cost is a percentage of TCV? From the wiki: 'This amount is used for EACH purchase.' Therefore each day it will be using 2% more.

I see you have ALL_max_cost_percentage but the wiki explains that that is:
 'Indicate % of total current value (TCV) of account we will use to buy. This is useful when your balance changes frequently and you want to keep a minimum balance. ' 

Now, is that in total or for EACH purchase like ALL_max_cost? As you also have ALL_min_buy_balance_percentage I imagine it is for EACH purchase.

If ALL_max_cost_percentage _is_ used for EACH buy, that is great, I can use that and it will effectively compound profit? If so perhaps update the wiki to reflect that.

Thanks

**Comment by armcbride12** [comment]
@antknight - I agree with you completely.

**Comment by taniman** [comment]
It is for each buy. I do not see where the wiki is confusing in this?

**Comment by antknight** [comment]
In the wiki for ALL_max_cost_percentage simply add:
_This amount is used for EACH purchase._
