### ISSUE TITLE
Binance - Bot is buying to much on DCA

### ISSUE THREAD

**Issue by wuschew** [taniman/profit-trailer#762]
Hi,

![binance-dca](https://user-images.githubusercontent.com/34742856/35183610-7ff1acde-fde9-11e7-9dec-6819fc38c24d.jpeg)

ALL_max_cost = 0.028

As u can see the first row is the first buy of the bot, but then for any reason the bot is buying in DCA to much and twice (row 2&3), that becomes worse, because from that point on my bot is using 0.14 for the next DCA and so on, finally my total at DCA(5) is now 3.7 ETH instead of normal calculated DCA(5) round about 0.7 ETH.

I expected this not the first time on Binance, that the bot is buying more than necessary on the DCA.

Please checkit out.

Thanks a lot
BR
Ives

**Comment by taniman** [comment]
please provide me with your log. I do not think that it's the same bot buying all this.

**Comment by wuschew** [comment]
ups, i checked the log and u are right, that was a manual buy, sorry

2018-01-20 22:05 GMT+01:00 taniman <notifications@github.com>:
