### ISSUE TITLE
Trailing Profit not working correctly?

### ISSUE THREAD

**Issue by CarlJo** [taniman/profit-trailer#763]
Hi everyone.  I am new to Profit Trailer having a problem with the trailing profit.  I have read the Wiki several times but I do no understand why the bot is not selling my trades on price retractions.  One of my trades the profit trigger hit 4.46%, but did not sell until the profit retracted back down to 1.65%.  The other one I had, the trigger% reached 2.23% but did not sell until it retracted back down to 1.25%,  I stopped the bot after these two trades, so these are currently the only two trades I have. Can someone explain the hows or why's of this?

These are my settings:

ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_min_profit = 1
ALL_trailing_profit = 0.25

Thanks,
Carl

**Comment by taniman** [comment]
Please ask this in support. this is not an issue to bel logged
