### ISSUE TITLE
GUI on mobile devices

### ISSUE THREAD

**Issue by Tank33au** [taniman/profit-trailer#764]
We really need to be able to see the last time the bot had a heartbeat on the mobile devices.
Where it is showing the current version, you need to replace it with the heartbeat information.

Version no is already been shown in the box after the profit today. so I dont know why its repeated at the bottom of the monitoring screen. 

Please make it show the heartbeat, this is the only way we can be sure that the bot is running properly without logging onto VPS or home computer with a remote access.

I had a few instances when the bot was dead for a few hours, GUI seemed to be updating but the bot didn't have a heartbeat for many hours.

If you dont want to utilise the telegram for error reporting, this would save us the downtime.

Thanks.

**Comment by taniman** [comment]
Notifications will be added in next release on the monitoring page

you bot lost heartbeats on bittrex? or binance?
