### ISSUE TITLE
Profit Last Week wrong value

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#765]
I just started the bot from scratch on Binance on ETH yesterday (Saturday), and the same day, the Profit Last Week value was the same as the Profit Today. It should have been showing zero.
Now, since is Sunday, after 12AM, it shows the same as Profit Yesterday. See screenshot attached.
![image](https://user-images.githubusercontent.com/6478474/35191131-9dd0d624-fe40-11e7-9d69-3272f812bd45.png)

**Comment by taniman** [comment]
Profit last week, is a wrong name, it's actually profit last 7 days. So this is correct.

**Comment by nstefi** [comment]
I think you should change the name then, because in my mind last week is not the current week.
