### ISSUE TITLE
[Feature request] New trailing options

### ISSUE THREAD

**Issue by Zombato** [taniman/profit-trailer#766]
I think it would be nice to have two additional trailing options in PT:

**1) Trailing Rebound Count**

i.e. ALL_trailing_rebound_count = 1

It would be useful for both buy and sell modes. It means that if the trailing_profit set to 0.5, in example, and rebound_count set to 1 (0 by default, current state), the first price rebound will be ignored and trailing will continue. In many cases small rebounds stop us from getting more profit or better buy price due to small price changes either ways. If set to 3, in example, price drops will be ignored 3 times.

**2) Separate trailing percentage for dropping trailing_profit**

In example ALL_trailing_profit_drop = 1

Serves the same target of increasing profits. Allows to set a separate (usually larger) percentage for sale trailer, which will help ignore small rebounds while price rises overall.

Say, we have ALL_trailing_profit = 0.5 and ALL_trailing_profit_drop = 1

Then PT will trail the price with 0.5% steps, but won't sell if the trailing price drop doesn't exceed 1% (and not the same 0.5% as of now).

**Comment by Tank33au** [comment]
I really hope the trailing value to be dynamic according to what we gained already.

For example,
If we had a sell value = 1 and profit % went to 2, I am sure ppl wouldnt mind risking 0.5% to gain more.
And if the profit went to 5%, we can risk 2% of that to gain higher profit and so on.

**Comment by keithofaptos** [comment]
+1
yes a "trailing stop ,stop limit" would be amazing.

**Comment by angelsomar** [comment]
Something like that

https://github.com/taniman/profit-trailer/issues/289

**Comment by taniman** [comment]
Being worked on + smart trailing
