### ISSUE TITLE
[ Feature Request ] Easier protection against P & D

### ISSUE THREAD

**Issue by jcdesigndesk** [taniman/profit-trailer#767]
New property in pairs for minimum market cap, or perhaps limit to top XX coins from coinmarketcap.com

**Comment by cristianserban** [comment]
please check [https://wiki.profittrailer.io/doku.php/pump_and_dump_protection_strategies](url)

also [https://wiki.profittrailer.io/doku.php/pairs.properties](url) 

you can setup also min_volume for selecting pairs..
