### ISSUE TITLE
[Bug] Profit calculation on BNB market

### ISSUE THREAD

**Issue by lars974** [taniman/profit-trailer#768]
Hi,

looks like there's a problem with the eq. USD value of the profit made on my BNB bot.

Example for today's profit : 0.01924820 * 14 = 0.27$ and not 1.68$

![capture](https://user-images.githubusercontent.com/35058348/35205933-7f23bbc0-ff52-11e7-96a2-6bca13d2be05.JPG)

**Comment by Tank33au** [comment]
I reckon you guys gotta give the dev team a break and stop complaining about stuff that doesnt affect your money or the operation of the bot.

I wish the dev team just get rid of the US $ figures. At the end of the day, you are trading to accumulate BNB. $ only matters when you decide to sell out your BNB.

**Comment by lars974** [comment]
Hi Tank,

I don't complain at all. I notice there's a bug and I report it. 
I don't think there's any emergency in fixing this. I just do my best to give a little help when I see something's wrong.

I perfectly know the incredible the dev team does on PT.

Have a wonderful day.
