### ISSUE TITLE
Suggest to have an extra parameter to work with ALL_trailing_buy parameter

### ISSUE THREAD

**Issue by dragonforce2010** [taniman/profit-trailer#769]
Hi, PT awesome developers,

I'd like to suggest to have an extra parameter to work with ALL_trailing_buy parameter.

Why?
- I like ALL_trailing_buy parameter, but quite often when I buy it, the price is still dropping because the selling force is bigger than buying force on the order book chart. 

Suggestion
- I was thinking if we have an extra parameter to specify buy force must bigger than sell force, only that happens and ALL_trailing_buy condition satisfies, then we will make a buy order.

**Comment by cristianserban** [comment]
please check https://github.com/taniman/profit-trailer/issues/766
