### ISSUE TITLE
max_cost problem and minbuybalance problem

### ISSUE THREAD

**Issue by Azizg** [taniman/profit-trailer#770]
i tried pt and i liked it so much after i saw a videos with pt feeder i wanted to try it also. i set up everything for binance and it was actually working until one day its tarted to write in log "cannot buy XXXX increasy max_cost at least to 0.002. My max cost is used as percentage and its more than 0,002 BTC as i got 0,01 BTC on my account in binance so i tried EVERYTHING to set it up and i just cant. im very angry about it beacuse it was all working until something that i cannot understand ruined everything. please help me to setup my PT and PTF. ty

**Comment by YoJeff** [comment]
Please use regular support channels -- this is for bugs only.

**Comment by yobimania** [comment]
I'm having the same issue. My work around at the moment is to manually change the ALL_max_cost in the pairs.properties file however this kind of defeats the purpose of a bot haha. 

I'm curious to see if this issue is caused by using percentages.
