### ISSUE TITLE
DCA Partially filled buy order issue (Binance)

### ISSUE THREAD

**Issue by jbhitman** [taniman/profit-trailer#773]
I've been noticing more and more now that I am getting Partially filled DCA orders.  The problem is 1. The bot doesn't calculate the needed amount for another order to complete the DCA and place it, and 2. even partial orders bump up the DCA trigger to the next level.  So if I have 5 levels and it only partially filled the level 5th DCA order, even with a tiny amount, the benefit of DCA'ing is almost completely negated, especially if it was only able to fill, say 5% of the DCA order.  Can it not be possible for the bot to see that the previous DCA buy order was expired and partially filled, and calculate the needed amount it needs to buy to complete the DCA fully? Is there an option somewhere, that I'm missing that forces the bot to read the orderbook and ensure that there's enough volume in them to fill the DCA buy order at the needed pricepoint?

**Comment by Tank33au** [comment]
Yes you are missing the option.
buy_available_volume_trigger = 150
https://wiki.profittrailer.io/doku.php/dca.properties
