### ISSUE TITLE
Both save files were damaged

### ISSUE THREAD

**Issue by Gitulu** [taniman/profit-trailer#774]
Hello guys,

I have received on my two bots the same message today.

Message: "Both save files were damaged, If you have a backup somewhere please use that or just delete ProfitTrailerData.json".

Bot: 1.2.6.11
Exchange: Both on Binance
Newest Java Version, Windows 10 64 Bit
Log Attached
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1652958/ProfitTrailer.log)

Please let me know if you need anything else.

Thank you

**Comment by Legedric** [comment]
Did your machine you run the bot on got rebooted unexpected?

This happened to me when my VPS provider rebooted the machine so the bot did not get stopped properly.

Since then I am running a backup solution moving my data files to a backup location every 10 minutes :)

**Comment by YoJeff** [comment]
Something is wrong with your environment.
