### ISSUE TITLE
[Request] - Keep LT coins in exchange without excluding future trades

### ISSUE THREAD

**Issue by nate5532** [taniman/profit-trailer#775]
Hello - 

I've been running PT for about a week and have learned a ton.  

Currently, all of my crypto is wrapped up in the Binance exchange (small amount - ~$3k).  

I'm holding 6 coins in that exchange that are LT holds., and I'm currently excluding those in my pairs.cfg.  

My request would be to allow the bot to trade all coins, but allow me to **set a threshold** that would trade/sell above and beyond my initial LT investment.  

For example - lets say I have 12k TRX that I purchased and want to keep.  If the bot wants to, I'd like it to allow it buy more and sell **in addition to my 12k TRX,** but not sell my LT investment.

**Comment by cristianserban** [comment]
at the moment the only way to buy more is to do it manually once you deselect the pair from trading...
