### ISSUE TITLE
DCA partially filled sell order issue

### ISSUE THREAD

**Issue by BritoSupreme** [taniman/profit-trailer#777]
PT ended up selling this coin at a net loss because for some reason it dropped the average bought price  (0.00055661 to 0.00054567) after the first partially filled sell order.  The next two trades were at a loss since it thought it was still at a profit.
```
# | Date              | Coin | Sell Strat | Bought Price | Sold Price | Profit% | Trigger% | Profit BTC | Sold Amount | Bought Cost | Sold Value
- | 23.01.2018 01:57 (0D) | BQXBTC | GAIN | 0.00054567(4) | 0.00055471 | 1.46 | 2.59 | 0.00009522 ($0.98) | 12 | 0.00654799 | 0.00664321
- | 23.01.2018 01:57 (0D) | BQXBTC | GAIN | 0.00054567(4) | 0.00055408 | 1.34 | 2.59 | 0.00117629 ($12.09) | 161 | 0.08785218 | 0.08902847
- | 23.01.2018 01:54 (0D) | BQXBTC | GAIN | 0.00055661(4) | 0.00056296 | 0.94 | 2.19 | 0.00018271 ($1.88) | 35 | 0.01948148 | 0.01966419
```

I found this in the log in between those trades
`2018-01-23 01:54:14 INFO AverageCalculator - Please set BQXBTC_bought_price`
Did it lose the average bought price and then miscalculate it?

**Comment by merricrubiyat** [comment]
Had this happen to me too. Here is PT doing a partial sell, then miscalculating the bought_cost on the second sell. In my case I luckily ended up with a net gain.

https://cdn.discordapp.com/attachments/373691609486852098/403236377069879297/unknown.png

Here is my binance log, where it bought 4 times (3 double downs, which agrees with the ```(3)``` in above pic)
![image](https://user-images.githubusercontent.com/35739228/35291720-0e2d5224-0023-11e8-894b-cc0938f561c8.png)

**Comment by gregbillings** [comment]
I have a similar issue where it copied over the bought price from the previous time and used that as the bought price for this time... Then it said I got a 50% profit, when in-fact I lost btc from the sale.
![image](https://user-images.githubusercontent.com/5951731/35319755-daeb94fa-00a6-11e8-93e4-2990027a1b76.png)

Here's my Binance logs for these transactions The last time it bought before the mis-calculation, it partially filled the buy order:
![image](https://user-images.githubusercontent.com/5951731/35319790-02448746-00a7-11e8-91ba-731c6d0fef2e.png)

And my profittrailer log from the same time.
[log.txt](https://github.com/taniman/profit-trailer/files/1658958/log.txt)

**Comment by yunier2002** [comment]
I have been having the same issues for days now, I've sent lots of screenshots and data to Mario & SgtBatten on your discord channel. 

I know exactly why the bug is happening and included it in my information to you guys. I'll be testing and see if it was fixed in this new version 12. Contact me if more info is needed

**Comment by taniman** [comment]
@yunier2002 let me know if it's still happening with the new version. if So I will need your logs and I will look into fixing this the next release. Cause up until know I was certain is was being caused because of the binance throttle

**Comment by yunier2002** [comment]
@taniman It looks like it's working correctly on this new 1.2.6.12 version I'm running. See screenshot of multiple DCA sells with the correct bought price.

If nothing was changed code-wise please make sure fixing the Binance throttle/ban issues don't bring this bug back.

![image](https://user-images.githubusercontent.com/35727467/35368699-941618e6-0152-11e8-9c90-858c86c613c0.png)
