### ISSUE TITLE
Feature Request - Add Max Cost Stepping

### ISSUE THREAD

**Issue by 4Ykw** [taniman/profit-trailer#778]
Hi there,

I have been doing something manually that can very well work as a feature here.

**Example (configured values):**
Total Balance: 1 ETH
Configured all_max_cost = 0.1

**Proposed modifiers (for example):**
Balance Stepping (TRIGGER): 50% Used

**Reaction:**
Once my balance goes to 0.5 ETH, all_max_cost will be modified to 0.05 ETH. If my balance goes further down to 0.25 ETH then my all_max_cost would be 0.025 ETH.

**Vision:**
Using this max cost modifier low balance users won't suffer as much as when having full balance. Effectively reducing the number of bag size under low balance.

Cheers

**Comment by cristianserban** [comment]
Hi,

there is this which is exactly what you proposed imo: 
please check [https://wiki.profittrailer.io/doku.php/pairs.properties](url)
```
ALL_max_cost_percentage = 2
Valid Values: Decimal value greater or equal to 0. 
Indicate % of total current value (TCV) of account we will use to buy 
This property only works if ALL_max_cost = 0. This is useful when your balance changes frequently and you want to keep a minimum balance. 
```

**Comment by 4Ykw** [comment]
This was not what I was trying to say. But I will try to get more intel from discord channel... and if necessary come back here with a better example.
