### ISSUE TITLE
technical : Whale detect .

### ISSUE THREAD

**Issue by dechut** [taniman/profit-trailer#78]
hi everyone .

sometime , whale keep dump a coin to lower price by using an very big sell order like this : 
![image](https://user-images.githubusercontent.com/31846587/30629622-03dc245e-9e07-11e7-9fcd-9a6319572036.png)

price in chart :

![image](https://user-images.githubusercontent.com/31846587/30629583-d875c662-9e06-11e7-92de-07b1677213b2.png)

could we check queue order and found this ?

if big whale in sell , then dont buy .

**Comment by keithofaptos** [comment]
+1

**Comment by Mikeeetrue** [comment]
probably buy, but after whale has sold everything and price has dropped

**Comment by taniman** [comment]
Initial version added to 2.1.0
