### ISSUE TITLE
Bot takes 5 minutes to recalculate bought_price

### ISSUE THREAD

**Issue by merricrubiyat** [taniman/profit-trailer#780]
On binance I have dust in my account. Most buys end up confusing the bot because of existing dust, and it ending up with more of the coin than it bought. It eventually fixes itself but takes 5 minutes. (Of course I could fix it manually but I'm not at the keyboard) A lot can happen in 5 minutes and it surely has the info needed to fix it within seconds. Please fix whatever is causing it to take so long.

**Comment by taniman** [comment]
you have been busy with creating issues it seems. WE can go faster and get banned. Or go slow and not get banned by binance. 
The next release will be faster than current release
