### ISSUE TITLE
Change log entries to mention partial and expired transactions

### ISSUE THREAD

**Issue by merricrubiyat** [taniman/profit-trailer#781]
Right now we see ```Sell order for VIBEBTC sold amount 83.000000 for price 0.000094 -- {"symbol":"VIBEBTC"...,"origQty":"83.00000000","executedQty":"0.00000000","status":"EXPIRED",...} ``` -- since you have the json response at that time you can easily parse out the status and whether ```origQty``` and ```executedQty``` are the same and put different log messages, so users don't have to visually parse flat json responses in order to understand what the bot's doing.

**Comment by taniman** [comment]
The logs are not meant for the user to parse or not. So they will not be enhanced
