### ISSUE TITLE
Make bot remember dust in account

### ISSUE THREAD

**Issue by merricrubiyat** [taniman/profit-trailer#782]
Bot should not get confused by dust when it buys. It should remember how much dust is in the account and expect that. It should not need to recalculate.

**Comment by taniman** [comment]
The bot already does this. Recalculation is always needed when a value is biger than dust

**Comment by merricrubiyat** [comment]
If it already remembers the amount of dust in the account and the purchase price of the dust, why does it need to take 5 minutes recalculating the new bought_price when it buys some of that coin?
