### ISSUE TITLE
[BUG] EMASPREAD in some instances buying when conditions are not met

### ISSUE THREAD

**Issue by ACETyr** [taniman/profit-trailer#783]
I have in several instances seen that PT buys with EMASPREAD strategy when buy conditions are not met. I have documented one such a case.

Bought LSKBTC on 22.1.2018 at 19:07 for 0.00192190 (see screenshot)
![bildschirmfoto 2018-01-22 um 23 14 09](https://user-images.githubusercontent.com/35745290/35301572-2feea4da-008c-11e8-97d4-d235de492bd2.png)

Buy Strategy is EMASPREAD with ALL_buy_value = -0.29
Indicators are set to:
EMA_period = 300
EMA_1 = 24
EMA_2 = 3

I verified EMA Settings on Binance are adjusted accordingly and candlesize is set correctly (see Screenshots) 
![bildschirmfoto 2018-01-22 um 23 19 06](https://user-images.githubusercontent.com/35745290/35301753-b280e2a0-008c-11e8-90a2-8c0505d249b8.png)

I did measured carefully on both EMA lines at indicated buy time and calculated the spread (result -0,177) Screenshots show values)
![bildschirmfoto 2018-01-22 um 23 32 02](https://user-images.githubusercontent.com/35745290/35301823-e9e4511e-008c-11e8-89ab-41ea8133b9ff.png)
![bildschirmfoto 2018-01-22 um 23 31 33](https://user-images.githubusercontent.com/35745290/35301824-ea04f3d8-008c-11e8-944f-1825563df547.png)

ALL_buy_value = -0.29 was not met in the candle at the time where it bought nor in the candles before.

These are the outputs on the console at that time:

2018-01-22 19:07:06 INFO ProfitTrailerService - Buy order for LSKBTC -- {"symbol":"LSKBTC","orderId":4926262,"clientOrderId":"9lbRT4cg0ZkN8ROrWlNtd0","transactTime":1516644426158,"price":"0.00192190","origQty":"1.82000000","executedQty":"1.82000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
2018-01-22 19:07:12 INFO ProfitTrailerService - Get order information -- {"symbol":"LSKBTC","orderId":4926262,"clientOrderId":"9lbRT4cg0ZkN8ROrWlNtd0","price":0.00192190,"origQty":1.82000000,"executedQty":1.82000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1516644426158}
2018-01-22 19:07:12 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -- currency pair LSKBTC - BV -0.29, BVL 0.0, MTP 12, TTP 12

**Comment by YoJeff** [comment]
So... Did the ask price ever reach .0019203 ?

**Comment by DemoFreak** [comment]
Indicators.properties:
EMA_period = 900
EMA_1 = 20
EMA_2 = 5

Buy strategy:
ALL_buy_strategy = EMASPREAD
ALL_buy_value = -0.75
ALL_trailing_buy = 0.4

Log:
Jan 27 17:08:23 idefix PT_Binance[29608]: 2018-01-27 17:08:23 INFO ProfitTrailerService - Buy order for CNDBTC -- {"symbol":"CNDBTC","orderId":5432779,"clientOrderId":"D1O0SN2mJhegwSl282zt9g","transactTime":1517069305611,"price":"0.00002503","origQty":"152.00000000","executedQty":"152.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
Jan 27 17:08:30 idefix PT_Binance[29608]: 2018-01-27 17:08:30 INFO ProfitTrailerService - Get order information -- {"symbol":"CNDBTC","orderId":5432779,"clientOrderId":"D1O0SN2mJhegwSl282zt9g","price":0.00002503,"origQty":152.00000000,"executedQty":152.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1517069305611}
Jan 27 17:08:30 idefix PT_Binance[29608]: 2018-01-27 17:08:30 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -- currency pair CNDBTC - BV -0.75, BVL 0.0, MTP 40, TTP 24

![screenshot_20180127_193421](https://user-images.githubusercontent.com/9294774/35475157-ab5bc2fa-0399-11e8-8040-b533e723d5b4.png)

The spread condition of -0.75 was met the last time several hours ago (at appr. 12:40 or so), and after that the rate was more than trailing_buy 0.4 higher. Thus the trailing shouldn't have lasted until 17:08, I guess.
