### ISSUE TITLE
Historical Reporting: Daily Profit Report over time.

### ISSUE THREAD

**Issue by ironc0in** [taniman/profit-trailer#784]
Currently you can only see reporting for **Today**, **Yesterday**, and **This Week**.
We all have to keep daily profit, investment, percentage, etc on excel/google sheets.
It would be great if this could be added on in a similar tabular fashion where you can go back months and get graphs charts etc.

**Comment by SinFuego1** [comment]
Would be great aswel if you can set an option that the daily and weekly is send to telegram aswel daily at a specific time

**Comment by RunPlz** [comment]
Would this have to do with Tracker / Magic integration?
