### ISSUE TITLE
[FEATURE REQUEST] Multiple APIs for Individual Exchanges to Speed Up Data Feed

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer#785]
**Challenge:**
I recognise that the API usage restrictions determine the max speed at which the bot can respond, often resulting in missed trading opportunities.

**Suggestion:**
Wouldn't it be great if the bot could use, let's say 6 or 7 API keys to the same exchange so that the bot could have access to more frequently fed data? : )

In other words, it would successively and continuously rotate through all APIs given, so as to stay within individual API request limitations, whilst reducing the required wait time between each useable data feed by 6 or 7x.

**Benefit:**
This would mean missing less buy/sell levels, increasing the trade success rate, reducing the trade turnaround time and thus increasing potential trade opportunities in any given timeframe 

**Possible Implementation:**
Where (n) represents, let's say up to 12 API keys:

trading_apiKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
trading_apiSecret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

trading_apiKey_2x = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
trading_apiSecret_2x = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

trading_apiKey_(n)x = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
trading_apiSecret_(n)x = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Cheers.

**Comment by cristianserban** [comment]
For example Binance api is looking at requests from ips so the multiple trading key is obsolete

**Comment by omarmoss** [comment]
And what about the other exchanges?

There is always the option for using proxies as well.

trading_apiKey_(n)x = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
trading_apiSecret_(n)x = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
trading_apiProxy_(n)x = xxx.xxx.xxx.xxx:xx|username|password

I think having a faster execution time would make it well worth the extra effort.

**Comment by merricrubiyat** [comment]
Really unfortunate that these valueable requests are getting closed without discussion

**Comment by omarmoss** [comment]
New bots are coming out with this exact facility.

**Comment by mishaaltk** [comment]
I think this is a great novel idea!
I lose a lot of profit because of the 5 min lag and small margin. This would solve that.
Proxies would help.
I understand it's a big core feature request, but it could be added to the roadmap, or hire more developers to accomplish/test this task.

**Comment by merricrubiyat** [comment]
Proxies, multiple accounts (i.e. not api keys on the same account), etc. would all be viable approaches. @cristianserban did you fully consider all those options?

**Comment by omarmoss** [comment]
The other brand new bot I have seen with this option is also the same price, by the way, @cristianserban 

As well as this, they also allow unlimited exchanges and multiple buy/sell strategies that implement trailing.

 Just food for thought.

I'm not complaining, just presenting you with the competition so that you can make well-informed decisions as to the validity of the opportunity.

I fully understand and agree that it is best to make what you have robust first, but as it has been mentioned earlier, I think it would be well worth at least keeping this opportunity on the radar.

All 'opportunities' aside, I think this is a great product, so thanks all the same : )
