### ISSUE TITLE
New setting: Enable telegram sound (it is currently disabled in PT)

### ISSUE THREAD

**Issue by Legedric** [taniman/profit-trailer#788]
Hi all,

so I setup my telegram bot and everything is working as intended. However, I couldn't get my telegram bot for PT to "notify" me with sound or vibration on my Android phone.
So all I got was the notification icon in the top bar but no sound, no vibration or whatsoever, no matter how I configured the notification settings to be for the bot or telegram itself.

As I already worked with the Telegram Bot API myself, I assume that PT is setting the "disableNotification" to "true" when it is sending the message through the API.

Please allow us to enable this in PT application.properties by setting something like "telegram.disableSilentMode = true".

Thanks and regards,

Legedric

**Comment by Tank33au** [comment]
Isnt this achievable by turning the notification on on telegram?
I dont think PT is muting anything.

**Comment by cristianserban** [comment]
its mutted by default it will be configurable

**Comment by Tank33au** [comment]
I am getting telegram notification..

**Comment by cristianserban** [comment]
problem is that the notif si silenced ... not beep or vibration :D

**Comment by wood-galaxy** [comment]
thank you for this report, it's been days that I'm looking for how to have an audible notification :/

**Comment by Zvezke** [comment]
Oh, so this is being looked in to? Because I'm also not getting sound/vibrations.

**Comment by agm010391** [comment]
Hi everyone. Did anyone find a solution to this?

**Comment by Rogiervdberg1982** [comment]
Yes, used a extra product PTNotifications
