### ISSUE TITLE
Remove Hearbeats from new "Notifications" on monitoring site

### ISSUE THREAD

**Issue by Legedric** [taniman/profit-trailer#789]
Hi guys,

while I appreciate the new bell icon up there having these notifications, I find it rather annoying that it is highlighting the PT heartbeats to me every 10 minutes.

I would find it more usefull if those notifications would be limited to things that need my attention. Detecting config changes is ok, Erros etc. even more important.

But having the heartbeats in there makes ignore this rather sooner than later rendering this new feature useless after some time.

Best regards,

Legedric

**Comment by djcrypto75** [comment]
Hi,

You can always disable the notifications with server.disableNotification = true in your application file.

For now it will stay like this until we evolve the system :)

**Comment by Legedric** [comment]
I do not want to disable it entirely.
I find it very usefull, as long as it would be limited to "important" things. Heartbeats are nothing that I need to know of in my monitoring site.

But ok, you are the devs...

**Comment by taniman** [comment]
@Legedric heartbeats are the most important thing. Else we would not have added them.
They tell you that the bot is still running correctly as it seems the bot freezes on some systems.

The notification system shows latest 20 messages. There are only 3 heartbeats so If there is anything important it will show up.

**Comment by Legedric** [comment]
Ok then how about a setting to disable heartbeats from those notifications?

Don't get me wrong. But "notifications" for me always mean: "Hey, I need you attention and you need to do something!"

So if the heartbeats are always worth a notification, I will always have a red little badge up there with a number on it. When my bot is running as intended (which it is 90% of the time) then I start to ignore it because always when I click on it I see heartbeats and nothing else.

For me, Errors are the most important thing because it means the bot isn't running properly, while the heartbeats still may be alive. So THIS would need my attention, the heartbeats do generally not need my attention because they do not result in taking any action for me.

**Comment by Tank33au** [comment]
@Legedric heartbeats are the most important thing. Else we would not have added them.They tell you that the bot is still running correctly as it seems the bot freezes on some systems.The notification system shows latest 20 messages. There are only 3 heartbeats so If there is anything important it will show up.
--
But why dont you make them noticeable on mobile web?
Its more important to find out on move rather than sitting in front of computer watching the monitoring screen on a PC.

**Comment by djcrypto75** [comment]
You can see them on mobile.
I have a solution and will build something else for heartbeats :)

**Comment by jzan** [comment]
I have to agree with @Legedric that the constant notification icon diminishes the value of having the notification.  I also have to agree that the heartbeats are critical to know that the software is working properly.  Perhaps the display logic could be changed to add the heartbeats to the log but only raise the red notification icon in the event of a missed heartbeat?  I would find notification of a missed heartbeat more critical than seeing each heartbeat message individually.
