### ISSUE TITLE
Header for new USD colum in Sales Log export says "BTC

### ISSUE THREAD

**Issue by Legedric** [taniman/profit-trailer#790]
As you can see here, the heading for the column is set to BTC where it should be USD instead.

And while you are at it, please remove the brackets from this column as well so it has only the USD amount in there. Preferably even without the $ so it can be directly used in Excel or Google Spreadsheets as a floating number.

![image](https://user-images.githubusercontent.com/8308141/35331288-0255f386-0107-11e8-98ee-f2ce12e016a5.png)

Thanks and regards,

Legedric

**Comment by ruudwelten** [comment]
The monitoring page on 1.2.6.12 also shows BTC everywhere while I am trading in USDT. On the top it says 'Market: BINANCE USDT' while on the monitoring page it says 'Market: BINANCE BTC' and all profits are in BTC.

**Comment by djcrypto75** [comment]
Thank you.
I will fix for next release :)
