### ISSUE TITLE
Monitoring page on BTC market instead of USDT

### ISSUE THREAD

**Issue by ruudwelten** [taniman/profit-trailer#791]
The monitoring page in 1.2.6.12 on Binance shows BTC everywhere while I am trading in USDT. On the top it says 'Market: BINANCE USDT' while on the monitoring page it says 'Market: BINANCE BTC' and all profits are in BTC.
![screen shot 2018-01-24 at 13 14 47](https://user-images.githubusercontent.com/1828953/35331699-9d41ca2c-0108-11e8-9135-4ee755d77661.png)

**Comment by djcrypto75** [comment]
I will fix on next release :)
Thanks.

**Comment by tooraj-enayati** [comment]
Fixed in 1.2.6.14
