### ISSUE TITLE
[Feature] Allow excluding coins from max_pairs

### ISSUE THREAD

**Issue by romerotg** [taniman/profit-trailer#792]
I set BNBBTC_trading_enabled = false but don't hide it because I don't want to open binance when I want to check my BNB amount (it shows on PAIRS with Sell Strat WATCHMODE).

Problem is when my BNB is low it goes to DUST, and that makes it harder to config the bot because I set one more PAIR to keep the BNB on WATCHMODE, but when it goes to DUST, the bot will try to buy another PAIR, since BNB isn't there anymore.

**Comment by ruudwelten** [comment]
I think this will be solved when the issue #496 is implemented in version 1.2.8. Until then you could simply hide BNBBTC by setting ALL_hidden_pairs = BNBBTC. This way you can still configure PT one way.

**Comment by romerotg** [comment]
I don't see how that is going to solve this issue, since BNB is being used on taxes

**Comment by ruudwelten** [comment]
If you can save a reserve amount of a pair it would not be logical to have these appear in the Pairs Log, as these pairs would be able to be traded (just not the reserved part) it would be confusing to have the reserved amounts in the Pairs Log. So they're not in there, they won't count towards your ALL_max_trading_pairs.

**Comment by YoJeff** [comment]
The problem here isn't the coin going to dust, it's that the coin is counted toward pairs in the first place.   Ideally the pair count should only include actively trading pairs.   So either of these proposed options should work:

ALL_uncount_pairs = BNBBTC,ABCDEF,ETCETC

or perhaps

ALL_count_watchmode = true | false
 
@taniman

**Comment by YoJeff** [comment]
Purging old feature requests.   Resubmit here https://github.com/taniman/profit-trailer-enhancements/issues if there is still interest.
