### ISSUE TITLE
Error occured in OO, message Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by makeithatton** [taniman/profit-trailer#793]
Error occured in OO, message Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive How do you fix this issue

**Comment by crack00r** [comment]
same here.... only errors since update

![image](https://user-images.githubusercontent.com/6163329/35338575-90a09724-011e-11e8-8e07-cf1a5c651003.png)

**Comment by JerryLingle** [comment]
What is the FIX?!
