### ISSUE TITLE
Top bar lower opacity instead of disappearing on update

### ISSUE THREAD

**Issue by ruudwelten** [taniman/profit-trailer#794]
The top bar displaying the balance, total values and such disappears on every update. It is updated quite a bit so it keeps flashing and with a sometimes spotty connection it sometimes can be gone for quite a few seconds.

I propose this bar does not disappear entirely while updating but has its opacity lowered to about 30%. This way it's clear it is being updated but can still be read without having to go back to Monitoring.

Normal:
![screen shot 2018-01-24 at 14 08 40](https://user-images.githubusercontent.com/1828953/35337109-a20580fa-011a-11e8-8c33-072a8b2704e3.png)
Proposed:
![screen shot 2018-01-24 at 14 09 07](https://user-images.githubusercontent.com/1828953/35337118-a6ea9b28-011a-11e8-8632-8d81665fc3ed.png)

And a minor issue: On the 1.2.6.12 update I noticed the arrival of extra spaces inside the brackets of the top bar for the profits. I think this might be accidental because it's not at the closing brackets or at the BTC 24H percentage.

**Comment by djcrypto75** [comment]
Will work on a solution :)
