### ISSUE TITLE
Feature Request: Option for market sells / buys instead of limit sells / buys

### ISSUE THREAD

**Issue by machyy1** [taniman/profit-trailer#799]
I'd like to have two new options, one for buying and another for selling (separate choices).

The new options would be to issue a market sell or buy, instead of a limit sell or buy.

To be specific, this would be a primary setting, so for example I could chose to always have PT do market sells, or market buys for all transactions.

**Comment by tomastoth** [comment]
On bittrex you can not have market buying/selling using api. On Binance if you try to do a market sell/buy you will not get the price u bought/sold for in the returned message so it would be hard to calculate the actual profit.

**Comment by machyy1** [comment]
There is an API for getting recent trades from Binance.  This could be called after a market sell / buy, to get the actual price that it sold / bought at.

**Comment by tomastoth** [comment]
There is, but it will return you price 0.000000000

**Comment by machyy1** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md


Name | Type | Mandatory | Description
-- | -- | -- | --
symbol | STRING | YES |  
limit | INT | NO | Default 500; max 500.

**Comment by machyy1** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

GET /api/v1/trades

Response:
[
  {
    "id": 28457,
    "price": "4.00000100",
    "qty": "12.00000000",
    "time": 1499865549590,
    "isBuyerMaker": true,
    "isBestMatch": true
  }
]

**Comment by tomastoth** [comment]
That is response from limit order no market order. Market order returns price 0.0000

**Comment by machyy1** [comment]
In Binance, the response FULL from a market sell includes the actual prices.  It looks like this:

{
  "symbol": "BTCUSDT",
  "orderId": 28,
  "clientOrderId": "6gCrw2kRUAF9CvJDGP16IP",
  "transactTime": 1507725176595,
  "price": "0.00000000",
  "origQty": "10.00000000",
  "executedQty": "10.00000000",
  "status": "FILLED",
  "timeInForce": "GTC",
  "type": "MARKET",
  "side": "SELL",
  "fills": [
    {
      "price": "4000.00000000",
      "qty": "1.00000000",
      "commission": "4.00000000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3999.00000000",
      "qty": "5.00000000",
      "commission": "19.99500000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3998.00000000",
      "qty": "2.00000000",
      "commission": "7.99600000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3997.00000000",
      "qty": "1.00000000",
      "commission": "3.99700000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3995.00000000",
      "qty": "1.00000000",
      "commission": "3.99500000",
      "commissionAsset": "USDT"
    }
  ]
}

**Comment by machyy1** [comment]
when you make the call to sell (on binance)
there is a parameter called newOrderRespType
that is optional
if you don't set it, the response defaults to RESULT
if you set it to "FULL"
you'll get the response above

**Comment by Tank33au** [comment]
It would be equally nice if we had an option for the bot to place a pending order (limit buy/sell order at calculated price) too.

**Comment by neo302** [comment]
Yes.  We need a market order or something better.  I have watched it miss repeatedly on orders and lose a lot of the profit.

**Comment by CryptoxxG** [comment]
This would be amazing, watched too much potential profit slip into the abyss!

**Comment by mishaaltk** [comment]
I’m not sure, but I read that you cannot have limit orders set against the bot in Binance with their API. 
It IS possible on bittrex though. I could be misinformed.

**Comment by blindaim** [comment]
There's nothing like getting excited to see a pump then look and see you sold for a 2% profit haha.

**Comment by machyy1** [comment]
mishaaltk, PT is doing limit sells / buys right now.  This request is to have an option to do market sells / buys.  The API (as linked above) shows this is possible in Binance.

**Comment by empbac** [comment]
Is there a difference in fees between market and limit orders on Binance? I know that on GDAX you want limit orders because of higher fees on market orders. Any additional fees would have to be figured in too, I guess adjusting min_profit would do the job.
