### ISSUE TITLE
New feature idea: pair rise trigger

### ISSUE THREAD

**Issue by loopy83** [taniman/profit-trailer#80]
There is 24h trend in Polo Ticker...
 "percentChange":"0.08108108" means +8,11%
 So thats the trigger value we need to avoid bags.

e.g.
if percentChange_BTC_ETH > ALL_percentChange:
    BTC_ETH_sell_only_mode = true

Or sth like this...
ALL_percentChange is new config value and will be set around 10-15%. So when there was a big pump in the last 24h dont buy any coins in that pair to avoid bags because of massive falling chart after huge pump.

 It should be easy to implement, because I think you already go through the Ticker json and collect a lot of data.
 So a kind of BTC rise/drop trigger for every coin :)

**Comment by Othon3** [comment]
ALL_???_price_drop_trigger    is not  PAIR ENABLED... this feature is a must on PT...
I dont want the bot to buy coins that have gone up more than 10 in the last 12 hours..
or 20% on the last 24h

**Comment by RunPlz** [comment]
Closed?
