### ISSUE TITLE
Config/Hotconfig section corrupt - How to reinstall without data loss

### ISSUE THREAD

**Issue by mein1080p** [taniman/profit-trailer#800]
Hi,
My hotconfig & entire config section in the webUI will not commit any saves. Exiting out of the area after clicking on save multiple times raises the prompt: "Changes that you made are not saved..." 
Maybe one of my PT files are corrupt. Is there a way to reinstall this without losing my sales history/dust log etc???

**Comment by YoJeff** [comment]
This is for bugs, not support.
