### ISSUE TITLE
Asking to set bought price for BTC when bought with ETH

### ISSUE THREAD

**Issue by mikeyshann** [taniman/profit-trailer#801]
Hello,

I want to use the BTC market for the bot to trade but it asks for me to set buy price for certain coins that I bought with ETH. How am i supposed to set this? And vice versa for when I want to trade with ETH market but I bought the coins with BTC.

Thank you in advanced

**Comment by Prozacovich** [comment]
Follow this instruction:
https://wiki.profittrailer.io/doku.php/hotconfig

**Comment by StoicPerlman** [comment]
url that worked for me https://wiki.profittrailer.com/doku.php?id=hotconfig
