### ISSUE TITLE
1.2.6.12 Not displaying USDT properly

### ISSUE THREAD

**Issue by imphocused** [taniman/profit-trailer#802]
After upgrading to the lastest version, the monitoring page shows wrong values (BTC) despite being USDT

<img width="1084" alt="screen shot 2018-01-24 at 10 27 09 am" src="https://user-images.githubusercontent.com/501310/35343837-381ee8f8-00f1-11e8-901c-e8fcfd74b933.png">

**Comment by djcrypto75** [comment]
Duplicate with #791
Will be fixed on next version :)

**Comment by tooraj-enayati** [comment]
Fixed in 1.2.6.14
