### ISSUE TITLE
Binance 24 hour ticker broken  v1.2.6.12

### ISSUE THREAD

**Issue by antknight** [taniman/profit-trailer#803]
ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message Error in reading response connect timed out

 v1.2.6.12

**Comment by MijnUsername** [comment]
ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set 
ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 14

Also updated to v1.2.6.12 and running on Binance with BTC

**Comment by xyr0x** [comment]
I got the Error

ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message Error in reading response Read timed out

**Comment by dazzyb2k3** [comment]
Confirmed.  I've had the 24hr ticker lockup twice since upgrading.  Got this error in the logs:

09 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Fragmented Close Frame [CLOSE]

**Comment by cristianserban** [comment]
please send us the log file with the entire stacktrace
