### ISSUE TITLE
Binance - Ticker update - There is something wrong with your Bot, please restart

### ISSUE THREAD

**Issue by Draztik99** [taniman/profit-trailer#804]
I'm getting the error on my telegram below no matter how many times i restart. It startups immediately. I'm running 1.2.6.12

"Binance - Ticker update - There is something wrong with your Bot, please restart"

**Comment by bluefuzz** [comment]
Yes, I'm seeing this too after the latest update. Everything appears to be running fine. No errors in the log, no errors on the dashboard but the Telegram bot is telling me there is a problem with the bot. Binance only. Poloniex bot seems not to have the problem,

**Comment by Draztik99** [comment]
@bluefuzz yeah exactly on the monitor it says its fine. on Telegram its been spewing errors for 2 hours now

**Comment by inoxi** [comment]
Same issue. PT loose the Heartbeat and freezes. It loose the Normal Heartbeat. The DCA and Cache Heartbeat are OK. This is happen only on Binance. On Poloniex works just fine for me.

**Comment by taniman** [comment]
@bluefuzz @Draztik99  and what does the log files say?

**Comment by Draztik99** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1662963/ProfitTrailer.log)

heres the log

**Comment by bluefuzz** [comment]
Here's my log. It seems to have stopped spamming Telegram after it bought XRP.

[ProfitTrailer.log.zip](https://github.com/taniman/profit-trailer/files/1663306/ProfitTrailer.log.zip)

**Comment by taniman** [comment]
@inoxi TRACE shows also your secret if you dont use it correctly. So i deleted your log file from here. 

@Draztik99  I am not seeing any indication in your log that the bot was sending you error messages in telegram. I am however seeing errors connecting to binance. This might explain it. but still is not clear.

**Comment by inoxi** [comment]
@taniman thank you! Didn't know.

**Comment by Draztik99** [comment]
@taniman yeah not sure why its still spamming my telegram but the bot is still trading so i'm not sure what the issue is. i have restarted a few times and replaced .jar file as well
