### ISSUE TITLE
DCA: max_buy_spread setting not getting reflected

### ISSUE THREAD

**Issue by Tank33au** [taniman/profit-trailer#806]
Even though I have it set max_buy_spread = 2 in DCA.properties, the console says
DCAStrategyRunner - XXXXXX spread is too big - current spread:1.206000 , max spread; 1.000000
and fail to DCA the pair.

Using the latest release on Binance.
BTW, very nice job with the latest release, I love every bit of the update. no more bans and running smoothly.
Thanks.

**Comment by taniman** [comment]
Please check if you dont have a second line in DCA.properties for max_buy_spread
