### ISSUE TITLE
[FEATURE REQUEST] Failsafe based on price change

### ISSUE THREAD

**Issue by ACETyr** [taniman/profit-trailer#807]
Following my less than desireable experiences with 1.2.6.12 (Bot running but obviously not updating and acting on price changes) see ISSUE #798 i propose a basic failsafe layer for such events.

This one should be quite simple to implement:

If "Current Price" in all pairs does not change for x amount of time -> configurable action (Telegram message / restart bot / switch to SOM

**Comment by Paraoxysmal** [comment]
I really like this idea, please! +1
