### ISSUE TITLE
[BUG] 1.2.6.13 Temp Ban on Binance

### ISSUE THREAD

**Issue by ACETyr** [taniman/profit-trailer#808]
Temp ban after starting latest 1.2.6.12.
Bot initializes, announces DCA Cooldown 1 min. to log then tempban. looks like it hangs forever.
CTRL+C and console floods with:

2018-01-24 23:17:38 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.

**Comment by BritoSupreme** [comment]
I was getting these messages shortly after startup

`
2018-01-24 17:44:07 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Way too many requests; IP banned until 1516833935572. Please use the websocket for live updates to avoid bans.
`

**Comment by ashleyknowles** [comment]
Also getting this in 1.2.6.13
`0|profit-t | 2018-01-25 00:34 +00:00: 2018-01-25 00:34:26 ERROR ProfitTrailerService - Error occured in ticker, message ERROR: -1003, Way too many requests; IP banned until 1516840489345. Please use the websocket for live updates to avoid bans., result: `

**Comment by icistech** [comment]
I am getting the same issue . Opened another ticket before I found this one https://github.com/taniman/profit-trailer/issues/815

**Comment by mishaaltk** [comment]
yea, this is annoying, i keep getting banned after the .12 update! cant trade anymore.
**This is a NON working update!**
i'm downgrading until they fix it.

**Comment by icistech** [comment]
Yes, I rolled back to 1.2.6.11 and I am back up and running.  new version looks great and has some great features but they need to tweak it for the binance limitations

**Comment by nexenta81** [comment]
Confirmed here too: the **1.2.6.12** (**Latest Release**) is a **non-working release**

**Comment by jrodjared** [comment]
Having the same issues. About 4 minutes after starting, it goes into cool down mode, then

**Comment by beograd17** [comment]
Get this message after 5-6 minutes.  Have tried  using ProtonVPB to change Ip but still happens also happens on VPS Machine
2018-01-26 05:37:14 ERROR ProfitTrailerService - Tradehistory - ERROR: -1003, Way too many requests; IP banned until 1516964018975. Please use the websocket for live updates to avoid bans.

**Comment by empbac** [comment]
Same here. Same messages. The last release was meant to speed up Binance, which is good, but apparently Binance doesn't like those faster speeds, which is bad. I've downgraded as well and everything is working again.
