### ISSUE TITLE
Feature request: Include manual trades in sales log

### ISSUE THREAD

**Issue by ashleyknowles** [taniman/profit-trailer#809]
I've noticed that the pairs/pending logs will retrieve order history and calculate averages etc for pairs which aren't enabled for trading; this is great; however, if I manually trade these on the exchange (I'm using Binance), the pair disappears from PT after some time, and no sales log entry is generated. Given PT already sucks in order history to calculate averages and it knows that I have this pair in my account, would it be possible to also add a corresponding sales log entry if a manual sale is detected?

**Comment by steveoneal** [comment]
+1
Agree!

**Comment by sbarmoy** [comment]
Same! I'd think it would just pull from sells in Order History on Binance.

**Comment by taniman** [comment]
This has been asked multiple times. This is not as easy as you would think. and will not be added until we have a proper way of doing this.
