### ISSUE TITLE
New feature, multiple max_cost levels based on volume

### ISSUE THREAD

**Issue by dutchbase** [taniman/profit-trailer#81]
I would like the possibilty to set multiple levels for *_max_cost, for instance:

#volume settings:
volume_level_1 = <100
volume_level_2 = 100 - 499
volume_level_3 = 500 - 999
volume_level_4 = >1000

#btc per trade:
max_cost_level_1 = 0.001
max_cost_level_2 = 0.005
max_cost_level_3 = 0.01
max_cost_level_4 = 0.1

And there will have to be settings for DCA as well

this way you can run all pairs all the time without having to set the max_cost for each pair in you config also having to update as volume changes.

#Elroy Edited
group rule by volume
like if volume >100 then buy with bb10
volume < 100 buy with bb0

Maybe make it more generic ..

**Comment by YoJeff** [comment]
Here is a manual node script to do this, if anybody wants....

https://gist.github.com/YoJeff/385209d74e5b6b832446a6cfc3abbcfd

**Comment by dutchbase** [comment]
I was just about to post a link tho Jeff's awesome script! I love it man! (still would love to have it in PB config though)

**Comment by ThecRw** [comment]
This is a very interesting request. Would be great to have automatic max_cost for different coins based on the volume.

**Comment by taniman** [comment]
@ThecRw  you mean automagic? :)
