### ISSUE TITLE
Bought price calculation after manual sale

### ISSUE THREAD

**Issue by steveoneal** [taniman/profit-trailer#811]
Not sure if this is a bug or by design.  But If I have a pair with several purchases with DCA disabled to handle manually.  If I sell some number of other than all available, or even move some to an offline wallet, the bought price calculation is using FIFO, I think, to recalculate the cost.   It would be nice to have setting to force it to maintain the original cost.

**Comment by YoJeff** [comment]
You can override your cost if you wish.
