### ISSUE TITLE
1.2.6.12 is grilling my Raspberry

### ISSUE THREAD

**Issue by bruce133** [taniman/profit-trailer#812]
CPU maxing out, and no sign of slowing down.

Had to downgrade, which is a shame 'cause I liked the new features.

**Comment by JCUnatco** [comment]
Which Raspberry do you have?

**Comment by bruce133** [comment]
Sorry, forgot to mention that. It's a Raspberry Pi 3:

- Quad Core 1.2GHz Broadcom BCM2837 64bit CPU
- 1GB RAM

**Comment by bruce133** [comment]
Noticed the newest release had '(FIXED)' appended to its name today, so I figured I'd give it another shot. Seems to be doing a lot better now, holding around 40%. Still somewhat higher than the old version, but I reckon it should be fine.
