### ISSUE TITLE
[Feature Request] Heartbeats don't trigger notifications.

### ISSUE THREAD

**Issue by Macflurry26** [taniman/profit-trailer#814]
I like the new features that have been added but the heartbeats triggering the notification alert is driving me crazy and quickly turning notifications into something that will be routinely ignored!! lol

Alerts would be great for config changes, error messages and then buys and sells going through.

With the heart beats being routine would a status indicator be more appropriate on the monitor page or maybe only missed heartbeats triggering an alert?

The status box that displays the PT version and Market is kind of wasted and could get rid of PW, CON, SOM and SOMO as they are already displayed at the top of each page.  These could be replaced with red and green status lights for how long ago the last heartbeat was detected and this is enough to show if you need to investigate any issues.

This would stop unnecessary alerts popping up as to me alerts should only be things that require your attention to act upon or as notification of important status changes.

**Comment by Tank33au** [comment]
Yes, I second this. This will also make monitoring on mobile devices easier but so far I dont think I have to worry about heartbeat death any more.

**Comment by Legedric** [comment]
I already started an issue (and follow up discussion) about this yesterday.

See here for details:
https://github.com/taniman/profit-trailer/issues/789

However, the devs see heartbeats as being the "most important" thing there and said they won't change it...

**Comment by Macflurry26** [comment]
Ahh, ok.  They may be important but you don't need a constant reminder that they're working, just when they failed. Random analogy but imagine if they took that approach in a hospital.  All the alarms going off telling you people still have a heart beat would cause complacency and would drown out the real alerts and emergencies in the noise. Its effectively a spam alert unless you have a specific requirement for it.

**Comment by Tank33au** [comment]
My guess is when the heartbeat is dead. The bot is dead so it won't be able to send us anything.

**Comment by djcrypto75** [comment]
No need to worry, I have an idea how to change this. Will build something different.

**Comment by Legedric** [comment]
Much appreciated @djcrypto75 👍
