### ISSUE TITLE
MIssing trades in Sales Log

### ISSUE THREAD

**Issue by freerosey** [taniman/profit-trailer#818]
<img width="946" alt="screen shot 2018-01-24 at 2 24 16 pm" src="https://user-images.githubusercontent.com/35621663/35369735-1b2d64be-014f-11e8-83cb-9a2ab75da724.png">

This is not the only one trade that is missing - happened to take a screenshot of this one earlier today.  what could be the issue?

**Comment by freerosey** [comment]
totally profit from yesterday is way off 
<img width="1280" alt="screen shot 2018-01-24 at 9 55 45 pm" src="https://user-images.githubusercontent.com/35621663/35370127-93aca646-0151-11e8-8691-af6ebd91697d.png">

**Comment by omarmoss** [comment]
I had the same problem when moving the installation folder to a different location on my hard disk.
After the move, the sales log was empty.

**Comment by freerosey** [comment]
<img width="522" alt="screen shot 2018-01-25 at 3 18 59 am" src="https://user-images.githubusercontent.com/35621663/35380349-a2c361ec-017e-11e8-8b20-0f76c2c47015.png">

**Comment by freerosey** [comment]
<img width="539" alt="screen shot 2018-01-25 at 3 20 20 am" src="https://user-images.githubusercontent.com/35621663/35380381-b4287bd4-017e-11e8-93ab-5cca91e0e51f.png">

**Comment by freerosey** [comment]
<img width="518" alt="screen shot 2018-01-25 at 3 20 49 am" src="https://user-images.githubusercontent.com/35621663/35380407-c563537e-017e-11e8-9d2c-6458d46a7b55.png">

**Comment by sbarmoy** [comment]
I've had the same issue, didn't even change directories.

**Comment by cristianserban** [comment]
sales log can also be lost in case the ProfitTrailer.json or backup of this file is corrupted.. 
if you see in log that order is filled than for sure that was sold..

the sales log are only showing you the sales that the bot made, and it takes the data from the above mentioned file.

we will try to change the logic here but this has low priority....
