### ISSUE TITLE
No LOGS folder being created

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer#820]
This has been a long time issue.
A PT representative tried assisting me with it via Telegram, to no avail.

I have tried running a fresh (unzipped) version from various locations on my hard drive (in and out of cloud drives, on desktop etc).
I have tried creating the LOGS folder manually.
I have tried disabling my firewall/Anti-virus.

Nothing has facilitated the creation of a LOGS folder.

I run PT on Windows 7 with all updates.

Thanks anyone who can shed light on this mystery.

**Comment by omarmoss** [comment]
Version 1.2.6.6

**Comment by cristianserban** [comment]
do you have a error or log for this issue ?

**Comment by omarmoss** [comment]
I just explained in detail that I have NO LOGS folder and therefore cannot give you an error log.
How can I ensure that I have an error log folder for this very reason?

Thanks

**Comment by cristianserban** [comment]
but you may have one error in console of the PT even if the logs file are not created... 
Logging api sends messages to 2  outputs: console and file (log file)

**Comment by omarmoss** [comment]
Yes, I get:
ERROR ProfitTrailerService - balances - No value was returned.
This has also been the case since the begining. Perhaps something to do with the fact that the first time I run it, there were in fact no balances available in my connected exchange account.

Apart from this, everything seems to run perfectly fine apart from the odd occasion where the bought_value is slightly off and I need to hot config.

Thanks again.

**Comment by YoJeff** [comment]
Please use regular support channels.

**Comment by omarmoss** [comment]
@YoJeff what are the regular support channels for getting technical support?

**Comment by omarmoss** [comment]
The problem was with COMODO containing the jar application.
Exception added.
Exception also added to Comodo's VirusScope.

All good now.
