### ISSUE TITLE
Error Application port8081 in use

### ISSUE THREAD

**Issue by praveend12** [taniman/profit-trailer#822]
Hi,
I am a beginner just trying to setup profit trailer. I am getting port 8081 in use error.

How do i fix this?

Thanks
Prav

**Comment by ZFGyall** [comment]
You're already running software on your computer that uses port 8081.  Edit application.properties and change: 

server.port = 8081 

to 

server.port = 808x

Where x is any number 2 through 9.  If the error persists, keep changing the number until you've exhausted your options.  If you get that far, then you have a real problem.

I was surprised to see this wasn't on the Wiki under "Common Error Messages"

**Comment by YoJeff** [comment]
This is for bugs only.

**Comment by praveend12** [comment]
Thanks ZfGyall.. yes that’s right it should be in wiki
