### ISSUE TITLE
WARN DCAStrategyRunner - You can't DCA with immediateOrCancel and fillOrKill false im not using DCA

### ISSUE THREAD

**Issue by APantslessMan** [taniman/profit-trailer#825]
log gets spammed with this warning when immediateorcancel is set to false even when DCA is disabled

would like to be able to wait on buy orders that have a higher initial Cost. 0.05 BTC orders wont get immediately filled, so they are expired and PT constantly is trying to rebuy them with every one of them being Expired

**Comment by Tank33au** [comment]
Yeah. Ive seen this. I think the bot circles through DCA routine even when its disabled.

**Comment by APantslessMan** [comment]
I think the fix should be reasonably easy, an if DCA == False, no warning, else warning. the warning is constant at about 3 second intervals. it would be nice to not have my log filled with it

**Comment by Tank33au** [comment]
you ppl are wasting your time concentrating things on meaningless stuff.

**Comment by APantslessMan** [comment]
meaningless to you. but you don't have line after line of warnings in you log file. do you even get what GitHub is for? if you don't feel its important, then syfm, and go do something you find useful while the adults talk.

**Comment by taniman** [comment]
@APantslessMan I am not sure what you are doing by disabling the IoC logic. But the bot will not mark down sales correctly if this function is disabled for sales. So I can make sure the spam log goes away. But any issues created around this behaviour of you having disabled the IoC will be rejected.

The bot can work with those other options but anything that does not return an immediate sale or buy does not register by the bot.

**Comment by APantslessMan** [comment]
I have Immediate or cancel set as false for buys only. I found with an initial buy price of .05 BTC, I was getting a buy order and an immediate expiry on sub 1000 Volume coins. it would create many buy orders and instant expiry's afterwards, not actually buying anything.

![capture](https://user-images.githubusercontent.com/4605998/35431840-01ca5e52-0233-11e8-860c-6cc2df18461c.PNG)


 with it set false, the order takes a few seconds, but does complete, and PT has been picking them up and handling them properly as far as I can see. 

I'm trying to create a fast strategy for a sideways market, No DCA, Low instant sell Profit % with no trailing.
