### ISSUE TITLE
FEATURE REQUEST / BUG :  Total Current Value shouldn't include Excluded Coins

### ISSUE THREAD

**Issue by gitHappy2** [taniman/profit-trailer#826]
Hello, 

Currently, 'Total Current Value' is including HODL coins that also happen to be in the exchange, but which are not part of the PT trading coins, and have been set as Excluded Pairs, (not to be traded). 

It would be really helpful if there were 2 separate indicators

1) Total Current Value (EVERYTHING sitting in the Binance account, including excluded pairs) , and also
2) Total Current PT Value  - the value of coins   that are being used in trading ( not including excluded pairs)

Thanks, 

Jp

**Comment by CryptoxxG** [comment]
I agree with this, for tracking I always have to subtract that amount. Even have an option to "included HODL coins in TCV" or "dont include HODL coins in TCV"

**Comment by taniman** [comment]
I really disagree with this. As it will be a nightmare for most people. We already get plenty of support question Why is my TCV diffent than on the exhcange. Do you imagine how much much it will be if we exclude WATCHMODE coins?

Also you can hide watchmode coins. Why don't you want to hide them from the bot? If you hide them they will not be counted as either TCV nor max_pairs

**Comment by YoJeff** [comment]
Agreed.  This is a trading bot, not a hodl/keep track of everything bot.

**Comment by CryptoxxG** [comment]
I wasn't aware there was a way to hide coins from the bot, if this is the case than you already have a solution to this.

**Comment by gitHappy2** [comment]
Oh, that is a good point. How do you hide watch mode coins from the bot, is that a setting?
