### ISSUE TITLE
[REQUEST] Automatically buy BNB on binance if BNB balance is too low

### ISSUE THREAD

**Issue by ba32107** [taniman/profit-trailer#827]
My BNB balance got too low. Because of this, all the trade fees were paid by coin percentage and I ended up with a lot of dust.

**Comment by Tank33au** [comment]
I think we need buy only mode. To buy BNB and other HODL coins when they meet our normal buy strategy conditions.

**Comment by MijnUsername** [comment]
1. Install the Binance app on your smartphone.
2. Check your balance regulary by using the app.
3. ???
4. Profit

**Comment by Tank33au** [comment]
The purpose of the bot is to trade without human intervention or attention.

**Comment by mishaaltk** [comment]
I just put lots of BNB coins and set them not to trade in PT.
I haven't run short on them yet, but I'm keeping an eye on em. Prob will need to buy in bulk every few months. The price goes up overtime, so it's not a big risk.

**Comment by taniman** [comment]
This issue has been rejected multiple times already. We will not create a functionality based on 1 exchange only
