### ISSUE TITLE
Last two columns of DCA grid is not visible on Android

### ISSUE THREAD

**Issue by ba32107** [taniman/profit-trailer#828]
If I view the site in Android's Chrome browser, the DCA table is not fully visible. I am not able to get it to show in any way (tried landscapce + request desktop site too).

**Comment by djcrypto75** [comment]
Show me some screenshots please. 
Have you tried to zoom or move the table?

**Comment by ba32107** [comment]
I have attached three screenshots, one in normal portrait mode, one in landscape and one in landscape with desktop site enabled. I have zoomed all the way out until possible. If by 'move the table' you mean scroll, then yes I tried it, but I cannot scroll any more to the right to see the last two columns.

Thanks very much for looking into it! 

![landscape](https://user-images.githubusercontent.com/26036493/35428545-f9c5dd3e-026f-11e8-8abc-71ee7c09dd7a.jpg)
![landscape_desktop](https://user-images.githubusercontent.com/26036493/35428546-f9e2e7c6-026f-11e8-9182-b10b377f8bad.jpg)
![portrait](https://user-images.githubusercontent.com/26036493/35428547-f9fe009c-026f-11e8-80c3-1aadc96b4e83.jpg)

**Comment by djcrypto75** [comment]
If you hold your finger on the table you are not able to "drag" or "pull" it left and right?

**Comment by ba32107** [comment]
I can drag and scroll the table left or right (if not in desktop mode), but
I can't make the last two columns appear. It's as the table would end
there, it really looks and behaves as if the 'Vol' column was the last one.
In desktop mode the whole table appears as one (without the last two
columns)  and I can't scroll it (which is expected I think). If I tap and
hold, the text gets selected (also expected), not sure if this is what you
meant.

Might be a phone specific issue? I'm on Oneplus 3T, latest Oxygen OS.

On Jan 26, 2018 09:07, "dj_crypto" <notifications@github.com> wrote:

If you hold your finger on the table you are not able to "drag" or "pull"
it left and right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/taniman/profit-trailer/issues/828#issuecomment-360711251>,
or mute the thread

**Comment by djcrypto75** [comment]
I will investigate :)

**Comment by swoopsus** [comment]
Just FYI, same issue on iphone in Safari. I end up clicking the Excel link to see the columns. Thanks for all the hard work!

**Comment by djcrypto75** [comment]
Click + button in front.

**Comment by ba32107** [comment]
Thanks, it works.
