### ISSUE TITLE
more api keys for faster bot speed

### ISSUE THREAD

**Issue by sethiano** [taniman/profit-trailer#832]
Hey Devs, first off, hats off to all for a wonderful product \ community.

I know with the latest release you increased speed of the bot.

Curious as to if you guys have thought about letting us connect more API keys to allow for quicker actions of the bot.

I believe EON bot is doing this, and it seems like a good idea.

Also new features (manual 1 click DCA button in GUI would be awesome)

**Comment by djcrypto75** [comment]
The multiple API Keys is a old myth, Exchanges use IP addresses these days. 
It doesn't really matter if you attach 10 API Keys, wont change anything :)

For the buttons, its been requested many times and are on the roadmap :)
