### ISSUE TITLE
While Trading in USDT Monitor Shows Balance in BTC

### ISSUE THREAD

**Issue by tooraj-enayati** [taniman/profit-trailer#834]
In version 1.2.6.12, while trading in USDT, the top row of monitor show balance and TCV etc in BTC instead of USDT.

Version 1.2.6.12 was OK.

Please see the image.

![capture](https://user-images.githubusercontent.com/24386973/35433689-76dbe35a-02d8-11e8-9d7d-90f030053c4f.JPG)

**Comment by tooraj-enayati** [comment]
Found more errors. Please see the attached. All highlighted.
![capture1](https://user-images.githubusercontent.com/24386973/35434024-b8740e40-02d9-11e8-8d18-1498e144ca01.JPG)

**Comment by djcrypto75** [comment]
Yes its these 6. I am aware. Its been reported already. Will be fixed on next version :)

**Comment by tooraj-enayati** [comment]
Still an issue with 1.2.6.14!
