### ISSUE TITLE
REQUEST: STOP LOSS when max - % is reached

### ISSUE THREAD

**Issue by SinFuego1** [taniman/profit-trailer#835]
Hi,

Trailer does not have an automatic stoploss. During big dumps everything in PT starts to get into a loss. And when this reached like - 20%. It is far better to take the hit and use the BTC to reinvest into a new trade that potential creates a new profit. Especially when DCA already did a couple of trades to get the loss less severe. 

I would like to have an option that sets this, so that PT automatically sells the trade at a certain percentage value (configurable) then becoming a massive bag holder and a bot that doesn't trade anymore because everything is tight up in bags. There should also be a DISABLE option in case someone doesn't want to use it.

**Comment by felipeff** [comment]
It already exists. Read the wiki. All_stop_loss_triggrr

**Comment by cristianserban** [comment]
hi
please check [wiki](https://wiki.profittrailer.io/doku.php/instructions)
