### ISSUE TITLE
pair specific dca settings

### ISSUE THREAD

**Issue by sethiano** [taniman/profit-trailer#836]
Any plans on making pair specific dca settings? so pair A could dca at -1 2 3 4% and pair B could dca at -2 -4 -5 -6%

This would also allow for feeder folks to have dynamic dca trigger conditions based on their pair specific change % data.

Let me know,

Thanks!!!!!!!!

**Comment by cristianserban** [comment]
hi 
for the moment we only support dca per pair - when to go to dca 

>  BTC_BELA_DCA_enabled = -3.6

We will let you know if this goes to implementation
