### ISSUE TITLE
Will Stop-less act as panic sell?

### ISSUE THREAD

**Issue by timtaylorrr** [taniman/profit-trailer#838]
I want to use the Stop-loss function from now but I'm not quite sure whats going to happen to my positions which are currently  below this value.

I want to set the stop-loss value around -3%. Currently I have a few bags which are -5%, -10% etc.. . Does it mean when I set the stop-loss that all currents pairs which are below the stop-loss value will be sold like in the panic sell mode?

Thank you in advance.

**Comment by cristianserban** [comment]
please check [wiki ](https://wiki.profittrailer.io/doku.php/instructions)and also talk to our discord users in main channel https://discord.gg/K9a37Vh.. 
we try to keep here only bugs feature request... 
thanks for undestanding

**Comment by timtaylorrr** [comment]
The problem with this kind of messaging systems is if your question is gone no one is taking care of it.  Thats the reasing why i post this question here.
