### ISSUE TITLE
Bot seems to run OK but No updated from Binance

### ISSUE THREAD

**Issue by alexjbyron** [taniman/profit-trailer#839]
I had been running PT through Binance and had left the program running autonomously for a couple of hours. I came back to review my settings and PT seemed to be running perfectly with all the correct heart beats but in noticed that the %ages were not updating. I restarted the bot to find several DCAs in the green. Im a bit worried as I do need to leave the bot to run on its own without me being about. Is this a known issue? Please fix!

**Comment by cristianserban** [comment]
hi there please follow up this https://github.com/taniman/profit-trailer/issues/803
