### ISSUE TITLE
Error occured - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by orty87** [taniman/profit-trailer#840]
I run PT on my raspberry pi, until v1.2.6.11 without any problems.

Since v12 after a few hours i get the error "java.lang.OutOfMemoryError: Java heap space". 
After the error PT doesn't work anymore and i need to restart it.

Any ideas?

[Error log.txt](https://github.com/taniman/profit-trailer/files/1667778/Error.log.txt)

**Comment by taniman** [comment]
Well problem is quite simple. in order to use binance websockets we need to use more memory. Try increasing the amount of memory you give to the bot when starting it

**Comment by orty87** [comment]
Thanks for the quick answer! I've set it to 1024 now. Will see if it helps
