### ISSUE TITLE
Profit% not calculating correctly

### ISSUE THREAD

**Issue by cybershadow76** [taniman/profit-trailer#841]
I've double checked the math and PT is using Bought Cost and Current Value to calculate Profit%.  The wiki clearly states that "Profit% - The current profit (gain or loss) which is a percentage between the bought price and the current price.".  It really should be using Bought Price and Current Price.  Can this problem please be fixed ASAP.  It makes chart analysis very difficult.  I use chart analysis to setup my bot.  See attached screenshot.
![issuepercent](https://user-images.githubusercontent.com/35465018/35441352-3d61a4f0-0271-11e8-97f2-86a3fbb36061.jpg)

**Comment by taniman** [comment]
you are wrong in your calculations.  we use avgprice and current price. minus the fees. There is the piece of code. 

![image](https://user-images.githubusercontent.com/6751341/35441791-2811f13e-02a5-11e8-81a1-3d11e77b8823.png)

**Comment by cybershadow76** [comment]
Thank you for explaining.  I know what the problem is. (I think)  I pay for fees in BNB not BTC.  I think you calculate fees using Binance's .1BTC fee per buy and sell.  Would that make sense since the numbers are .2 off (forgot decimal point on my screenshot, my bad)?  So in terms of PT i don't in theory pay any fees but the calculation assumes I am.  This is definitely a problem for BNB users.  Thoughts?

**Comment by taniman** [comment]
Well as there are multiple ways for binances users to pay for fees and definitely also there is an instance where you pay with BNB but have no more BNB so the fee is split in half BNB half non BNB I chose to always use the max.
0.2 is the MAX fee you can pay on Binance. and this is what we work with regardless of what you paid. 
This makes the logic cleaner

So it's not a problem but a choice in implementation

**Comment by cybershadow76** [comment]
totally agree, it would be hard to program every scenario.  Using BNB saves me money but it throws off all my numbers.  1st world problems right? lol.
