### ISSUE TITLE
Pairs go to dust log ?!

### ISSUE THREAD

**Issue by PeyoHristov** [taniman/profit-trailer#842]
Hello last 3 days i get some bugs.... when pairs go to -4 % move to dca logs and when up  go back to pairs but some times i get that pairs go to dust log .... dust log have 2 pairs with max price 0.0025 ? and dont move... one of that is from 2 days.... how can i change that ? Last day i get 4 dust like that and 2 of then is sold.... but other stay.... ? i run on .12 version

**Comment by taniman** [comment]
Please be aare that thus is not only dependent on the value of a coin. but also on the amount you have of a certain coin. This rule applies to binance and bittrex. 

So i guess most likely this is what is causing your dust

**Comment by taniman** [comment]
for further support contact support  as this is not a bug
