### ISSUE TITLE
[Request] Get someone to make a backtesting trading view script for PT strategies

### ISSUE THREAD

**Issue by tomastoth** [taniman/profit-trailer#846]
I was thinking if the owners of profit trailer would get someone who is good at making scripts for trading view to make a strategy back-testing script for each strategy. The scripts would be available to everybody so even new non customers could check the profitability and maybe end up buying the profit trailer.

**Comment by cristianserban** [comment]
please use the search function 
https://github.com/taniman/profit-trailer/issues/435
