### ISSUE TITLE
Safari browser support

### ISSUE THREAD

**Issue by starmetal** [taniman/profit-trailer#848]
It seems that monitoring dashboard doesn't display any data in Safari browser.

**Comment by djcrypto75** [comment]
Screenshots and more details please.

**Comment by starmetal** [comment]
![screen shot 2018-01-27 at 08 54 16](https://user-images.githubusercontent.com/35848607/35469929-eb013c28-033f-11e8-8eaf-2116e8da2f46.png)
Here are the screenshot. When I open http://my_ip:8081/monitoring in Firefox it works fine. When I open the same url in the Safari Browser it looks like at the screenshot. If I click on any of the menu itemst it looks the same. It seems that it cannot fetch data when using Safari browser on MacOS. The same is if I open it with Safari on iPhone.

**Comment by djcrypto75** [comment]
Must be something local on your safari as they sync over devices. 
I tested here now on my Macbook with Safari and on my iPhone with Safari and it works fine.
Are you running an old version? Try Safari in Private Window Mode. 
I will close this issue as its a support issue. Open a ticket or use Discord. You can refer to this ticket :)
