### ISSUE TITLE
Monitor displays BTC even when USDT market is selected.

### ISSUE THREAD

**Issue by icybob** [taniman/profit-trailer#849]
After I updated to the latest version 1.2.6.12, I noticed the monitor has BTC for the balance and profits even though I am in the USDT market. It does not appear to be causing other issues, PT is still trading and performing beautifully. Exchange is Poloniex and I have performed a fresh install with same results.

**Comment by tooraj-enayati** [comment]
Yep, I reported this yesterday. It is a known bug.

**Comment by djcrypto75** [comment]
Been reported 3-4 times now :) Please use search function.

**Comment by tooraj-enayati** [comment]
Still an issue with 1.2.6.14

**Comment by tooraj-enayati** [comment]
Fixed in 1.2.6.14 after running for a few hours. Doesn't makes sense but took a few hours and many refreshes.
