### ISSUE TITLE
Current Value not updating.

### ISSUE THREAD

**Issue by Paraoxysmal** [taniman/profit-trailer#850]
I'm using the latest profit trailer and profit trailer feeder on Binance. The program is not updating current price on the monitoring screen. I reinstalled trailer and feeder, tried default settings. Tried crypto crow settings, tried gnome settings. Nothing seems to change this issue. 

<img width="987" alt="screen shot 2018-01-26 at 3 23 48 pm" src="https://user-images.githubusercontent.com/35851108/35459207-279fcfde-02ad-11e8-86ec-485f7132e974.png">

**Comment by cristianserban** [comment]
what exchange are you using?

**Comment by smoochy** [comment]
I do have the same issue. Version .12, also running on binance. Not using PTF though.

**Comment by subru77** [comment]
I am running version 11 and I have 24hrs column also zero

<img width="1405" alt="screen shot 2018-01-26 at 6 04 41 pm" src="https://user-images.githubusercontent.com/938928/35467463-5cf4c0b6-02c3-11e8-9b4b-3ba036399dea.png">

**Comment by earlnod** [comment]
Same for me. I was on .12 but rolled back to .11 and still getting the same issue. No heartbeat after initial startup/initialization. Bot is effectively frozen

**Comment by chrismpalmer** [comment]
I think this is the same as #837

**Comment by Paraoxysmal** [comment]
I found the fix, *I* am using profit feeder. I downgraded profit trailer to .11 and feeder down to v3, now the bot runs fine!

**Comment by mymatelee** [comment]
Thanks for the info Paraoxysmal, that seemed to work for me too.

**Comment by OlympusSolutionsInc** [comment]
I have the same issue.
