### ISSUE TITLE
DCA buying consecutive times on v1.2.6.12

### ISSUE THREAD

**Issue by ThecRw** [taniman/profit-trailer#851]
Hi there

Seems to be an issue with Binance

The DCA on v1.2.6.12 was acting weird. I have my bot configured to start DCA in the lower BB (0) and if there is a -3% price drop. This is the conf:

max_buy_times = 3
buy_strategy = LOWBB
buy_value = 0
buy_trigger = -3
trailing_buy = 0.2

This was working fine in v1.2.6.11 and after I updated to v1.2.6.12 I noticed that, right after the first DCA, there was a second and sometimes even the 3rd, one after the other. Sometimes within minutes of difference. Sometimes seconds. This was obviously not allowing the bot to DCA properly, generating some bags, as I would not have any balance left for more DCAs.

I've rolled back to the previous version (v1.2.6.11) and everything is back to normal.

Attached the log from 25/01 and 26/01 so you can see the multiple DCAs

[25_26.txt](https://github.com/taniman/profit-trailer/files/1669157/25_26.txt)

Let me know if you need any more info on this.

Thanks

Cristiano W

**Comment by steffenkoenig** [comment]
Same Issue here. (1.2.6.12)
Earlier today 5 pairs got DCA'd 4 times in less then 30minutes. 
Only first DCA was legit according to the settings. Afterwards percentage would have been below the trigger.

Issue occured in the time window of 5 to 5:40 p.m. CET
