### ISSUE TITLE
[Feature Request] New Version Available

### ISSUE THREAD

**Issue by tomohern** [taniman/profit-trailer#853]
I currently have [a bash script](https://github.com/tomohern/PTS/blob/scripts/downloadLatestPT) that uses the below code to download the latest version of PT to my server when I do upgrades:

ver=$(curl -s https://api.github.com/repos/taniman/profit-trailer/releases/latest | grep 'browser_' | cut -d '/' -f8)

I am wondering if similar code could be used to set a flag in the Monitor if a new version of the software is available so that users can be notified when to download it?

**Comment by taniman** [comment]
Update notification is now available when using PTN. But will add a notification in notification bell in GUI too
