### ISSUE TITLE
[Feature Request] Total cost in USD

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer#854]
Would be cool to have Current Value and Total Cost in USD or a selected Currency (EUR, GBP) to understand at a glance how much is it without turning to an external currency calculator to figure it out.

**Comment by tooraj-enayati** [comment]
This might do what you a want, well almost:

https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons

**Comment by djcrypto75** [comment]
Its already on the roadmap and have been mentioned before :)
