### ISSUE TITLE
[Feature Request] Excel Sales Log 

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer#855]
Could we get the Sales Log output an Excel Spreadsheet to the Logs folder?
And keep updating it at every sale.

**Comment by swoopsus** [comment]
Agree getting the all of the logs output regularly to a folder in excel or csv would save a lot of people a lot of time. Keep up the good work!

**Comment by keithofaptos** [comment]
Aqua,on Discord, made a bat file that auto loads PT into terminal and auto
backs up LOG files too ,i believe.

**Comment by daryledesilva** [comment]
@keithofaptos  do you have direct link to this bat file?

**Comment by YoJeff** [comment]
#784 #755 #507
