### ISSUE TITLE
[Feature request] DCA date change

### ISSUE THREAD

**Issue by Wackywoods** [taniman/profit-trailer#857]
Heya All

Firstly thanks for a great product, it works well, easy to setup and maintain with no real issues and it works.

I just wanted to see if i can do a features request on the DCA date info.

It is hard to see how long you have had a specific pair for as when a DCA is triggers it updates the Date and time of that DCA purchase vs the time the first purchase was done. So to help make it clearer how old a coin is, is it possible to have the origin date of purchase once the first DCA is purchase triggered. As a DCA is purchased it does not move back under the pairs log either.

Thanks

Wacky

**Comment by HojouFotytu** [comment]
Agreed.  The most recent DCA purchase isn't really as important as the original purchase date/time.

**Comment by Joaoha** [comment]
Agreed, and also a possible enhancement would be to have all the DCA buys, when/howmuch / and what price. For example one could see by clicking on the DCA coin, and see the multiple levels.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
