### ISSUE TITLE
[Feature Request] Telegram Heartbeat and Summary Notifications

### ISSUE THREAD

**Issue by tooraj-enayati** [taniman/profit-trailer#858]
Can I please suggest a new feature whereby users can choose to get telegram message at a set interval with some summary information. This will also work as a heartbeat check, so the user doesn't have to hit the monitor page.

Eg:

**telegram.notificationSummary= 0/#**

Where # is a whole number of hours to receive a telegram message
     0 disables summary notification
     1 will send a summary notification via telegram every hour

eg:

	telegram.notificationSummary= 1

Will send something similar to the folowing:

	BAL:0.950 TCV:1.434 TPV:1.734  Profit:(4.73 LW)(0.83 YD)(3.90 TD)
	Trend:(-3.13% 24H) BTC:11368.99 (-2.03%)
	Possible Buy:4 Pairs:2 DCA:1 Pending:0 Sales:9 Dust:1

**Comment by Tank33au** [comment]
It would be nicer to have DCA buys in there too..
Need to know where the bot is spending my money on.

**Comment by Alutun** [comment]
+1 for @Tank33au  I would love to get the DCA notification when it's doing something.

**Comment by tulihub** [comment]
check https://github.com/tulihub/moonbot

**Comment by YoJeff** [comment]
v2.x introduced pt-notifications.

If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
