### ISSUE TITLE
[Feature Request] Run server side scripts from within the Monitor

### ISSUE THREAD

**Issue by tomohern** [taniman/profit-trailer#859]
I am currently using a shell script to load settings from my GitHub Repository. I would like to be able to place this script in a directory inside the Profit Trailer directory and then have a menu of scripts that I can execute.

Alternatively, if there is a way to incorporate the functionality of [this script](https://github.com/tomohern/PTS/blob/scripts/loadprofile) to load a list of settings profiles and then let the user choose which profile to load that would solve the issue also.

**Comment by taniman** [comment]
Maybe in a future release. fow now it's just filling up my issues log
