### ISSUE TITLE
[BUG] smagain buy strategy

### ISSUE THREAD

**Issue by DeWim** [taniman/profit-trailer#860]
Settings:
ALL_buy_strategy = SMAGAIN
ALL_buy_value = -1
ALL_trailing_buy = 0.5

Scenario:
Current value goes down to -1.9
Buy value i afcourse also changed to -1.9
Curent value shoots up to -0.7
Buy value stays at -1.9

The problem:
If, like stated in the wiki, 'trailing_buy' works the same as 'trailing_profit' but in reverse should the 'buy valu' not be reset to -1 if the 'current value' rises above -1 ?

I hope you understand what i mean. I tried to lay it out as clearly as possible :)

Regards,
Wim

**Comment by taniman** [comment]
I understand what you mean but this behaviour was never implemented.

**Comment by DeWim** [comment]
Would it be hard to implement the 'reset buy value' behaviour ?
Like it is working now the bot will, in a lot of cases, buy at a much higher value then it should.
Continuing on the above scenario this will happen a lot with the curren behaviour.

Current value goes down to -1.9
Buy value i afcourse also changed to -1.9
Curent value shoots up to -0.7
Buy value stays at -1.9
Curent value drops to -1.1 (here the bot will buy)
Curent value keeps droping to -3
Curent value goes up to -2.5 (here is where the bot should have bought)

In strategies where we're scraping low percentage gains this can be a huge deal and leave alot of profit on the table.

Regards,
Wim

**Comment by DeWim** [comment]
Is it possible to look at this one again since i realy think its rather a serious isue. Right now i am auto-restarting the bot every 30 minutes to have the buy values reset.
