### ISSUE TITLE
[Feature Request] Have a Control Panel like page that helps adjusting parameters

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#862]
Since some parameters appear to be dependent on each other (when adjusting one, you need to watch out for another one), it would be nice to have a page with some slider controls, where when you try to set one parameter (sliding left or right), you would be limited by some other parameters that you have set. Or changing one value would change another one to make sure you are not risking running out of balance or keeping the parameters in acceptable ranges without risking to lose money.
I was thinking of slider controls similar to these, and show the percentage and amount value when you move them:
[http://www.fmsinc.com/microsoftaccess/controls/components/slider-bar/sliders.gif](http://www.fmsinc.com/microsoftaccess/controls/components/slider-bar/sliders.gif)
I have started to put together a Google Sheet for my own calculations, to see how much balance I would be left after all pairs in DCA:
[https://docs.google.com/spreadsheets/d/1JWdSw6ZUPH6VuvczVjd9K4_BrXGlJ8EsmenGwoRf5nc/edit#gid=1190797594](https://docs.google.com/spreadsheets/d/1JWdSw6ZUPH6VuvczVjd9K4_BrXGlJ8EsmenGwoRf5nc/edit#gid=1190797594)

Thanks.

**Comment by Paraoxysmal** [comment]
Thats a great idea but would be very dangerous, this *technical* wall that exist is protecting people from gambling.

**Comment by nstefi** [comment]
Sorry, I can't tell if you are kidding or serious :)
To me it seems like we are gambling now with the bot by trying out lots of settings from each other, and not really understanding the consequences that small changes can have. It's easy to make mistakes, and accidentally the bot could make buys at high and sells at low if you don't configure it correctly.
