### ISSUE TITLE
[Feature Request] DCA Variable Level Multiplier 

### ISSUE THREAD

**Issue by slimgit** [taniman/profit-trailer#864]
Please add an option to set a variable multipliers for each level in  "Anderson DCA" instead of  having constant multipliers 1, 2, 4 , 8, ...2^n. This would make it less aggressive, balance consuming and more flexible.

**Comment by Macflurry26** [comment]
This is exactly what I was checking for before posting.

I was about to ask for exactly the same thing! lol

A setting like the one below for each trigger:

buy_trigger_1_multiplier = 1

So 1 would be default but any other settings would need the line adding to  make that DCA buy 2, 3 or 4 times the current amount.  

I find that quite often only DCAing oncee leaves the average value quite high in the BB.  If you're using a trailing value then you have to wait for it to trail again before it DCAs a second time but by then it may have slipped to far to be a useful as you wanted and you're back to needing two DCAs.

I use a first DCA in case it didn't quite purchase at the bottom of the dip.  But then I want to use DCA 2 to double up twice and crash the average right down after a bigger slip in value.
