### ISSUE TITLE
[Suggestion] Telegram Message - Display profit higher so it shows in iOS notification

### ISSUE THREAD

**Issue by okulair** [taniman/profit-trailer#865]
The iOS notification of Telegram display the first 4 lines only.  I would be interesting to show the profit % and profit in one of the first 4 lines instead that lower in the message.

They could be on the same line:
Profit BTC: 0.00234231 (1.11%)

**Comment by dumolibr** [comment]
Yes!! Very annoying. Show profit first and then in the following lines the cost and rate. Tnx

**Comment by Paraoxysmal** [comment]
You can make a work around, make a second bot. Write a simple api script, have your messages go to your second bot. Your second bot deciphers specific information, reorganizes and sends it to your first bot. Kind of like profit trailer feeder, a bot for your bot.

**Comment by steveoneal** [comment]
Or perhaps a user configurable template.

**Comment by YoJeff** [comment]
everything has changed now, the gui, pt-notifications, etc...

If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
