### ISSUE TITLE
[Bug] Average Price Incorrect in Gui

### ISSUE THREAD

**Issue by CryptoKnine** [taniman/profit-trailer#866]
I was trying to figure out how PT bought at such a high price but when i compared to the exchange it was way off. Check the average price and current.  They were both off. Already tried to restarting to no avail. I may just start from scrate tomorrow.  There is prob other buys , i just didnt notice till now

![pt](https://user-images.githubusercontent.com/35861508/35469171-e8ad6754-02fd-11e8-9730-a664f8fbbbe7.PNG)

![binance](https://user-images.githubusercontent.com/35861508/35469161-c21f36d0-02fd-11e8-933c-89200ba71fe2.PNG)

**Comment by CryptoKnine** [comment]
Seems another buy

![binance2](https://user-images.githubusercontent.com/35861508/35473028-b9bc02bc-0347-11e8-8de7-1466a3ce9306.PNG)

![another](https://user-images.githubusercontent.com/35861508/35473037-d703d7dc-0347-11e8-8227-f67b5b315601.PNG)

**Comment by taniman** [comment]
Both of your examples are wrong. in the first image you own 4.32 coins  in the seoncd image you own 8.64 coins 
So you are not calculating using all the buys that you should be using to get to these amount of coins
