### ISSUE TITLE
BB Strategy not working

### ISSUE THREAD

**Issue by antigravity83** [taniman/profit-trailer#867]
Having some issues with BB Strategy. Bot doesn't seem to be triggering as per rules set

Buy -15
Trail 5

This example dropped way below -15% of the Bollinger Band width, but PT didn't watch it or trail it. 

![image](https://user-images.githubusercontent.com/27241813/35470018-c07033a4-038c-11e8-9699-756b421e8a5f.png)

Wiki says Buy value is percentage of Bollinger Band Width. So I've set -15% (so buy when price gets -15% below the LowBB

Wiki also says trailing number has to be positive. So Ive set that positive also

**Comment by BrotherMunk** [comment]
If you set BB trigger at -15% you do have put tour trail buy at positive. But you went way to far. If you want to be at -15% then it has to be lower such as -14 or -10 bringing it back towards the bottom BB line but not passed it. You also have to modify indicators and watch the at cost price to the BB trigger cost. Using this set up takes a long time to get down.

**Comment by antigravity83** [comment]
Thanks - I've changed the LowBB trigger to -1 and still nothing is being trailed.

Indicators are at - the following to match the chart shown.

300 seconds
10 SMA

**Comment by BrotherMunk** [comment]
I would suggest not using those indicators. Put it at 900 and 20. Then look at the graph for one coin that its looking at and compare all the numbers reading for buy cost with the graph. SMA should be at 40 or 20

**Comment by antigravity83** [comment]
Ok thanks I will try those. 

Concerned that 900/20 won't pick up dips quickly enough?

Want to Buy/Sell, Buy/Sell, Buy/Sell quickly. Lots of small transactions.

**Comment by antigravity83** [comment]
I've read the wiki a number of times. Understand how Bollinger Bands work and also the indicators. 

900 Seconds actually refers to the candle time frame? That's what your wiki says:
https://wiki.profittrailer.io/lib/exe/detail.php/bb_setup_exchange.jpg?id=indicators.properties

Does the bot only look at a certain number of candles when doing calculations?

I don't understand why BB as a method is slower? Wouldn't speed be based on candle time and sma length? Not the method itself?

Or is the bot not quick enough to calculate BB on smaller time frames?

**Comment by antigravity83** [comment]
I've changed the LowBB Buy trigger to 0 and it isn't picking up the following drops below the LowBB?

![image](https://user-images.githubusercontent.com/27241813/35470526-e54e4d3c-0396-11e8-9a2a-fa8af1688948.png)

**Comment by antigravity83** [comment]
Here's another one. 2% potential profit.

![image](https://user-images.githubusercontent.com/27241813/35470917-b36c2a08-039d-11e8-8a89-bbc4fdd9917e.png)

**Comment by antigravity83** [comment]
Here's another example.

I moved the LowBB Buy to +2, Trail to 2, and it wasn't picking up anything

![image](https://user-images.githubusercontent.com/27241813/35473024-621192e2-03c5-11e8-929a-0bfceb6a60b7.png)

**Comment by antigravity83** [comment]
Increased to +5, not picking up

![image](https://user-images.githubusercontent.com/27241813/35473123-0302d138-03c7-11e8-82fc-9a5c99514a6b.png)

**Comment by antigravity83** [comment]
Here are my settings:

INDICATORS
BB_period = 300
BB_sma = 10

PAIRS
ALL_enabled_pairs = ETHBTC, XRPBTC, BCCBTC, ADABTC, XLMBTC, LTCBTC, EOSBTC, NEOBTC, XEMBTC, IOTABTC, DASHBTC, XMRBTC, TRXBTC, VENBTC, QTUMBTC, ICXBTC, BTGBTC, ETCBTC, LSKBTC, XRBBTC, OMGBTC, STEEMBTC, ZECBTC, STRATBTC, XVGBTC, BTSBTC, SCBTC, ZRXBTC, SNTBTC, WTCBTC, WAVESBTC, DOGEBTC, HSRBTC, LRCBTC, BATBTC, KNCBTC, ELFBTC, QASHBTC, DGDBTC, GASBTC, BTMBTC, SALTBTC, CNDBTC, NASBTC, POWRBTC, REQBTC, QSPBTC, SUBBTC, PAYBTC, CVCBTC
ALL_trading_enabled = true
ALL_sell_only_mode = false
ALL_DCA_enabled = -2
ALL_buy_strategy = LOWBB
ALL_buy_value = 5
ALL_trailing_buy = 2
ALL_max_cost = 0
ALL_max_cost_percentage = 3
BNBBTC_trading_enabled =  false
ALL_hidden_pairs = BNBBTC
ALL_max_trading_pairs = 1
ALL_min_buy_price = 0.00000500
ALL_max_buy_spread = 2
ALL_min_buy_volume = 800
ALL_min_buy_balance = 0
ALL_min_buy_balance_percentage = 10
ALL_buy_available_volume_trigger = 150
ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_trailing_profit = 0.1
ALL_btc_price_drop_trigger = 10
ALL_btc_price_drop_recover_trigger = 2
ALL_btc_price_rise_trigger = 10
ALL_btc_price_rise_recover_trigger = 2
ALL_consecutive_buy_trigger = 3
ALL_consecutive_sell_trigger = 2

**Comment by Macflurry26** [comment]
Try setting your trailing buy to less than 1 and see if it picks something up.  I've recently increased mine to 0.75 to wait longer for purchases.  I think I tried 2 when I started and wasnt getting anything.

**Comment by taniman** [comment]
@antigravity83  I will answer your last 2 pictures. Current price is not below trigger BB, So these 2 examples will never trail

**Comment by antigravity83** [comment]
@taniman If I use the last screenshot as an example, why is the BB Trigger not 5% above the LowBB line as per my settings?

As you can see, the price is at or below the actual LowBB line in the screenshot. I set my LowBB trigger to 5% ABOVE that. So why is the trigger not 5% above the LowBB line?

**Comment by antigravity83** [comment]
@taniman Just had another look, and the price is below the trigger.

Tradingview has the price at 18371, the BB Trigger is 18460?

**Comment by antigravity83** [comment]
@Macflurry26 thanks mate will give that a try.

My concern is more around the fact the bot doesn't even start watching the trail when it clearly gets below the BB Trigger. 

It's as if the bot is simply too slow to catch moving Bollinger bands

**Comment by Tank33au** [comment]
I told you you can't use tradingview to get the figures.
You have to use figures from the exchange at the moment its happening.
Not any period after. BB lines get fixed after the expiry of the period but it moves in realtime.

**Comment by taniman** [comment]
@antigravity83 it does not matter what trading view says. At the moment you posted your screenshot the bot thinks the price is above the trigger. just look at your screenshot. it is right there for you to see. 

I am only static the facts that lead to the bot not trailing. 

Now if the price the bot is displaying is wrong. that is something different and depends if you are using V1.2.6.12 or not. Because there is huge price lags in that version.

Before coming to own conclusions and starting to declare things broken you need to at least understand  what the bot is telling you.  

I am currently trying to built my case for Binance with their lagging websocket. They won't investigate for me. And neither will eye. until you come with actual proof.

and as it stands right now I have debunked your 2 screenshots

**Comment by antigravity83** [comment]
Hi @taniman 

I appreciate your help - apologies if I come across rude- just getting frustrated that the BOT doesn't seem to follow my clear instructions. I've taken lots of time reading the wiki, watching videos and writing my own config files (instead of copying others). 

What you said re. the speed of the bot could potentially be the issue - that the bot isn't picking up prices quick enough, and the price is going below the BB trigger and back too quick for the bot to pick up.

For example- in my last screenshot. PT has the price of ZRX at 18539, and trigger at 18460. The actual live price was 18371 (which is below the BB trigger). But PT never picked it up. 

I would like to see an example of LowBB (between +5 and -15) working though. No matter what settings I enter into the BOT, and leave it running for hours with heaps of pairs, it never triggers a purchase.

**Comment by antigravity83** [comment]
Here is another example - PT and Live Binance Chart side by side

LowBB
Buy = 10
Trail = 1

BINANCE
Actual Live Price = 0.0035648
In bottom 10% of Bollinger Band on Binance? = YES

PROFIT TRAILER
Live Price Listed = 0.00361100 (higher than Binance)
BB Trigger = 0.00361100

The live price is below the BB Trigger in Profit Trailer- but for some reason PT thinks the price is higher, so doesn't trail it/buy it?

![image](https://user-images.githubusercontent.com/27241813/35478192-4af7e8ce-0422-11e8-8f41-7ef344f7f5c3.png)

**Comment by antigravity83** [comment]
Interesting... Noticed this in the log for the first time:

0|profit-t | 2018-01-28 12:01 +10:00: 2018-01-28 12:01:24 INFO NormalStrategyRunner - There is not enough volume to buy WTCBTC

However Volume is set to 800, and WTCBTC has current volume of over 5000?

**Comment by felipeff** [comment]
I'm using LOWBB on binance with a buy_value of -0.5. have been using for 2 days now and it's working fine. Had around 30 trades since I started using LOWBB

**Comment by antigravity83** [comment]
Interesting thanks.

What is your trailing and your indicators?

**Comment by antigravity83** [comment]
Great thanks. 

Only real difference between you and me is the SMA. I'm using a 10 SMA for thinner, more volatile Bollinger Bands

**Comment by antigravity83** [comment]
Another example:

Live price below the BB Trigger.

Live price not reflected correctly in PT.

Therefore no purchase is made. 

![image](https://user-images.githubusercontent.com/27241813/35478937-063c6552-0436-11e8-99f8-47746d079459.png)

**Comment by taniman** [comment]
@antigravity83 I will try and create a working example for ASAP.  
About the not enough volume message. This is not total volume but current available coins in orderbook needed to place an order

**Comment by taniman** [comment]
@antigravity83 What version of PT is this?

**Comment by antigravity83** [comment]
Thanks @taniman. Worked out that volume issue was related to my order book settings.

**Comment by taniman** [comment]
@antigravity83 nevermind. i can see from yuor screenshot your 24h% are showing. so you are using .12 version. 

Are you not in our discord channel. I send an announement about using v.12 on binance. There is a price lag using sockets so the live price as you call it will definitely be missed a lot.

**Comment by antigravity83** [comment]
Those screenshots were from .12

I've dropped down to .11 but experienced the same issue.

Just to confirm, when applying settings to LowBB buy and trail settings, do you use full number to represent percentages (ie. 1 = 1%). Wiki suggests so?

**Comment by taniman** [comment]
yes. correct 1 = 1%

also be aware that 1% buy_value is based on the BB width.
this 1% is NOT 1% below LOWBB price.

The correct formula is not on the wiki.  But I will still come with an example for you. 

Can you double check on your V11 version that cache heart beat is there.
also wait 10 minutes for the bot to startup before starting your charting

**Comment by antigravity83** [comment]
Thanks- that was my understanding.

1 = +1% of the BB width above the LowBB line
0 = on the LowBB line
-1 = -1% of the BB width below the LowBB line

Can I confirm that trail on LowBB uses decimals to represent percentages?

Ie.
0.1 = 10%

**Comment by taniman** [comment]
@antigravity83 That would make the software a mess wuld you not agree?
trail is the same. 0.1 = 0.1%

But for BB trailing we take a snapshot of the BB trigger price when price hits our BB trigger. Than start trailing based on the price change.

But there is a bug currently in this trailing logic that will be fixed in next release. But that's how the trailing ogic works for BB

**Comment by antigravity83** [comment]
Ok thanks @taniman... Will wait for the next release to play with LowBB again.

**Comment by Paraoxysmal** [comment]
I didnt read through all of this but whats your indicators for BB, youre only checking 10 candles on trading view and the default is 40 candles for the bot. Youre seeing something different than your bot.

**Comment by Paraoxysmal** [comment]
Read through your trading view is the same as your settings, ignore my comment. Bolinger Bands is meant to measure volatility, buying and selling on them accurately is difficult. You really need an EMA to follow dips and crosses!

**Comment by antigravity83** [comment]
@paraoxysmal Tradingview and PT were both running 5 minute candles

**Comment by antigravity83** [comment]
Noticed the latest update didn't specify any fixes for BB Trailing in the change log. 

Is this still in the works?

**Comment by ChadMC** [comment]
I'm been running LOWBB a few days with Binance. 300/40 on the indicator. Buy value at -28. It works well most of the time, but over the course of a few hours, the BB data seems to get way out of sync until I restart the bot. So it will start buying way above the LOWBB after some time. After a restart, back to normal again. This occurred on version .12 and even the latest .14. Is this a similar bug to the previous one where the websocket price data would stop updating, but in this case it could be the BB data has stopped updating?

**Comment by YoJeff** [comment]
Resubmit if still issue with .16

**Comment by blockheadbits** [comment]
Has this been fixed at all or the wiki updated? Having same lowbb issues
