### ISSUE TITLE
[Feature Request] Trailing EMA/SMA SPREAD

### ISSUE THREAD

**Issue by Justlooking7** [taniman/profit-trailer#868]
Hi, I have an idea that I think will help with better buys.

I suggest instead of blindly buying into the dip when EMA spreads triggers according to your strategy why not wait for some sort of confirmation that trend has reversed to upside ? 

To achieve that we would need bot to trail EMA spread itself, lets say EMA fast crossed down EMA slow and price is dipping, bot would monitor % of the spread, once it got to its highest level (biggest spread) and started to shrink (EMA spread decreasing) only then we would be looking to buy. In this case we would not blindly buy into the dip, but we would have some sort of confirmation that we had a bottom and trend reversed (of course there will be fake-outs and nothing you can do about that). I believe with this we would almost always would buy at lower price (as we would be looking to buy once we start climbing again close to bottom).

Ex.
![image](https://user-images.githubusercontent.com/35863796/35470636-069d07f0-0345-11e8-9af5-60e5156ddc2f.png)

In chart above lets say we are interested to buy once spread is -1.4% we skip first -1.4% trigger and trailing the spread all the way down, once we start reversing and spread shrinking back to -1.4% we would be looking to make a buy order. With this type of trailing we would purchase at roughly 4.5% lower price in this example (depending on your trailing), most of the charts i pull it seems to me that almost always this would succeed with better buy.

I hope I described my idea well enough to be understandable, if you have any questions let me know on discord, my nickname is Edgar111 or write a comment here, thanks :)

**Comment by miloaissatu** [comment]
This sounds great! I was trying out EMA cross to attempt to achieve something similar but having limited success. Trailing EMA spread the way you describe definitely sounds like a more viable and consistent approach.

**Comment by Sherland5540** [comment]
Great idea. Hope we can implement it

**Comment by JulesBern** [comment]
This is how I manually trade so if I can do it the bot should do it.

**Comment by Gitulu** [comment]
Amazing

**Comment by ba32107** [comment]
Isn't this the same thing what trailing_buy does?

**Comment by cryptomail2018** [comment]
perfect . i hope they come out with a more accurate setting soon . this would give us a better gain of 4-5% instead if 1-2% in my opinion

**Comment by blockheadbits** [comment]
It wouldn't work that way using the method you suggest though.  The bot would have bought 13 bars over at the next uptick because that is where spread hits 1.4% again.  The highlighted point 35 bars over is the second appearance.  ICX/BTC 1/24/18 13:00

So bot is still buying on a false positive. 

![tv01](https://user-images.githubusercontent.com/36007841/36272265-06fb1e62-124f-11e8-9695-b76282b2d9ca.jpg)
![tv02](https://user-images.githubusercontent.com/36007841/36272266-070a9ba8-124f-11e8-82ea-71400eb1e125.jpg)
![tv03](https://user-images.githubusercontent.com/36007841/36272267-071b92f0-124f-11e8-82b7-ab46280d082b.jpg)

**Comment by taniman** [comment]
This will not be implemented. PT2.0 will come give the ability to use multiple indicators to provide confirmations.
Plus some other additions.
