### ISSUE TITLE
coin that PT sold is not showing up in logs

### ISSUE THREAD

**Issue by razorseal** [taniman/profit-trailer#869]
Hello,

PT sold a coin (I certainly didn't sell it), however it is not shown on the sales log. I remember seeing it in the pending log, and realized the coin was missing today. I looked and it appears it had been sold some time ago... I think it was stuck in 'pending log' way after being sold, and once I restarted the PT, it disappeared for good. I did sell teh LTC myself, but not MONA

![image](https://user-images.githubusercontent.com/34427378/35471178-f509e25e-0323-11e8-8ba6-5988ce04329e.png)

![image](https://user-images.githubusercontent.com/34427378/35471183-0d69b9fa-0324-11e8-9be9-1e7cbca9e4a4.png)

Something isn't right here.

**Comment by felipeff** [comment]
Sells made by the "pending log" does not show in the sales log.
You probably have on your strategy a time limit which after that the bot creates a pending order and give up on that trade.
