### ISSUE TITLE
DCA sold in parts often results in terrible recalculation of average buy price.

### ISSUE THREAD

**Issue by inbound-be** [taniman/profit-trailer#871]
Hi guys,

I am seeing this more and more. Bigger bags get sold in parts: sometimes all is good, but sometimes PT recalculates the average buy price and makes a huge mistake. I just had another one and decided to come in and post it here.

Here's a sample:
![image](https://user-images.githubusercontent.com/30729272/35474116-f1ce28d2-0389-11e8-9ee3-6955532d836e.png)

I can't seem to find the correct line in my logs, but have had more instances like this one, often resulting in the bot selling my bag with a loss, sometimes quite hefty. In this case, seeing as TNT climbed up even further 15 minutes later, I lost out on about 0.015BTC, would be great to be able to avoid this in the future.

**Comment by inbound-be** [comment]
Update: this is all the trade history on Binance for this trade:

![image](https://user-images.githubusercontent.com/30729272/35475471-59252476-039f-11e8-8085-21c5f57bc109.png)

**Comment by inbound-be** [comment]
I don't feel comfortable posting logs in public but feel free to message me on telegram or on discord (kanyewestofgaming) if you need them for your research.

**Comment by Wackywoods** [comment]
Is it not possible that it trying to sell them but price is changing so it is selling the bags in a trailing stop loss sort of way, puts in one order it fills and cancels and puts in another order to get the sale cleared? 

I have seen this on a few of mine aswell but not as bad as yours it seems.

**Comment by Paraoxysmal** [comment]
Shouldnt the average remain the same? I mean *yes* you can sell DCA bags at varying levels but you're still trying to hit the same average.

**Comment by inbound-be** [comment]
Yes, AVG price does not change because you sold a piece of a bag. Otherwise you're selling with a loss.

**Comment by taniman** [comment]
Upgrade to version 1.2.6.14. If this happens again. We will reopen this issue
