### ISSUE TITLE
435+ Expired buy orders in 4 days

### ISSUE THREAD

**Issue by symbion6** [taniman/profit-trailer#873]
I'm getting a LOT of expired buy orders, both for regular pairs as well as DCA.
https://www.dropbox.com/s/2lp2sk1htpxzuiz/ProfitTrailer.zip?dl=0

435+ expired orders in 4 days.

**Comment by mindcqntroller** [comment]
Same problem here. See coins with 5 DCA go to +3%. PT can't sell them. Get a lot of expired orders.  This happend to me about 25 times today.  A heavy loss.

**Comment by Tank33au** [comment]
Go back to the older version..
Executing orders are the most important function of the bot.
If you didn't have ban issue, use v10 otherwise go back to v11.

**Comment by Masterman1980** [comment]
Went back to v10 and same problem. Getting a lot of expired orders. For buying and selling on Binance.

**Comment by taniman** [comment]
Expired orders can happen. use buy available volume trigger when buying. so avoid partial buys. 

We are aware of .12 having expired orders and this was announced in the discord channel so I do not see why there is a need to create an issue about it too

**Comment by symbion6** [comment]
Please be aware that not everyone is on discord :) I'm doing my best to keep up and so is everyone, but some things will be missed. The v10 seems to run better than v12. Still getting expired orders, but I'll work with the buy available volume trigger to see if it improves.

**Comment by taniman** [comment]
@symbion6 Yes. Sometimes I tend to forget that. We will need maybe a different channel for notifications. Maybe our website. 

But the issues page should not be filled with the same over and over, that's also not the idea of this page.

**Comment by symbion6** [comment]
@taniman. Agree, I searched for "expired" before creating the issue, but didn't find anything that's related to the problem, hence the new issue.
