### ISSUE TITLE
Pending Value Drops

### ISSUE THREAD

**Issue by empbac** [taniman/profit-trailer#874]
This is low priority.

I have noticed that the Pending Value sometimes drops. I believe this is connected to the log rotation value set in application.properties, trading.logHistory. I had it set to 7 and started seeing it drop occasionally after a week. I changed it to 30 days and it was fine until today, and it has dropped. I have now set it to 999 to avoid this in the future. I have held some bags a long time, over 30 days, and I believe data regarding their contribution to Pending Value has been lost.

I don't believe anything is mechanically wrong here, this is simply a confusing reporting bug. The fix would be to make sure to not delete logs of coins that are still held in your account. Everything else can rotate out, but if you still hold a coin you need to retain whatever corresponding data informs the Pending Value calculation.

I can see people freaking out over this if they notice, so I wanted to point it out. I don't know if a fix would be quick and simple or not, I leave it to the devs.

**Comment by taniman** [comment]
Pending value has no relation to saleslog. 
Pending value drops is any bought_price is lost

**Comment by empbac** [comment]
So log rotation only applies to Sales?

I see that my BTC-DASH bought_price was lost. It was originally bought on Dec 22 2017 and later was DCA'd twice. My log rotation was set to 30, but Pending didn't drop until today. Is this not related at all to log rotation time? Does this just randomly happen sometimes?

**Comment by GGaulin** [comment]
I think the data you are looking for is in the ProfitTrailerData.json, this file might have been overridden by an update :(

**Comment by taniman** [comment]
@empbac  correct. ON bittrex this happens if you own a pair for more than 30 days. Just set the bougt price using hotconfig
