### ISSUE TITLE
emagain possible issue

### ISSUE THREAD

**Issue by cybershadow76** [taniman/profit-trailer#876]
I have emagain setup with a positive  buy percent.  I've noticed the bot buys above or below the lowest ema line with a positive number.  According to the wiki below it does confirm that.  I just wanted to make sure that is accurate because i was hoping a positive number would only buy above the lowest ema line.

Strategy = EMAGAIN
Buy as soon as the price goes a percentage below the specified EMA line.
ALL_buy_value is a percentage below or above the lowest of the 2 EMA lines.
Possible ALL_buy_value example:
ALL_buy_value = -1 → buy if the current price is 1% below or lower than the lowest EMA line.1 → buy if **the current price is 1% above or lower than the lowest EMA line.**

**Comment by taniman** [comment]
A positive value WILL but below the line too. Just like it says there
