### ISSUE TITLE
[Feature Request] Trigger a pair into SOM when its 24h trend is lower than BTC (or base) trend

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#878]
When I look at the top are of the Monitoring page, and I see that the 24h trend of the market is lower than the trend of my base (BTC or ETH), I usually collect more bags.
I thought we might need a setting where you could turn on a trigger, that looks at the trend of a coin and if it's lower than the trend of the base, it would turn on SOM for that coin. (for example BTC-XRP_sell_only_mode = true)
Then if the trend of the coin recovers and is higher than the trend of the base, turn off the SOM.
This would help avoid bags automatically.
Thanks.

**Comment by YoJeff** [comment]
#80
