### ISSUE TITLE
Buying preference from PBL

### ISSUE THREAD

**Issue by Justlooking7** [taniman/profit-trailer#880]
Hi, I have noticed on few occasions that BOT has no preferences when making a purchase from PBL, what I mean is I have 2 possible buys and only 1 pair available, one with -7% spread and other with -1.9% spread, and bot made a purchase with -1.9% spread. 

I wonder if it wouldn't make sense to prefer one that has passed further through your trigger (this case -7% spread) as that would probably yield in better returns.

**Comment by Tank33au** [comment]
I asked about this a long time ago.. At the moment, first come first served.. Remember you can always narrow your range down with the limit setting.
