### ISSUE TITLE
[Suggestion] Option to restart bot through the UI

### ISSUE THREAD

**Issue by poomato** [taniman/profit-trailer#881]
I see you can stop your bot with /stop or the red button, but how about a /start or a /restart?

Thanks

**Comment by Wackywoods** [comment]
IT would also be nice to be able to disable that start stop button from showing on the GUI. specially as anybody that access the GUI can stop it. IF you running a group bot it can cause potential issues but a great function to have for private bots

**Comment by poomato** [comment]
Nah, you can't stop it with password disabled.

**Comment by YoJeff** [comment]
Restarting is implementation specific.
