### ISSUE TITLE
Sales log and daily profit doesnt update

### ISSUE THREAD

**Issue by Reymon6666** [taniman/profit-trailer#882]
Hi

I realized that my Binance bot does not update the sales log every time It does a sell, I know its buying and selling because the Telegram bot send me notifications. Is there any way to re sync the log file with the bot?

looking forward to speak with you.
Best regards

**Comment by avnery4** [comment]
Same problem here. Prices doesn't update with Binance API after a couple hours that the bot is running. 
Only updates after bot restart.

**Comment by MohamedToure3** [comment]
The same thing is happening to me. I am using Bittrex and my sales are not going past 20

**Comment by TalonPower** [comment]
was this fixed?  because im using bittrex and see the orders sold there and not in profit trailer...

using  P T Ver:  1.2.6.16

**Comment by Regimax** [comment]
After upgrading to the latest version, my sale are not logged. Exchange: Binnance.
