### ISSUE TITLE
Monitoring Page uses wrong coin label when market is USDT.

### ISSUE THREAD

**Issue by jeffturpin** [taniman/profit-trailer#885]
When the market = USDT, the monitoring page uses the "BTC" label on all the tiles instead of the USD or USDT label.

This issue isn't present with ETH is the market - the label = ETH.  Issue only impacts USDT markets.

**Comment by djcrypto75** [comment]
Hey :) This is the 5th time this is raised, please search.
I will fix for next release.

**Comment by jeffturpin** [comment]
Sorry, guess my search terms were overly specific, I didn't see it.  Thanks.

**Comment by tooraj-enayati** [comment]
Fixed in 1.2.6.14
