### ISSUE TITLE
[Feature Request] EMA3 Option

### ISSUE THREAD

**Issue by bathtub2007** [taniman/profit-trailer#886]
Currently there are only 2 EMA options for slow and fast.  Would it be possible to add a medium EMA? (I.E. EMA1 - EMA2 - EMA3) ?

**Comment by Paraoxysmal** [comment]
What leverage would a medium offer you, how would you weight it vs the fast/slow EMA's? 

How could it function in EMASPREAD, EMAGAIN, EMACROSS? 

Adding a medium line would not help you, it would just complicate where you are at in the spread, cross etc. (Also a medium EMA would be the average of the fast/slow or just a hot mess.)
