### ISSUE TITLE
Can you please explain BT% and BB / Trigger columns in DCA Log page

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#887]
I don't understand what these 2 highlighted values mean in the DCA log:
![image](https://user-images.githubusercontent.com/6478474/35486648-1617817e-043f-11e8-9dd1-cbda7fe9a903.png)
In the wiki there is no explanation beside "BT% -"
My pair XMRETH that is highlighted already DCA'd 3 times, so my next level based on my configuration is:
buy_trigger_4 = -9.52
None of those 2 values are -9.52. Is it because it started trailing?
My trailing_buy = 0.07771
How do we calculate those 2 values on the image?
Thanks

**Comment by taniman** [comment]
Ask support as this is not an issue

**Comment by nstefi** [comment]
I have asked this twice in the support channel, but still didn't get any explanations.
Those columns should be explained in the wiki, because they are important to understand what the bot is doing during DCA.
