### ISSUE TITLE
Discrepancy between Binance trade History and PT Sales Log

### ISSUE THREAD

**Issue by grandmore** [taniman/profit-trailer#888]
Total profit is incorrect as wrong price showing in sales log.

Sales Price
0.00005560 (PT)
0.00005562 (Binance)

PT Sales Log
![sales-log](https://user-images.githubusercontent.com/666743/35486900-cc47dfa2-046c-11e8-86a0-1316645fd864.jpg)

Binance Order History
![order-history](https://user-images.githubusercontent.com/666743/35486907-e719d4de-046c-11e8-994a-790ede23eb85.jpg)

Binance Trade History
![biannce-trade-history](https://user-images.githubusercontent.com/666743/35486804-2e187e5a-046b-11e8-98d0-79f223434974.jpg)

**Comment by taniman** [comment]
bot always substract 0.2% fees even if you are paying fees with BNB.
