### ISSUE TITLE
Feature Request: Exclude pairs based on 24 hour % rise 

### ISSUE THREAD

**Issue by shakilVai** [taniman/profit-trailer#889]
Is it possible to include this feature in future release to exclude pairs based on 24 hour % rise? For example if the coin price has risen more than 25% don't buy the pair. Thanks.

**Comment by miloaissatu** [comment]
Also would be good if there was a similar setting on 24h % drop, like on coins that are on a solid straightline downtrend.

**Comment by Paraoxysmal** [comment]
You could just use negatives for that, I like this idea a lot. More stop triggers, more failsafes!

**Comment by taniman** [comment]
search before creating new issues. This one is even on a milestone already
