### ISSUE TITLE
[Feature Request] _min_buy_balance to be COIN-PAIR ENABLED

### ISSUE THREAD

**Issue by tooraj-enayati** [taniman/profit-trailer#890]
It would be great to allow "_min_buy_balance" to be COIN-PAIR ENABLED. That way we can hodl some of the coins but trade the excess.

**Comment by YoJeff** [comment]
The wiki suggests the _percentage setting IS coin pair enabled but the non percentage is not.

Clarification @taniman ?

**Comment by a7777777v** [comment]
This would be AMAZING i would love to have it 50% HOLD

**Comment by a7777777v** [comment]
Just to clarify, I'm trying this:

```
# Only buy coins if the buy cost will not let your balance go below specified amount. 
# Example 0.5, if we are trading BTC, the bot will keep at least 0.5BTC in your account.
# also need to set this value in DCA.properties
ALL_min_buy_balance = 0

# Leave 60% of my account untouched. set value to 60%. This property only works if ALL_min_buy_balance = 0
ALL_min_buy_balance_percentage = 60
BNBBTC_min_buy_balance_percentage = 60
IOSTBTC_min_buy_balance_percentage = 60
```

**Comment by a7777777v** [comment]
@YoJeff This doesnt work to keep 60% of a coins balance. Everything is sold IOSTBTC_min_buy_balance_percentage = 60
