### ISSUE TITLE
[Request] DCA Strategy Rework

### ISSUE THREAD

**Issue by Paraoxysmal** [taniman/profit-trailer#891]
Doubledown on DCA is a phenomenal risk/profit leverage point. Doing math and playing with virtual values, being able to do more than doubledown would be phenomal. If we had access to tripple down and quadruple down we can leverage 16%^2 better and 25%^2 better. 

Now 5x is not practical unless you have 10BTC or more, tripple works at 1BTC and Quad begins being effective around 3.5BTC.

TL:DR add Tripple down/ Quadruple down, at minium Tripple down

**Comment by Mopagi** [comment]
Thinking about the same past few days. Also possibility of setting exact DCA levels for each coin based on value would be great, something like:

ETHBTC_DCA_1 = 0.10500000
ETHBTC_DCA_2 = 0.10000000
ETHBTC_DCA_3 = 0.08000000
ETHBTC_DCA_4 = 0.06000000

ETHBTC_DCA_1_multiplier = 2
ETHBTC_DCA_2_multiplier = 3
ETHBTC_DCA_3_multiplier = 4
ETHBTC_DCA_4_multiplier = 5

**Comment by Paraoxysmal** [comment]
I use feeder for offsets but yes more DCA. Tripple down is better for risk management, Quadruple requires more capital but is even better. 

*Exact* values I part ways with opinion, the world is too inexact. I like parameters and I want more.

**Comment by taniman** [comment]
already on the roadmap.
