### ISSUE TITLE
[Feature Request] Buy on Signals

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#892]
Example (Telegram or API):
https://cryptoping.tech/guides/signal-anatomy
Example2 (List of Providers and Performance):
https://www.cryptohopper.com/signals
Example3 (AI by API):
https://bitbank.nz/

**Comment by taniman** [comment]
Did you really link a competitor?

Asside from that? I will investigate

**Comment by iller75** [comment]
He did, but on a note it's far from as advanced as PT, but CH was where i started then upgraded to PT.

But as for the signals they provide the good ones are 
CryptoGrow
Mining Hamster
Coinindicator
Cryptosignals

**Comment by Regimax** [comment]
Great idea.  I've had success with Mining Hamster signals.

**Comment by wahbalami** [comment]
+1

**Comment by fjdelaba** [comment]
I would also love this feature

**Comment by DevilSquare** [comment]
guys I have PT and also have minighamster signals subsription.. but I dnt know how to use that signal to automatically buy on PT ? can anyone pleas help?
