### ISSUE TITLE
console view

### ISSUE THREAD

**Issue by woodyalien** [taniman/profit-trailer#893]
Would you please consider adding a console view within PT?
It would be fantastic to SEE (view only) on PT browser interface all messages issued on the console, without the need of logging into the VPS.

Though being informative, the messages on the console are often relevant to make adjustments to our settings so it would be very useful to have easy access to them.

**Comment by Paraoxysmal** [comment]
I *highly* recommend installing teamviewer on your phone, computer and VPS. I also *highly* advise agaisnt it as Im often checking on my baby.

When you install teamviewer make an account, you can add that VPS to 'your computers'. Then access it anywhere you can get on teamviewer + their phone apps arent that bad!

**Comment by Mahons** [comment]
Install SSH on your computer (JuiceSSH on android). Configure Port Forwarding. Then you can simply browse using your local web browser over SSH. No need to login into your VPS. Forwarned as per Paraoxysmal - it's addictive!

**Comment by cristianserban** [comment]
Hi this is on our road map but with lower priority ...
 Thanks ..
