### ISSUE TITLE
[strategy]  PingPong

### ISSUE THREAD

**Issue by freeebits** [taniman/profit-trailer#894]
Hi,

How about new buy strategy buying coins at a specific price like followings?

BTC-ETH_buy_strategy = PRICE
BTC-ETH_buy_value = 0.09

If trailing buy is still supported it would be better!

**Comment by Legedric** [comment]
You don't need a bot to buy/sell at a fixed price. You are able to do this on every exchange by yourself... Using abot for this is rather pointless.

**Comment by Paraoxysmal** [comment]
Actually this might be a great idea, you buy a coin at a volume following a trend. Set your sell price and make the bot SOM it. While it trades everything else

**Comment by Legedric** [comment]
> Actually this might be a great idea, you buy a coin at a volume following a trend. Set your sell price and make the bot SOM it. While it trades everything else

You can do that already today with Profit Trailer...

You buy a coin (for example BTC-ETH) at price X and then you set BTC-ETH_sell_value = Y.
Y is then the profit you want to have from your bought price X.

**So for example:**
- X (your bought price) was 10
- You want to make at least 10% profit on that
- Set BTC-ETH_sell_value = 10 (for 10% profit)
- This will translate to a fixed sell price of 11 for that coin

**Comment by freeebits** [comment]
> You buy a coin (for example BTC-ETH) at price X and then you set BTC-ETH_sell_value = Y.
Y is then the profit you want to have from your bought price X.

This is a buy strategy not a sell with fixed sell value.
So please consider if it's valid request for another buy strategy.

**Comment by keithofaptos** [comment]
Would I need to change anything out than the line commands listed above for each pair being traded, making a listing of pairs in PAIRS.properties?
Anything being changed in DCA?

I really like the control of trading in this possibility.
Could you show me an example?

**Comment by a7777777v** [comment]
This is commonly referred to as PING PONG strategy, set a buy, set a sell. Check this video on a forex example in action: https://youtu.be/evFycXy8ygI?t=1m20s

**Comment by cryptomail2018** [comment]
i prefer it when the Bot actually logs your manual buys and sell as well .. it does not do this so the Sales Log not add up no more ..

**Comment by Cryptosexual** [comment]
I agree with op. I would kindly request the inclusion of specified pricing for buy and sell (ping pong) settings. Extremely useful in a sideways moving market. It is very useful and should be the easiest change to implement. 

@Legedric: if someone has identified a need for a particular strategy, it is reasonable for them to request it. Just because you can't see the value in it, that doesn't make it pointless.

**Comment by YoJeff** [comment]
Housecleaning time.   If this is still a valid feature request, post it in the feature request github.
https://github.com/taniman/profit-trailer-enhancements/issues
