### ISSUE TITLE
current price not updating

### ISSUE THREAD

**Issue by aldrinh07** [taniman/profit-trailer#896]
current prices on pairs suddenly doesnt update, leaving bot with no buys and sells. had to stop and restart to get it back but then happens again after a while. using binance btc

**Comment by danielwpugh** [comment]
Having this same issue on 1.2.6.12 binance btc. Need to restart about once a day.

**Comment by m59peacemaker** [comment]
Same on Binance v .11. I'm not sure restarting even reliably fixes it.

**Comment by m59peacemaker** [comment]
I rebooted my entire machine and the prices are still stuck.

**Comment by taniman** [comment]
@m59peacemaker  than there is something wrong with your system or setup. V.12 indeed needs a reboot once in a while. This is being worked on. There is however nothing wrong with v.11 people ran it for days in a row no problem

**Comment by m59peacemaker** [comment]
@taniman The prices occasionally move now. About every two minutes. That seems very slow. How long should updates be occurring?  I'm fairly confident I didn't do anything wrong / there's nothing wrong with my server.

**Comment by nyhcguy** [comment]
I'm having the same issue with binance.  The coins aren't buying or selling properly.

**Comment by m59peacemaker** [comment]
Try updating to the latest release v1.2.6.14. I am not having that problem on this version.

**Comment by nyhcguy** [comment]
Just updated to v1.2.6.14. I will monitor it.  Thanks.
