### ISSUE TITLE
[Feature Request] GDAX exchange

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#898]
It's one of the best USD to BTC/ETH/LTC (no fee's on maker orders)

API is SUPER SOLID

API Docs:
https://docs.gdax.com

Node.js (official sample code)
https://github.com/coinbase/gdax-node

GDAX trading toolkit (official sample code)
https://github.com/coinbase/gdax-tt 

Crazy high rate limits:
https://docs.gdax.com/#rate-limits

> REST API
> We throttle public endpoints by IP: 3 requests per second, up to 6 requests per second in bursts.
> PRIVATE ENDPOINTS
> We throttle private endpoints by user ID: 5 requests per second, up to 10 requests per second in bursts.
> FINANCIAL INFORMATION EXCHANGE API
> The FIX API throttles each command type (eg.: NewOrderSingle, OrderCancelRequest) to 50 commands per second.

**Comment by a7777777v** [comment]
@lukepighetti

**Comment by cristianserban** [comment]
For the moment we are staying with existing exchanges...
Thanks for understanding...

**Comment by lukepighetti** [comment]
Too bad. GDAX has no maker fees and provides tax documents to USA traders.
