### ISSUE TITLE
[Feature Request] "Sell Now" button in Pairs + DCA log

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#899]
Add a "Sell Now" button under the Sell Strat name in each line in the Pairs Log and DCA log

![image](https://user-images.githubusercontent.com/69228/35535185-a4f007b4-04f7-11e8-8725-e2787479a7c9.png)

This would allow for near instant sale of that one pair.

**Comment by cobuscoetsee** [comment]
+1

**Comment by cristianserban** [comment]
Please use search...

**Comment by a7777777v** [comment]
@cristianserban Where is this in search? I did search, for over 10 minutes. Please link?

![image](https://user-images.githubusercontent.com/69228/35535350-1d7e90d8-04f8-11e8-91d8-de57d6c1fc47.png)

**Comment by taniman** [comment]
#805 
#749 

These are 2. I already marked these as duplicated. Button are coming soon enough
