### ISSUE TITLE
Create Store to allow other developers to add and sell plugins

### ISSUE THREAD

**Issue by cobuscoetsee** [taniman/profit-trailer#900]
It would be great if I as a developer could hook into the front-end and create plugins and sell it on the platform, like Android and Apple. This will allow tools and the platform to be very popular and let other developers add value.

**Comment by cristianserban** [comment]
Well it will be nice... But we are far far away from that...

**Comment by cobuscoetsee** [comment]
Perhaps an API exposing actions like buy sell, if it is documented with swagger then we can run localhost:8080/swagger review api end points and start to do some fancy actions. That will probably be a good start. :) Just a thought.

**Comment by tooraj-enayati** [comment]
Wouldn't that be a backdoor into the exchange?!!  Just use the exchange's API and API keys.

**Comment by cobuscoetsee** [comment]
Agreed that was an example, if we do directly in the exchange we lose
information on sales, so doing everything from one point will make sense.
Sell for example will probably just clear an existing holding immediately I
think this probably needs scoping to what other functions the front-end
might expose.
- Get Sales Log
- Get Pairs Log
- Open an position for a specified pair without it matching the current buy
strategy.
- Close current position
- etc. :)

Thanks, guys you doing amazing work!
