### ISSUE TITLE
Top bar profits in monitor showing 0.00

### ISSUE THREAD

**Issue by pirex00** [taniman/profit-trailer#901]
Hey, the info bar at the very top of the monitor that displays balance, TCV, TPV, profits, and trend. all profits for LW, YD, and TD are all showing 0.00. However in the main monitor page all my profits are showing properly in the big main boxes. Just not in the top bar. Balances and everything else is showing properly in the top bar, but all profits reading 0.00. running version .12

See pic attached

[https://i.imgur.com/gAKyYDg.jpg](url)

**Comment by djcrypto75** [comment]
Yes top bar uses 2 decimals, dashboard uses 8.
