### ISSUE TITLE
24H% doesn't get updated

### ISSUE THREAD

**Issue by famunger** [taniman/profit-trailer#906]
All 24h% on Binance are not updated. Restarted bot, nothing in the log files.

In parallel a Bittrex instance is running on same VPS - there everything is just fine. Heartbeats are showing up fine from both instances.

So now I am very uncertain if bot runs at all. 

<img width="1115" alt="bildschirmfoto 2018-01-30 um 10 55 07" src="https://user-images.githubusercontent.com/32521416/35559928-39a43ad8-05ac-11e8-8f51-2927b4f220f8.png">

<img width="1107" alt="bildschirmfoto 2018-01-30 um 10 57 17" src="https://user-images.githubusercontent.com/32521416/35559981-5e18e878-05ac-11e8-92f6-ef4b427243ef.png">

**Comment by JulesBern** [comment]
This is a known issue and a reboot of the bot seems to fix it. Of course rebooting the bot every few hours is not a long term solution, but it is a bandaid temp solution. You can either restart the bot or create a cron job that can restart it.

**Comment by famunger** [comment]
I did restart the bot using pm2 restart 0 - but doesn't help. But good to know that this is an known issue.

**Comment by djcrypto75** [comment]
Update to last version :)

**Comment by BaGRoS** [comment]
Same on version v1.2.6.16
