### ISSUE TITLE
PT buying pairs and not tracking them in the GUI, so doesn't trigger sell order... happening again. Serious issue. 

### ISSUE THREAD

**Issue by commandocrypto** [taniman/profit-trailer#907]
PT bought a pair per NormalStrategyRunner, the coins are in my binance account, but the PT GUI can't find the pair... so it is not tracking it in any way...  Then it tried to rebuy the same pair just two minutes later but gave me a minimum spend error... and I don't know why that is either. It just bought the pair a few minutes ago, and now can't buy it for the same minimum cost. I have enough funds to trade and I am not even close to 5% use of my capital. That's a different issue that I'll have to solve... 

I had this error two weeks ago, it happened about 6 times in a few hours to I shutdown the bot.
Last night I resetup the bot without Feeder, and use simple configurations and only four pairs to trade from. 

The purchase is recorded in the PT log, right there in black and white... Its a full purchase, not dust. It is not in the GUI at all. 

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1677292/ProfitTrailer.log)
GUI is completely empty except for a different pair in DCA. It is still tracking the pair it just bought in "possible buy log" and tried to buy it again. 

Thank you for your help.

**Comment by Paraoxysmal** [comment]
I'm on binance, using feeder. I had to downgrade feeder and use version .10 of trailer. (.10 I'm referring to the what a sunday release incase my number is wrong.) Since I downgraded, my bot has had 0 issues

**Comment by commandocrypto** [comment]
Two weeks ago when I first encountered the issue, I thought it was caused by feeder. Last night when I decided to setup PT again, I removed the feeder-modified files and started fresh with PT-only files and I am not using feeder at all, and haven’t launched it, so the files haven’t been affected by feeder. 

This is not an issue of orders expiring and just buying some dust. I have that issue also. But I understand that sometimes the bot can’t execute a full order.

But the bot should NEVER be buying something and just not track that it bought it and posture immediately to sell it at a profit. That is the entire point of a bot.

**Comment by TheSkyScraper** [comment]
I'm having the same issue with 1.2.6.12 while not running feeder.

**Comment by TheSkyScraper** [comment]
I'm having a similar issue with 1.2.6.12 while not running feeder. It seems the GUI/bot is not updating. I restarted the bot and a few of my pairs immediately jumped to 10% profit. I checked the charts and it should have updated that hours ago because it wasn't sudden.

**Comment by JulesBern** [comment]
I can confirm that this issue has been persistent on Binance with 1.2.6.12 version. I restart of the bot seems to clear the issue, so I wrote a shell script that restarts the bot every 6 hours. This is a temporary fix, but it should def be addressed.

**Comment by GGaulin** [comment]
I also have the issue with DCA and Pending not updating. The Top shows the bot is connected and communicating with Binance. I also restart to clear the issue. I cannot determine if this is a GUI only issue, it might be because the bot tried to sell at pair at the same time I was executing a manual sale of the pair. I will next attach WireShark to see what data is flowing in/out of the bot when this happens.

**Comment by taniman** [comment]
V1.2.6.12 should not be used with binance because of multiple known issues. Upgrade to the latest version
