### ISSUE TITLE
Issue with moving PT to new server

### ISSUE THREAD

**Issue by PoconoCrypto** [taniman/profit-trailer#908]
I need to move PT to another server, I copied over the entire ProfitTrailer folder to the new server, however when launching it, all the existing DCA are now in pairs not knowing it was a DCA and the sales log shows 0. I did try copying over the old log that had the data but it is acting like it is a new install.

**Comment by YoJeff** [comment]
This is not support.

**Comment by PoconoCrypto** [comment]
How can it not be supported? I have a server that is end of lease and needs to be sent back.

**Comment by YoJeff** [comment]
Github issues are for bugs only.   If you need support - go through regular support channels.
