### ISSUE TITLE
Smell like scam

### ISSUE THREAD

**Issue by Alkaris** [taniman/profit-trailer#909]
This smell of a scam, just like BitConnect.

Too generic looking like every other trading bot out there, just like those stock market trading bots that you see around on the Internet. Comments and Testimonials look like they're from yourselves trying to pretending to be written by other people. That and the fact you don't share source code samples here on GitHub, a place where you are suppose to share code works of the bot itself.

Can't see the source code? Can't trust the software.

**Comment by cristianserban** [comment]
thanks for your interest in our software.
maybe you should also check out our discord group....

anyway since this is bug/feature req system we are closing this

thanks for understanding
