### ISSUE TITLE
Binance - Allow extra API keys so no Ban

### ISSUE THREAD

**Issue by seertenedos** [taniman/profit-trailer#910]
For Binance could you allow a comma separated list of API keys that get used for everything but doing the actual trade orders and rotate between them to help prevent banning. It has been suggested in posts i read that for Binance the api limits are per key not account for IP so if there were more keys for the bot to use when getting prices etc and non trading actions that may work around the issue for now for those with a large number of pairs. For Binance the licenced pair could be the one used for trading and the others could be used to get data.

**Comment by a7777777v** [comment]
I would love this to be added. EonBot has similar, multiple pairs, and i believe it rotates through them round robin. But keeping one pair saved for buy/sell is better.
