### ISSUE TITLE
[Feature Request] Manual double down on UI

### ISSUE THREAD

**Issue by seertenedos** [taniman/profit-trailer#911]
Could a button be added to the DCA UI and maybe even pairs UI to double down? I find that for some coins i want to double them down outside of my DCA settings but only on a case by case basis based on market info. Eg it may have doubled down 6 times already but market looks good so it would be nice to be able to click a button to double down again. Another case is where it has not reached a double down level yet but market looks like it will take off so i want to double down before the normal DCA levels. 

I know i could do a config just for that coin on the spot but then that would affect future trades for the coin and i need to set percentage level in DCA that matches the current percentage level exactly. A button is easier.

**Comment by cristianserban** [comment]
there are a lot of requests of adding manual interactions inside the UI
we will add to our review this one also
thanks
