### ISSUE TITLE
PT cant see all pairs, 0 dust, not seeing funds

### ISSUE THREAD

**Issue by Seabhac1** [taniman/profit-trailer#913]
PT can only see 3 out of 8 pairs on Binance, it shows 0 dust on the PT moniter and it is not showing the full value of the funds. I have rebooted PT and internet connection. How should I proceed?

**Comment by Seabhac1** [comment]
It now sees 5 in Dust Log, and 1 in pairs log. Is it normal for PT not to see all that is in Binance intermittantly? Not only dust.

**Comment by JulesBern** [comment]
Just replace the ProfitTrailer.jar on the old version with the new one and you should see everything back. Make sure you stop the bot first and backup everything just in case.

**Comment by taniman** [comment]
not an issue. please contact support for further help
