### ISSUE TITLE
Ticker errors on running 1.2.6.14

### ISSUE THREAD

**Issue by GeoffBoyle** [taniman/profit-trailer#916]
On first run, the gui displays but with no financial data. 
Telegram message for startup is sent. 
I was advised to leave it running, after ten minutes or so the sales log displays in the gui but DCA and Pairs are empty. 
Json backups seem to be made successfully 
The following errors repeats in terminal multiple times every few minutes.

2018-01-30 22:16:16 ERROR ProfitTrailerService - Error occured in ticker, message We got incorrect data, retrying, result:

Running on Server 2012 R2 
Java 8 (build 1.8.0_151-b12)
Binance - BTC.
No errors in 1.2.6.11 though similar errors in 12.

**Comment by cristianserban** [comment]
did you get also in log the heartbeats?

**Comment by taniman** [comment]
the error says it right there. We got incorrect data.

**Comment by GeoffBoyle** [comment]
Then the bot doesn't run. The error repeats, no DCA or Pair values are ever displayed. 
I don't care about an occasional error, this is continuous.

**Comment by GeoffBoyle** [comment]
Log in debug mode.

[ProfitTrailer_v14_debug_partial.log](https://github.com/taniman/profit-trailer/files/1682147/ProfitTrailer_v14_debug_partial.log)

**Comment by fboleto** [comment]
@GeoffBoyle  I had the same with mine. The solution was simple, my Firewall was blocking requests to stream.binance.com on port 9443 . Once I allowed it, everything is working correctly. I hope it helps

**Comment by GeoffBoyle** [comment]
Many thanks @fboleto, opening port 9443 outbound did indeed fix the problem. 
If access to specific ports is required maybe it should be added to the wiki.

**Comment by JerryLingle** [comment]
exactly what steps should I take to fix this? 
I do not know about opening ports

**Comment by TrueOsiris** [comment]
Same issue here. Firewall is open on that port.
Worked perfectly until a week ago.

**Comment by aries-delossantos** [comment]
Binance is currently down
https://steemit.com/bitcoin/@kingscrown/binance-down-for-next-12-hours-unannounced

**Comment by TrueOsiris** [comment]
Again?
