### ISSUE TITLE
[BUG] 1.2.6.14 - 24h% not in pending pairs (Binance)

### ISSUE THREAD

**Issue by jalapeno777** [taniman/profit-trailer#918]
Pairs in the pending section do not have 24h% displayed from Binance.

**Comment by MojoManagement** [comment]
Do you have any BinanceWebSocketAdapter24Ticker errors in your log?

**Comment by jalapeno777** [comment]
I do not....in fact the 24h% shows up fine in the other areas of the console...just not in the pending pairs.

**Comment by djcrypto75** [comment]
Hey, tried to replicate, its working fine here. Screenshots please :)

**Comment by YoJeff** [comment]
Looking like it's fixed.   Closing
