### ISSUE TITLE
No buys in 4 hours

### ISSUE THREAD

**Issue by virender007** [taniman/profit-trailer#919]
I have followed all instructions on PT and its working but I hasn't bought anything in 4 hours, it shows possible buy logs 8 and Config : Off (in red). Should I change anything?PS : I'm trading with $450+ budget. 
![untitled](https://user-images.githubusercontent.com/35955610/35603560-78a8388c-0670-11e8-9cbd-353877bd5d59.jpg)

**Comment by keithofaptos** [comment]
The market is tanking.where exaclty is the bot supposed to find a market buy?patience.when the market swings back up it will be buying and selling a lot.
