### ISSUE TITLE
LATEST VERSION 

### ISSUE THREAD

**Issue by cryptomail2018** [taniman/profit-trailer#920]
cant update price and date in Pair Folder or Hotconfig . 

Example : this wont work 

XRPBTC_Price_Bought = 0.00850000
XRPBTC_Date_Bought = 2018/01/08
EOSBTC_Price_Bought = 0.00037821
LTCBTC_Price_Bought = 0.26651844

**Comment by cristianserban** [comment]
do you see any errors inside bot console or log file ?

**Comment by taniman** [comment]
Please read the wiki on more time. That is not the way to set bought price
