### ISSUE TITLE
[FEATURE REQUEST] Safety setting for pumped coins

### ISSUE THREAD

**Issue by Christian862** [taniman/profit-trailer#922]
So a few times now my PT bot has bought just after a coin has been pumped and is not yet on an aggressive downtrend, which as you can expect does not fare well for making profit and results in a very large bag with multiple DCAs over a few days. From what i've read you have a feature in PTF to avoid this from happening, among the other things that PTF does however i have a simple suggestion that i think would greatly improve the quality of buys in stock PT. Someone has most likely already thought about it, however it is one additional setting in the pairs file with the following functionality: 

trendLimit = 40       ////coin change percentage, user would set this in pairs file
if(coinpair.get24HourChange() > trendLimit)
{
      coinpair_trading_enabled = false    ////don't allow PT to buy this coin for a period of time
}

I think this is an easy way to improve the quality of PT buys but not detract from users purchasing the PTF add on as it of course has much more functionality. I know for myself this would have saved me on multiple occasions from buying at the top of an aggressive 24Hr uptrend which ends up being a long expensive bag. Fantastic job on the bot so far! thanks for your consideration.

**Comment by clownfish44** [comment]
Wonderful idea we need this!!!!!!!!

**Comment by mikobeaudry** [comment]
+1 A+ SUGGESTION!

**Comment by oktay50000** [comment]
+100

**Comment by mikobeaudry** [comment]
Good call!

**Comment by taniman** [comment]
please please search before creating issues. This has been asked multiple times!!! and is even on the road map already
