### ISSUE TITLE
Pending log

### ISSUE THREAD

**Issue by SinFuego1** [taniman/profit-trailer#926]
Hi,

Why is it that my PENDING log is getting filled with fixed items by the bot?  It should immediately cancel or fill any items, but I see a rising number of pending items coming up. Is there a setting wrong here ? 

The pending items grow slowly. I now have about 6 since sunday. I had one saturday out of  nowhere. I have now installed the latest version of the bot aswel. I used the previous one. I use the binance setup.

#sell options
sell_fillOrKill = false
sell_immediateOrCancel = true

#buy options
buy_fillOrKill = false
buy_immediateOrCancel = true

testMode=false

**Comment by Afzsufi** [comment]
If you have following line
ALL_pending_order_wait_time = 1440
Or any number other than 0 then it will put in pending log after that many minutes

**Comment by Regimax** [comment]
What happens after 1440 minute?  Does it go back into the DCA log?  Or does it just stay in the pending long?  Thanks- R

**Comment by SgtBatten** [comment]
It goes into the pending log after that many minutes
