### ISSUE TITLE
[Feature request] Read-Only and Admin only web interface 

### ISSUE THREAD

**Issue by rayjonesy** [taniman/profit-trailer#929]
Currently there is only a full admin interface, which if you enable the hotconfig is an issue if someone else has rights to access the page. 

Request a second read-only or guest option with a different password which has no hotconfig option viewable. 

You can then share your URL if you so decide for others in your circle to view without the hotconfig option.

**Comment by RichardKeschinger** [comment]
would be pretty cool

**Comment by Maze111** [comment]
+1

**Comment by YoJeff** [comment]
Developer resources are finite, and supporting "club bots" would not make my list.   But let's see what @taniman says about it...
