### ISSUE TITLE
MONITOR: Totals Tab Percent loss

### ISSUE THREAD

**Issue by jadiesel** [taniman/profit-trailer#93]
Would love to see a percent loss from Total Current Value to Total Pending Value. And maybe the Total Loss in BTC.  That would make it easy to do something like "Oh, I can afford to panic sell that shit and start over" or "Crap, I can't sell em all at the moment"

Because, sometimes you just want to smack em all flat and start over in a new market pattern.

**Comment by djcrypto75** [comment]
Hey @jadiesel 

Can you update this one and make it for todays GUI. It seems like a old version of the GUI :)
