### ISSUE TITLE
[BUG] EMA lines calculated wrong (EMAGAIN & EMASPREAD examples) (Binance) V.14

### ISSUE THREAD

**Issue by Douwetje** [taniman/profit-trailer#930]
Hello,

I am using the EMAGAIN strategy and I may have encountered a bug. 
My bot just bought ICXBTC twice (at 16:37 and 16:46 for the price of 0.00074800 and 0.00075270 respectively). These two prices however are above the fast_ema line.
I saw the first buy and PT said the current value was something like -3. This was about right for the slow moving EMA line, but not for the fast moving EMA line (the price was above this line).
The wiki states the following: ALL_buy_value is a percentage below or above the lowest of the 2 EMA lines.
So it should have looked at both of the lines right?

My indicators are: 
EMA_period = 900
EMA_1 = 36
EMA_2 = 9

These were my buy settings:
ALL_buy_strategy = EMAGAIN
ALL_buy_value = -1.01
ALL_trailing_buy = 0.36

Edit: I also found an example today at 16:06. The WTCBTC price is higher than the fast EMA line, but PT says its current value is -3.10 (which correlates with the slow EMA line).
![capture](https://user-images.githubusercontent.com/36005896/35685670-a1e00d7e-076a-11e8-9c2b-dd42d2a76cb8.PNG)

I hope you can help me.

Greetings,
Douwe

**Comment by Douwetje** [comment]
I also have an example for EMASPREAD.
The spread is next to nothing, but PT says the spread is -8.
I think the EMA lines are not calculated correctly
![capture2](https://user-images.githubusercontent.com/36005896/35706898-d9aeb7ae-07a7-11e8-9127-bf995a075f03.PNG)

**Comment by a7777777v** [comment]
Can you test EMACROSS?

**Comment by taniman** [comment]
> Edit: I also found an example today at 16:06. The WTCBTC price is higher than the fast EMA line, but PT says its current value is -3.10 (which correlates with the slow EMA line).

The lowest of the 2 lines is used to calculate. so at 16:06 which of the lines was lower? fast or slow?

**Comment by Douwetje** [comment]
The fast EMA line was lower.

But, I reinstalled V.14 again and this seemed to have fixed the problem, but I will continue to watch it.
