### ISSUE TITLE
[FEATURE REQUEST] Double down button on web interface

### ISSUE THREAD

**Issue by jSevyn** [taniman/profit-trailer#932]
I like the DCA Anderson strategy but would rather stick to the stock LowBB setting for profit trailer. Is there a way we can have a column created for manual buying? Maybe have a 1X and 2X button in that column. The 1X button would just purchase additional coins that equal the original ALL_max_cost or original purchase quantity and the 2X button would double the current amount of coins held? This is a nice feature that was used on the trading platform I was using when day trading stocks and would love to see it added to this interface if possible!

**Comment by vaidehiapawar** [comment]
I think PT should have an option  that "If Available" and  "Option Selected" then PT should switch between BTC & ETH to trade based on market conditions

**Comment by jSevyn** [comment]
I was not talking about switching from BTC to ETH. I was talking about something similar to the Anderson buy strategy but a button on the web interface to make it manual so the person can do it when they want to. I dont even know what you are talking about cause it has nothing to do with what I was asking for???

**Comment by cristianserban** [comment]
https://github.com/taniman/profit-trailer/issues/360
