### ISSUE TITLE
Your save file is corrupted 

### ISSUE THREAD

**Issue by meinit** [taniman/profit-trailer#933]
Hello, New user, been running for a day all fine, then today get home to find 'Your save file is corrupted' I've had a look through the files and all seem ok. Done a google search. 
Please can you let me know where or how I can get my corrupted save file, 
Ive no backup at all.

Many Thamnks
![save-file](https://user-images.githubusercontent.com/35960677/35641224-7dfca4de-06b7-11e8-8128-3ff238592813.jpg)

**Comment by MojoManagement** [comment]
Do you have a ProfitTrailerData.json.backup file?

**Comment by meinit** [comment]
Ahh haa, yes I do, Is that my save file then? Ive open as a txt file and it does have buy info in it, so do i just rename it ProfitTrailerData.json.
Thank you for you last reply
