### ISSUE TITLE
[FEATURE REQUEST] Simplify coin-pair enabled settings

### ISSUE THREAD

**Issue by tj78492** [taniman/profit-trailer#938]
Instead of having to input pairs could we instead use only the coin name for coin-pair settings?

So instead of:
NEOBTC_enabled_pair = true
we'd use:
NEO_enabled_pair = true

The actual pair can be inferred with relatively simple logic using trading.exchange and market.

This would allow settings to be more portable between users, exchanges, and markets.
The same pairs and DCA files would work if you wanted to use bittrex or binance, or change from BTC to ETH markets.

It would also simplify the documentation and make adding future exchanges easier

**Comment by taniman** [comment]
see #346
