### ISSUE TITLE
Support for Kraken

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#942]
I have been using Kraken for a while now and would love to see it supported by PT. Any plans on adding Kraken or any other exchanges?

https://www.kraken.com/help/api

**Comment by ACETyr** [comment]
Kraken has a very small assortment of trade options. More exchange options would be great especially as long as BINA has API strangeness, TREX does not accept new users and POLO is meh... but Kraken is rather near the bottom of the list of valid exchanges (few pairs), one of the worst trading interfaces.
