### ISSUE TITLE
Emotionless trading

### ISSUE THREAD

**Issue by efahrenholz** [taniman/profit-trailer#943]
So I have bit of an odd improvement. Our bots trade based on what we tell the bot to do. It's supposed to help us take emotion out, and trade while we are unavailable. I did some soul searching and have determined that these bots are trading with emotion. We trade for a gain and we set a stop loss to prevent a loss. What if we added an option to create a random stop loss level (in a defined range) and a random gain amount (in a defined range)? This would truly remove some of the predictable human nature programmed into the bot. The bot should still follow the defined strategy rules, but let's shake it up a little and see how much better or worse our profit is. I know it's crazy to think like that but if you think about it, setting a strict gain limit to hit is our way of influencing emotion into the bot. There are times where I missed a sell opportunity because my bot wanted that 1% gain and the price moved down fast. If we set a range (0.5 to 1%) randomly, we might get some interesting results. If we remove some of the human in the bot that limits our own profitability, we might see some unexpected but welcome gains.

Thank you for your consideration.

**Comment by YoJeff** [comment]
This is something you can do yourself by setting quasi-random sell values in your pairs file.   Don't see this as a core bot function.
