### ISSUE TITLE
[FEATURE REQUEST] GUI sell button

### ISSUE THREAD

**Issue by Alec423** [taniman/profit-trailer#946]
I find PT's GUI very useful to track my gains and losses. The bot can be very efficient but I'd like to be able to monitor my percentages and sell directly form the GUI at the price I see displayed, in order to avoid cases where the coin goes up 3% for a couple of minutes but the bot waits too much and ends up seeling at 2%

**Comment by james151br** [comment]
Yes, this will be a good feature. Sometimes we lost a good profit due the lack of this problem.
