### ISSUE TITLE
Copy function on Sales log includes extra columns

### ISSUE THREAD

**Issue by ba32107** [taniman/profit-trailer#948]
Hi,

Using 1.2.6.14. If I copy paste on the Sales Log, I get the following columns between 'Trigger%' and 'Sold Amount':
Profit BTC | Profit | BTC

In reality, there is only one column between them: Profit BTC. There are two extra columns: Profit and BTC (separate columns).

This is the actual first row of my copy-paste from the bot:
#	Date	Coin	Sell Strat	Bought Price	Sold Price	Profit%	Trigger%	Profit BTC	Profit	BTC	Sold Amount	Bought Cost	Sold Value

This problem is making it difficult to use current tracking methods (Excel sheets).

**Comment by YoJeff** [comment]
You mean copy/paste off the web page, instead of clicking Copy or Excel???

**Comment by ba32107** [comment]
I mean using the Copy button in Profit Trailer

**Comment by djcrypto75** [comment]
Excel button works better. Will work on a solution for Copy.

**Comment by cryptomail2018** [comment]
why not make a hyperlink and a addon with a attachment to a Excel folder with the perfect spreadsheet where all data is automatically logged every 6 hours also where we can link multiple logs of different bots , just saying ,, its a great software program but it lacks a bit on the finishing touches for trailing of records and the likes .. i dont have time to site every day several hours filling in spreadsheets. but  i do like to know my ups and downs throughout the trading .. im sure this is a advanced mathematical program with endless possibilities for more advanced options , i am not skilled enough to be able to accomplish that.

**Comment by YoJeff** [comment]
Because the sales log is supposed to be a quick-view of your recent performance.  Not an exhaustive recreation of your whole trading account.
