### ISSUE TITLE
DCA log not showing my latest DCA's ?

### ISSUE THREAD

**Issue by mather21** [taniman/profit-trailer#950]
Hi 

I just installed and set up trailer on my server got it running it made two sales and two landed in DCA i altered a couple of buy setting today and since then the DCA log is empty but the GUI still shows half my money in DCA any ideas whats wrong ?

**Comment by YoJeff** [comment]
Bugs only here, use support.
https://wiki.profittrailer.io/doku.php

**Comment by mather21** [comment]
Hi

I want to use my affiliate code where can i find it?

Cheers

James

**Comment by djcrypto75** [comment]
Use support.profittrailer.com 
GitHub is for bugs
