### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by edgemont** [taniman/profit-trailer#953]
I am running PT on Vultr Ubuntu on 2048 memory and when running PT along I don't encounter any issues, however when adding PT-Feeder (after a few hours) the "current value" field becomes populated with just zeros. 

Rebooting PT-Trailer fixes this issue...for another 4-8 hours.

So, I suspect there is a memory leak occurring.

**Comment by a7777777v** [comment]
keep in mind Feeder is made by a different group

**Comment by taniman** [comment]
I fail to see the relation between current value being zero and a memory leak.  
If there is no error in your log file saying java heap out of memory or something similar, that means you don't have a memory problem.

Also what version of the bot are you running? 
And are you getting error in PT log file?

As the comment above states. PTF is NOT a PT product
