### ISSUE TITLE
.14 Binance still not updating 

### ISSUE THREAD

**Issue by FatedOne** [taniman/profit-trailer#956]
I restarted my bot before bed, went to sleep, woke up and saw that prices were wrong, restarted bot and 3 coin pairs went green and sold instantly. CMD windows was still showing that it was updating with regular heartbeat messages all the way up until I restarted. If you have any questions about my set up let me know.

**Comment by jbhitman** [comment]
Same here

**Comment by machyy1** [comment]
Same here

**Comment by artfusion** [comment]
same here

**Comment by machyy1** [comment]
Could something be added, like, check if prices have not changed in the last 2 minutes on any coin, and if so, reset the connection?

**Comment by machyy1** [comment]
Is anyone with this issue not running on Windows?

**Comment by djbadders** [comment]
I am running on linux and have had the same issue at least twice in 12 hours

**Comment by BrotherMunk** [comment]
I already gave up on the new release and went back to an older version. Too
many problems and no help from team.

**Comment by swoopsus** [comment]
Same

**Comment by JSEM100** [comment]
Ditto, though it seems to be occurring less often on this release, I've still had to restart the bot a couple of times.

**Comment by 4Ykw** [comment]
Check if you not getting this error in your logs #957

**Comment by BrotherMunk** [comment]
It was a constant flow of java errors the same as #957 shows.

**Comment by timh77** [comment]
Unfortunately still experiencing the same with v15.
Logs don't show anything.

**Comment by stucarney** [comment]
I have the same issue, with v15, and I'm running on a VPS, with Ubuntu, and PM2.

**Comment by smoochy** [comment]
I have the same issue with .15. Running VPS on WIndows Server 2016. Java 8 Update 162 with the start.cmd containing:

java -jar ProfitTrailer.jar -XX:+UseConcMarkSweepGC -Xmx512m -Xms4096m
pause

I switched back to .14 where I did not experience the issue. Had the issue with .12 though.

**Comment by tmoffett** [comment]
Same issue with 15. 

windows server 2016
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by TalesFromThaCrypt** [comment]
Same issue also, with v15, running on a VPS, with Ubuntu

**Comment by cisops** [comment]
Can someone recommend the best stable version where this issue doesn't exist? Very frustrating and missing opportunities to sell bags here too.

**Comment by bitcointrucker** [comment]
@cisops I'm using 1.2.6.10... working fine.

**Comment by BrotherMunk** [comment]
I was able to fix my system watching this video and link. The video is discussing the feeder but covers how to check java errors.

https://www.youtube.com/watch?v=AgtVgeiMcs8

https://jsonlint.com

**Comment by BrotherMunk** [comment]
btw.... the new version is worth the trouble to fix the situation.

**Comment by LeonidStern** [comment]
DEBUG BinanceWS - temp log - resetting websocket sessions

this is message from debug log
