### ISSUE TITLE
[bug] PT can't work on iOS9

### ISSUE THREAD

**Issue by monkuo** [taniman/profit-trailer#958]
in JS 

function cpPendingLog (pendingLogData) {
    let sumVals = ........
     ...
}
Unexpected identifier 'sumVals'

**Comment by djcrypto75** [comment]
Screenshot and more details please

**Comment by monkuo** [comment]
![s__94543876](https://user-images.githubusercontent.com/2976882/35766824-3c033b00-091a-11e8-9ebc-174c4d33fda8.jpg)
![2018-02-03 19 41 54](https://user-images.githubusercontent.com/2976882/35766826-54652082-091a-11e8-8ba2-14751886fe2d.jpg)

**Comment by djcrypto75** [comment]
Tested and works here. Try different browser or update. Also check with support. No bug.

**Comment by monkuo** [comment]
I download v1.2.6.15
Still can't work on chrome and safari 
So you will not support iOS 9 ?

**Comment by djcrypto75** [comment]
As said before, it works on iOS9. So issue is local. Support issue :)

**Comment by kyro38** [comment]
btw the keyword `let` is not supported on iOS 9,
