### ISSUE TITLE
[Feature Request] Buy & Hold

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#962]
I would like to set specific pairs to be bought, DCA'd, and not sold = hold

ETH-BTC = HOLD
XRB-BTC = HOLD
XRM-BTC = HOLD
NEO-BTC = HOLD

OR the ability to set a very high % return per pair, like 1000% before selling. Forgive me if this is possible per pair, tell me how

**Comment by YoJeff** [comment]
You can do either of these things.   Visit support, this is for bugs.
https://wiki.profittrailer.io/doku.php/start
