### ISSUE TITLE
Sale Log problem

### ISSUE THREAD

**Issue by ekateos** [taniman/profit-trailer#966]
since 12:05 am EST of 2/2/18 up to 12:pm the same day i had in my pending log 13 items of which the 8 items it was sold on trade but the sale log never recorded these sales it wasn't an manual trading issue  
any ideas , maybe it is bug issue with BINANCE PLEASE ADVISE 
THANK YOU VERY MUCH
KOSTAS VLACHOS

**Comment by YoJeff** [comment]
Pendings do not show up in sales by design currently.    It's being considered.
