### ISSUE TITLE
GainStrategyRunner problem 

### ISSUE THREAD

**Issue by ekateos** [taniman/profit-trailer#967]
|profit-t | 2018-02-02 19:58 +00:00: 2018-02-02 19:58:49 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:58 +00:00: 2018-02-02 19:58:54 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:58 +00:00: 2018-02-02 19:58:59 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:04 ERROR GainStrategyRunner - An error occured

0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:09 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:14 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:19 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:24 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:29 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:34 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:39 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:44 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:49 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:54 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 19:59 +00:00: 2018-02-02 19:59:59 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:04 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:09 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:14 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:19 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:24 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:29 ERROR GainStrategyRunner - An error occured
0|profit-t | 2018-02-02 20:00 +00:00: 2018-02-02 20:00:34 ERROR GainStrategyRunn

**Comment by cristianserban** [comment]
Are you on vps?

**Comment by cristianserban** [comment]
Please check your firewall settings

**Comment by YoJeff** [comment]
Please use support.
