### ISSUE TITLE
Unclear definition of LOWBB strategy

### ISSUE THREAD

**Issue by siedi** [taniman/profit-trailer#968]
The calculation of the LOWBB strategy is misleading. In https://wiki.profittrailer.io/doku.php/basic_pt_buy_and_sell_logic#buying_with_lowbb it says 

> the current price must be equal to or less than the value of the LOWBB band multiplied by (1 + ALL_buy_value expressed as a percentage)

which would mean

`Buy Price = LOWBB * (1 + buy_value/100)`

and later (for negative values)
`Buy Price = LOWBB - ((HIGHBB - LOWBB) * ABS(buy_value)/100)`

But these are different calculations. 

What is the right one?

**Comment by YoJeff** [comment]
I think the first one was just meant to be simple napkin-style math suggesting that the calculation point was lowbb.   But I agree it should probably be eliminated.

**Comment by siedi** [comment]
OK, thx. will change my tradingview script then.

**Comment by YoJeff** [comment]
The wiki has been retooled for v2.x.    If this is still an issue -- resubmit for current version.
