### ISSUE TITLE
Calculation of Bought Price in Sales Log doesn't seem right

### ISSUE THREAD

**Issue by nstefi** [taniman/profit-trailer#970]
The Bought Price column in Sales Log should show the average price value when there are multiple buys (DCA), right?
I checked this case - this is from my Sales Log:
![image](https://user-images.githubusercontent.com/6478474/35754799-ce7aec28-0832-11e8-87e0-0f929454df3f.png)

and this is from Binance's Trade History page, I pasted to Excel and calculated the average price below in blue:
![image](https://user-images.githubusercontent.com/6478474/35754855-fd8427e6-0832-11e8-8cf6-146e65001620.png)

so the average bought price should be 0.01442033, not 0.01432725

**Comment by YoJeff** [comment]
What's your average less fees?

**Comment by mayday79** [comment]
The Average Price is correct!

You have to summerize all the total costs and than divide them with the sum of all coins...
so in your case:

1st buy = 0.01472100
2nd buy = 0.01449200
3rd buy= = 0.10198848

The sum of all is 0.20803167 and this must be divided by a total of 14.52 coins.

0.20803167 : 14.52 = 0.01432725 BTC....

So everything is correct ;-)

**Comment by YoJeff** [comment]
Thanks, I was too lazy to calculate.   Closing.

**Comment by nstefi** [comment]
I see, I forgot to multiply with the amounts.
Thanks a lot and sorry about that.
But I see that the fees are not accounted for. Probably because those are deducted from my BNB.
