### ISSUE TITLE
Profit Trailer Telegram alerts on LOWBB and HIGHBB

### ISSUE THREAD

**Issue by GitHubmahe** [taniman/profit-trailer#971]
hey  guys, i just think it would be a great additional feature, if PT could send you a Telegram every time a pair of your choice hits LOWBB or HIGHBB; as it could represent an opportunity to buy an oversold or to sell and overpriced crypto, you are keeping an eye in // 🚀

**Comment by JulesBern** [comment]
Extending the alert system of the bot when certain signals are triggered would be amazing. It would allow us to potentially confirm other signals and make manual traders with larger amounts, this would be a great complement to the automation of the bot.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
