### ISSUE TITLE
New buy Strategy = LOWBB>EMA

### ISSUE THREAD

**Issue by angelsomar** [taniman/profit-trailer#973]
Hello this is an Idea of purchase strategy according to the trend, remember that the trend is our best friend

In order to decrease the recurrent entry to "DCA"

The idea is to combine the "LowBB" strategy with the EMA indicator

Only Consider buying if LowBB is above the EMA = 200 line

or near school with a tolerance value.

this would help us to operate with the trend of the moment this ema should be calculated in the same period of the example BB

BB_period = 900
BB_sma = 20
BB_ema = 200
![lowbbema](https://user-images.githubusercontent.com/36096512/35763801-0d975ac8-0882-11e8-8562-a0badc37e841.PNG)

**Comment by taniman** [comment]
We will make combining strategies possible in next major release. If that i not sufficient to implement this strategy we will look into this one further. check the milestone for 1.2.7
