### ISSUE TITLE
Idea to make LOWBB accept multiple triggers

### ISSUE THREAD

**Issue by angelsomar** [taniman/profit-trailer#974]
#In DCA
buy_strategy = LOWBB
buy_available_volume_trigger = 49
buy_value = -2.8
buy_trigger_1 = -3.5
buy_trigger_2 = -5.5
buy_trigger_3 = -7.5
buy_trigger_4 = -9.5
buy_trigger_5 = -12.5

Hello It would be good if this strategy were valid, my intention is that when

-3.5% look for the best price with lowbb, that is, buy below -3.5%
So with the others (-5.5 -7.5 -9.5 -12.5)

my doubt is born because with buy_strategy = ANDERSON he does not look for the best price simply buy in -3.4 so this in -4.5%

**Comment by alexdolli** [comment]
You can add a trailing_buy in the Anderson strategy.

**Comment by Macflurry26** [comment]
Could Anderson be configured to have an option that allows its percentages work against BB levels instead of Gain/Loss?

**Comment by angelsomar** [comment]
Hello and thanks for the contribution, but the truth is a strength of bot is DCA, the whole is to reserve the balance so that it can work thanks
