### ISSUE TITLE
DOUBT Being able to trade with BNB

### ISSUE THREAD

**Issue by angelsomar** [taniman/profit-trailer#976]
Before the PT I manually won with BNB, I would like to know if there is a way to indicate to the Bot that I trade with the BNBBTC pair but I always want to have 2 BNB, that is, to trade with everything above 2 BNB

Something like

BNBBTC_min_buy_balance = 2

BNBBTC_min_sell_balance = 2

my intention is to trade with all BNBs above 2 BNB

and it's a way to ensure that there are always for commissions

**Comment by taniman** [comment]
No, this is not possible. but is on the future milestones
