### ISSUE TITLE
Enhanncements: BB settings: StdDev and offset, EMACROSS SELL strategy, High freq. high volatility pumpish pair selling option that gives you the returns of a peak without trailing.

### ISSUE THREAD

**Issue by Utone** [taniman/profit-trailer#977]
These BB settings BB settings StdDev and offset are pretty useful in setting the BB bands to trigger just like you need them to when for instance using HIGHBB as an exit strategy for EMACROSS..

But this all is more of a makeshift solution to not having EMACROSS as an exit / SELL strategy, which would be great..

Like here: Now it triggers a sell at a safe exit points at around HighBB 0:
[img]https://ptpimg.me/9t2nu2.png[/img]

Instead of here with the BB sma 40:
[img]https://ptpimg.me/ija5yf.png[/img]
(Of course  you can set HIGH BB levels but with out trailing buy sell being much of an option in these high volume high volatility goldmine pairs, it's not even close to optimal, as you need to set DCA without trail (also a potential risk, not only are you losing better buy levels , but when it dumps your static settings will eat.. Still haven't had much trouble on this one theres plenty of usable volatility for DCA to get out of a position.)

Looking for a good SELL strategy for high volatility high volume pairs on Binance (as you se its quite pumpy) Trailing profit or buy in the rare case it jumps into DCA you want it to basically buy the best price, while this is not an option here I set ANDERSON with trailing=0  And a sell value gain at fixed level of only 1% and no trail and just hopes it jumps high, still even with the min volume to fill due to the price fluctuations You either need to disable 

I have seen MANY pairs in PT drop from +40% profit back to 5% etc.. get sold only to pup back up after perhaps a partial fill, might try bumppinhg min available volume to 130 or something, will try that....Thing is: buy walls move...
(Can post interesting screenshots, to prove the point, but won't) As with all posts and comments only being constructive here, but, maybe others have had similar experiences and a solution Is already being worked on)

Apparently you have not / don't care to read your PM's, or the decency to reply to a customer (who thought he could speek freely albeit a bit pissed off about something he was very supportive of and perhaps to emotionally involved in the lovely community etc so didn't expect that.) not personal but PT related , even apologised but, don't even think he read it...(my bad misread you on this a shame but couldn't care less, if you want to put your head into sand because your ego got a little bruised then, I respect that.  (Well.. no XD but I'm being polite here)

We still are customers and its your product. If you can't care well, then I don't. all good but since I love monies I posted this little freebie while i came 'aCROSS' it, I figured well why not...

Before I knew it yeah..this^ (F me i'm stupid..) as it all stems from finding non optimal solutions to a problem you have not even acknowledged, nor did I want to, bring it up, but here it is: It all boils down to that one trailing thing....

Which can be much improved upon, as it simply can't keep up with the rapid fluctuations. And setting a gain of 1, 2  hell do i set it to 1 and hope it spikes to 25 and sells in one go? See where i'm getting at? 

SPEED is the issue, hell even Binance doen't load the page of these pairs when they behave like that, you really need tradingview to see whats going on, currently making a custom 1 minute machine gun style killer for these pairs as its big money.

**Comment by taniman** [comment]
> Apparently you have not / don't care to read your PM's, or the decency to reply to a customer (who thought he could speek freely albeit a bit pissed off about something he was very supportive of and perhaps to emotionally involved in the lovely community etc so didn't expect that.) 

No idea what you are talking about here. Who are you? What's your username?

If you would care to check out our milestone instead of just venting you would see we have more selling strategies on the way.

We can't and won't build any suggestion into the bot. 
There are more options out there if this one does not meet your requirements.
