### ISSUE TITLE
[Feature Request] Market notifications

### ISSUE THREAD

**Issue by jSevyn** [taniman/profit-trailer#983]
Is it possible to get market notifications on the web interface if someone is using the feeder add on with PT? I know with the stock feeder, there are 3 market conditions - Bear, Boring and Bull but with Gnome's version which I used as a base, there are 5- Super Bear, Bear, Boring, Bull and Super Bull. Is there a way to have a notification similar to the SOM and SOMO notification on the web interface that we can activate by adding a line in the feeders market conditions area so we know which market feeder is currently using? And can we get these notifications including the Config, PW, SOM, SOMO and time to be fixed like the BTC balances at the top so it doesnt disappear when you scroll down the page?

**Comment by djcrypto75** [comment]
Notifications in dev, 2nd part I will look at.
