### ISSUE TITLE
Monitoring dont works in home network

### ISSUE THREAD

**Issue by Domber134** [taniman/profit-trailer#984]
Hello, ive set up Profit Trailer on my Linux Mini Pc and all is running fine. Console shows things as usual and localhost:8081/monitoring works fine.
Now i want to have a look at PT from my normal PC. So Chrome: 192.168.2.133:8081 and it shows the monitoring window without any information, completely empty. Only the background and Possible Buy Log, Pairs Log etc. is shown.

#Edit on my Handy it works

**Comment by djcrypto75** [comment]
Support request. No bug.
