### ISSUE TITLE
[Feature Request] Live charts with indicators / See what the bot sees

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#986]
I know, this is probably a huge request and not easy to do, but what if we had a live chart, created by the bot, that shows us, what the bot sees? Including the indicators, depending on what strategy and settings we are using and maybe the triggers as trigger lines?
That would make life soooo much easier, trying to fine tune different strategies and probably would save you a lot of time in support questions.
Maybe add it to the Profitable Buy Log as an icon next to each listing?
Again, this is big, I understand that, but but... pretty please? :)

**Comment by a7777777v** [comment]
This would be AMAZING. TradingView has code you can implement link here:
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

**Comment by djcrypto75** [comment]
Already requested earlier. Will add some charts in the future, but not TV.
