### ISSUE TITLE
[Feature Request] HODL 50%

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#989]
Ability to set in **Pairs + DCA**
**NANOBTC_min_sell_balance_percentage = 50**

This would only sell 50% of the current coin and hold the rest. This would also need to effect DCA sales too. 

Important: HODL coins should not effect/count against the **min_buy_balance_percentage** (the hold value could be large, and block total value / current balance %)

I've tested the above already, wish it worked.

**Comment by a7777777v** [comment]
Would also love to be able to specify a number to hold, like = 1000

**Comment by taniman** [comment]
see #496
