### ISSUE TITLE
[Feature Request] DCA to support Pair Specific _sell_value

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#990]
I would like to set in **DCA** (works in pairs just fine): 
**NANOBTC_sell_value = 1000
NANOBTC_sell_trigger = 1000**

I'm looking only to sell specific coins (hodl ones) when they reach a certain % even if they have entered into DCA at some point.

**Comment by alexdolli** [comment]
It would be even nicer, if we could specify how many of a particular coin we want to hold and are not available for trading for the bot. Anything above the specified amount, have at it.

**Comment by a7777777v** [comment]
+ 1 to specify coin number to hold

**Comment by YoJeff** [comment]
#222 dup
