### ISSUE TITLE
PT does not buy anything :/

### ISSUE THREAD

**Issue by flaj123** [taniman/profit-trailer#991]
Hello, from about a week when I updated PT, he stopped buying. I am asking for advice if it's my fault (change in settings) or regardless of me.

PAIRS: 
MARKET = BTC
ALL_trading_enabled = true
ALL_enabled_pairs= ALL
ALL_max_cost = 0.125     (cos my budget is 0.13)
ALL_min_buy_balance = 0.0015
ALL_min_buy_volume = 500
ALL_min_buy_price = 0.000000500
ALL_max_trading_pairs = 50
 
ALL_max_buy_spread = 1

#Buy
ALL_buy_strategy = LOWBB
ALL_buy_value = -2
ALL_trailing_buy = 0.4

#Sell
ALL_sell_strategy = GAIN
ALL_sell_value = 0.75
ALL_trailing_profit = 0.2

All_stop_loss_trigger = 0
ALL_stop_loss_timeout = 0
ALL_panic_sell_enabled = false

ALL_DCA_enabled = true
ALL_DCA_enabled = -1.5

ALL_sell_only_mode = false

ALL_btc_price_drop_trigger = 0
ALL_btc_price_drop_recover_trigger = 0

ALL_btc_price_rise_trigger = 0
ALL_btc_price_rise_recover_trigger = 0

ALL_consecutive_buy_trigger = 0
ALL_consecutive_sell_trigger = 0

ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0

**Comment by DeWim** [comment]
ALL_max_cost = 0.125 (cos my budget is 0.13)
ALL_min_buy_balance = 0.0015

You are telling the bot to use 0.125 of your ballance to buy 1 pair and leave 0.0015 of your balance untouched. Change to:

ALL_max_cost = 0.0015 (or 0.0025 if on binance))
ALL_min_buy_balance = 0

ALL_DCA_enabled = true
ALL_DCA_enabled = -1.5

ALL_DCA_enabled shoould be only one off 'true/false/negative number.
true = Every pair will go to DCA as soon as its bought
false = DCA disabled
Negetaive number = go to DCA as soon as the pair dropped for instance -1.5%
So you have to get rid of one of your dca lines.

Hope this helps.

**Comment by BrotherMunk** [comment]
Try all max cost as a % such as 5.

**Comment by DeWim** [comment]
'ALL_max_cost' is a value
if you want to use percentages it has to be 'ALL_max_cost_percentage'

**Comment by YoJeff** [comment]
The discord channel is for support/questions.   This is for bugs only.
https://wiki.profittrailer.io/doku.php/start
