### ISSUE TITLE
Feature Request: Instead of detecting consecutive buy orders, how about detecting consecutive trailing coins...

### ISSUE THREAD

**Issue by cyberena** [taniman/profit-trailer#992]
When a market is crashing, seems like every coin gets trailed.  Was thinking if we could set it so if more then X number of  coins are trailing at same time or whatever, to go in SOM.

This should work for all exchanges since its detected on the bots side and does not require binance to interact with to know.

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the features github here:  https://github.com/taniman/profit-trailer-enhancements/issues
