### ISSUE TITLE
Telegram bot does not receive messages

### ISSUE THREAD

**Issue by ManuGithu** [taniman/profit-trailer#993]
PT version: v.1.2.6.14
OS: Linux Debian 9

I have a Telegram bot that is correctly configured. A simple python application can send messages to the bot using the bot token and chat id.

However, I cannot get any message sent from PT. My application.properties file looks like:
telegram.botToken = MyToken
telegram.chatId = MyID
telegram.postNewOrders = true
telegram.notificationOnStartup = true
telegram.notificationOnShutdown = true

When I access http://MyIP:8081/settings/telegramTestMessage I can see in the log:
TelegramService - Telegram message sent - ManuPT - Your telegram is setup correctly

But the telegram bot does not receive anything. There is also no msg when PT starts or stop.

**Comment by Shaping** [comment]
I am having exactly the same problem, and I've verified via a sendmessage URL that a test message can be sent to my bot.

**Comment by ManuGithu** [comment]
Just installed v.1.2.6.15 and it now works

**Comment by YoJeff** [comment]
Lets call this fixed.
