### ISSUE TITLE
Bot Failed to Recognize Manual Sale

### ISSUE THREAD

**Issue by vividmemes** [taniman/profit-trailer#994]
I've only ever done a handful of manual sales while running PT, but the bot has always successfully recognized their occurrence. For this sale, although the circumstances remained the same (PT running, balance recognized on Binance), PT did not input the sale into its log and my sales log/TCV/TPV numbers seem to be off as a result. Attached is a screenshot of the recognized sales for that coin on that date (in yellow) as they appear in the sales log, alongside the total sales that were recorded in my Binance trade history.
![missingsaless](https://user-images.githubusercontent.com/36136937/35781161-4e6f5bd0-09b4-11e8-838e-e764fe8a9cb0.png)

**Comment by YoJeff** [comment]
Manual sales and pending sales do not currently make it into the sales log.   This is known and by design.   It's being discussed.

The bot is not supposed to be a window into your manual trading.   It's not the official record of your sales.
