### ISSUE TITLE
Json backup not working as intended

### ISSUE THREAD

**Issue by DeWim** [taniman/profit-trailer#996]
The backup funcionality makes 6 backups in the backup folder and then keeps replacing the newes one instead of the oldest one which makes it that there is only 1 usable backup file. Look at the timestamps in the screenshot. This is running the bot on ubuntu vps.

![2018-02-05](https://user-images.githubusercontent.com/27749343/35783874-588aa128-0a0f-11e8-8629-b0814b385fab.png)

**Comment by DeWim** [comment]
Couple of day further in. Notice the first 5 files staying exactly the same as in the previous screen only the 6th one being updated.
![image](https://user-images.githubusercontent.com/27749343/35929603-279aace8-0c30-11e8-9261-da6359573219.png)

**Comment by DeWim** [comment]
Look at the time and date stamps of the files in the latest screen. There is a 2 day diference between the first 5 and the last one.

So what the bot is doing now is deleting the newest backup and making a new backup which makes it so there is only 1 usable backup since the first 5 are outdated.

What the bot should be doing is deleteing the oldest backup instead of the newest and then make a new backup. That way there are always 6 plausible backups to choose from as it was decribed in the release notes 'Create a backup folder with 5 latests backups (once per minute)'

**Comment by YoJeff** [comment]
Odd, I have one that's has old files like this.    If you delete the backup directory it appears to work correctly (at least during my few test restarts).     Might be a gremlin in there somewhere.   Flaggin as a bug.

**Comment by ingeniumdesign** [comment]
i have the same again.
now i del. all file, its works for one round perfect, but now the same bug :/

**Comment by taniman** [comment]
lol. nice catch. will fix

**Comment by cvthub** [comment]
fixed for next release.
