### ISSUE TITLE
Feature request ?

### ISSUE THREAD

**Issue by BlitzKC** [taniman/profit-trailer#997]
You know how sometimes your bag sits at +1% what if the bot would double-down and throw it up even more positive, then sell?  Many times I see the bot flurting with the sell trigger.  Sometimes it flirts with the sell trigger for hours...

**Comment by taniman** [comment]
a double down would not make the % go up. your logic is flawed. when you buy. you pay fees and also have to dea lwith a spread. this all causes the % to go down not up.
