### ISSUE TITLE
Profit trailer warning an illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by Iandesanta** [taniman/profit-trailer#998]
Hi! Can someone help me? I try to install Profit trailer WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/IanDeSanta/Desktop/ProfitTrailer/ProfitTrailer.jar!/BOOT-INF/lib/spring-core-4.3.7.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
9.0.4
2018-02-05 13:03:32 ERROR Application - Please install java 8
MBP-de-Ian:ProfitTrailer IanDeSanta$ 

I don't get it because I have installed java 8
(build 1.8.0_162-b12  

Do you have any plan what can cause the issue?

**Comment by YoJeff** [comment]
You may have installed 8, but it's not using 8.    Please use support -- this is not a bug.
